### ISSUE TITLE
Remove pdal::Options, refactor pdal::Option

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#1000]
PDAL options do not need to be a tree of things. It is confusing as currently implemented and causes plenty of trouble. We will start cleaning things up by removing pdal::Options and eliminating the ability for an Option to be arbitrary depth. They will be a single, flat map after this effort.

**Comment by abellgithub** [comment]
Fixed with 88c4ca595a9a88ef53b4bfde5d1bb22984f3734b, 987624451f94374577b544e0a848b055c5a4ae5e,
e9d0ef84b5d43cf07d7b1651f0d86fcbe802e6a0,
25be81d8315bc07af8717c2a83ee430ca1d271d1
