### ISSUE TITLE
Refactor range filter options

### ISSUE THREAD

**Issue by chambbj** [PDAL/PDAL#1001]
In support of #1000, refactor range filter options.

For example, via the command line

```
--filters.range.limits=X(10:20),Y[:30],Z[40:],Intensity(50:60]
```

or via XML

```
<Filter type="filters.range">
    <Option name="limits">
        X(10:20),Y[:30],Z[40:],Intensity(50,60]
    </Option>
</Filter>
```

In each case, the range specified in the form

```
dimension-name(lower-bound : upper-bound)
dimension-name(lower-bound : upper-bound]
dimension-name[lower-bound : upper-bound)
dimension-name[lower-bound : upper-bound]
```

With parenthesis indicating exclusive bounds, and square brackets indicating inclusive bounds.

A missing upper or lower bound, e.g., `(: upper bound)`, indicates that the bound should be taken at infinity.

We could make this very [PostgreSQL-like](http://www.postgresql.org/docs/9.2/static/rangetypes.html).

This should be an improvement over the current solution, where range options cannot be specified via the command line and the XML equivalent (no inclusive bounds) would be something like

```
<Filter type="filters.range">
    <Option name="dimension">
        X
        <Options>
            <Option name="min">10</Option>
            <Option name="max">20</Option>
        </Options>
    </Option>
    <Option name="dimension">
        Y
        <Options>
            <Option name="max">30</Option>
        </Options>
    </Option>
    <Option name="dimension">
        Z
        <Options>
            <Option name="min">40</Option>
        </Options>
    </Option>
    <Option name="dimension">
        Intensity
        <Options>
            <Option name="min">50</Option>
            <Option name="max">60</Option>
        </Options>
    </Option>
</Filter>
```

**Comment by chambbj** [comment]
We should also consider lists of values to filter on, which would be especially useful for discrete things like classification labels.

```
dimension-name(value1, value2, ..., valueN)
```

**Comment by chambbj** [comment]
Oh yeah, and you may want boolean operators. Right now, it's all just OR'd together.

Perhaps...

```
--filters.range.limits=X[:10],Y(2:8) --filters.range.comparison=[ AND | OR | XOR...]
```

I suppose that

```
--filters.range.limits=(X[:10] && Y(2:8)) || Z[100:]
```

(or similar) would be nice too, but I'm not sure I'm motivated enough, and maybe you'd like to [learn some python](http://www.pdal.io/stages/filters.programmable.html) anyway.

**Comment by landersson** [comment]
A simple "--filters.range.invert=true" option that discards rather than keeps the matching points would be very useful to me.

**Comment by abellgithub** [comment]
Negation now supported by adding a '!' character in front of a range specification.

**Comment by landersson** [comment]
Thanks. I just realized that range conditions are ORed rather than ANDed together, which makes ranges less useful in my current use case. Anyway, I can just use the 'programmable' filter instead.

**Comment by abellgithub** [comment]
Is that how it should be?  That seems unhelpful.  @hobu, @chambbj ?

**Comment by chambbj** [comment]
@abellgithub @landersson I had considered more complex logic (see earlier comment in this thread). Initially, I thought I'd go ahead and add the AND option to go along with the default OR, and that may still not be a bad idea. Only reason I didn't was because I could see that leading to implementation of a full boolean algebra. I just felt like that would get away from the simplicity of something you'd like to do on the command line. (Also read as, OR was good enough for me.)

I guess the ideal way forward would be to

1. First, add AND as an optional switch, applies to all ranges, this would be a trivial change.

~~~
--filters.range.limits=X[:10],Y(2:8) --filters.range.comparison=AND  // OR would remain the default
~~~

2. Later on, add the ability to parse more complex boolean expressions. I don't think this would be all that hard, I just don't have the bandwidth for it presently.

~~~
--filters.range.limits=~(X~[0:1] | Y~[0:1])
--filters.range.limits=X[0:1] & Y[0:1]
--filters.range.limits=X[0:1] | (Y~[0:1] & Z[0:1])
~~~

**Comment by hobu** [comment]
:+1: to AND and OR support.

The reason @mpgerlek and I end at `filters.programmable` was we didn't want to make our own complete expression language (first attempt was boost::spirit), and it's just easier to pass off to Python because people eventually want more and more. This kind of creep probably stops for this particular filter, but one could imagine a "simple algebra" one next...

I don't know how we strike the right balance. `filters.range` is convenient and useful. `filters.programmable` is a bit of a pain to use and certainly slower. Each has their own strengths. My instinct is we err toward usefulness until it becomes too much to manage.

**Comment by abellgithub** [comment]
On Wed, Oct 21, 2015 at 2:03 PM, Howard Butler <notifications@github.com>
wrote:

> [image: :+1:] to AND and OR support.
>
> The reason @mpgerlek <https://github.com/mpgerlek> and I end at
> filters.programmable was we didn't want to make our own complete
> expression language (first attempt was boost::spirit), and it's just easier
> to pass off to Python because people eventually want more and more. This
> kind of creep probably stops for this particular filter, but one could
> imagine a "simple algebra" one next...
>
> I don't know how we strike the right balance. filters.range is convenient
> and useful. filters.programmable is a bit of a pain to use and certainly
> slower. Each has their own strengths. My instinct is we err toward
> usefulness until it becomes too much to manage.
>
I was going to start this, but I wanted to field thoughts.  I don't think
it will take too much to implement some more boolean logic.  If we want to
undo the change I made last night in the process and do something more
general, that's fine too.  But we could also just combine it with the && ||
and () stuff.  It's really about syntactic preference.

-- 
Andrew Bell
andrew.bell.ia@gmail.com

**Comment by hobu** [comment]
>  I don't think it will take too much to implement some more boolean logic. 

More expression logic and capability is fine with me. I'm just nervous about too many "little languages" getting spread allover the place.
