### ISSUE TITLE
OSGeo4W CMake configure files fail with non-existent directories

### ISSUE THREAD

**Issue by gadomski** [PDAL/PDAL#1006]
On Windoze 7, Visual Studio 11 2012 Win64, CMake 3.3.2, OSGeo4W64:

```
CMake Error at C:/OSGeo4W64/lib/pdal/cmake/PDALConfig.cmake:11 (message):
  File or directory C:/osgeo-target/pdal/include referenced by variable _foo
  does not exist !
Call Stack (most recent call first):
  C:/OSGeo4W64/lib/pdal/cmake/PDALConfig.cmake:34 (set_and_check)
  CMakeLists.txt:4 (find_package)
```

My `PDALConfig.cmake` that came with OSGeo4W includes the following on line 33:

``` cmake
foreach(_dir C:/osgeo-target/pdal/include;c:/OSGeo4W64/include/boost-1_56)
```

That `C:/osgeo-target/...` is blowing things up, I think. @chambbj I believe you're "maintainer" of the OSGeo4W, is this a PDAL bug, or something I'm supposed to have done with my OSGeo4W setup?

**Comment by chambbj** [comment]
Nope. Sounds like a bug. I'll have to take a look at how it gets
configured/released.

**Comment by hobu** [comment]
reopen if still an issue.
