### ISSUE TITLE
Precision Loss in Outlier Removal

### ISSUE THREAD

**Issue by landersson** [PDAL/PDAL#1008]
Hi, I'm using PDAL to do outlier removal on large las files. The command I run is something like this:

pdal translate -i in.las -o out.las -f statisticaloutlier --filters.statisticaloutlier.mean_k=56 --filters.statisticaloutlier.multiplier=2 --filters.statisticaloutlier.extract=true

The outlier removal seems to work fine, but I've noticed that all points in the output cloud seem to be slightly, randomly shifted around compared to the input cloud. I thought this was related to PCL processing, but even a no-op command like:

pdal translate -i in.las -o out.las

seems to shift the points... Any idea why, or suggestions for how to fix it?

**Comment by abellgithub** [comment]
On Sun, Oct 18, 2015 at 7:59 PM, landersson <notifications@github.com>
wrote:

> Hi, I'm using PDAL to do outlier removal on large las files. The command I
> run is something like this:
>
> pdal translate -i in.las -o out.las -f statisticaloutlier
> --filters.statisticaloutlier.mean_k=56
> --filters.statisticaloutlier.multiplier=2
> --filters.statisticaloutlier.extract=true
>
> The outlier removal seems to work fine, but I've noticed that all points
> in the output cloud seem to be slightly, randomly shifted around compared
> to the input cloud. I thought this was related to PCL processing, but even
> a no-op command like:
>
> pdal translate -i in.las -o out.las
>
> seems to shift the points... Any idea why, or suggestions for how to fix
> it?
>
See the writers.las documentation for information about precision.  PDAL
doesn't preserve precision unless you request it.  You can set the scale
factors for output explicitly (scale_x, scale_y, scale_z), or you can
forward them from the input file (forward=scale).

-- 
Andrew Bell
andrew.bell.ia@gmail.com

**Comment by landersson** [comment]
Ok, adding "--writers.las.forward=scale,offset" to the command line fixes my problem. Thanks!
