### ISSUE TITLE
PDAL: Merge 'Too many open files'

### ISSUE THREAD

**Issue by rolanddu** [PDAL/PDAL#1017]
I receive this error when I attempt to merge a large number of las files.

'PDAL: Unable to create open stream for 'my500.las' with error 'Too many open files''

How many open files is too many?  Also, is there anything I can do to increase this limit?  I have already attempted to merge 1/2 the files at a time.

Thanks for any advice.
Roland

**Comment by hobu** [comment]
How many files are you trying to merge at once? `filters.merge` currently keeps all files open while it operates.

**Comment by abellgithub** [comment]
On Wed, Oct 28, 2015 at 4:06 PM, rolanddu <notifications@github.com> wrote:

> I receive this error when I attempt to merge a large number of las files.
>
> 'PDAL: Unable to create open stream for 'my500.las' with error 'Too many
> open files''
>
> How many open files is too many? Also, is there anything I can do to
> increase this limit? I have already attempted to merge 1/2 the files at a
> time.
>
The limit on the number of open files is operating-system dependent.  On
linux you can usually change the limit by editing something
/etc/security/limits.conf.  Search the web for information regarding your
particular OS.

-- 
Andrew Bell
andrew.bell.ia@gmail.com

**Comment by rolanddu** [comment]
I am using Windows 10 (OSGeo4w build) and I am trying to merge around 800 .las files.

**Comment by abellgithub** [comment]
From some Googling it looks like the Windows limit is 512.

On Wed, Oct 28, 2015 at 4:42 PM, rolanddu <notifications@github.com> wrote:

> I am using Windows 10 (OSGeo4w build) and I am trying to merge around 800
> .las files.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PDAL/PDAL/issues/1017#issuecomment-152003003>.
>



-- 
Andrew Bell
andrew.bell.ia@gmail.com

**Comment by hobu** [comment]
I believe this one has now been fixed, but I don't know the specific SHA. Please reopen if it is still an issue once you have an updated PDAL to test.

**Comment by abellgithub** [comment]
Not fixed.
