### ISSUE TITLE
`readers.nitf` does not recognize `./test/data/nitf/write_test1.ntf`

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#1025]
```
pdal info ./test/data/nitf/write_test1.ntf
PDAL: Unable to determine NITF file version
```

**Comment by abellgithub** [comment]
@hobu: Do you know where this file came from?  Any reason why we think it should work?

**Comment by hobu** [comment]
I think PDAL itself wrote it, but I'm not sure.

**Comment by abellgithub** [comment]
This error comes directly from a failure of the NITRO call to fetch the file version.  Unless we have some information that can tell us that this is indeed a valid NITF file, I think we should just remove the file and close the ticket.
