### ISSUE TITLE
Warning for missing GeoTiff rather than empty SRS string?

### ISSUE THREAD

**Issue by connormanning** [PDAL/PDAL#1028]
Currently, things that return an SRS give an empty string if GeoTiff is not installed.  For example `pdal info --metadata`, or programmatically invoking `QuickInfo`.

There was some discussion on warning the user that GeoTiff is missing in this case.  Maybe at run-time with a warning string, or at configure time notifying the user that SRS strings will be unpopulated (and any other related side effects).  For now it's not obvious how to resolve the issue if you're seeing empty SRS strings, and if you're not very knowledgable about what each optional PDAL dependency does.

**Comment by hobu** [comment]
I think this should be a warning in the output. `readers.las` knows there's SRS information if the VLRs exist, but if we don't have libgeotiff, we can't interpret them. In that situation, we should output the equivalent of "hey, here's something here, but you're not configured to get it"

**Comment by abellgithub** [comment]
So I put something in for this.  It prints a message.  Not sure, though, if we should do something fancier.  Should the the output say something where the SRS is?  Not sure I like that because output is JSON and we'd break that.  Thoughts?

**Comment by hobu** [comment]
I see @223cedddedc5639932d391ede2ebfd13c80e575d

I don't think this is an error condition either. I'm conflicted what to do.

**Comment by abellgithub** [comment]
It doesn't exit.  Just prints a message.  Maybe I'm not understanding.

**Comment by hobu** [comment]
oops, I read that it was throwing.

**Comment by abellgithub** [comment]
Fixed sufficiently by above referenced change.
