### ISSUE TITLE
Readers and writers that expect filename provide poor feedback when it's missing

### ISSUE THREAD

**Issue by abellgithub** [PDAL/PDAL#1034]
If the 'filename' option is missing, a reader/writer will still attempt to open a file and you'll end up with:

`C++ exception with description "File '' not found" thrown in the test body.`

It would be better if you were told explicitly that the 'filename' option was not provided.

**Comment by hobu** [comment]
This should now be resolved with the reimplementation of program args. Please reopen if it is still an issue.
