### ISSUE TITLE
`pdal info --summary` broken for RxpReader

### ISSUE THREAD

**Issue by gadomski** [PDAL/PDAL#1038]
NB this is a possible duplicate of #1012, @abellgithub feel free to close this if it is.

`pdal info` works just fine:

``` bash
$ pdal info test/data/0916_2014_girdwood35.rxp | head
{
  "filename": "test/data/0916_2014_girdwood35.rxp",
  "pdal_version": "1.0.1 (git-version: 1394a1)",
  "stats":
  {
    "statistic":
    [
      {
        "average": 0.407355579,
        "count": 257576,
```

But `pdal info --summary` is bunk:

``` bash
$ pdal info --summary test/data/0916_2014_girdwood35.rxp
{
  "filename": "test/data/0916_2014_girdwood35.rxp",
  "pdal_version": "1.0.1 (git-version: 1394a1)",
  "summary":
  {
    "bounds":
    {
      "X":
      {
        "max": -1.797693135e+308,
        "min": 1.797693135e+308
      },
      "Y":
      {
        "max": -1.797693135e+308,
        "min": 1.797693135e+308
      },
      "Z":
      {
        "max": -1.797693135e+308,
        "min": 1.797693135e+308
      }
    },
    "dimensions": "",
    "num_points": 0,
    "spatial_reference": ""
  }
}
```

I'm guessing this has to do with the fact that the `RxpReader` doesn't know anything about its points until it reads them, since rxp is a streaming format with no concept of a "header" or anything. If that is the case, it's an open question what the appropriate response of `pdal info --summary` should be — either bomb, saying summary doesn't work with this reader, or read all the points then summarize (maybe with a warning message about what it's doing)?

(if we used issue priority levels, this one would be tagged "low priority")

**Comment by abellgithub** [comment]
You have to implement inspect() to get output.  `pdal info --summary` should certainly tell you if it can't do a summary, or it should do things the hard way and report that.  The way it is now is bad.

**Comment by gadomski** [comment]
Is `inspect` expected to fill all member variables of `QuickInfo`? I.e. if
I can't fill m_pointCount without reading the whole file, what should I do?
Read the whole file and fill it in? Leave `inspect` unimplemented?

On Mon, Nov 16, 2015 at 11:25 AM Andrew Bell <notifications@github.com>
wrote:

> You have to implement inspect() to get output. pdal info --summary should
> certainly tell you if it can't do a summary, or it should do things the
> hard way and report that. The way it is now is bad.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PDAL/PDAL/issues/1038#issuecomment-157107977>.
>
-- 
Pete Gadomski
Physical Scientist
Cold Regions Research and Engineering Laboratory
530.440.4630
pete.gadomski@gmail.com

**Comment by abellgithub** [comment]
On Mon, Nov 16, 2015 at 7:55 PM, Pete Gadomski <notifications@github.com>
wrote:

> Is `inspect` expected to fill all member variables of `QuickInfo`? I.e. if
> I can't fill m_pointCount without reading the whole file, what should I do?
> Read the whole file and fill it in? Leave `inspect` unimplemented?
>

Up to you.  There are no rules at this point.  Wish I could tell you more.

-- 
Andrew Bell
andrew.bell.ia@gmail.com

**Comment by abellgithub** [comment]
I updated `pdal info --summary`.  This won't make good data appear, but it should make bad data go away.  Can you check @gadomski ?  I don't have Rivlib.

**Comment by gadomski** [comment]
@abellgithub works for me, thanks.

```
$ PDAL_DRIVER_PATH=build/lib build/bin/pdal info --summary plugins/rxp/test/data/130501_232206_cut.rxp
PDAL: No summary data available for 'plugins/rxp/test/data/130501_232206_cut.rxp'.
```
