### ISSUE TITLE
readers.las doc needs examples and rewording

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#1044]
The front matter paragraph is super dense, expects intimate knowledge of LAS formats, and doesn't explain they why of any of what is being said.

We need to link to laz-perf and LASzip, and we need some verbiage that explains why there's two possibilities. 

http://www.pdal.io/stages/readers.las.html

**Comment by abellgithub** [comment]
Well, there was an assumption that if someone was using the LAS reader, they knew LAS, but I can try to make it more simple.

**Comment by abellgithub** [comment]
What should we say about why there are two possibilities for LAZ decompression WRT PDAL?

**Comment by hobu** [comment]
> What should we say about why there are two possibilities for LAZ decompression WRT PDAL?

LASzip is the primary LAZ implementation, with the widest support for all LAZ versions. laz-perf is used by the database drivers (:ref:`writers.oci` and :ref:`readers.sqlite`) and by JavaScript implementations http://plas.io and http://potree.org. laz-perf *may* be faster to decompress in C++, and it is certainly faster than Emscripten-compiled LASzip. You can find laz-perf library at https://github.com/verma/laz-perf

**Comment by abellgithub** [comment]
@hobu, change if you don't like it, but I guess I thought a link to LAZperf would allow people to find details if they wanted it.  Perhaps the LAZperf github stuff should be updated?  I'll check to make sure the DB drivers mention LAZperf.
