### ISSUE TITLE
readers.pgpointcloud get wrong pcid

### ISSUE THREAD

**Issue by redheli** [PDAL/PDAL#1046]
readers.pgpointcloud use below sql to get pcid, but it may return the result with multi rows. PgReader only take the first one.

SELECT PC_Typmod_Pcid(a.atttypmod) AS pcid FROM pg_class c, pg_attribute a WHERE c.relname = table_name AND a.attname = column_name;

to reproduce :
DROP TABLE patches;
CREATE TABLE patches (id SERIAL PRIMARY KEY,pa PCPATCH(1));
DROP TABLE patches2;
CREATE TABLE patches2 (id SERIAL PRIMARY KEY,pa PCPATCH(2));
DROP TABLE patches3;
CREATE TABLE patches3(id SERIAL PRIMARY KEY,pa PCPATCH(3));

SELECT PC_Typmod_Pcid(a.atttypmod) AS pcid FROM pg_class c, pg_attribute a WHERE c.relname = 'patches' AND a.attname = 'pa';

**Comment by hobu** [comment]
If you can suggest an update to the PDAL drivers, we will be happy to include it. I'm unclear from the scenario you present how PDAL can be modified to handle your situation.

**Comment by redheli** [comment]
use below sql can solve my problem, just add one condition a.attrelid=c.relfilenode :
SELECT PC_Typmod_Pcid(a.atttypmod) AS pcid FROM pg_class c, pg_attribute a WHERE c.relname = 'patches' AND a.attname = 'pa' AND a.attrelid=c.relfilenode ;

shall I create one PR?

**Comment by hobu** [comment]
yes, please make a PR
