### ISSUE TITLE
PluginManager::createObject not thread safe

### ISSUE THREAD

**Issue by redheli** [PDAL/PDAL#1048]
when call createObject in mult thread, it crash.
shall add mutex when m_exactMatchMap insert data.

**Comment by abellgithub** [comment]
PDAL is not thread-safe.

**Comment by hobu** [comment]
> PDAL is not thread-safe.

But it isn't actively thread unsafe. :smile:

**Comment by abellgithub** [comment]
Well, yes.  But you have to be really, really careful if you're going to use PDAL in a threaded environment.  There are lots of ways/places that things could break.  Not sure how much value there is in changing something like this.

**Comment by hobu** [comment]
I think thread safety for PluginManager and StageFactory seems reasonable. Any other object type, maybe not so much. Thoughts?
