### ISSUE TITLE
Support For Storing Extra Dimensions

### ISSUE THREAD

**Issue by rolanddu** [PDAL/PDAL#1057]
I have aerial imagery that has 4 bands, where the 4th band represents light in the near infrared portion of the spectrum.  Is there a way for me to store all four of these bands in a single LAS file?  ...otherwise I need to create two LAS files for each location... one representing true color and the other representing false color IR.

**Comment by abellgithub** [comment]
If you use LAS format 1.4 for output, you can use point format 8, which contains a field for NIR.  You can also use the writer.las "extra_dims" option for earlier LAS formats, but there is no general metadata information that will ride with your file to indicate that you have placed NIR data in the point record -- you would have to let the receiver of the file know by an external note or some such.
