### ISSUE TITLE
Height filter uses unnecessary custom dimension

### ISSUE THREAD

**Issue by abellgithub** [PDAL/PDAL#1077]
Rather than adding the "Height" dimension, we should either use the existing HeightAboveGround dimension or add another.

**Comment by hobu** [comment]
Easy to get into the weeds, but I think just a dimension called `Height` should be enough -- not HeightAboveGround.

**Comment by abellgithub** [comment]
On Tue, Dec 29, 2015 at 12:22 PM, Howard Butler <notifications@github.com>
wrote:

> Easy to get into the weeds, but I think just a dimension called Height
> should be enough -- not HeightAboveGround.
>

HeightAboveGround was added for the HeightAboveGround kernel.  Not sure if
it represents something different from that returned by the Height filter.

-- 
Andrew Bell
andrew.bell.ia@gmail.com

**Comment by hobu** [comment]
> Not sure if it represents something different from that returned by the Height filter.

That's what I meant by the weeds. It certainly could mean something different than just a generic Height, but maybe the nuance isn't enough to really care.

**Comment by chambbj** [comment]
Honestly, I probably just forgot that the HeightAboveGround dimension existed. I have no strong feelings. There are many things you could call this - AboveGroundLevel and NormalizedHeights are both common alternatives. I don't know of any formats that natively support the dimension either, and you can effectively rename it to whatever you want with ferry anyway.

**Comment by hobu** [comment]
Implemented in #1108
