### ISSUE TITLE
Kernel extra options parser treats stage names with digits as invalid

### ISSUE THREAD

**Issue by chambbj** [PDAL/PDAL#1081]
See https://github.com/PDAL/PDAL/blob/master/src/Kernel.cpp#L257.

@abellgithub Any reason we would be doing this on purpose? Unless I'm overlooking something, I think we are safe changing this to `return std::islower(c) || std::isdigit(c)`. Or maybe just add another predicate for the stage name, since this rule would still be valid for stage type.

This matters because all of the Points2Grid (p2g) writer options are falling on the floor when entered as CLI options.

**Comment by abellgithub** [comment]
Seems fine, though I'd like to see us exclude digits as the first character.  Guess when I did it I didn't remember p2g and nobody has complained.  You might look over the history.  I would, but don't have time this morning.  If it can wait until next week, I'd be happy to.

**Comment by chambbj** [comment]
Sounds reasonable. I may go ahead and merge #1083 just to get p2g options working again in master, and will look into your other suggestions as a follow-on.
