### ISSUE TITLE
Add `geographic` flag to info output

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#1089]
When there's a coordinate system on the data, we can use GDAL to tell us if it is geographic or not. We should output this flag so downstream processing can pivot based on it.

**Comment by hobu** [comment]
This makes me wonder if `spatialreference` shouldn't be a separate JSON/metadata object instead of having it flat.

This:

```
{"spatialreference":
  {'"horizontal":"PROJCS...",
   "vertical": "VERT_CS...",
   "geographic" : true,
   "compound" : "COMP_CS...",
   "units" : {"horizontal":"m", "vertical":"us-ft"},
   "geocentric": false,
  }
}
```

**Comment by msmitherdc** [comment]
That makes a lot of sense. I like it a lot.

**Comment by hobu** [comment]
To transition, I think we should make this object be `srs`, and leave the other items that have been sprinkled into the metadata alone.

**Comment by msmitherdc** [comment]
could there also be a `"complete": true, ` option (or something) to indicate whether the projection is valid for the coordinates? Thats 3/4 of our battle, determining whether the projection is valid and correct for the data. Maybe by determining whether the coords back projection to valid geographic coords? I realize there are many ways to go wrong here but looking for some simple ways to flag issues.

**Comment by busstoptaktik** [comment]
I think I understand the usefulness of this, but I think the name
"validated" would make more sense.

Also, if I understand the use case correctly, care should be taken NOT to
propagate this flag to derived datasets where the validation might have
become invalid, so to speak.

I may misunderstand the case, but I can imagine cases where this may really
create more confusion than it eliminates.
Den 24/01/2016 18.09 skrev "Michael D. Smith" <notifications@github.com>:

**Comment by hobu** [comment]
> could there also be a `"complete": true`

Really, really tough to do this well. I think we can return a `minlong`, `maxlong`, `minlat`, and `maxlat` bounding box, which you might be able to use for validation yourself. If we can do that, what should we do in the case we can't transform to geographic for whatever reason (no SRS, not on earth)?

**Comment by msmitherdc** [comment]
I think if you can't convert to min/max Lat/Lon then complete = false. It's not saying it's not valid just that it's not complete enough to validate.

**Comment by abellgithub** [comment]
Validity is in the eye of the beholder.  I'm not sure this kind of
functionality belongs in PDAL.  If it's needed for GRiD, perhaps it should
go there?

Some of the information in the structure is duplicate.  For example, the
projection can't be both geocentric and geographic.  I think we should
spend some time thinking about how to split apart the WKT and make it
useful if that's what we're talking about.

On Sun, Jan 24, 2016 at 6:08 PM, Michael D. Smith <notifications@github.com>
wrote:

> I think if you can't convert to min/max Lat/Lon then complete = false.
> It's not saying it's not valid just that it's not complete enough to
> validate.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PDAL/PDAL/issues/1089#issuecomment-174355190>.
>



-- 
Andrew Bell
andrew.bell.ia@gmail.com

**Comment by hobu** [comment]
I don't think validity of content, where we were to check if the `point coordinates + srs == valid`, belongs in PDAL. That's gotta be the caller's responsibility.

>   I think we should spend some time thinking about how to split apart the WKT and make it
useful if that's what we're talking about.

Yeah, I don't know how far down this road to go. If you care about parameters and such, you can head to GDAL/OSR to get what you need. I think it's about providing just enough convenience (is it geographic, what's the geographic bounds of the data, is it geocentric) so people don't have to jump to GDAL and a scripting language if they're doing [`jsawk`-style] (https://github.com/micha/jsawk) JSON chopping from the command line.

> For example, the projection can't be both geocentric and geographic.

But it can be !geocentric and !geographic

**Comment by hobu** [comment]
Added in #1103
