### ISSUE TITLE
problems with dropping tables with pgpointcloud driver

### ISSUE THREAD

**Issue by smathermather** [PDAL/PDAL#1098]
Using a table name like 54001640PAN_heightasz_0-1.5 loads fine, but does not reload fine, resulting in an error like:

```LINE 1: DROP TABLE IF EXISTS 54001640PAN_heightasz_0-1.5```
I think this is an issue with escaping the name appropriately. I get a similar error in psql if I fail to quote my table name:
```
gisuser=# drop table 54001640PAN_heightasz_0-1.5;
ERROR:  syntax error at or near "54001640"
LINE 1: drop table 54001640PAN_heightasz_0-1.5
                   ^
gisuser=# drop table "54001640PAN_heightasz_0-1.5";
DROP TABLE
```

**Comment by hobu** [comment]
Done in #1098

**Comment by smathermather** [comment]
Awesome. Thanks!
