### ISSUE TITLE
Dimension Units

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#1104]
Like `Dimension::Type` and `Dimension::Id`, we need a `Dimension::Unit` and a Units enum

**Comment by snowskater** [comment]
I'm currently in need of units tied to my dimensions. Our algorithm requires that the points are in meters.
Manually testing against the SR is a little janky as 'meter' == 'metre' and in a particular instance my current dataset has a SpatialReference with no vertical units, just horizontal units. Thus I'm checking if both units are anything other than meter/metre/null and at least one is not null.

**Comment by hobu** [comment]
It would be possible to extract unit information for some drivers (say `readers.las`, but not for every situation and not for every dimension type. It is likely the default situation would still continue to be unitless even if we supported assignment of a unit type dimensions.

```
using namespace pdal::Dimension;

layout->registerDim(Id::X, Type::Double);
layout->registerDim(Id::Y, Type::Double);
layout->registerDim(Id::Z, Type::Double);

layout->registerUnit(Id::X, Unit::Degree);
layout->registerUnit(Id::Y, Unit::Degree);
layout->registerUnit(Id::Z, Unit::Meter);

if (layout->dimUnit(Id::Z) == Type::Meter)
{
    // convert or something
}
```
