### ISSUE TITLE
Generalize a Longitude normalization function

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#1106]
We have code sprinkled about in multiple places (SpatialReference, IceBridgeReader, Ilvis2Reader) that does longitude normalization. A single function would be nice.

https://github.com/PDAL/PDAL/commit/d492b91539111b46e4718329629c4bf4f914ae73#commitcomment-16016212

**Comment by abellgithub** [comment]
This was completed some time ago.  See Utils::normalizeLogngitude.
