### ISSUE TITLE
pdal::Metadata::addJson()

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#1109]
We have geometries and such that are already GeoJSON and I want to add them to metadata so they don't end up being escaped.

```
      {
        "bbox":
        {
          "maxx": -123.0689038,
          "maxy": 44.0515451,
          "maxz": 158.651448,
          "minx": -123.0734481,
          "miny": 44.04990077,
          "minz": 123.828048
        },
        "boundary": "{ \"type\": \"Polygon\", \"coordinates\": [ [ [ -123.07338097, 44.04990077 ], [ -123.07344805, 44.05144394 ], [ -123.06897075, 44.0515451 ], [ -123.06890378, 44.05000193 ], [ -123.07338097, 44.04990077 ] ] ] }"
      },

```

`boundary` in this case is already JSON, and I know that beforehand. I just want to add it to the Metadata tree. Is there a convenient way to do this with Metadata now? I don't see it...

**Comment by abellgithub** [comment]
This should now work by calling addWithType("boundary", jsondata, "json");
