### ISSUE TITLE
writers.derivative feature requests

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#1112]
1. It would be handy to specify a naming template and a list of `primitive_type` options and have them all be generated in a single run
2. I would like to specify the GDAL output format type as an option

**Comment by abellgithub** [comment]
What do you mean by a "naming template"?

**Comment by hobu** [comment]
Given some config like so...

```
"name": "/var/path/output",
"types": ["slope_d8", "aspect_fd", "profile_curvature", ...],
```

... and then after you run data through the filter...

```
output_slope_d8.tif
output_aspect_fd.tif 
output_profile_curvature.tif
```

... files would be written out to the file system at /var/path/

**Comment by hobu** [comment]
Added in #1141

**Comment by abellgithub** [comment]
#1141 Just does part 1) of this request.

**Comment by hobu** [comment]
Ok. I'll file a new ticket for that. Part #1 is good enough for 1.2 release.
