### ISSUE TITLE
pdal bash_completion install in /usr/etc if build with prefix

### ISSUE THREAD

**Issue by tigerfoot** [PDAL/PDAL#1115]
Building rpm with this cmake (extract)
```spec
%cmake \
    -G "Unix Makefiles"  \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=%{_prefix} \
    -DCMAKE_INSTALL_LIBDIR=%{_libdir} \
    -DPDAL_LIB_INSTALL_DIR=%{_libdir} \
    -DCMAKE_C_FLAGS_RELEASE="%{optflags} -fno-strict-aliasing -g -DNDEBUG" \
    -DCMAKE_CXX_FLAGS_RELEASE="%{optflags} -fno-strict-aliasing -g -DNDEBUG" \
    -DCMAKE_SKIP_INSTALL_RPATH=ON \
    -DCMAKE_SKIP_RPAH=ON \

```
Make pdal installing bash_completion pdal to /usr/etc/bash_completion.d/pdal

grep return me some information
```
ChangeLog:      * Sandro Santilli <strk@keybit.net> Install bash completion IFF /etc/bash_completion.d exists (05:09:04)
```cmake
365 # TODO: move under scripts/bash-completion ?
366 if (IS_DIRECTORY /etc/bash_completion.d)
367     install(FILES "${PROJECT_SOURCE_DIR}/scripts/bash-completion/pdal" DESTINATION "${CMAKE_INSTALL_PREFIX}/etc/bash_completion.d")
368 endif()
```
The assumption is not totally true on 100% of case.
During a rpm build (should be same for .deb packaging) if we don't BuildRequires: bash-completion
then /etc/bash_completion.d doesn't exist 
Most of the time we will use a prefix (/usr/) and not /usr/local under /usr /usr/etc doesn't exist.
Without being catastrophic (Forced to add bash-completion on build) the situation should be improved.

**Comment by hobu** [comment]
I made this an optional install in #1116.

**Comment by sebastic** [comment]
Ideally the bash-completions install directory is not hardcoded but retrieved from `pkg-config`.

`/etc/bash-completion.d` is deprecated in favor of `/usr/share/bash-completion/completions`. 

From the [bash-completion FAQ](https://github.com/scop/bash-completion#faq):
> Q. I author/maintain package X and would like to maintain my own completion code for this package. Where should I put it to be sure that interactive bash shells will find it and source it?
> 
> A. Install it in one of the directories pointed to by bash-completion's pkgconfig file variables. There are two alternatives: the recommended one is `completionsdir` (get it with `pkg-config --variable=completionsdir bash-completion`) from which completions are loaded on demand based on invoked commands' names, so be sure to name your completion file accordingly, and to include for example symbolic links in case the file provides completions for more than one command. The other one which is present for backwards compatibility reasons is `compatdir` (get it with `pkg-config --variable=compatdir bash-completion`) from which files are loaded when `bash_completion` is loaded.
> 
> [...]
> For cmake we ship the `bash-completion-config.cmake` and `bash-completion-config-version.cmake` files. Example usage:
> ```
>    find_package(bash-completion)
>    if(BASH_COMPLETION_FOUND)
>      message(STATUS
>        "Using bash completion dir ${BASH_COMPLETION_COMPLETIONSDIR}")
>    else()
>      set (BASH_COMPLETION_COMPLETIONSDIR "/etc/bash_completion.d")
>      message (STATUS
>        "Using fallback bash completion dir ${BASH_COMPLETION_COMPLETIONSDIR}")
>    endif()
> 
>    install(FILES your-completion-file DESTINATION
>      ${BASH_COMPLETION_COMPLETIONSDIR})
> ```
