### ISSUE TITLE
Plugin loading debugging

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#1118]
We once had a `PDAL_DEBUG` environment variable to override any PDAL logging information and see the pluging loading status. 

We need to fix up the global logging to push its output to `stderr` when `PDAL_DEBUG` is set.

**Comment by abellgithub** [comment]
I'm halfway done with this.

**Comment by hobu** [comment]
Is this in a branch? I can take it on if it is still half done.

**Comment by abellgithub** [comment]
On Tue, Feb 23, 2016 at 2:45 PM, Howard Butler <notifications@github.com>
wrote:

> Is this in a branch? I can take it on if it is still half done.
>

I'll have to look.

-- 
Andrew Bell
andrew.bell.ia@gmail.com
