### ISSUE TITLE
plugins versionnig like pdal_*.so.2.0.0 ?

### ISSUE THREAD

**Issue by tigerfoot** [PDAL/PDAL#1119]
Building pdal for openSUSE I've been warned about our shlib versionning policy 
Full log at
https://build.opensuse.org/package/live_build_log/home:bruno_friedmann:branches:Application:Geo/PDAL/openSUSE_Tumbleweed/x86_64
```
/usr/bin/pdal
/usr/lib64/libpdal_base.so.2.0.0
/usr/lib64/libpdal_plang.so.2.0.0
/usr/lib64/libpdal_plugin_filter_attribute.so
/usr/lib64/libpdal_plugin_filter_predicate.so
/usr/lib64/libpdal_plugin_filter_programmable.so
/usr/lib64/libpdal_plugin_reader_pgpointcloud.so
/usr/lib64/libpdal_plugin_reader_sqlite.so
/usr/lib64/libpdal_plugin_writer_pgpointcloud.so
/usr/lib64/libpdal_plugin_writer_sqlite.so
/usr/lib64/libpdal_util.so.2.0.0
....
[ 1765s] libpdal1.x86_64: W: shlib-unversioned-lib libpdal_plugin_filter_attribute.so
[ 1765s] libpdal1.x86_64: W: shlib-unversioned-lib libpdal_plugin_reader_sqlite.so
[ 1765s] libpdal1.x86_64: W: shlib-unversioned-lib libpdal_plugin_filter_programmable.so
[ 1765s] libpdal1.x86_64: W: shlib-unversioned-lib libpdal_plugin_writer_sqlite.so
[ 1765s] libpdal1.x86_64: W: shlib-unversioned-lib libpdal_plugin_reader_pgpointcloud.so
[ 1765s] libpdal1.x86_64: W: shlib-unversioned-lib libpdal_plugin_filter_predicate.so
[ 1765s] libpdal1.x86_64: W: shlib-unversioned-lib libpdal_plugin_writer_pgpointcloud.so
[ 1765s] Your package matches the Shared Library Policy Naming Scheme but contains an
[ 1765s] unversioned library. Therefore it is very unlikely that your package can be
[ 1765s] installed in parallel to another version of this library package. Consider
[ 1765s] moving unversioned parts into a runtime package.

```
I would conclude that also plugin should be versionned, is it right ?

Could be related to 
https://github.com/PDAL/PDAL/issues/549
https://github.com/PDAL/PDAL/pull/679

In the meantime, I found confusing the 2.0.0 when soname state 1 ?

**Comment by hobu** [comment]
Yes the plugins probably need to be versioned too, although I'm unsure how proprietary and/or closed plugins can keep up with the versioning scheme. I suppose PDAL would have to provide some kind of cmake-time macro that reports the versioning the plugin should use.

As for the soversion of 2, that's just normal incrementing. The soversion should not conform to the semantic versioning.
