### ISSUE TITLE
Enhance sort filter

### ISSUE THREAD

**Issue by abellgithub** [PDAL/PDAL#1121]
It would be nice to sort largest to smallest with the sort filter.
It would be nice to allow a stable sort in the sort filter.

**Comment by wrenoud** [comment]
@hobu I took a stab at adding the reversed sort and submitted  #1530. The stable sort seems like a much bigger issue to tackle. Wondering if you have thoughts on how it could be approach.

**Comment by connormanning** [comment]
Couldn't we just use [std::stable_sort](http://en.cppreference.com/w/cpp/algorithm/stable_sort) in place of the current `std::sort` for that?

**Comment by abellgithub** [comment]
Stable sort is simple, since it's implemented in the standard library.  Usually stable sort isn't an issue unless you're sorting on multiple dimensions.  I didn't implement because

1) I hadn't heard anybody wanted it
2) There is a design choice to be made -- do you sort multiple dimensions in one filter or chain filters if you want sorting on multiple dimensions.

Mostly I was waiting for any demand to do anything about it.

**Comment by wrenoud** [comment]
I'm jumping in here simply because I was looking for a small case to contribute on to get familiar with the library.  :)

**Comment by abellgithub** [comment]
Thanks!

**Comment by wrenoud** [comment]
@abellgithub I tried std::stable_sort, it requires a default constructor for `pdal::PointViewIter`, is that a safe thing to add?

Also the unittests don't show any meaningful difference in sort time... should I go ahead and add it?

**Comment by abellgithub** [comment]
My concern would be speed.  If stable_sort weren't slower, there'd be no need for the alternative.  I don't know that our tests are large enough to show anything of interest.
