### ISSUE TITLE
Visual Studio 2015 build clean-up

### ISSUE THREAD

**Issue by mloskot** [PDAL/PDAL#1128]
This ticket may be of interest to anyone who needs to build PDAL using the latest VS2015.

Since I've started working on the build, master@ 329d5d397a92522e3ec27e01ed4e00abbb74f870, handful of fixes was required:

* #1124
* #1125 
* #1126
* #1127

Having those patches applied to the current master, I can successfully build using VS2015, 64-bit target in both configurations, Release and Debug.

The only dependencies I have installed, using OSGeo4W, are GEOS, GDAL and libxml2.
Then, I configured minimal build configuration with default features only:
```
cmake.exe -G "Visual Studio 14 2015 Win64" ..
```

If this is enough to cover testing of **core functionality**, then I consider the VS2015 build back in shape
and the ticket can be closed. Otherwise, please suggest what else to install to cover any missing features.

**Comment by abellgithub** [comment]
Thanks for this.  We haven't had much demand for VS2015 AFAIK.  @hobu: Can we do Appveyor with VS2015?

**Comment by mloskot** [comment]
@abellgithub Technically, AppVeyor supports VS2015, during my last attempt a while ago, I hit a wall which I could not find a work around for: http://help.appveyor.com/discussions/problems/3203-vs2015-and-incorrect-mspdb140dll-version Possibly, it has been fixed since then, especially that VS2015 Update 1 is out.

**Comment by hobu** [comment]
@mloskot can you please merge with my `windows-warnings-cleanup-hobu` branch? I had started trying to get AppVeyor builds happy, but you've eclipsed my efforts.

**Comment by mloskot** [comment]
@hobu Ah, sorry. I see you have already merged all the four patches linked in the issue.
So, I'll continue using your `windows-warnings-cleanup-hobu` branch.

**Comment by hobu** [comment]
No worries. You are much better at this than me!

**Comment by mloskot** [comment]
My convenience `build.bat` script for VS2015 is here in `ml/build-bat` branch at  b4796488dca49f8f792f1937d9c527ca0056adb2

**Comment by mloskot** [comment]
After fixing the bunch of crashes, heap corruptions, etc. I've come to the point all tests run w/o crashing:
```
1>  93% tests passed, 4 tests failed out of 56
1>
1>  Total Test time (real) = 120.69 sec
1>
1>  The following tests FAILED:
1>  	  3 - pdal_file_utils_test (Failed)
1>  	 16 - pdal_spatial_reference_test (Failed)
1>  	 23 - pdal_io_bpf_test (Failed)
1>  	 52 - pc2pc_test (Failed)
```

where

* `pdal_file_utils_test` should be easy to fix, see #1131.
* `pdal_spatial_reference_test` is failing with
```
[ RUN      ] SpatialReferenceTest.test_proj4_roundtrip
D:\dev\PDAL\test\unit\SpatialReferenceTest.cpp(95): error: Value of: ret == proj4_out
  Actual: false
Expected: true
D:\dev\PDAL\test\unit\SpatialReferenceTest.cpp(102): error: Value of: ret == proj4_out
  Actual: false
Expected: true
D:\dev\PDAL\test\unit\SpatialReferenceTest.cpp(109): error: Value of: ret == proj4_out
  Actual: false
Expected: true
[  FAILED  ] SpatialReferenceTest.test_proj4_roundtrip (2 ms)
```
* `pdal_io_bpf_test` is failing with
```
[ RUN      ] BPFTest.bundled
unknown file: error: C++ exception with description "writers.bpf: bundledfile 'D:/dev/PDAL/test/data/bpf/bundle1' name exceeds maximum length of 32." thrown in the test body.
[  FAILED  ] BPFTest.bundled (24 ms)
```
* `pc2pc_test` is failing with
```
[ RUN      ] pc2pcTest.pc2pcTest_test_no_input
PDAL: Missing value for positional argument 'input'.

D:\dev\PDAL\test\unit\apps\pc2pcTest.cpp(64): error: Value of: expected
  Actual: "Usage error: --input"
Expected: output.substr(0, expected.length())
Which is: ""
[  FAILED  ] pc2pcTest.pc2pcTest_test_no_input (36 ms)
```

I will look at those at some point.

**Comment by abellgithub** [comment]
That last one is just because the pdal help output has changed.

**Comment by hobu** [comment]
> SpatialReference...ick. Probably different proj.4 versions?

Yes, probably. Older GDAL output of proj4 strings didn't report towgs84 parameters.

**Comment by mloskot** [comment]
@abellgithub Regarding `pc2pc_test`, I've submitted #1136

**Comment by abellgithub** [comment]
Thanks!

**Comment by mloskot** [comment]
#1137 fixes `pdal_file_utils_test` and `pdal_io_bpf_test` failures.
