### ISSUE TITLE
writers.derivative GDAL output types

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#1146]
I would like to specify any GDAL writeable output format type as an option in `writers.derivative`

**Comment by abellgithub** [comment]
@chambbj: Can this be closed?

**Comment by chambbj** [comment]
With #1402, yes. Did you want to take a look at that? Or should I just merge?

**Comment by abellgithub** [comment]
#1402 is fine, but does that do types for the derivative writer?

**Comment by chambbj** [comment]
Yes, it now passes a user-provided driver type through to GDALUtils to
write the raster - the default is GTiff. No checks or guarantees on whether
or not the driver type supports the output as we briefly discussed on Slack.

**Comment by abellgithub** [comment]
OK.
