### ISSUE TITLE
prettycompoundwkt in JSON metadata dump not validating

### ISSUE THREAD

**Issue by marops** [PDAL/PDAL#1157]
pdal info --metadata <filename>. The outputted JSON is not validating (python json decode, and couple of online JSON validators.

It fails on prettycompoundwkt which is in the srs field. It appears to be with the embedded CR/LF. If they are taken out it validates. Also the compoundwkt field validates OK.

Found in file  include/pdal/PDALUtils.hpp

**Comment by hobu** [comment]
PDAL JSON escaping is deficient.

1. Metadata string `value()` members are not escaped on output `toJSON`
2. `escapeJSON` removes control characters instead of escaping them

**Comment by marops** [comment]
The 2 "pretty" fields (prettywkt and prettycompoundwkt) are the same data as the wkt and compoundwkt with the CR/LFs added for readability. One option could be drop those "pretty" fields in the srs node since we already have the data. If the user needs a more readable version, they parse and reformat for display. I do this with LAS NGA VLRs, which I parse with a python script, decode the Base64 data and output the VLR XML text so I can read it.

**Comment by hobu** [comment]
The pretty fields are there as a convenience, and maybe we can indeed dump them. It is easy enough to pretty'ify them by pushing them through GDAL.

**Comment by marops** [comment]
Thanks for adding the escaping to JSON code.

**Comment by abellgithub** [comment]
@hobu: Is this done?
