### ISSUE TITLE
Programmable filter broken in Docker's `pdal/pdal`

### ISSUE THREAD

**Issue by gadomski** [PDAL/PDAL#1174]
Using Docker's `pdal/pdal` @ sha256:35809, the following command fails (assuming the command is run from the PDAL root and PDAL was successfully built to `build/`):

```bash
docker run -v $(pwd):$(pwd) pdal/pdal pdal pipeline $(pwd)/build/test/data/plang/programmable-update-classifications.xml
```

with:

> ImportError: numpy.core.multiarray failed to import
> PDAL: ImportError('numpy.core.multiarray failed to import',)

Numpy imports ok and reports an ok version on the docker image:

```bash
docker run pdal/pdal python -c "import numpy; print numpy.version.version"
```

> 1.8.2

I wasn't able to `apt-get install gdb` on the docker image, and my Docker-fu is limited, so I'm opening this issue in case someone knows where to start debugging.

**Comment by abellgithub** [comment]
See #1010 for more info.

**Comment by abellgithub** [comment]
As far as I can tell this is a build issue.  I'm not sure why we haven't generally had the problem.  It *seems* that PDAL_PYTHON_LIBRARY isn't getting set in pdal_defines.h, which means the necessary symbols aren't getting loaded.  I'm removing PDAL_PYTHON_LIBRARY from pdal_defines.h and setting is explicitly in python.cmake which seems to address the issue.
