### ISSUE TITLE
PDAL include install flattening

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#1180]
PDAL currently flattens the include paths (`<pdal/io/las/LasReader.hpp>` turns into `<pdal/LasReader.hpp>`) upon install. 

Is there a good reason for this?

Here's some reasons why it's a problem:
1) You can't interchangeably switch from installed to uninstalled PDALs.
2) Documentation ends up not matching code/tests
3) Confusing

I'd like to go back to installing with the full path. Then we don't have to worry about name collisions, we can easily switch between codebases, and we don't have to be so careful.

**Comment by abellgithub** [comment]
I don't like the idea of the full path.  It's a pain in the ass for people using the API.  I'd rather just have <pdal/Whatever> for everything.  I think this is why I liked the symlink thing that we tried and everyone else hated.  I agree that it's an issue, but I don't know the best solution.  I'd be very pleased if we could merge the sources and header files that we have in "src" and "include/pdal", respectively.  Not sure how best to attack this.

What about eliminating the <pdal/...> prefix altogether?  Downside of that is name collision, I guess.

**Comment by abellgithub** [comment]
I'm not sure what to do with this.  I agree that it's an issue.  It seems like we have to 1) decide how we want things arranged in an installation and 2) figure how to coerce the build environment to match.

- Symlinks work, but nobody likes them except me.
- We could make sure that all headers sit in a `pdal` directory in the source tree.  How do we feel about commingling source and header files?  I'm fine with it.  I'm just not sure about how we name things in, say, the plugin directories.  Right now it's plugins/\<plugin_name>/io/\<files>.  Should we make it plugins/\<plugin_name>/pdal/\<files>?  Do people see other issues?
- Other ideas?

Input appreciated.

**Comment by chambbj** [comment]
Should this be closed via 006ea71362a5486109f48d2981b72ada15b31916?

**Comment by abellgithub** [comment]
Fixed with #1413
