### ISSUE TITLE
Inconsistent reader behavior - and QuickInfo behavior issue

### ISSUE THREAD

**Issue by connormanning** [PDAL/PDAL#1188]
Here's an oddity where two identically-created Stages can behave differently based on the presence of an "unrelated" third stage.  In particular, I ran into this issue performing these steps:

 - Create a `Reader` and get its `QuickInfo`.  The file for this reader has an SRS issue, so an error message is logged.

- Create a `ReprojectionFilter`, and `prepare` it.  Behind the scenes, this triggers a call to `GlobalEnvironment::initializeGDAL`, which causes the issue in the next step.

- Create another `Reader`, identical to the first, and get its `QuickInfo`.  Instead of the error message being logged, now it will be thrown.

Here's some code and its output: https://gist.github.com/connormanning/2f666606cabd51be5e74
Here's a sample file: https://s3.amazonaws.com/iowa-lidar/IA_LAZlib/02004736.laz

It seems like the second behavior (throwing) is the desired behavior, however I think that QuickInfo specifically should still succeed even with bad SRS info in the file.  For example, in my application I am specifically using externally-supplied SRS info for my projections and ignoring the file's SRS contents completely - so I still need the point count and native bounds even if the SRS can't be determined (empty string would suit my needs just fine).  This aspect is possibly related to https://github.com/PDAL/PDAL/pull/1043.

**Comment by hobu** [comment]
This issue was fixed by #1222
