### ISSUE TITLE
pdal docker dependencies based on old image

### ISSUE THREAD

**Issue by msmitherdc** [PDAL/PDAL#1198]
Recommend changing `FROM ubuntu:15.04` to `FROM ubuntu:trusty`. 15.04 is not getting CVE updates

**Comment by hobu** [comment]
That's so frustrating. 16.04 isn't out yet and 14.04 is ancient.

**Comment by msmitherdc** [comment]
`16.04` is out and you can use it, or use `xenial`

**Comment by hobu** [comment]
Certainly doable, but a number of the package names and such (specifically boost) will need to be updated.

**Comment by hobu** [comment]
PDAL's dependencies package is now based on Xenial
