### ISSUE TITLE
License for plugins/hexbin/kernel/OGR.cpp

### ISSUE THREAD

**Issue by sebastic** [PDAL/PDAL#1204]
PDAL 1.2.0 introduces the file `plugins/hexbin/kernel/OGR.cpp` whose copyright header is unclear which license applies to it:
```
    This is free software; you can redistribute and/or modify it under the
    terms of the GNU Lesser General Licence as published by the Free Software
    Foundation. See the COPYING file for more information.
```
It contains the common typo "GNU Lesser General Licence" instead of "GNU Lesser General Public Licence", and the `COPYING` file reference is not actually included.

The license is probably LGPL-2.1+ because version 2 of the license was called "GNU Library General Public License".

Please update the license header to include the common text for the applicable license, for LGPL-2.1+ this would be:
```
    (c) 2013 Hobu, Inc. hobu.inc@gmail.com

    Author: Howard Butler, hobu.inc@gmail.com

    This library is free software; you can redistribute it and/or modify it 
    under the terms of the GNU Lesser General Public License as published by 
    the Free Software Foundation; either version 2.1 of the License, or 
    (at your option) any later version.

    This library is distributed in the hope that it will be useful, but 
    WITHOUT ANY WARRANTY; without even the implied warranty of 
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
    See the GNU Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public License 
    along with this library; if not, write to the Free Software Foundation, 
    Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA 
```

**Comment by hobu** [comment]
I copied this data out of http://github.com/hobu/hexer and neglected to update the header. I meant to relicense this code under the same license as PDAL (OGR.hpp header was updated, but I forgot OGR.cpp). I will update the `1.2-maintenance` branch with the license update.
