### ISSUE TITLE
Allow specification of --driver with pdal info

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#1207]
There are a number of formats that are `.txt`. Allow manual specification via command line.

**Comment by abellgithub** [comment]
Wondering if perhaps we could do something like come up with some reasonable extensions for files?  This is an issue for more than `pdal info`.

**Comment by hobu** [comment]
I think we should have Stage advertise its extensions so StageFactory doesn't have the static map that we currently have. We still need the driver selection bit (just an issue for `info` but maybe `tindex` or some of the other `inferReaderDriver`-calling kernels).

**Comment by abellgithub** [comment]
> I think we should have Stage advertise its extensions so StageFactory doesn't have the static map that we currently have.

Agree.

> We still need the driver selection bit (just an issue for info but maybe tindex or some of the other inferReaderDriver-calling kernels).

Do we?  Perhaps we can find another way.  Can we identify the problems and then look at our options?  I'm not a fan of dumping this on the user.

**Comment by hobu** [comment]
> Do we? Perhaps we can find another way. Can we identify the problems and then look at our options? I'm not a fan of dumping this on the user

GDAL implements this really poorly with its `SKIP_DRIVER` environment variable. Magic, on the user, and arbitrary. I don't have a good solution either, but we need a way to be specific. 

Maybe a way to interrogate extensions and allow the user to specify would be sufficient:

`$ pdal --drivers "txt"`

```
readers.text
readers.ilvis2
writers.text
writers.ilvis2
```

**Comment by hobu** [comment]
Available now.
