### ISSUE TITLE
Laz writer inserting dimensions it shouldn't

### ISSUE THREAD

**Issue by connormanning** [PDAL/PDAL#1212]
Encountered while performing a `filters.range` operation on a LAZ file whose `pdal info` contains no RGB dimensions.  The resulting output does contain these dimensions (zeroed out of course).  Expected behavior would be to retain only the dimensions from the input file.

To reproduce:
- use PDAL 1.2.
- fetch [this file](https://s3.amazonaws.com/hobu-lidar/misc/range.laz).
- `pdal info range.laz` shows 12 dimensions with no color.
- `pdal translate -i range.laz -o output.laz -f range --filters.range.limits="Z[100:400]"`
- `pdal info output.laz` has 15 dimensions since RGB was added.

**Comment by abellgithub** [comment]
The LAS writer uses a default point format that can be overridden with the option `dataformat_id`.  The default point format is "3", which contains includes RGB.  See http://www.pdal.io/stages/writers.las.html

**Comment by abellgithub** [comment]
If you want to forward the dataformat_id, you can use the option `--forward=dataformat_id`

**Comment by connormanning** [comment]
Great, this works as expected.  What are the reasons for not turning this option on by default?  My thoughts being that going from "no color here" to "there's color here, and it's black" is surprising default behavior.

**Comment by abellgithub** [comment]
It's been that way since before I was involved.  I'm hesitant to change such things.

**Comment by hobu** [comment]
Explicit (you need to set it) is better rather than implicit (we silently set the point format for you for this one specific format for this one specific pipeline operation).
