### ISSUE TITLE
Options shouldn't support multiple values

### ISSUE THREAD

**Issue by abellgithub** [PDAL/PDAL#1224]
When options accept multiple values for the same key it breaks our new JSON pipeline spec.  It also makes it difficult to determine if values should be replaced or appended when a duplicate key is referenced.

**Comment by hobu** [comment]
Can we move to using an object with an array?

```
{"multiples": [ "value1","value2",'value3"]}
```

**Comment by abellgithub** [comment]
That seems a complication for no benefit.  Seems better to just do:

`"key": "val1, val2, val3"`

We already do this in most cases and it seems good just to make it universal.  There are only like two cases to fix.

**Comment by connormanning** [comment]
You don't need to introduce a new nested object for it to be an array, e.g. `"key": ["val1", "val2", "val3"]`.  That seems much more in line with JSON in general than a comma separated string.

**Comment by abellgithub** [comment]
This isn't really about JSON.  It's about keeping our code consistent and simple.  We're already doing comma-separated string lists all over the place.

**Comment by abellgithub** [comment]
I take this back.
