### ISSUE TITLE
no display of kernel output from docker

### ISSUE THREAD

**Issue by msmitherdc** [PDAL/PDAL#1226]
Example:
docker exec -i pdaldock pdal --version

or 

docker exec -i pdaldock pdal --drivers

both yield no output

**Comment by abellgithub** [comment]
Is this on the docker image that we build, or one that you're building?

**Comment by msmitherdc** [comment]
Both

**Comment by hobu** [comment]
Did we get to the bottom of this one?

**Comment by abellgithub** [comment]
I think so.  I think we're not compiling PCL with C++ 11 when we do our docker build.  It's PCL-related.

**Comment by hobu** [comment]
I have pushed a new version of `pdal/dependencies` which should resolve this issue.

**Comment by abellgithub** [comment]
Can this be closed?

**Comment by msmitherdc** [comment]
yes
