### ISSUE TITLE
Can Stage::prepare() be called multiple times?

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#1234]
Calling `prepare()` multiple times might have inconsistent behavior depending on the stage.

1. `preview()` calls `initialize()`
2. `prepare()` calls `initialize()`
3. `setInput()` gets called on the Stage, and then `prepare()` gets called again.

```
    if (pdal::Reader* reader = makeReader(path))
    {
        reader->preview();

        pdal::Stage* filter = makeRange("Red[0:50]");

        filter->setInput(*reader);

        pdal::PointTable table2;
        filter->prepare(table2);
```

The above code works for `readers.las`, but would it work for every stage type? `Stage::prepare()` doesn't protect against being called multiple times, and I wonder if it should.

**Comment by abellgithub** [comment]
This is generally fine.  prepare() calls processOptions(), initialize() and addDimensions().  Processing options more than once isn't a problem.  Neither is adding dimensions.  Most of the readers/writers now open files for IO at the start of initialize() and close at the end to avoid proliferation of file handles.  There may be outstanding issues, but they should probably be addressed individually when encountered.
