### ISSUE TITLE
PLY reader ignores normal fields (and curvature)

### ISSUE THREAD

**Issue by rhuitl** [PDAL/PDAL#1262]
The PLY reader seems to ignore the normal fields stored in a PLY file like this one written by Meshlab:

```
ply
format ascii 1.0
comment VCGLIB generated
element vertex 1
property float x
property float y
property float z
property float nx
property float ny
property float nz
property uchar red
property uchar green
property uchar blue
property uchar alpha
element face 0
property list uchar int vertex_indices
end_header
-2.64944 -13.0955 0.00640115 -0.0237552 -0.00902114 0.999665 63 63 64 255
```

Output of "pdal info -p 0":
```
{
  "filename": "ply-with-normals.ply",
  "pdal_version": "1.2.0 (git-version: f5a958)",
  "points":
  {
    "point":
    {
      "Alpha": 255,
      "Blue": 64,
      "Green": 63,
      "PointId": 0,
      "Red": 63,
      "X": -2.64944,
      "Y": -13.0955,
      "Z": 0.00640115
    }
  }
}
```

Further, PLY files written by PCL include a field called "curvature":
```
property float curvature
```

This field is also not imported. Is there a way to import all the fields defined in PLY or instruct the reader to import fields I name? Or even better, just import all the fields that are present?

**Comment by abellgithub** [comment]
@gadomski: We're explicitly only reading well-known dimensions.  I can fix this super-fast if there's no reason not to load all dimensions.

**Comment by gadomski** [comment]
No reason no to @abellgithub go ahead.

**Comment by rhuitl** [comment]
Hi Andrew, thanks for fixing this so quickly!
Was it intended to have the extra fields as an array without name (see below)?

```
{
  "filename": "ply-with-normals.ply",
  "pdal_version": "1.2.0 (git-version: 07e01f)",
  "points":
  {
    "point":
    {
      "":
      [
        -0.02375520021,
        -0.009021139704,
        0.9996650219
      ],
      "Alpha": 255,
      "Blue": 64,
      "Green": 63,
      "PointId": 0,
      "Red": 63,
      "X": -2.64944005,
      "Y": -13.09549999,
      "Z": 0.006401150022
    }
  }
}
```

**Comment by abellgithub** [comment]
Just fixed with #1265.

**Comment by rhuitl** [comment]
Awesome, thanks ;-)
By the way, do you not have normals as a well-known dimension? If you don't, that would limit the usefulness of filters like http://www.pdal.io/stages/filters.transformation.html quite a bit - in this case, the normals should also be rotated when applying a transform. VoxelGrid should average the normals and renormalize the result, etc...

**Comment by abellgithub** [comment]
We add standard dimensions to support formats.  I don't believe that normals are provided as a standard dimension by any of the formats we currently support.  I don't know the details of the VoxelGrid filter so can't speak to its operation.
