### ISSUE TITLE
Compilation errors on Ubuntu 16.04 : /usr/bin/ld: cannot find -lvtkproj4

### ISSUE THREAD

**Issue by swiss-knight** [PDAL/PDAL#1267]
Hi. 
After configuring and generating pdal within **cmake-gui** (here is the complete cmake-gui console log : http://pastebin.com/raw/FipnGvrY )

The make process stops on these 4 same errors while building plugins : 
> /usr/bin/ld: cannot find -lvtkproj4
> collect2: error: ld returned 1 exit status

Here are the completes last lines of the make process :
http://pastebin.com/raw/wsdNhxMe

System specifications : 
> $ lsb_release -rd
> Description:	Ubuntu 16.04 LTS
> Release:	16.04
> 
> $ uname -r
> 4.4.0-28-generic

Thanks.

**Comment by hobu** [comment]
https://github.com/PointCloudLibrary/pcl/issues/1594 seems relevant here. PDAL itself doesn't use vtkproj4 in any way AFAIK.

**Comment by swiss-knight** [comment]
Okay thank you, I will switch to PCL Issues tracker, so you can close here.
