### ISSUE TITLE
Make[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libpcl_common.so', needed by 'lib/libpdal_plugin_filter_(...)'

### ISSUE THREAD

**Issue by swiss-knight** [PDAL/PDAL#1268]
Hi.
I have compiled and installed **pcl** 1.8 release from here : https://github.com/PointCloudLibrary/pcl/releases 
using cmake-gui to configure & generate, then 'make' && 'sudo checkinstall make install'
It all went to _/usr/local_ without particular issues except one of the same flavour than here also with **PDAL** and related to VTK (again) :

> The imported target "vtk" references the file
>    "/usr/bin/vtk"
> but this file does not exist.  Possible reasons include:
> * The file was deleted, renamed, or moved to another location.
> * An install or uninstall procedure did not complete successfully.
> * The installation package was faulty and contained
>    "/usr/lib/cmake/vtk-6.2/VTKTargets.cmake"
> but not all the files it references.

For **PDAL** installation then, configuring with cmake-gui seems OK but generating leads to lots of warnings ; here is the whole log from cmake-gui : http://pastebin.com/raw/QUkVzgVr 

Warnings are of type :
> CMake Warning at cmake/macros.cmake:114 (add_library):
>   Cannot generate a safe runtime search path for target
>   pdal_plugin_kernel_pcl because files in some directories may conflict with
>   libraries in implicit directories:
> 
>     runtime library [libpcl_common.so] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
>       /usr/local/lib
>     runtime library [libpcl_octree.so] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
>       /usr/local/lib
>     runtime library [libpcl_io.so] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
>       /usr/local/lib
>     runtime library [libpcl_kdtree.so] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
>       /usr/local/lib
>     runtime library [libpcl_search.so] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
>       /usr/local/lib
>     runtime library [libpcl_sample_consensus.so] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
>       /usr/local/lib
>     runtime library [libpcl_filters.so] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
>       /usr/local/lib
>     runtime library [libpcl_features.so] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
>       /usr/local/lib
>     runtime library [libpcl_segmentation.so] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
>       /usr/local/lib
>     runtime library [libpcl_visualization.so] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
>       /usr/local/lib
>     runtime library [libpcl_surface.so] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
>       /usr/local/lib
>     runtime library [libpcl_registration.so] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
>       /usr/local/lib
>     runtime library [libpcl_keypoints.so] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
>       /usr/local/lib
>     runtime library [libpcl_tracking.so] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
>       /usr/local/lib
>     runtime library [libpcl_recognition.so] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
>       /usr/local/lib
>     runtime library [libpcl_outofcore.so] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
>       /usr/local/lib
>     runtime library [libpcl_people.so] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
>       /usr/local/lib
> 
> Some of these libraries may not be found correctly.
> Call Stack (most recent call first):
> plugins/pcl/CMakeLists.txt:186 (PDAL_ADD_PLUGIN)

But there is absolutely nothing about **pcl** in the _/usr/lib/x86_64-linux-gnu_ directory. 
Again, everything went to _/usr/local_

And 'make' ends on issues "No rule to make target '/usr/lib/x86_64-linux-gnu/libpcl_common.so', needed by 'lib/libpdal_plugin_filter_(...)'" that seem (?) related to the previous warnings, here are the last lines where the errors appeared : http://pastebin.com/raw/ayHsLxU0

System : Ubuntu 16.04 LTS, kernel : 4.4.0-28-generic

Thanks a lot.

**Comment by swiss-knight** [comment]
I absolutely don't know why but when generating the program within cmake-gui, all PCL_XXX_LIBRARY entries were mixed up between an old pcl-1-7 directory that doesn't exist anymore (!) and some wrong pcl-1.8 path to almost all theses libraries. 
Same thing for the PCL_XXX_INCLUDE paths.
By fixing them manually, it all went like a charm (in my case they are installed within the _/usr/local_ path ).

For example : 
```
PCL_XXX_INCLUDE -> /usr/local/include/pcl-1.8 (exactly the same path for every XXX)
PCL_XXX_LIBRARY -> /usr/local/lib/libpcl_xxx.so
PCL_XXX_LIBRARY_DEBUG -> /usr/local/lib/libpcl_xxx.so (same as above)
```

You can close this thread, I think.
It runs well now ! :)

**Comment by hobu** [comment]
> I absolutely don't know why but when generating the program within cmake-gui, all PCL_XXX_LIBRARY entries were mixed up between an old pcl-1-7 directory that doesn't exist anymore (!)

The cmake magic detection probably found a PCL cmake file from the old install that had those paths set.

**Comment by wine3603** [comment]
I struggled on this problem for two days!!! 
tried to reinstall pcl 1.7 1.8 1.81 1000000times but no luck,
also reinstall cmake 3.11, 3.8, no luck.
finally. I found that it was from the multi-install directions of pcl.
mostly, this problem is from that, when you install pcl using cmake-gui, you may set the prefix dir to 
/usr/local/, but former pcl 1.7 are set to /usr/
this lead some bugs since you may have two PCL_Config.cmake in your /usr/share/lib/...
the way to fix is just uninstall some pcl versions.

But, what make me crazy was in my project file.
I used the same build file to compile new pcl libs, and always fall in multi-pcl_lib bugs,
and I thought it was pcl pkg problem.....
actually u just need to delete the build file in your project, and make a new try with cmake-gui......

**Comment by MingFengHill** [comment]
I limited the search path for the package through cmake, but the same error occurred.
```
find_package(PCL REQUIRED PATHS /usr/local/ NO_DEFAULT_PATH)
```

 Finally, I solved this problem through a soft link .
```
oeng@rh-Precision-7920-Tower:/usr/lib/x86 64-inux-gnussr/local/lib/libpcl apps.so libpcl apps.sosudoSssssssssssssssssssspeng@rh-Precision-7920-Tower:/usr/lib/x86 64-linux-gnu$sudosr/local/lib/libpclcommon .so libpcl common .sopeng@rh-Precision-7920-Tower:/usr/lib/x86 64-linux-gnu$sudosr/local/lib/libpcl features.so libpcl features.sopengarh-Precision-7920-Tower:/usr/lib/x86 64-linux-gnu$sudosr/local/lib/libpcl io ply.so libpcl io ply.sopeng@rh-Precision-7920-Tower:/usr/lib/x86 64-linux-gnu$sudolsr/local/lib/libpcl io.so libpcl io.sopeng@rh-Precision-7920-Tower:/usr/lib/x86 64-linux-gnussudosr/local/lib/libpcl kdtree.so libpcl kdtree.sopeng@rh-Precision-7920-Tower:/usr/lib/x86 64-linux-gnu$sudosr/local/lib/libpcl keypoints.so libpcl keypoints.sopeng@rh-Precision-7920-Tower:/usr/lib/x86 64-linux-gnu$sudosr/local/lib/libpcl ml.so libpc ml.sosr/local/lib/libpcl octree.so libpcl octree.sopeng@rh-Precision-7920-Tower:/usr/lib/x86 64-Tinux-gnussudopengarh-Precision-7920-Tower:/usr/lib/x86 64-linux-gnu$sudosr/local/lib/libpcl outofcore.so libpcl outofcore.sopengarh-Precision-7920-Tower:/usr/lib/x86 64-linux-gnu$sr/local/lib/libpcl people.so libpcl people.sosudopengarh-Precision-7920-Tower:/usr/lib/x86 64-linux-gnu$sudosr/local/lib/libpcl recognition.so libpcl recognition.sopeng@rh-Precision-7920-Tower:/usr/lib/x86 64-linux-gnu$sudosr/local/lib/libpcl registration.so libpcl registration.sopeng@rh-Precision-7920-Tower:/usr/lib/x86 64-linux-gnu$sudosr/local/lib/libpcl sample consensus.so libpcl sample consensus.sopeng@rh-Precision-7920-Tower:/usr/lib/x86 64-linux-gnu$sudosr/local/lib/libpcl .search.so libpcl search.sopeng@rh-Precision-7920-Tower:/usr/lib/x86 64-linux-gnussr/local/lib/libpcl segmentation.so libpcl segmentation.sosudopeng@rh-Precision-7920-Tower:/usr/lib/x86 64-Tinux-gnussudosr/local/lib/libpcl !stereo.so libpcl stereo.sopeng@rh-Precision-7920-Tower:/usr/lib/x86 64-linux-gnu$sudosr/local/lib/libpclsurface.so libpcl surface.sopengarh-Precision-7920-Tower:/usr/lib/x86 64-inux-gnu$sr/local/lib/libpcl sudontracking.so libpcl tracking.sopengarh-Precision-7920-Tower:/usr/lib/x86 64-linux-gnu$sr/local/lib/libpclsudovisualization.so libpcl visualization.so
```
But why CMAKE would search for PCL in the `/usr/lib/x86_64-linux-gnu` is still unknown
