### ISSUE TITLE
Latest docker image fails to load libgdal.so.1

### ISSUE THREAD

**Issue by AsgerPetersen** [PDAL/PDAL#1290]
Following a great presentation from @msmitherdc I have just pulled the latest docker image and tried to use it. However it fails like 

```bash
$ docker pull pdal/pdal
Using default tag: latest
latest: Pulling from pdal/pdal
Digest: sha256:2bb01acfd2f005c802b62a9324ae63b5cf6d21f5b0e62a51a73ea0690ed8c8b4
Status: Image is up to date for pdal/pdal:latest
~
$ docker run -v ~/Data:/data pdal/pdal pdal info /data/file.laz
pdal: error while loading shared libraries: libgdal.so.1: cannot open shared object file: No such file or directory
```

**Comment by hobu** [comment]
bah! confirmed.

This is related to some updates we've made refreshing the `pdal/dependencies` image to Xenial. I will update this ticket when it is refreshed.

**Comment by hobu** [comment]
This has now been fixed. Please reopen if you have any issues.
