### ISSUE TITLE
vendor'd code should not have versioned file names

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#1294]
versioning the filenames creates package maintenance issues downstream for projects like Homebrew and Debian that do IP verification.

https://lists.osgeo.org/pipermail/pdal/2016-August/001019.html

**Comment by abellgithub** [comment]
I don't understand the issue in the provided link.  Are we distributing things in that structure?  I would think we'd just need the libraries that are linked (and we could get rid of them if we statically link).

**Comment by hobu** [comment]
It seems if we have vendored version 1.1.x (`vendor-1.1.x`) and replace it with 1.2.x (`vendor-1.2.x`), Debian's filters get tripped for a bunch of code review.

**Comment by abellgithub** [comment]
But why would they see this in a distribution?

**Comment by hobu** [comment]
> Are we distributing things in that structure?
Yes we distribute the entire `vendor/` tree as it exists in the code tree.

**Comment by abellgithub** [comment]
Why?  That seems incorrect.

**Comment by hobu** [comment]
> Why? That seems incorrect.

Why have it in the tree at all if we're not going to distribute it with releases?

**Comment by hobu** [comment]
done in #1310
