### ISSUE TITLE
Allow same-named stages to have options be overridden via command line argument

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#1295]
The cleanest way to support this is to allow overrides via stage tags in addition to option names:

`pdal pipeline --tag.option=something`

Users would then need to put tags on their stages when they write the pipeline.

**Comment by abellgithub** [comment]
This is hard to do given our current command-line scheme.  We don't know that an option is a tagname until we read the pipeline, and we can't read the pipeline until we parse the command line and find the filename in one way or another.  It would be much easier (and perhaps less ambiguous) to do something a little different.  One option is just using a special keyword, say "stage": `--stage.<tagname>.<optionname>=value` would be fine.  Other ideas appreciated.

**Comment by abellgithub** [comment]
Implemented by using the syntax suggested above. d1da72c5ee1654d4784628ac8d989c0ac1bfd6f8
