### ISSUE TITLE
Broken link to Dimension.hpp in documentation

### ISSUE THREAD

**Issue by jedfrechette** [PDAL/PDAL#1297]
The documetation at:

http://www.pdal.io/stages/writers.html

links to: 

https://github.com/PDAL/PDAL/blob/master/include/pdal/Dimension.hpp

in the note about dimension names. However, that file doesn't currently exist.

**Comment by hobu** [comment]
need to push this back to `1.3-maintenance` too so it updates the website.

**Comment by srijackec** [comment]
Where can I find this Dimension.hpp?

**Comment by abellgithub** [comment]
Dimension.hpp is created as part of the PDAL build process.

**Comment by kbevers** [comment]
The link in the note at the top of the page now points towards a ```Dimensions.json```. The link is still broken though. I guess it wasn't changed after the restructure of the source tree. I believe the correct link is https://github.com/PDAL/PDAL/blob/master/pdal/Dimension.json

**Comment by hobu** [comment]
Thanks. There's a complete page now http://www.pdal.io/dimensions.html

I'll update the link.

**Comment by MarkcusD** [comment]
What builds this file (it's not being created in my case)?

**Comment by abellgithub** [comment]
Are you sure? It gets created in the build directory, not the source directory. There are dependencies for it in the build file.

**Comment by abellgithub** [comment]
What is the version of cmake you're using?
