### ISSUE TITLE
pdal 1.3.0 macOS <= 10.9: return must match previous build failure

### ISSUE THREAD

**Issue by ilovezfs** [PDAL/PDAL#1300]
This is a build failure that affects macOS <= 10.9, but doesn't affect 10.10 or 10.11. The error is
```
vendor/arbiter/arbiter.cpp:1361:25: error: return type 'basic_string<[3 * ...]>'
must match previous return type 'const basic_string<[3 * ...]>' when
lambda expression has unspecified explicit return type
                        return out + c;
                        ^
```
Full log:
https://gist.github.com/ilovezfs/0fe1815da9da173d4693c1da90a7ab28

**Comment by hobu** [comment]
clang `AppleClang 6.0.0.6000057` must not support lambda expressions with implicit types.

Upstream bug filed in connormanning/arbiter#7

**Comment by abellgithub** [comment]
It's a const mismatch that the older compiler doesn't handle. Brad ran into
this and I thought fixed, but I can do it.

**Comment by abellgithub** [comment]
This was fixed.
