### ISSUE TITLE
kernels.split requires origin if splitter is used

### ISSUE THREAD

**Issue by loganbyers** [PDAL/PDAL#1304]
When running `pdal split` and specifying `--length` to use `filters.splitter` as the filter, an exception is raised.

``PDAL: Invalid value for argument 'origin_x'.``

`--origin_x` is an option that is only available if `--length` is set. The default behavior of `filters.splitter` is to set the origin for the grid from the first point in the cloud. It would make sense to have `kernels.split` operate in the same way.

Can someone quickly confirm that an exception is raised for running:
`pdal split -i test.las -o test_split.las --length 1000`
``PDAL: Invalid value for argument 'origin_x'.``

`pdal split -i test.las -o test_split.las --length 1000 --origin_x 0`
``PDAL: Invalid value for argument 'origin_y'.``

I have tried to trace the exception, and I know that it is first thrown at line 403 in ProgramArgs.hpp.

[SplitKernel.cpp; 120] Stage::prepare() --> [Stage.cpp; 130] Stage::handleOptions() -?-> [Stage.cpp; 102] ProgramArgs::parse() --> [ProgramArgs.hpp; 1010]  ???? -> [ProgramArgs.hpp; 403] 

I am having a hard time understanding how the optional/conditional options `origin_x` and `origin_y` are being parsed, it would seem like they shouldn't/couldn't be pulled from the command line unless they are explicitly set.

For what it's worth, I am adding some extra functionality to `filters.splitter` and updating `kernels.split` to accordingly. The new option is added just like `origin_x` and `origin_y`, but no exception is being raised when it is not set explicitly at the commandline.

**Comment by abellgithub** [comment]
On Thu, Sep 8, 2016 at 4:49 PM, Logan Byers <notifications@github.com>
wrote:

> When running pdal split and specifying --length to use filters.splitter
> as the filter, an exception is raised.
>
> PDAL: Invalid value for argument 'origin_x'.
>
> --origin_x is an option that is only available if --length is set. The
> default behavior of filters.splitter is to set the origin for the grid
> from the first point in the cloud. It would make sense to have
> kernels.split operate in the same way.
>
> Can someone quickly confirm that an exception is raised for running:
> pdal split -i test.las -o test_split.las --length 1000
> PDAL: Invalid value for argument 'origin_x'.
>

I have no problem with your command.  What version are you using?


-- 
Andrew Bell
andrew.bell.ia@gmail.com

**Comment by loganbyers** [comment]
pdal 1.3.0 (git-version: 91dad6)

I removed all the installed libraries and binaries from /usr/local/. Cloned a fresh master copy. 
`cmake . -DBUILD_PLUGIN_P2G=ON -DBUILD_PLUGIN_PCL=ON`
`make`
`sudo make install`

**Comment by abellgithub** [comment]
What is your platform?  If you run from the build directory, do you get different behavior?

**Comment by loganbyers** [comment]
Ubuntu 14.04.1
cmake version 2.8.12.2
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.1)

`cd ~/pdal_13`
`cd bin`
`./pdal split -i ../test/data/las/1.2-with-color.las -o ~/DELETE/color.las --length 100`

Same problem, invalid x_origin

**Comment by abellgithub** [comment]
Just for grins, if you use the syntax `pdal split --length=100 <input_file> <output_file>` do you get the same error?

**Comment by loganbyers** [comment]
Yeah, I have played around with all sorts of perturbations. Using the `-i` flag and not. I initially thought it was coming from the validate() method (of Stage?) because that was handling verification of positional and positional/optional arguments.

**Comment by abellgithub** [comment]
I've recreated the issue on Ubuntu 14.04.

**Comment by loganbyers** [comment]
Thanks!
