### ISSUE TITLE
Missing documentation for filters.mongus and filters.smrf

### ISSUE THREAD

**Issue by jedfrechette** [PDAL/PDAL#1307]
The documentation for 1.3.0 does not include any information about filters.mongus and filters.smrf, which are mentioned in its release notes.

**Comment by chambbj** [comment]
@jedfrechette Take a look at #1308 and let me know if this is good for now. Both of these filters are a bit rough around the edges, both in terms of docs and the implementations themselves. Regardless, we should have something for the docs even if a work in progress.

**Comment by jedfrechette** [comment]
That all seems reasonable to me. It's good to see the Experimental warning.

As a bit of an aside, the release notes also say that readers.greyhound is Beta quality, but the docs don't include a warning like you've added here.
