### ISSUE TITLE
Remove --scale and --offset  "global" kernel options

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#1317]
Looking at these now, I think it is confusing to have them. 

1) Do they apply to all inputs too, or just outputs? 
2) What do they do on an `info` call?
3) Do they override `pipeline` calls?

They existed when it wasn't convenient to override stage options. That is now convenient and easy. These can go.

**Comment by abellgithub** [comment]
I agree.  I would have removed them when I reworked the kernel stuff, but the exact specification was different than it was in stages and I didn't want to break things.
