### ISSUE TITLE
ProgramArgs add() specialization that takes in std::vector<std::string>> for default values

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#1324]
Numerous args have default values that are plucked from a set of choices. Different drivers ad hoc the description of these choices in the help text or other various ways. I wonder if we can regularize this a little bit.

**Comment by abellgithub** [comment]
Example?

**Comment by hobu** [comment]
https://github.com/PDAL/PDAL/blob/gdalwriter/io/gdal/GDALWriter.cpp#L69

**Comment by hobu** [comment]
I think this ticket is more about documentation and outputting valid values to users in help text.

**Comment by abellgithub** [comment]
Default arguments for vector args in c8a9fd51d59c9632eda7654b31b601822fc8e9ad
