### ISSUE TITLE
Output summary

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#1351]
We have `pdal translate --pipeline` and `pdal pipeline --pipeline-serialization` which are attempts to provide a full JSON'ized summary of the operations of a pipeline. They are deficient, however.

We want to improve `--pipeline` JSON summary to output:

- [ ] metadata
- [ ] stage hierarchy and all options (including any modified/updated with computed values)
- [ ] all files written (expand out filters that create multiples)

**Comment by abellgithub** [comment]
This isn't really what `pdal translate pipeline` is doing.  That option is giving a pipeline that you could run.  Perhaps we add a `metadata` options and still the output files in there?

**Comment by hobu** [comment]
I think we want something that is like a combo of light duty `pdal info` output (capture the metadata and options) along with the expanded pipeline that could be potentially run.

**Comment by abellgithub** [comment]
I think this is done.  We now stick the names of the output files in the metadata and there is an option in `pdal translate` to allow output of the metadata to a file.  You have always been able to get the pipeline with the `--pipeline` option.

**Comment by abellgithub** [comment]
@hobu: Can this be closed?
