### ISSUE TITLE
Switch to `target_include_directories` from `include_directories`

### ISSUE THREAD

**Issue by gadomski** [PDAL/PDAL#1354]
CMake's `target_include_directories` is better than `include_directories` because:

1. It allows finer-grained control over what directories are added to the include path for which target.
2. It automatically populates `INTERFACE_INCLUDE_DIRECTORIES`, which simplifies things for downstream users of PDAL's CMake config (see #1353 for an example of how `include_directories` can break things for a downstream).

To fix this issue, it should just be a matter of replacing all usages of `include_directories` with the corresponding `target_include_directories` call, though of course complications may arise.

**Comment by abellgithub** [comment]
Thanks for entering this!
