### ISSUE TITLE
filters.programmable -> set Red Green Blue values for pointcloud colorization

### ISSUE THREAD

**Issue by KlemenSpruk** [PDAL/PDAL#1368]
Hello!

I'm trying to change colorization of ground points in pointcloud.
I've written the following pipeline to achieve this.

{
    "pipeline":[
                    {
                        "filename":"input.las"
                    },
                    {
                        "type":"filters.programmable",
                        "function":"projectPoints",
                        "module":"anything",
                        "source":"
                                    import numpy as np

                                    def projectPoints(ins, outs):
                                        if ins['Classification'] == 2:
                                            outs['Red'] = ins['Green'] * 50
                                            outs['Green'] = ins['Green'] * 0
                                            outs['Blue'] = ins['Blue'] * 0
                                            return True
                                        "
                    },
                    {
                        "type":"writers.las",
                        "filename":"out.las"
                    }
                ]
}

The  **if ins['Classification'] == 2:** line is causing me problems.
I can't achieve this test to work.
I tried:
if np.equal(ins['Classification'][0],[2])[0]
if ins['Classification'][0] == 2
if ins['Classification'] == [2]
.
...

Any suggestions how to write proper test?

Thanks Klemen!

**Comment by hobu** [comment]
You'll have to read through the numpy documentation to get exactly what you need. The following would seem to work, but I have not tested it very much:

```
{
    "pipeline":[
                    {
                        "filename":"greyhound.las"
                    },
                    {
                        "type":"filters.programmable",
                        "function":"projectPoints",
                        "module":"anything",
                        "source":"
import numpy as np

def projectPoints(ins, outs):
    cls = ins['Classification']
    red = ins['Red']
    green = ins['Green']
    blue = ins['Blue']
    it = np.nditer(cls, flags=['f_index'])

    while not it.finished:

        if (cls[it.index] == 2):
            red[it.index] = red[it.index] * 50
            green[it.index] = green[it.index] * 0
            blue[it.index] = blue[it.index] * 0

"
                    },
                    {
                        "type":"writers.las",
                        "filename":"out.las"
                    }
                ]
}
```

**Comment by KlemenSpruk** [comment]
It works! :)
