### ISSUE TITLE
Add ability to test for existence of a proprietary dimension

### ISSUE THREAD

**Issue by chambbj** [PDAL/PDAL#1376]
When testing for the existence of a particular dimension, one would normally use

```
layout->hasDim(Dimension::Id::Foo);
```

But in the case of proprietary dimensions, we now need to add `findProprietaryDim` to get the `Dimension::Id` that `hasDim` requires.

```
layout->hasDim(layout->findProprietaryDim("Bar"))
```

It would be nice if `hasDim` could lookup the dimension by name alone. For example,

```
layout->hasDim("Bar")
```

Open to other suggestions. I may be missing something that already exists.

**Comment by abellgithub** [comment]
What's wrong with `layout->findDim()` ?

**Comment by chambbj** [comment]
I may have simply overlooked it. Will try when I return and report back.

**Comment by chambbj** [comment]
Unless I'm missing something, I don't think `findDim` buys me much.

All I'm trying to do is to ensure a dimension exists prior to running a filter. So, in `prepared` I've got something like

```
if (!layout->hasDim(layout->findProprietaryDim("Pixel Number")))
    throw pdal_error("Filter requires Pixel Number dimension");
```

Maybe it works to switch out `findDim` for `findProprietaryDim`. It just seems a lot more intuitive to hide the find step and allow someone to say

```
if (!layout->hasDim("Pixel Number"))
    throw pdal_error("Filter requires Pixel Number dimension");
```

I suppose there is also an argument here that if I'm going to be building a filter off a particular dimension, that I should just go ahead and add it to the Dimension.json file and proceed with the usual logic of

```
if (!layout->hasDim(Dimension::Id::PixelNumber))
    throw pdal_error("Filter requires PixelNumber dimension");
```

**Comment by abellgithub** [comment]
Not sure what the issue is.  What's wrong with:

```
if (layout->findDim("foo") != Unknown)
   ...
```
?

**Comment by chambbj** [comment]
I guess this is fine. Most other filters doing something like this had used `hasDim` so I was just following their lead.
