### ISSUE TITLE
PDAL can't find files in current directory

### ISSUE THREAD

**Issue by kbevers** [PDAL/PDAL#1389]
A pipeline like

```
{
  "pipeline":[
    {
      "filename":"1607604_Norlev_DKTM2.las",
      "type":"readers.las"
    },
    {
      "type":"filters.reprojection",
      "in_srs":"EPSG:4094",
      "out_srs":"EPSG:25832"
    },
    {
      "type":"writers.las",
      "minor_version": 3,
      "filename":"1607604_Norlev_ETRS89_UTM32.las"
    }
  ]
}
```

results in the following error message:

```
C:\data\pilotdrone>pdal pipeline coordinate_transform_xy.json
PDAL: Unable to create open stream for '1607604_Norlev_DKTM2.las\1607604_Norlev_DKTM2.las' with error 'No such file or directory'
```

I run the ```pdal``` command from the same directory as both pipeline file and the input file is placed. If I change the filename line to:
```
      "filename":"./1607604_Norlev_DKTM2.las",
```
everything is fine. So somehow PDAL get's confused without some indication of which directory it should look in.

This is on windows.

**Comment by abellgithub** [comment]
I don't understand this issue.  You're going to have to provide more information about the locations of things.

Do your filenames start with a single quote?

**Comment by kbevers** [comment]
I just noticed that I wrote the wrong filename in the last code-snippet. Maybe that makes it less confusing. Anyway, here's the contents of the directory:

```
C:\data\pilotdrone>ls
1607604_Norlev_DKTM2.las   coordinate_transform_xy.json
```

Two files, a las-file and the pipeline file. No single-quotes in the filenames. That is what PDAL prints in the error message.

From the same directory, ```C:\data\pilotdrone``` I run 
```
C:\data\pilotdrone>pdal pipeline coordinate_transform_xy.json
```
and that's when I get 
```
C:\data\pilotdrone>pdal pipeline coordinate_transform_xy.json
PDAL: Unable to create open stream for '1607604_Norlev_DKTM2.las\1607604_Norlev_DKTM2.las' with error 'No such file or directory'
```

The way I read the error message is that PDAL is trying to read the file ```1607604_Norlev_DKTM2.las\1607604_Norlev_DKTM2.las```, that is a file called ```1607604_Norlev_DKTM2.las``` in the directory ```1607604_Norlev_DKTM2.las```.

Does that make sense to you?

**Comment by abellgithub** [comment]
The pipeline you posted has leading single quotes in the filenames.  Is that the actual pipeline in question?

**Comment by kbevers** [comment]
A yes, that was a stupid cut and paste error. It is fixed now. Sorry.

**Comment by kbevers** [comment]
I just tried this on OS X and can't reproduce it. Very likely a Windows-only issue.

**Comment by abellgithub** [comment]
@kbevers:
Think the problem is here: https://github.com/PDAL/PDAL/blob/master/src/util/FileUtils.cpp#L352-L371

This is code that I ripped from the tindex change you made.  Maybe I broke it.  Can you fix and add a test for windows?

**Comment by kbevers** [comment]
That might be it, yes. I'll give it a go. I've never made a test for PDAL before so I might ask for help with that at some point.

**Comment by abellgithub** [comment]
I think our current tests would have found this, but they tend to operate out of alternate directories, which probably means test files all have '/' in their names.  I can try to make a test this AM.  Thanks for finding this.

**Comment by kbevers** [comment]
I was just looking at how to create a test that would find this, and came to the same conclusion as you. The files will have to be in the working directory. 

I am trying to fix the code right now. If you can make a test that would be great.

**Comment by kbevers** [comment]
@abellgithub You had the test ready a few minutes before my PR. Good timing. Hopefully it works out.

**Comment by psawall** [comment]
![docker_nosuchfile](https://cloud.githubusercontent.com/assets/27730586/25133699/04fb2a06-2413-11e7-9695-017b7dd68763.PNG)
I seem to be having (what I believe to be) the exact same issue. I can't get any pipelines to run, because they can't seem to see the files...but when I pull the metadata for the files it can see them. What is going on and how can I fix it?

**Comment by abellgithub** [comment]
Please open a new ticket.
