### ISSUE TITLE
Build error for pcl plugin

### ISSUE THREAD

**Issue by loganbyers** [PDAL/PDAL#1409]
I can't build the PCL plugin using gcc 4.9.3 and cmake 2.8.12.2 on redhat. This is due to some stray(?) characters in `plugins/pcl/CMakeLists.txt` from a997e7f. It seems like they should have been commented out by @abellgithub.

Lines 43, 104, 131.

`CMake Error: Error in cmake code at /sw/pdal_/plugins/pcl/CMakeLists.txt:43:
Parse error.  Expected a command name, got unquoted argument with text "]]".
`

**Comment by abellgithub** [comment]
Those are cmake block comments, not supported in cmake 2.8.  Feel free to remove them in your local build.  They'll go away shortly.

**Comment by hobu** [comment]
Which distros would we leave behind if we were to make cmake 3.x+ required at this point?

**Comment by loganbyers** [comment]
#### Ubuntu
Trusty Tahr (14.04) and earlier are cmake 2.x
https://launchpad.net/ubuntu/+source/cmake
