### ISSUE TITLE
No way to get metadata from pipeline

### ISSUE THREAD

**Issue by abellgithub** [PDAL/PDAL#1414]
Seems like we should have a `--metadata` option for `pdal pipeline`.

**Comment by achidlow** [comment]
Is this related to the reason http://www.pdal.io/stages/filters.hexbin.html example no longer works? 
> In order to write out the metadata record, the pdal pipeline command must be invoked using the –pipeline-serialization option
The above option no longer seems to write out metadata to serialized pipeline, contrary to what is shown in the example output.

**Comment by abellgithub** [comment]
Yes.  I think it went away when we converted pipelines to JSON.  I'll try to fix this today.
