### ISSUE TITLE
Allow 'user_data' JSON object on any PDAL Stage

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#1427]
JSON doesn't have comments, but we need a way for upstream and downstream applications to communicate textual comments and maybe other JSON objects across pipeline invocations. A generic, dump-whatever-you-want object that can be attached to any/every node should do the trick.

**Comment by msmitherdc** [comment]
👍 
possible to get this in 1.4?

**Comment by abellgithub** [comment]
Don't understand this.  Can someone provide a use case?

**Comment by msmitherdc** [comment]
Yes, Chris Irwin provided some good examples where it would be useful to document in the pipeline why particular params are used especialy when the pipeline is kept around for repeated use.

**Comment by kbevers** [comment]
Also a 👍  from me. I keep a bunch of general use pipeline-files around, some of them fairly complicated. Right now it is only really possible to describe what they do via the filename. A comment at the start of a file would help a lot in that regard. @msmitherdc also has a good point about documenting why certain parameters are used.

**Comment by hobu** [comment]
There's two parts here. The first are simple comments, and the second is extension facility for other PDAL pipeline consumers/producers.

# Comments

The following pipeline translates some RXP files to LAS, and it does so with a few transformation filters. The order of the transformations matter, and it would be very helpful to be able to communicate what each matrix represents. 

```
{
  "pipeline":[
      {
          "type":"readers.rxp",
          "filename": "/data/scan.rxp"
      },
    {
      "type":"filters.transformation",
      "matrix":" 0.886021478 -0.463609330 -0.005685887 1001.767853725 0.463642504 0.885984748 0.008164234 927.201546884 0.001252594 -0.009869906 0.999950507 514.513223273 0.000000000 0.000000000 0.000000000 1.000000000",
      "comment":"Scanner's Own Coordinate System. Measured from blah blah and blah."
    },
    {
      "type":"filters.transformation",
      "matrix":"1.000000000 0.000000000 0.000000000 536000.000000000 0.000000000 1.000000000 0.000000000 7356000.000000000 0.000000000 0.000000000 1.000000000 0.000000000 0.000000000 0.000000000 0.000000000 1.000000000",
      "comment":"Geo Coordinate System. Measured from blah blah and blah."
    },
    {
      "type":"filters.colorinterp",
      "ramp":"pestel_shades",
      "minimum":0,
      "maximum":300
    } ,
    {
      "type":"writers.las",
      "a_srs":"EPSG:32624",
      "filename":"/data/helheim.las"
    }
  ]
}
```


# Extension

Other producers and consumers of PDAL pipeline do not have the ability to extend the objects in a way that will pass through PDAL's parser/validation. Other applications may wish to decorate their own JSON objects on top of PDAL's. The ability for them to be able to extend allows them to use PDAL's pipeline as their processing serialization and not require them to maintain a parallel serialization with their own extensions. We should investigate using whatever the current state-of-the-art is for JSON extension approaches. Some sort of self-assigned key to prevent people's applications/objects from stepping on each other might be needed. Consider the following as a straw man. 

```
{
  "pipeline":[
    {
        "type":"readers.las",
        "filename":"duck-filtered.laz"
        "extension":{"owner":"howard", {"something":[1, 2, 3, 4], "something else":"text"}},
    },
    {
        "type":"writers.gdal",
        "radius":6.5,
        "dimension":"Intensity",
        "resolution":2,
        "nodata":-8888,
        "filename":"haloe.tif",
        "extension":{"owner":"howard", {"grid-thing":["first", "second", "third"], "key":"value"}},
    }
  ]
}
```

**Comment by hobu** [comment]
More background about the ``extension`` item. An application that wraps PDAL pipelines, like say a GUI application with buttons, settings, and defaults, has only one choice today for how it wraps pipelines -- it needs to maintain a separate copy of the pipeline and one of all of the application's stages/settings, and then when asked, serialize a PDAL-valid pipeline to feed into the application or API or whatever.

These kinds of applications might carry a lot of their own per-stage information -- it's hard to know what exactly. A simple free-for-all extension mechanism will allow these folks to continue to utilize PDAL pipeline as their serialization rather than maintaining *two* serializations -- one of a valid pipeline/tree and another of all of their application settings, data, etc. 

The only thing PDAL needs to do here is:
* Not complain when it sees an ``extension`` JSON object on any node
* Describe in the spec how apps are supposed to participate with the ``extension`` block so they don't step on each other.

**Comment by hobu** [comment]
#1434 is the implementation that transparently allows this, and so the question is simply what's the agreed upon name for the option that any application can pass into PDAL and not have the parser complain.

I propose we have a single `application` member, and if you want comments or objects or whatever, they're available as the `Stage::getApplicationData()` member.
