### ISSUE TITLE
CMake Error LASZIP_LIBRARY set to NOTFOUND

### ISSUE THREAD

**Issue by ilovezfs** [PDAL/PDAL#1446]
Despite passing `-DWITH_LASZIP=FALSE`, if laszip is not installed, the build fails with
```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LASZIP_LIBRARY
    linked by target "pdalcpp" in directory /tmp/pdal-20161215-22167-1qwb7g7

-- Configuring incomplete, errors occurred!
See also "/tmp/pdal-20161215-22167-1qwb7g7/CMakeFiles/CMakeOutput.log".
/usr/local/Homebrew/Library/Homebrew/debrew.rb:11:in `raise'
```
This affects 1.4.0 and HEAD.

If laszip is installed, then the build proceeds, but laszip ends up linked even though `-DWITH_LASZIP=FALSE` was passed.

I can workaround this by
```
inreplace "CMakeLists.txt", "        ${LASZIP_LIBRARY}\n", ""
```
to disable laszip.

Full build log: https://gist.github.com/ilovezfs/888105f8e980db68bb27ec4ff2cf605a
cmake -LAH: https://gist.github.com/ilovezfs/90619fbfb84157c8f6484a2685059cf3

**Comment by hobu** [comment]
Thanks for the report! It has been fixed in both `1.4-maintenance` and `master` branches.

**Comment by ilovezfs** [comment]
@hobu this still seems to be an issue when laszip is not installed:
```
-- Configuring done
CMake Error in CMakeLists.txt:
  Target "pdalcpp" INTERFACE_INCLUDE_DIRECTORIES property contains path:

    "/tmp/pdal-20170407-16081-10ujjgw/LASZIP_INCLUDE_DIR-NOTFOUND"

  which is prefixed in the build directory.
```

**Comment by ilovezfs** [comment]
Opened https://github.com/PDAL/PDAL/issues/1558.
