### ISSUE TITLE
Add support for EC2 Instance Profiles for S3 access

### ISSUE THREAD

**Issue by msmitherdc** [PDAL/PDAL#1448]
For AWS S3 Access, access credentials aren't always available directly and need to be invoked via Instance Profiles. Currently the AWS SDKs do this automatically. Not sure the best way to do with with curl and without the SDKs.

**Comment by hobu** [comment]
This will need to be implemented upstream in connormanning/arbiter#8 and then integrated

**Comment by hobu** [comment]
This is now done and incorporated in the embedded arbiter tree.
