### ISSUE TITLE
Filter to compare dimensions

### ISSUE THREAD

**Issue by chambbj** [PDAL/PDAL#1466]
I started in on writing a filter that would extract last returns (assuming `ReturnNumber` and `NumberOfReturns` are available), but it would be equally viable to return only first returns, intermediate returns, etc. Locking this into the given dimension names also loosely implies that the source data will be LAS.

A more generalized approach would be to create a filter, similar to the range filter in some regards, that accepts some form of an expression to compare dimensions, like `ReturnNumber=NumberOfReturns` for last returns.

First returns and single returns are already possible with the range filter, `ReturnNumber[1:1]` or `NumberOfReturns[1:1]` respectively.

Question is, do others have a use for such a generalized approach (perhaps with different dimensions)?

**Comment by hobu** [comment]
We have typically done these kinds of things with filters.programmable for a generic approach.

**Comment by chambbj** [comment]
Ah yes. I meant to look into this last week and forgot! Found the last return example https://github.com/PDAL/PDAL/blob/master/test/data/pipeline/predicate-keep-last-return.json.in, which is only marginally slower than the dedicated filter I'd written.
