### ISSUE TITLE
Python PDAL Troubleshooting after install or misunderstanding on my side

### ISSUE THREAD

**Issue by marcel-bariou** [PDAL/PDAL#1472]
PDAL 1.4 compile on Fedora 22 it was correct. I setup the python module in two ways , from the local directory of PDAL source, and after failure from GITHUB each time egg archive is installed in site-packages of python. I extract the egg file to have pdal directory and pdal.egg-info directory, and I run an example similar to yours :

"""
Created on Fri Jan 13 11:56:59 2017

@author: mbariou
"""
```
json = """
{
  "pipeline": [
    "simple.las",
    {
        "type": "filters.sort",
        "dimension": "X"
    }
  ]
}"""
import pdal
pipeline = pdal.Pipeline(pipeline)
pipeline.validate() # check if our JSON and options were good
pipeline.loglevel = 9 #really noisy
count = pipeline.execute()
arrays = pipeline.arrays
metadata = pipeline.metadata
log = pipeline.log`
 ```

each time I have the failure message :

> Traceback (most recent call last):
> File "<ipython-input-10-e493d53d8fd1>", line 18, in <module>
>     import pdal
> 
>   File "/usr/lib64/python2.7/site-packages/pdal/__init__.py", line 3, in <module>
>     from .pipeline import Pipeline
> 
>   File "/usr/lib64/python2.7/site-packages/pdal/pipeline.py", line 2, in <module>
>     from pdal import libpdalpython
> ImportError: libpdal_base.so.4: cannot open shared object file: No such file or directory

I created symbolic link to /usr/local/lib/ibpdal_base.so.4, inside pdal module and inside site-packages , no more progress. Some hints will help. Thanks

**Comment by marcel-bariou** [comment]
Add library path in /etc/ld.so.conf.d/xxxx.conf
Add your path (one per line) whatever are your library e.g 

> /us/local/lib
> /usr/local/lib64

**Comment by lytk01** [comment]
Add library path in /etc/ld.so.conf.d/xxxx.conf
Add your path (one per line) whatever are your library e.g
```
/us/local/lib
/usr/local/lib64
```

and then
`ldconfig`

thank you @marcel-bariou
