### ISSUE TITLE
Support building libpdal-plang for both Python 2 & Python 3

### ISSUE THREAD

**Issue by sebastic** [PDAL/PDAL#1478]
Triggered by the recent [PDAL Python3 issues](https://lists.osgeo.org/pipermail/pdal/2017-January/001120.html) thread, it would be great if libpdal-plang can be built with both Python 2 & Python 3.

This allows packagers to offer python-pdal packages for both Python 2 & Python 3.

Building libpdal-plang always with Python 2, and building libpdal-plang3 always with Python 3 would be an option. Depending on the configure options, either one or both can be built.

**Comment by hobu** [comment]
There are some challenges that would need to be overcome to do this:

1) PDAL *embeds* Python. The `filters.programmable` and `filters.predicate` filters us Python and Numpy to allow users to filter data.  

2) PDAL *extends* Python. The [extension](http://pypi.python.org/pypi/pdal) allows users to orchestrate PDAL pipeline operations using Python objects. 

3) libpdal-plang currently [checks](https://github.com/PDAL/PDAL/blob/master/pdal/plang/Environment.cpp#L112) if it is active, and if not, imports a custom extension to support log stream redirection so users can ``print()`` into the PDAL log if they wish during execution.

4) libpdal-plang always [import_array](https://github.com/PDAL/PDAL/blob/master/pdal/plang/Environment.cpp#L109) on initialization. `import_array` is always version-specific to which Python it was compiled for as far as I know.

I'm happy to try to reorganize things, but I'm not sure how we can satisfy you with the current arrangement.

**Comment by hobu** [comment]
Closing this for now. If someone wants to take on the heavy lift to allow this to happen, we'll be happy to merge a patch.
