### ISSUE TITLE
Fails to build with GCC 7

### ISSUE THREAD

**Issue by sebastic** [PDAL/PDAL#1484]
As reported by Matthias Klose in [Debian Bug #853602](https://bugs.debian.org/853602):
> The package fails to build in a test rebuild on at least amd64 with
> gcc-7/g++-7, but succeeds to build with gcc-6/g++-6. The
> severity of this report may be raised before the buster release.
> There is no need to fix this issue in time for the stretch release.
>
> The full build log can be found at:
> http://people.debian.org/~doko/logs/gcc7-20170126/pdal_1.4.0-1_unstable_gcc7.log
> The last lines of the build log are at the end of this report.
>
> To build with GCC 7, either set CC=gcc-7 CXX=g++-7 explicitly,
> or install the gcc, g++, gfortran, ... packages from experimental.
>
>   apt-get -t experimental install g++
>
> Common build failures are new warnings resulting in build failures with
> -Werror turned on, or new/dropped symbols in Debian symbols files.
> For other C/C++ related build failures see the porting guide at
> http://gcc.gnu.org/gcc-7/porting_to.html
>
> ```
> [...]
>       ^
> In file included from /<<PKGBUILDDIR>>/vendor/arbiter/arbiter.cpp:43:0:
> /<<PKGBUILDDIR>>/vendor/arbiter/arbiter.hpp:223:20: note: candidate: pdal::arbiter::http::Response pdal::arbiter::http::Resource::exec(int)
>      http::Response exec(std::function<http::Response()> f);
>                     ^~~~
> /<<PKGBUILDDIR>>/vendor/arbiter/arbiter.hpp:223:20: note:   no known conversion for argument 1 from 'pdal::arbiter::http::Resource::post(std::__cxx11::string, const std::vector<char>&, pdal::arbiter::http::Headers, pdal::arbiter::http::Query)::<lambda()>' to 'int'
> /<<PKGBUILDDIR>>/vendor/arbiter/arbiter.cpp: At global scope:
> /<<PKGBUILDDIR>>/vendor/arbiter/arbiter.cpp:2972:10: error: prototype for 'pdal::arbiter::http::Response pdal::arbiter::http::Resource::exec(std::function<pdal::arbiter::http::Response()>)' does not match any in class 'pdal::arbiter::http::Resource'
>  Response Resource::exec(std::function<Response()> f)
>           ^~~~~~~~
> In file included from /<<PKGBUILDDIR>>/vendor/arbiter/arbiter.cpp:43:0:
> /<<PKGBUILDDIR>>/vendor/arbiter/arbiter.hpp:223:20: error: candidate is: pdal::arbiter::http::Response pdal::arbiter::http::Resource::exec(int)
>      http::Response exec(std::function<http::Response()> f);
>                     ^~~~
> vendor/arbiter/CMakeFiles/pdal_arbiter.dir/build.make:65: recipe for target 'vendor/arbiter/CMakeFiles/pdal_arbiter.dir/arbiter.cpp.o' failed
> make[4]: *** [vendor/arbiter/CMakeFiles/pdal_arbiter.dir/arbiter.cpp.o] Error 1
> make[4]: Leaving directory '/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu'
> CMakeFiles/Makefile2:3883: recipe for target 'vendor/arbiter/CMakeFiles/pdal_arbiter.dir/all' failed
> make[3]: *** [vendor/arbiter/CMakeFiles/pdal_arbiter.dir/all] Error 2
> make[3]: *** Waiting for unfinished jobs....
> [  3%] Linking CXX static library ../../lib/libpdal_boost.a
> cd /<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/vendor/pdalboost && /usr/bin/cmake -P CMakeFiles/pdal_boost.dir/cmake_clean_target.cmake
> cd /<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/vendor/pdalboost && /usr/bin/cmake -E cmake_link_script CMakeFiles/pdal_boost.dir/link.txt --verbose=1
> /usr/bin/ar qc ../../lib/libpdal_boost.a  CMakeFiles/pdal_boost.dir/libs/system/src/error_code.cpp.o CMakeFiles/pdal_boost.dir/libs/filesystem/src/codecvt_error_category.cpp.o CMakeFiles/pdal_boost.dir/libs/filesystem/src/operations.cpp.o CMakeFiles/pdal_boost.dir/libs/filesystem/src/path.cpp.o CMakeFiles/pdal_boost.dir/libs/filesystem/src/path_traits.cpp.o CMakeFiles/pdal_boost.dir/libs/filesystem/src/portability.cpp.o CMakeFiles/pdal_boost.dir/libs/filesystem/src/unique_path.cpp.o CMakeFiles/pdal_boost.dir/libs/filesystem/src/utf8_codecvt_facet.cpp.o
> /usr/bin/ranlib ../../lib/libpdal_boost.a
> make[4]: Leaving directory '/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu'
> [  3%] Built target pdal_boost
> [  3%] Linking CXX executable ../bin/dimbuilder
> cd /<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/dimbuilder && /usr/bin/cmake -E cmake_link_script CMakeFiles/dimbuilder.dir/link.txt --verbose=1
> /usr/bin/c++   -g -O2 -fdebug-prefix-map=/<<PKGBUILDDIR>>=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wdate-time -D_FORTIFY_SOURCE=2 -Wextra -Wall -Wno-unused-parameter -Wno-unused-variable -Wpointer-arith -Wcast-align -Wcast-qual -Wredundant-decls -Wno-long-long -Wno-unknown-pragmas -Wno-deprecated-declarations -isystem /usr/local/include -std=c++11 -Wextra -Wall -Wno-unused-parameter -Wno-unused-variable -Wpointer-arith -Wcast-align -Wcast-qual -Wredundant-decls -Wno-long-long -Wno-unknown-pragmas -Wno-deprecated-declarations -isystem /usr/local/include -std=c++11 -O2 -g -DNDEBUG  -specs=/usr/share/dpkg/no-pie-link.specs -Wl,-z,relro -Wl,-z,now CMakeFiles/dimbuilder.dir/DimBuilder.cpp.o CMakeFiles/dimbuilder.dir/__/pdal/util/Utils.cpp.o  -o ../bin/dimbuilder -rdynamic -ljsoncpp -ldl
> make[4]: Leaving directory '/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu'
> [  3%] Built target dimbuilder
> [  3%] Linking CXX static library ../../lib/libgtest.a
> cd /<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/vendor/gtest && /usr/bin/cmake -P CMakeFiles/gtest.dir/cmake_clean_target.cmake
> cd /<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/vendor/gtest && /usr/bin/cmake -E cmake_link_script CMakeFiles/gtest.dir/link.txt --verbose=1
> /usr/bin/ar qc ../../lib/libgtest.a  CMakeFiles/gtest.dir/src/gtest-all.cc.o
> /usr/bin/ranlib ../../lib/libgtest.a
> make[4]: Leaving directory '/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu'
> [  3%] Built target gtest
> make[3]: Leaving directory '/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu'
> Makefile:163: recipe for target 'all' failed
> make[2]: *** [all] Error 2
> make[2]: Leaving directory '/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu'
> dh_auto_build: make -j64 returned exit code 2
> debian/rules:47: recipe for target 'override_dh_auto_build' failed
> make[1]: *** [override_dh_auto_build] Error 2
> make[1]: Leaving directory '/<<PKGBUILDDIR>>'
> debian/rules:16: recipe for target 'build' failed
> make: *** [build] Error 2
> dpkg-buildpackage: error: debian/rules build gave error exit status 2
> ```

**Comment by sebastic** [comment]
Full build log: [pdal_1.4.0-1_unstable_gcc7.txt](https://github.com/PDAL/PDAL/files/742805/pdal_1.4.0-1_unstable_gcc7.txt)

All errors in the build log are for the arbiter embedded copy.

**Comment by abellgithub** [comment]
@connormanning: Can this be closed?
