### ISSUE TITLE
Georeferencing Point Cloud

### ISSUE THREAD

**Issue by ryokochang** [PDAL/PDAL#1499]
Hello, guys

I was studying the workshop files, because I'm trying to build a point cloud using the points data from a Velodyne VLP 16 Lidar with a GPS connected. 
I noticed that one of the exercises uses a file named S1C1_csd_004.csd that contains some airborne data. That is exactly the type of file that I wanted to analyze, because I have no idea how the structure of such file has to be. 
My LiDAR outputs a point cloud file (.csv) for each frame and another file that contains all the GPS positions.
I have no idea what to do with those file. I think I have to merge them, making correlations between the point and the GPS coordinates by their timestamp. I really don't know.

Anyone has access to the S1C1_csd_004.csd file, so I could see its structure I maybe understand what I have to do?

**Comment by hobu** [comment]
It is in the PDAL [workshop materials](http://www.pdal.io/workshop/agenda.html#materials).

https://s3.amazonaws.com/pdal/workshop/PDAL.zip
