### ISSUE TITLE
filters.attribute documentation updates

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#1510]
- [x] remove filters.attribute html from aws s3 bucket
- [x] add filters.assign docs
- [x] add filters.overlay docs
- [x] update workshop and tutorials with references to filters.attribute

**Comment by abellgithub** [comment]
I'm not sure what's being requested here.  We already have docs for filters.assign and filters.overlay and the doc for filters.attribute has already been removed from master.

**Comment by hobu** [comment]
when a document is removed, the generated output must also be manually removed from the deployment location. At the moment, when PDAL's docs are deployed, the `aws s3 sync` does not do an exact mirror to prevent removing something unintentionally.
