### ISSUE TITLE
tindex w/o hexer fails awkwardly, need better error message

### ISSUE THREAD

**Issue by mrosen** [PDAL/PDAL#1532]
```
pdal tindex --tindex C18075.sqlite  --filespec C18075.las -f SQLite
PDAL: Couldn't create filter stage of type 'filters.hexbin'.
```
this is caused b/c I didn't build with hexer.  We should handle this more gracefully.  Perhaps just a new error message.  Something like
PDAL:  Couldn't create filter stage of type 'filters.hexbin.'  Try adding '--fast_boundary' or rebuilding with hexer.

**Comment by hobu** [comment]
PR submitted in #1533
