### ISSUE TITLE
Poisson outputs only vertices rather the mesh itself?

### ISSUE THREAD

**Issue by y22ma** [PDAL/PDAL#1553]
Seems like an odd choice, considering poisson reconstruction is intended for computing a surface model (mesh) rather than pointclouds.

Is there plan to add the ability to output a mesh file (stl, obj, etc)?

**Comment by abellgithub** [comment]
Yes.  I'm not sure why we're doing what we're currently doing.  @chambbj ?

**Comment by chambbj** [comment]
@y22ma We are not using the surface reconstruction filters at the moment. I added them some time ago now, mostly as an exercise. That being said, you should be able to put something together using existing PCL capabilities, e.g., https://github.com/PointCloudLibrary/pcl/blob/master/io/include/pcl/io/obj_io.h#L333-L342. Patches and other insights into how PDAL can better support this type of application are always welcome.

**Comment by abellgithub** [comment]
Fixed with new filters.poisson.

**Comment by khelkun** [comment]
> Fixed with new filters.poisson.
@abellgithub 
I guess it's fixed but the the [meshing exercise](https://pdal.io/en/latest/workshop/generation/meshing/meshing.html) confused me. With this exercise, one obtains a  PLY which does not contain a surface mesh but a point cloud.

One must add the `--writers.ply.faces=true` to obtain a surface mesh PLY:
```
pdal translate -i ./exercises/analysis/clipping/stadium.copc.laz \
-o ./exercises/analysis/meshing/first-mesh.ply \
poisson --filters.poisson.depth=16 \
--writers.ply.faces=true \
--verbose 4
```

Or it worked out for me with the equivalent pipeline:
```
[
    "./exercises/analysis/clipping/stadium.copc.laz",
    {
        "type":"filters.poisson"
    },
    {
        "type":"writers.ply",
        "faces":true,
        "filename":"./exercises/analysis/meshing/first-mesh.ply"
    }
]
```
N.B: with the pipeline [the default value is 8 for the depth option of the poisson filter](https://pdal.io/en/latest/stages/filters.poisson.html#options).
