### ISSUE TITLE
pdal translate in.las out.sqlite fails

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#1560]
`pdal translate test/data/las/1.2-with-color.las out.sqlite` <-- fails with Unexpected argument 'filename'

`pdal translate test/data/las/1.2-with-color.las out.sqlite --writers.sqlite.connection=out.sqlite` <-- fails with Unexpected argument 'filename'

`pdal translate test/data/las/1.2-with-color.las --writers.sqlite.connection=out.sqlite` <-- fails with Missing value for positional argument 'output'

**Comment by abellgithub** [comment]
@hobu: Do you want me to look at this?

**Comment by hobu** [comment]
Yeah. It's still confusing about `filename` and its relation to drivers with `pdal translate`.

**Comment by abellgithub** [comment]
This will still fail without explicitly setting the block table name and cloud table name, but the filename issue is fixed.

**Comment by hobu** [comment]
I like the solution. Thanks.
