### ISSUE TITLE
Multiband output in writers.gdal

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#1561]
The `writers.gdal` driver needs to support multiband output so we can rasterize multiple bands at once. A scenario where this would be immediately useful is the rasterization of Red, Green, and Blue dimensions into 8-bit color bands.

**Comment by hobu** [comment]
It's easier to script this and not have the complexity in PDAL.

Here's a bash script that coordinates it with GDAL
```
export PDAL_DRIVER_PATH=/Users/hobu/dev/git/pdal/lib
export PATH=/Users/hobu/dev/git/pdal/bin:$PATH


read -d '' pipeline <<"EOF"
{
    "pipeline": [
        {
            "filename":"input2.laz",
            "type":"readers.las"
        },
        {
            "filename":"output.tif",
            "output_type":"max",
            "resolution":"2.0",
            "type": "writers.gdal"
        }
    ]
}
EOF

echo $pipeline

input=$1
dry=false

dimensions=("Red" "Green" "Blue")
tifs=()
for dimension in "${dimensions[@]}"
do

fname=$(basename "$input")
fbname=${fname%.*}

output="$fbname.$dimension.tif"
tifs+=("$output")
command="pdal pipeline -i gdal.json --debug --writers.gdal.dimension=$dimension --readers.las.filename=./$input --writers.gdal.filename=./$output"
echo $command
if [[ "$dry" == "false" ]]
then
$command
fi
done;

tifoutput="$input.combined.tif"
coloroutput="$input.colored.tif"
fnames=$(printf "%s " "${tifs[@]}")
mergecommand="gdal_merge.py -separate ${fnames[@]} -o $tifoutput"
echo $mergecommand
translatecommand="gdal_translate -co PHOTOMETRIC=RGB  $tifoutput  $coloroutput"
echo $translatecommand

if [[ "$dry" == "false" ]]

then
$mergecommand
$translatecommand
fi
```

**Comment by fwrite** [comment]
A short note for those looking into a similar solution: combining these steps in PDAL is currently not possible.

To save some time on reading the point cloud (especially on the LAZ decompression) I tried to [chain various exports in the pipeline](https://github.com/PDAL/PDAL/files/2575590/pipeline.txt) overwriting the filenames by parameter substitution.
As mentioned in #1386 this is impossible and you will ***not*** get a warning about this (#1538).

**Comment by fwrite** [comment]
> As a special case, writers can be chained. Just place them one after the other in the pipeline:
> [...]
> However, you cannot create bands for different variables in the same output file. Perhaps you can use a utility program to combine the outputs.

With PDAL 1.7.2 (a8e86bddc11e8d5b2adeeba8fcb705c2c5d2a7ea), using
[this pipeline](https://github.com/PDAL/PDAL/files/2576400/pipeline.txt),
 I get the following error, related to a missing dimension when chaining the writers: `PDAL: writers.gdal: Specified dimension 'nn_z' does not exist.`.

This would be a bug then?
