### ISSUE TITLE
PDAL: filters.outlier: Unexpected argument 'extract'.

### ISSUE THREAD

**Issue by nielsin** [PDAL/PDAL#1564]
When using [filters.outlier](https://www.pdal.io/stages/filters.outlier.html) PDAL 1.5 (through docker) I get the error message:

`PDAL: filters.outlier: Unexpected argument 'extract'.`

My question on [stackoverflow](http://stackoverflow.com/q/43441446/3573243) has some more details.

**Comment by abellgithub** [comment]
The message is correct.  The argument is no longer supported.  @chambbj: can you comment on current behavior and update the docs?

**Comment by nielsin** [comment]
Ok, thank you

**Comment by chambbj** [comment]
No problem. Also, SO answer posted here http://stackoverflow.com/a/43442320/1620549.
