### ISSUE TITLE
PDAL: filters.pmf: Unexpected argument 'classify'.

### ISSUE THREAD

**Issue by nielsin** [PDAL/PDAL#1565]
When using [filters.pmf](https://www.pdal.io/stages/filters.pmf.html) PDAL 1.5 (through docker) I get the error message:

`PDAL: filters.pmf: Unexpected argument 'classify'.`

**Comment by abellgithub** [comment]
The message is correct.  The argument is no longer supported.  @chambbj: can you comment on current behavior and update the docs?

**Comment by chambbj** [comment]
Yes, the release notes covered this, but I missed it in the docs (will
update them tomorrow). These filters now only classify points. To extract,
a range filter is required.

**Comment by nielsin** [comment]
Thank you!
