### ISSUE TITLE
writers.ply does not follow readers.ply file structure

### ISSUE THREAD

**Issue by alexsmartens** [PDAL/PDAL#1570]
Hi there,
I am interested in using Poisson sampling. 
This is the command I am intending to use:

`$ pdal translate --writers.ply.storage_mode="ascii" pt_original_downsample.ply pt_original_downsample2.ply -f filters.sample --filters.sample.radius="0.5"`

So far, I have a mini problem with coupling writers.ply & readers.ply

-- here is my initial ply structure (input for readers.ply):

```
ply
format ascii 1.0
comment VCGLIB generated
element vertex 8192
property float x
property float y
property float z
property uchar red
property uchar green
property uchar blue
property uchar alpha
element face 0
property list uchar int vertex_indices
end_header
-0.573693 -0.255396 -1.55488 107 77 47 255
...
```

-- here is my final ply structure (output of writers.ply):

```
ply
format ascii 1.0
comment Generated by PDAL
element vertex 38
property uint8 Alpha
property uint8 Blue
property uint8 Green
property uint8 Red
property float32 X
property float32 Y
property float32 Z
property uint8 Classification
end_header
255 31 59 74 -0.526698 -0.011267 0.481901 0
...
```

My problem is that the output property names are written in capitals. 
Because of that, Mashlab does not recognise output PLY files.

How is it possible to keep the initial PLY structure (property names, types and order) for the output PLY file?

**Comment by abellgithub** [comment]
At the current time, no.  You could hand-edit the file for capitalization or run it through a sed script.  The code change to allow better control isn't difficult if you'd like to tackle it.

That said, this seems like a shortcoming in the PLY reader in meshlab.

**Comment by alexsmartens** [comment]
Thank you for your explanation, Andrew
