### ISSUE TITLE
Error with clipping function "overlay" - can't find polygon

### ISSUE THREAD

**Issue by Mathvarin** [PDAL/PDAL#1580]
Hello,

I did a lot a tests and I was not able to find a solution. I am trying to do the overlay example with my own polygon but it doesn't work! I tried with a .vrt and a .shp. See the code here :

![error](https://cloud.githubusercontent.com/assets/28075022/25548973/22428be0-2c3d-11e7-9248-ed9f267269cf.png)

Here is the json :
```
{
    "pipeline": [
        "/data/Las_villeQc/13_2485188f07_dc.las",
        {
            "type": "filters.overlay",
            "dimension": "Classification",
            "datasource": "/data/Las_villeQc/attributes.vrt",
            "layer": "polygon",
            "column": "Id"          
            
        },
        
        "/data/Las_villeQc/13_2485188f07_decoupe.las"
        
    ]
}
```
Here is the .vrt :

```
<OGRVRTDataSource>
        <OGRVRTWarpedLayer>
            <OGRVRTLayer name="polygon">
                <SrcDataSource>/data/Las_villeQc/polygon.json</SrcDataSource>
                <LayerSRS>EPSG:4326</LayerSRS>
            </OGRVRTLayer>
            <TargetSRS>+proj=lcc +lat_1=43 +lat_2=45.5 +lat_0=41.75 +lon_0=-120.5 +x_0=399999.9999999999 +y_0=0 +ellps=GRS80 +units=ft +no_defs</TargetSRS>
        </OGRVRTWarpedLayer>
    </OGRVRTDataSource>
```

Could it be the projection? Sometimes I don't have an error, but no .las was created.

Thank you for your help

Mathieu

**Comment by hobu** [comment]
What does `ogrinfo attributes.vrt` report? I suppose it is possible the VRT isn't valid and we aren't properly reporting the error.

**Comment by Mathvarin** [comment]
Hello,
sorry I forgot to say we are working with the docket toolbox. Is gdal installed in this docker? How can we use ogrinfo attributes.vrt in the command line? Thank you.

**Comment by hobu** [comment]
The [PDAL docker image](https://hub.docker.com/r/pdal/pdal/) does have GDAL installed.
