### ISSUE TITLE
Curious Behaviour for pdal_plang for Python Extension

### ISSUE THREAD

**Issue by marcel-bariou** [PDAL/PDAL#1582]
On linux 4.8.13 FEDORA 23, with CMAKE When I build without PostGres or Sqlite, libpdal_plang is not created and I can't install the python extension this library is missing. Some hint Thanks!

**Comment by hobu** [comment]
You have to make sure to enable `-DBUILD_PLUGIN_PYTHON=ON` during your CMake configuration, and you need to make sure that the python-devel package and numpy-devel packages are available to provide headers to compile against.

See PDAL's [Travis configuration](https://github.com/PDAL/PDAL/blob/master/scripts/ci/script.sh) for CMake inspiration.
