### ISSUE TITLE
Interface compiler definitions are not populated

### ISSUE THREAD

**Issue by gadomski** [PDAL/PDAL#1608]
Given a (stripped down for example purposes) downstream project with the following `CMakeLists.txt`:

```cmake
cmake_minimum_required(VERSION 3.8)
project(pdal-downstream)
find_package(PDAL REQUIRED)
add_executable(pdal-downstream main.cpp)
target_link_libraries(pdal-downstream PRIVATE ${PDAL_LIBRARIES})
target_include_directories(pdal-downstream PRIVATE ${PDAL_INCLUDE_DIRS})
```

And the following `main.cpp`:

```cpp
#include <pdal/io/LasReader.hpp>

int main(int argc, char** argv) {
	return 0;
}
```

A Windoze build fails with an error

```
1>C:\Users\RDCRLPJG\local\include\pdal/util/ProgramArgs.hpp(1238): error C2589: '(': illegal token on right side of '::'
1>C:\Users\RDCRLPJG\local\include\pdal/util/ProgramArgs.hpp(1238): error C2062: type 'unknown-type' unexpected
1>C:\Users\RDCRLPJG\local\include\pdal/util/ProgramArgs.hpp(1238): error C2059: syntax error: ')'
```

and a bunch of warnings. To fix the error, the downstream user needs to define `NOMINMAX`. While a downstream user can figure out the fix hersef, this seems a bit burdensome and introduces unnecessary friction to our API usage.

PDAL defines `NOMINMAX` in a [win32-specific configuration file](https://github.com/PDAL/PDAL/blob/master/cmake/win32_compiler_options.cmake#L23), along with other helpful defines (there is an [analogous Unix configuration script](https://github.com/PDAL/PDAL/blob/master/cmake/unix_compiler_options.cmake)). This script uses `add_definitions`, which [populates `COMPILE_DEFINITIONS` on the directory it is called within](https://cmake.org/cmake/help/v3.0/command/add_definitions.html), but does not touch the [interface compile definitions](https://cmake.org/cmake/help/v3.0/prop_tgt/INTERFACE_COMPILE_DEFINITIONS.html), meaning that downstream projects do not get to inherit all of these helpful definitions.

To me, it makes sense to populate not only the `COMPILE_DEFINITIONS` but also `INTERFACE_COMPILE_DEFINITIONS` using [`target_compile_definitions(PUBLIC)`](https://cmake.org/cmake/help/v3.0/command/target_compile_definitions.html). However, at the [current point that the compiler definitions are included](https://github.com/PDAL/PDAL/blob/master/CMakeLists.txt#L12), the targets of interest are not defined.

I'll plan at taking a stab tomorrow at refactoring the CMake to set those compile definitions on targets instead of on directories, but wanted to open this issue to document the problem and provide a point of reference.

*Edit: cc @pjh172*

**Comment by abellgithub** [comment]
As a follow-up... The changes in this ticket caused undesired behavior for some users.  Pushing compiler switches and options downstream to projects using PDAL isn't what many want.  The initial issue brought up by this ticket (NOMINMAX) can be fixed by sticking () around std::min, which inhibits macro expansion and also eliminates the need for NOMINMAX.
