### ISSUE TITLE
filters.colorinterp: make compatible with --stream in some cases

### ISSUE THREAD

**Issue by Groutcho** [PDAL/PDAL#1609]
I understand that `filters.colorinterp` relies on loading the entire dataset when computing standard deviation or when the minimum and maximum value for the specified dimension is not known in advance, but would it be possible to make this filter compatible with the `--stream` option if `minimum` and `maximum` are provided ? This would be incredibly helpful !

**Comment by hobu** [comment]
> but would it be possible to make this filter compatible with the `--stream` option if `minimum` and `maximum` are provided ?

Yes that should be straightforward to implement. We would be happy to incorporate a patch that provided it.
