### ISSUE TITLE
Mark formats as built-in or optional

### ISSUE THREAD

**Issue by mloskot** [PDAL/PDAL#1612]
Following up https://lists.osgeo.org/pipermail/pdal/2017-June/001309.html

As explained by @chambbj, from a source tree perspective, if formats are in the `io` folder, then they are built-in, and anything else would be relegated to the `plugins` folder.

It would be useful to tag readers/writers in the docs with something like:

> built-in: yes

and

> built-in: optional

Or alternative indicator (Suggestions?)

**Comment by mloskot** [comment]
@hobu Awesome, thank you! TBH, I was not brave to get around the advanced Sphinx.

**Comment by hobu** [comment]
Yes. The worst part was keeping te latex builder happy. The output looks quite good now and will be up when 1.6 website is pushed.
