### ISSUE TITLE
option to specify separator character in readers.text

### ISSUE THREAD

**Issue by mikeskaug** [PDAL/PDAL#1630]
I wonder if it would be useful to allow users to specify a custom separator character when using the text reader. For example:
```
{
            "type": "readers.text",
            "filename": "tmpfile",
            "separator":","
}
```

I know it would help us. The source data that we're reading has field names like `LONGITUDE_CENTROID` and `LONGITUDE_LOW` and unfortunately first field name is `LVIS_LFID`, so pdal identifies the underscore as the field separator, when in fact it should be a comma. (You may notice that this is ilvis2 data, which there is also a reader for, readers.ilvis2, but we are augmenting the data with several additional fields, so we're falling back on using the text reader.) We could just rename the fields to eliminate the underscores, but we want to keep it as similar to the original source data as possible.

**Comment by hobu** [comment]
There is a `separator` option currently, have you tried it? 

https://github.com/PDAL/PDAL/blob/master/io/TextReader.cpp#L90

**Comment by mikeskaug** [comment]
How about that! I've just been going off of this - https://www.pdal.io/stages/readers.text.html
Thanks for pointing that out.

**Comment by hobu** [comment]
Docs still need fixing...
