### ISSUE TITLE
pdal::SpatialReference should be thread safe

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#1631]
PDAL uses GDAL's OSRSpatialReference for backing its coordinate system description, and this isn't thread safe. Upstream users don't know when we're creating/destroying these things, and they have to randomly sprinkle locks around to try to protect against it.

`pdal::SpatialReference` should take responsibility for managing its own lock of usage/creation/deletion of `OGRSpatialReference/H`.

**Comment by abellgithub** [comment]
I don't think that there is any evidence that SpatialReference isn't threadsafe.  I recommend closing.
