### ISSUE TITLE
Implement Greyhound's filter operations for filters.range

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#1635]
There's a fine line between providing a full programming language (`filters.python`) and simple data filtering in PDAL. `filters.range` isn't as convenient as it could be.

Implementing [Greyhounds filters](https://github.com/hobu/greyhound/blob/master/doc/clientDevelopment.rst#filters) could provide that convenience and expressiveness without burying a full language implementation in PDAL. 
```
{"$or":[
    {"Red":{"$gt":200}},
    {"Blue":{"$gt":120,"$lt":130}},
    {"Classification":{"$nin":[2,3]}}
]}
```

**Comment by abellgithub** [comment]
Conversation on Slack regarding this proposal:

chambbj [10:17 AM] 
This proposal specifically? Or more generally, filters for Entwined data?


abell [10:18 AM] 
I think we do this already except AND and OR.  The syntax is different, though. (edited)


[10:19] 
Our current syntax comes from PDAL 1.0 or something like that.


chambbj [10:24 AM] 
I’m lazy, and I feel like that, while perhaps more expressive, is not exactly convenient. It’s quite a lot to type. The real addition is the OR. And maybe that’s necessary. I haven’t created a pipeline yet that required it though. Whatever happens, the concept of a DimRange that applies to `filters.range`, `filters.assign`, and filter options like `filters.smrf.ignore` should be consistent.


hobu [10:39 AM] 
my case for the Mongo filters
* reusability of someone else's syntax
* it's all just JSON, not another syntax inside of JSON
* reuse of the same filters in at least two of our softwares


[10:42] 
IIRC, you came up with the `filters.range` syntax Andrew. Did it come from somewhere, or was it something you just kind of came up with?


chambbj [10:49 AM] 
I think I came up with the first elements of it, but @abell improved (adding multiple ranges, negation, etc.). A pro is that if you are trying to reach the scientist/non-coder, they are going to be familiar with Python/R/MATLAB which all specify ranges _similar_ to this, though not standardized.


abell [10:51 AM] 
The syntax was from way back.  Just checked and it’s in like 0.9.8.


chambbj [10:51 AM] 
This may have been the initial discussion. https://github.com/PDAL/PDAL/issues/1001
GitHub
Refactor range filter options · Issue #1001 · PDAL/PDAL
 


hobu [10:53 AM] 
How distasteful to support both? There would be some nice synergy to have the same filtering for both greyhound and PDAL -- especially in PDAL processing scenarios where the filter can just be passed upstream to the server


abell [10:56 AM] 
I just hate to break things that work and people may depend on.  Not sure on supporting both.  Guess I’m wondering about demand.


chambbj [11:00 AM] 
I think I don’t hate the Mongo syntax for use in the JSON pipeline. I’m really thinking it would suck on the CLI. Just too easy to get wrong. And if we were to allow a different syntax on the command line than would be expected in the pipeline, that sets kind of a strange precedent.


hobu [11:02 AM] 
I can definitely see how the current syntax is convenient for command line and scientificos
