### ISSUE TITLE
How to loop in a directory on windows

### ISSUE THREAD

**Issue by Mathvarin** [PDAL/PDAL#1636]
Hello,

We are trying to do a filter (crop) on every .laz located into a folder. We tried https://www.pdal.io/tutorial/reading.html but arguments are not recognized. It is not working even in the simple example in this website.

We are working on Windows with OSGeo. Is there a command line to loop through a directory?

Here is the full json code we want to use :
```
{
  "pipeline":[
   {
      "type":"readers.las",
      "filename":"c:/Users/mvarin/PDAL/{}.laz"
    },
    {
      "type":"filters.crop",
      "bounds":"([157494.020200,233114.494000],[5157891.568000,5256495.001200])"
    },
	{
      "type":"writers.las",
      "filename":"c:/Users/mvarin/PDAL/{}.las"
    }
   
  ]
}
```

Thank you very much

Mathieu Varin

**Comment by abellgithub** [comment]
It's not clear what command you're using, but I'd recommend a loop with whatever scripting language that you like and then using [pdal translate](https://www.pdal.io/apps/translate.html) passing the name of your pipeline file with the `--json` option.

I don't think '{}' is valid syntax for a filename on windows.

**Comment by hobu** [comment]
# To merge them all into a single file

I would use [pdal tindex](https://www.pdal.io/apps/tindex.html) to create a SQLite or Shapefile or some kind of OGR-readable vector file for your files and then use `readers.tindex` https://www.pdal.io/stages/readers.tindex.html to feed your pipeline. This will give you the most flexibility.

## Pipeline

```
{
  "pipeline":[
   {
      "type":"readers.tindex",
      "filename":"c:/Users/mvarin/PDAL/myfiles.sqlite"
    },
    {
      "type":"filters.crop",
      "bounds":"([157494.020200,233114.494000],[5157891.568000,5256495.001200])"
    },
	{
      "type":"writers.las",
      "filename":"c:/Users/mvarin/PDAL/cropped-and-merged.las"
    }
   
  ]
}
```

## Command

```
pdal tindex --tindex myfiles.sqlite --filespec "C:/Users/mvarin/PDAL/*.laz" ^ 
    -f SQLite --fast_boundary
```

# To run one at a time on each file, use a batch file

Batch feebly stolen from [here](https://stackoverflow.com/questions/39615/how-to-loop-through-files-matching-wildcard-in-batch-file). 

## Pipeline

```
{
  "pipeline":[
   {
      "type":"readers.las",
      "filename":"c:/Users/mvarin/PDAL/first-file.laz"
    },
    {
      "type":"filters.crop",
      "bounds":"([157494.020200,233114.494000],[5157891.568000,5256495.001200])"
    },
	{
      "type":"writers.las",
      "filename":"c:/Users/mvarin/PDAL/cropped/output.las"
    }
   
  ]
}
```

## Batch file

```
 for %%f in (*.laz) do (

            echo "Cropping file" %%~nf
            pdal pipeline pipeline.json --readers.las.filename="c:/Users/mvarin/PDAL/%%~nf"  --writers.las.filename="C:/Users/mvarin/PDAL/output/%%~nf"
)    
```

**Comment by Mathvarin** [comment]
Hello Howard,

Thank you very much for this information. The batch worked fine.

Mathieu
