### ISSUE TITLE
Normal flipping

### ISSUE THREAD

**Issue by chambbj** [PDAL/PDAL#1638]
Need to provide a mechanism within the Normal filter to flip normals to a consistent viewpoint.

**Comment by tomvantilburg** [comment]
Makes sense to do it according to a viewpoint, though for my personal use of airborne lidar an 'always up' flag would also do.

**Comment by chambbj** [comment]
Should always up be the default? And users can just override with a
specific viewpoint?

**Comment by tomvantilburg** [comment]
My guess is that airborne lidar will be the main use case for PDAL (I may be wrong) and that 'always up' makes sense as a default.  Would there be a penalty in speed when calculating against the coordinates of a viewpoint? If not, the default might be some miles above the center of the extent I guess. If so, a check for the normalz sign might be faster.

**Comment by chambbj** [comment]
@tomvantilburg See #1639

**Comment by tomvantilburg** [comment]
Did you check for any speed penalty? As far as I can see there are 2 extra calculations involved that can be skipped when you already know that it's only about the normalZ :
- [This block](https://github.com/PDAL/PDAL/pull/1639/files#diff-08cec75aadf8f2e081e144fdac96235cR113) that compares the eigevector and
- view.calculateBounds(bounds); 

I guess the penalty is small with these simple substractions but would be nice to know how small.

**Comment by chambbj** [comment]
@tomvantilburg A quick test on a 38000 point test file, shows the normal flipping method to be about 3-4% slower. On a file that size (which is admittedly small), it's a matter of milliseconds. Only flipping on negative normalZ, obviously falls somewhere in between.

I'd be open to your first proposal, to offer options both for orienting towards the viewpoint and just blindly assuming always up. In the former case, I think there should be no default viewpoint coordinates. The user either provides all three coordinates, or none at all. Viewpoint and always up options will be mutually exclusive.

**Comment by tomvantilburg** [comment]
@chambbj I agree with this, it sounds logical to be mutually exclusive and put the default on always up.

**Comment by chambbj** [comment]
Okay, the PR has been updated. `always_up` is now the default behavior. Users can optionally specify a `viewpoint` as a WKT or GeoJSON point - if they do, `always_up` is ignored. The only way to prevent any flipping is to set `always_up=false` and do not provide a `viewpoint`.

**Comment by chambbj** [comment]
@tomvantilburg Just merged this into master. Closing the issue. Let me know if you have any other issues with the normal filter.
