### ISSUE TITLE
cut LAS file with a shapefile

### ISSUE THREAD

**Issue by blanchotc** [PDAL/PDAL#1640]
Hello,
I would like to cut a LAS file with a shapefile. I tried the filters.crop but the output is empty when i try with a boundary.  When I tried with a polygon, I had this error message : 
PDAL : filters.crop: Invalid polygon specification. Must be valid GeoJson/WKT

This is my pipeline, how could I fix it both issues? Thank you !
Claire

```
{
  "pipeline":[
   {
      "type":"readers.las",
      "filename":"c:/Users/mvarin/PDAL/16_1905197f07_dc.laz"
    },
    {
      "type":"filters.crop",
	  "bounds":"([190340.322581,190592.380423],[5197421.078977 ,5197745.328142])",
      "polygon":"POLYGON ((190340.323 5197724.527, 190592.0380 5197745.328, 190570.356 5197432.091, 190351.335 5197421.079))"
    },
	{
      "type":"writers.las",
      "filename":"c:/Users/mvarin/PDAL/16_1905197f07_dc.las"
    }
   
  ]
}
```

**Comment by hobu** [comment]
1. You can used `bounds` OR `polygon`, not both.
2. Your POLYGON WKT is not valid WKT. It needs the beginning point at the end to close it.

**Comment by blanchotc** [comment]
Thank you verry much, it works !
