### ISSUE TITLE
Support ability to add external sidecar file to supplement/override pdal metadata

### ISSUE THREAD

**Issue by msmitherdc** [PDAL/PDAL#1641]
Similar to gdal's .aux.xml, support a .aux.json (for example) that allows setting/overriding pdal metadata for a file. The metadata would just be treated as existing pdal metadata down the pipeline. 

Key example for overriding would be spatial reference (wkt).

**Comment by abellgithub** [comment]
I don't understand.  What do you expect to be done with the data?  How is this different than passing a filename in the metadata?

**Comment by msmitherdc** [comment]
This has nothing to do with the filename. This is about setting/overriding values in the file with this sidecar file. To allow to set metadata values, including projection, that replace the values (for PDAL) when the file is read. So one could use this to replace or set metadata values that aren't present is the source file or are wrong. 

You can see the concept with PAM in GDAL (http://www.gdal.org/classGDALPamDataset.html)

**Comment by msmitherdc** [comment]
We will also need some environment variable similar to `GDAL_PAM_PROXY_DIR` to support reading metadata from a separate location

**Comment by hobu** [comment]
I propose that we write `.json` files as the sidecars that are full PDAL pipelines. Additionally, we should update PDAL's Pipeline reader to mask any `MetadataNode` items. Then you can override anything you want using the same approach as everything else, and we don't have jabby bits of files all over the place for little chunks.
