### ISSUE TITLE
pg writer not dropping table when same tablename in multiple schemas

### ISSUE THREAD

**Issue by tomvantilburg** [PDAL/PDAL#1642]
According to [this ](https://github.com/PDAL/PDAL/blob/master/plugins/pgpointcloud/io/PgWriter.cpp#L370)piece of code, the 'DROP TABLE' will not happen when there is more than 1 table with the same name in the whole database. I would think this is not the intention since having the same table twice is not uncommon.

Actually, it would make more sense to add the schema name into the CheckTableExists functions or even skip this whole function since it is obsoleted by the use of "DROP TABLE IF EXISTS"

**Comment by hobu** [comment]
That code came before schema support. I think drop table support should be removed entirely. Do it with your `pre_sql` if you want, and not have PDAL take any responsibility for potentially screwing it up...

**Comment by tomvantilburg** [comment]
The nice thing about having it as a single PDAL parameter is that it easy to replace with a variable in my scripting. Ofcourse I can parse a string into the pre_sql parameter but it is less versatile.

I have no objection in PDAL doing part of the SQL work for me, even at the risk of screwing things up. Are there other objections for having the "DROP TABLE IF EXISTS" clause in the pg writer?
