### ISSUE TITLE
docker gdal library url calls throw segfault

### ISSUE THREAD

**Issue by msmitherdc** [PDAL/PDAL#1647]
url calls can't be used in the filters.colorization. 

This works in gdal when compiled with libcurl but segfaults in the pdal dependencies docker image:

```
gdalinfo "https://isse.cr.usgs.gov/arcgis/rest/services/Orthoimagery/USGS_EROS_Ortho_1Foot/ImageServer/exportImage?f=image&bbox=333615,4691634,330227,4689471&imageSR=26919&bboxSR=26919&size=338,216&format=tiff&pixelType=U8"
```
Might require custom building gdal in docker dependencies

**Comment by abellgithub** [comment]
Using version 2 of GDAL fixes this. If we need to address an earlier version, please provide a specific PDAL test case that will reproduce.
