### ISSUE TITLE
PDAL - las to pcd Translate Problems 

### ISSUE THREAD

**Issue by ahmadshabbir2468** [PDAL/PDAL#1650]
Hi, Sir 
I Use this Syntax 
**pdal translate -i test.las -o test_out.pcd** 
And It Continuously  Gives This error ""PDAL: Couldn't create writer stage of type writers.pcd"" ??

And Same Error For The  PCD to las Translate 

**pdal Translate first.pcd -o test.las**

 Gives This error""PDAL: Couldn't create writer stage of type writers.pcd""

Please Guideline 

Thanks in advance

**Comment by abellgithub** [comment]
PDAL can't find the PCD plugin.  Did you build PDAL yourself?  Did you build the PCL plugin during the process?  If so, make sure that you have the file libpdal_plugin_writer_pcd.<shared library extension> where pdal can find it, or set PDAL_DRIVER_PATH to the location where you've placed it.

**Comment by pbach3** [comment]
To add to @abellgithub you also should update the "BUILD_PLUGIN_PCL:BOOL=" line in the CMAKECache.txt located inside your "build" folder to "ON" then rebuild.

**Comment by ahmadshabbir2468** [comment]
Sir I was Working some other major thing Can't See this One ! SIR i Download PDAL From OSGEO and Install PDAL  Sir i can;t find "libpdal_plugin_writer_pcd " Or Can You Explain Location/Directroy Where should i See this File 
This issue is Serious Sir
