### ISSUE TITLE
PDAL Classification ??

### ISSUE THREAD

**Issue by ahmadshabbir2468** [PDAL/PDAL#1652]
Hi, 
Sir there is a  Confusion Related To PDAL Classification ? How PDAL Classification Actually Work ? 
Problem Statement  :- 
I Have an **Unclassified .LAS** File and I want to classify It.I am successfully Classify Las Files as Ground Vs Non Ground But i want classification with further classes like **buildings,Power Lines, vegetation, vehicles, and water.**

For  Classifications The Number 
1. Step    is  Ground Vs Non Ground Classifications  
2 . Step   is filters.assign 

But as i have UnClassified FIles How Can I usE  Filter Assign ? 

**Question**:-
Can We Do This Kind of Classification **(Extract buildings,Power Lines, vegetation, vehicles, and water)** With PDAL Or We Can Do ONLY Ground Vs Non Ground Classification ! 

Kind Regards
Mr.Ahmad

**Comment by chambbj** [comment]
@ahmadshabbir2468 You have posed many questions here ("Can I...?, How do I...?"), which I believe are best suited for the [mailing list](https://lists.osgeo.org/mailman/listinfo/pdal). As such, I'm closing this as a non-issue.

In short though, PDAL currently has filters to identify ground, non-ground, and noise. Nothing else at the moment.

If you find that the documentation is not explaining this well, we are happy to accept pull requests with suggested edits. Or you could at least point us directly to the confusing bits, and we will try to clean them up.

**Comment by ahmadshabbir2468** [comment]
OK Sir 👍  Thanks Highly Appreciated And I Am Working on That IF i Find Any thing i will Share It With to you ..
