### ISSUE TITLE
PDAL Calculating Heights: Couldn't create filter stage of type 'filters.height'

### ISSUE THREAD

**Issue by ahmadshabbir2468** [PDAL/PDAL#1660]
I Use PDAL to find the height of points cloud data. But When I Run The Command 

**pdal translate myfile.las height.bpf height --writers.bpf.output_dims="X,Y,Z,Height;"**

Its throws this ErrorPDAL: Couldn't create filter stage of type 'filters.height'

I follow This Document  Please have a look 
https://www.pdal.io/tutorial/calculating-normalized-heights.html?highlight=height

**Comment by chambbj** [comment]
The document needs to be updated. Try "hag" instead of "height" for the
filter name. Also, your output dimension name will now be
"HeightAboveGround".

**Comment by chambbj** [comment]
Closing with no documentation updates needed. The [tutorial](https://www.pdal.io/tutorial/calculating-normalized-heights.html) in question clearly states that `filters.height` has been replaced by `filters.hag` and provides a [link](https://www.pdal.io/stages/filters.hag.html) to the documentation that describes proper usage and the expected dimension name.
