### ISSUE TITLE
PDAL Metadata support for Matlab family

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#1661]
For sure we need SRS info on the array struct. 

Users want the other metadata information too, but either as JSON string or real Matlab objects. The former is challenging because what might happen to push that back into pipeline operations.

**Comment by huntm** [comment]
One concern for JSON in MATLAB is that built-in support for JSON decoding/encoding is fairly recent. In our code base, we've targeted R2015b, but built-in JSON decoders/encoders (`jsondecode`/`jsonencode`) were first introduced in R2016b. So requiring functions to decode their own JSON will force a move to R2016b or later, or require an unofficial MATLAB JSON parser (my experience with them hasn't been great so far--the one I tried didn't handle backslash-escaped quotes in strings, for example).

**Comment by huntm** [comment]
(Of course, if PDAL implements native MATLAB representations by calling MATLAB's `jsondecode` function, that *also* forces a move to R2016b or later. So... maybe it's time for us to move to 2016b or later. :-))

**Comment by hobu** [comment]
Available in https://github.com/PDAL/PDAL/tree/matlab-metadata

For now I have pushed a ``metadata`` struct that has a ``json``, ``wkt``, ``horizontal``, and ``vertical`` string entries. The ``wkt`` one is used to set the coordinate system for anything coming from ``readers.matlab``. Nothing is done to the JSON other than it's placed into Matlab.

**Comment by hobu** [comment]
Merged to master @b67103c2d9ba31b28480315ac131f100ab5dee36

**Comment by huntm** [comment]
Using the MATLAB metadata functionality now with no problems. Thanks!
