### ISSUE TITLE
cpd plugin and filter names are mismatched

### ISSUE THREAD

**Issue by kbevers** [PDAL/PDAL#1670]
The CPD plugin creates the ```filters.change``` filter, but the shared library of the plugin is called ```libpdal_plugin_filter_cpd.so```, this results in PDAL not being able to load ```filters.change``` since it is looking for a ```libpdal_plugin_filter_change.so```. At least that is what the below debug output suggests:

```
$cat cpd.json
{
    "pipeline": [
        "PUNKTSKY_00003_1km_6231_501.laz",
        "PUNKTSKY_00003_1km_6231_502.laz",
        {
            "type": "filters.change",
            "method": "rigid"
        },
        "output.las"
    ]
}

$ pdal pipeline cpd.json --verbose=8
(pdal pipeline Debug) Plugin search path: '.'
(pdal pipeline Debug) Plugin search path: './lib'
(pdal pipeline Debug) Plugin search path: '../lib'
(pdal pipeline Debug) Plugin search path: './bin'
(pdal pipeline Debug) Plugin search path: '../bin'
(pdal pipeline Debug) Plugin search path: '/usr/local/lib'
PDAL: Couldn't create filter stage of type 'filters.change'.
```
If I change the filter name to cpd, the shared library is loaded but the filter is not found:

```
$ cat cpd.json
{
    "pipeline": [
        "PUNKTSKY_00003_1km_6231_501.laz",
        "PUNKTSKY_00003_1km_6231_502.laz",
        {
            "type": "filters.cpd",
            "method": "rigid"
        },
        "output.las"
    ]
}

$ pdal pipeline cpd.json --verbose=8
(pdal pipeline Debug) Plugin search path: '.'
(pdal pipeline Debug) Plugin search path: './lib'
(pdal pipeline Debug) Plugin search path: '../lib'
(pdal pipeline Debug) Plugin search path: './bin'
(pdal pipeline Debug) Plugin search path: '../bin'
(pdal pipeline Debug) Plugin search path: '/usr/local/lib'
(pdal pipeline Debug) Attempting to load plugin '/usr/local/lib/libpdal_plugin_filter_cpd.so'.
(pdal pipeline Debug) Loaded plugin '/usr/local/lib/libpdal_plugin_filter_cpd.so'.
(pdal pipeline Debug) Initialized plugin '/usr/local/lib/libpdal_plugin_filter_cpd.so'.
PDAL: Couldn't create filter stage of type 'filters.cpd'.
``` 

The problem can be fixed by substituting "change" with "cpd" in ```plugins/cpd/filters/CpdFilter.cpp``` and ```plugins/cpd/filters/CpdFilter.hpp``` the plugin is loaded and the filter is found by pdal. Obviously other solutions exists as well, depending on the desired name of the filter.

**Comment by chambbj** [comment]
@gadomski should weigh in on this. We discussed naming a bit back in #1577. My vote is to revert this from `filters.change` back to `filters.cpd`.

**Comment by kbevers** [comment]
I yes, I remember reading that. My vote is on ``filters.cpd`` too.

**Comment by gadomski** [comment]
Yup "filters.cpd" is what it should be. @kbevers should be fixed in 9fbcc785b9c81a3d56779fe933ac783c3f3bf801 if you want to pull that and confirm?

**Comment by kbevers** [comment]
@gadomski You probably also want to update the .hpp files, yes? I will give it a test run when I get to the office tomorrow morning.

**Comment by gadomski** [comment]
Sorry, what needs to change in the hpp files? NP on timing.

**Comment by kbevers** [comment]
Perhaps it's not necessary (haven't really looked at the code, other than a quick search and replace for change -> cpd), but at least there's this in ```CpdFilter.hpp```:

```
PointViewPtr change(PointViewPtr fixed, PointViewPtr moving);
```

**Comment by gadomski** [comment]
The change method is a method on the cpd filter and shouldn't need to be changed.
