### ISSUE TITLE
CI issues caused by pdal-scala project

### ISSUE THREAD

**Issue by pomadchin** [PDAL/PDAL#1671]
### The problem

Sometimes CI fails with the compilation error: https://travis-ci.org/PDAL/PDAL/jobs/273302835#L4726 

### Description

In the code we use circe [AutoDerivation](https://github.com/PDAL/PDAL/blob/master/java/core-scala/src/main/scala/io/pdal/pipeline/json/Implicits.scala#L28). _(note: it's taken from the [circe-extras](https://github.com/PDAL/PDAL/blob/master/java/core-scala/src/main/scala/io/pdal/pipeline/json/Implicits.scala#L22) package, as it allows to make codecs [configurable](https://github.com/PDAL/PDAL/blob/master/java/core-scala/src/main/scala/io/pdal/pipeline/json/Implicits.scala#L29-L30))_.

The idea is that probably circe generates too complex instructions for the compiler and it creates problems randomly.

### Solution

As a workaround, and as a thing which can make the code cleaner and more friendly for compiler, we can use `@ConfiguredJsonCodec` which behaves as `@JsonCodec` but can be configured using custom configuration object `(note: is is located in the circe-extras package)`. We need to remove circe `auto` from everywhere and to use `semi-auto` derivation for all case classes. 

It can be tricky, as smth can potentially go a bit not as expected, and should be done carefully.

### P.S.

[Here](https://github.com/PDAL/PDAL/blob/master/scripts/ci/script.sh#L71-L75) we call sbt two times, and in this project we use sbt 1.0.1 with a new zinc compiler. Probably there can be an issue, that sometimes it spoils `target` folders, so we can try to add a targets cleanup command: 

```
# JNI tests
cd /pdal/java; PDAL_DEPEND_ON_NATIVE=false ./sbt -Djava.library.path=/pdal/_build/lib core/test
# Cleanup project
cd /pdal/java; rm -rf target */target
# Scala tests
cd /pdal/java; PDAL_DEPEND_ON_NATIVE=false ./sbt -Djava.library.path=/pdal/_build/lib core-scala/test
```

Though it's just a thought, and there are no proofs that it's true, and I feel more that the problem is in the circe auto derivation functionality.

**Comment by lossyrob** [comment]
@pomadchin I know we've done similar work in Raster Foundry, can you point to any commits or PRs that would give a hint on how to do this refactor?

**Comment by pomadchin** [comment]
@lossyrob here it is: https://github.com/raster-foundry/raster-foundry/pull/1485/files

**Comment by abellgithub** [comment]
Can this be closed?

**Comment by pomadchin** [comment]
I'm on vacation, will be back this Monday, and this issue would be the first task for to do.
