### ISSUE TITLE
Apache Arrow support

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#1687]
Apache Arrow is a columnar datastore that big data ecosystem players such as Spark are now starting to use for data interchange. It would be very useful if PDAL had Arrow support because people could use PDAL for picking up and processing chunks of data before handing it off to something that is BigData™️ capable.

https://github.com/apache/arrow

1. Provide an `ArrowPointTable` implementation
2. Provide a static method to take `pdal::PointLayout`->`arrow::Schema`
3. Add option to Python extension that enables use of `ArrowPointTable`
4. Provide a kernel or writer that provides serialized or memory-accessible Arrow access.

**Comment by abellgithub** [comment]
Can we get a use case?
