### ISSUE TITLE
pdalargs not functional in filters.matlab

### ISSUE THREAD

**Issue by huntm** [PDAL/PDAL#1689]
When defining a pipeline, `filters.python` and `filters.matlab` accept a `pdalargs` dictionary of extra metadata values, but this functionality doesn't seem to be "wired up" for `filters.matlab`. The values do not appear in the PDAL structure in the MATLAB interpreter.

**Comment by hobu** [comment]
What would be the most reasonable way to push these into Matlab? I'm thinking just sticking a `pdalargs` member on the named array struct, since there is no function call like there is with `filters.python`. 

Ideas?

**Comment by huntm** [comment]
I'm totally happy with a `pdalargs` member on the struct.

**Comment by hobu** [comment]
ok, it will be whatever string you passed in via the option.
