### ISSUE TITLE
Automatically set UTM zone when writing BPF data for UTM coordinate systems

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#1716]
# Problem

GDAL has the `OSRGetUTMZone` method ([link](http://www.gdal.org/classOGRSpatialReference.html#a4b17d85f5db53978c749780b214c4237)) that will return a single number that is sufficient for the current `writers.bpf` `coord_id` value. We can automatically set the `coord_id` with that value if the specified coordinate system is actually UTM.

# Proposal

* If the user sets the `autoutm` option, the `writers.bpf` will attempt to compute one if the active coordinate system is UTM. If the coordinate system is not UTM, no zone value will be computed.
* If OSR does not determine a UTM zone ID, the default `coord_id` user is used (current behavior).

**Comment by abellgithub** [comment]
-1 is a valid UTM zone.  Also, there is no default `coord_id`.  The default is to specify that the SRS type is cartesian.

**Comment by abellgithub** [comment]
Done in https://github.com/PDAL/PDAL/pull/1723
