### ISSUE TITLE
Set LAS dataformat_id based on dimensions in PointTable

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#1719]
Currently, the user must explicitly set the `dataformat_id` option for `writers.las`.  This could be complicated in messy merge scenarios, and `writers.las` already has the PointLayout information available to it to set it.

**Comment by abellgithub** [comment]
We forward dataformat_id if requested.  You want to infer dataformat_id from the layout?  Seems...risky.

**Comment by hobu** [comment]
> You want to infer dataformat_id from the layout? Seems...risky.

In what way is it risky? If you have `Red`, `Green`, `Blue`, or `GPSTime` on the layout and you never explicitly set the `dataformat_id` option on the `writers.las`, it would make sense to default to doing the right thing.

**Comment by abellgithub** [comment]
I like the idea of fowarding by default better than guessing what someone wants, though I think it's easy to forward if that's what you want and it's well documented.

Merging is a good example of when you might NOT want to infer `dataformat_id`.

Either is a change in behavior that might mess some people up.

**Comment by hobu** [comment]
> I like the idea of fowarding by default better than guessing what someone wants, though I think it's easy to forward if that's what you want and it's well documented.

`filters.colorization` could have added `Red`, `Green`, and `Blue` dimensions, and in that case if you're writing LAS, the `dataformat_id` needs to be `2` or `3`, and the forwarding option isn't going to help you.

> Merging is a good example of when you might NOT want to infer `dataformat_id`.

Why? If the user merges a `dataformat_id==2` and `dataformat==0` files together, we almost always want the output to have `dataformat_id==2`, which is what would get set based on the PointLayout. What's the counter-example here?

**Comment by hobu** [comment]
Users need to know the details of their formats rather than PDAL trying to be smart. We will just end up failing.
