### ISSUE TITLE
Conda Install Option

### ISSUE THREAD

**Issue by mccarthyryanc** [PDAL/PDAL#1724]
Installing via conda would be a nice option for me. I see that someone has already setup a [conda recipe](https://anaconda.org/mathieu/pdal) for pdal but it is only for PDAL=1.5, python=3.5, and numpy=1.12

**Comment by chambbj** [comment]
The same author appears to have an OSX recipe for PDAL=1.6, python=3.5, and numpy=1.12. What combo would you like to see supported?

Conda is on the fringes for us at this point.  IMO, the ideal route would be for someone to [submit a recipe](https://conda-forge.org/#add_recipe) to conda-forge, similar to what is done for [Homebrew](https://github.com/Homebrew/homebrew-core/blob/master/Formula/pdal.rb). I'm not sure we have the necessary Conda expertise (or motivation) at the moment to get this up and running and to keep it healthy moving forward. Contributions welcome though!

**Comment by mathieu1** [comment]
Hello, I'm responsible for those ad-hoc builds you've found. The plan is indeed to get pdal on conda-forge, but the recipes need a bit more work before being submitted (I would like at least that both laszip and python plugins all work, and preferably PGPointcloud and spatialite as well). The work in progress on the conda recipes for pdal and related dependencies can be found in [this repo](https://github.com/mathieu1/pcl-stack), feel free to open issues, PRs or comment here.

**Comment by mccarthyryanc** [comment]
@mathieu1 thanks for the links and the work on these recipes! I'll keep any issues/discussion over there until they get added to conda-feedstock.

**Comment by chambbj** [comment]
As a follow-up on this, we've just stepped into the Conda arena. Linux and macOS packages have been released in the [conda-forge channel](https://anaconda.org/conda-forge/pdal). Issues should be reported in the [pdal-feedstock](https://github.com/conda-forge/pdal-feedstock/issues/new). This initial release supports LAZ, NITF, and hexbin, but additional plugins and Windows support should be coming along in the near future. The [now separate](https://github.com/PDAL/python) PDAL python package will be submitted as a separate package.

**Comment by chambbj** [comment]
For anybody following this thread, the PDAL Python extension was [just added](https://anaconda.org/conda-forge/python-pdal) to conda-forge this evening as `python-pdal`. Please report issues in the [python-pdal-feedstock](https://github.com/conda-forge/python-pdal-feedstock/issues/new).
