### ISSUE TITLE
Translating a binary PCD file to an ascii PCD file

### ISSUE THREAD

**Issue by kanzah** [PDAL/PDAL#1730]
Hello. I have a question regarding the `translate` command for converting a binary PCD file. I can generate a PCD file with ascii data using the command `$ pdal translate -i bin_input.pcd -o pcd_output.pcd`. However running the `info` command on the output PCD file and the input PCD file reveals some discrepancies in the stats e.g. maxx, maxy, maxz and the boundary coordinates. The image height and width also appear to have altered in the output file's PCD header (although the total number of points are the same). I couldn't find anything related to this in the documentation for writers.pcd. It would be great if someone can help me understand this issue better.

Thank you.

**Comment by chambbj** [comment]
Could you expand on your issue? What were the expected and actual outputs of the boundary coordinates?

For the height/width, I'm guessing the problem is that you have some "organized" point cloud as your input (using PCL's terminology), where both height and width are greater than 1. PDAL doesn't support organized point clouds at the moment, so your organized point cloud is likely being converted to an unorganized one where width now equals the total number of points and height equals one.

**Comment by kanzah** [comment]
It appears that there is an offset in the coordinates for the output PCD file. Below are the boundary coordinates for the original PCD:

[ -759.12200928000004, -743.37963866999996 ],
[ -759.12200928000004, 833.68371581999997 ],
[ 926.17645263999998, 833.68371581999997 ],
[ 926.17645263999998, -743.37963866999996 ],
[ -759.12200928000004, -743.37963866999996 ]

And these are the boundary coordinates for the output PCD:

[ 0, 0 ],
[ 0, 1577.0633544899999 ],
[ 1685.29846191, 1577.0633544899999 ],
[ 1685.29846191, 0 ],
[ 0, 0 ]

Just as you mentioned, the height becomes 1 in the output PCD and your comment explains why so.

Thank you.

**Comment by chambbj** [comment]
We need to update the documentation for the writer, as this is currently
missing. Can you try setting the following PCD writer option?
subtract_minimum=false

**Comment by chambbj** [comment]
Docs updated in a3ece8ee7a1f1c43715eea4d0f9e707b88891c42. @kanzah Please let us know if still believe there to be an issue.

**Comment by kanzah** [comment]
Setting the driver option `--writers.pcd.subtract_minimum=false`, resolved the offset issue. Thank you for updating the documentation.
