### ISSUE TITLE
We need to adopt/create a grammar for Dimension math

### ISSUE THREAD

**Issue by chambbj** [PDAL/PDAL#1732]
PDAL already has the ability to filter by DimRange (`filters.range`) and to segment PointViews by DimRange (`filters.groupby`). We've discussed the possibility of splitting by multiple, possibly overlapping DimRanges too (`filters.slice` #1693).

I recently came across a [notebook](https://github.com/rockestate/point-cloud-processing/blob/master/notebooks/point-cloud-processing.ipynb) where the author was computing a new boolean dimension indicating that a point was likely a tree. This dimension was formed (in Python) simply by performing a logical AND of Classification not equal to ground, HeightAboveGround greater than or equal to three, and first eigenvalue greater than 0.1.

It also occurred to me that we do something very similar in `filters.approximatecoplanar`, where we are really just comparing the first, second, and third eigenvalues to look for areas that are approximately coplanar. This use case is a little more complicated as the method is comparing Dimensions element-wise rather than against a fixed threshold.

This all leads me to believe that we could certainly benefit from a more sophisticated grammar for doing such things. This has already been discussed briefly in #1635 and #1001. The purpose of this issue is to document some use cases. If we go the Greyhound route (which borrows from MongoDB), then this ticket can be closed as  duplicate.

So, in the case of `TreePotential`, I see at least three possible ways of defining the boolean operations that get to the new dimension.

1. Stick with the current DimRange approach

We can debate which existing (or new) filter would be the right tool for the job. Putting that aside for now, let's focus on the symantics.

```
TreePotential = Classification![2:2] & HeightAboveGround[3.0:) & Eigenvalue0(0.1:)
```

We reference three existing dimensions which had better exist, else we will fail. All ranges are specified using the existing grammar and fixed bounds. We indicate that the result will be recorded in the new dimension `TreePotential` (though `filters.assign` would reverse this and expect the new dimension explicitly on the right hand side of the equation.

2. Allow users to specify the equation in a more human readable form.

```
TreePotential = (Classification != 2) & (HeightAboveGround >= 3.0) & (Eigenvalue0 > 0.1)
```

There is very little different here, just perhaps a slightly lower bar to adoption because of the straightforward syntax.

3. Borrow from MongoDB and Greyhound and adopt a more JSON-based syntax

```
"TreePotential":{
    $and:[
        { $ne: [ "Classification": 2 ] },
        { $gte: [ "HeightAboveGround", 3.0 ] },
        { $gt: [ "Eigenvalue0": 0.1 ] }
    ]
}
```

There will be a certain class of users who are very comfortable with this, and it gets the point across, but I still worry about readability, and getting this right the first time, especially if trying to enter at the command-line.

Now, let's look at the three approaches in the context of `filters.approximatecoplanar`.

1. Current approach (adapted to compare element-wise across dimensions)

```
Coplanar = Eigenvalue1(25.0 * Eigenvalue0:) & Eigenvalue2(:6.0 * Eigenvalue1)
```

It is easy to overlook that the final argument is actually a less than in this case.

2. Human-readable form

```
Coplanar = (Eigenvalue1 > (25.0 * Eigenvalue0)) & (Eigenvalue2 < (6.0 * Eigenvalue1))
```

This is quite easy to enter and read.

3. MongoDB-style

```
"Coplanar":{
    $and: [
        { $gt: [ "$Eigenvalue1", { $multiply: [ "$Eigenvalue0", 25.0 ] } ] },
        { $lt: [ "$Eigenvalue2", { $multiply: [ "$Eigenvalue1", 6.0 ] } ] }
    ]
}
```

Again, it works, just is quite verbose IMO.

What other use cases/possible solutions can others come up with? I think this would be a very useful evolution of PDAL that would prevent us from creating new filter stages for this type of evaluation and from needing to dive into Matlab or Python every time we need to do it.

**Comment by abellgithub** [comment]
1) @hobu has argued against creating "yet another" language to do this kind of thing for a long time. I believe that the thinking was that people could use python (or Matlab, now) for these tasks, which is essentially what you're arguing against. Perhaps he feels differently now. I'm not sure how I feel, but I'm not really a user.  I just write the code. To me, writing a simple filter is...simple.
2) We don't do boolean dimensions. All dimensions take on numeric values. We typically create dimensions of unspecified type as doubles. If we go this route, do we want to do numeric processing as well as boolean?  You could essentially do `filters.transform` with such a language.  The proposed scale filter as well. At some point you're just creating your own interpreter.  Is that what we want?
3) I **hate** the MongoDB syntax and I think the people who created it should apologize.
4) The range syntax [low,high] has essentially been there from day one (it's in version 0.4).  I enhanced/modified it. In retrospect this may have been a bad call, but the intent was, to my way of thinking, noble -- I don't like breaking people's existing operations if avoidable.

**Comment by chambbj** [comment]
Closing the ticket and showing how the cited example (with minor updates from the original author) can be implemented as a Python filter.

```json
{
    "type":"filters.python",
    "function":"filter",
    "add_dimension":"TreePotential",
    "source":"import numpy as np

def filter(ins, outs):
    tree_potential = (
        (ins['Classification'] == 1) &
        (ins['HeightAboveGround'] > 2.0) &
        (ins['Eigenvalue0'] > 0.05) &
        ((ins['NumberOfReturns'] - ins['ReturnNumber'] >= 1)
    )
    outs['TreePotential'] = tree_potential.astype('float64')
    return True"
}
```

As with #1956, while there may a small performance penalty for doing this and similar dimension math type operations in Python, it is 100% possible and frees us from having to worry about coming up with and owning a custom solution.
