### ISSUE TITLE
Pipeline serialization does not produce `execution_metadata`

### ISSUE THREAD

**Issue by gadomski** [PDAL/PDAL#1741]
One-liner (from the root of the PDAL repository):

```
echo '{"pipeline":["test/data/las/autzen_trim.las",{"type":"filters.hexbin"}]}' | \
    pdal pipeline -s --pipeline-serialization output.json && \
    grep execution_metadata output.json
```

This makes `filters.hexbin` unusable AFAICT.

**Comment by abellgithub** [comment]
I don't understand this. I don't know what "execution_metadata" is, though I see it in `filters.hexbin` documentation.  There is no reference to "execution_metadata" in the code.

**Comment by gadomski** [comment]
Looks like it was removed in c29f692827ba192ffe398524b610eea9e3d90750. I don't need `execution_metadata` per se, but I (read: others) do need `filters.hexbin` in some form. If there's a better way to do it, and the docs just need to be updated, that's fine too.

**Comment by abellgithub** [comment]
I don't understand what you're saying isn't working.

**Comment by gadomski** [comment]
Following the instructions [here](https://www.pdal.io/stages/filters.hexbin.html), I am unable to retrieve a boundary multi-polygon via `pdal pipeline`. As far as someone from "the outside" (not me) is concerned, the hexbin filter doesn't work.

**Comment by abellgithub** [comment]
So you're saying the DOCUMENTATION is incorrect? I'm not having any trouble with the filter itself.

**Comment by gadomski** [comment]
How do you use it to get the boundary?

**Comment by abellgithub** [comment]
Sorry.  I'm not trying to be difficult.  I'm just trying to understand the issue, which I *think* is documentation.  This works for me:

foo.json:
```
{
    "pipeline": [
        "/Users/acbell/pdal/test/data/las/autzen_trim.las",
        {
            "type" : "filters.hexbin"
        }
    ]
}
```
`pdal pipeline foo.json --metadata=outputFile`

There's a boundary in outputFile.

**Comment by gadomski** [comment]
No worries! Thanks, that's what I needed. Yes, then in that case this issue could be retitled "hexbin documentation is incorrect", `s/execution_metadata/metadata/`.

**Comment by msmitherdc** [comment]
@gadomski you can also do this with `pdal info --boundary /Users/acbell/pdal/test/data/las/autzen_trim.las`

**Comment by gadomski** [comment]
@msmitherdc that should probably go into the hexbin filter docs as well? No idea that was an option. I had this monstrosity: https://twitter.com/petegadomski/status/941068191194845184
