### ISSUE TITLE
PDAL cannot translate from Lambert Conformal Conic to Proj4

### ISSUE THREAD

**Issue by squeakus** [PDAL/PDAL#1744]
I am trying to convert a 1.4 version las file to an earlier revision but get the following error:
(pdal info readers.las Error) GDAL failure (6) No translation for Lambert_Conformal_Conic to PROJ.4 format is known.

this seems to be a known bug with GDAL but I don't know how I would change it in PDAL to understand the file as described in the solution below:
https://gis.stackexchange.com/questions/128266/qgis-error-6-no-translation-for-lambert-conformal-conic-to-proj-4-format-is-kn

**Comment by hobu** [comment]
You can override the `spatialreference` of a file with an explicit GDAL-readable SRS definition. You can use proj.4 definitions, or point to a WKT file to provide the override to follow the StackOverflow post.

```
pdal translate myfile.las output.las \
    --readers.las.spatialreference="+proj=lcc \
                                    +lat_1=43.57503293972223 \
                                    +lat_0=43.57503293972223 \
                                    +lon_0=-90.78333333333333 \
                                    +k_0=1.0000408158 \
                                    +x_0=222504.44500889 \
                                    +y_0=47532.0603505207 \
                                    +ellps=GRS80 \
                                    +towgs84=0,0,0,0,0,0,0 \
                                    +units=us-ft +no_defs"
```

**Comment by squeakus** [comment]
That is exactly what I was looking for, thanks!
