### ISSUE TITLE
Accessor for Stages in PipelineManager

### ISSUE THREAD

**Issue by jw3** [PDAL/PDAL#1747]
While writing a Kernel I have the need to access to each stage in the PipelineManager prior to execution.  In this case it is to perform Stage dependency injection prior to execution starting.

Of the current accessors for `Stage*` in the PipelineManager interface, I dont see any that provide access to the full chain.  The root and leaf methods are a subset and the getStage is just the back?

What am I missing?  Or how about a [PR to add an accessor](https://github.com/jw3/PDAL/blob/pipeline_stage_access/pdal/PipelineManager.hpp#L136-L137)?

**Comment by abellgithub** [comment]
If you want to submit the PR as you've proposed, that seems fine.

**Comment by jw3** [comment]
Was there an issue with the PR?

**Comment by abellgithub** [comment]
Nope. Hit the wrong button. Thanks for noticing.
