### ISSUE TITLE
Have cmake not execute on source directory

### ISSUE THREAD

**Issue by cvvergara** [PDAL/PDAL#1749]
Currently it allows to use cmake on the source directory
This snippet I use in pgRouting
```
if ( ${CMAKE_SOURCE_DIR} STREQUAL ${CMAKE_BINARY_DIR} )
        message(FATAL_ERROR "In-source builds not allowed.
        Please make a new directory (called a build directory) and run CMake from there.
        You may need to remove CMakeCache.txt." )
endif()
```
## tasks

- add the snipet
- make sure travis & appveyor tests pass
  - make changes if needed
- modify .gitignore to ignore `build` directory instead of all the "in source" stuff

## references

https://cmake.org/Wiki/CMake_FAQ#Out-of-source_build_trees

**Comment by abellgithub** [comment]
I don't see any good reason to impose this requirement.  I get that people are probably better served by having an out-of-source build, but unless the build doesn't work with an in-source build, I see no reason to impose a restriction.

Most of the of the files in .gitignore aren't releated to the location of the build tree.

**Comment by cvvergara** [comment]
The PDAL manual sugests to do an "out of source" compilation and building:
https://www.pdal.io/development/cmake.html#compiling-the-project
