### ISSUE TITLE
Doxygen documentation

### ISSUE THREAD

**Issue by cvvergara** [PDAL/PDAL#1760]
For developers it would be nice to have.
I made this temporarly:
https://cvvergara.github.io/pdal/

**Comment by abellgithub** [comment]
My personal opinion on this is that it doesn't provide much value if it isn't done carefully.  Generating text for random classes seems more confusing than clarifying.  What advantage do you think this provides over header files?

**Comment by cvvergara** [comment]
I just made the PR that @hobu asked me to do
