### ISSUE TITLE
PDAL 1.6 Docker image does not contain SQLite support

### ISSUE THREAD

**Issue by bella-larsoni** [PDAL/PDAL#1771]
In the workshop, https://www.pdal.io/workshop/exercises/analysis/boundary/boundary.html#finding-the-boundary , the second example gave the error 

```
"PDAL: Can't create dataset using driver 'SQLite'. Driver is not available."
```

**Comment by chambbj** [comment]
PR submitted to GDAL Alpine package. See https://github.com/alpinelinux/aports/pull/3010 for more.
