### ISSUE TITLE
Issue configuring PDAL 1.6 with LASzip 3.1.1

### ISSUE THREAD

**Issue by jfbourgon** [PDAL/PDAL#1774]
I'm facing issue configuring latest PDAL release with recommended LASzip support.

Even if I set `LASZIP_LIBRARY` and `LASZIP_INCLUDE_DIR` flags to location where LASzip library is installed. The cmake script complains that recommended library cannont be found.

Looking inside [FindLASzip.cmake](https://github.com/PDAL/PDAL/blob/master/cmake/modules/FindLASzip.cmake), it appears that the script is not looking for header files according to the structure of my installation which corresponds the following:
```
include/laszip_api_version.h
include/laszip/laszip_api.h
```
while the script seems instead to expect something like:
```
include/laszip/laszip_api_version.h
include/laszip_api.h
```

Putting a copy of each header files in each location solved the issue I had while invoking cmake but I was willing to let you know.

**Comment by abellgithub** [comment]
How did you install laszip on your system?  What is your OS/version?

**Comment by hobu** [comment]
This is a LASzip bug.  I made a patch that fixes it in a branch but it is not merged to master.

**Comment by jfbourgon** [comment]
So the file structure expected by the FindLASzip.cmake is the right one and further release of LASzip will solved the issue. Thanks.
