### ISSUE TITLE
Clipping with Geometries

### ISSUE THREAD

**Issue by rolanddu** [PDAL/PDAL#1777]
I am following the tutorial here:

[https://www.pdal.io/tutorial/clipping-with-shapefile.html](https://www.pdal.io/tutorial/clipping-with-shapefile.html)

...using this tutorial and data, I am receiving errors on PDAL 1.6.0 (Fresh OSGeo4w install):

Example:
pdal pipeline shape-clip.json
(pdal pipeline filters.overlay Error) GDAL failure (1) Failed to find layer 'OGRGeoJSON' on datasource 'attributes.json'.
(pdal pipeline filters.overlay Error) GDAL failure (1) Failed to import source SRS
PDAL: filters.overlay: Unable to select layer 'OGRGeoJSON'

I have tested this on two machines and with different data but get the same error.  GDAL is version 2.2.3.

I ended up using the crop filter with WKT_Polygon to clip the LiDAR data.

Thanks,
Roland

**Comment by hobu** [comment]
Can you post your `attributes.vrt` file?

**Comment by rolanddu** [comment]
Please see the posted file.  I renamed to .txt in order to post it here:

[attributes.vrt.txt](https://github.com/PDAL/PDAL/files/1609733/attributes.vrt.txt)

Thanks,
Roland

**Comment by hobu** [comment]
It might be that this particular tutorial is out of data. It looks like https://www.pdal.io/workshop/exercises/analysis/clipping/clipping.html is an updated version of the exercise. Can you dig into it and see if the approach it defines can work?

**Comment by rolanddu** [comment]
I am still getting the same result.  I speculate that this could be tied to a change in GDAL:

E:\PDAL_test>pdal pipeline clipping.json
(pdal pipeline filters.overlay Error) GDAL failure (1) Failed to find layer 'OGRGeoJSON' on datasource 'E:/PDAL_test/attributes.json'.
(pdal pipeline filters.overlay Error) GDAL failure (1) Failed to import source SRS
PDAL: filters.overlay: Unable to select layer 'OGRGeoJSON'

I have attached the files I used here (without the large autzen.laz file):

[PDAL_test.zip](https://github.com/PDAL/PDAL/files/1612763/PDAL_test.zip)

Thanks again.

**Comment by abellgithub** [comment]
@hobu: Has this been resolved? Does it still need investigation?

**Comment by hobu** [comment]
I think the tutorial still needs some work, so this needs to stay open.

**Comment by hobu** [comment]
GDAL tightened up its layer naming for VRTs. If you modify the VRT to 

```
<OGRVRTDataSource>
    <OGRVRTWarpedLayer>
        <OGRVRTLayer name="OGRGeoJSON">
            <SrcDataSource>./attributes.json</SrcDataSource>
            <SrcLayer>attributes</SrcLayer>
            <LayerSRS>EPSG:4326</LayerSRS>
        </OGRVRTLayer>
        <TargetSRS>+proj=lcc +lat_1=43 +lat_2=45.5 +lat_0=41.75 +lon_0=-120.5 +x_0=399999.9999999999 +y_0=0 +ellps=GRS80 +units=ft +no_defs</TargetSRS>
    </OGRVRTWarpedLayer>
</OGRVRTDataSource>
```

The example should work. I will update the source materials with this change.
