### ISSUE TITLE
Passing artifacts between stages

### ISSUE THREAD

**Issue by jw3** [PDAL/PDAL#1785]
### description
Sometimes a stage produces non point cloud artifacts (vectors, rasters, etc..) that need to be passed along to future stages.  It is desirable to keep these artifacts in memory to avoid file IO.

My group has implemented a kernel based approach that allows injection of a shared container object into each Stage of a pipeline prior to its execution.  This works very well for our current usage, however it limits interoperability outside of this custom kernel.

If PDAL had a standard mechanism for sharing artifacts between stages we would use it.

### our solution
In our case we wrap an `unordered_map<string, shared_ptr<I>>` as a simple KV store which is instantiated in the kernel and injected into each stage.  Within a stage this shared storage provides `put` and `get` by key-name operations. 

The key names for the map can be externalized in the PDAL config, allowing non-related stages to sync up and use each others artifacts.  Eviction of artifacts occurs on demand, also externalized by the PDAL config.

Our `shared_ptr` in the map is typed to a tagging interface to allow extensibility in what can be passed around.  The map wrapping object attempts pointer cast when fetching things to ensure they fit into the requested type.

**Comment by abellgithub** [comment]
Some code showing use of your key-value store would be helpful.

If a downstream stage is receiving information from another stage, it has to know what this data is and how to deal with it.  I'm not sure is any advantage in trying to make something generic that isn't generic.  Perhaps I misunderstand. Knowing your specific needs would be helpful to evaluate the proposal.

Any set of stages that needs special handling of created data can either use the existing metadata infrastructure (which requires conversion of data to a string) or add code to support their specific data needs. An incomplete simple example follows:

```
//Header file.
class Singleton
{
  SomeType somedata;
  static Singleton *specialdata;
};
```

====
```
Stage1::initialize()
{
  Singleton::specialdata = new Singleton();
};

Stage1::run()
{
  setSomeData(Singleton::specialdata->somedata);
}

```
== Downstream Stage ==

```
Stage2::run()
{
  doSomethingWith(Singleton::specialdata->somedata);
}

Stage2::done()
{
  delete Singleton::specialdata;
}
```

**Comment by jw3** [comment]
>Some code showing use of your key-value store would be helpful.

Sure.  The code is not open as of now, but I will work up a gist at least.

>If a downstream stage is receiving information from another stage, it has to know what this data is and how to deal with it.

I see it as a contractual issue.  A Stage has requirements for binary artifacts the same way it has requirements for ProgramArgs.  If non-optional requirements are missing, it can't do it's job and ideally short circuits as soon as possible.  

Obviously a bit different from ProgramArgs as this is runtime generated values that do not exist at the time the app starts, but the contractual similarities are the same in my mind.

>I'm not sure is any advantage in trying to make something generic that isn't generic.

That's always a important consideration, completely concur.  If PDAL had an integrated way to do it that was flexible and wasn't generic, I would try it.

In our case we wanted to provide the loose coupling and flexibility of a KV store (a map) for this data, to allow clients to share a varying number of things at varying sets of keys.

>Any set of stages that needs special handling of created data can either use the existing metadata infrastructure

Yes, looked there first.  These are potentially large binary artifacts that it wouldn't make sense to serialize.  The best solution there is to write it back to a file and pass the path in the metadata.  But, file IO.

>or add code to support their specific data needs. An incomplete simple example follows

Yeah, makes sense.  Moves the contracts to compile time, which is always good.  Does it offer enough flexibility for clients, and how does it scale development-wise when sharing new things?  I will think about that some in the context of this example, what it means to clients who are creating a stage to drop into the system.

----

Overall our sharing concept seems very similar to the metadata infrastructure.  The difference is that we store pointers and metadata stores strings.  Can metadata be made to handle a `shared_ptr`?

**Comment by jw3** [comment]
See the following gist for a sketch of the components in this design.  Can fill in with more detail if requested.

https://gist.github.com/jw3/3ceac39492a0994c4e1a5634bdb5e3b5

> I will think about that some in the context of this example, what it means to clients who are creating a stage to drop into the system.

I think it comes down to interoperability across stages that do not share an API.  In the case of the [above example](https://github.com/PDAL/PDAL/issues/1785#issuecomment-360159948) they do not share the `Singleton` type.

So, for example if you have a third party PDAL plug-in, in binary form, that you just want to "plug in" and use in a pipeline, where the only common API is PDAL's, and you do not share compilation or have access to the source.  All that is known about this plug-in is that it consumes a vector data input, and produces a raster data output .

If PDAL could support these binary artifacts as it does metadata (Key-Value) then such drop in integrations would be possible.  

From the outside looking in there does not seem to be any semantic difference between what is sharable now between stages and what I propose.  The implementation detail of limiting to string serialization appears to be the primary difference.

Is this any more compelling now? 😄 

Would a `shared_ptr` integration with the metadata machinery be feasible?  Probably requiring a node that gets special handling because they don't really serialize...

**Comment by abellgithub** [comment]
@jw3 : https://github.com/PDAL/PDAL/tree/artifact

**Comment by jw3** [comment]
Thanks, will take it for a spin.

**Comment by jw3** [comment]
Converted ~30 plugins to use this new artifact machinery.  Initial testing says it is working well :+1:
