### ISSUE TITLE
Raster support in filters.overlay

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#1789]
It is common to want to assign the values from a raster cell into a custom specified dimension for further processing. We have the mechanics of this in `filters.colorization`, and it can be made to do this task with some severe contortion (by moving data through `Red`, `Green`, or `Blue` dimensions), but it would be conceptually simpler if it were in `filters.overlay`.

An example pipeline block:

```
    {
      "type":"filters.overlay",
      "dimension":"RasterValue",
      "datasource":"myfile.tif",
      "band":"1"
    }
```

Questions:
* If the `RasterValue` doesn't exist, should `filters.overlay` create it, or should the user create it first with `filters.ferry`?
* What happens when the dimension the user asks to place the `RasterValue` into doesn't match the data type of the `band` requested?

**Comment by abellgithub** [comment]
I don't understand why this isn't exactly what we're already doing with filters.colorization.

**Comment by hobu** [comment]
@gadomski demonstrates the challenges with what's currently possible http://www.gadom.ski/2018/02/28/pdal-hs.html

**Comment by hobu** [comment]
Done in #1841

**Comment by abellgithub** [comment]
Should we open another ticket for renaming?

**Comment by hobu** [comment]
> Should we open another ticket for renaming?

Yeah, I suppose. That would have a grep through the code for docs and links to clean up too.
