### ISSUE TITLE
The filters.ferry is poorly named and backwards

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#1790]
* [ ] Rename `filters.ferry` to `filters.copy`
* [ ] Adjust its syntax to `X => NewDimension` to make it clear what's going where.
* [ ] Clean up all references to `filters.ferry` in docs and tests.

**Comment by abellgithub** [comment]
I added the syntax change [here](https://github.com/PDAL/PDAL/tree/copy). Perhaps this is sufficient? Changing the name will break things for people. This causes no disruption.

**Comment by hobu** [comment]
The syntax was fixed in 1.7.1. We'll hold off on renaming for now.
