### ISSUE TITLE
Base Quickstart on OSGeo4W commands

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#1791]
The https://www.pdal.io/quickstart.html needs to be brought in line with the https://www.pdal.io/workshop/ which is based on OSGeo4W. We should have a small section about how to use Docker that points to the containers, but it shouldn't be the primary interaction mechanism to introduce people to PDAL. When it is, they end up having to learn both PDAL *and* Docker at the same time, which just sets them up for frustration.

**Comment by chambbj** [comment]
Should this be updated to target Conda rather than OSGeo4W or Docker?

**Comment by hobu** [comment]
I vote for Conda

**Comment by chambbj** [comment]
Does all the former Docker content in the quickstart need to be preserved though? I could imagine that users who _want_ to user Docker might still find elements useful, I'm just not sure where this should necessarily live...

**Comment by hobu** [comment]
meh, I'm fine with ditching Docker as any kind of prescribed or documented path to PDAL enlightenment especially now that Conda works so well for most people.

**Comment by hobu** [comment]
Appears done for now. 6e2d2a7363b2969b6e895d21b7e8381978cad7cf
