### ISSUE TITLE
std::max errors

### ISSUE THREAD

**Issue by yanliwenyong** [PDAL/PDAL#1794]
I use OSGEO install PDAL .  IDE use  vs2017 15.2
All *. HPP std::max errors   #idefine max(a,b) .
Can you help me?    Thanks

**Comment by abellgithub** [comment]
You need to provide more specific information about your problem for anyone to help you.

**Comment by yanliwenyong** [comment]
Thank you very much for your reply.

I build Source use Vs2017 Under Windows. With reference to“https://www.pdal.io/development/compilation/windows.html” 

Configuration VS2017 is Release X64. Building  successful.

But, I  create a new project use Vs2017. There will be  std::max errors #idefine max(a,b)

Configuration is as follows:

vc++ Directories
	Include Directories:C:\Program Files\PDAL\include(my pdal install path);C:\OSGeo4W64\include
        Library Directories:C:\Program Files\PDAL\lib;C:\OSGeo4W64\lib

c/c++  Preprocessor
        Add  _CRT_SECURE_NO_WARNINGS


The test code is as follows:

#include<pdal\Dimension.hpp>
#include<pdal\Options.hpp>
#include<pdal\StageFactory.hpp>
#include<pdal\io\BufferReader.hpp>
#include<vector>
#include<pdal\PointTable.hpp>
#include<pdal\PointView.hpp>
#include<pdal\Options.hpp>
#include<pdal\io\LasReader.hpp>
#pragma comment(lib,"ws2_32.lib")
void fillView(pdal::PointViewPtr view)
{
	struct Point
	{
		double x;
		double y;
		double z;
	};
	for (int i = 0; i < 1000; ++i)
	{
		Point p;
		p.x = -93.0 + i*0.001;
		p.y = 42.0 + i*0.001;
		p.z = 106.0 + i;
		view->setField(pdal::Dimension::Id::X, i, p.x);
		view->setField(pdal::Dimension::Id::Y, i, p.y);
		view->setField(pdal::Dimension::Id::Z, i, p.z);
	}
}
int main(int argc, char* argv[])
{
	using namespace pdal;
	Options options;
	options.add("filename", "myfile.las");
	PointTable table;
	table.layout()->registerDim(Dimension::Id::X);
	table.layout()->registerDim(Dimension::Id::Y);
	table.layout()->registerDim(Dimension::Id::Z);
	PointViewPtr view(new PointView(table));
	fillView(view);
	BufferReader reader;
	reader.addView(view);
	StageFactory factory;
	// Set second argument to 'true' to let factory take ownership of
	// stage and facilitate clean up.
	Stage *writer = factory.createStage("writers.las");
	writer->setInput(reader);
	writer->setOptions(options);
	writer->prepare(table);
	writer->execute(table);
}

The error list is as follows:

1>PDALtest.cpp
1>C:\Program Files\PDAL\include\pdal/Metadata.hpp(540): warning C4800: 'unsigned __int64': forcing value to bool 'true' or 'false' (performance warning)
1>C:\Program Files\PDAL\include\pdal/util/ProgramArgs.hpp(1240): error C2589: '(': illegal token on right side of '::'
1>C:\Program Files\PDAL\include\pdal/util/ProgramArgs.hpp(1240): error C2059: syntax error: '::'
1>C:\Program Files\PDAL\include\pdal/util/OStream.hpp(78): warning C4800: 'std::ostream *const ': forcing value to bool 'true' or 'false' (performance warning)

Did I miss any configuration?


Looking forward to your reply.
Thanks!
