### ISSUE TITLE
Bug in filters.cluster

### ISSUE THREAD

**Issue by nickponline** [PDAL/PDAL#1801]
I am trying to cluster the following point cloud: 

https://www.dropbox.com/s/uzns46raol7d7st/clusterbug.las?dl=0

Using 
```
{
      "type":"filters.cluster",
      "min_points" : 100,
      "tolerance" : 2.0
}
```

The results are really weird, distinct clusters have a distinct color/marker type: 

![1500036591_dannyinspire](https://user-images.githubusercontent.com/590151/35949810-40a824ca-0c28-11e8-8dde-4730c22397f0.png)

Notice the blue circles all over the place (top, bottom left and bottom right) belonging to the same cluster even through they are far away from each other.

Can someone help me understand why this is happening or if it's a bug?

**Comment by nickponline** [comment]
Do they represent "unclustered points?"

**Comment by abellgithub** [comment]
Yes.  I'll update the documentation.
