### ISSUE TITLE
Pdal Initialized plugin libpdal_plugin_writer_pgpointcloud.so

### ISSUE THREAD

**Issue by Gwen22200** [PDAL/PDAL#1806]
Hi,

I try to use pdal to import las pointcloud into postgresql database.

First i install pgpointcloud extension with this command : 

git clone https://github.com/pgpointcloud/pointcloud.git
cd pointcloud
mkdir build && cd build
cmake ../
make
sudo make install

CREATE EXTENSION pointcloud;
CREATE EXTENSION pointcloud_postgis;

Then i install pdal library : 
git clone https://github.com/PDAL/PDAL.git pdal
mkdir pdal-build
cd pdal-build
cmake .. 
make install

I update  /etc/ld.so.conf to add /usr/local/lib path where we find pdal.

After that i create a simple pipeline to upload data but nothing appear.

Wen i use debug mode i have this message : 
(pdal pipeline Debug) Plugin search path: '.'
(pdal pipeline Debug) Plugin search path: './lib'
(pdal pipeline Debug) Plugin search path: '../lib'
(pdal pipeline Debug) Plugin search path: './bin'
(pdal pipeline Debug) Plugin search path: '../bin'
(pdal pipeline Debug) Plugin search path: '/usr/local/lib'
(pdal pipeline Debug) Attempting to load plugin '/usr/local/lib/libpdal_plugin_w                      riter_pgpointcloud.so'.
(pdal pipeline Debug) Loaded plugin '/usr/local/lib/libpdal_plugin_writer_pgpointcloud.so'.
(pdal pipeline Debug) Initialized plugin '/usr/local/lib/libpdal_plugin_writer_pgpointcloud.so'.

 

The process wait and nothing in the database, what are going wrong ? i'm in ubuntu server 16.04 and postgresql 9.5

Thank you very much for your help

Gwendal

**Comment by abellgithub** [comment]
Please provide the pipeline you're using.

**Comment by Gwen22200** [comment]
hi @abellgithub 

The definition of the pipeline : 

{
"pipeline":[
{
"type":"readers.las",
"filename":"34_30112017_group1_densified_point_cloud.las"
},
{
"type":"filters.chipper",
"capacity":400
},
{
"type":"writers.pgpointcloud",
"connection":"host=localhost dbname=** user=postgres password=**********",
"table":"test"
}
]
}

Thanks

Gwen

**Comment by abellgithub** [comment]
If you write your output to LAS/text does it work?

**Comment by abellgithub** [comment]
If you can provide a small amount of data that you're having trouble with, that would be helpful.

**Comment by hobu** [comment]
Please reopen this issue if you have example data and a test scenario that demonstrates how it fails.
