### ISSUE TITLE
pdal split forces addition of color channels

### ISSUE THREAD

**Issue by mrosen** [PDAL/PDAL#1814]
pdal split changes PDF to add color when none is available.

Reproduce:

  $ pdal split --capacity 1000 -i ~/dev/PDAL/test/data/las/epsg_4326.las  -o pdal_split.las

The result has color info while the original does not.

**Comment by hobu** [comment]
The default `dataformat_id` is `3`, which has both color and time. https://github.com/PDAL/PDAL/blob/master/io/LasWriter.cpp#L112

You will need to override it by either forwarding or assigning it:

```
pdal split --capacity 1000 
                 -i ~/dev/PDAL/test/data/las/epsg_4326.las 
                 -o pdal_split.las 
                 --writers.las.forward=all
```

```
pdal split --capacity 1000 
                 -i ~/dev/PDAL/test/data/las/epsg_4326.las 
                 -o pdal_split.las 
                 --writers.las.dataformat_id=1
```
