### ISSUE TITLE
pdal split issues with .laz

### ISSUE THREAD

**Issue by mrosen** [PDAL/PDAL#1815]
I'm pdal 1.6.0 built locally with laszip_perf.  I see problems when I use the split command:

#  pdal split posts "the LAZ schema is not recognized", sometimes but not always.
$ pdal split --capacity 5000 -i ~/dev/PDAL/test/data/laz/simple.laz -o pdal_split.las
PDAL: The LAZ schema is not recognized

$ pdal split --capacity 10000000 -i 20146493.laz -o 20146493_part.las
Warning 1: Cannot find pcs.csv
...
(works as expected)

========
msr@msr-laptop build $ pdal split --capacity 10000000 -i 20146493.laz -o 20146493_part.las
(works as expected)

msr@msr-laptop build $ pdal split --capacity 10000000 -i 20146493.laz -o 20146493_part.laz
results in small (520 bytes), invalid files:
msr@msr-laptop from_wright $ lasinfo 20146493_part_7.laz
error: Failed to open LASzip stream: init() of LASreadPoint failed (LASzip v2.0r2)

I get acceptable results using lassplit.exe (under wine).

**Comment by abellgithub** [comment]
#1) The error message is correct.  simple.laz is compressed with version 1 of LAZ, which is not supported by LAZperf.

#2) This has been reported before but we've been unable to recreate. The error comes from GDAL and perhaps it's a GDAL installation issue.

#3 & #4) I have no way to know what's going on without knowing more about the data.

**Comment by mrosen** [comment]
Thanks for the clarifications, I'll see if I can't provide a repro case for the LAZ split issue.

**Comment by mrosen** [comment]
> more

**Comment by abellgithub** [comment]
This is a bug in lazperf.  I opened a ticket: https://github.com/hobu/laz-perf/issues/44
