### ISSUE TITLE
homebrew formula should use options

### ISSUE THREAD

**Issue by asmaloney** [PDAL/PDAL#1816]
(I'm not sure if you maintain the homebrew formula or not. If not, my apologies...)

Currently, PDAL via homebrew tries to install the following dependencies:

`proj, libgeotiff, geos, json-c, freexl, libspatialite, gcc, gdal, szip, hdf5, laszip, cminpack, flann, libusb, qhull, netcdf, vtk, pcl, postgresql`

As I am only interested in LAS support, I would like to install without gdal, hdf5, pcl, postgresql, and whatever else I can turn off. I certainly don't want to install gcc just for this.

```
$ brew info pdal
pdal: stable 1.6, HEAD
Point data abstraction library
https://www.pdal.io/
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/pdal.rb
==> Dependencies
Build: cmake ✔
Required: gdal ✘, hdf5 ✘, laszip ✘, pcl ✘, postgresql ✘
==> Options
--HEAD
	Install HEAD version
```

Thanks!

**Comment by chambbj** [comment]
Others could speak more to it, but I believe the Homebrew maintainers were
pushing for fewer options.

https://github.com/Homebrew/homebrew-core/pull/23134#issuecomment-359284086

**Comment by asmaloney** [comment]
:-) That's funny.

So the opposite of making it useful for other developers then. Guess I'll try to go back to libLAS then.

Thanks!

**Comment by hobu** [comment]
> So the opposite of making it useful for other developers then. Guess I'll try to go back to libLAS then.

Well, we also manage that project, so you are going to find much more to complain about in libLAS than just a fat Homebrew package. It hasn't been maintained in more than 5 years, it doesn't support the latest LASzip, and it is missing most of PDAL's processing features. Maybe, given your challenging requirements, it would be best to write your own library.

**Comment by asmaloney** [comment]
Sorry Howard. Maybe a little harsh. The only thing I need is to read LAS files - which was working with libLAS. I don't want the rest, so given that PDAL seems to be designed to make them optional (yay!) the homebrew thing is very disappointing and makes things more complicated than they need to be (boo!).

**Comment by hobu** [comment]
> the homebrew thing is very disappointing and makes things more complicated than they need to be

Users have exactly the opposite reaction. "I did `brew install pdal` and blah blah blah doesn't work. Your software is broken." We can't win either way here, and given the choice, installing a bit more crap in the Homebrew package generates less support traffic for the project.

**Comment by asmaloney** [comment]
That's why they are "options". If I'm building and installing something with specific options I'm doing it for a reason. So `brew install pdal` call install the kitchen sink, but having the option to not include some features makes it useful for those that don't want everything. I'm not blaming you - you had it right in that first submission, but based on the changes it seems to be the preferred homebrew method. It doesn't make any sense to me.

And it's more than just "installing a bit more crap" - if I'm shipping something based on these libs I have to do tons of fiddling with `otool` and a bunch of extra testing to make sure all the linking and lib finding work properly. That's super annoying when you aren't even going to use the lib (postgresql) or when you are already using one of them and have to then manage and ship different builds of them (gdal).
