### ISSUE TITLE
troubles installing with rivlib

### ISSUE THREAD

**Issue by jgrn307** [PDAL/PDAL#1821]
I'm using the latest (as of this post) GIT of PDAL, and I'm tyring to get rivlib included.  I'm getting this error:

[ 52%] Building CXX object plugins/rxp/CMakeFiles/pdal_plugin_reader_rxp.dir/io/RxpPointcloud.cpp.o
In file included from /root/pdal/plugins/rxp/io/RxpPointcloud.cpp:42:0:
/root/pdal/plugins/rxp/io/RxpPointcloud.hpp:46:32: fatal error: pdal/pdal_macros.hpp: No such file or directory
compilation terminated.
plugins/rxp/CMakeFiles/pdal_plugin_reader_rxp.dir/build.make:62: recipe for target 'plugins/rxp/CMakeFiles/pdal_plugin_reader_rxp.dir/io/RxpPointcloud.cpp.o' failed
make[2]: *** [plugins/rxp/CMakeFiles/pdal_plugin_reader_rxp.dir/io/RxpPointcloud.cpp.o] Error 1
CMakeFiles/Makefile2:394: recipe for target 'plugins/rxp/CMakeFiles/pdal_plugin_reader_rxp.dir/all' failed
make[1]: *** [plugins/rxp/CMakeFiles/pdal_plugin_reader_rxp.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

I am having no luck finding the pdal_macros.hpp searching through the git repo -- was this moved/renamed/deleted from the latest version?

Edit: I'm building a singularity package using Ubuntu xenial.

**Comment by abellgithub** [comment]
It has been removed from the master branch.  Sorry, we don't have a good RXP test build environment.  Just remove the #include line and things should be fine.

**Comment by jgrn307** [comment]
Will it still work without the #include line (I specifically need to be able to work with RIEGL data)?

**Comment by abellgithub** [comment]
Like I said, I have no way to test, but the code that was in "pdal_macros" has been moved as necessary.  Please write back if it fails to build with this line removed.

**Comment by gadomski** [comment]
@jgrn307 current PDAL **master** (35ccb51) doesn't have `#include <pdal/pdal_macros.hpp>` on line 46. Are you sure you're working from the latest **master**? You could also try the **1.6-maintinance** branch for an alternative.

**Comment by abellgithub** [comment]
I just removed it yesterday. Maybe even committed it.
