### ISSUE TITLE
support extra_dims=all in readers.las

### ISSUE THREAD

**Issue by davidcaron** [PDAL/PDAL#1831]
It seems the extra dimensions are ignored by the las reader unless you specify the name and datatype manually.

For example when I try to forward the extra dimensions from input to output:

this works:
`pdal translate --readers.las.extra_dims="new_dim=uint32" --writers.las.extra_dims=all out.las out2.las`

this doesn't:
`pdal translate --readers.las.extra_dims=all --writers.las.extra_dims=all out.las out2.las`

or am I missing something? Would this be possible?

**Comment by abellgithub** [comment]
What is the LAS version of the file you're working with?

**Comment by davidcaron** [comment]
I just tried with versions 1.0 to 1.3 and I get this behavior.

In version 1.4, the extra dimensions are read by default I believe. So the following command works and keeps all extra dimensions in the output:

`pdal translate --writers.las.extra_dims=all v14.las v14_out.las`

So my question only applies to versions 1.0 to 1.3

**Comment by abellgithub** [comment]
You say that the following doesn't work:

`pdal translate --readers.las.extra_dims=all --writers.las.extra_dims=all out.las out2.las`

How so? I would expect an error.

**Comment by davidcaron** [comment]
Well, it doesn't produce an error, but I would expect to keep the extra dimensions of out.las in out2.las and it's not the case.

**Comment by abellgithub** [comment]
I misread some code. It should throw an error, but doesn't.

For LAS 1.0 - 1.3, we have no way to know what is meant by "all" when reading points.  We have no way to know the meaning of the extra bytes on each point unless you tell us.  For LAS 1.4, this information is usually carried in a special VLR, which we read if present.

I suspect that you're wanting to simply tack the "extra" data from input points onto corresponding output points.  PDAL doesn't currently support this.  We have no notion of an "opaque" dimension that is part of a point.  All dimensions must be named and have a type.

**Comment by abellgithub** [comment]
Error added: cfb72b4b810d5efd0d1a9441d2474d057dc39426

**Comment by kbevers** [comment]
> We don't know the meaning of the extra bytes on each point unless you tell us. For LAS 1.4, this information is usually carried in a special VLR, which we read if present.

@abellgithub I have struggled with this in the past, so I understand @davidcaron's frustation. At the same time I understand why the architecture in PDAL makes this not-so-easy to handle. But here's a suggestion that might work: Treat extra bytes of a record as a single dimension in a LAS 1.0-1.3 files. 

If I remember correctly you can derive from the header that there are extra bytes at the end of each record. Dump the extra byte data in a dimension called "extrabytes". Of course this all depends on the ability to create dimension of a generic type that can handle different number of bytes. If it is possible to implement what I am suggesting, PDAL would now be able to do  `--readers.las.extra_dims=all --writers.las.extra_dims=all` since the extra bytes exists as a named dimension internally.

**Comment by davidcaron** [comment]
Ok thanks, I will keep investigating for a solution. I'm trying to bring back this functionality in CloudCompare, which recently switched from libLAS to PDAL. I have no idea how libLAS handled it but it seemed to work.

**Comment by hobu** [comment]
> I have no idea how libLAS handled it but it seemed to work.
libLAS treated it like @kbevers is requesting -- it was just a blob of whatever off the end of the regular point.

**Comment by kbevers** [comment]
@davidcaron 

I am sure you can jury rig something. For instance, from the header you can figure out how many extra bytes is attached to each record and tell PDAL to treat each byte as a new dimesion, so you have something similar to:

 `pdal translate --readers.las.extra_dims="eb1=uint8,eb2=uint8,eb3=uint8" --writers.las.extra_dims=all out.las out2.las`

Add as many `ebx`s as you need. It is not pretty but it (probably) works.

**Comment by davidcaron** [comment]
Here is what I ended up doing.

I found that the VLR record describing the extra bytes after each point is written most of the time in versions <= 1.3. The 1.4 specification says:

> This VLR has been added to LAS 1.4 to formalize a process that has been used in prior versions of LAS.

So I read the VLR manually, made a string of the names and data types, and passed that back to the PDAL reader.

Just a thought: would it be a good idea to look for the extra bytes VLR record for any version? I think that way the command `--readers.las.extra_dims=all` would be implicit, just like it is in v1.4

I made a quick test and it worked:

https://github.com/davidcaron/PDAL/commit/c3acafa4b82e256c055303fc0bdfc790a258787a

The readExtraBytesVlr function does nothing if it can't find the VLR.

Maybe that would have other side effects I'm not aware of.

**Comment by hobu** [comment]
> Just a thought: would it be a good idea to look for the extra bytes VLR record for any version?

It's a question of "is this a valid file if you do that?". The answer is technically no because seeing that VLR is supposed to make software behave in a certain way. From a practical standpoint, the answer is probably "who cares", and I believe @rapidlasso does extrabytes VLRs for any LAS versions, not just 1.4.

**Comment by davidcaron** [comment]
That's what I thought

**Comment by kbevers** [comment]
> From a practical standpoint, the answer is probably "who cares", and I believe @rapidlasso does extrabytes VLRs for any LAS versions, not just 1.4.

We also do this in Laspy. I don't know if it is intentional or not, though. It has saved me from a bunch of trouble in the past and I find that behaviour quite logical and unsurprising even though it is technically incorrect.

**Comment by davidcaron** [comment]
An optional parameter is a good solution, thanks!
