### ISSUE TITLE
How to properly use the dockerfiles with the dependencies?

### ISSUE THREAD

**Issue by jgrn307** [PDAL/PDAL#1833]
I'm trying to figure out how to get a docker working that includes the writers.pcd properly included.  It appears that the current dockers do NOT have this included, but there is another pdal dockerfile (pdal/dependencies) that seems to have everything EXCEPT PDAL installed.  Is there a way to "combine" the two docker files, or am I overthinking this?

**Comment by chambbj** [comment]
None of the current Alpine-based Docker images install PCL or build the plugin. You should be able to build https://github.com/PDAL/PDAL/blob/master/scripts/docker/1.6-maintenance/ubuntu/Dockerfile to get an Ubuntu-based image with PCL though. And yes, you could use the `pdal/dependencies` Docker image as base for your own Dockerfile. This is the way we used it in the past.
