### ISSUE TITLE
Unable to find laszip

### ISSUE THREAD

**Issue by gabri94** [PDAL/PDAL#1835]
Hello, i'm compiling pdal 1.6 on ubuntu xenial
To add the laszip support i compiled the version 3.1.1 and i installed in in /usr  (i also tryied in /usr/local).
Unfortunately there's no way to let pdal find laszip library and so i cannot compile it with the compression support.
Is there something wrong in my procedure? How should i add the support?

**Comment by gabri94** [comment]
Compiling laszip 4.0, pdal is able to find it but it fail to compile.
```
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/liblaszip.so: undefined reference to `LASwriteItemCompressed_RGB14_v4::LASwriteItemCompressed_RGB14_v4(ArithmeticEncoder*)'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/liblaszip.so: undefined reference to `LASwriteItemCompressed_RGBNIR14_v4::LASwriteItemCompressed_RGBNIR14_v4(ArithmeticEncoder*)'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/liblaszip.so: undefined reference to `LASreadItemCompressed_WAVEPACKET14_v4::LASreadItemCompressed_WAVEPACKET14_v4(ArithmeticDecoder*, unsigned int)'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/liblaszip.so: undefined reference to `LASwriteItemCompressed_WAVEPACKET14_v4::LASwriteItemCompressed_WAVEPACKET14_v4(ArithmeticEncoder*)'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/liblaszip.so: undefined reference to `LASreadItemCompressed_RGBNIR14_v4::LASreadItemCompressed_RGBNIR14_v4(ArithmeticDecoder*, unsigned int)'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/liblaszip.so: undefined reference to `LASreadItemCompressed_BYTE14_v4::LASreadItemCompressed_BYTE14_v4(ArithmeticDecoder*, unsigned int, unsigned int)'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/liblaszip.so: undefined reference to `LASwriteItemCompressed_POINT14_v4::LASwriteItemCompressed_POINT14_v4(ArithmeticEncoder*)'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/liblaszip.so: undefined reference to `LASreadItemCompressed_POINT14_v4::LASreadItemCompressed_POINT14_v4(ArithmeticDecoder*, unsigned int)'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/liblaszip.so: undefined reference to `LASreadItemCompressed_RGB14_v4::LASreadItemCompressed_RGB14_v4(ArithmeticDecoder*, unsigned int)'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/liblaszip.so: undefined reference to `LASwriteItemCompressed_BYTE14_v4::LASwriteItemCompressed_BYTE14_v4(ArithmeticEncoder*, unsigned int)'
```

**Comment by abellgithub** [comment]
It's really unclear what you're doing or what the problem is.  The last release of laszip is 3.1.1: https://github.com/LASzip/LASzip/releases.

**Comment by gabri94** [comment]
I'm trying to compile pdal in ubuntu. In order to enable the laszip support i have to compile and install laszip in my system.
I compiled and installed laszip from git (v3.1.1), but pdal was unable to find my laszip installation and thus to enable the support.
I tried to install it in both /usr/local and /usr.
By compiling the master branch of laszip (v4.0.0) pdal was able to find it, but not to compile.

**Comment by abellgithub** [comment]
You can apply this fix to your 3.1.1 source before you build/install laszip:

https://github.com/LASzip/LASzip/commit/2149a3c472406f2867538cb211c5736c28050baa

**Comment by abellgithub** [comment]
Is this resolved for you?

**Comment by adamsteer** [comment]
Hi @gabri94 - what's your compile command? eg `cmake ...`

did you use `-DWITH_LASZIP=ON`? 

Asking because I've just built PDAL 1.7.1 (master) with LASzip (master - 3 commits upward of 3.2.2) support on Artful (17.10) - with no special wrangling.
