### ISSUE TITLE
Can anyone help me in converting .las file to .pcd file using PDAL

### ISSUE THREAD

**Issue by niranjanreddy891** [PDAL/PDAL#1837]
`C:\OSGeo4W64\bin>pdal translate E:/Lidar-practice/New-data/LAS12_Sample_withInte
nsity_Quick_Terrain_Modeler.las test.pcd
PDAL: Couldn't create writer stage of type 'writers.pcd'.` 

This is the error I am facing while using command `pdal translate input.las output.pcd`. Thanks in advance

**Comment by abellgithub** [comment]
You need to build the PCL plugin.  See question/answer 2 [here](https://www.pdal.io/faq.html)

**Comment by niranjanreddy891** [comment]
Can you please provide any sample on how to build PDAL plugin. I couldn't understand the link which you mentioned @abellgithub . Thanks

**Comment by abellgithub** [comment]
From the FAQ:

"If you’ve built pdal yourself, make sure you’ve requested to build the plugin in question (set BUILD_PLUGIN_PCL=ON, for example, in CMakeCache.txt)."

If PCL is properly installed on your system, that should be all you need. Re-run cmake.

**Comment by niranjanreddy891** [comment]
how to run this `set BUILD_PLUGIN_PCL=ON` command?

**Comment by chambbj** [comment]
Are you building PDAL yourself? Or were you just working with the OSGeo distribution?

Windows compilation instructions can be found in the [docs](https://www.pdal.io/development/compilation/windows.html). The section on [configuration](https://www.pdal.io/development/compilation/windows.html#configuration) talks about running CMake to configure the build. There is even a detailed [example](https://github.com/PDAL/PDAL/blob/master/cmake/examples/hobu-windows.bat) provided for you.

**Comment by niranjanreddy891** [comment]
I am using OSGeo distribution

**Comment by niranjanreddy891** [comment]
Can anyone help me in this issue

**Comment by mloskot** [comment]
AFAICT, the OSGeo4W does not install PCL, so the PCD drivers are not supported

```
C:\>pdal --drivers | findstr las
readers.las                  ASPRS LAS 1.0 - 1.4 read support. LASzip support
writers.las                  ASPRS LAS 1.0 - 1.4 writer. LASzip support is also

C:\>pdal --drivers | findstr pcd

C:\>
```

I think, your choices are PDAL docker or building PDAL from sources yourself, as @chambbj explained in https://github.com/PDAL/PDAL/issues/1837#issuecomment-372355143

**Comment by jgrn307** [comment]
Sorry to re-open this, any chance we can get the PDAL and LAS plugins added to the latest DOCKER release?  I've had to go back to the 1.6-ubuntu image to get these (easily) working.
