### ISSUE TITLE
Manual destruction of pipeline from within kernel

### ISSUE THREAD

**Issue by jw3** [PDAL/PDAL#1838]
In a custom `Kernel` implementation we need to ensure all stages have been destroyed prior to the kernel exiting so that other shutdown logic can run.

We were unable to find a way to do this so we added a [`destroyAllStages`](https://github.com/jw3/PDAL/commit/9d61d5d79221f996d9c0ed43ac3eea760331f765) method to `PipelineManager` that can be invoked from a `Kernel` after the execution completes.

I'll PR that branch if there is not an existing or better way to accomplish this.

Thanks

**Comment by jw3** [comment]
A kernel that utilizes this looks like

```
Kernel::execute()
{
  doStuff();
  m_pipeline.destroyAllStages();
  otherShutdownLogic();  // has to run after all stages have been cleaned up
}
```

**Comment by abellgithub** [comment]
Can you not simply delete the PluginManager?

**Comment by jw3** [comment]
>Can you not simply delete the PluginManager?

It's not a pointer.

https://github.com/PDAL/PDAL/blob/master/pdal/Kernel.hpp#L105

**Comment by jw3** [comment]
I don't see what you are referring to about deleting the `PluginManager`.  Can you give a small snip?

**Comment by abellgithub** [comment]
I was writing while I was out. Forgot that the Kernel owned the PluginManager.

**Comment by abellgithub** [comment]
You should probably just reset the StageFactory.

**Comment by jw3** [comment]
Are you saying move the logic I am proposing down into the `StageFactory` as a `reset` method?

Or is there some other type of reset mechanism I am missing?

**Comment by abellgithub** [comment]
```
PipelineManager::destroyStage()
{
    m_factory.reset(new StageFactory());
}
```

or fancier:

```
PipelineManager::destroyStage(Stage *s = nullptr)
{
    if (s)
        m_factory->destroyStage(s);
    else
        m_factory.reset(new StageFactory());
}
```

**Comment by jw3** [comment]
Oh I see now.  I was working out of 1.6-maintenance, and then I cherry picked it over to an old version of master, in both of those I failed to notice [the changes](https://github.com/PDAL/PDAL/commit/9b3b340c7bc10e278d3674ee7be3e976d4bfa75a) you recently made  :)

Your fancier approach looks sane to me.

Any chance we could get support in 1.6 for this capability?  Would that look similar to what I had... or even just exposing `destroyStage` up in PipelineManager would work.

**Comment by hobu** [comment]
> Any chance we could get support in 1.6 for this capability

We are hoping to kick out 1.7 next week at the [OSGeo Bonn Code Sprint](https://wiki.osgeo.org/wiki/OSGeo_Code_Sprint_2018)

**Comment by jw3** [comment]
>We are hoping to kick out 1.7 next week at the OSGeo Bonn Code Sprint

OK.  Gotcha.  We are pretty late in our sprint to bump to 1.7.  We could just patch 1.6 here for now and then bump to 1.7 next sprint.

**Comment by jw3** [comment]
Thanks :+1:
