### ISSUE TITLE
Sqlite built without load_extensions

### ISSUE THREAD

**Issue by bildsoe** [PDAL/PDAL#1839]
So I'm almost ready to give up. I've actually managed to build PDAL, after several nights of trying installing different dependencies. (Boost... required for PCLblock filter).

But now I have a new problem. I get an error with Sqlite. It tells me that I have the version without "load_extensions" enabled.

> -- Performing Test SQLITE3_HAS_LOAD_EXTENSION
> -- Performing Test SQLITE3_HAS_LOAD_EXTENSION - Failed
> -- Found SQLITE3: C:/OSGeo4W64/lib/sqlite3_i.lib
> CMake Error at cmake/sqlite.cmake:7 (message):
>   SQLite3 compiled without load extension, which is required.  Please
>   re-compile SQLite3 with load extension or ensure CMake is pointing at the
>   correct SQLite3 installation.
> Call Stack (most recent call first):
>   plugins/sqlite/CMakeLists.txt:5 (include)

I'm using the Sqlite thats part of the OSGeo4W package (which recommended in the build-section of the documentation). 

My end-goal is to have PCLblock-filter included inorder for me to use the VoxelGrid filter.

**Comment by hobu** [comment]
SQLite is not required and you can build without it by setting `-DBUILD_PLUGIN_SQLITE=OFF` in your configuration.

**Comment by chambbj** [comment]
Also, please note that PDAL has a built-in VoxelGrid filter called
filters.voxelcentroidnearestneighbor (
https://www.pdal.io/stages/filters.voxelcentroidnearestneighbor.html).

Two advantages of changing the filter are 1) you won't require PCL at all,
and 2) actual points (along with their full point record) will be returned.
PCL's VoxelGrid will drop everything but XYZIRGB.

**Comment by hobu** [comment]
> Two advantages of changing the filter are 1) you won't require PCL at all,
and 2) actual points (along with their full point record) will be returned.
PCL's VoxelGrid will drop everything but XYZIRGB.

And 3), it's already in OSGeo4W.

**Comment by bildsoe** [comment]
Wow, that was what I call a quick response :) Thanks.

@hobu I actually tried turning Sqlite off (but part of me also thought this was a suboptimal solution, if I was ever to need it) - then I could build it, but upon running it (pdal pipeline proces.json), I got an error with Spatialite.dll - and as far as I know it's an extension of Sqlite?

**Comment by bildsoe** [comment]
3) Yes it's in PSGero4W but I still get an error of it being a version without "load_extensions" included. And I've cheked, I only have this one installation of Sqlite - and it is correctly referenced

**Comment by bildsoe** [comment]
After disabling Sqlite - I get this error:

![image](https://user-images.githubusercontent.com/2458362/37306212-44e9f1b6-2637-11e8-9dd3-3cd2d3d4bde7.png)

But also the result of my build isn't complete

> ========== Build: 91 succeeded, 18 failed, 7 up-to-date, 4 skipped ==========

**Comment by hobu** [comment]
https://github.com/PDAL/PDAL/tree/master/scripts/appveyor and https://github.com/PDAL/PDAL/blob/master/appveyor.yml show how we build the OSGeo4W packages. I'm not sure why you are getting this error. First suspicion is you have a spatialite.dll in your path somewhere that you don't expect.

**Comment by bildsoe** [comment]
You're probably right. I'm just having difficulty understanding, why this is a problem if Sqlite isn't included in the build.

For now I'm going to use the filters.voxelcentroidnearestneighbor, but I would liek to be able to build it with PCL support.

Thanks for your help.
