### ISSUE TITLE
LAS -> PCD error

### ISSUE THREAD

**Issue by jgrn307** [PDAL/PDAL#1846]
Folks, I'm having an error converting from .las to .pcd format via pdal translate.  Suggestions?  

pdal translate P002_E1_clip.las P002_E1_clip.pcd
PDAL: Unable to fetch data and convert as requested: Red:uint16_t(22662) -> unsigned char
PDAL: Unable to fetch data and convert as requested: Red:uint16_t(22662) -> unsigned char

**Comment by abellgithub** [comment]
The error is telling you that a value in your source LAS file is too large to fit in the space provided for it in the PCD output. (The value 22662 won't fit in an unsigned char.)

**Comment by jgrn307** [comment]
I've been working off the 1.6-ubuntu docker image.  Is that available from that image?

A little nooby here, sorry -- what value in the LAS file is it likely reading that is out of range?  A brightness value for "Red"?  All I want is a PCD of the x,y,z point locations from the LAS file.

**Comment by abellgithub** [comment]
The pcd writer has an option `--xyz` that will only write the X Y and Z dimensions.

**Comment by jgrn307** [comment]
How I include that into the pdal translate command above?  

pdal translate --xyz P002_E1_clip.las P002_E1_clip.pcd
Yields:
PDAL: kernels.translate: Unexpected argument 'xyz'.
PDAL: kernels.translate: Unexpected argument 'xyz'.

**Comment by jgrn307** [comment]
pdal translate --writers.pcd.xyz P002_E1_clip.las P002_E1_clip.pcd
PDAL: Stage option 'writers.pcd.xyz' must be specified  as --writers.pcd.xyz=<value>.

PDAL: Stage option 'writers.pcd.xyz' must be specified  as --writers.pcd.xyz=<value>.

:(

**Comment by abellgithub** [comment]
pdal translate --writers.pcd.xyz=true P002_E1_clip.las P002_E1_clip.pcd

**Comment by jgrn307** [comment]
That did it!  Thanks!  Quick follow-up -- is there a way to run this in a somewhat more memory-safe fashion?  I'm having to throw a TON of memory (64GB RAM for a ~ 13GB LAS file) to do the translation.  Cheers!

**Comment by abellgithub** [comment]
Not at this time.
