### ISSUE TITLE
Request: up-to-date Docker image with all (or most) drivers?

### ISSUE THREAD

**Issue by jgrn307** [PDAL/PDAL#1847]
This is a request rather than a bug -- would it be possible to get a docker image with all the latest-and-greatest PDAL updates that has all (or as many as possible) of the read/write drivers?  I have been using the 1.6-ubuntu docker image but I suspect that is a bit out-of-date, but it was the latest working image I could find on the Docker hub that has the PCD and LAS drivers functional.

Thanks!

**Comment by sjdrc** [comment]
It would be good if the [quickstart page](https://www.pdal.io/quickstart.html#quickstart) specified to use this image. [This](https://www.pdal.io/tutorial/pcl_block_tutorial.html) tutorial page claims that the 1.6 image specified on the quickstart page includes built in PCL support but only 1.6-ubuntu includes it.

**Comment by jgrn307** [comment]
Wanted to re-bump this -- any chance we can get a 1.7.x docker image  with all of the drivers that aren't licensed built?  Specifically, the PCD drivers?

**Comment by msmitherdc** [comment]
You can use this docker image `msmitherdc/pdal:1.7`, it has pcl and includes pcd reader and writer

**Comment by hobu** [comment]
Things should be in order now. `pdal/pdal` is currently Alpine-based, but `pdal/ubuntu` is available if you need that flavor.
