### ISSUE TITLE
Add filters.proj

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#1848]
A filter based on PROJ directly rather than through GDAL would provide a few benefits:

* direct access to PROJ 5+'s transform pipeline
* less data copying through PDAL => GDAL => PROJ => GDAL => PDAL
* chance at doing parallel operations
* one less translation layer to lose coordinate transformation definitions.

**Comment by abellgithub** [comment]
What transformations does GDAL do that PROJ doesn't?

**Comment by msmitherdc** [comment]
@abellgithub its actually the other way around, there are many things that proj.5 can do that gdal can't as its using the pre proj.5 api.

**Comment by msmitherdc** [comment]
gdal does handle all the spatial reference info and convert things to proj strings

**Comment by abellgithub** [comment]
So do we need filters.proj, or do we just need to make filters.reprojection use proj directly?

**Comment by kbevers** [comment]
> So do we need filters.proj, or do we just need to make filters.reprojection use proj directly?

I won't be the judge of that but will note that "reprojection" is an utterly bad name since there's much more that projections at play here. So introducing a new filter with a better name would be welcome.

**Comment by abellgithub** [comment]
Not sure proj is much different from reprojection - just seems a shortening.

And what else is going on? I'm pretty clueless on this stuff.

**Comment by kbevers** [comment]
> And what else is going on? I'm pretty clueless on this stuff.

Projection is the mapping of the sphere to the plane (at least in this geospatial context). In many cases when you are changing coordinate reference system, what you are really doing is changing reference frame (also known as a datum). It can include reprojection but is a more fundamental change of the earth model that coordinates relate to. Sometimes it is as simple as a basic translation of coordinates, other times it requires [a rather complicated chain of operations to fully deal with the change of reference frame](http://proj4.org/operations/transformations/deformation.html#example). 

I agree that filters.proj is not a particularly better name. It does hint at the underlying library like filters.hexbin, filters.matlab, etc. filters.coordinate_transformation would be a generic, descriptive name but is quite long. filters.transformation would also work but it is already occupied (although a PROJ-based filters.transfomation would be able to do the same thing).

**Comment by hobu** [comment]
> filters.transformation would also work but it is already occupied

``filters.transformation`` would be an ok place to put this functionality. The purpose of this ticket is to provide direct access to PROJ 5.0+ functionality without GDAL in between. For most users, GDAL-based ``filters.reprojection`` is going to be just fine, but for the other ~30% of folks, the ability to do transformations that consist of multiple shifts is a definite need. Now that the functionality is available in PROJ 5.0+, we can just hand it all off to that.

**Comment by hobu** [comment]
https://gdalbarn.com/ is going to take care of the mechanics of defining the transformations from WKT and applying all of the shifts and transforms contained in them. Let's reopen this ticket when we're ready to jump to pure PROJ for performance reasons.
