### ISSUE TITLE
missing data fields when reading raw sonar file (MBF_EMOLDRAW)

### ISSUE THREAD

**Issue by epifanio** [PDAL/PDAL#1852]
I found some minor issues on a raw sonar dataset (Old Simrad format: MBF_EMOLDRAW). 

test file available at:

* https://nextcloud.epinux.com/index.php/s/P492fH5tWCFS4tH

The issue is that not all the dimensions are included in the resulting  PDAL data structure, from `mbinfo` I see the `Sidescan ` field is not recognized by PDAL

* `mbinfo -I{inputfilename}`
```
Swath Data File:      0001_RAW.ALL
MBIO Data Format ID:  51
Format name:          MBF_EMOLDRAW
Informal Description: Old Simrad vendor multibeam format
Attributes:           Simrad EM1000, EM12S, EM12D, 
                      and EM121 multibeam sonars,
                      bathymetry, amplitude, and sidescan,
                      60 beams for EM1000, 81 beams for EM12S/D,
		      121 beams for EM121, variable pixels,
		      ascii + binary, Simrad.

Data Totals:
Number of Records:                        6734
Bathymetry Data (121 beams):
  Number of Beams:           814814
  Number of Good Beams:      385771     47.34%
  Number of Zero Beams:      429043     52.66%
  Number of Flagged Beams:        0      0.00%
Amplitude Data (121 beams):
  Number of Beams:           814814
  Number of Good Beams:      385771     47.34%
  Number of Zero Beams:      429043     52.66%
  Number of Flagged Beams:        0      0.00%
Sidescan Data (1024 pixels):
  Number of Pixels:         6895616
  Number of Good Pixels:    4902051     71.09%
  Number of Zero Pixels:          0      0.00%
  Number of Flagged Pixels: 1993565     28.91%

Navigation Totals:
Total Time:             1.2190 hours
Total Track Length:    28.4434 km
Average Speed:         23.3326 km/hr (12.6122 knots)

Start of Data:
Time:  11 09 1998 19:45:49.910000  JD313 (1998-11-09T19:45:49.910000)
Lon:   -69.045371667     Lat:    41.134296568     Depth:   102.7800 meters
Speed: 21.9600 km/hr (11.8703 knots)  Heading: 252.7000 degrees
Sonar Depth:    2.1500 m  Sonar Altitude:  100.6300 m

End of Data:
Time:  11 09 1998 20:58:58.460000  JD313 (1998-11-09T20:58:58.460000)
Lon:   -69.046525300     Lat:    40.895848400     Depth:    79.8800 meters
Speed: 22.3200 km/hr (12.0649 knots)  Heading: 178.9000 degrees
Sonar Depth:    1.9400 m  Sonar Altitude:   77.9400 m

Limits:
Minimum Longitude:     -69.053638788   Maximum Longitude:     -69.040874589
Minimum Latitude:       40.895772214   Maximum Latitude:       41.144692660
Minimum Sonar Depth:     0.9800   Maximum Sonar Depth:     3.2000
Minimum Altitude:       -2.8000   Maximum Altitude:      101.5900
Minimum Depth:          56.9200   Maximum Depth:         140.1800
Minimum Amplitude:     -60.0000   Maximum Amplitude:       0.5000
Minimum Sidescan:      -64.0000   Maximum Sidescan:        0.5000
```

* `pdal info --driver readers.mbio --readers.mbio.format="MBF_EMOLDRAW" {filename}  `

```
{
  "filename": "0001_RAW.ALL",
  "pdal_version": "1.6.0 (git-version: a3b3da)",
  "stats":
  {
    "bbox":
    {
      "native":
      {
        "bbox":
        {
          "maxx": -69.04131799,
          "maxy": 41.14447534,
          "maxz": -56.92,
          "minx": -69.05326568,
          "miny": 40.89582026,
          "minz": -140.18
        },
        "boundary": {
   "coordinates" : [
      [
         [ -69.053265679999996, 40.895820260000001 ],
         [ -69.053265679999996, 41.14447534 ],
         [ -69.041317989999996, 41.14447534 ],
         [ -69.041317989999996, 40.895820260000001 ],
         [ -69.053265679999996, 40.895820260000001 ]
      ]
   ],
   "type" : "Polygon"
}

      }
    },
    "statistic":
    [
      {
        "average": -69.04623589,
        "count": 196066,
        "kurtosis": -3.674571374e+20,
        "maximum": -69.04131799,
        "minimum": -69.05326568,
        "name": "X",
        "position": 0,
        "skewness": -8.167264828e+21,
        "stddev": 0.1559350276,
        "variance": 0.02431573284
      },
      {
        "average": 41.02207459,
        "count": 196066,
        "kurtosis": 1.511722763e+22,
        "maximum": 41.14447534,
        "minimum": 40.89582026,
        "name": "Y",
        "position": 1,
        "skewness": 4.036481416e+21,
        "stddev": 0.1174951596,
        "variance": 0.01380511254
      },
      {
        "average": -84.99609387,
        "count": 196066,
        "kurtosis": 1.21135417e+18,
        "maximum": -56.92,
        "minimum": -140.18,
        "name": "Z",
        "position": 2,
        "skewness": -1.475147148e+17,
        "stddev": 8.886753488,
        "variance": 78.97438755
      },
      {
        "average": -26.52734028,
        "count": 196066,
        "kurtosis": 8.033911962e+16,
        "maximum": -0.75,
        "minimum": -60,
        "name": "Amplitude",
        "position": 3,
        "skewness": -1.354060954e+16,
        "stddev": 7.060398888,
        "variance": 49.84923246
      }
    ]
  }
}
```

**Comment by abellgithub** [comment]
When I wrote the interface I didn't understand how the data should be interpreted, so I left out the sidescan data.

I'm using the mb_read function descriped [here](https://www3.mbari.org/data/mbsystem/html/mbio.html).  I'm mapping the bath lat/lon values to X/Y/Z, but the array of sidescan data seems not to be tied to the bath values (at least not guaranteed), so I'm not sure what should be done.  Should one assume that the arrays are the same and the X/Y positions match? How should points with sidescan data be created from the data returned by the mb_read interface?

Thanks for any help.

**Comment by epifanio** [comment]
@abellgithub thanks for the pointer to `mb_read` (again :) ) I see in the description : 
```
Sidescan is generally constructed with
a higher spatial resolution than bathymetry, and carries its
own location parameters.
```
So my best guess, is you did the right thing in not merging the sidescan within the Amplitude.

I wonder how/where the sidescan position is stored ... if it is at all.
Maybe there is a larger number of sidescan data-points for each ping, compared with the number of Amplitude data-points (per ping).
If that's the case the "along-track" resolution of the sidescan and  Amplitude should be the same, while the across track will be different. (with the sidescan being more dense).
If there is no position information for the sidescan, maybe and the difference in data-points density can be considered constant for each ping, then one could be able to extrapolate the sidescan position  at each ping ... but the it would generate a different data-file in terms of output from a pdal pipeline. 

Hope it make sense, as I'm going through this I also found that extra information (which are important for the use of the data in postprocessing) like [sound velocity profiles](https://gist.github.com/epifanio/3bc8d7615522e07fcfc8f54e9ff09455) got discarded I guess because not part of `mb_read` function ? is that correct? One thing would make a lot of sense is to have the time included in the data, I know that there will be duplication because each N datapoint (where N is the number of beams) will share the same time ... but this will allow postporcessing of the data-points position by merging the information from IMU data etc ..

Thanks for your help in making PDAL reading sonar data, already as it is makes possible to render raw sonar data on the vessel bridge!

**Comment by abellgithub** [comment]
My understanding is that the sidescan data is essentially a simultaneous but separate data collection.  I'm not sure what a user would desire, but it seems like it only makes sense to read the sidescan data or the multibeam data, but not both, since the locations and data are essentially different.  I can work on this functionality if it makes sense.  Please let me know your thoughts.

**Comment by epifanio** [comment]
@abellgithub,  having PDAL able to read both the `sidescan` and the `amplitude+depth` by passing on a user specified argument in the pipeline would be great.
This way the user can have two separate pipeline acting on a the same datasource to produce two distinct point-cloud dataset :

* x,y,z,Amplitude
* x,y,Sidescans

An other information which is  available in the raw data and is essential for proper post-processing of a sonar dataset (it is used to reduce artifacts due to uncompensated vessel motion) is the `ping time` (see previous comment). Of course this info will be repeated `N` times  for points belonging to the same 'ping' (where `N` is the number of beam per ping).

**Comment by abellgithub** [comment]
@epifanio 
I added support for reading sidescan data [here](https://github.com/PDAL/PDAL/tree/mbio).  You read sidescan data by using the option --datatype=sidescan.  I can't test because I have no data.  Are you able to provide a small test file or test yourself?

I haven't done anything with the GPS time yet.

**Comment by epifanio** [comment]
@abellgithub 👍  great! - I'm setting up a new build with the `mbio` branch. I will conduct some test and share a directory with at least 4 different data formats which can be used for further testing purposes.

**Comment by epifanio** [comment]
@abellgithub, I'm trying to build from a fresh checkout PDAL:mbio I got this error:

```
[ 43%] Building CXX object plugins/mbio/CMakeFiles/pdal_plugin_reader_mbio.dir/io/MbReader.cpp.o
In file included from /home/epinux/dev/src/PDAL/plugins/mbio/io/MbReader.hpp:44:0,
                 from /home/epinux/dev/src/PDAL/plugins/mbio/io/MbReader.cpp:35:
/usr/include/mbsystem/mb_define.h:966:19: error: redundant redeclaration of ‘int mb_swap_check()’ in same scope [-Werror=redundant-decls]
 int mb_swap_check();
                   ^
/usr/include/mbsystem/mb_define.h:841:5: note: previous declaration of ‘int mb_swap_check()’
 int mb_swap_check(void);
     ^
cc1plus: all warnings being treated as errors
plugins/mbio/CMakeFiles/pdal_plugin_reader_mbio.dir/build.make:62: recipe for target 'plugins/mbio/CMakeFiles/pdal_plugin_reader_mbio.dir/io/MbReader.cpp.o' failed
make[2]: *** [plugins/mbio/CMakeFiles/pdal_plugin_reader_mbio.dir/io/MbReader.cpp.o] Error 1
CMakeFiles/Makefile2:263: recipe for target 'plugins/mbio/CMakeFiles/pdal_plugin_reader_mbio.dir/all' failed
make[1]: *** [plugins/mbio/CMakeFiles/pdal_plugin_reader_mbio.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
```

```
mbinfo -v

Program MBINFO
Version $Id: mbinfo.c 2261 2016-01-07 01:49:22Z caress $
MB-system Version 5.5.2274
```

**Comment by abellgithub** [comment]
This is an issue with the version of mb-system you're using.  Simply remove the second declaration on line 966 of mb_define.h and it should be fine.  I'd make the change and a request to integrate but the mb-system owners don't provide an easy way to do this.

**Comment by epifanio** [comment]
I'll continue the test for the side-scan variables and provide you the link to test dataset

**Comment by epifanio** [comment]
@abellgithub I've built pdal using the mbio branch:
 ```
epinux@Ubuntu-1604-xenial-64-minimal:~$ cd dev/src/PDAL/
epinux@Ubuntu-1604-xenial-64-minimal:~/dev/src/PDAL$ git branch
* mbio

```
How should I use the `--datatype=sidescan` option?

```
pdal info --driver readers.mbio --readers.mbio.format="MBF_EMOLDRAW" --datatype=sidescan /home/epinux/notebooks/0001_RAW.ALL
PDAL: kernels.info: Unexpected argument 'datatype'.
```

**Comment by abellgithub** [comment]
`datatype` is an option of the stage `readers.mbio`, so you need to specify it as you do the `format` option: `--readers.mbio.datatype=sidescan`

**Comment by epifanio** [comment]
Thanks @abellgithub , I tested it on the same dataset I attached at the top of this issue 

* test file available at:

https://nextcloud.epinux.com/index.php/s/54kLFZfNj3dVsw3/download

The command is returning values for the Intensity but with a wrong range and with null position, this is the output of `pdal info` and `mbinfo`:

pdal info --driver readers.mbio --readers.mbio.format="MBF_EMOLDRAW" 0001_RAW.ALL
{
  "filename": "\/home\/epinux\/notebooks\/0001_RAW.ALL",
  "pdal_version": "1.6.0 (git-version: fb90ef)",
  "stats":
  {
    "bbox":
    {
      "native":
      {
        "bbox":
        {
          "maxx": -69.049807,
          "maxy": 40.89582026,
          "maxz": -83.49,
          "minx": -69.049807,
          "miny": 40.89582026,
          "minz": -83.49
        },
        "boundary": {
   "coordinates" : [
      [
         [ -69.049807000000001, 40.895820260000001 ],
         [ -69.049807000000001, 40.895820260000001 ],
         [ -69.049807000000001, 40.895820260000001 ],
         [ -69.049807000000001, 40.895820260000001 ],
         [ -69.049807000000001, 40.895820260000001 ]
      ]
   ],
   "type" : "Polygon"
}

      }
    },
    "statistic":
    [
      {
        "average": -69.049807,
        "count": 196066,
        "kurtosis": 196063,
        "maximum": -69.049807,
        "minimum": -69.049807,
        "name": "X",
        "position": 0,
        "skewness": -8.16809663e+21,
        "stddev": 0.1559417603,
        "variance": 0.02431783259
      },
      {
        "average": 40.89582026,
        "count": 196066,
        "kurtosis": 196063,
        "maximum": 40.89582026,
        "minimum": 40.89582026,
        "name": "Y",
        "position": 1,
        "skewness": 8.16809663e+21,
        "stddev": 0.09235892864,
        "variance": 0.0085301717
      },
      {
        "average": -83.49,
        "count": 196066,
        "kurtosis": 196063,
        "maximum": -83.49,
        "minimum": -83.49,
        "name": "Z",
        "position": 2,
        "skewness": -8.16809663e+21,
        "stddev": 0.1885534244,
        "variance": 0.03555239385
      },
      {
        "average": 0,
        "count": 196066,
        "maximum": 0,
        "minimum": 0,
        "name": "Intensity",
        "position": 3,
        "stddev": 0,
        "variance": 0
      },
      {
        "average": -34.5,
        "count": 196066,
        "kurtosis": 196063,
        "maximum": -34.5,
        "minimum": -34.5,
        "name": "Amplitude",
        "position": 4,
        "skewness": -8.16809663e+21,
        "stddev": 0.07791463818,
        "variance": 0.006070690842
      }
    ]
  }
}
```

* with `--readers.mbio.datatype=sidescan` option:

epinux@Ubuntu-1604-xenial-64-minimal:~/dev/src/PDAL$ pdal info --driver readers.mbio --readers.mbio.format="MBF_EMOLDRAW" --readers.mbio.datatype=sidescan 0001_RAW.ALL
{
  "filename": "\/home\/epinux\/notebooks\/0001_RAW.ALL",
  "pdal_version": "1.6.0 (git-version: fb90ef)",
  "stats":
  {
    "bbox":
    {
      "native":
      {
        "bbox":
        {
          "maxx": 0,
          "maxy": 0,
          "maxz": 0,
          "minx": 0,
          "miny": 0,
          "minz": 0
        },
        "boundary": {
   "coordinates" : [
      [
         [ 0, 0 ],
         [ 0, 0 ],
         [ 0, 0 ],
         [ 0, 0 ],
         [ 0, 0 ]
      ]
   ],
   "type" : "Polygon"
}

      }
    },
    "statistic":
    [
      {
        "average": 0,
        "count": 3447808,
        "maximum": 0,
        "minimum": 0,
        "name": "X",
        "position": 0,
        "stddev": 0,
        "variance": 0
      },
      {
        "average": 0,
        "count": 3447808,
        "maximum": 0,
        "minimum": 0,
        "name": "Y",
        "position": 1,
        "stddev": 0,
        "variance": 0
      },
      {
        "average": 0,
        "count": 3447808,
        "maximum": 0,
        "minimum": 0,
        "name": "Z",
        "position": 2,
        "stddev": 0,
        "variance": 0
      },
      {
        "average": -1000000000,
        "count": 3447808,
        "kurtosis": 3447805,
        "maximum": -1000000000,
        "minimum": -1000000000,
        "name": "Intensity",
        "position": 3,
        "skewness": -3.425241987e+22,
        "stddev": 538553.0955,
        "variance": 2.900394367e+11
      },
      {
        "average": 0,
        "count": 3447808,
        "maximum": 0,
        "minimum": 0,
        "name": "Amplitude",
        "position": 4,
        "stddev": 0,
        "variance": 0
      }
    ]
  }
}
```

* From the `mbinfo` output:
```
Limits:
Minimum Longitude:     -69.053638788   Maximum Longitude:     -69.040874589
Minimum Latitude:       40.895772214   Maximum Latitude:       41.144692660
Minimum Sonar Depth:     0.9800   Maximum Sonar Depth:     3.2000
Minimum Altitude:       -2.8000   Maximum Altitude:      101.5900
Minimum Depth:          56.9200   Maximum Depth:         140.1800
Minimum Amplitude:     -60.0000   Maximum Amplitude:       0.5000
Minimum Sidescan:      -64.0000   Maximum Sidescan:        0.5000
```

The `Sidescan` range should be between  `-64.0000 , 0.5000`

**Comment by epifanio** [comment]
@abellgithub I stored a series of test dataset on my personal cloud, the files are described below:

* Kongsberg **.all** (probably the most common format)
[MBF_EM710RAW](https://nextcloud.epinux.com/index.php/s/BVWXbUWxFwLh25o) 37.4 MB

```
Swath Data File:      0000_20150605_152944_RVCS.all
MBIO Data Format ID:  58
Format name:          MBF_EM710RAW
Informal Description: Kongsberg current multibeam vendor format
Attributes:           Kongsberg EM122, EM302, EM710,
                      bathymetry, amplitude, and sidescan,
                      up to 400 beams, variable pixels, binary, Kongsberg.
```

* Hypack **HSX** (this is generated by the Hypack acquisition software)

[MBF_HYSWEEP1](https://nextcloud.epinux.com/index.php/s/OGG5OVkN7dH2LG6) 18.5 MB
```
Swath Data File:      0000_20150605_152944_RVCS.HSX
MBIO Data Format ID:  201
Format name:          MBF_HYSWEEP1
Informal Description: HYSWEEP multibeam data format
Attributes:           Many multibeam sonars, 
                      bathymetry, amplitude
                      variable beams, ascii, HYPACK.
```

* RESON **.s7k** (this is raw backscatter data, bathymetry and attitudes are in an associated HSX file) 

[MBF_RESON7KR](https://nextcloud.epinux.com/index.php/s/zSUxUvuIzHRaV7D) 367.6 MB
```
Swath Data File:      170_003_2118.HSX.s7k
MBIO Data Format ID:  88
Format name:          MBF_RESON7KR
Informal Description: Reson 7K multibeam vendor format
Attributes:           Reson 7K series multibeam sonars, 
                      bathymetry, amplitude, three channels sidescan, and subbottom
                      up to 254 beams, variable pixels, binary, Reson.
```

* Hypack **HSX** file, bathymetry associated with backscatter from **s7k**

[MBF_HYSWEEP1 ](https://nextcloud.epinux.com/index.php/s/CrBEV7q9kVxjQMx) 169.1 MB
```
Swath Data File:      170_003_2118.HSX
MBIO Data Format ID:  201
Format name:          MBF_HYSWEEP1
Informal Description: HYSWEEP multibeam data format
Attributes:           Many multibeam sonars, 
                      bathymetry, amplitude
                      variable beams, ascii, HYPACK.
```

As you can see from the nature of the files (Bathymetry separated from Intensity. with different resolution) having the time associated with each beam/ping is essential for post-processing these data (usually the navigation is adjusted by comparing the attitude of the sonar with the set files from the GPS, in that case time is the only way to relate the two files) in the `.HSX` and in the `.all` files there are also extra information which are picked up by mbsystem ()e.g.: sonar offsetts (hsx), sound velocity profile (.all) .. )

Hope this can be useful!

**Comment by abellgithub** [comment]
Thanks for this. I hope to get to it shortly.

**Comment by epifanio** [comment]
The MBES Sonar system can send `pings` to the seafloor at a variable ping rate, up to `50Hz`,  which match the time resolution of the IMU unit (attitude records). Hence the need of preserving the microseconds resolution. Having `time_i` in the PADAL array will enable post-processing based on the IMU attitude records. Hope to make sense :)

**Comment by abellgithub** [comment]
Maybe I don't understand the use case.  Time in a resolution finer than seconds is no problem, but it would be nice to put the time in a form that's compact and useful for people doing analysis with other PDAL tools.  This generally means that they want GPS time (standard or week time).  I can convert time_i to one of these forms of GPS time, but I'm not sure that would do what you're asking.

Also, I modified the code to deal with the dimensions better depending on the `datatype` option. If you're building from source, you could check out this [branch](https://github.com/PDAL/PDAL/tree/mbio).

**Comment by epifanio** [comment]
@abellgithub , As long the time is stored in the PDAL data output any format will work for my use case. Actually, `standard GPS time` will work great as it is the same format used in the `.sbet` files generated by the IMU.

**Comment by abellgithub** [comment]
@epifanio, I committed a change that is an attempt to handle time.  It tried to put mb-system time in the same format as that usually in a LAS file.  (This is GPS standard time - 1E9, so if you want to get GPS standard time, add 1E9).  Is there any chance you can check out the branch and test?

**Comment by epifanio** [comment]
@abellgithub I'll rebuild, test and report. Thanks!

**Comment by epifanio** [comment]
@abellgithub, I rebuilt PDAL and now I was testing the data I shared for the test.

The file-format `MBF_EMOLDRAW` used for this issue (which is linked on the top page) works great!
 I can access the new GpsTime field.


Continuing the testing, I'm having problems in reading the other file-formats I posted a test.
I don't know if it is a problem with the files... The command  `mbinfo` detects the format but can't find any record in it. I need to test those files with another SW.


This [`HSX` file: 170_001_1942.hsx](https://nextcloud.epinux.com/index.php/s/xn8E6Ziy4EtR8xz), works fine with `mbinfo` :

 `mbinfo 170_001_1942.hsx` returns:
```
Swath Data File:      170_001_1942.hsx
MBIO Data Format ID:  201
Format name:          MBF_HYSWEEP1
Informal Description: HYSWEEP multibeam data format
Attributes:           Many multibeam sonars, 
                      bathymetry, amplitude
                      variable beams, ascii, HYPACK.

Data Totals:
Number of Records:                        5775
Bathymetry Data (512 beams):
  Number of Beams:          2956800
  Number of Good Beams:     2956800     100.00%
  Number of Zero Beams:           0      0.00%
  Number of Flagged Beams:        0      0.00%
Amplitude Data (512 beams):
  Number of Beams:          2956800
  Number of Good Beams:     2956800     100.00%
  Number of Zero Beams:           0      0.00%
  Number of Flagged Beams:        0      0.00%
Sidescan Data (1024 pixels):
  Number of Pixels:         5913600
  Number of Good Pixels:    5082059     85.94%
  Number of Zero Pixels:          0      0.00%
  Number of Flagged Pixels:  831541     14.06%

Navigation Totals:
Total Time:             0.3197 hours
Total Track Length:     3.3268 km
Average Speed:         10.4063 km/hr ( 5.6250 knots)

Start of Data:
Time:  06 19 2015 19:42:15.627000  JD170 (2015-06-19T19:42:15.627000)
Lon:  -176.931307218     Lat:    41.067903819     Depth:    76.2195 meters
Speed: 10.2898 km/hr ( 5.5621 knots)  Heading:  87.5100 degrees
Sonar Depth:    0.0700 m  Sonar Altitude:   76.1500 m

End of Data:
Time:  06 19 2015 20:01:26.500999  JD170 (2015-06-19T20:01:26.500999)
Lon:  -176.891856726     Lat:    41.065767073     Depth:    68.5425 meters
Speed: 10.1538 km/hr ( 5.4885 knots)  Heading:  69.7988 degrees
Sonar Depth:    0.0300 m  Sonar Altitude:   68.5599 m

Limits:
Minimum Longitude:    -176.931368063   Maximum Longitude:    -176.891470778
Minimum Latitude:       41.064805873   Maximum Latitude:       41.068982022
Minimum Sonar Depth:    -0.4300   Maximum Sonar Depth:     0.4800
Minimum Altitude:       64.7399   Maximum Altitude:      145.7400
Minimum Depth:          53.1573   Maximum Depth:         145.7200
Minimum Amplitude:       0.0000   Maximum Amplitude:   26627.0000
Minimum Sidescan:       33.0000   Maximum Sidescan:    23515.0000
```

* But `PDAL` hangs at the `p.execute()` command when trying to read it.  No logs are printed, I have to restart the notebook kernel to kill the process.


This is how I read the `HSX`:

```
json = u'''
    {
      "pipeline":[
        {
          "filename": "%s",
          "type":"readers.mbio",
          "format" : "%s"
        }
      ]
    }''' % ('170_001_1942.hsx', 'MBF_HYSWEEP1')
```

```
import pdal
p = pdal.Pipeline(json)
p.validate() 
p.loglevel = 8
count = p.execute()
```

**Comment by epifanio** [comment]
@abellgithub back. working on this, I see the `mbio` branch has been removed. Do you know if the changes have been merged into master? If yes, can you point me to the git commit? Testing some files I got no data point loaded where mb-system detected valid records, I was trying to debug the issue but I need a rebuild of PDAL on a new system. Thanks!

**Comment by epifanio** [comment]
@abellgithub I'm back on this, I modified the link to the test dataset (my server got hacked by cryptocurrency miner ... and I had to shut it down) I re-uploaded the same file on a new instance.

I rebuild PDAL  branch `issue-1852` and python PDAL from pip. I'm Using python `3.7` and `mbsystem-trunk.r2350`

I started the testing the notebook to read those datafile , I see the GPSTime is in the data array, cool! For a 1998 survey I have time values in the range of: `(59555498338.26, 59555502726.155)`
Can you please point me to a data time conversion so to print the UTC time? 
I was using the formula:
```
# utc = 1980-01-06UTC + (gps - (leap_count(2017) - leap_count(1980)))
```
but doesn't seem correct.

I'll continue the testing. Thanks for looking into this!

**Comment by epifanio** [comment]
@abellgithub did you removed/renamed the branch `issue-1852`. Trying to update `PDAL` I got:
```
epinux@Ubuntu-1804-bionic-64-minimal:~/dev/PDAL$ git pull
remote: Enumerating objects: 821, done.
remote: Counting objects: 100% (821/821), done.
remote: Compressing objects: 100% (45/45), done.
remote: Total 1353 (delta 791), reused 803 (delta 776), pack-reused 532
Receiving objects: 100% (1353/1353), 3.30 MiB | 8.26 MiB/s, done.
Resolving deltas: 100% (950/950), completed with 301 local objects.
From https://github.com/PDAL/PDAL
   07d19a48e..a8e86bddc  1.7-maintenance             -> origin/1.7-maintenance
 * [new branch]          1.8-maintenance             -> origin/1.8-maintenance
 * [new branch]          dont-escape-forward-slashes -> origin/dont-escape-forward-slashes
 * [new branch]          info-pipeline-output        -> origin/info-pipeline-output
 * [new branch]          issue-1983                  -> origin/issue-1983
 * [new branch]          issue-2230                  -> origin/issue-2230
 * [new branch]          issue-2292                  -> origin/issue-2292
 * [new branch]          license-cleanup             -> origin/license-cleanup
   cafff53a1..29e457fb3  master                      -> origin/master
 * [new branch]          more-eigen-cleanup          -> origin/more-eigen-cleanup
 * [new branch]          osgeo4w-proj4dll            -> origin/osgeo4w-proj4dll
 * [new branch]          project-referencing         -> origin/project-referencing
 * [new branch]          reprojection-override       -> origin/reprojection-override
 * [new branch]          version-setting-1.8         -> origin/version-setting-1.8
 * [new branch]          windows-shut-the-hell-up    -> origin/windows-shut-the-hell-up
 * [new tag]             1.8.0                       -> 1.8.0
 * [new tag]             1.8rc1                      -> 1.8rc1
 * [new tag]             1.8rc2                      -> 1.8rc2
Your configuration specifies to merge with the ref 'refs/heads/issue-1852'
from the remote, but no such ref was fetched.
```

**Comment by abellgithub** [comment]
No idea.  Do the branches go stale?

I just pushed a local copy.

**Comment by pdal-docs** [comment]
I may have deleted the remote branch. It should be restoreable.

**Comment by epifanio** [comment]
@abellgithub 
I'm back on this, can you please point me to a conversion to `UTC` from the `GpsTime` used in the `mbio reader`
> This is for a 1998 survey I have time values in the range between:
> `(59555498338.26, 59555502726.155)`
> Can you please point me to a data time conversion rule, so to print out the UTC time?

**Comment by abellgithub** [comment]
Not sure what you're asking.  Here's the relevant code:

https://github.com/PDAL/PDAL/blob/master/plugins/mbio/io/MbReader.cpp#L169-L220

**Comment by epifanio** [comment]
@abellgithub Thanks for pointing me to the relevant part of the code. What I'm asking (due to my ignorance) is how to convert from `adjusted GPS standard time` to `Universal Time`.  I'm now trying to reverse eng the code you linked ... but I guess I should look more in a formula/function to do it correctly.

**Comment by hobu** [comment]
> What I'm asking (due to my ignorance) is how to convert from adjusted GPS standard time to Universal Time. I'm now trying to reverse eng the code you linked ... but I guess I should look more in a formula/function to do it correctly... but can't find one.

https://pdal.io/stages/filters.gpstimeconvert.html is now available to do this task.
