### ISSUE TITLE
Add "triangulate" or "delaunay" filter

### ISSUE THREAD

**Issue by plimkilde** [PDAL/PDAL#1855]
It would be nice to have a filter that provides Delaunay triangulation. Note that for 2.5D applications such as DEM generation, it is relevant to provide 2D triangulation.

One possible backend could be Geogram (http://alice.loria.fr/software/geogram/doc/html/index.html), which provides both 2D and 3D Delaunay triangulation.

**Comment by hobu** [comment]
Should we have a `filters.triangulate` super-filter that would encompass the functionality of `filters.greedyprojection` and `filters.poisson` (and any other triangulation methods)? Should we add a new class type (`triangulate.alice`, `triangulate.greedyprojection`, `triangulate.poisson`)? I'm not sure how to proceed. I agree as they are now kind of buries them and makes it hard to know what they do.

**Comment by abellgithub** [comment]
Merging the filters would make options confusing, I think.

**Comment by plimkilde** [comment]
I now have a working implementation of a filter for Delaunay triangulation (2D only at the moment). It's in the "delaunay" branch in my personal fork and relies on the Geogram Delaunay PSM.
