### ISSUE TITLE
Failed to find match ... when using merge on PCD files

### ISSUE THREAD

**Issue by jgrn307** [PDAL/PDAL#1856]
I'm trying to merge a large number of PCD files into an output PCD file with pdal merge, but I'm getting these errors repeatedly:

Failed to find match for field 'intensity'.
Failed to find match for field 'rgba'.

Any ideas?

**Comment by abellgithub** [comment]
Do you have a small file or two that fails?  This is a type issue with trying to map dimensions to a PCL point could that isn't appropriately typed.

**Comment by abellgithub** [comment]
This error comes from PCL.  It is indicating that you're reading data that has no color or intensity information.  The point cloud will always be created with rgb/intensity information, set to 0.  If you don't want to write the "extra" information on output, you can use the --writers.pcd.xyz=true option.

**Comment by abellgithub** [comment]
@jgrn307 OK to close?
