### ISSUE TITLE
Filter categories

### ISSUE THREAD

**Issue by chambbj** [PDAL/PDAL#1859]
This may be more of an assignment for updating our documentation, but it seems that we often come around to the question of how to "bin" our various filters into categories, such that they are easier to locate and for users to have at least a clue as to what they may do to the data. (Note, that this could also help other areas, e.g., determining when we do or do not need to rebuild a KDIndex, and to that end there _may_ be some utility in truly treating them specially, beyond simple documentation updates.)

Several months ago, I used the following list of "categories" in a presentation.

- Create/alter dimensions other than XYZ
  - ApproximateCoplanar
  - Assign
  - Cluster
  - ColorInterp
  - Colorization
  - ComputeRange
  - Eigenvalues
  - EstimateRank
  - ELM
  - Ferry
  - HAG
  - KDistance
  - LOF
  - Mongus
  - Normal
  - Outlier
  - Overlay
  - PMF
  - RadialDensity
  - SMRF
- Change point order
  - MortonOrder
  - Randomize
  - Sort
- Move points
  - Reprojection
  - Transformation
- Cull points
  - Crop
  - Decimation
  - Divider
  - Head
  - IQR
  - Locate
  - MAD
  - Range
  - Sample
  - Tail
  - VoxelCenterNearestNeighbor
  - VoxelCentroidNearestNeighbor
- Create new PointViews
  - Chipper
  - Divider
  - Groupby
  - Splitter
- Join PointViews
  - Merge
- Create metadata
  - CPD
  - HexBin
  - ICP
  - Stats
- Create meshes
  - GreedyProjection
  - GridProtection
  - MovingLeastSquares
  - Poisson
- Embed other languages
  - Matlab
  - Python

I guess the questions to everybody are, how best to we capture these categories? Is this needed? Are these categories sufficient, or are some missing? Is documentation enough or do we need to make an actual distinction between filter "types" (post v1.7)?

**Comment by tomvantilburg** [comment]
What I would love to see in the current documentation is just 1 line of description with every filter-name. Too often I can't remember a certain filter that I don't use regularly, especially with abbreviations and when your are a non-native in English. Tags would also greatly help.

**Comment by chambbj** [comment]
Closed via #1880. If we feel we need more than documentation, it can be ticketed separately.
