### ISSUE TITLE
Don't use decimal precision for integers in text writer

### ISSUE THREAD

**Issue by tomvantilburg** [PDAL/PDAL#1869]
Currently all dimensions are written with the same precision (defaulting to 3) but this seems unneeded for integers and gives unexpected errors when trying to import the data into other programs (postgres in my case).

Current output:
`Intensity,ReturnNumber,NumberOfReturns,ScanDirectionFlag,EdgeOfFlightLine,Classification,ScanAngleRank,UserData,PointSourceId,GpsTime,X,Y,Z

60.000,1.000,1.000,0.000,0.000,9.000,8.000,1.000,210.000,78563061.316,139067.845,556254.579,-1.049`

Expected output:
`60,1,1,0,0,9,8.000,1,210, 78563061.316, 139067.845, 556254.579, -1.049`

**Comment by abellgithub** [comment]
Frankly, this seems like a postgres problem.

I'll have to think about some reasonable way to handle this.
