### ISSUE TITLE
PDAL in Docker don't read LAZ 

### ISSUE THREAD

**Issue by winsento** [PDAL/PDAL#1871]
I try to test PDAL in docker (info, eprojection) and when run  `pdal info` I get nothing as a result.

```bash
docker run -v /data:/data pdal/pdal:1.6 pdal info /data/point.laz
```
When run  `pdal translate` get `Killed` as a result.
```bash
docker run -v /data:/data pdal/pdal:1.6 pdal translate /data/point.laz /data/point_3857.laz filters.reprojection  --filters.reprojection.out_srs=EPSG:3857
Killed
```

**Comment by connormanning** [comment]
You are running out of memory - how much memory does your docker VM have available?  Can you try increasing it?

**Comment by winsento** [comment]
@connormanning point.laz -600Mb, Docker machine - 2Gb mem,  4CPU.

Tell me how RAM need to reproject 70Gb LAZ.

**Comment by abellgithub** [comment]
You can use stream mode if you create a pipeline.  Then use `pdal pipeline --stream pipeline.json`.  Your pipeline.json should look something like:

```
{
  "pipeline" : [
     "data/point.laz",
    {
        "type" : "filters.reprojection",
        "out_srs": "EPSG:3857"
    },
    "/data/point_3857.laz"
  ]
}
```

Hope that helps,

**Comment by winsento** [comment]
@abellgithub thank you, i will try. Correctly I understand that the stream mode (via pipeline) not processed all points data at once, but in parts? Thus reducing the amount of occupied RAM.

**Comment by winsento** [comment]
@abellgithub I confirm. With pipeline and `--stream` all ok. Tickets can be close.
