### ISSUE TITLE
PDAL always runs in standard mode in Windows or VStudio

### ISSUE THREAD

**Issue by ahuarte47** [PDAL/PDAL#1874]
I have tested PDAL from OSGeo4W for Windows10 (x64), and I built it with VS2017 too. Both of them **always** run in standard mode even for streamable methods like _Translate_.

[PipelineManager::executeStream](https://github.com/PDAL/PDAL/blob/master/pdal/PipelineManager.cpp#L218) should calls to [Streamable::execute](https://github.com/PDAL/PDAL/blob/master/pdal/Streamable.cpp#L56) instead of [Stage::execute](https://github.com/PDAL/PDAL/blob/master/pdal/Stage.cpp#L156) method.

I have got fine execution adding this:

```
void PipelineManager::executeStream(FixedPointTable& table)
{
    validateStageOptions();
    Stage *s = getStage();
    if (!s)
        return;

    s->prepare(table);

+   if (Streamable * p = dynamic_cast<Streamable *>(s))
+   {
+      p->execute(table);
+      return;
+   }
    s->execute(table);
}
```

Edit:
Or maybe better...

```
void PipelineManager::executeStream(FixedPointTable& table)
{
    validateStageOptions();
+   Streamable *s = dynamic_cast<Streamable *>(getStage());
    if (!s)
        return;

    s->prepare(table);
    s->execute(table);
}

```

**Comment by abellgithub** [comment]
Thanks so much for catching this.

I'm wondering about the best solution. I could push execute(StreamPointTable&) into the Stage class  as virtual and have it throw or assert.  The idea when I created the Streamable interface was to have things work no matter what, but perhaps it's less clear what's going to happen this way -- whether you're going to use streaming mode or not (I obviously missed changing the function you reference when I changed the interface, which is perhaps a hint). Hmmm.

**Comment by abellgithub** [comment]
I decided that it was safer to throw an exception if someone tried to use a StreamPointTable in non-streaming mode and make sure that execute() is invoked in streaming mode if you do use a StreamPointTable.  This exposed a couple of other issues that are also fixed in the branch:

https://github.com/PDAL/PDAL/compare/streamfix

If there are no complaints after a bit, I'll merge that change.

**Comment by ahuarte47** [comment]
Thanks Andrew!
