### ISSUE TITLE
Batch processing - dynamic input/output filename

### ISSUE THREAD

**Issue by bildsoe** [PDAL/PDAL#1893]
Hi,

Is it possible to call the pipeline tool with an input and output argument? 

What I would like to be able to do is something like this:

```
filter.json
{
  "pipeline":[
    {
      "type":"readers.las",
      "filename": $1
    },
    {
      "type":"filters.range",
      "limits":"Classification[2:2]"
      },
    {
      "type":"writers.ply",
      "filename": $2,
      "faces": false
    }
  ]
}
```

and then calling it like this, replacing $1 and $2 respectively:

`pdal pipeline filter.json input.las output.ply`

BR
Thomas

**Comment by chambbj** [comment]
This type of "How do I..." question is really good for the PDAL [mailing list](http://lists.osgeo.org/mailman/listinfo/pdal).

You have a couple of options. Using your original pipeline (minus the reader/writer `filename`)

```
{
    "pipeline":[
        {
            "type":"readers.las"
        },
        {
            "type":"filters.range",
            "limits":"Classification[2:2]"
        },
        {
            "type":"writers.ply",
            "faces": false
        }
    ]
}
```

you can inject the filenames from the command line thusly

```
pdal pipeline filter.json --readers.las.filename=input.las --writers.ply.filename=output.ply
```

Or you can create a filter-only pipeline

```
{
    "pipeline":[
        {
            "type":"filters.range",
            "limits":"Classification[2:2]"
        }
    ]
}
```

and call it like this

```
pdal translate input.las output.ply --json=filter-only.json --writers.ply.faces=false
```
