### ISSUE TITLE
Backtrace not available within Alpine containers

### ISSUE THREAD

**Issue by connormanning** [PDAL/PDAL#1904]
To reproduce, start in a directory containing the file [bt.cpp](https://gist.github.com/connormanning/96435f04e19caf1527b75ce397110c73).

```
docker run -it -v `pwd`:/opt/home pdal/pdal:master sh
apk update && apk add alpine-sdk
cd /opt/home
g++ -std=c++11 bt.cpp -l pdalcpp -o bt
./bt
No backtrace!
```

Running natively or within a Ubuntu container, output is:
```
./bt
Backtrace:
1   bt             main + 33
2   libdyld.dylib  start + 1
3   ???            0x0000000000000001 0x0 + 1
```

We could use [libunwind](https://www.nongnu.org/libunwind/) for backtrace functionality on alpine.  See [sample code](https://eli.thegreenplace.net/2015/programmatic-access-to-the-call-stack-in-c/).

**Comment by chambbj** [comment]
As originally noted in #1862, Alpine may be able to provide backtrace-like functionality with libunwind.

https://pkgs.alpinelinux.org/package/edge/main/x86_64/libunwind
https://pkgs.alpinelinux.org/package/edge/community/x86_64/llvm-libunwind
