### ISSUE TITLE
Installing on Mac OS

### ISSUE THREAD

**Issue by berkayoruc** [PDAL/PDAL#1912]
Hey im new about this topic and an geomatics engineering student at ITU(Turkey). I installed pdal with brew on my OS. But i cant find setup.py . Where can i find it?

**Comment by chambbj** [comment]
See this recent announcement.

https://lists.osgeo.org/pipermail/pdal/2018-April/001501.html

The python package has been relocated to it's own repository.

**Comment by berkayoruc** [comment]
Thank you
