### ISSUE TITLE
PDAL 1.7 plugins with underscores in name

### ISSUE THREAD

**Issue by jw3** [PDAL/PDAL#1923]
We have plugins that have underscores in their names, eg. a filter named `foo_bar_baz`, its shared lib is `libpdal_plugin_filter_foo_bar_baz.so`.

When upgrading to 1.7 a library name in this format does not appear to be detected.  A quick look shows maybe [this block in PluginDirectory](https://github.com/PDAL/PDAL/blob/c9a06fd42f48782e505071043ab4ac95c176edf2/pdal/PluginDirectory.cpp#L92-L96) is limiting it.

[This change](https://github.com/jw3/PDAL/commit/29ac2227f98853e1bf270abf266857a5acb611a8) might be a quick "fix" for it.  Are there any other concerns within the plugin system after changing the behavior of `PluginDirectory`?

**Comment by abellgithub** [comment]
If prior to version 1.7 PDAL loaded plugins with underscores in their names, that was an oversight.  Stage names are limited to lowercase characters and digits and must start with a lowercase character.  The pipeline parser currently depends on this.  Changing the behavior would require more code to change than proposed and careful testing to follow-up.  We're planning on taking this up next week when developers meet in person.

**Comment by jw3** [comment]
>that was an oversight

I feared that "oversight" would be part of the response, and can appreciate the dilemma this has caused.

>We're planning on taking this up next week when developers meet in person.

Standing by with ~30 unfortunately named plugins, eagerly awaiting feedback.  :)

**Comment by hobu** [comment]
Would allowing `-`'s in stage names be acceptable? This would give @jw3 whitespace and very long names, and it wouldn't be reserved for filenames.

**Comment by abellgithub** [comment]
We use '-' in detecting option names. Parsing may be impacted. It would take some work to determine the impact of that change.

**Comment by jw3** [comment]
>We're planning on taking this up next week when developers meet in person.

Was a resolution to this issue determined?

**Comment by jw3** [comment]
>Stage names are limited to lowercase characters and digits and must start with a lowercase character.

Didn't catch the lowercase bit earlier, was focused on the underscores.

Have now verified that this was implemented correctly. :/

**Comment by jw3** [comment]
Perhaps this is now a closer reference implementation, https://github.com/jw3/PDAL/commits/underscored_plugins

At this time Ive only tested with the pipeline kernel, successfully running pipelines with plugin names like
- `filters.myplugin`
- `filters.my_plugin`
- `filters.My_Plugin`
- `filters.My_Plugin_is_Working`
- `filters.My_Plugin_is_Working_1_2_3_4_5`

The head commit there doesnt seem to be needed for the pipelines, I suspect it is for cli usage... looks like it needed updated to match the changed format anyways, so I did.

The `validPlugin` function could have some test coverage added pretty easily but Im not sure what the best way is to get at it from a unit test.

**Comment by abellgithub** [comment]
I see no reason to accommodate mixed-case stage names.  Allowing mixed-case
makes it more confusing for users as they need to remember the specific
case logic used by a developer (did they use camel case? Underscores?). It
seems harmless to expect developers to conform to a simple rule that eases
use for end-users.

**Comment by jw3** [comment]
>It seems harmless to expect developers to conform to a simple rule that eases use for end-users.

Which approach actually eases things for an end user likely depends on the plugins being developed.  I used a poor examples above, here Ill try again

`projecta_vendor1_intensityseparationwithtreeweights`
vs
`projecta_vendor1_IntensitySeparationWithTreeWeights`

**Comment by jw3** [comment]
> I see no reason to accommodate mixed-case stage names.

Looks like you currently have varying levels of mixed-case support. 

> The head commit there doesnt seem to be needed for the pipelines

My branch works with mixed case pipelines, without the head commit on that branch which was the only place I messed with case.

So perhaps pipelines dont share the logic that back up this statement:  "Stage names are limited to lowercase characters and digits and must start with a lowercase character."

> Have now verified that this was implemented correctly. :/

This was wrong, I conflated some results with another part of this API that changed behavior in 1.7.

**Comment by hobu** [comment]
@jw3 , is support of plugin/stage names like `libpdal_plugin_stagetype_projecta_vendor1_intensity_separation_with_tree_weights` satisfactory? That is, allow underscores after the `libpdal_plugin_stagetype_` prefix and disallow mixed-case. 

> Allowing mixed-case makes it more confusing for users as they need to remember the specific case logic used by a developer (did they use camel case? Underscores?).

True, but these names are so long that it probably doesn't matter. No user is going to be writing CLI with 70 character stage names by hand anyway. Most groups writing stages want single, short names for stages. We just as easily have the other problem for many of our stages -- the names are so short as to be confusing about what they do.

**Comment by jw3** [comment]
> allow underscores after the libpdal_plugin_stagetype_ prefix and disallow mixed-case.

Well yesterday before discovering the above notes regarding case handling I would have answered yes to that question... now I wish I hadn't brought up case at all :grinning: 

We are pretty close to not having to rename any of 30 plugins, pipelines, and documentation affected by the 1.7 changes.  It doesn't seem like uppercase has been a problem to this point, there doesn't appear to be technical limitations,  it just sounds like the discussion point is what is confusing or not for end users.

Question:  Is PDAL a toolkit/framework to develop applications, or is it an application that has an API?

**Comment by hobu** [comment]
> Question: Is PDAL a toolkit/framework to develop applications, or is it an application that has an API?

I would say it has grown up as the latter -- we use `pdal pipeline` to drive data processing workflows, but as it has matured the pendulum has been swinging toward the former.  No doubt there's some more teething to endure as that happens. You're the first group we know of to make 30 plugins. Our typical interaction is around one or two plugins, and often times we were the proprietors of them because of licensing issues ([PRC](https://github.com/PDAL/PRC) is one of those for example).

**Comment by hobu** [comment]
> OK. I am just trying to understand which side of the equation drives decisions.

For the most part, *we* have been our only API consumers, so the consequence for any changes has been limited to effects on us. That's obviously changing as more API users start picking PDAL up, but most of our bug reports and traffic is about application uses, not API consumers. That could either mean the API is so convenient to use that no one needs to ask questions (doubtful), or we haven't had many direct outside API users (more likely).

> Question: What is the intent of the --drivers and --options flags?

To allow the user, or anyone helping to debug a user, to list the active stages (after plugin detection), their options, and some light docs. The stage creation asks for a URL for populating this output too. An application developer can also combine them with the hidden `--showjson` option, which will emit the active stage tree and options as JSON (along with option defaults). The thought was they might use the structured output to populate a GUI with them in some generic way, although that might be fraught.
