### ISSUE TITLE
Version the docs

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#1927]
Users of older versions of PDAL still need access to docs corresponding to the version they're using. The typical Sphinx document versioning scenario has the unfortunate side effect of screwing up the google juice for commonly searched things. You often end up looking at a version of the docs that you didn't expect or is the wrong one for you.

I propose that we use the PDF snapshots tied to specific versions and point to them on a separate web page in the website for "previous versions". That way they won't suck up all of the google juice and people can still get back to something that was relevant to their version.

**Comment by chambbj** [comment]
Don't know enough about how they do it, but CMake and Python both are Sphinx powered with version dropdowns. Also, Read The Docs may be a handy way to version (and offer latest, yet to be released versions of the docs).

**Comment by kbevers** [comment]
> Don't know enough about how they do it, but CMake and Python both are Sphinx powered with version dropdowns

[this](https://robpol86.github.io/sphinxcontrib-versioning/) seems to offer a solution for that.

**Comment by kbevers** [comment]
> Both CMake and Python are my counter examples. When I google for items, I never get current-version results, I get highest-pagerank stuff.

I think you should be able to avoid that by adding a [robots.txt](http://www.robotstxt.org/robotstxt.html) that hide old versions from search engines.

**Comment by msmitherdc** [comment]
Agree, read the docs would be nice (or similar)

**Comment by hobu** [comment]
>  Also, Read The Docs may be a handy way to version

Multi-version docs end up competing for attention with themselves. Sphinx has a directive to allow you to mark specific items with specific versions, which is a nice habit, but it doesn't require a full, parallel-universe copy of the old version of the docs to be alongside what's currently being viewed. I like this solution much better than easy-to-miss switchable versions hidden in a dropdown. 

`robots.txt` is easy to forget to update as part of an update process. I don't know if I like that solution either, because it begs the question whether the canonical location of a document should be 

* [https://www.pdal.io/stages/writers.las.html](https://www.pdal.io/stages/writers.las.html )

or 

* [https://www.pdal.io/1.8/stages/writers.las.html](https://www.pdal.io/1.8/stages/writers.las.html )
 
PDAL's utilities point to canonical locations when printing command-line help, and we ask for a document URL as part of the stage creation machinery to be able to specifically provide a canonical URL. If we version the docs, would we version those too? It just all seems too messy to me.

**Comment by kbevers** [comment]
> Multi-version docs end up competing for attention with themselves. Sphinx has a directive to allow you to mark specific items with specific versions, which is a nice habit, but it doesn't require a full, parallel-universe copy of the old version of the docs to be alongside what's currently being viewed. I like this solution much better than easy-to-miss switchable versions hidden in a dropdown.

I assume you talk about the `:versionadded:`, `:versionchanged:` and `:versiondeprecated:` directives. As long as you only add things I agree with you, this is a neat and simple way of handling the docs. But let's say you have a filter introduced in version 1.5, that you change slightly in 1.6, maybe again in 1.7 and finally in 2.0 it is deprecated. That would generate some rather noisy docs which has the potential to be as confusing for the user as selecting the specific version in a dropdown. This is of course an extreme example but for a project that probably will live for a long time this can easily happen.

> PDAL's utilities point to canonical locations when printing command-line help, and we ask for a document URL as part of the stage creation machinery to be able to specifically provide a canonical URL. If we version the docs, would we version those too? It just all seems too messy to me.

I would try to make a setup with the current version at https://www.pdal.io/stages/writers.las.html and older version at https://www.pdal.io/v/1.8/stages/writers.las.html. A generic exclusion of https://www.pdal.io/v/* would hide older versions for search engines. This way you wouldn't have the need to update `robots.txt` unless the entire doc setup is changed.

**Comment by msmitherdc** [comment]
Old PDFs are pretty terrible by themselves. Having the version right on the page ala the Django docs (or many others) are much more preferable IMHO.

**Comment by hobu** [comment]
Closing for now. If someone wants to build up this infrastructure, they can reopen and push a branch that implements.
