### ISSUE TITLE
PDAL-java <= 1.6.0: with apt-get jni binary is missing

### ISSUE THREAD

**Issue by romulogoncalves** [PDAL/PDAL#1935]
Hi, 

I am using Ubuntu and I have installed pdal using:
apt-get install pdal

The following was installed:
romulo:emma$ dpkg -l | grep pdal
ii  libpdal-base5                         1.6.0-1 xenial1
ii  libpdal-plugin-greyhound              1.6.0-1 xenial1
ii  libpdal-plugin-icebridge              1.6.0-1 xenial1
ii  libpdal-plugin-pgpointcloud           1.6.0-1 xenial1
ii  libpdal-plugin-python                 1.6.0-1 xenial1
ii  libpdal-plugin-sqlite                 1.6.0-1 xenial1
ii  libpdal-plugins                       1.6.0-1 xenial1
ii  libpdal-util5                         1.6.0-1 xenial1
ii  pdal                                  1.6.0-1 xenial1

Then I got the jar files:

<dependency>
    <groupId>io.pdal</groupId>
    <artifactId>pdal_2.11</artifactId>
    <version>1.6.0</version>
</dependency>

When I try to read a LAS file I am getting:
Message: Native library libpdaljni.1.4.so (/native/x86_64-linux/libpdaljni.1.4.so) cannot be found on the classpath.

Should that have be solved by the package installation apt-get install pdal?
Or is still required to install PDAL from sources?

If I am missing some step, please let me know.

**Comment by hobu** [comment]
This issue might need to move over to https://github.com/PDAL/java
