### ISSUE TITLE
version 1.7.1: Compilation fails on Ubuntu 16.4, dynamic linkage issue

### ISSUE THREAD

**Issue by romulogoncalves** [PDAL/PDAL#1937]
The compilation fails with following:
[ 60%] Linking CXX executable ../../../bin/pdal_io_numpy_test
/usr/bin/ld: CMakeFiles/pdal_io_numpy_test.dir/__/plang/Environment.cpp.o: undefined reference to symbol 'dlopen@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
plugins/python/io/CMakeFiles/pdal_io_numpy_test.dir/build.make:161: recipe for target 'bin/pdal_io_numpy_test' failed
make[2]: *** [bin/pdal_io_numpy_test] Error 1
CMakeFiles/Makefile2:1191: recipe for target 'plugins/python/io/CMakeFiles/pdal_io_numpy_test.dir/all' failed
make[1]: *** [plugins/python/io/CMakeFiles/pdal_io_numpy_test.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

The configuration should handle such situation. The makefiles were generated with the following options:

cmake ../ -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_MAKE_PROGRAM=make -DBUILD_PLUGIN_PYTHON=ON -DBUILD_PLUGIN_CPD=ON -DBUILD_PLUGIN_GREYHOUND=ON -DBUILD_PLUGIN_HEXBIN=ON -DBUILD_PLUGIN_NITF=ON -DBUILD_PLUGIN_ICEBRIDGE=ON -DBUILD_PLUGIN_PGPOINTCLOUD=ON -DBUILD_PLUGIN_SQLITE=ON -DWITH_LASZIP=ON -DWITH_LAZPERF=ON -DBUILD_PLUGIN_DELAUNAY=ON

-- The CXX compiler identification is GNU 5.4.0
-- The C compiler identification is GNU 5.4.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found GDAL: /usr/lib/libgdal.so (Required is at least version "1.9.0")
-- Found GeoTIFF: /usr/lib/x86_64-linux-gnu/libgeotiff.so
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8")
-- Found JSONCPP: /usr/lib/x86_64-linux-gnu/libjsoncpp.so (Required is at least version "1.6.2")
-- Found LibXml2: /usr/lib/x86_64-linux-gnu/libxml2.so (found version "2.9.3")
-- Found CURL: /usr/lib/x86_64-linux-gnu/libcurl.so (found version "7.47.0")
-- Found Hexer: /usr/local/lib/libhexer.so
-- Found HDF5: /usr/lib/x86_64-linux-gnu/hdf5/serial/lib/libhdf5_cpp.so;/usr/lib/x86_64-linux-gnu/hdf5/serial/lib/libhdf5.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libsz.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libm.so (found version "1.8.16")
-- Found PostgreSQL: /usr/include/postgresql
-- Numpy output: /usr/lib/python2.7/dist-packages/numpy/core/include
1.11.0

-- Performing Test SQLITE3_HAS_LOAD_EXTENSION
-- Performing Test SQLITE3_HAS_LOAD_EXTENSION - Success
-- Found SQLITE3: /usr/lib/x86_64-linux-gnu/libsqlite3.so
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1")
-- Checking for one of the modules 'spatialite>=4.2.0'
-- Found PythonInterp: /usr/bin/python (found version "2.7.12")
--
-- The following features have been enabled:

 * CPD plugin , Coherent Point Drift (CPD) computes rigid or nonrigid transformations between point sets
 * Greyhound plugin , read points from a Greyhound server
 * Hexbin plugin , determine boundary and density of a point cloud
 * Icebridge plugin , read data in the Icebridge format
 * NITF plugin , read/write LAS data wrapped in NITF
 * PostgreSQL PointCloud plugin , read/write PostgreSQL PointCloud objects
 * SQLite plugin , read/write SQLite objects
 * Python plugin , add features that depend on python
 * Unit tests , PDAL unit tests

-- The following OPTIONAL packages have been found:

 * Lazperf
 * JSONCPP (required version >= 1.6.2)
 * PkgConfig
 * LibXml2
 * Curl

-- The following RECOMMENDED packages have been found:

 * LASzip (required version >= 3.1)
   Provides LASzip compression
   Provides LASzip compression

-- The following REQUIRED packages have been found:

 * GDAL (required version >= 1.9.0)
   Provides general purpose raster, vector, and reference system support
 * GEOS (required version >= 3.3)
   Provides general purpose geometry support
 * GeoTIFF
 * ZLIB
   Compression support in BPF
 * Cpd (required version >= 0.5)
 * Hexer
 * HDF5
 * Nitro (required version >= 2.6)
 * PostgreSQL
 * PythonLibs
 * NumPy (required version >= 1.5)
 * SQLite3
 * PythonInterp
 * Threads , The thread library of the system

-- The following features have been disabled:

 * Bash completion , completion for PDAL command line
 * GeoWave plugin , Read and Write data using GeoWave
 * Matlab plugin , write data to a .mat file
 * MrSID plugin , read data in the MrSID format
 * OpenSceneGraph plugin , read/write OpenSceneGraph objects
 * PCL plugin , provides PCL-based readers, writers, filters, and kernels
 * RiVLib plugin , read data in the RXP format
 * MBIO plugin , add features that depend on MBIO

-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    BUILD_PLUGIN_DELAUNAY

-- Build files have been written to: /data/local/jupyterhub/modules/pdal/pdal_1_7_1/makefiles

**Comment by hobu** [comment]
Can you please try the `1.7-maintenance` branch. I believe there the fix for this is #1900 which may not have been merged into the 1.7.1 release.

**Comment by romulogoncalves** [comment]
For 1.7-maintenance it works.

**Comment by hobu** [comment]
Ok. Marking this issue closed. 1.7.2 should be released in May.
