### ISSUE TITLE
Globbing of s3 input data files not working

### ISSUE THREAD

**Issue by wakruse** [PDAL/PDAL#1938]
I’m unable to glob the source las files on s3 needed by PDAL tindex application in the pdal:1.7 docker container from an ec2 instance. I got a similar result when testing the use of globbing in a json pipeline description described in issue #1792, also using docker. Globbing worked with input from the local ec2 filesystem and when requesting a single file from s3. When globbing for multiple files on s3 I got the following error:

PDAL: Unable to open stream for 's3://bucketname/path/input_00000*.las' with error 'No such file or directory'

Docker command line:
docker run --rm -v /home/ec2-user/.aws:/root/.aws -v /home/ec2-user/metadata/pdal_trans/:/out pdal/pdal:1.7 pdal pipeline /out/pdal_glob_tst.json --writers.las.filename=/out/outs3.laz

Single file json works:
{
  "pipeline": [
    {"type":"readers.las","filename":"s3://bucketname/path/input_000001.las"},
    {"type":"writers.las"}  
  ]
}

Glob file json doesn’t work:
{
  "pipeline": [
    {"type":"readers.las","filename":"s3://bucketname/path/input_00000*.las"},
    {"type":"writers.las"}  
  ]
}

Globbing works as expected for entwine build using s3 so it appears that arbiter is working.

**Comment by hobu** [comment]
The reason it doesn't work is arbiter's globbing is not plugged into PDAL's for this kind of pipeline operation. We can merge a patch on it if you can construct one.

**Comment by connormanning** [comment]
Currently arbiter only globs things where the path ends with `*` (or `**` for a recursive search) - so `*.las` isn't implemented.  It could potentially be added.

**Comment by wakruse** [comment]
Thanks for the quick reply.  I'll need to work around this for the moment. My understanding of the underlying codebase is insufficient to effectively suggest a patch at this time.
