### ISSUE TITLE
PDAL 1.7.0 fails to build with undefined reference to symbol 'dlopen@@GLIBC_2.2.5'

### ISSUE THREAD

**Issue by neteler** [PDAL/PDAL#1945]
Trying to build PDAL 1.7.0 on Fedora's COPR platform fails with

```
/usr/bin/ld: CMakeFiles/pdal_io_numpy_test.dir/__/plang/Environment.cpp.o: undefined reference to symbol 'dlopen@@GLIBC_2.2.5'
```

... see at the end of:
https://copr-be.cloud.fedoraproject.org/results/neteler/pdal/fedora-27-x86_64/00743512-PDAL/build.log.gz

Searching around I see that similar problems were fixed by adding -ldl but I thought to better report it here first. Happy to test changes!

**Comment by hobu** [comment]
Yes, it is fixed on the `1.7-maintenance` branch and available in #1900. I goofed up on the release. It will be fixed in the 1.7.2 release which we expect in mid-May.
