### ISSUE TITLE
PDAL: readers.pgpointcloud: Unable to fetch pcid with column 'pa' and  table 'pcpatches'

### ISSUE THREAD

**Issue by jfjffilk** [PDAL/PDAL#1955]
when i am trying to run pipeline json file to write the patches to PostgreSQL database, i get this from readers.pgpointcloud Unable to fetch pcid with column 'pa' and  table 'pcpatches'. 
if anyone could help me out that would be great. thank you
ps: I am a student and very new PDAL

**Comment by abellgithub** [comment]
Usually this is caused by a mismatch between your schema and the one that PDAL is trying to use.  For the time being I'd suggest letting PDAL create the table/schema for you, rather than pre-create one.

**Comment by jfjffilk** [comment]
i had let PDAL only create the schema. but when i try to read it 
throws the same error

**Comment by abellgithub** [comment]
Without knowing exactly what you have tried and the exact problem, I don't think we can help.
