### ISSUE TITLE
Add points using filters.python

### ISSUE THREAD

**Issue by clucas111** [PDAL/PDAL#1965]
The point cloud we are working with regularly has holes on the roofs of houses, which is a consequence of puddles of water at the time of scanning. These holes in the data result in a reduced performance of our algorithm. To fix this we want to add synthetic points at these locations. Since puddles of water only appear on flat surfaces we can fill these holes with points at the same height as the surrounding points.

I made an algorithm in python that finds the holes in the data and fills them with these synthetic points. Now I want to add this python script in a PDAL pipeline, but I have found no way of adding these points to the point cloud, to be used in subsequent steps in a PDAL pipeline. If I set the 'outs' 'X', 'Y' and 'Z' parameters to equal the arrays of the x, y and z of the points with the synthetic points included:

outs['X'] = points_filled[:, 0]
outs['Y'] = points_filled[:, 1]
outs['Z'] = points_filled[:, 2]

and subsequently run the PDAL pipeline and save it to a file it will only write the original points. Is there a way for me to add these points?

**Comment by hobu** [comment]
This is not possible today, but it would be possible to implement. `filters.python` pre-dates the PointView concept in PDAL, and that is why it uses its special `Mask` dimension. `filters.python` could also be made to add or remove points from its PointView(s), but modifying the schema of the data in-place would never be allowed. 

The approach would require some special consideration of PointId for points, but that limitation shouldn't be too restrictive.

**Comment by hobu** [comment]
Added for 1.8 in f1b695b874a8c3dc43e1a061ecb96089d282acef
