### ISSUE TITLE
Docker scripts and 1.7-maintenance

### ISSUE THREAD

**Issue by jw3** [PDAL/PDAL#1968]
I expected to see a `1.7-maintenance` directory under `scripts/docker`.  Was this intentionally excluded and if so whats the pattern to expect from the versioning on these scripts?

Thanks

**Comment by hobu** [comment]
bah, we haven't gotten to cleaning this up yet. I'd happily merge Dockerfile scripts for 

* `pdal/pdal:1.7-ubuntu`
* `pdal/pdal:1.7-alpine`

and go through the updates of Dockerhub to auto-build these when commits happen to the `1.7-maintenance` branch.
