### ISSUE TITLE
PDAL conversion error using Osgeo4w Powershell

### ISSUE THREAD

**Issue by niranjanreddy891** [PDAL/PDAL#1973]
`PDAL: Couldn't create writer stage of type 'writers.pcd'.`

It throws me this error while I am trying to convert .las file to .pcd file. 
I am using win-7 64bit with python-3.6 installed. PDAL version-1.6.0
Thanks in advance

**Comment by chambbj** [comment]
@niranjanreddy891 You have asked this [before](https://github.com/PDAL/PDAL/issues/1837). Also answered [here](https://gis.stackexchange.com/a/251284). The PCD plugin is still not provided with the OSGeo4W distribution.
