### ISSUE TITLE
PDAL installation error

### ISSUE THREAD

**Issue by niranjanreddy891** [PDAL/PDAL#1974]
`AttributeError: module 'pip' has no attribute 'main'`

When I am installing PDAL using `pip install PDAL`, it throws error.

I am using win-7 64 bit with python-3.6 installed. I am installing PDAL-2.0.0

**Comment by chambbj** [comment]
What is PDAL-2.0.0? Our latest release is 1.7.1. If you are referring to the 2.0.0 release of [PDAL/python](https://github.com/PDAL/python/releases/tag/2.0.0), then you can report issues [here](https://github.com/PDAL/python/issues/new).
