### ISSUE TITLE
PDAL 1.7.1 contains pdal_features.hpp with optional dependencies enabled

### ISSUE THREAD

**Issue by mloskot** [PDAL/PDAL#1976]
The latest archive http://download.osgeo.org/pdal/PDAL-1.7.1-src.tar.gz contains CMake-generated config header `include/pdal/pdal_features.hpp` which a bunch of optional dependencies enabled:

```
#define PDAL_HAVE_LASZIP
/* #undef PDAL_HAVE_LAZPERF */
/* #undef PDAL_HAVE_HDF5 */
/* #undef PDAL_HAVE_ZSTD */
#define PDAL_HAVE_ZLIB
/* #undef PDAL_HAVE_LZMA */
#define PDAL_HAVE_LIBXML2
/* #undef PDAL_HAVE_PYTHON */
#define PDAL_ARBITER_ENABLED
```

The https://www.pdal.io/development/compilation/dependencies.html list the following as *optional*:

- libxml2
- LASzip

This is troublesome to clients which compile without any of those.

I suspect, the CMake-generated header should not make it into the source distribution archive.

**Comment by hobu** [comment]
#1943 is related. We need a cpack ignore for this header.

**Comment by mloskot** [comment]
I see. I searched the archive for `pdal_features.hpp` and nothing came up, so I opened this one. Please, close if you think it should be closed.

**Comment by hobu** [comment]
> close if you think it should be closed.

Nope, we need to address this one too.

**Comment by mloskot** [comment]
Thanks!

**Comment by hobu** [comment]
@mloskot #1980 added a procedure for cutting a release, so hopefully this cleans things up considerably.
