### ISSUE TITLE
Conversion error using PDAL

### ISSUE THREAD

**Issue by niranjanreddy891** [PDAL/PDAL#1982]
I am facing conversion error while converting .las to .pcd file. I am using this command `pdal translate input.las out.pcd` . This is the error I am facing `PDAL: Couldn't create writer stage of type 'writers.pcd'`

I am using win-7 64 bit with PDAL-1.7.1

**Comment by abellgithub** [comment]
Please see the [FAQ](https://www.pdal.io/faq.html).
