### ISSUE TITLE
Couldn't create reader stage of type 'readers.pcd'.

### ISSUE THREAD

**Issue by MahdiSMIDA** [PDAL/PDAL#2000]
![screenshot_20180507_150559](https://user-images.githubusercontent.com/23388936/39703445-5da56152-5208-11e8-94da-9067392ed9ff.png)

**Comment by chambbj** [comment]
Looks like you've installed via Conda. PDAL conda-forge issues should be raised at https://github.com/conda-forge/pdal-feedstock. Regardless, if it is the conda-forge package, we are not currently building with PCL support.
