### ISSUE TITLE
Eliminate issue with Windows min/max #define

### ISSUE THREAD

**Issue by abellgithub** [PDAL/PDAL#2018]
Windows #defines min and max, which is awful, and everyone knows this, but it's how it is.  One solution to this problem is to #define NOMINMAX, which prevents the inclusion of the min/max definitions.  This works and is what we currently do when we build.  The problem, though, is that PDAL is a library and people include our header files and may not #define NOMINMAX in their code.  Anyway, there are standard techniques for preventing the compiler from expanding macros and we should use these for min and max to eliminate any issues with downstream users of PDAL.

**Comment by mloskot** [comment]
The `NOMINMAX` should be part of PDAL usage requirements.

Since PDAL uses CMake, the usage requirements could be part of the PDAL targets

On usage requirements, Daniel Pfaifer's  talk:
https://www.youtube.com/watch?v=bsXLMQ6WgIk&t=22m8s

> The way you use CMake affects your users

**Comment by abellgithub** [comment]
Not everybody is going to use cmake. When I'm doing something fast, I just
want to compile and link.

There may also be users who are depending on min and max being defined for
their application.

Injecting requirements like this into a user's build seems a bad plan and
we already experienced pushback from some people, which is what started
this in the first place.

**Comment by abellgithub** [comment]
I'm sorry but I don't understand your first point.

On your second point, I agree completely.  I just got tired of fighting and as long as we're targeting Windows, this is going to be an issue.

**Comment by mloskot** [comment]
> I'm sorry but I don't understand your first point.

I mean what perhaps his comment explains better at https://svn.boost.org/trac10/ticket/11149#comment:2

> (...) you can very well implement a max/min function in your own namespace. Then the following would be possible (due to ADL):
> ```
> using std::max;
> cpp_dec_float_50 x, y = max(x, 2*x);
> ```
> Unfortunately, ADL does not work when writing `(max)` instead of `max`

Nevermind though.

**Comment by abellgithub** [comment]
We don't have situations where we're exposing PDAL classes as templates - there's no opportunity to overload our uses of min/max AFAIK.  Notably, Eigen still does the (std::min) thing in header files.   

But all of this is awful. Why MS didn't force use of a macro to get the #defined'd versions years ago... They've taken the "we shall never break existing code for any reason ever" a little far.  There were lots of options for improving the situation and they punted.

**Comment by mloskot** [comment]
re Microsoft, I don't know. I'm not an advocate but here is how I explain it to myself (when I need to easy my own annoyance): that is for similar reason why Microsoft-s own libraries have problems when used in strict compiling mode `cl.exe /Za`, and toolkits have rights to enable extensions by default. By default, GCC enables its extensions to the C/C++ language too ie. `-std=gnu11` and `-std=gnu++11` are default modes if no other is specified.
