### ISSUE TITLE
pdal c++ extension

### ISSUE THREAD

**Issue by jfjffilk** [PDAL/PDAL#2028]
hello,
 I want to use PDAL drivers such as readers and writers in my c++ program. how to go about this? do we have any c++ extension for reader function such as reader.las?

**Comment by abellgithub** [comment]
There are lots of examples in the tests and the kernel code may also be
helpful.

**Comment by jfjffilk** [comment]
thank you. 
is it possible to use drivers like readers.las, filters.chipper directly by just passing the json file as we do in the command line from my c++ program??

**Comment by chambbj** [comment]
You would not pass a JSON file directly to a stage (such as readers.las or filters.chipper), but you can use pipelines in your own project. If you search the code for `PipelineManager` you will find a number of examples of how pipelines are constructed and managed.
