### ISSUE TITLE
python-pdal extension

### ISSUE THREAD

**Issue by jfjffilk** [PDAL/PDAL#2029]
hello,
i have installed python-pdal extension using conda with the following command

conda install -c conda-forge pdal python-pdal

After this, if i run my python file i.e the example file 
`json = """
{
  "pipeline": [
    "1.2-with-color.las",
    {
        "type": "filters.sort",
        "dimension": "X"
    }
  ]
}"""
import pdal
pipeline = pdal.Pipeline(json)
pipeline.validate() # check if our JSON and options were good
pipeline.loglevel = 8 #really noisy
count = pipeline.execute()
arrays = pipeline.arrays
metadata = pipeline.metadata
log = pipeline.log`

i get the following error, 

Traceback (most recent call last):
  File "dd.py", line 12, in <module>
    import pdal
ModuleNotFoundError: No module named 'pdal'

**Comment by chambbj** [comment]
Please create an issue at https://github.com/conda-forge/python-pdal-feedstock/issues/new. There, make sure to also include the output of `conda info` and `conda list` as directed in the issue template. Thanks!
