### ISSUE TITLE
Clipping Exercise autzen.laz missing

### ISSUE THREAD

**Issue by kylemann16** [PDAL/PDAL#2033]
I downloaded the zip file containing PDAL for the workshop and exercises, but autzen.laz was not included. This file is necessary for the clipping exercise in order to do the pipelining portion and create the stadium.las file. 

The exercise page references [Clipping with Geometries]( https://pdal.io/tutorial/clipping/index.html#clipping), which then says the laz file can be downloaded from [http://www.liblas.org/samples/autzen/autzen.laz](http://www.liblas.org/samples/autzen/autzen.laz). This site is currently down.

**Comment by hobu** [comment]
It is available from https://github.com/PDAL/data/blob/master/workshop/autzen.laz

**Comment by abellgithub** [comment]
Can this be closed?
