### ISSUE TITLE
Libzstd does not get linked

### ISSUE THREAD

**Issue by connormanning** [PDAL/PDAL#2036]
On OS X, with [libzstd](https://github.com/facebook/zstd) installed from source, configuring PDAL with `-DWITH_ZSTD` and then building fails due to missing linkage with libzstd.

For me, this is because after [FindZstd.cmake](https://github.com/PDAL/PDAL/blob/master/cmake/modules/FindZSTD.cmake), neither `ZSTD_SHARED_LIB` nor `ZSTD_STATIC_LIB` are populated, and the `STATIC` one is what PDAL uses to link with zstd.  My libraries are present:

```
$ ls /usr/local/lib/libzstd.*
/usr/local/lib/libzstd.1.3.2.dylib@
/usr/local/lib/libzstd.1.3.4.dylib*
/usr/local/lib/libzstd.1.dylib@
/usr/local/lib/libzstd.a
/usr/local/lib/libzstd.dylib@
```

`ZSTD_FOUND`, `ZSTD_INCLUDE_DIR`, and `ZSTD_LIBRARY` are all populated as expected, and replacing [this line](https://github.com/PDAL/PDAL/blob/master/CMakeLists.txt#L275) with `${ZSTD_LIBRARY}` (which is populated to `/usr/local/lib/libzstd.dylib`), allows me to get things linking properly.

**Comment by hobu** [comment]
I don't think we want the static library in every instance. A patch to adjust this as you describe seems reasonable to me. Please PR.

**Comment by abellgithub** [comment]
Do you care if we link static or dynamic?  I've been trying to get a handle on cmake findXXX modules and can clean this up.

**Comment by hobu** [comment]
> Do you care if we link static or dynamic?

Given we are a library that others are using, we should use the library the user requested. Don't we run the risk of causing symbol clashes y defaulting to always using static library?

**Comment by abellgithub** [comment]
@hobu changed the FindZSTD because of some Windows issue: https://github.com/PDAL/PDAL/commit/4f595c248ce9b1870b47f1666c456dd45e0474a2#diff-a5d6c157391193ac119d82d2fb92aa04

I'm not sure if we should revisit or just punt.  I kind of like the idea of just static linking in ZSTD, but it doesn't matter much.  The current FindZSTD doesn't populate the "standard" variables.  Perhaps it should.

**Comment by hobu** [comment]
> The current FindZSTD doesn't populate the "standard" variables. Perhaps it should.

indeed. Maybe there is a proper FindZSTD.cmake around now.
