### ISSUE TITLE
tree-based data structure on filtering

### ISSUE THREAD

**Issue by muzo583** [PDAL/PDAL#2044]
Hi all,
Is there any function for spatial data structure to use in PDAL?
My process on filtering point cloud is very slow. Maybe kdtree or octree make this progress faster? I have tested my 1.3 GB data with Cloudcompare and PDAL. Cloud compare finished filtering outlier very fast, but PDAL took to much time. 

How can I improve the PDAL performance? 

Thanksin advance.

**Comment by abellgithub** [comment]
PDAL has a quad tree and KD tree available. Without knowing the specifics of what you're doing, we can't help you.

**Comment by muzo583** [comment]
@chambbj 

I have build PDAL from source. Does it make an issue? I 've build and missed some functionalities? hmm. Is there any possibility to check performance of functions?

I am using PDAL on ubuntu 18.04 and compiled as described here: [https://pdal.io/development/compilation/unix.html](url)

Thanks.

**Comment by chambbj** [comment]
It only raises the issue that perhaps it was built in `DEBUG` mode. I also don't recall off the top of my head what types of optimizations are or are not used if the build type simply isn't specified. I'd have to take a closer look at that.

Can you provide the cmake command you used to configure the project? If you haven't already, can you also try explicitly setting `CMAKE_BUILD_TYPE=Release`?

**Comment by muzo583** [comment]
As I remember, I compliled it only 
`mkdir build `
`cd build `
`cmake ..`
`make`
`make install`

how can I see the installed type?

I have tried to view from build with `cmake-gui` but I could not see the type of build.

**Comment by chambbj** [comment]
From within your build directory, this should do the trick to show you what the value is currently.

```
cat CMakeCache.txt | grep "CMAKE_BUILD_TYPE:STRING"
```

To see/set the value using `cmake-gui` you probably just need to toggle advanced mode by pressing `t`.

To rerun `cmake` from the command line try

```
cmake .. -DCMAKE_BUILD_TYPE=Release
```

**Comment by muzo583** [comment]
@chambbj 
Thank you for your answer. I have recompiled PDAL with release and then run the outlier. But I have not get reasonable time to process.

2 minutes in CloudCompare.
20 minutes in PDAL.

Anyway. I can still use both CloudCompare and PDAL.

Thank you very much.
