### ISSUE TITLE
Conda infiltration needs to permeate docs

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#2047]
Need docs:

https://pdal.io/python.html

https://pdal.io/development/compilation/python.html

**Comment by chambbj** [comment]
@hobu I've started this. The first link was easy to find, but the second is a bit of a mystery to me. Aren't docs built off the current maintenance branch? If so, `python.rst` should live [here](https://github.com/PDAL/PDAL/tree/1.7-maintenance/doc/development/compilation), but I see nothing. Did this move to PDAL/python and the docs are just lagging?
