### ISSUE TITLE
SMRF and PMF should no longer default to using last returns

### ISSUE THREAD

**Issue by chambbj** [PDAL/PDAL#2053]
Although this can be a powerful option, now that we have changed the last return filtering to retain strictly last returns (i.e., last of **many**, see #1844 and #2045), it will give misleading results in scenes where ground returns arise from single returns. Better to switch the default behavior to process all returns, and let the user turn this on if they know their data is largely multiple return.

**Comment by abellgithub** [comment]
I'm not sure what's up here.  Have we, essentially, changed the definition of "last return" under the covers to exclude points that only have a single return?  In that case, should we implement the previous functionality and indicate this with other language?  For instance, should be change the option `filters.pmf.last` to something like `filters.pmf.segmentation` and set it to "last && only" or whatever?

**Comment by chambbj** [comment]
I wouldn't say we changed the definitely per se, but we did change the implementation to match an established definition.

I would not be opposed to offering the previous set of returns via another option name.

There is still the question of defaults. Maybe offer both options (`last` and `whatever-we-call-it`), both defaulting to `false`.

**Comment by chambbj** [comment]
Still may be a bit clunky, but I think I will actually provide two options to each ground filter, one called `last`and one called `only`. Both will be `true` by default, thus matching our current output. Either can be turned off, allowing you to process with `last` or `only` independently. And if both are turned off, you will process the whole cloud. There is no option to process `first` or `intermediate` returns as these would presumably have no impact on ground segmentation.

**Comment by abellgithub** [comment]
I'd prefer a single option that takes various options.  "mode" or some such.  It prevents a proliferation of options and makes it easier to change things without breaking existing pipelines.

**Comment by chambbj** [comment]
Closed via #2055
