### ISSUE TITLE
LAS 1.4 extended types error message

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#2059]
The `readers.las` gives a false error message given the following conditions:

* The point format is 6-10
* There is no WKT
* There is no GeoTIFF

The error message is 

```Invalid SRS specification.  GeoTiff not allowed with point formats 6 - 10```

I think the issue is `LasHeader::incompatibleSrs` also needs to check if the WKT is empty or not.

**Comment by abellgithub** [comment]
The code implies that the global encoding bit is improperly set for the file.
