### ISSUE TITLE
Reprojecting LAS 1.4 with extra bytes?

### ISSUE THREAD

**Issue by AndrewYinLi** [PDAL/PDAL#2061]
For some reason I cannot reproject LAS 1.4 files with extra bytes as the coordinate system does not show up for several viewers. I can see the correct coordinate system if I only reproject.

**Comment by abellgithub** [comment]
It's unclear what you're doing or how you're trying to use PDAL.  Please provide a command line and/or pipeline so that we can help you.

**Comment by AndrewYinLi** [comment]
My bad! 
``
jsonObj = {
				"pipeline": [
					fileToConvert, 
					{
						"type": "writers.las",
						"filename": lasTempFilePath,
						"minor_version": "4", # Specify version 1.4
						"extra_dims": "all" # Include all possible dimensions
						"a_srs": "EPSG:32619"
					}
				]
			}
``
Should this be correctly converting a file to LAS 1.4 and also projecting it? I can do one or the other and verify it in my viewer and also by reading the outputted file through PDAL but I cannot do both. If this pipeline looks correct, then it's probably a problem on my viewer's end (ArcGIS Desktop).

**Comment by abellgithub** [comment]
A pipeline like this won't reproject.  Adding the "a_srs" option to the writer doesn't reproject, it just sets the SRS of the file as specified.  You must add a reprojection filter before the writer in order to actually reproject the points.  You generally don't need to specify the SRS of the output dataset - it will be carried from the input or an intermediate filter.

**Comment by AndrewYinLi** [comment]
I tried this:
``
jsonObj = {
				"pipeline": [
					fileToConvertPath
					{
						"type": "filters.reprojection",
						"out_srs": "EPSG:32619" # Reprojection to the correct format
					},
					{
						"type": "writers.las",
						"filename": lasTempFilePath,
						"minor_version": "4", # Specify version 1.4
						"extra_dims": "all" # Include all possible dimensions
					}
				]
			}
``
but it appears to still not be properly projected. Not quite sure if I am doing this correctly.

**Comment by AndrewYinLi** [comment]
For example, when I load the converted file into ArcScene, it cannot detect the coordinate system. If I remove ``"minor_version": "4"`` and ``"extra_dims": "all"`` from the pipeline and load the converted file into ArcScene it can detect the coordinate system.

**Comment by AndrewYinLi** [comment]
The problem with that is that the file is no longer LAS 1.4 and is missing the extra dimensions I want.

**Comment by abellgithub** [comment]
You might try using `pdal info --metadata` to look at the output file information.  If you have lastools installed, you can also use `lasinfo`.

**Comment by AndrewYinLi** [comment]
That's a good idea! I'm going to keep this open for now and try your suggestion tomorrow to make sure the LAS file is indeed projected to my specification and holds the extra dimensions.

**Comment by AndrewYinLi** [comment]
I think that this problem is on ArcScene's end. I tried your suggestion on two converted .las files, with and without extra dimensions. Spatial reference is clearly defined the same way in both outputted files.

**Comment by AndrewYinLi** [comment]
I just want to note that I was able to circumvent my problem with ESRI Arc software using the method arcpy.management.CreateLasDataset(...) available in their native arcpy library, which generates a .lasd pointer file with the correct spatial reference. I have no clue why their software refuses to play nice with PDAL.

**Comment by abellgithub** [comment]
If you can show that PDAL is creating output that doesn't meet the LAS specification, you should open another ticket.

Glad you got your problem resolved.
