### ISSUE TITLE
pdal split does not accept negative values for origin

### ISSUE THREAD

**Issue by romulogoncalves** [PDAL/PDAL#2062]
If we define origin negative it reports that no value was provided.
```
pdal split -i C_25EZ2.laz -o ./3/C_25EZ2.laz --origin_x -212.6837 --origin_y 99063.1429 --length 2816.85898203

PDAL: kernels.split: Argument 'origin_x' needs a value and none was provided.
```

We are using `EPSG:28992`. Should not be possible to have an `origin_x` which is negative?

**Comment by abellgithub** [comment]
PDAL can't tell that you're not trying to specify an argument named `212.6837`  Get around this by using the assignment syntax: `--origin=-212.6837`

**Comment by JRice15** [comment]
Could this fact be documented for split and tile? It took me a good while to find this

**Comment by chambbj** [comment]
PRs are graciously accepted @JRice15. You can find the documentation source [here](https://github.com/PDAL/PDAL/blob/master/doc/apps/split.rst) and [here](https://github.com/PDAL/PDAL/blob/master/doc/apps/tile.rst).
