### ISSUE TITLE
filters.python add_dimension only works for single dimension

### ISSUE THREAD

**Issue by devdylan** [PDAL/PDAL#2098]
Despite the `filters.python` [documentation](https://pdal.io/stages/filters.python.html) stating

> If you want to write a dimension that might not be available, use can use one **or more** add_dimension options.

, only the _last_ argument listed as an `add_dimension` option is honored.

For example,
```
{
    "type":"filters.python",
    "function":"MyFilter",
    "script":"MyScript",
    "module":"anything",
    "add_dimension":"NewDimensionOne",
    "add_dimension":"NewDimensionTwo",
    "add_dimension":"NewDimensionThree"
}
```
Only values written to `NewDimensionThree` will appear in the output model.

Note, my workaround is to use filters.ferry as a pre-step:
```
{
   "type": "filters.ferry",
   "dimensions": "=>NewDimensionOne,=>NewDimensionTwo,=>NewDimensionThree"
}
```

**Comment by devdylan** [comment]
@abellgithub,

Now that I'm testing it a bit, I'm actually having trouble using an array.

When I use an array of dimensions in my python filter, the output model has the dimensions I added, but its values are all zero (as revealed by running `info --all`). This is the behavior I was seeing before for all added dimensions except the last one listed.

When I use the filters.ferry pre-step (to add the dimensions), followed by the python filter (which has no `add_dimension` option), the output model has dimensions *with the values I set in the python filter*. Everything works as expected.

I can provide more context if needed.

This the gist of my filter:
```
import numpy as np

def colorize_classification(ins, outs):
    cls = ins['Classification']

    red = np.ones(cls.size, dtype=np.uint8)
    green = np.ones(cls.size, dtype=np.uint8)
    blue = np.ones(cls.size, dtype=np.uint8)

    it = np.nditer(cls, flags=['f_index'])
    while not it.finished:

        if (cls[it.index] ==1):
            red[it.index] = 204
            blue[it.index] = 20
            green[it.index] = 153

        elif (cls[it.index] ==2):
            red[it.index] = 255
            blue[it.index] = 255
            green[it.index] = 255

        ...
            
        else:
            red[it.index] = 255
            blue[it.index] = 255
            green[it.index] = 255

        it.iternext()

    outs['Red'] = red.astype('float64')
    outs['Blue'] = blue.astype('float64')
    outs['Green'] = green.astype('float64')
    return True
```

**Comment by abellgithub** [comment]
Please copy this last bit into a new ticket and add the relevant pipeline that's causing problems.

**Comment by devdylan** [comment]
Will do.
