### ISSUE TITLE
writers.gdal: set reference system

### ISSUE THREAD

**Issue by chobm** [PDAL/PDAL#2101]
Is it possible to set the reference system when creating a raster (GeoTiff) with `writers.gdal` ? I tried to use the "gdalopts" option, but it does not define any reference system:

```
{
  "pipeline":[
    {
      "type":"readers.las",
      "filename":"input.las"
    },
    {
      "type":"writers.gdal",
      "resolution":"0.5",
      "output_type":"idw",
      "gdalopts":"a_srs=EPSG:25833",
      "filename":"output.tif"
    }
  ]
}
```
Checking gdalinfo after processing leaves the "Coordinate system is" field empty:
![image](https://user-images.githubusercontent.com/41343405/43133448-14365296-8f3f-11e8-9fe6-31ced49a3c9f.png)

**Comment by abellgithub** [comment]
To my knowledge, `a_srs` isn't a driver option for the GDAL tiff driver.  `a_srs` is used as an option to commands, like `gdal_translate`.

If your source file is missing an SRS but you know what it is, you can use the `spatialreference` option on the LAS reader.  If your source file has a particular SRS and it you want the output written using a different SRS, you should reproject the data by adding a [reprojection filter](https://pdal.io/stages/filters.reprojection.html) before you create the raster.

**Comment by chobm** [comment]
Thanks a lot!
