### ISSUE TITLE
filters.python add_dimension array not working

### ISSUE THREAD

**Issue by devdylan** [PDAL/PDAL#2105]
Follow-up, from https://github.com/PDAL/PDAL/issues/2098

When I use an array of dimensions in my python filter, the output model has the dimensions I added, but its values are all zero (as revealed by running `info --all`).
```
      {
        "average": 0,
        "count": 21178491,
        "maximum": 0,
        "minimum": 0,
        "name": "Red",
        "position": 12,
        "stddev": 0,
        "variance": 0
      },
      {
        "average": 0,
        "count": 21178491,
        "maximum": 0,
        "minimum": 0,
        "name": "Green",
        "position": 13,
        "stddev": 0,
        "variance": 0
      },
      {
        "average": 0,
        "count": 21178491,
        "maximum": 0,
        "minimum": 0,
        "name": "Blue",
        "position": 14,
        "stddev": 0,
        "variance": 0
      },
 ```

When I use a filters.ferry pre-step to add the dimensions, followed by the python filter (which has no add_dimension option), the output model has dimensions with the values I set in the python filter. Everything works as expected, but this adds considerable processing time to the pipeline.
```
      {
        "average": 244.1093034,
        "count": 21178491,
        "kurtosis": 14.35534825,
        "maximum": 255,
        "minimum": 0,
        "name": "Red",
        "position": 12,
        "skewness": -3.876008839,
        "stddev": 42.26158408,
        "variance": 1786.041489
      },
      {
        "average": 49.4982151,
        "count": 21178491,
        "kurtosis": 1.284154791e+13,
        "maximum": 255,
        "minimum": 0,
        "name": "Green",
        "position": 13,
        "skewness": 3.106217842e+12,
        "stddev": 100.1434097,
        "variance": 10028.70251
      },
      {
        "average": 120.8368289,
        "count": 21178491,
        "kurtosis": -3.0158649e+11,
        "maximum": 255,
        "minimum": 0,
        "name": "Blue",
        "position": 14,
        "skewness": 4.934173081e+11,
        "stddev": 123.2736605,
        "variance": 15196.39537
      },
```

Pipeline with filters.ferry pre-step to add dimensions:
```
{
  "pipeline":[
    "/data/input/classified_lidar.las",
    {
      "type": "filters.ferry",
      "dimensions": "=>Green,=>Red,=>Blue"
    },
    {
      "type":"filters.python",
      "script":"/data/scripts/pdal/prepare/colorize_classification.py",
      "function":"colorize_classification",
      "module":"anything"
    },
    "/data/output/colorized_classified_lidar.las"
  ]
}
```

Pipeline with array of dimensions in `add_dimension` (and no filters.ferry pre-step):
```
{
  "pipeline":[
    "/data/input/point_cloud.las",
    {
      "type":"filters.python",
      "script":"/data/scripts/pdal/prepare/colorize_classification.py",
      "function":"colorize_classification",
      "module":"anything",
      "add_dimension":["Red", "Green", "Blue"]
    },
    "/data/output/colorized_point_cloud.las"
  ]
}
```

This the gist of my filter:

```
import numpy as np

def colorize_classification(ins, outs):
    cls = ins['Classification']

    red = np.ones(cls.size, dtype=np.uint8)
    green = np.ones(cls.size, dtype=np.uint8)
    blue = np.ones(cls.size, dtype=np.uint8)

    it = np.nditer(cls, flags=['f_index'])
    while not it.finished:

        if (cls[it.index] ==1):
            red[it.index] = 204
            blue[it.index] = 20
            green[it.index] = 153

        elif (cls[it.index] ==2):
            red[it.index] = 40
            blue[it.index] = 70
            green[it.index] = 255

        ...
            
        else:
            red[it.index] = 255
            blue[it.index] = 255
            green[it.index] = 255

        it.iternext()

    outs['Red'] = red.astype('float64')
    outs['Blue'] = blue.astype('float64')
    outs['Green'] = green.astype('float64')
    return True
```

Thanks for all your help.

**Comment by abellgithub** [comment]
What is the dataformat of your source LAS file?

**Comment by abellgithub** [comment]
Or post your source file someplace.

**Comment by abellgithub** [comment]
I'm sorry, but I misled.  The repeated option support was added after version 1.7.2 with PR #2021 (missed 1.7.2  by about a week).  If you want to build PDAL from source, you can use the master branch and the pipeline should work as discussed (it does for me).  If not, the ferry method you have already used is the way to go until the next release, expected September, 2018.

(Prior to this change, arrays were treated as JSON data, which is why you aren't receiving an error).

**Comment by devdylan** [comment]
👍 Mystery solved. Thank you.

**Comment by abellgithub** [comment]
You could also pre-add RGB to the input by translating the file from dataformat 1 to dataformat 3, but I can't imagine that would be any faster than the ferry option.

**Comment by devdylan** [comment]
Ok, good to know. I'm going to build from source though to get the capability.

**Comment by abellgithub** [comment]
For anyone else facing this issue, another "trick" to easily introduce dimensions is to add an empty text file with the dimensions you want in the header:

in.txt:
```
X Y Z Red Green Blue
```

pipeline.json
```
{
    "pipeline": [
        "in.txt",
        "in.las",
        {
            ...
        }
    ]
}
```

**Comment by devdylan** [comment]
Hmm, I gave your alternative method a shot in hopes that it may offer a performance improvement over `filters.ferry`, but it doesn't seem to be working. I tried both with only the added dimensions in the text file, as well as with all the dimensions. Same results - during my python filter, it complains that I am attempting to iterate over an empty dimension (`Classification`).

dimensions.txt:
`X Y Z Classification Red Green Blue`

or

dimensions.txt:
`Red Green Blue`

Result:
```
PDAL: 'Traceback (most recent call last):\n''  File "anything", line 18, in colorize_classification\n''ValueError: Iteration of zero-sized operands is not enabled\n'
```

Pipeline:
```

{
  "pipeline":[
    "/data/scripts/pdal/prepare/dimensions.txt",
    "/data/input/classified_lidar.las",
    {
      "type":"filters.python",
      "script":"/data/scripts/pdal/prepare/colorize_classification.py",
      "function":"colorize_classification",
      "module":"anything"
    },
    "/data/output/colorized_classified_lidar.las"
  ]
}
```

**Comment by abellgithub** [comment]
Data sources are maintained separately in PDAL until they are merged, either explicitly using a merge filter, or implicitly when written.  In your case, the first call to the python function has no items in it (there were no points in the text file) and your code doesn't deal with this case.  If you were to exit if there were no points in the point set (called a PointView), things should work.

**Comment by devdylan** [comment]
Ok, that makes sense. After introducing a merge filter before the python filter in the pipeline, things are working now. Performance is comparable to the ferry method - maybe slightly better. 

Lastly, I received no warning about multiple SRSs. 

All set now. Thanks so much for your help.

**Comment by abellgithub** [comment]
If it were me, I'd skip the merge filter and change the python code.  The merge filter does work (a little), and really, you aren't merging anything.  The issue is that most filters iterate the points (even if they don't do much with them), and your files contain a lot of points.

**Comment by devdylan** [comment]
I see what you're saying now - the python filter runs for each data source, including my "empty" data source (which just contains the new dimensions). Thus, I should handle this case in my python script:
```
    cls = ins['Classification']
    if(cls.size < 1):
        return True
```
This provides slightly better performance than the ferry method, fyi. Thanks again!

**Comment by abellgithub** [comment]
Another large gating factor in your pipeline is the python filter.  Python numpy arrays require contiguous data.  We currently don't store PDAL data contiguously, so it must be copied in order to get it to Python.  This is expensive in terms of memory and CPU.  We used to store data contiguously, but we got a bunch of complaints from people with large data sets on 32 bit systems.  We're planning on implementing a numpy point table that should alleviate this, but it hasn't hit the top of my queue yet.  If you can write C++ code, your python can be written easily as a filter which you could invoke from your pipeline or using the API.  We're also happy to do consulting on such things.

**Comment by devdylan** [comment]
Good to know - the python filter should suffice for now, but we may need to look the C++ option if we run into significant performance issues.
