### ISSUE TITLE
PDAL 1.7.2 encounters build error on Docker Hub

### ISSUE THREAD

**Issue by mevatron** [PDAL/PDAL#2110]
Seems like the latest version of PDAL 1.7.2 is unable to build on Docker Hub due to Busybox unzip not supporting the -j option. More info is available here: https://hub.docker.com/r/pdal/pdal/builds/bcd6f77g855zaqwaw5rvlpy/

**Comment by hobu** [comment]
Fixed in @ 0654cd7a301a703d0d45e7941cac0bdf1131e6a0
