### ISSUE TITLE
Handling Imaginary numbers

### ISSUE THREAD

**Issue by AndrewYinLi** [PDAL/PDAL#2111]
How do I handle imaginary numbers? I keep getting this error:

```
File "pdal\libpdalpython.pyx", line 88, in pdal.libpdalpython.PyPipeline.execute (pdal/libpdalpython.cpp:2545)
RuntimeError: Unable to set data and convert as requested: :double(-nan(ind)) -> float
```

I am converting preprocessed .bpf data to .las and ended up having some imaginary numbers in my data.

**Comment by abellgithub** [comment]
PDAL doesn't handle imaginary numbers.  BPF doesn't support them.  Neither does LAS. I'm not sure how you're making imaginary numbers.  If you mean NaN values, we don't support writing NaNs either.  It's hard to know how you're generating these values without more information.

**Comment by hobu** [comment]
Can you please provide a small python example that demonstrates the issue? This should be handled in https://github.com/PDAL/python, but since none of the formats support imaginary numbers at the moment, the resolution is they are likely to be dropped on the floor without error.

**Comment by AndrewYinLi** [comment]
I spoke too soon, they were NaNs instead of imaginary numbers.
