### ISSUE TITLE
Passing non-string list argument to filter

### ISSUE THREAD

**Issue by jw3** [PDAL/PDAL#2113]
Seeing a difference between passing string lists as arguments (from both command line and pipeline) and any other data type.

Data defined as

```
      struct Args
      {
         std::vector<int> ivec;
         std::vector<std::string> svec;
      };
```

initializing vectors like this works

```
   void VecFilter::addArgs(ProgramArgs& args) {
      args.add("ivec", "just a vector of ints", m_args.ivec, {0, -1});
      args.add("svec", "just a vector of strings", m_args.svec, {"is","mt"});
   }
```

then calling as part of a pipeline with

```
pdal pipeline -i pipeline.json --filters.vec.svec=foo,bar,baz --filters.vec.ivec=1,2,3
```

Results in the string vector being populated correctly, but the int vector will only receive the first value in the list.

Similar behavior if calling filter directly

```
pdal info --driver filters.vec --filters.vec.svec=x,y,z --filters.vec.ivec=9,1,1 no-points.las
```

or from a pipeline json (using format that `--pipeline-serialization` suggests, also have tried several other notations)

```
"ivec": "1,2,3",
"svec": "foo,bar",
```

Am I doing something incorrectly or are non-string types unsupported?  I saw verbiage in docs and some code in pdal that make me think its the latter, but didn't find a definitive answer.

**Comment by abellgithub** [comment]
Strings are special.

We don't try to parse generic vectors of stuff from a string because we don't know how.  The string thing is just a convenience that works most of the time.  You can repeat options that map to a vector<int>:

`pdal info --filters.vec.ivec=1 --filters.vec.ivec=2 --filters.vec.ivec=3`

In a pipeline they can be specified in an array:

```
{
    "type": "filters.vec",
    "ivec": [1, 2, 3]
}
```

**Comment by abellgithub** [comment]
It appears you're right.  I'll investigate.

**Comment by abellgithub** [comment]
Closing in favor of #2114

**Comment by abellgithub** [comment]
You can tell how often this feature is used ;)
