### ISSUE TITLE
PDAL tindex in Docker: unable to read tiles on s3?

### ISSUE THREAD

**Issue by wakruse** [PDAL/PDAL#2153]
Is arbiter enabled for reading tiles on s3 in pdal applications like tindex in Docker? If so, an example would welcome.

I can successfully index tiles from the local ec2 directory using a list of tiles piped into Docker through –stdin as described in the documentation. However, I’m unable to do the same thing if the tiles are on s3 and the list of tiles is updated to the full s3 paths. The error message is:  “Unable to open stream for the first file in the list ‘/s3://bucket-name/pathname/filename.laz”, which should be arbiter compatible, except for the “/” that was added by pdal at the beginning.

Current command line using Docker: cat files_to_index_list.txt | docker run -i  --rm -v /home/ec2-user/.aws:/root/.aws -v /home/ec2-user/tile_index:/data pdal/pdal pdal tindex --developer-debug --fast_boundary --tindex /data/file_tile_index --stdin

Thanks

**Comment by hobu** [comment]
> Is arbiter enabled for reading tiles on s3 in pdal applications like tindex in Docker? 

I do not think this pathway has been specifically tested, and it is likely there are some issues. Arbiter simply pulls down a whole copy of the file to a tmp location and then PDAL does its business there. We would gladly merge some patches that fix up this workflow.

**Comment by wakruse** [comment]
Thanks for the quick answer confirming that issues may remain. I currently use a python script to copy the s3 files to local temp storage which works but was attempting to simplify the process using pdal's existing built-in capabilities. Also for large tile sets, using the --fast_boundary switch would run much faster of only the tile header was downloaded. As I continue becoming more familiar with the code, perhaps I'll end up in a better position to suggest patches. I seems that entwine may already have an equivalent fast boundary functionality working with the trustHeaders command option so I'll take a look there first for an example.

**Comment by wakruse** [comment]
One more (off topic) question: Is there an estimate for when a PDAL readers.ept capability might become available for reading entwine ept indexed data sets into processing pipelines?

**Comment by hobu** [comment]
Please email me at howard@hobu.co to find out about that topic.
