### ISSUE TITLE
Passing negative numeric list arguments to filter

### ISSUE THREAD

**Issue by jw3** [PDAL/PDAL#2155]
Related to discussion from #2113 

On master we are seeing a failure when passing negative values as a vector parameter to a filter.  This failure occurs from both a pipeline json and from command line arguments.

data defined as
```
      struct Args
      {
         std::vector<int> ivec;
      };
```
then
```
{
  "pipeline": [
    {
      "ivec": [-1],
      "type": "filters.vec"
    }
  ]
}
```
or
```
pdal info --driver filters.vec --filters.vec.ivec=-1 no-points.las
```
Produces error

> PDAL: filters.vec: Argument 'ivec' needs a value and none was provided.

**Comment by abellgithub** [comment]
I believe this is resolved by surrounding the value with quotes.

**Comment by jw3** [comment]
So, like this?
```
"ivec": ["-1"],
```
with multiple values
```
"ivec": ["-1",2,3],
```
Both attempts produce the same error
>PDAL: filters.vec: Argument 'ivec' needs a value and none was provided.

Or perhaps you had something else in mind.

**Comment by abellgithub** [comment]
I have previously tested this on the command line, but not in pipelines.

**Comment by abellgithub** [comment]
I've recreated this. It should be fixed shortly.
