### ISSUE TITLE
filters.crop with polygon giving unexpected results

### ISSUE THREAD

**Issue by vstaggs** [PDAL/PDAL#2161]
Hi,

I'm using PDAL 1.7.2-1 on Windows 10 x64, as part of the OSGeo4W install.

I'm attempting to use filters.crop, following the example at https://pdal.io/stages/filters.crop.html?highlight=crop

When I filter with "bounds", it seems to be working, but when I filter with an equivalent polygon wkt it looks like all the original points in the las file are being returned, and not a cropped result set.

I tried using clockwise and counter-clockwise winding orders for the polygon, but it looks like my results are the same.

Are there any gotchas or caveats when using filters.crop?

[pipeline.json.txt](https://github.com/PDAL/PDAL/files/2357617/pipeline.json.txt)
[input.laz.txt](https://github.com/PDAL/PDAL/files/2357618/input.laz.txt)
[command.txt](https://github.com/PDAL/PDAL/files/2357621/command.txt)

**Comment by abellgithub** [comment]
I'm guessing this issue is [this](https://github.com/PDAL/PDAL/issues/2038).  You can verify by running in standard mode (using the --nostream option).

**Comment by hobu** [comment]
With `master`, it fails to crop any points for me with the following pipeline and `--nostream`:

```
{
	"pipeline": [
		"input.laz",
		{
			"type": "filters.crop",
			"polygon": "POLYGON(( 532325.0 2230550.0, 532325.5 2230550.0, 532325.5 2230550.5, 532325.0 2230550.5, 532325.0 2230550.0))",
			"outside": false
		},
		{
			"type": "writers.las",
			"filename": "polygon.laz"
		}
	]
}
```

**Comment by hobu** [comment]
This also fails
```
{
	"pipeline": [
		"input.laz",
		{
			"type": "readers.las",
			"spatialreference": "EPSG:26915",
			"filename": "input.laz"
		},
		{
			"type": "filters.crop",
			"a_srs": "EPSG:26915",
			"polygon": "POLYGON(( 532325.0 2230550.0, 532325.5 2230550.0, 532325.5 2230550.5, 532325.0 2230550.5, 532325.0 2230550.0))",
			"outside": false
		},
		{
			"type": "writers.las",
			"filename": "polygon.laz"
		}
	]
}
```
```
(PDAL Debug) Debugging...
(pdal pipeline Debug) Executing pipeline in standard mode.
PDAL: filters.crop: Polygon::transform failed due to ref being empty
```

**Comment by abellgithub** [comment]
This fails because there are no points in the input set that fall in the bounding region.  Clipping with a box gives the same results.

**Comment by vstaggs** [comment]
Not sure if this helps, but with the same input dataset, if I specify bounds in the pipeline.json file like so:

    "bounds": "([532325,2230550],[532325.5,2230550.5])"

then I get an output laz file with what looks like 167 points.

If I comment out the "bounds" property in pipeline.json and use a polygon instead, like so:

  			"polygon": "POLYGON((
				532325.0 2230550.0,
				532325.0 2230550.5,
				532325.5 2230550.5,
				532325.5 2230550.0,
				532325.0 2230550.0
			))",

then I get an output file containing 77858 points, which is how many were in the original input file.

I.e. I'm not getting an empty result set when using a polygon in the pipeline file, it looks like I'm getting all the points in the output that were in the input.

**Comment by vstaggs** [comment]
If I remove the comments from the pipeline.json file I get the same result.

I think maybe I'm staring too closely at this polygon and hopefully I'm making a rookie mistake.

How is the polygon wkt not equivalent to the bounds?  And if there were no points in the input dataset falling within the area described by the polygon, shouldn't I then be getting an empty output dataset?

**Comment by vstaggs** [comment]
Whoops, looking at the documentation for bounds...

**Comment by vstaggs** [comment]
Ok, I finally got it to work the way I expected it to work for bounds and the equivalent polygon.  I'm attaching the pipeline for using bounds and also the pipeline for using a polygon.  Couldn't get the polygon to work until adding a spatial reference using Hobu's post above for guidance, and also looking at the details for bounds using abellgithub's post above.

I am happy as the proverbial clam!  Thanks for everyone's help.

[pipeline.bounds.json.txt](https://github.com/PDAL/PDAL/files/2358343/pipeline.bounds.json.txt)
[pipeline.polygon.json.txt](https://github.com/PDAL/PDAL/files/2358344/pipeline.polygon.json.txt)

**Comment by Vicent-Ribas** [comment]
Hi, I am having the same issue. I am working with a Python embebed PDAL pipeline, and when I use the filters.crop the output is not cropped, but the original surface. See my pipeline:

`        print("PDAL pipeline")
        pipeline = (
            pdal.Reader(norm_las, spatialreference=f"{src}", extra_dims="HeightAboveGround=float32") # change to 64 when I re-run the normalization function with next point cloud
            | pdal.Filter.crop(a_srs=f"{src}", polygon=f"{serie}", outside="true")
            | pdal.Filter.range(limits="returnnumber[1:1]")
            | pdal.Filter.ferry(dimensions="HeightAboveGround => z")
            | pdal.Writer.las(temp_file, a_srs=f"{src}")
        )

        print("Executing pipeline")
        pipeline.execute()
`

**src** is the Spatial Reference System that I am working with, and **serie** is my polygon in a WKT format: "POLYGON ((137679.77354564724 -940686.5695928412, 137679.77354564724 -940711.5695928412, 137654.77354564724 -940711.5695928412, 137654.77354564724 -940686.5695928412, 137679.77354564724 -940686.5695928412))". 

I am looping over the several polygons of a shapefile. 

I have tried to replicate what vstaggs suggested in the last post but it is not working in my embebed Python pipeline. I will very much appreciate any help. Thank you!
