### ISSUE TITLE
pdal info doesn't work with non-file sources

### ISSUE THREAD

**Issue by abellgithub** [PDAL/PDAL#2181]
Sources such as EPT and greyhound don't currently work with `pdal info`.  Fixing may be as simple as removing the expectation that the sources are files, but they should all be tested.

**Comment by connormanning** [comment]
To reproduce: `pdal info ept://http://na.entwine.io/lone-star`

Currently this invocation fails with `PDAL: File not found: ept://http://na.entwine.io/lone-star`.  The relevant code is the `fileExists` check in the InfoKernel [here](https://github.com/PDAL/PDAL/blob/master/kernels/InfoKernel.cpp#L280-L281).  If allowed to get past this check, the above `pdal info` command succeeds.

**Comment by abellgithub** [comment]
This is addressed in #1894
