### ISSUE TITLE
Can not write 1.0 Las files

### ISSUE THREAD

**Issue by martinheidegger** [PDAL/PDAL#2196]
When trying to write las-files with `--writers.las.minor_version=0` it exits with following error: 

```
PDAL: writers.las: Invalid value '0' for argument 'minor_version'.
```

Yet the documentation mentions:

> There are five LAS versions – 1.0 to 1.4. Each iteration added some complexity to the format in terms of capabilities it supports, possible data types it stores, and metadata. Users of LAS must balance the features they need with the use of the data by downstrea...

https://pdal.io/tutorial/las.html#id4

Is this a bug? (the other versions work)

**Comment by abellgithub** [comment]
On Tue, Oct 2, 2018 at 2:06 AM Martin Heidegger <notifications@github.com>
wrote:

> When trying to write las-files with --writers.las.minor_version=0 it
> exits with following error:
>
> PDAL: writers.las: Invalid value '0' for argument 'minor_version'.
>
> Yet the documentation mentions:
>
> There are five LAS versions – 1.0 to 1.4. Each iteration added some
> complexity to the format in terms of capabilities it supports, possible
> data types it stores, and metadata. Users of LAS must balance the features
> they need with the use of the data by downstrea...
>
> https://pdal.io/tutorial/las.html#id4
>
> Is this a bug? (the other versions work)
>
I believe that LAS version 1.0 was an abortive first attempt.  PDAL doesn't
support it.  AFAIK nobody uses LAS version 1.0.

-- 
Andrew Bell
andrew.bell.ia@gmail.com

**Comment by hobu** [comment]
> I believe that LAS version 1.0 was an abortive first attempt. 

There is LAS 1.0 data out there. I agree that maybe PDAL shouldn't proliferate it, but we definitely see 1.0 data from time to time. What prompts the need to write 1.0 data? I think our `writers.las` doc should be updated to say PDAL only writes 1.1 – 1.4.

**Comment by martinheidegger** [comment]
> What prompts the need to write 1.0 data?

I wanted to use pdal to generate test data for my tool, see if the tool supports las 1.0.

**Comment by hobu** [comment]
You'll have to make that test data with LAStools or libLAS.
