### ISSUE TITLE
pdal info empty output

### ISSUE THREAD

**Issue by skoslitz** [PDAL/PDAL#2234]
I am using pdal info within a docker env for a specific .las file (~2 GB).

`docker run -v /Users/user.name/workspaces/testData:/data pdal/pdal pdal info /data/sp.las --developer-debug`

Unfortunately I get no output , no errors just nothing, but it works with smaller files.

Using lasinfo from LASTools works.
Here is the output from LASTools lasinfo:
`lasinfo (180520) report for 'sp.las'
reporting all LAS header entries:
  file signature:             'LASF'
  file source ID:             1
  global_encoding:            0
  project ID GUID data 1-4:   00000000-0000-0000-0000-000000000000
  version major.minor:        1.2
  system identifier:          'Agisoft PhotoScan'
  generating software:        'Agisoft PhotoScan'
  file creation day/year:     238/2016
  header size:                227
  offset to point data:       698
  number var. length records: 3
  point data format:          2
  point data record length:   26
  number of point records:    67003099
  number of points by return: 67003099 0 0 0 0
  scale factor x y z:         0.0001 0.0001 0.0001
  offset x y z:               455000 5706000 100
  min x y z:                  455426.5285 5706750.6877 106.5704
  max x y z:                  455544.0945 5706861.8590 122.6846
variable length header record 1 of 3:
  reserved             0
  user ID              'LASF_Projection'
  record ID            34735
  length after header  200
  description          ''
    GeoKeyDirectoryTag version 1.1.0 number of keys 24
      key 1024 tiff_tag_location 0 count 1 value_offset 1 - GTModelTypeGeoKey: ModelTypeProjected
      key 1025 tiff_tag_location 0 count 1 value_offset 1 - GTRasterTypeGeoKey: RasterPixelIsArea
      key 2048 tiff_tag_location 0 count 1 value_offset 4258 - GeographicTypeGeoKey: look-up for 4258 not implemented
      key 2049 tiff_tag_location 34737 count 7 value_offset 0 - GeogCitationGeoKey: ETRS89
      key 2050 tiff_tag_location 0 count 1 value_offset 6258 - GeogGeodeticDatumGeoKey: look-up for 6258 not implemented
      key 2051 tiff_tag_location 0 count 1 value_offset 8901 - GeogPrimeMeridianGeoKey: PM_Greenwich
      key 2054 tiff_tag_location 0 count 1 value_offset 9102 - GeogAngularUnitsGeoKey: Angular_Degree
      key 2055 tiff_tag_location 34736 count 1 value_offset 0 - GeogAngularUnitSizeGeoKey: 0.01745329252
      key 2056 tiff_tag_location 0 count 1 value_offset 7019 - GeogEllipsoidGeoKey: Ellipse_GRS_1980
      key 2057 tiff_tag_location 34736 count 1 value_offset 1 - GeogSemiMajorAxisGeoKey: 6378137
      key 2059 tiff_tag_location 34736 count 1 value_offset 2 - GeogInvFlatteningGeoKey: 298.2572221
      key 2061 tiff_tag_location 34736 count 1 value_offset 3 - GeogPrimeMeridianLongGeoKey: 0
      key 3072 tiff_tag_location 0 count 1 value_offset 25833 - ProjectedCSTypeGeoKey: ETRS89 / UTM 33N
      key 3073 tiff_tag_location 34737 count 22 value_offset 7 - PCSCitationGeoKey: ETRS89 / UTM zone 33N
      key 3074 tiff_tag_location 0 count 1 value_offset 16033 - ProjectionGeoKey: Proj_UTM_zone_33N
      key 3075 tiff_tag_location 0 count 1 value_offset 1 - ProjCoordTransGeoKey: CT_TransverseMercator
      key 3076 tiff_tag_location 0 count 1 value_offset 9001 - ProjLinearUnitsGeoKey: Linear_Meter
      key 3077 tiff_tag_location 34736 count 1 value_offset 4 - ProjLinearUnitSizeGeoKey: 1
      key 3080 tiff_tag_location 34736 count 1 value_offset 5 - ProjNatOriginLongGeoKey: 15
      key 3081 tiff_tag_location 34736 count 1 value_offset 6 - ProjNatOriginLatGeoKey: 0
      key 3082 tiff_tag_location 34736 count 1 value_offset 7 - ProjFalseEastingGeoKey: 500000
      key 3083 tiff_tag_location 34736 count 1 value_offset 8 - ProjFalseNorthingGeoKey: 0
      key 3092 tiff_tag_location 34736 count 1 value_offset 9 - ProjScaleAtNatOriginGeoKey: 0.9996
      key 4099 tiff_tag_location 0 count 1 value_offset 9001 - VerticalUnitsGeoKey: Linear_Meter
variable length header record 2 of 3:
  reserved             0
  user ID              'LASF_Projection'
  record ID            34736
  length after header  80
  description          ''
    GeoDoubleParamsTag (number of doubles 10)
      0.0174533 6.37814e+06 298.257 0 1 15 0 500000 0 0.9996
variable length header record 3 of 3:
  reserved             0
  user ID              'LASF_Projection'
  record ID            34737
  length after header  29
  description          ''
    GeoAsciiParamsTag (number of characters 29)
      ETRS89|ETRS89 / UTM zone 33N|
reporting minimum and maximum for all LAS point record entries ...
  X             4265285    5440945
  Y             7506877    8618590
  Z               65704     226846
  intensity           0      65535
  return_number       1          1
  number_of_returns   1          1
  edge_of_flight_line 0          0
  scan_direction_flag 1          1
  classification      0          0
  scan_angle_rank     0          0
  user_data           0          0
  point_source_ID     1          1
  Color R 0 65535
        G 0 65535
        B 0 65535
number of first returns:        67003099
number of intermediate returns: 0
number of last returns:         67003099
number of single returns:       67003099
overview over number of returns of given pulse: 67003099 0 0 0 0 0 0
histogram of classification of points:
        67003099  never classified (0)`

**Any ideas?**

**Comment by abellgithub** [comment]
I assume that you've just run out of memory.  The next version of PDAL will use what we call "stream mode" to reduce memory consumption when running `pdal info`.
