### ISSUE TITLE
Error in coding for legacy return count in writers.las

### ISSUE THREAD

**Issue by abellgithub** [PDAL/PDAL#2235]
The LAS spec says that legacy values should be set to 0 if the actual values exceed the size allowed in version 1.4.  We currently set legacy point counts to the maximum value supported rather than 0 in these cases.

**Comment by leavauchier** [comment]
Hello, 
Thank you all for releaseing and maintaining PDAL!

Is fixing this issue in the plans for a future release?
It should also be 0 when version is 1.4 and dataformat is >=6, which is not the case in writers.las output.

cf. https://www.asprs.org/wp-content/uploads/2019/07/LAS_1_4_r15.pdf page 12
> Legacy Number of Point Records
> This field contains the total number of point records within the file if the file is maintaining legacy
> compatibility, the number of points is no greater than UINT32_MAX, and the Point Data Record
> Format is less than 6. Otherwise, it must be set to zero

**Comment by abellgithub** [comment]
You can submit a PR.

I'm not sure why I didn't change this. Perhaps it's historic in that old versions of PDAL didn't conform.  We are always concerned with introducing modifications that could impact existing users. This is true despite the non-conformance.

LAS as a standard has a problem in that the specification is changed after release without a version increment, though I don't know that this was a factor for this requirement.
