### ISSUE TITLE
readers.rxp: "reflectance_as_intensity" does not work as documented

### ISSUE THREAD

**Issue by sedot42** [PDAL/PDAL#2250]
Hi again, I'm using readers.rxp to extract reflectance values from .rxp-files. It seems like the "reflectance_as_intensity"-option does not work as documented, if set, it scales reflectance from 0 to 65535. 
How to reproduce: Unzip [test file](https://github.com/PDAL/PDAL/files/2493688/rxp_testfile.zip) from #2226. Run the following script:
```python
import pdal

pipeline = pdal.Pipeline("""
{
"pipeline":[
    {
        "type":"readers.rxp",
        "filename":"./rxp_testfile/180417_133121.mon.rxp",
        "sync_to_pps":false,
        "reflectance_as_intensity":true
    }
]
}
""")

pipeline.validate()
count = pipeline.execute()
reflectance_data = pipeline.arrays[0]["Intensity"]
print(f"Read {count} points. " +
      f"Min reflectance: {min(reflectance_data)}. " +
      f"Max reflectance: {max(reflectance_data)}.")
```
Expected behaviour:
`Read 120278 points. Min reflectance: -25. Max reflectance: 5.`
Actual behaviour:
`Read 120278 points. Min reflectance: 0. Max reflectance: 65535.`

**Comment by gadomski** [comment]
It seems like the option is working correctly to me. The `reflectance_as_intensity` option exists primarily for writing to the las format. In las, `Intensity` is a two-byte unsigned integer, meaning that it can contain values from 0 to 65535; there is no `Reflectance` in the las format. The `reflectance_as_intensity` option tells the rxp reader to take reflectance values (which can be negative or positive, and generally are in the domain -25dB to 5dB) and scale them to fit within that unsigned integer field. The math is `intensity = 65535 * (reflectance + 25) / 30`.

For your use-case, I would suggest just using the "Reflectance" attribute directly, e.g.:

```python
reflectance = pipeline.arrays[0]["Reflectance"]
```

**Comment by abellgithub** [comment]
I think this is a documentation issue.  The option read to me as if intensity would be in the range -25 to 5, which isn't the case.  Also, the intensity value is clamped by `min_reflectance` and `max_reflectance` and that's not clear to me from the description.

**Comment by abellgithub** [comment]
Already done.

**Comment by abellgithub** [comment]
We can battle it out.
