### ISSUE TITLE
Error encountered in readers.tindex using shapefile: Unable to open layer 'pdal' from OGR datasource

### ISSUE THREAD

**Issue by d-diaz** [PDAL/PDAL#2256]
```
$ pdal tindex tile_index.shp '*.laz' --t_srs 'EPSG:2992' --a_srs 'EPSG:2992' --fast_boundary --lyr_name 'pdal'
Warning 1: Cannot find pcs.csv
```
I save the following as pipeline.json:
```
{
  "pipeline":[
    {
      "type":"readers.tindex",
      "filename": "tile_index.shp",
      "lyr_name": "pdal"
    },
    {
      "type":"filters.splitter",
      "length":"4000",
      "buffer":"100"
    },
    {
      "type":"writers.las",
      "compression":"laszip",
      "filename":"retiled_#.laz"
    }
  ]
}
```
Then execute:
```
$ pdal pipeline pipeline.json
PDAL: readers.tindex: Unable to open layer 'pdal' from OGR datasource 'tile_index.shp'
```
Computing Environment Specs:
pdal 1.7.2 (git-version: 3e9adb) (installed with conda)
OS: Ubuntu 14.04.4 (trusty)

I do not get this error if I use sqlite for the tindex instead of shapefile...

**Comment by abellgithub** [comment]
What command did you use to create the shapefile?

**Comment by d-diaz** [comment]
The `pdal tindex` command shown at the top of my post.

**Comment by hobu** [comment]
Shapefile is weird in OGR. It's not quite an "OGR Datasource" and OGR treats it more like a directory. Clients have to do special things when they're working with a shapefile-based "OGR Datasource", and PDAL likely isn't doing the right thing here.

I would work around by using sqlite to write your tindex and then use `ogr2ogr` to convert that to a shapefile.

**Comment by abellgithub** [comment]
Closing in favor of #2269
