### ISSUE TITLE
How to fill holes in DTM?

### ISSUE THREAD

**Issue by jhacsonmeza** [PDAL/PDAL#2258]
I have a point cloud from a neighborhood in LAS format and I need to generate a DTM (removing houses and trees). Yesterday I found PDAL and with the following pipepeline

```
{
  "pipeline":[
    {
      "type":"filters.assign",
      "assignment":"Classification[:]=0"
    },
    {
      "type":"filters.elm"
    },
    {
      "type":"filters.outlier"
    },
    {
      "type":"filters.smrf",
      "last":true,
      "ignore":"Classification[7:7]",
      "slope":0.05,
      "window":16,
      "threshold":0.45,
      "scalar":1.2
    },
    {
      "type":"filters.range",
      "limits":"Classification[2:2]"
    }
  ]
}
```

that I executed with OSGeo4W Sheel, I got this

![results](https://user-images.githubusercontent.com/29784391/47730548-68d30180-dc30-11e8-8998-bc57aa33e2ef.png)

Then, I used this pipeline

```
{
    "pipeline": [
        "op3.las",
        {
            "filename":"dtm1.tif",
            "gdaldriver":"GTiff",
            "output_type":"all",
            "resolution":"0.5",
            "type": "writers.gdal"
        }
    ]
}
```

based on this [exercise](https://pdal.io/workshop/exercises/analysis/dtm/dtm.html) to generate a DTM, but the gaps are not filled. 

![hillshade](https://user-images.githubusercontent.com/29784391/47738268-cd965800-dc40-11e8-8b8e-5e455e65f7dc.png)

Is there a way to fill gaps with PDAL for generating a DTM?

**Comment by abellgithub** [comment]
Your first pipeline asks to filter out all points that aren't classified as "ground".  I'm not sure what you're trying to do when you say "fill gaps".  I suppose you have cells in your raster that are set to the "nodata" value.  You can set this value to any you wish by adding ```"nodata" : <some number>,``` to the `writers.gdal` stage in your second pipeline.

**Comment by jhacsonmeza** [comment]
When I say fill gaps I'm talking about doing something like this

![dtm-dsm](https://user-images.githubusercontent.com/29784391/47743022-ff60ec00-dc4b-11e8-84c4-23248c8c205c.png)

Where houses and trees are removed. I do not know if the way I did it is the right one. The idea is to generate a DTM based on the LAS file where there are houses and trees (DSM).

**Comment by chambbj** [comment]
If you want the DSM, you need to remove the range filter in your first
pipeline, as Andrew has suggested.

**Comment by jhacsonmeza** [comment]
I need the DTM only.

**Comment by abellgithub** [comment]
I don't think we have a way to do this, exactly.  You could increase the `window_size` in `writers.gdal`, which will attempt to fill "nodata" areas with data inferred from valid cells.  This may not be adequate.  I don't believe we have an algorithm developed specifically to fill points removed as "non-ground".
