### ISSUE TITLE
undefined reference to pdal::LazPerfDecompressor

### ISSUE THREAD

**Issue by rmam-spinworks** [PDAL/PDAL#2260]
While trying to build entwine v1.3.0 I've stumbled on a build error caused by an undefined reference to `pdal::LazPerfDecompressor`.

The same build error was previously covered in an issue reported to entwine (see https://github.com/connormanning/entwine/issues/126).

After some digging I've noticed that in PDAL v1.7.2 the source file compression/LazPerfCompression.cpp is conditionally added to the build if the lazperf library is not used.  (check CMakeLists.txt:241)  However, the build process does include the header file `compression/LazPerfCompression.hpp` either way.  

Therefore, if PDAL is built without lazperf then LazPerfCompression.hpp will be included in the build although LazPerfCompression.cpp is left out, thus LazPerfCompression is left undefined.

**Comment by abellgithub** [comment]
It would be good if you would post the errors that you're encountering.

Including the header file shouldn't introduce undefined references.

**Comment by rmam-spinworks** [comment]
@abellgithub fair enough, here's the error message outputted while building Entwine 1.3.0 with PDAL v1.7.2 on Ubuntu 16.04.  PDAL was built from source with `WITH_LAZPERF=ON`, `Lazperf_DIR` pointing to an installation of laz-perf 1.3.0 but with PDAL marking lazperf as not found.

```
<snip/>
[ 72%] Linking CXX executable entwine
../libentwine.so.1.3.0: undefined reference to `pdal::LazPerfDecompressor::LazPerfDecompressor(std::function<void (char*, unsigned long)>, std::vector<pdal::DimType, std::allocator<pdal::DimType> > const&, unsigned long)'
../libentwine.so.1.3.0: undefined reference to `pdal::LazPerfCompressor::LazPerfCompressor(std::function<void (char*, unsigned long)>, std::vector<pdal::DimType, std::allocator<pdal::DimType> > const&)'
collect2: error: ld returned 1 exit status
kernel/CMakeFiles/kernel.dir/build.make:202: recipe for target 'kernel/entwine' failed
make[2]: *** [kernel/entwine] Error 1
CMakeFiles/Makefile2:660: recipe for target 'kernel/CMakeFiles/kernel.dir/all' failed
make[1]: *** [kernel/CMakeFiles/kernel.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by abellgithub** [comment]
I'm guessing that you just aren't finding the installed lazperf on your system.  Take a look at the output from cmake of pdal.  On mine, with lazperf not found, I get:

```
CMake Warning at cmake/lazperf.cmake:4 (find_package):
  By not providing "FindLazperf.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Lazperf", but
  CMake did not find one.

  Could not find a package configuration file provided by "Lazperf" with any
  of the following names:

    LazperfConfig.cmake
    lazperf-config.cmake

  Add the installation prefix of "Lazperf" to CMAKE_PREFIX_PATH or set
  "Lazperf_DIR" to a directory containing one of the above files.  If
  "Lazperf" provides a separate development package or SDK, be sure it has
  been installed.
```

When you run cmake for PDAL, you'll have to make sure the Lazperf_DIR variable is properly set if you're not installing lazperf in a cmake standard location.  For example, installing lazperf to /home/acbell/lazperfinstall, I used:

`cmake -G Ninja .. -DLazperf_DIR=/home/acbell/lazperfinstall/lib/cmake/lazperf`

With this done, LazPerfCompression is built (I tested on Ubuntu 16.04). You can verify by checking your PDAL build directory for `LazPerfCompression.cpp.o`.

Hope this helps,

_Withholding my feelings about "modern" cmake, kind of_

**Comment by abellgithub** [comment]
I'll make a change so that the PDAL build fails if WITH_LAZPERF is ON but lazperf isn't found.  It's easy to miss the warnings as they fly by.

**Comment by rmam-spinworks** [comment]
@abellgithub yes that's essentially the problem: if lazperf is not found even though the `Lazperf_DIR` is set, PDAL's build breaks by not removing declarations from the build (i.e. LazPerfCompression.hpp) when definitions are removed (i.e. LazPerfCompression.cpp).  

When this problem occurs, PDAL is built while including LazPerfCompression.hpp but omitting LazPerfCompression.cpp,  which causes all the undefined references. 

In this scenario, as PDAL also installs LazPerfCompression.hpp, applications that include PDAL (such as Entwine) will be able to include LazPerfCompression.hpp but their build will throw undefined reference errors due to the way PDAL was built.

Therefore this issue actually refers to two distinct problems:

* PDAL should not include (in the build and in the installation) declarations of components whose definitions are intentionally removed from the project (this triggers undefined references)

* failing to find an optional component that was intentionally added by the user should throw an error.

There is also a third (relatively minor) problem with PDAL's build: PDAL's lazperf.cmake routine fails to find lazperf even when users specify the exact directory where it is installed.  Currently, lazperf.cmake is only able to detect a lazperf installation if users set `lazperf_DIR` directly to the path where lazperf's cmake modules are stored (i.e. ~/foo/lazperf-1.3.0/lib/cmake/lazperf), and otherwise fails if lazperf's directory is set (i.e. ~/foo/lazperf-1.3.0).  IIRC this type of issue may be mitigated if `Lazperf_DIR` is passed to `find_package` as a hint.

**Comment by abellgithub** [comment]
I don't understand what you're saying anymore.  Including LazPerfCompression.hpp has nothing to do with undefined references.  You'll need to specifically restate your problem if you're still seeking help.

**Comment by rmam-spinworks** [comment]
@abellgithub correct me if I'm wrong but isn't the "undefined reference" compilation problem caused by providing only declarations (i.e., the contents of LazPerfCompression.hpp) while providing no definition (i.e., the contents of LazPerfCompression.cpp)?  

This sounds like PDAL's problem.  When lazperf is not found then LazPerfCompression.cpp is removed from the build,  yet PDAL still bundles LazPerfCompression.hpp in its installation process.  Therefore, when PDAL users install PDAL without lazperf they'll end up installing LazPerfCompression.hpp, and consequently when they try to compile PDAL they trigger the "undefined reference" problem I've mentioned previously. 

Don't you agree?

**Comment by abellgithub** [comment]
No.  Declaring functions (or names in general) doesn't generate any dependency.  Try building this:

```
#include <iostream>

int foo();

int main()
{
    std::cerr << "Hello, world!\n";
}
```

This will build and run despite `foo()` never being defined.  Whether `int foo();` is in a header file or directly in source is irrelevant.

Unless you attempt to use a function from LazPerfCompression.hpp you'll get no link error from including the header file LazPerfCompression.hpp.

Entwine DOES use the constructor from LazPerfCompression, so the definition needs to be present in some library.  PDAL will build this constructor (and all the code in LazPerfCompression.cpp) if it can find it.  You can check that it was indeed built by looking in the build directory for `LazPerfCompression.cpp.o`.  You can make sure that it was included in the library by searching for it in the pdalcpp library:


```
(pdal) master $ nm lib/libpdalcpp.dylib | c++filt | grep LazPerfCompressor | head 2>&1
0000000000290ef0 T pdal::LazPerfCompressor::done()
0000000000290ea0 T pdal::LazPerfCompressor::compress(char const*, unsigned long)
0000000000290cd0 T pdal::LazPerfCompressor::LazPerfCompressor(std::__1::function<void (char*, unsigned long)>, std::__1::vector<pdal::DimType, std::__1::allocator<pdal::DimType> > const&)
...
```

The only issue that I can see at this point is the the PDAL build doesn't stop if WITH_LAZPERF is ON but LAZperf can't be found.  Instead, only a warning is issued.

**Comment by connormanning** [comment]
I think this all boils down to the desire for this error to occur at compile time (that no laz-perf headers should be installed if the laz-perf lib code isn't also going to be installed) rather than link time.

**Comment by abellgithub** [comment]
Yes, that could be done.

**Comment by abellgithub** [comment]
Actually, it appears we're already doing this:

```
if (NOT PDAL_HAVE_LAZPERF)
    set(LAZPERF_EXCLUDES PATTERN pdal/compression/LazPerf* EXCLUDE)
endif()
```

I can verify the packaging.

**Comment by rmam-spinworks** [comment]
@abellgithub 

> Unless you attempt to use a function from LazPerfCompression.hpp you'll get no link error from including the header file LazPerfCompression.hpp.

That's the whole point.  If PDAL is built without lazperf then LazPerfCompression.hpp will ship anyway, but LazPerfCompression.cpp is not compiled as its removed from the build.  Therefore when PDAL is built and packaged without lazperf, it still ships with LazPerfCompression.hpp although no definition is provided for the stuff declared in it. 

Correct me if I'm wrong but if failing to find lazperf triggers a removal of LazPerfCompression.cpp then shouldn't  LazPerfCompression.hpp be removed as well, at least from the install?

**Comment by abellgithub** [comment]
I've just tested the installation, and it seems to work fine.  LazPerfCompression.hpp is not installed if LAZperf wasn't built.  If you have an instance where a `make install` installs `pdal/compression/LazPerfCompression.hpp` when LAZperf was found, please provide details of the configuration and installation.

**Comment by rmam-spinworks** [comment]
@abellgithub that's not the result I'm seeing.  I've just tested PDAL 1.7.4 in Ubuntu 16.04 (`WITH_LAZPERF` option set to OFF, installed files to /tmp/pdal-without/lazpref) and the install copies LazPerfCompression.hpp to the destination folder.

[CMakeCache.txt](https://github.com/PDAL/PDAL/files/2543277/CMakeCache.txt)
[installed_files.txt](https://github.com/PDAL/PDAL/files/2543284/installed_files.txt)

**Comment by abellgithub** [comment]
I think you're going to have to debug this yourself, as I can't recreate the issue.  I'd check the value of PDAL_HAVE_LAZPERF and see what's happening in the install portion of the build.

**Comment by rmam-spinworks** [comment]
@abellgithub fair enough.  Currently I don't have much free time but I'll report back if I find anything.

**Comment by hobu** [comment]
Is this closeable?
