### ISSUE TITLE
tindex writes polygon with insufficient precision when using fast_boundary option

### ISSUE THREAD

**Issue by rphillips91** [PDAL/PDAL#2271]
I used this command to attempt to create a simple tile index for a couple of LAS files;

`pdal tindex --tindex "C:\a\test_two\index_tile.shp" --filespec "C:\a\test_two\*.las" -f "ESRI Shapefile" --t_srs "EPSG:2193"`

This is what my output looked like;
![index_tile.shp](https://user-images.githubusercontent.com/36900458/48176358-86ad0e80-e374-11e8-9d3c-31722ca20495.png)

I've shown all the points for one of these input LAS files in the picture below, the index tile doesn't follow the data extent or give the minimum rectangular bounding boxes, also none of my input LAS files overlap. 

![LAS File compared to its tile index](https://user-images.githubusercontent.com/36900458/48176541-65005700-e375-11e8-94c4-bd33695b4aae.png)

Have I written the command wrongly or is this a limitation of pdal tindex?

**Comment by hobu** [comment]
PDAL's boundary computation is provided by [`filters.hexbin`](https://pdal.io/stages/filters.hexbin.html), which tesellates the domain and cumulates a boundary of the tessellation. The overlap you are seeing is from the default tessellation cells being rather large. You can control them with `filters.hexbin` settings, but I suspect what you would rather have is something like [lasboundary](https://rapidlasso.com/lastools/lasboundary/) delaunay triangulation output. PDAL has just gotten a `filters.delaunay` filter to do that (very likely at a much slower pace than the LAStools' utility), but it is not connected to tools like `pdal tindex` at this time.

**Comment by hobu** [comment]
oops. I forgot to add that you control these options with something like this:

```
pdal tindex --filters.hexbin.edge_size=10 \
                    --filters.hexbin.threshold=1 \
                    index.sqlite "*.las" -f "SQLite" \
                    --lyr_name "pdal" \
                    --t_srs "EPSG:4326"
```

**Comment by rphillips91** [comment]
Thank you @hobu for the heads up, really good to understand. Hi @abellgithub I looked at pdal tile and since it only creates square tiles , I assumed it would not be the command to use to grab the bounding boxes of the LAS tiles, or generate something very similar to that? Apologies if I'm wrong, a bit of a rookie with pdal.

**Comment by abellgithub** [comment]
If all you're trying to do is get bounding boxes, you can run `pdal info` on the files.

**Comment by rphillips91** [comment]
I'm trying to create an index tile shapefile of a list of LAS files consisting of their bounding boxes. 
If that's not possible my second attempt is to find a way to create an index tile made up of the files' point extent, set up so that the output is a close match to the general shape of the file. 

Will try out @hobu's suggesting for lasboundary delaunay triangulation, I think that's what I'm after if I can't find out a way to just a get collection of bounding boxes in a shapefile.

**Comment by hobu** [comment]
The `--fast_boundary` option of `pdal tindex` will give you just a box rather than the `filters.hexbin` output. See the docs at https://pdal.io/apps/tindex.html for more

**Comment by rphillips91** [comment]
Thank you @hobu for the heads up. I've used this command;

`pdal tindex --tindex "F:\sample_lidar_data\LAZ_index_tile.shp" --fast_boundary --filespec "F:\sample_lidar_data\LAZ\*.laz" -f "ESRI Shapefile" --t_srs "EPSG:2193"`

It seems like it generates an estimation of the bounding boxes? Please see the second image for the discrepancy between the tile index extent and the points. Do you know of a way that pdal can create a shapefile with all the bounding boxes of the input LAS files (directly from extents I'm guessing)?

![overall_shapefile](https://user-images.githubusercontent.com/36900458/48229571-582f4200-e40d-11e8-8c99-8526660ea5e1.png)

![smaller_scale_detail](https://user-images.githubusercontent.com/36900458/48229610-76953d80-e40d-11e8-8c70-6d68261d2772.png)

**Comment by hobu** [comment]
`--fast_boundary` takes its bounds from whatever the file provides. If the file is providing bad boundary information, it will be reflected.

**Comment by rphillips91** [comment]
Thank you so much for the confirmation. Will be looking at this LAS file that's been supplied!

**Comment by abellgithub** [comment]
What is your intimate goal?

**Comment by rphillips91** [comment]
To create an index tile of the LAS files, and run some geometry predicates to make sure there are no gaps and overlaps between tiles. For Quality Checking Processed LiDAR Data.

**Comment by rphillips91** [comment]
Hi guys, just checked the bounding boxes in the metadata for the file that had overlapping points with pdal tindex using the `--fast_boundary` switch (grey line) and compared this with the lastools command (red line) 

`lasboundary.exe -i C:\a\sample_data\LAZ\CL2_BP25_2016_2000_0816.laz -use_bb -o C:\a\sample_data\LAZ\CL2_BP25_2016_2000_0816_lasb_tileindex.shp`

![comparing lastools to pdal](https://user-images.githubusercontent.com/36900458/48300748-af393200-e547-11e8-9e17-8ca363ea0677.png)

It seems like the lasboundary command is picking up the extents from the metadata, unlike the pdal output? I cross checked the boundary of the lasboundary output (in red) with the metadata of the LAS file and they seem to be the same. 

![comparing_lasboundary_boundingbox_withmetadataoffile](https://user-images.githubusercontent.com/36900458/48300929-8e261080-e54a-11e8-95d5-f14d29bcde2a.png)

As lasboundary does not have an open source licence for this command, was wondering if pdal had this capability? Many thanks

**Comment by abellgithub** [comment]
LAS files have metadata in the header to show the bounding box of the points.  That data can be wrong.  You should run `lasinfo` or `pdal info` to check this.  Here's an example with `lasinfo`:

```
(pdal) $ bin/lasinfo ~/pdal/test/data/las/autzen_trim.las
lasinfo (181001) report for '/Users/acbell/pdal/test/data/las/autzen_trim.las'
reporting all LAS header entries:
  file signature:             'LASF'
  file source ID:             0
  global_encoding:            0
  project ID GUID data 1-4:   00000000-0000-0000-0000-000000000000
  version major.minor:        1.2
  system identifier:          'PDAL'
  generating software:        'PDAL 1.0.0 (9e8465)'
  file creation day/year:     253/2015
  header size:                227
  offset to point data:       2038
  number var. length records: 5
  point data format:          3
  point data record length:   34
  number of point records:    110000
  number of points by return: 99257 9021 1623 99 0
  scale factor x y z:         0.01 0.01 0.01
  offset x y z:               0 0 0
  min x y z:                  636001.76 848935.20 406.26
  max x y z:                  637179.22 849497.90 520.51
...
reporting minimum and maximum for all LAS point record entries ...
  X            63600176   63717922
  Y            84893520   84949790
  Z               40626      52051
```

In this case the values match (after applying scale and offset). `pdal tindex` with `--fast_boundary` takes its values from the header (this is what makes it fast :)  It looks like this value is incorrect for the file you're having difficulty with.  If this is the case, you should contact your data provider.  `pdal tindex` provides no option to use the actual bounding box (rather than the reported one) for LAS files.

**Comment by abellgithub** [comment]
You can also use pdal to create a copy of the file with the bad extent:

`pdal translate --writers.las.foward=all in.las out.las`

**Comment by rphillips91** [comment]
Thank you for the heads up @abellgithub;

I've run `pdal translate --writers.las.foward=all in.las out.las` and the output has the same extent, scale but different offset in the header as what was in the original file metadata (and also the lasboundary output that corresponded with the point extent, please see image above).

I've also re-run the command `pdal tindex --tindex "F:\sample_lidar_data\LAZ_index_tile.shp" --fast_boundary --filespec "F:\sample_lidar_data\LAZ\*.laz" -f "ESRI Shapefile" --t_srs "EPSG:2193"` on the `pdal translate` output. The same shapefile extents are given;

![image](https://user-images.githubusercontent.com/36900458/48309933-8c128f00-e5e8-11e8-9396-9eaaf39f1cbf.png)

I'm not sure what is happening here, as the offset has been changed using pdal translate, but when running pdal tindex on this new file, it gives me the same bounding box. 

[Note: I've double checked the lasboundary documentation on the `-usebb` switch, [http://www.cs.unc.edu/~isenburg/lastools/download/lasboundary_README.txt](lasboundary_documentation) and it seems to just read it from the header too.]



*pdal translate output lasinfo report* 
```
C:\lastools\LAStools-master\bin>lasinfo.exe C:\a\sample_data\LAZ\CL2_BP25_2016_2000_0816_pdal_output.laz
lasinfo (180907) report for 'C:\a\sample_data\LAZ\CL2_BP25_2016_2000_0816_pdal_output.laz'
reporting all LAS header entries:
  file signature:             'LASF'
  file source ID:             0
  global_encoding:            0
  project ID GUID data 1-4:   00000000-0000-0000-0000-000000000000
  version major.minor:        1.3
  system identifier:          'LAStools (c) by rapidlasso GmbH'
  generating software:        'las2las (version 170203)'
  file creation day/year:     97/2017
  header size:                235
  offset to point data:       535
  number var. length records: 3
  point data format:          1
  point data record length:   28
  number of point records:    15969750
  number of points by return: 5677988 4781574 3172153 1558943 572692
  scale factor x y z:         0.01 0.01 0.01
  offset x y z:               0 0 0
  min x y z:                  1602546.50 5466480.00 24.73
  max x y z:                  1603359.99 5467919.99 305.76
  start of waveform data packet record: 0
...
reporting minimum and maximum for all LAS point record entries ...
  X           160254650  160335999
  Y           546648000  546791999
  Z                2473      30576
```

**Comment by rphillips91** [comment]
That's what I did previously, did the process again, to double check;

```
(myenv) C:\Users\rphillips>pdal tindex --tindex "C:\a\sample_data\LAZ\LAZ_index_tile_BP25_0816.shp" --fast_boundary --filespec "C:\a\sample_data\LAZ\CL2_BP25_2016_2000_0816_pdal_output.laz" -f "ESRI Shapefile" --t_srs "EPSG:2193"
Warning 6: Field modified create as date field, though DateTime requested.
Warning 6: Field created create as date field, though DateTime requested.
Warning 1: Cannot find pcs.csv

(myenv) C:\Users\rphillips>
```

This is the pdal translate laz output with the pdal tindex generated with the --fast_boundary switch 

![image](https://user-images.githubusercontent.com/36900458/48317829-d2a1d100-e65c-11e8-9921-df2f71da63ba.png)


Here's a link to the original file, pdal output and pdal tindex output, would be really great to find out where I've gone wrong. Many thanks

https://drive.google.com/drive/folders/18t9swg3BrCPKCfxv71DLO2x98weBwH54

**Comment by abellgithub** [comment]
This is an error in the precision with which the data is being written.

**Comment by rphillips91** [comment]
Hi @abellgithub thank you for addressing this issue. Will this new commit be installed if I ran `conda update pdal` in myenv in anaconda?

Used this command and ran pdal tindex again with the same parameters, and had the same issue with my output.

**Comment by hobu** [comment]
If you can use docker, you can obtain the latest build from using the `pdal/ubuntu:master` docker container, which is regenerated with every merge of the master.

**Comment by rphillips91** [comment]
Thank you so much for the heads up. I've never been able to get Docker to work on my Windows 10 Pro computer (with admin rights). Tried twice before, following instructions, it doesn't seem to install the pdal packages properly. I assumed there were always issues and that's why the package manager was changed to conda in the quickstart guide in pdal.io website?

I'll try and install docker again, when I have the time, but not too optimistic that I can get it to work sorry.
