### ISSUE TITLE
pdal merge output different LAS version to input files

### ISSUE THREAD

**Issue by rphillips91** [PDAL/PDAL#2272]
I have merged a couple of LAs files in LAS 1.4 format using pdal merge and noticed my larger output file is in LAS 1.2 format. Is it possible to preserve the file format using this command?

**Comment by hobu** [comment]
Please use the [mailing list](https://pdal.io/community.html#mailing-list) for questions and reserve github for bug ticket traffic. #2271 is a good enough bug insofar as the docs aren't clear on what you should be expecting for output.

For this issue, you need to be adjusting your `writers.las` `dataformat_id` as appropriate. Alternatively, use the `forward` option of `writers.las` to carry forward the options while you convert from 1.2 to 1.4. See https://pdal.io/stages/writers.las.html for more details.
