### ISSUE TITLE
SMRF/PMF filters don't properly handle reset of returns option

### ISSUE THREAD

**Issue by abellgithub** [PDAL/PDAL#2275]
If a point table has no ReturnNumber or NumberOfReturns dimension, the filters attempt to reset the returns argument, but it is done incorrectly: it sets it to the empty string instead of clearing the string list.

**Comment by luipir** [comment]
In case working with an old PDAL version this is an override of this issue.
e.g. create fake dimensions!

   {
        "type": "filters.ferry",
        "dimensions": "=>ReturnNumber, =>NumberOfReturns" 
    },
    {
        "type": "filters.assign",
        "assignment": "NumberOfReturns[:]=1"
    },
    {
        "type": "filters.assign",
        "assignment": "ReturnNumber[:]=1"
    },
