### ISSUE TITLE
hub.docker.com pdal/pdal:1.8 build passes but GDAL is missing

### ISSUE THREAD

**Issue by adamsteer** [PDAL/PDAL#2278]
pdal/pdal:1.8 is passing builds on hub.docker.com, but PDAL itself doesn’t appear to be built in the image. Logs here:

https://hub.docker.com/r/pdal/pdal/builds/b29fvgpjsdjc9tnq75aktrd/

report that building PDAL failed:

```
[91mFindGDAL.cmake: gdal-config not found. Please set it manually: GDAL_CONFIG=GDAL_CONFIG-NOTFOUND
CMake Error at cmake/gdal.cmake:12 (message):
  GDAL support is required
Call Stack (most recent call first):
  CMakeLists.txt:117 (include)

[0m
-- Could NOT find GDAL (missing: GDAL_LIBRARY GDAL_INCLUDE_DIR) (Required is at least version "1.9.0”)
-- Configuring incomplete, errors occurred!
See also "/pdal/build/CMakeFiles/CMakeOutput.log".

[91mninja: error: loading 'build.ninja': No such file or directory
[0m
```

Attempting to run the image results in:
```
docker run -it pdal/pdal:1.8 pdal --version
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"pdal\": executable file not found in $PATH": unknown.
```

**Comment by abellgithub** [comment]
Not sure why this didn't run on docker hub.  I built/tested locally right before it got pushed.

I'm not sure you're running the correct Dockerfile locally.

You can use pdal/ubuntu if you need a 1.8 image.

**Comment by adamsteer** [comment]
OK. pdal/ubuntu 1.8 runs!

I’m trying to build locally:

/PDAL/scripts/docker/Dockerfile

thanks!

**Comment by adamsteer** [comment]
closing, the standard docker build is working now. many thanks!
