### ISSUE TITLE
Conda installs pdal ver.1.7.2 instead of 1.8.0 on windows

### ISSUE THREAD

**Issue by tanisha11** [PDAL/PDAL#2279]
On using the command, 'conda install -c conda-forge pdal python-pdal' in a conda virtual environment on windows, the older version 1.7.2 is installed. Even on doing a 'conda update pdal', it does not upgrade to 1.8.0.

**Comment by hobu** [comment]
https://github.com/conda-forge/python-pdal-feedstock/pull/7 attempts to fix this.

**Comment by hobu** [comment]
Should be fixed now. We still have an issue to fix an old python-pdal on OSX that we are working.
