### ISSUE TITLE
get extra dimension names

### ISSUE THREAD

**Issue by appanacca** [PDAL/PDAL#2282]
Hello everyone !
As far as I know there is not way in the current state of PDAL c++ api to get the names of all the extra dimensions written in a LAS file.

It seems to me that the information is stored in the "PointLayout" class, in particular in the "m_propIds" member.

I have modified the class adding the method:

`<pre>   
std::map&lt;std::string, Dimension::Id&gt; getMapExtraDims() <font color="#87FFAF">const</font> {
        <font color="#FCE94F">return</font> m_propIds;
    }

</pre>`

and I have tested that it works for my use.

However I would like to know if there an other way to do it without modifying the class.
If not, are the maintainers of PDAL interested in this feature to be merged ?
Thank you !

**Comment by abellgithub** [comment]
What is the use case for this?

**Comment by appanacca** [comment]
I have a complex machine learning pipeline and I write some features as external field in a LAS.
Afterwards I will want to get the names of these features directly from the file. My idea was to avoid to copy around some extra custom config files and/or hardcode these names in different parts of my code.

**Comment by abellgithub** [comment]
You can do the same thing you've proposed by comparing any dimension ID to Dimension::PROPRIETARY.  Any dimension >= Dimension::PROPRIETARY would be a non-registered dimension.

You should take care, though, because proprietary dimensions are not necessarily the same as those stored as extra bytes in LAS.  Many dimensions are registered with PDAL that aren't defined by the LAS spec.  If you want to fetch the actual names of dimensions in a LAS file containing an extra bytes VLR, you can do something like this:

```
LasReader r;
r.preview();

LasHeader&h = r.header();
LasVLR* vlr = h.findVlr(SPEC_USER_ID, EXTRA_BYTES_RECORD_ID);
size_t size = vlr->dataLen();
const char *data = vlr->data();
size_t pos = 4; // Offset to name
while (pos < size)
{
    std::string name(data + pos, 32);  // LAS dimension names are 32 bytes long.
    pos += 192;  // Size of dimension data.
}
```

**Comment by appanacca** [comment]
> Many dimensions are registered with PDAL that aren't defined by the LAS spec. 

Can you make an example ?

**Comment by abellgithub** [comment]
I don't know how you're constructing your LAS file, so I'm not sure I can help much more.

**Comment by appanacca** [comment]
I have copied to you part of the code used to write the las file. Let me know if it helps:


```
        std::string filePath;
        pdal::PointTable table;
        std::shared_ptr<pdal::PointView> view;
        std::string srsWkt;
        double xOffset, yOffset, zOffset;
        double xScale, yScale, zScale;

 pdal::Dimension::IdList ids = {
            dimId::X,
            dimId::Y,
            dimId::Z,
            dimId::Red,
            dimId::Green,
            dimId::Blue,
            dimId::Classification,
    };
    table.layout()->registerDims(ids);

using typeMap = std::map<std::string, std::string>;
        typeMap userData = ....;


 for(auto& userDim: userData){
            table.layout()->registerOrAssignDim(userDim.first, pdal::Dimension::type(userDim.second));
        }

    view = std::make_shared<pdal::PointView>(table);

Eigen::Matrix3Xd &coordinates = ....

    for (pdal::PointId idx = 0; idx < coordinates.cols(); idx++) {
        view->setField<double>(dimId::X, idx, coordinates(0, idx));
        view->setField<double>(dimId::Y, idx, coordinates(1, idx));
        view->setField<double>(dimId::Z, idx, coordinates(2, idx));
    }

  auto extraDim = table.layout()->findProprietaryDim(dimName);
 for (pdal::PointId idx = 0; idx < data.cols(); idx++) {
        view->setField(extraDim, idx, data(idx));
    }

  pdal::Options options;
    options.add("filename", filePath);
        options.add("a_srs", srsWkt);
        options.add("offset_x", xOffset);


std::string extraDim;
        for(auto& userDim: userData){
            extraDim += userDim.first+"="+userDim.second+",";
        }
        extraDim.pop_back();
        options.add("extra_dims", "all");

  pdal::BufferReader reader;
    reader.addView(view);
    pdal::StageFactory factory;
    pdal::Stage *writer = factory.createStage("writers.las");
    writer->setInput(reader);
    writer->setOptions(options);
    writer->prepare(table);
    writer->execute(table);


```

**Comment by abellgithub** [comment]
I didn't know you were using PDAL to create your LAS file.  The PDAL LasWriter always writes the LAS extra bytes VLR when there are extra bytes dimensions specified, so the code I provided above should get the dimension information you want.

**Comment by appanacca** [comment]
I already tested your code and it works for me.
I consider the issue closed, thank you !

**Comment by Alex000821** [comment]
Hello, I'd like to ask if the current version of Padl supports reading additional fields from LAS files. I tried adding "extra_dims" with the value "all" using input_opts.add("extra_dims", "all");, but encountered an error when executing las_reader.prepare(inputtable);.
