### ISSUE TITLE
1.8.0 build fail 

### ISSUE THREAD

**Issue by appanacca** [PDAL/PDAL#2289]
Building  the 1.8.0 version of PDAL I get the following error at the end:
```
100%] Linking CXX executable ../bin/pdal

lib/libpdal_base.so.8.0.0: undefined reference to `pdal::arbiter::fs::LocalHandle::~LocalHandle()'
lib/libpdal_base.so.8.0.0: undefined reference to `pdal::arbiter::Endpoint::get(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) const'
lib/libpdal_base.so.8.0.0: undefined reference to `pdal::arbiter::Endpoint::prefixedRoot[abi:cxx11]() const'
lib/libpdal_base.so.8.0.0: undefined reference to `pdal::arbiter::http::Pool::~Pool()'
lib/libpdal_base.so.8.0.0: undefined reference to `pdal::arbiter::Arbiter::Arbiter()'
lib/libpdal_base.so.8.0.0: undefined reference to `pdal::arbiter::Endpoint::getLocalHandle(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) const'
lib/libpdal_base.so.8.0.0: undefined reference to `pdal::arbiter::Endpoint::getBinary(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) const'
lib/libpdal_base.so.8.0.0: undefined reference to `pdal::arbiter::Arbiter::getEndpoint(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) const'
```
I am using Ubuntu 18 and gcc7.3; these are my cmake configurations:
`
 cmake .. -G "Unix Makefiles"         -DCMAKE_BUILD_TYPE=Release         -DCMAKE_MAKE_PROGRAM=make         -DWITH_LAZPERF=ON       -DCMAKE_INSTALL_PREFIX=/myinstall
`

Do you have any idea on the problem ?
Thanks

**Comment by hobu** [comment]
The issue is libstdc++ vs libc++ and the mixing of the two. PDAL is likely setting `-std=c++11` or similar, and this may not be what you want for gcc 7.3.

**Comment by hobu** [comment]
https://github.com/PDAL/python/pull/17 had some traffic related to this too. I think PDAL needs to use the CMake facilities for setting the standard library linkage. I thought we had cleaned all of the manual `-std=c++11` entries in the configuration, but maybe something has been missed, or maybe it is in the arbiter vendor code compilation unit only.

**Comment by abellgithub** [comment]
I think it's something different.  Arbiter is built as a static lib and should be included in libpdalcpp.  It seems that arbiter isn't getting built (because of no curl?), but there is a reference from a header file that is apparently not properly guarded.

If you could upload the entire build log, that would be helpful.

**Comment by hobu** [comment]
ah yes, quite possible. I saw `std::__cxx11::basic_string` and gcc 7.3 and jumped to (misery remembering) conclusions.

**Comment by appanacca** [comment]
-- The CXX compiler identification is GNU 7.3.0
-- The C compiler identification is GNU 7.3.0
-- Check for working CXX compiler: /usr/bin/g++
-- Check for working CXX compiler: /usr/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found GDAL: /home/nicola/gdal-2.2.2/myinstall/lib/libgdal.so (Required is at least version "1.9.0") 
-- Found GeoTIFF: /usr/lib/x86_64-linux-gnu/libgeotiff.so  
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- Found JSONCPP: /usr/lib/x86_64-linux-gnu/libjsoncpp.so (Required is at least version "1.6.2") 
-- Found LibXml2: /usr/lib/x86_64-linux-gnu/libxml2.so (found version "2.9.4") 
-- Could NOT find CURL (missing: CURL_LIBRARY CURL_INCLUDE_DIR) 
-- Could NOT find LIBEXECINFO (missing: LIBEXECINFO_LIBRARY) 
-- Could NOT find LIBUNWIND (missing: LIBUNWIND_LIBRARY LIBUNWIND_INCLUDE_DIR) 
-- The following OPTIONAL packages have been found:

 * Lazperf
 * JSONCPP (required version >= 1.6.2)
 * PkgConfig
 * LibXml2

-- The following REQUIRED packages have been found:

 * GDAL (required version >= 1.9.0)
   Provides general purpose raster, vector, and reference system support
 * GEOS (required version >= 3.3)
   Provides general purpose geometry support
 * GeoTIFF
 * Threads, The thread library of the system
 * ZLIB
   Compression support in BPF

-- The following features have been disabled:

 * Bash completion, completion for PDAL command line
 * CPD plugin, Coherent Point Drift (CPD) computes rigid or nonrigid transformations between point sets
 * Delaunay plugin, perform Delaunay triangulation of point cloud
 * GeoWave plugin, Read and Write data using GeoWave
 * I3S plugin, Read from a I3S server or from a SLPK file
 * Greyhound plugin, read points from a Greyhound server
 * Icebridge plugin, read data in the Icebridge format
 * Matlab plugin, write data to a .mat file
 * MrSID plugin, read data in the MrSID format
 * NITF plugin, read/write LAS data wrapped in NITF
 * OpenSceneGraph plugin, read/write OpenSceneGraph objects
 * Oracle OCI plugin, Read/write point clould patches to Oracle
 * PCL plugin, provides PCL-based readers, writers, filters, and kernels
 * PostgreSQL PointCloud plugin, read/write PostgreSQL PointCloud objects
 * SQLite plugin, read/write SQLite objects
 * RiVLib plugin, read data in the RXP format
 * rdblib plugin, read data in the RDB format
 * Python plugin, add features that depend on python
 * MBIO plugin, add features that depend on MBIO
 * FBX plugin, add features that depend on FBX
 * Unit tests, PDAL unit tests

-- The following OPTIONAL packages have not been found:

 * PostgreSQL
 * Curl
 * Libexecinfo
 * Libunwind

-- The following RECOMMENDED packages have not been found:

 * LASzip (required version >= 3.1)
   Provides LASzip compression

-- Configuring done
-- Generating done


It seem as @abellgithub said that curl is missing. However I have already installed via ppa.

**Comment by abellgithub** [comment]
1) Curl isn't being found.  Is it installed somewhere non-standard?  You should post the location of `curl.h` and `libcurl.so`.

2) PDAL should build without curl.  Unless you've explicitly enabled arbiter when curl can't be found, PDAL should build anyway.  To test this, I'd create a new build directory and re-run cmake from scratch.

3) You should check that arbiter has been enabled by looking in `pdal_features.hpp`.  If curl has not been found `PDAL_ARBITER_ENABLED` should NOT be defined in that file after cmake configuration.  In your case, it seems as if `PDAL_ARBITER_ENABLED` has been defined but the arbiter library was never built (because curl wasn't found).

**Comment by mleotta** [comment]
I'm also seeing this issue with PDAL 1.8.0.  I'd like to build without Curl.  How can I work around this issue without Curl?

**Comment by abellgithub** [comment]
What does pdal_features.hpp say WRT arbiter?  What does your cmake run say about finding curl?

**Comment by mleotta** [comment]
pdal_features.hpp says `PDAL_ARBITER_ENABLED` is not defined and CMake says it did not find curl.  I think these are both as expected.  I think the problem is that `io/EptReader.cpp` is still built and includes `arbiter/arbiter.hpp` without any sort of guarding in place with `PDAL_ARBITER_ENABLED`.
