### ISSUE TITLE
Make Kernel::outputHelp protected

### ISSUE THREAD

**Issue by jw3** [PDAL/PDAL#2293]
Would it be possible to make `Kernel::outputHelp` protected to give kernel implementations access to customize the help message?

I have a Kernel that has another level of commands under it, think a docker command structure like run, ps, kill, etc. nested under pdal.  So I say

`pdal mykernel mycommand [options]`

It would be nice to have access to tweak the help message from `pdal mykernel -h`.  With the current Kernel impl I get pretty close to what is needed by parsing the command line and placing some logic in `addSwitches`, but the one thing that eludes me is the usage string

`usage: pdal mykernel [options]` instead of `usage: pdal mykernel command [options]`

Even though I'm close as is, being able to place all the help related stuff in an overridden `outputHelp` would clean things up a lot and allow for a much more native feel of this plugin.

**Comment by abellgithub** [comment]
We try to keep behavior consistent between the various parts of PDAL. The
private interface helps to enforce this. I'd ask why you don't break your
kernel into multiple kernels or use options rather than change standard
syntax.

**Comment by abellgithub** [comment]
If we're going to support this syntax, I think I'd rather make it formally supported.  We have a few commands now that might benefit from subcommands (tindex comes to mind).  What I'd resist is something that is just "do whatever you want."  I find programs with inconsistent interfaces and command organization terribly frustrating, but maybe that's just me.  One layer of subcommands would add sufficient flexibility, I'm thinking.

Comments?

**Comment by jw3** [comment]
From my perspective formal support of subcommands would be ideal.  I'd be happy to test it out in my current work and then use it once finalized.

> One layer of subcommands would add sufficient flexibility, I'm thinking.

Concur.  I don't currently go deeper than a single level, and every use I can think of offhand should work with a single level.   For example a verb-noun structure would be supported.

**Comment by abellgithub** [comment]
Pushed a branch https://github.com/PDAL/PDAL/tree/issue-2293

In order to use this, your kernel should
- subclass SubcommandKernel.
- implement subcommands() that returns a list of allowable subcommands (strings)
- implement addSubSwitches(ProgramArgs&, const std::string& subcommand) that replaces addSwitches() for SubcommandKernel.  You should only add options relevant for the subcommand passed as the argument.
- use the protected value `m_subcommand` to get the name of the subcommand provided at the command line.

Let me know how this works for you.

**Comment by jw3** [comment]
Ported things over, it was painless

>  Showing 2 changed files with 18 additions and 35 deletions

After some light use it feels the same, and seems to work like it did previously.  Ill give it a better run through next week.

**Comment by abellgithub** [comment]
I think I'm going to PR this without the changes suggested in the last comment.  Another ticket can be added to enhance behavior if necessary.

**Comment by jw3** [comment]
@abellgithub sounds good, what is in there worked well.  I hope to have time again soon to revisit this.  Thanks.
