### ISSUE TITLE
sshfs breaks pdal in alpine image

### ISSUE THREAD

**Issue by devon-sofdesk** [PDAL/PDAL#2298]
**Description**
Installing `sshfs` breaks `pdal` in the alpine image.

**Repro steps**
1. `docker run --rm -it pdal/alpine:1.8`
2. `apk update && apk add sshfs`
3. `pdal`

**Expected behavior**
pdal doesn't throw any errors

**Actual behavior**
pdal throws errors

**Recording**
https://asciinema.org/a/mPrVy0NPL9hH7O1FG0u7eCKw7

**Comment by abellgithub** [comment]
Installing the sshfs package seems to remove libraries on which PDAL depends.  I don't think there's much we can do about that.  You should ask the people who created the sshfs package why they're doing this and how it can be avoided.
