### ISSUE TITLE
Correct way to deal with large files (split w/buffer + merge?)

### ISSUE THREAD

**Issue by jgrn307** [PDAL/PDAL#2303]
We've got some large las files (derived from a TLS) that we want to perform some operation on like ground classification.  We can split the files with a buffer using e.g. filters.splitter with the buffer parameter, run e.g. an smrf filter on the smaller (memory safer) tiles.  What I'm confused with is how to then merge the tiles back together without duplicating points in the buffer zones.  Is there a "safe" way to debuffer the tiles first, or does filters.merge have some ability to do this dynamically?  Thanks!

**Comment by abellgithub** [comment]
I'm sorry, but there's no straightforward way to do this. You'll have to
crop the buffer off of each tile after you run the classification. This has
come up before, so I'll enter a ticket.

**Comment by abellgithub** [comment]
Closed #2304 in favor of #2309.
