### ISSUE TITLE
Add the ability to trim a buffer using filters.crop

### ISSUE THREAD

**Issue by abellgithub** [PDAL/PDAL#2304]
Allowing cropping by a distance from the bounds box of a set of points.

**Comment by jgrn307** [comment]
A note: this needs to "perfectly" reverse buffer split.  The "bounds" of the resultant tile + buffer (x/y min to max) may not be exactly the buffer distance.

**Comment by abellgithub** [comment]
Yes.  I can't think of a good way to do this, which is probably why it hasn't been done in the past.

**Comment by jgrn307** [comment]
Is it possible to store metadata (the tile's "true" or "original" bounding box that would be used in a crop) in some point formats?  If so, this could be an easy solution -- tile + buffer with maybe a "--store_boundary" flag that could be used during the merge step?  I imagine not all formats can support the arbitrary metadata but I'm guessing some of them could (las, for instance)?
