### ISSUE TITLE
pdal tile is unable to handle url link as input

### ISSUE THREAD

**Issue by tanisha11** [PDAL/PDAL#2308]
On giving a http url as input file, the following error is returned in pdal tile command:
PDAL: No input files found for path <filePath>

**Comment by abellgithub** [comment]
Can you please provide a sample of the command that generated the error message.

**Comment by tanisha11** [comment]
pdal tile -i https://tiles.arcgis.com/tiles/cFEFS0EWrhfDeVw9/arcgis/rest/services/PCL__3857__F_Helsinki__CityCenter_PointCloud_RGB/SceneServer -o "d:/pdal/output#.las"

**Comment by connormanning** [comment]
Try `pdal tile -i i3s://https://tiles.arcgis.com/tiles/cFEFS0EWrhfDeVw9/arcgis/rest/services/PCL__3857__F_Helsinki__CityCenter_PointCloud_RGB/SceneServer -o "d:/pdal/output#.las"`.  See the docs stating this [here](https://pdal.io/stages/readers.i3s.html).

**Comment by abellgithub** [comment]
This is a real limitation of the current code, rather than a bug.
