### ISSUE TITLE
Add tagging of points in the buffer region in filters.splitter

### ISSUE THREAD

**Issue by abellgithub** [PDAL/PDAL#2309]
Tagging points in the buffer region of a point view would allow them to be easily removed after later processing.

**Comment by hobu** [comment]
By "tagging", do you simply mean adding another attribute with an indicator variable?

**Comment by abellgithub** [comment]
Yes. Add a dimension that tracks whether a point was in the buffer or not.

**Comment by connormanning** [comment]
There's a `Dimension::Omit` I've used for a similar purpose.

**Comment by abellgithub** [comment]
I forgot that we're just using the PointView facility to stick points in multiple tiles, so I'm not sure this will work exactly as proposed.  We'd have to copy the point data or perhaps find another way around.

**Comment by abellgithub** [comment]
We don't have any good way of doing this for the time being.

**Comment by jgrn307** [comment]
What formats support custom header fields?  Certainly LAS -- do others?  LAStools' solution is to simply embed the original bounding box in a custom header field.

**Comment by abellgithub** [comment]
LAS has a fixed header.  You can add data to the end of the header, but it is undefined.  Much better in LAS is to add VLRs for user data.
