### ISSUE TITLE
Require minimum number of points

### ISSUE THREAD

**Issue by jw3** [PDAL/PDAL#2315]
I am looking for the counterpart to the `count` arg in Reader, to set a _minimum_ count.

The use case is to short circuit a pipeline if a minimum point count is not met, where failing early could save expensive and futile logic that follows the read.

Specifically thinking about the Greyhound and EPT readers, but might be applicable to all readers.

An example of savings might exist in the EPT reader itself; where even if zero points are going to be received it will still read all the nodes (which is not cheap).  Perhaps that's a good example or perhaps I am missing some other detail there, but I think it is representative of the savings one might see if they have stages that will fail if there are not enough points.

Here is reference impl I am using for ept reader https://github.com/jw3/PDAL/commit/d116c257a5da5a1b06d471a436f4840460095c71

**Comment by connormanning** [comment]
I'm a bit confused on the use-case here.
> in the EPT reader itself; where even if zero points are going to be received it will still read all the nodes

This should not be the case - the EPT reader already short-circuits and only reads the nodes that potentially overlap the query.  For example, if no nodes overlap the query bounds, no remote point-cloud data is read:
```
$ ./bin/pdal translate ept://http://na.entwine.io/nyc/ no-points.laz --readers.ept.bounds="([0,0],[1,1])" --debug
(PDAL Debug) Debugging...
(pdal translate readers.ept Debug) Endpoint: http://na.entwine.io/nyc/
(pdal translate readers.ept Debug) Got EPT info
(pdal translate readers.ept Debug) Query bounds: ([0, 0], [1, 1], [-1.797693134862316e+308, 1.797693134862316e+308])
(pdal translate Debug) Executing pipeline in standard mode.
(pdal translate readers.ept Debug) Overlap nodes: 0
(pdal translate readers.ept Debug) Overlap points: 0
(pdal translate readers.ept Debug) Done reading!
(pdal translate writers.las Debug) Wrote 0 points to the LAS file
```

Can you provide an example pipeline where your `min` option comes into play while the current short-circuit logic does not?

Are you referring primarily to the logic of subsequent stages or the EPT reader itself?  I would think that subsequent stages should generally be quite fast if the upstream reader provides zero points - a concrete example that shows otherwise would be the best support for this issue.

**Comment by jw3** [comment]
> I will follow up with a small conceptual example that tries to illustrate the usefulness of that

```
pipeline
  - reader
  - filter-a: does not care about point count, but is expensive
  - filter-b: must have X number / density of points for success
```
If in another pipeline `b` is buried under other stages, or there are many stages that care about point count, then it would get complicated and redundant to specify per stage.

Semantically it might be a tiny stretch to say `min` points constraint is the same thing as `max` points to a reader, but it seems to me it fits.

I wasn't sure if there was an existing mechanism for this or a pattern that is encouraged.  All I came up with was a guard filter.  The more I type here the more I think there is a simple solution to this... trying to recall the init flow of pipeline and stage execution... Haven't come up with that simple solution yet.

**Comment by abellgithub** [comment]
It seems trivial to create a filter that you could place after a reader that would throw an exception in this case.

**Comment by jw3** [comment]
Yea it would indeed be trivial to do from a filter.

**Comment by jw3** [comment]
This would have all been easier to follow had I not conflated the questions of "hey how can I short circuit  pipeline" and "why is ept reader doing this".

Still wondering about both though :)

**Comment by jw3** [comment]
Thanks you both for the input, the replies here answer everything I was asking about.
- there is no existing mechanism to short circuit a reader as am asking
- a guard filter is the recommended approach to short circuit a pipeline
- the behavior I am seeing from entwine reading empty nodes is what it is but could be addressed later using an extension that would exclude nodes based on additional metadata

I really like the idea of the extensions for entwine, will keep an eye out for that.

As for the readers... while the guard filter is a trivial way to stop the rest of my pipeline, I still incur the expense of reading the nodes in, which is costing hours of time on jobs that are futile (actually much more because the futile jobs consume bandwidth that slows down other jobs which would have completed faster).  So I will likely be using a custom version of the EPT reader for now, just with that additional lower bounds specified so it can fail faster.

:+1:
