### ISSUE TITLE
readers.tindex  no keyword polygon

### ISSUE THREAD

**Issue by pmagdon** [PDAL/PDAL#2316]
I am trying to accompllish a standard task with pdal. I have a large set of *.laz files from which I want to extract a small proportion of points that are inside a polygon. Since the rest of my application is in python I try to this  with the python api.  I created an index file with the following code:

`pdal tindex  laz_index.shp "data\*.laz" -f "ESRI Shapefile" --lyr_name "pdal" --t_srs "EPSG:25832" --fast_boundary `

Which created a nice shapefile:
![grafik](https://user-images.githubusercontent.com/8035446/50056731-ba900680-0160-11e9-8b83-111251fe179c.png)

Now I want to extract all points within  a polygon. Following the documentation [here](https://pdal.io/stages/readers.tindex.html#readers-tindex) I created the following pipeline:

`json1 = """
{
  "pipeline":[
    {
      "type":"readers.tindex",
      "filename":"/laz_index.shp", 
      "polygon":"POLYGON((660000 5875000, 660000 5875050,660050 5875050,660050 5875000,660000 5875000))"
    },
    {
      "type":"writers.las",
      "filename":"D:/tmp/file-cropped.las"
    }
  ]
}
"""`
When validating the pipeline using pdal.validate() I get th following error:

readers.tindex: Unexpected argument 'polygon'

Questions:
1.) How should i specify the polygon /AOI?
2.) Is it possible to combine a wkt filter (e.g. the bounding box of a irregular polygon) and the polygon filter itself to increase the speed?

**Comment by abellgithub** [comment]
The options for the tindex program and the reader are a bit inconsistent.  Sorry.  See the [documentation](https://pdal.io/stages/readers.tindex.html): .  I think you're looking for the option `--wkt`.  You can also use `pdal --options=readers.tindex` to list all the options for the reader.

**Comment by pmagdon** [comment]
Ok, the -wkt option is the correct one. The pipeline example in the [documentation](https://pdal.io/stages/readers.tindex.html) should be updated as it still includes 'polygon'.  When I import with the wkt option I always get the following warning:
`(readers.tindex Error) GDAL failure (1) Geometry has no SRS`
However, the tindex shp has a projection and looks ok in Qgis (see picture above)
