### ISSUE TITLE
Update API code for LASzip 1.4

### ISSUE THREAD

**Issue by abellgithub** [PDAL/PDAL#2320]
LASzip 1.4 doesn't work properly with 1.4 points if the data structure containing the data doesn't populate the 1.2 data as well as the 1.4 data.  See https://github.com/LASzip/LASzip/issues/50

**Comment by fgilic** [comment]
Hi,
I would like to check if this should solve [the problem](https://gitter.im/PDAL/PDAL?at=5c167badae1ab5539ef69649) I have posted on Gitter? I have updated PDAL conda package and still have the same problem.

**Comment by abellgithub** [comment]
I believe so.
