### ISSUE TITLE
Output las file created using pdal translate, does not show any data.

### ISSUE THREAD

**Issue by tanisha11** [PDAL/PDAL#2322]
Command used- pdal translate -i i3s://https://tiles.arcgis.com/tiles/z2tnIkrLQ2BRzr6P/arcgis/rest/services/USGSNYC_2014_LiDAR/SceneServer -o d:/pdal/nycOutput.las  --readers.i3s.threads=64 --readers.i3s.bounds="([-73.978984,-73.9442618],[40.7065545,40.7412767])" 

The output las file was of about 5.38 GB but it does not display any data when loaded. Similarly, for other data sets, the data isnt loaded. eg. https://tiles.arcgis.com/tiles/z2tnIkrLQ2BRzr6P/arcgis/rest/services/SONOMA_AREA2_LiDAR/SceneServer

**Comment by tanisha11** [comment]
On trying the sample given in the documentation (https://pdal.io/stages/readers.i3s.html?highlight=i3s), the same issue of data not loading in the las file is observed. Also, please note the data url given in the documentation is wrong, corrected url is as below:

pdal translate -i i3s://https://tiles.arcgis.com/tiles/8cv2FuXuWSfF0nbL/arcgis/rest/services/AUTZEN_LiDAR/SceneServer -o d:/pdal/outputFiles/autzen.las --readers.i3s.threads=64 --readers.i3s.bounds="([-123.075542,-123.06196],[44.049719,44.06278])"

**Comment by hobu** [comment]
> The output las file was of about 5.38 GB but it does not display any data when loaded. 

We need more information. Does not display in what? Does not load in what? If you wrote a 5.38gb LAS 1.2 file, which is the default that will happen with your invocation above, that is not going to be valid.

**Comment by tanisha11** [comment]
> We need more information. Does not display in what? Does not load in what? If you wrote a 5.38gb LAS 1.2 file, which is the default that will happen with your invocation above, that is not going to be valid.

The las file did not display any data in ArcGIS Pro nor in an online viewer, http://lidarview.com/
In ArcGIS Pro, the extent boundary is displayed but inside it is completely white/blank. We tested against various extents, creating las files ranging from 477 bytes to 8 GB.

pdal translate -i i3s://https://tiles.arcgis.com/tiles/z2tnIkrLQ2BRzr6P/arcgis/rest/services/USGSNYC_2014_LiDAR/SceneServer -o d:/pdal/outputFiles/nycOutput3.las --readers.i3s.threads=64 --readers.i3s.bounds="([-73.978984,-73.9616229],[40.6891934,40.7065545])"

Created a 477 byte output file as attached-
[nycOutput3.zip](https://github.com/PDAL/PDAL/files/2697540/nycOutput3.zip)

**Comment by abellgithub** [comment]
The attached file contains no points.

I used the following command to create a valid LAS file:

```
bin/pdal translate i3s://https://tiles.arcgis.com/tiles/z2tnIkrLQ2BRzr6P/arcgis/rest/services/USGSNYC_2014_LiDAR/SceneServer \
out.las --readers.i3s.bounds="([-73.978984,-73.95],[40.6891934,40.72])"
```

The file contains 30,736,218 points.  Both `lasinfo` (LAStools) and `pdal info` have no trouble reading the output. You can download the output of the above command [here](https://drive.google.com/file/d/1-7SBpzI0A4LGQFEEQkPELeCeXU6kqub0/view?usp=sharing)

**Comment by abhiataero** [comment]
we downloaded the data and tried to load in multiple viewer, it does not show up. 

Viewer tried 
- Fugro Viewer
- Las File Viewer http://www.kgs.ku.edu/stratigraphic/LAS/
- ArcGIS Pro 

We have exported the points to CSV to take a look at it, one thing that was noticed is that the data is in WGS84 and the value ( lat long ) stored are upto 2 decimals, 
e.g  -73.98 40.70 24.16
Correct me if I am wrong, since the lat long are same for most of the point they just overlap. The number of decimal should be more else it looses the accuracy of the data

**Comment by abellgithub** [comment]
It's unclear what you're trying to do. Please post a command and/or pipeline.

**Comment by abhiataero** [comment]
We are trying to view the las [output ](https://drive.google.com/file/d/1-7SBpzI0A4LGQFEEQkPELeCeXU6kqub0/view?usp=sharing) that you have provided in the above reply.  
We are trying to say that when the input is3 file is in WGS84 projection the output created can not be viewed. The coordinates stored in the file are having only two decimal places, which is causing the issue

**Comment by abellgithub** [comment]
You can set the scale factor for X, Y and Z of LAS output as you like.  Add `--writers.las.scale_x=.001", for example, to the command line above, to get three places to the right of the decimal point (the default is two) for the X dimension.  See the [documentation](https://pdal.io/stages/writers.las.html).  You can write CSV directly using the [text writer](https://pdal.io/stages/writers.text.html).
