### ISSUE TITLE
PDAL translate creating empty LAS files

### ISSUE THREAD

**Issue by vedantbajaj96** [PDAL/PDAL#2334]
Trying to convert i3s service to las file. Getting empty LAS files (477kb in size).

Command I am using - 
pdal.exe translate i3s://https://tiles.arcgis.com/tiles/z2tnIkrLQ2BRzr6P/arcgis/rest/services/USGSNYC_2014_LiDAR/SceneServer D:/PDAL/output/op.las --readers.i3s.threads=64 --readers.i3s.bounds="([-73.958801,-73.938901],[40.755493,40.775493])" --readers.i3s.dimensions="ELEVATION,INTENSITY,CLASS_CODE,FLAGS,RETURNS" --writers.las.scale_x=0.000001 --writers.las.scale_y=0.000001 --writers.las.scale_z=0.000001

**Comment by abellgithub** [comment]
I don't see an issue with the command.  Perhaps the bounds you've selected contain no points?  Are you sure that there are points to be fetched?

**Comment by vedantbajaj96** [comment]
> I don't see an issue with the command. Perhaps the bounds you've selected contain no points? Are you sure that there are points to be fetched?

The selected bound certainly has valid points. We can duplicate this error for a lot of bounds where there is valid data.

**Comment by kylemann16** [comment]
We agree there is an issue here, and are working on it. Have you tried this on any version 2.0 data sets?

**Comment by abhiataero** [comment]
@kylemann16 We have not tried with v2.0 dataset, will try it out and let you know how it goes

**Comment by vedantbajaj96** [comment]
@kylemann16 
We tried with a few different 2.0 datasets - 
a. Manitowoc_County_Ground_Point_Cloud https://tiles.arcgis.com/tiles/ceC3pbsIeU7iCdFg/arcgis/rest/services/Manitowoc_County_Ground_Point_Cloud/SceneServer
b. Zuid_Holland
https://tiles.arcgis.com/tiles/nSZVuSZjHpEZZbRo/arcgis/rest/services/Zuid_Holland/SceneServer
c. AUTZEN_LiDAR_2X https://tiles.arcgis.com/tiles/z2tnIkrLQ2BRzr6P/arcgis/rest/services/AUTZEN_LiDAR_2X/SceneServer
What we are trying to do is convert i3s to las by creating smallers chips of size 0.01 * 0.01.
For manitowoc and Autzen, we were able to generate the different las files for the smaller chips. However, for Zuid, for some bounds, we got valid LAS files, but some returned empty ( 477 bytes file), even though there seems to be valid data in those bounds.

Few examples for which we get empty las files - 
- pdal.exe translate i3s://https://tiles.arcgis.com/tiles/nSZVuSZjHpEZZbRo/arcgis/rest/services/Zuid_Holland/SceneServer D:\PDAL_Valid\XYZ\Zuid36.las --readers.i3s.threads=64 --readers.i3s.bounds="([4.556321,4.566321],[51.927268,51.937268])" --readers.i3s.dimensions="ELEVATION,INTENSITY,RGB,FLAGS,CLASS_CODE,RETURNS" --writers.las.scale_x=0.000001 --writers.las.scale_y=0.000001 --writers.las.scale_z=0.000001
- pdal.exe translate i3s://https://tiles.arcgis.com/tiles/nSZVuSZjHpEZZbRo/arcgis/rest/services/Zuid_Holland/SceneServer D:\PDAL_Valid\XYZ\Zuid37.las --readers.i3s.threads=64 --readers.i3s.bounds="([4.566321,4.576321],[51.927268,51.937268])" --readers.i3s.dimensions="ELEVATION,INTENSITY,RGB,FLAGS,CLASS_CODE,RETURNS" --writers.las.scale_x=0.000001 --writers.las.scale_y=0.000001 --writers.las.scale_z=0.000001
- pdal.exe translate i3s://https://tiles.arcgis.com/tiles/nSZVuSZjHpEZZbRo/arcgis/rest/services/Zuid_Holland/SceneServer D:\PDAL_Valid\XYZ\Zuid38.las --readers.i3s.threads=64 --readers.i3s.bounds="([4.576321,4.586321],[51.927268,51.937268])" --readers.i3s.dimensions="ELEVATION,INTENSITY,RGB,FLAGS,CLASS_CODE,RETURNS" --writers.las.scale_x=0.000001 --writers.las.scale_y=0.000001 --writers.las.scale_z=0.000001
- pdal.exe translate i3s://https://tiles.arcgis.com/tiles/nSZVuSZjHpEZZbRo/arcgis/rest/services/Zuid_Holland/SceneServer D:\PDAL_Valid\XYZ\Zuid39.las --readers.i3s.threads=64 --readers.i3s.bounds="([4.586321,4.596321],[51.927268,51.937268])" --readers.i3s.dimensions="ELEVATION,INTENSITY,RGB,FLAGS,CLASS_CODE,RETURNS" --writers.las.scale_x=0.000001 --writers.las.scale_y=0.000001 --writers.las.scale_z=0.000001

**Comment by kylemann16** [comment]
@vedantbajaj96 
Try using the esri-debug branch. This should help you.

**Comment by abellgithub** [comment]
@kylemann16 @hobu - Can this be closed?

**Comment by kylemann16** [comment]
I believe so. As far as I know the most recent i3s pull request fixes this issue.
