### ISSUE TITLE
Exporting las from pgpointcloud with higher precision

### ISSUE THREAD

**Issue by Mitko88** [PDAL/PDAL#2336]
I have point clouds imported in PostgreSQL with 12 decimal places. However, when I try to export the points as a las file there are just two. How can I increase the precision?

**Comment by Mitko88** [comment]
Thank you for the quick response. I managed to export 6 decimals with setting up the scale, but not more than this. Do you know how this can be increased?

**Comment by abellgithub** [comment]
I know of no reason why you couldn't get any precision you desire up to that which is actually in your data, up to the limits of IEEE double precision values.  You'll need to provide information on your data, command you're using and how you're analyzing the data in order for me to help you more.

**Comment by Mitko88** [comment]
The error that I am getting is due to the dimension of the int32.

`"pipeline":[
     {
      "type":"readers.pgpointcloud",
      "connection":"dbname='postgres' user='postgres'",
      "table":"input",
      "column":"pa",
      "spatialreference":"EPSG:4326"
    },
    {
      "type":"writers.las",
      "filename":"output.las",
      "scale_x":0.00000001,
      "scale_y":0.00000001,
      "scale_z":0.001
    }
  ]`

`RuntimeError: writers.las: Unable to convert scaled value (1.517167713e+10) to int32 for dimension 'X' when writing LAS/LAZ file t.las.`

**Comment by abellgithub** [comment]
I misspoke above.  IEEE double-precision gets you about 16 significant digits.  However, LAS stores X, Y and Z in 32 bit integers, along with a scale factor.  A 32 bit integer only provides up to 10 significant digits.  The error message says that with the scale you're requesting, one of the values can't be stored in the space available (32 bits).  You can set `scale_x` to `auto`, which will set the scale factor to provide the most precision possible given the range of output data values.

Hope that helps,

**Comment by abellgithub** [comment]
@mghildiy : You can't. The postgres interface only supports point X/Y/Z with 32 bit integers. But there is scale and offset that should let you get sufficiently precise for almost any situation. This is the same as it is with LAS.

**Comment by mghildiy** [comment]
> @mghildiy : You can't. The postgres interface only supports point X/Y/Z with 32 bit integers. But there is scale and offset that should let you get sufficiently precise for almost any situation. This is the same as it is with LAS.

I tried both scale and offset in my pipeline, but nothing worked.
