### ISSUE TITLE
Convert SBET angle to degrees

### ISSUE THREAD

**Issue by gui2dev** [PDAL/PDAL#2354]
Hi,

I had to use SBET reader, but came across odd values that would not fit the pdal documentation.

Applanix provides documentation for the POSPac SBET files.

Based on Table 4 of PosPac Quick Start Guide.pdf in 3.0 POSPac Land Output Data Files Post-Processed Solution File:

> Data | Units | Type
> -- | -- | --
> time | seconds | double
> latitude | radians | double
> longitude | radians | double
> altitude | meters | double
> x velocity | meters/second | double
> y velocity | meters/second | double
> z velocity | meters/second | double
> roll | radians | double
> pitch | radians | double
> platform heading | radians | double
> wander angle | radians | double
> x body acceleration | meters/second2 | double
> y body acceleration | meters/second2 | double
> z body acceleration | meters/second2 | double
> x body angular rate | radians/second | double
> y body angular rate | radians/second | double
> z body angular rate | radians/second | double

But according to PDAL documentation angles (and notably latitude and longitude) are expected to be in degrees.

For now I'm using a transformation filter to put back latitude and longitude in degrees before reprojection.

First, I would suggest to edit the documentation for the reader to warn the user about that.

Then, I'm not sure if some sort of conversion should be included in the reader, or maybe as an option ?

**Comment by abellgithub** [comment]
Longitude and Latitude are mapped to Y and X, respectively by the SBET
reader. X,Y and Z are unitless in PDAL, though units may be implied by a
spatial reference.

**Comment by gui2dev** [comment]
But still roll, pitch, azimuth and wander angle are in radians, but documented as degrees

**Comment by abellgithub** [comment]
It's probably worth reviewing all the input and modifying values to meet expectations.  It appears that we didn't have much documentation when the readers/writer were originally written.

**Comment by gui2dev** [comment]
@abellgithub that will be for v2.0

**Comment by abellgithub** [comment]
This is about more than documentation.  There are some dimensions that probably aren't converted to the proper units as we've defined them.  @gadomski indicated he had no good documentation for SBET, so we didn't know how things should be handled.

To me, the big question is whether we should convert lon/lat to degrees from radians or just set an appropriate SRS.

**Comment by gadomski** [comment]
I think the least-surprising-for-the-user way would be to convert _only_ latitude and longitude to degrees by default, with an option on the reader that would disable the degree conversion (i.e. keep things in radians). At least in my experience, I don't see much/any downstream work that can handle lat+long in radians.

**Comment by gadomski** [comment]
@gui2dev pull request at #2386. It felt weird to just convert lat+long and not convert the other angles, so in the patch I went ahead and converted everything to degrees. Is there any value in keeping some angles as radians while converting others to degrees?

**Comment by gui2dev** [comment]
IMHO it's better to convert so angles to be compliant with the pdal dimensions documentation.

**Comment by abellgithub** [comment]
Where are you seeing such documentation?  I see degrees specified for ScanAngleRank, Pitch and Roll, but that's it.

**Comment by gui2dev** [comment]
> Where are you seeing such documentation? I see degrees specified for ScanAngleRank, Pitch and Roll, but that's it.

I agree. IMHO, either it should be unitless, or unified but either ways, documented.
