### ISSUE TITLE
Don't build EPT if no arbiter

### ISSUE THREAD

**Issue by abellgithub** [PDAL/PDAL#2357]
EPT needs arbiter to work properly.

**Comment by connormanning** [comment]
Arbiter works for filesystem access without Curl (or should, unless a bug has caused a regression), so it could just be always enabled.  If an HTTP access is attempted, it will throw.  This would get rid of all the `PDAL_HAVE_ARBITER` stuff.

**Comment by abellgithub** [comment]
We always have arbiter now.
