### ISSUE TITLE
Unexpected output with writers.gdal

### ISSUE THREAD

**Issue by mccarthyryanc** [PDAL/PDAL#2361]
Here is a test pipeline to output a raster for the autzen dataset:
```json
{
    "pipeline":[
        "autzen-utm.las",
        {
            "type": "writers.gdal",
            "resolution": 100,
            "output_type":"max",
            "bounds": "([494400,494600],[4878200,4878400])",
            "dimension":"Z",
            "filename":"testing.tif"
        }
    ]
}
```

Given the bounds and resolution I would have expected a 2x2 raster. However, I get a 3x3 raster with an extra row/column of pixels on the top and right. Is this a bug, or is it expected that I should subtract the resolution from the max values to get a raster perfectly within the bounds?

**Specs**
* Pdal 1.8.0
* Ubuntu 18.04
* installed via conda

**Comment by abellgithub** [comment]
The bounds are inclusive.  So 494400 falls in the first cell, 494500 falls in the second cell and 494600 falls in the third cell (though it is the minimum value).  So, yes, you could subtract 100 from your upper bounds if you want a 2x2 grid.

A quick look at the code makes me think that this isn't the best, as the bounds are just used to create the grid and points aren't checked against the bounds as they're processed.  We just check that they impact the grid.  Perhaps it would be better to specify an origin and the number of cells in the X and Y directions.
