### ISSUE TITLE
[Question] readers for geomesa database support?

### ISSUE THREAD

**Issue by sunapi386** [PDAL/PDAL#2362]
We have [`readers.geowave`](https://pdal.io/stages/readers.geowave.html) and [`writers.geowave`](https://pdal.io/stages/writers.geowave.html) support, do we plan to support the [Geomesa](geomesa.org) database? 

And I'm just curious, Geomesa and Geowave are quite similar, so was there a reason why Geowave is the supported database?

**Comment by abellgithub** [comment]
Because the people who contributed the code wrote it that way.

If you'd like to write support for another database, that would be fine.
