### ISSUE TITLE
Can't find geotiff.h when building in RHEL7/Centos7

### ISSUE THREAD

**Issue by jeffsp** [PDAL/PDAL#2364]
$ mkdir build
    $ cd build
    $ cmake3 ..
    ...
    CMake Error at /usr/share/cmake3/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
      Could NOT find GeoTIFF (missing: GEOTIFF_INCLUDE_DIR)
    $ cmake3 .. -DGEOTIFF_INCLUDE_DIR="/usr/include/libgeotiff"
    ...
    -- Configuring done
    -- Generating done
    -- Build files have been written to ...
    $

**Comment by abellgithub** [comment]
The find module looks for geotiff.h.  Where is that file on your system?  It should find it in /usr/include/libgeotiff without you doing anything special.

**Comment by abellgithub** [comment]
Also, my recollection is that Centos 7 comes with an exceedingly old version of GCC which we don't support.  If you can build/install a newer compiler, you might stand a chance of building PDAL, but I don't think it will work out of the box and we have no plans to support it.

**Comment by jeffsp** [comment]
It seems to work just fine for me. I was just letting folks know that you need to pass this extra parameter to cmake, in case someone else is having trouble on Centos 7.

    $ sudo updatedb
    $ locate geotiff.h
    ...
    /usr/include/libgeotiff/geotiff.h

**Comment by abellgithub** [comment]
I'm glad it worked, though I don't understand why you needed to do anything special.  PDAL comes with a FindGeoTIFF.cmake that contains:

```
FIND_PATH(GEOTIFF_INCLUDE_DIR
  geotiff.h
  PATH_SUFFIXES geotiff libgeotiff
  PATHS
  ${OSGEO4W_INCLUDE_DIR})
```

So I'm not sure what's happening on your system.

**Comment by hobu** [comment]
@jeffsp Can you report your gcc version information?

**Comment by adamsteer** [comment]
I recall using devtoolsets to build PDAL on centOS7 - far easier than updating a compiler:

https://www.softwarecollections.org/en/scls/rhscl/devtoolset-7/

this is my dependencies list for a clean CentOS install from those days: https://github.com/adamsteer/pointWPS/blob/master/buildscripts/pdal_depends.sh

HTH - ignore the postgres bits, and **cautionary note** - I haven't audited that list for more modern PDAL (1.4 or 1.5 was state of the art when I made it)

**Comment by jeffsp** [comment]
@hobu 

    # gcc --version
    gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)

@adamsteer Thanks for the suggestion about devtoolset.

I didn't seem to have problems compiling. The original issue, not finding libgeotiff, was because I had version 1.2.5 of geotiff installed, but it was looking for version > 1.3.0.

After manually directing cmake to geotiff.h and laszip.h, things started to look better:

     $ cmake3 .. -DGEOTIFF_INCLUDE_DIR="/usr/include/libgeotiff" -DLASZIP_INCLUDE_DIR="/usr/local/include"
    ...
     $ make -j
     ...
    [ 99%] Built target xml_schema_test
    [ 99%] Built target pdal
    [100%] Built target pgpointcloudtest
    $ make test
    ...
    98% tests passed, 2 tests failed out of 89
    Total Test time (real) = 107.02 sec
    The following tests FAILED:
              1 - pgpointcloudtest (Failed)
             82 - pc2pc_test (Failed)
     Errors while running CTest
     make: *** [test] Error 8

but then

    $ pdal ground a.las b.las
    $ lasinfo b.las
    error: The geotiff keys could not be read from VLR records
    $ texpert_viewer x.las
    exception: The geotiff keys could not be read from VLR records

If I install libgeotiff 1.4.2 from source, that's when I get segfaults

    $ make -j
    ...
    $ make test
    ... segfaults, core dumps, and other ugly stuff

I will try a newer compiler, if you think that may help.

**Comment by hobu** [comment]
#2381 should demonstrate a path forward.
