### ISSUE TITLE
unresolved external symbol in examples/writing (VS 2015) 

### ISSUE THREAD

**Issue by massoudpourmandi** [PDAL/PDAL#2367]
when I build an example of PDAL library I'm getting following errors, it is originated from Extractor.hpp and Insertor.hpp. did I miss something with I'm building PDAL project?. I used OSGeo4W64 for downloading dependencies.
I would appreciate any 
[tutorial.log](https://github.com/PDAL/PDAL/files/2853516/tutorial.log)
help, thanks in advance.  

Building Custom Rule C:/pdal/pdal_maintance1.8/PDAL-1.8-maintenance/examples/writing/CMakeLists.txt
  CMake does not need to re-run because C:/pdal/pdal_maintance1.8/PDAL-1.8-maintenance/examples/writing/build/CMakeFiles/generate.stamp is up-to-date.
  tutorial.cpp
C:\pdal\pdal_maintance1.7\install\include\pdal/util/Uuid.hpp(174): warning C4996: 'sprintf': This function or variable may be unsafe. Consider using sprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\ucrt\stdio.h(1769): note: see declaration of 'sprintf'
C:\pdal\pdal_maintance1.7\install\include\pdal/Metadata.hpp(586): warning C4800: 'unsigned __int64': forcing value to bool 'true' or 'false' (performance warning)
C:\pdal\pdal_maintance1.7\install\include\pdal/PipelineManager.hpp(104): warning C4800: 'pdal::Stage *': forcing value to bool 'true' or 'false' (performance warning)
     Creating library C:/pdal/pdal_maintance1.8/PDAL-1.8-maintenance/examples/writing/build/Release/tutorial.lib and object C:/pdal/pdal_maintance1.8/PDAL-1.8-maintenance/examples/writing/build/Release/tutorial.exp
tutorial.obj : error LNK2019: unresolved external symbol __imp_htonl referenced in function "public: virtual class pdal::BeInserter & __cdecl pdal::BeInserter::operator<<(int)" (??6BeInserter@pdal@@UEAAAEAV01@H@Z)
tutorial.obj : error LNK2019: unresolved external symbol __imp_htons referenced in function "public: virtual class pdal::BeInserter & __cdecl pdal::BeInserter::operator<<(short)" (??6BeInserter@pdal@@UEAAAEAV01@F@Z)
tutorial.obj : error LNK2019: unresolved external symbol __imp_ntohl referenced in function "public: virtual class pdal::BeExtractor & __cdecl pdal::BeExtractor::operator>>(int &)" (??5BeExtractor@pdal@@UEAAAEAV01@AEAH@Z)
tutorial.obj : error LNK2019: unresolved external symbol __imp_ntohs referenced in function "public: virtual class pdal::BeExtractor & __cdecl pdal::BeExtractor::operator>>(short &)" (??5BeExtractor@pdal@@UEAAAEAV01@AEAF@Z)
C:\pdal\pdal_maintance1.8\PDAL-1.8-maintenance\examples\writing\build\Release\tutorial.exe : fatal error LNK1120: 4 unresolved externals

**Comment by abellgithub** [comment]
This seems confused.  It's mixing up 1.7 with 1.8.  And the command you're using or trying to use isn't clear.

**Comment by massoudpourmandi** [comment]
actually, I used pdal 1.7 library.and for testing purpose, I used one
generic example which is common in 1.7 and 1.8. anyway, it is fixed because
of your advice. thanks, Andrew.
