### ISSUE TITLE
Converting .pcd to .las file

### ISSUE THREAD

**Issue by DepickereSven** [PDAL/PDAL#2368]
I found [this answer][1] on my question.
But when I try to do it, I get this error:

The command:

    pdal translate D:\Information\bigrotate_frontview.pcd D:\Information\output.las

I get this error:

    Failed to find match for field 'intensity'.

So I searched for that error and I found [this][2].

So I tried the option ` --writers.pcd.xyz=true`

My command looks like this:

```
pdal translate --writers.pcd.xyz=true D:\file.pcd D:\output.las
```
I got the following error:

```
PDAL: Argument references invalid/unused stage: 'writers.pcd'.
```

  [1]: https://gis.stackexchange.com/a/294700
  [2]: https://github.com/PDAL/PDAL/issues/1846

**Comment by chambbj** [comment]
`--writers.pcd.xyz` is not relevant here as you are not using the PCD writer. You are reading PCD and writing LAS.

Instead, there seems to be some issue reading the PCD header, which actually occurs in the PCL codebase.

Can you provide information on how you installed/built PDAL? What versions of PDAL and PCL are you using?

If you can provide sample data, that will help also. I'd be especially interested to see the header plus first row of data, which you can obtain using the command `head -12 /path/to/input.pcd` in the case of an ASCII PCD file.

**Comment by abellgithub** [comment]
Please see #2288

**Comment by DepickereSven** [comment]
@chambbj This is the header:

```
# .PCD v.7 - Point Cloud Data file format
VERSION .7
FIELDS x y z rgb
SIZE 4 4 4 4
TYPE F F F F
COUNT 1 1 1 1
WIDTH 1024
HEIGHT 640
VIEWPOINT 0 0 0 1 0 0 0
POINTS 655360
DATA ascii
0 0 0 0
```
I have this version of PDAL

`pdal 1.8.0 (git-version: Release)`

The way I installed PDAL was by following [this guide](https://pdal.io/quickstart.html)

**Comment by DepickereSven** [comment]
@abellgithub Yesterday it generated the .las file but today after reinstalling it worked.
