### ISSUE TITLE
tile/splitter with buffer. No buffer at the corners!

### ISSUE THREAD

**Issue by smgrz** [PDAL/PDAL#2372]
I’m using python 3.7.1 and pdal 1.8.0

cml: pdal tile -i infile.las -o "tiles/outfile_#.las" --length 200 --buffer 25 --origin_x 730131.60 --origin_y 222010.74 

I’ve also tried to use filters.splitter with buffer, but still no points at the corners (buffer area).

**Comment by abellgithub** [comment]
It's not clear what the issue is that you're seeing.  A small sample and more detail would be helpful.

**Comment by smgrz** [comment]
Here is an example (plot) and python code to reproduce it.

`import pdal
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

data = np.random.rand(500000,3)
data[:,0:2] = data[:,0:2]*1000
np.savetxt('input.csv', data, header='X,Y,Z',delimiter=',',comments='',fmt='%3.5f')

json_pipeline = '''
        {
          "pipeline":[
            {
              "type":"readers.text",
              "filename":"input.csv"
            },    
            {
              "type":"filters.splitter",
              "length":"300",
              "origin_x":"500.0",
              "origin_y":"500.0",
              "buffer": "25"
            },
            {
              "type":"writers.las",
              "filename":"outTile_#.las"
            }
          ]
        }'''
pipeline = pdal.Pipeline(json_pipeline)
pipeline.validate() 
pipeline.execute()

for i in np.random.randint(1,10,size=3):
    pl_rt = '{  "pipeline": [    "outTile_'+str(i)+'.las"  ]}'
    pl_readTile = pdal.Pipeline(pl_rt)
    pl_readTile.execute()
    tile_points= pd.DataFrame(pl_readTile.arrays[0])

    plt.figure()
    plt.plot(tile_points.X,tile_points.Y,'.')
    plt.axis('equal')
    plt.show()`

![pdal_tile_splitter](https://user-images.githubusercontent.com/47631342/52797081-65477700-3075-11e9-8dae-3359e7a6a09e.PNG)

**Comment by abellgithub** [comment]
Thanks.  I've figured out the issue and will have a fix shortly.
