### ISSUE TITLE
Density command Not available after compilation

### ISSUE THREAD

**Issue by marcel-bariou** [PDAL/PDAL#2378]
Any Help ThankYOU
PDAL Latest commit d77cf59 Compilation 6 novembre 2018 
UBUNTU 18.04 AMD64
Density command not available Why  ? Hereinafter CMAKE option

> Eigen found (include: /usr/include/eigen3, version: 3.3.4)
FLANN found (include: , lib: flann;flann_cpp)
FLANN found (include: , lib: flann;flann_cpp)
OpenNI2 found (include: /usr/include/openni2, lib: /usr/lib/libOpenNI2.so)
OpenNI2 found (include: /usr/include/openni2, lib: /usr/lib/libOpenNI2.so)
QHULL found (include: /usr/include, lib: optimized;/usr/lib/x86_64-linux-gnu/libqhull.so;debug;/usr/lib/x86_64-linux-gnu/libqhull.so)
Numpy output: /usr/local/lib/python2.7/dist-packages/numpy/core/include
1.15.4

Performing Test SQLITE3_HAS_LOAD_EXTENSION
Performing Test SQLITE3_HAS_LOAD_EXTENSION - Success
Could NOT find LIBEXECINFO (missing: LIBEXECINFO_LIBRARY) 
The following features have been enabled:

 * Bash completion, completion for PDAL command line
 * CPD plugin, Coherent Point Drift (CPD) computes rigid or nonrigid transformations between point sets
 * Delaunay plugin, perform Delaunay triangulation of point cloud
 * PCL plugin, provides PCL-based readers, writers, filters, and kernels
 * PostgreSQL PointCloud plugin, read/write PostgreSQL PointCloud objects
 * SQLite plugin, read/write SQLite objects
 * Python plugin, add features that depend on python
 * Unit tests, PDAL unit tests

-- The following OPTIONAL packages have been found:

 * Lazperf
 * JSONCPP (required version >= 1.6.2)
 * LibXml2
 * Curl
 * Eigen
 * FLANN
 * PkgConfig
 * OpenNI2
 * Qhull
 * VTK
 * Boost (required version >= 1.52)
 * Libunwind

-- The following REQUIRED packages have been found:

 * GDAL (required version >= 1.9.0)
   Provides general purpose raster, vector, and reference system support
 * GEOS (required version >= 3.3)
   Provides general purpose geometry support
 * GeoTIFF
 * ZLIB
   Compression support in BPF
 * Cpd (required version >= 0.5)
 * Qt5Core (required version >= 5.9.5)
 * Qt5Gui (required version >= 5.9.5)
 * Qt5Sql
 * Qt5Widgets
 * Qt5
 * PCL (required version >= 1.7), Point Cloud Library, <http://pointclouds.org>
   Enables PCD reader/writer, PCLVisualizer, PCLBlock filter, ICP filter, and ground, pcl, smooth, and view kernels
 * PostgreSQL
 * PythonLibs
 * NumPy (required version >= 1.5)
 * SQLite3
 * PythonInterp
 * Threads, The thread library of the system

-- The following features have been disabled:

 * GeoWave plugin, Read and Write data using GeoWave
 * I3S plugin, Read from a I3S server or from a SLPK file
 * Greyhound plugin, read points from a Greyhound server
 * Icebridge plugin, read data in the Icebridge format
 * Matlab plugin, write data to a .mat file
 * MrSID plugin, read data in the MrSID format
 * NITF plugin, read/write LAS data wrapped in NITF
 * OpenSceneGraph plugin, read/write OpenSceneGraph objects
 * RiVLib plugin, read data in the RXP format
 * rdblib plugin, read data in the RDB format
 * MBIO plugin, add features that depend on MBIO
 * FBX plugin, add features that depend on FBX

-- The following OPTIONAL packages have not been found:

 * Libexecinfo

Configuring done
Generating done

Some hints needed Thank you

**Comment by abellgithub** [comment]
I would guess that this is the problem:

https://github.com/PDAL/PDAL/issues/2283

You should build from the master or 1.8-maintenance branches.

**Comment by marcel-bariou** [comment]
Thanks it is ok, I closed it!
