### ISSUE TITLE
"count" option is not implemented on reader.ept

### ISSUE THREAD

**Issue by mantbe** [PDAL/PDAL#2379]
The EPT reader currently doesn't respect the `count` option at all.  This is a default reader option inherited by all readers, which is why it appears in the docs even though the EPT reader itself doesn't use it.

For now, the only possibility would be limiting EPT reads by bounds or resolution, and then using the head filter to limit the point count exactly.

**Comment by hobu** [comment]
#2446 also related.

**Comment by hobu** [comment]
This is done in `preview()` and is bounding-polygon aware https://github.com/PDAL/PDAL/commit/83feb8645cd573e670d199c66c46ebfa7c800c43#diff-6c6aa6fc314618e64694ec420896da89R448-R449

**Comment by hobu** [comment]
Added in #3168 and #3172. Note that this returns the maximal point count that might be fetched given a bounds, not a specific value given filtering.
