### ISSUE TITLE
clustering without ground returns

### ISSUE THREAD

**Issue by spiegelss** [PDAL/PDAL#2388]
Good afternoon,

I am attempting to run a pipeline that will:

1. Remove outliers
2. Use a simple morphological filter to get ground returns
3. Compute normal vectors and eigenvalues
4. Use the filters.cluster to cluster points based on the Euclidean Cluster Extraction

The issue I am having is I would like to exclude ground returns from the cluster extraction.  However, I am unsure of a way to get back the ground returns after I use a "filters.range", filtering out the ground classification.  Is there a way to do this that I am missing?  I know I can probably run 2 different pipelines but is there a way to do this all in one?  Thank you so much in advance.

**Comment by hobu** [comment]
This question would be better asked on the email list. Please join the list and ask it there. https://pdal.io/community.html#mailing-list
