### ISSUE TITLE
  Stage* writer(f.createStage("writers.pgpointcloud"))   writer is null

### ISSUE THREAD

**Issue by h137842358** [PDAL/PDAL#2389]
I want to use PDAL in my own project to read Las files and store them in postgresql. I refer to the project PGPOINTCLOUDTEST, but there will be errors.

StageFactory f;
Stage* reader(f.createStage("readers.las"));

reader is not  null.....but,

Stage* writer = f.createStage("writers.pgpointcloud");

writer is null...Why? I don't know how to solve it.

pg_execute(m_testConnection,"CREATE EXTENSION pointcloud");  The previous link PostgreSQL database is working properly。

Thank you!

**Comment by abellgithub** [comment]
Please see the answer to [FAQ](https://pdal.io/faq.html) question 2.

**Comment by h137842358** [comment]
std::string connstr = getMasterDBConn();
	try
	{
		m_masterConnection=pg_connect(connstr);
		// Silence those pesky notices
		pg_execute(m_masterConnection, "SET client_min_messages TO WARNING");
		
		std::stringstream dropDbSql;
		dropDbSql << "DROP DATABASE IF EXISTS " << testDbTempname;
		pg_execute(m_masterConnection, dropDbSql.str());
		std::stringstream createDbSql;
		
		createDbSql << "CREATE DATABASE " <<
			testDbTempname << " TEMPLATE template0";
		try
		{
			pg_execute(m_masterConnection, createDbSql.str());
		}
		catch (const pdal_error&)
		{
			m_bSkipTests = true;
			return;
		}
		
		m_testConnection = pg_connect(getTestDBTempConn());
		try
		{
			pg_execute(m_testConnection,"CREATE EXTENSION pointcloud");
		}
		catch (const pdal_error&)
		{
			m_bSkipTests = true;
			return;
		}
		if (m_bSkipTests)
			return;

		const std::string file("C:/Users/HP/Desktop/1.las");
		const Option opt_filename("filename", file);
		
		StageFactory f;
		Stage* reader(f.createStage("readers.las"));
		Options options;
		options.add(opt_filename);
		reader->setOptions(options);
		

		Stage* writer = f.createStage("writers.pgpointcloud");
		//Stage* writer(f.createStage("writers.pgpointcloud"));
		Options ops = getDbOptions();

		ops.add("scale_x", .01);
		ops.add("scale_y", .01);
		ops.add("scale_z", .01);
		writer->setOptions(ops);
		writer->setInput(*reader);
		PointTable table;
		writer->prepare(table);

		PointViewSet written = writer->execute(table);
		point_count_t count(0);
		for (auto i = written.begin(); i != written.end(); ++i)
			count += (*i)->size();
		writer->execute(table);	
	}
	catch (const std::exception&)
	{
		QMessageBox::information(NULL, “1”, "2");
	}

	if (!m_testConnection || !m_masterConnection) 
		return;
	if (m_testConnection)
	{
		PQfinish(m_testConnection);
	}
	if (m_masterConnection)
	{
		PQfinish(m_masterConnection);
	}

this is my Code，Threads are not used in my code. And I set pgpointcloudWriterTest as a startup project and run it directly with VS2017, which is the same error. Writer is empty.

**Comment by abellgithub** [comment]
The above is irrelevant.  Please follow the information in question 2 of the FAQ.

**Comment by h137842358** [comment]
> The above is irrelevant. Please follow the information in question 2 of the FAQ.

thank you !I set the environment variable PDAL_DRIVER_PATH,it work! Thank you very much
