### ISSUE TITLE
Doc issues with workshop

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#2395]
* The webpage for writer.gdal does not show an output-format option. Because gdal automatically deduces the format from the filename, this was easily solved by just removing the line. 

* Also, for the many people who are attempting to use this as a cookbook, it might be useful in the example to include a "window-size" option to fill data holes. 

My suggested correction is:
```
{
    "pipeline":[
        "autzen-full.las",
        {
            "type":"filters.smrf",
            "window":33,
            "slope":1.0,
            "threshold":0.15,
            "cell":1.0
        },
        {
            "type":"filters.range",
            "limits":"Classification[2:2]"
        },
        {
            "type":"writers.gdal",
            "filename":"autzen-surface.tif",
            "output_type":"min",
            "output_format":"tif",
            "window-size": 3,
            "resolution":1.0
        }
    ]
}
```

**Comment by abellgithub** [comment]
Fixed via #2396.
