### ISSUE TITLE
DTM example on pipelines web page produces error

### ISSUE THREAD

**Issue by Llaves** [PDAL/PDAL#2396]
Running the DTM example on version 1.8.0 produces an error, complaining about
the output-format option in the writer section of the pipeline. The webpage for writer.gdal does not show an output-format option. Because gdal automatically deduces the format from the filename, this was easily solved by just removing the line.
Also, for the many people who are attempting to use this as a cookbook, it might be useful in the example to include a "window-size" option to fill data holes.

My suggested correction is:

```diff
    {
        "pipeline":[
            "autzen-full.las",
            {
                "type":"filters.smrf",
                "window":33,
                "slope":1.0,
                "threshold":0.15,
                "cell":1.0
            },
            {
                "type":"filters.range",
                "limits":"Classification[2:2]"
            },
            {
                "type":"writers.gdal",
                "filename":"autzen-surface.tif",
                "output_type":"min",
-               "output_format":"tif",
+               "window_size": 3,
                "resolution":1.0
            }
        ]
    }
```

**Comment by abellgithub** [comment]
The name of the output format option is `gdaldriver`.  I don't know if you'd like that the option name simply corrected.

**Comment by Llaves** [comment]
I'm too new to the PDAL world to have a strong opinion as the correct solution. Fixing the name is certainly preferable to leaving it with an invalid option keyword.

That said, I am fairly familiar with GDAL and know that it's ability to deduce a driver from a filename extension is quite good. Since the example is intended to demonstrate the pipeline capabilities, adding the unnecessary driver option is a potential source of confusion for the naive user.  So, I guess I would have a small preference for just removing the output_format option and not replacing it with the correct keyword.

**Comment by abellgithub** [comment]
I fixed the name.  Thx.

**Comment by Llaves** [comment]
I should have mentioned at the time that "tif" is NOT a valid driver name for GDAL. The option should read
```
"gdaldriver":"GTiff"
```

**Comment by adamsteer** [comment]
just a quick comment: `window_size` is for ‘how far away from the grid cell I’m filling can I get data from which contributes to the value in the cell’.

hole filling is downstream, eg GDAL’s `fill_nodata.py`.

**Comment by Llaves** [comment]
Is that really true? The description in the writers:gdal docs says:

> If no points fall within the circle about a raster cell, a secondary algorithm can be used to attempt to provide a value after the standard interpolation is complete. If the window_size option is non-zero, the values of a square of rasters surrounding an empty cell is applied using inverse distance weighting of any non-empty cells. The value provided for window_size is the maximum horizontal or vertical distance that a donor cell may be in order to contribute to the subject cell (A window_size of 1 essentially creates a 3x3 array around the subject cell. A window_size of 2 creates a 5x5 array, and so on.)

My interpretation of this says "if there's data in the cell, use it. If there's no data directly in the cell, go window_size cells out looking for data", That seems like it only applies to hole-filling.

I looked at the gdal docs for fill_nodata, and it appears that this is precisely the alg. being called to implement window_size for empty cells.

**Comment by adamsteer** [comment]
oops, I was thinking of `radius`! `window_size` will fill small holes at the expense of potentially smoothing other features. Just like `gdal_fillnodata`.
