### ISSUE TITLE
Documentation: filename globbing

### ISSUE THREAD

**Issue by Llaves** [PDAL/PDAL#2397]
When multiple filenames are provided on the reader line in a pipeline, the input files are effectively merged and processed as a single file, producing a single output, covering the region of the union of the input files. I did not see this in the docs or webpage.

(Note - this comment is based on a single, DTM pipeline. Someone who knows the code could verify whether this statement is true in general.)

**Comment by chambbj** [comment]
This is covered in the documentation [here](https://pdal.io/stages/writers.gdal.html#options). See the `filename` option describing the treatment of multiple inputs.

**Comment by abellgithub** [comment]
Not sure that's the same thing, but input globbing is here: https://pdal.io/pipeline.html

**Comment by Llaves** [comment]
I think it would be useful in the globbing section of the docs to refer forward to the writer options mentioned above.
