### ISSUE TITLE
windows build with error  

### ISSUE THREAD

**Issue by MerlotQ** [PDAL/PDAL#2403]
The error info is 

"error C2280: “std::unique_ptr<pdal::NullOStream,std::default_delete<_Ty>>::unique_ptr(const std::unique_ptr<_Ty,std::default_delete<_Ty>> &)”: attempt to reference a deleted function D:\PDAL-1.7.2\pdal\util\Utils.hpp	618	1	pdalcpp" 

It seems that the following lines give the error.
 /**
      Redirect a stream to some other stream, by default a null stream.
      \param out   Stream to redirect.
      \param dst   Destination stream.
      \return  Context for stream restoration (see \ref restore()).
    */
```
    inline RedirectStream redirect(std::ostream& out, std::ostream& dst)
    {
        RedirectStream redir;

        redir.m_buf = out.rdbuf();
        out.rdbuf(dst.rdbuf());
        return redir;
    }
```

**Comment by abellgithub** [comment]
What compiler/version are you using?

**Comment by MerlotQ** [comment]
visual studio 2013 update5 @abellgithub

**Comment by MerlotQ** [comment]
I now can only build release version of this lib using vs2015 since some of its lib can only be obtained from release version. 
Ubuntu build is always fine but it is not that convenience on a windows machine.

**Comment by abellgithub** [comment]
Why can you not build a release version?  You've provided no errors or information.

**Comment by MerlotQ** [comment]
> Why can you not build a release version? You've provided no errors or information.

The error comes from building with vs2013. Now with 2015 it seems sucess in release build.

**Comment by hobu** [comment]
vs2013 is not supported.
