### ISSUE TITLE
"--spatialreference already exists" error when using readers.pgpointcloud in pipeline

### ISSUE THREAD

**Issue by carstoid** [PDAL/PDAL#2406]
getting the following error output when trying to run the example pipeline for readers.pgpointcloud shown in the documentation, with the connection/table information changed to match my database

removing spatialreference from the pipeline definition doesn't appear to make a difference

(PDAL Debug) Debugging...
(pdal pipeline Debug) Attempting to load plugin '/usr/local/anaconda3/envs/lidar/lib/libpdal_plugi n_reader_pgpointcloud.dylib'.
(pdal pipeline Debug) Loaded plugin '/usr/local/anaconda3/envs/lidar/lib/libpdal_plugin_reader_pgpointcloud.dylib'.
(pdal pipeline Debug) Initialized plugin '/usr/local/anaconda3/envs/lidar/lib/libpdal_plugin_reader_pgpointcloud.dylib'.
PDAL: readers.pgpointcloud: Argument --spatialreference already exists.
running PDAL 1.8.0 installed through conda on osx

see also issue #233 and here:
http://osgeo-org.1560.x6.nabble.com/pdal-PDAL-readers-pgpointcloud-Argument-spatialreference-already-exists-td5393026.html

**Comment by abellgithub** [comment]
This is a duplicate.  See https://github.com/PDAL/PDAL/issues/2393

**Comment by carstoid** [comment]
thank you!
