### ISSUE TITLE
Issue with pipeline sor-pmf and sor-pmf2

### ISSUE THREAD

**Issue by KillianPremel** [PDAL/PDAL#2408]
I tried to do the tutorial on pdal.io, about "Identifying ground returns". 
Link : https://pdal.io/tutorial/pcl_ground/index.html

But when after creating the pipeline (just copy/paste and then download it as sor-pmf2.json), and then call it with the command written in the website ($ pdal pcl -i CSite1_orig-utm.laz -o CSite1_orig-utm-ground.laz -p sor-pmf.json -v 4) it doesn't work. 

I have this : 
_pdal pcl -i D:\TFE\file_lidar.laz -p D:\TFE\sor-pmf2.json -o D:\TFE\Test8888882.laz -v 4 
(I tried with several files, and of course the files are in D:\TFE, I also tried with all in C) 

__(PDAL Debug) Debugging...
(PDAL Debug) Attempting to load plugin 'C:\Users\emac\Anaconda3\envs\myenv\Library\bin\libpdal_plugin_kernel_pcl.dll'.
(PDAL Debug) Loaded plugin 'C:\Users\emac\Anaconda3\envs\myenv\Library\bin\libpdal_plugin_kernel_pcl.dll'.
(PDAL Debug) Initialized plugin 'C:\Users\emac\Anaconda3\envs\myenv\Library\bin\libpdal_plugin_kernel_pcl.dll'.
(pdal pcl readers.las Debug) GDAL debug: OGRSpatialReference::Validate: No root pointer.
(pdal pcl Debug) Executing pipeline in standard mode.
(pdal pcl Debug) Attempting to load plugin 'C:\Users\emac\Anaconda3\envs\myenv\Library\bin\libpdal_plugin_filter_pclblock.dll'.
(pdal pcl Debug) Loaded plugin 'C:\Users\emac\Anaconda3\envs\myenv\Library\bin\libpdal_plugin_filter_pclblock.dll'.
(pdal pcl Debug) Initialized plugin 'C:\Users\emac\Anaconda3\envs\myenv\Library\bin\libpdal_plugin_filter_pclblock.dll'.
(pdal pcl Debug) Executing pipeline in standard mode.
Requested filter `Progressive Morphological Filter with Outlier Removal` not implemented! Skipping...
No points in filtered cloud. Aborting!
(pdal pcl writers.las Debug) Wrote 0 points to the LAS file
(pdal pcl Debug) GDAL debug: GDAL: In GDALDestroy - unloading GDAL shared library._

So it says the filter is not implemented, but I don't understand what I have to do. I just began to work on pipeline and PDAL, but I  really don't find the solution.

**Comment by KillianPremel** [comment]
And it is the same with sor-pmf of course. 

The kind of pipeline (for sor-pmf in this case) :  
_{
  "pipeline": {
    "name": "Progressive Morphological Filter with Outlier Removal",
    "version": 1.0,
    "filters": [{
        "name": "StatisticalOutlierRemoval",
        "setMeanK": 8,
        "setStddevMulThresh": 3.0
      }, {
        "name": "ProgressiveMorphologicalFilter"
    }]
  }
}_

**Comment by abellgithub** [comment]
You don't have the PCL plugin. You'll need to build it as it appears the
PDAL you installed doesn't come with it.

**Comment by KillianPremel** [comment]
Ok thanks ! So I have to install PCL plugin and then it should work ?  Because I tried with that, and it doesn't work. I put the PCL plugin in the same folder.

I looked at the FAQ section in pdal.io and I found this sentence : "If you’ve built pdal yourself, make sure you’ve requested to build the plugin in question (set BUILD_PLUGIN_PCL=ON, for example, in CMakeCache.txt). 
But I don't find CMAkeCache.txt in my files...

**Comment by abellgithub** [comment]
I'm sorry but I didn't read carefully enough the first time through.  You are properly loading the PCL plugin.  It appears that the documentation for this tutorial is out of date.  The PCL filter `Progressive Morphological Filter with Outlier Removal` is indeed not implemented. Please see https://pdal.io/stages/filters.pclblock.html for current documentation on the pclblock filter.

**Comment by chambbj** [comment]
Also, be sure to take a look at the workshop for a more current example of how to run ground filtering (without PCL). https://pdal.io/workshop/exercises/analysis/ground/ground.html
