### ISSUE TITLE
Legacy flags and extended flags are not identical

### ISSUE THREAD

**Issue by KillianPremel** [PDAL/PDAL#2410]
I am doing the workshop on pdal.io, but I have some issues :  on the denoising part and Identifying a ground (https://pdal.io/workshop/exercises/analysis/ground/ground.html).
When I try to run, the issue "Legacy flags and extended flags are not identical" comes up and so the output file is empty. 

For Identifying a ground, it is the second part of filtering thaht doesn't work 👍 
_pdal translate ^
   c:/Users/hobu/PDAL/exercises/analysis/ground/CSite1_orig-utm.laz ^
   -o c:/Users/hobu/PDAL/exercises/analysis/ground/denoised-ground-only.laz ^
   outlier smrf range ^
   --filters.outlier.method="statistical" ^
   --filters.outlier.mean_k=8 ^
   --filters.outlier.multiplier=3.0 ^
   --filters.smrf.ignore="Classification[7:7]" ^
   --filters.range.limits="Classification[2:2]" ^
   --writers.las.compression=true --verbose 4_

For Removing noise it is this pipeline : (the writers.las part)
{
    "pipeline": [
        "c:/Users/hobu/PDAL/exercises/analysis/denoising/18TWK820985.laz",
        {
            "type": "filters.outlier",
            "method": "statistical",
            "multiplier": 3,
            "mean_k": 8
        },
        {
            "type": "filters.range",
            "limits": "Classification![7:7],Z[-100:3000]"
        },
        {
            "type": "writers.las",
            "compression": "true",
            "minor_version": "2",
            "dataformat_id": "0",
            "filename":"c:/Users/hobu/PDAL/exercises/analysis/denoising/clean.laz"
        }
    ]
}
(of course it is not the same path)

Of course, I searched on Google and I found that laszip_dll.cpp would assure identical legacy and extended flags, but in laszip_write_point(). So I don't know if I have to look at what it's done there and if the issue is somewhere else.

Nota : It works for the denoising part when I use a las file and returns a las file without all the options for writers.las (compression, minor_version, dataformat_id), so I thought it could be linked to the format but it is not the case for the DTM part.

**Comment by abellgithub** [comment]
You're running into this issue: https://github.com/LASzip/LASzip/issues/50.  You can build PDAL from source using the master or 1.8-maintenance branch to work around the problem, or you can use another input file that doesn't trigger the error.  You can also use pdal or las2las to convert the 1.4 LAS file to 1.2 as well, which will work around the problem.
