### ISSUE TITLE
Add filters.zip

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#2413]
There are merge situations where it would be handy to "zip" multiple point clouds that have the same XYZ dimensions and append new attributes upon a resultant output.  For example, consider the following scenario:

File A
===

```
X,Y,Z,Intensity
1,2,3,230
2,2,3,250
2,2,5,106
```

File B
===

```
X,Y,Z,Intensity
1,2,3,130
2,2,3,150
2,2,5,206
```

I'd like to `filters.zip` these together into 

```
X,Y,Z,FileA,FileB
1,2,3,230,130
2,2,3,250,150
2,2,5,106,206
```

Maybe we could have something like:

```
{
  "pipeline": [
    "FileA.csv",
    "FileB.csv",
    {
      "type": "filters.zip"
    },
    "output.text"
  ]
}
```

**Comment by chambbj** [comment]
This could indeed come in handy. How do you propose indicating which dimension(s) to zip and how to handle conflicts with duplicate names?

**Comment by hobu** [comment]
Maybe something like this with all of the extra dimensions being some kind of numbering scheme that isn't addressable. 

* The user can use `filters.ferry` or something if they need to move them around.
* The ordering of the `dimensions` option (which otherwise defaulted to `X,Y,Z`) defines the sorting order for determining the zip operation. Binary equality of all listed dimensions is all that is used for determining matches.

```
{
  "pipeline": [
    "FileA.csv",
    "FileB.csv",
    {
      "type": "filters.zip",
      "dimensions": "X,Y,Z"
    },
    "output.text"
  ]
}
```

**Comment by hobu** [comment]
So much easier to do this in Python with the new Python extension.
