### ISSUE TITLE
writers.ply invalid output when precision is set

### ISSUE THREAD

**Issue by klassenjs** [PDAL/PDAL#2421]
When precision is set (>0) all dimensions are output formatted as floating point numbers while the property specifications in the PLY header retain their original type.  Thus, a property declared as an integer type ends up having floating point data in it.  This causes at least some PLY readers (I've tested MeshLab and CloudCompare) to fail to read the file.

My preference is that the precision parameter would only apply to floating point dimensions (and not to integer ones).   Alternatively, the PLY file still parses correctly if the property types are listed as floats.

Simple test case:

in.ply:
```
ply
format ascii 1.0
comment Generated by PDAL
element vertex 3
property float64 x
property float64 y
property float64 z
property int32 i
end_header
1.234 2.345 3.456 10
2.345 3.456 4.567 12
0.000 0 0 0
```

commands:
```
pdal translate in.ply out.ply
pdal translate in.ply out2.ply --writers.ply.precision=3
```
out.ply:
```
ply
format ascii 1.0
comment Generated by PDAL
element vertex 3
property float64 x
property float64 y
property float64 z
property int32 i
end_header
1.234 2.345 3.456 10
2.345 3.456 4.567 12
0 0 0 0
```

out2.ply: notice the last column is declared int32 but formated as a float.
```
ply
format ascii 1.0
comment Generated by PDAL
element vertex 3
property float64 x
property float64 y
property float64 z
property int32 i
end_header
1.234 2.345 3.456 10.000
2.345 3.456 4.567 12.000
0.000 0.000 0.000 0.000
```

I'm willing to submit a PR if an approach is agreed upon.

**Comment by abellgithub** [comment]
I don't know that anything is wrong with this. Do you have reason to
believe that it is?

**Comment by klassenjs** [comment]
I don't know if it is writing technically an invalid PLY or not, but the PLY it creates is rejected by CloudCompare and MeshLab.

Ah heck, it looks like my trimmed down example isn't triggering the error in MeshLab.  On a large dataset (laz source) where I first noticed the issue, I had tested changing the int32's to float64's and it allowed MeshLab to read it.

CloudCompare (2.9.1) still fails on out2.ply with the message: "An error occurred while loading 'out2': reading error (no access right?)".  CloudCompare reads out.ply fine (and yes they have the same permissions).

**Comment by abellgithub** [comment]
On Sat, Mar 23, 2019, 8:54 PM Jim Klassen <notifications@github.com> wrote:

> I don't know if it is writing technically an invalid PLY or not, but the
> PLY it creates is rejected by CloudCompare and MeshLab.
>

Please open an issue. If you want to fix it with a PR as well, that would
be great.

>
>

**Comment by abellgithub** [comment]
You're welcome to look over/test this branch: https://github.com/PDAL/PDAL/tree/issue-2421

**Comment by klassenjs** [comment]
You beat me to it.  Looks good to me.  Thanks!

**Comment by abellgithub** [comment]
Large integers may be written with 'g' format.

**Comment by abellgithub** [comment]
Close via #2467.
