### ISSUE TITLE
1.9-rc1 fails to detect NumPy (PythonInterp & PythonLibs out of sync)

### ISSUE THREAD

**Issue by sebastic** [PDAL/PDAL#2431]
The Debian package build for PDAL 1.9-rc1 failed due to failing to detect NumPy because it uses the python3 interpreter:
```
Setting up python-numpy (1:1.16.2-1) ...
...
-- Numpy output: 
CMake Error at /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find NumPy (missing: NUMPY_VERSION NUMPY_INCLUDE_DIR) (Required
  is at least version "1.5")
Call Stack (most recent call first):
  /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindNumPy.cmake:32 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  cmake/python.cmake:21 (find_package)
  plugins/python/CMakeLists.txt:5 (include)
...
//Path to a program.
PYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3

//Path to a file.
PYTHON_INCLUDE_DIR:PATH=/usr/include/python2.7

//Path to a library.
PYTHON_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libpython2.7.so
```

Looks like `PythonInterp` & `PYTHON_LIBRARY` are out of sync, and python3 should not be used for `PYTHON_EXECUTABLE` when `PYTHON_LIBRARY` is for 2.7.

**Comment by abellgithub** [comment]
What is the python configuration that's available? Should I be able to find both python 2 and 3 interpreter and libraries?

We attempt to find python3 first. Do you know anything about dealing with both installations on one system?

**Comment by sebastic** [comment]
python-all-dev & python-numpy are included in the build dependencies for the Python support in PDAL, python3 is pulled in via sphinx.

The comment in `cmake/python.cmake` claims that the `PythonInterp` will be used to to find the version of the library, but that doesn't seem to be the case, or python3 just reports that `libpython2.7.so` should be used.

You may need to specify the version for `PythonLibs` too, e.g.:
```
find_package(PythonInterp 2.7)
find_package(PythonLibs 2.7)
```
Loop over this for the python versions an use the first that has a match for both.

**Comment by abellgithub** [comment]
Yeah. Was mostly curious because this code changed to deal with essentially
this problem on another platform. Grrr.

**Comment by sebastic** [comment]
I've worked around this issue by switching the package to Python 3, Python 2 EOL is at the end of the year anyway.

**Comment by hobu** [comment]
We will be dropping explicit Python 2 support when we release PDAL 2.0 at the end of summer.

**Comment by sebastic** [comment]
So I guess this issue mostly affects people building PDAL on RHEL/CentOS where Python 3 is only in EPEL?
