### ISSUE TITLE
How do I install PDAL in google colab?

### ISSUE THREAD

**Issue by rejivipin** [PDAL/PDAL#2432]
I tried to install PDAL in Google Colab using pip:

!pip install PDAL
But it gave the following error:

![1](https://user-images.githubusercontent.com/33048649/55318043-6569cd80-548f-11e9-9793-5c29d144bfe4.png)

How can I solve this?

**Comment by abellgithub** [comment]
This doesn't seem like a PDAL issue.

@chambbj : Do you know anything about Google Colab?

**Comment by chambbj** [comment]
I don't. It looks like some people have had luck first installing conda on
colab, where you could then install PDAL, but I've never tried.

**Comment by hobu** [comment]
This doesn't seem like a PDAL issue in any way.

**Comment by rejivipin** [comment]
Now I have a new problem in colab.
I tried this way out:
!wget https://anaconda.org/mathieu/pdal/2.0.0/download/linux-64/pdal-2.0.0-py36_0.tar.bz2
!tar xvjf pdal-2.0.0-py36_0.tar.bz2
!!pip install pdal

and when i try to import it:
import pdal
I get this error:
![image](https://user-images.githubusercontent.com/33048649/55861641-6805aa80-5b94-11e9-8382-59987e18afa8.png)

and if I don't import and directly use it in my python program:
I get an error like this:
PDAL: STDIN: Couldn't create filter stage of type 'filters.neighborclassifier'.
I am using this pipeline in my code:
 pipeline = {"pipeline":[
                    ipath,
                    {"type":"filters.neighborclassifier","k":FLAGS.n_angles*4+1,"candidate":cpath}, opath]}

Please help me.  I am stuck at this point.

**Comment by abellgithub** [comment]
We have no experience with Google Colab.

The ImportError seems like a path issue.  Make sure the referenced library is installed in a location that can be found by your python install/Colab.

The second error also seems like an initialization issue of the PDAL library from Google Colab.  The filters are usually initialized when the library is loaded.  There is special code to do this as part of the python extension, but it seems as if it's not being properly run.

**Comment by chambbj** [comment]
I'd also point out that you appear to be using a third-party Conda package,
not ours. That one is pretty old (last I checked), and so may not be 100%
up-to-date.

**Comment by pournami123** [comment]
Thanks for the reply.
@chambbj  if so can you please give me the link of a pdal Linux distribution, since I am pretty confused at this moment

**Comment by chambbj** [comment]
Although this is not directly a PDAL problem, I thought I'd share that I have had success with the following:

```
!wget https://repo.continuum.io/miniconda/Miniconda3-4.5.4-Linux-x86_64.sh && bash Miniconda3-4.5.4-Linux-x86_64.sh -bfp /usr/local
import sys
sys.path.append('/usr/local/lib/python3.6/site-packages')
!conda install -y -q -c conda-forge python-pdal

```

**Comment by pournami123** [comment]
@chambbj Great....
It worked for me... thank you so much...

**Comment by WalidGharianiEAGLE** [comment]
@chambbj I've tired your suggested solution but I got the following `ImportError: cannot import name 'libpdalpython' from 'pdal' (/usr/local/lib/python3.8/site-packages/pdal/__init__.py)`. What would you suggest to fix this? Thanks!

**Comment by AndyCarter-NOAA** [comment]
Wow... getting PDAL to install on 'Google Collab' is a real chore.  Anybody out there had recent success (2021)?

**Comment by chambbj** [comment]
@AndyCarter-NOAA You have to jump through a few hoops, but it's possible using Conda. Take a look at this [example](https://colab.research.google.com/drive/1S9Mm4lBHrUefIKTPgpDhEHTu2fwMMLc4?usp=sharing).

**Comment by AndyCarter-NOAA** [comment]
@chambbj Hey... that works great getting pdal installed on that google machine instance.... however, I am still having a problem importing pdal into the Google Colab's Python.  This may be a similar issue to the GDAL installed on a Conda env... but I don't know.

[gdal issues link](https://gis.stackexchange.com/questions/364421/how-to-make-proj-work-via-anaconda-in-google-colab)

Any thoughts would be appreciated.

![pdal_google_colab](https://user-images.githubusercontent.com/79324516/143938648-c7029bef-c37a-4652-b407-1b70d2ceb3e8.png)

**Comment by andycarter-pe** [comment]
Thanks to @hobu I was able to get PDAL running on Google Colab.

![pdal_google_colab_3](https://user-images.githubusercontent.com/65196014/146618803-fd92fc96-c408-486e-8367-73a3de0454c6.png)
