### ISSUE TITLE
Inconsistent results from colorization filter through Python bindings

### ISSUE THREAD

**Issue by gadomski** [PDAL/PDAL#2437]
@jomey has classifications in a tif file. He uses `filters.colorization` to classify his points for filtering. Example data are here: [data.zip](https://github.com/PDAL/PDAL/files/3034081/data.zip).

```json
{
    "pipeline": [
        "points.laz",
        {
            "type": "filters.colorization",
            "raster": "classes.tif",
            "dimensions": "Red:1"
        },
        {
            "type": "filters.range",
            "limits": "Red[0:2]"
        },
        {
            "filename": "output.laz",
            "forward": "all",
            "dataformat_id": 0
        }
    ]
}
```

When I run this pipeline via `pdal pipeline`, I always get an output file with 184757 points. When I run this pipeline via my PDAL bindings, I sometimes get an output file with 56 points and sometimes with 297843 points (all the original points). My Python script looks like this:

```python
#!/usr/bin/env python3

"""Run a PDAL pipeline through the Python bindings."""

import sys
import pdal

def main():
    """The main function."""
    print(pdal.getDebugInformation())
    if len(sys.argv) != 2:
        raise "Invalid number of arguments: {}".format(len(sys.argv))
    with open(sys.argv[1]) as infile:
        json = infile.read()
    pipeline = pdal.Pipeline(json)
    pipeline.validate()
    pipeline.execute()

if __name__ == '__main__':
    main()
```

I've nuked and rebuilt PDAL and my Python bindings, and I've ensured both `pdal --version` and `pdal.getDebugInformation()` report that they are built against PDAL 4ab8c0a56752e58ffae4cb041d8e0b0d80cb4014.

**Comment by abellgithub** [comment]
Do you have the same issue without the colorization filter?

**Comment by gadomski** [comment]
No, when I take away the colorization filter, both `pdal pipeline` and the Python version produce an output file with the same number of points. Note that there's no filtering going on without the colorization filter, so it's just a pass-through pipeline.

**Comment by jomey** [comment]
I also would like to note that when using the Python bindings from either conda-forge or installing via pip install that the above pipeline does not write an output file for me. It executes the pipeline fine, but no output is written to disk.

This only happened with the above colorization and filter combination. Using a different pipeline (e.g. `filters.crop`, the `pdal.execute()` does write the output.

Let me know if that should be logged separately.

**Comment by abellgithub** [comment]
I can't recreate this with the master branch. Please re-open if you can currently recreate.
