### ISSUE TITLE
EPT reader resolution/addons explained

### ISSUE THREAD

**Issue by sunapi386** [PDAL/PDAL#2443]
In the [readers.ept](https://pdal.io/stages/readers.ept.html) documentation, descriptions for "resolution" and "addons" are non-existent. These are in the source code, but could use more elaboration and examples uses.

```c++
void EptReader::addArgs(ProgramArgs& args)
{
    args.add("bounds", "Bounds to fetch", m_args.boundsArg());
    args.add("origin", "Origin of source file to fetch", m_args.originArg());
    args.add("threads", "Number of worker threads", m_args.threadsArg());
    args.add("resolution", "Resolution limit", m_args.resolutionArg());
    args.add("addons", "Mapping of addon dimensions to their output directory",
            m_args.addonsArg());
}
```
@connormanning

**Comment by abellgithub** [comment]
The documentation reflects the current release (1.8). The features you note
are not part of the 1.8 release.
