### ISSUE TITLE
pdal translate and las2txt

### ISSUE THREAD

**Issue by Yukon-climate** [PDAL/PDAL#2445]
Hello,
I am trying to use fewer tools to process my las files, I am already using Pdal for a few things but I am having issues with pdal translate. 
I use to use las2txt in a really easy way without fancy options and I was kind of expecting to be able to just do pdal translate 1.las 1.txt and get a similar ouptut, however the file obtained is 4 times bigger and not recognized by my other scripts.
I believe that las2txt was based on Pdal so I am trying to find out what is actually being called for the las2txt command :
`las2txt -v -i "20180720_0631_00.las" -parse xyz`

**Comment by abellgithub** [comment]
This is incorrect.  las2txt has nothing to do with PDAL.  You should join the mailing list and ask such questions [there](https://pdal.io/community.html).

Without knowing your PDAL command I can't comment further.

**Comment by Yukon-climate** [comment]
Thank you I will take a look. For now I was just doing `pdal translate 1.las 1.txt` but some argument seem to be missing or options. I go from a 50Mb LAS file to 200Mb txt.

**Comment by abellgithub** [comment]
You should read the documentations for the text writer:

https://pdal.io/stages/writers.text.html#writers-text

Text writer options can be specified when using `pdal translate`.  For example:

`pdal translate 1.las 1.txt --writers.text.keep_unspecified=false --writers.text.order="X,Y,Z"
