### ISSUE TITLE
EPT reader currently doesn't pluck out per-source-file metadata into PDAL metadata

### ISSUE THREAD

**Issue by msmitherdc** [PDAL/PDAL#2446]
Currently per source file metadata is not populated when the EPT reader fetches a specific file from a resource. The original file cannot be reconstructed without this. 

Example:  `pdal info --metadata  ept://resource --readers.ept.origin=filename` should return the original metadata

**Comment by connormanning** [comment]
Additionally, a query like this could provide the original sort order in many cases, which it currently doesn't do.  The precedence for this is probably the `PointId` dimension if present, falling back to the more typical implicit ordering via the `GpsTime`.  This would probably not be possible in streaming mode (#2439) though.

**Comment by hobu** [comment]
this 🐴 is 💀. Reopen if this is ever going to actually be addressed.
