### ISSUE TITLE
Segfault in gdal::Band due to integer overflow

### ISSUE THREAD

**Issue by mikethefarmer** [PDAL/PDAL#2454]
Issue #2448 has not been solved by #2450.  

Upon running the same test set as in #2448 PDAL 1.90 also segfaulted.  The full BT (now that I know there is more than one  BT) [PDAL_btFull_1.9.0(std).txt](https://github.com/PDAL/PDAL/files/3067190/PDAL_btFull_1.9.0.std.txt) showed that wholeRowElts was negative (which was clearly wrong) and probably an overflow.  I added some more local parameters (so I could see other values - having no other idea how to) which reflected m_xBlockSize as xBlockSize etc.  The result was [PDAL_btFull_1.9.0(local param).txt](https://github.com/PDAL/PDAL/files/3067242/PDAL_btFull_1.9.0.local.param.txt).  

As can be seen, when you calculate wholeRowElts = 85100*((25235*1)+0) = 2147498500 (0x80003a04), the result is greater than a signed int, and hence returns the neg value seen in the BT.

Changing wholeRowElts (and partialRowElts for good measure) in GDALUtils.hpp lines 486/7 to 'long' appeared to solve the issue as below:

long wholeRowElts = (long)m_xTotalSize * ((y * m_yBlockSize) + row);
long partialRowElts = (long)m_xBlockSize * x;

I haven't done a change/pull as not sure whether this meets coding requirements and have only undertaken limited testing (though these are local variables only used with a 64-bit address so should not have any other unintended effects).  They may need to be changed to 'long long' or a platform independent type (which suitable type is beyond my knowledge) for cross-platform consistency. This change (combined with #2450) resulted in successful execution of the test command from #2448, as well as the original --nostream pipeline that triggered #2448.

If change agreed, request that this and #2450 be included in 1.8-maintenance branch (as the stable GDAL in Ubuntu 16.04 < 2.2)

**Comment by abellgithub** [comment]
On Thu, Apr 11, 2019, 4:21 AM mikethefarmer <notifications@github.com>
wrote:

> Issue #2448 <https://github.com/PDAL/PDAL/issues/2448> has not been
> solved by #2450 <https://github.com/PDAL/PDAL/pull/2450>.
>
> Upon running the same test set as in #2448
> <https://github.com/PDAL/PDAL/issues/2448> PDAL 1.90 also segfaulted. The
> full BT (now that I know there is more than one BT)
> PDAL_btFull_1.9.0(std).txt
> <https://github.com/PDAL/PDAL/files/3067190/PDAL_btFull_1.9.0.std.txt>
> showed that wholeRowElts was negative (which was clearly wrong) and
> probably an overflow. I added some more local parameters (so I could see
> other values - having no other idea how to) which reflected m_xBlockSize as
> xBlockSize etc. The result was PDAL_btFull_1.9.0(local param).txt
> <https://github.com/PDAL/PDAL/files/3067242/PDAL_btFull_1.9.0.local.param.txt>
> .
>
> As can be seen, when you calculate wholeRowElts = 85100*((25235*1)+0) =
> 2147498500 (0x80003a04), the result is greater than a signed int, and hence
> returns the neg value seen in the BT.
>
> Changing wholeRowElts (and partialRowElts for good measure) in
> GDALUtils.hpp lines 486/7 to 'long' appeared to solve the issue as below:
>
> long wholeRowElts = (long)m_xTotalSize * ((y * m_yBlockSize) + row);
> long partialRowElts = (long)m_xBlockSize * x;
>
Astounded I had no trouble with this on either mac or Ubuntu VM. Sure helps
to be able to recreate. If I had done the math on the y index I would have
seen this, though when you see one issue, you stop looking for others.

>

**Comment by mikethefarmer** [comment]
What I did find through lots of research (mainly trying to get to terms with unfamiliar tools etc) is that not only is int dependent on OS but on underlying systems (inc CPU).  I actually had to run some small code snippets to ensure that in my config int was 32bit and long 64!  Hence there may be a better type (ie more consistent) to use rather than long?

BTW on my iMac (17,1 Mojave) int is definitely 32 bit.

**Comment by abellgithub** [comment]
Closing in favor of reopening other #2448

**Comment by abellgithub** [comment]
Almost all 64-bit systems use 32-bit int and 64-bit long, but yes, there are better ways.  32-bit systems usually use 32-bit int and 32-bit long.

I know better, but got sucked into ints because the GDAL interface is integers.  I'll modify appropriately.

**Comment by abellgithub** [comment]
If you want to checkout https://github.com/PDAL/PDAL/tree/issue-2454, that would be great.

**Comment by mikethefarmer** [comment]
Figuratively checked out (I only downloaded unmanaged before so did again) and it tested OK with the supplied test.  Much better code than mine.

As above, can we include this (and #2448) in 1.8-Maintenance branch as well. Not sure how ODM will want to handle (using 1.8-Maint, forking 1.8 and applying, or something else)
