### ISSUE TITLE
EPT reader - Performance question

### ISSUE THREAD

**Issue by nicolas-chaulet** [PDAL/PDAL#2457]
Hi, for some reason the ept reader is quite slow compared to reading a single LAZ and does not even seem to use 100% of cpu when run on a local file system. Am I the only one seeing this behaviour? Not sure what the reason is for this sub optimal cpu usage, maybe lot's of small files (<1M) to read? 

@connormanning  do you see a good reason for not remove the lock [there](https://github.com/PDAL/PDAL/blob/fc5e6bb58f626cc0297150e5f35c6428d40048e1/io/EptReader.cpp#L558) and making each thread operate on a new `PointView`? We can then merge those views or leave the undrelying Pdal logic to perform the merge? 
I'm thinking that this would greatly improve the performance even on remote files. Looking forward to hearing your views on that one.

**Comment by abellgithub** [comment]
I think if separate point tables are used for the LAS reading, the lock can
be eliminated until the destination point view is accessed. Don't know if
that would help.

**Comment by connormanning** [comment]
At the very least, that lock should be unlocked during `LasReader::execute`.  Oops - my mistake.  @nicolas-chaulet can you test out branch https://github.com/PDAL/PDAL/tree/ept-reader-unlock.  That's a pretty minimal change that'll be a big benefit for local EPT datasets.  Maybe not so noticeable for remote ones where IO is much more dominant, though.

**Comment by nicolas-chaulet** [comment]
@connormanning it did not help much. At the start cpu usage is good (mutli threading behaves nicely) but then it quickly drops to something like 60%. I compared against reading the same file in laz format (128M points) and it takes around 250s for the ept reader against 99s for the laz reader. I also have some malloc failures occasionaly `malloc: *** error for object 0x7fd06f60ad00: pointer being freed was not allocated`. Not sure that helps, I'll do some digging on my end as well.

**Comment by connormanning** [comment]
Interesting.  A stack trace for the malloc error would be helpful if you could capture it in gdb.  You might also take a look at the [ept-reader-parallel](https://github.com/PDAL/PDAL/tree/ept-reader-parallel) branch, I did some tinkering there on parallel per-point processing.

**Comment by nicolas-chaulet** [comment]
@connormanning I had a look at that again and it seems that the problem was somewhere else, I seem to remember some commits in May that were addressing an issue with multiple las readers. ept-reader-unlock and ept-reader-parallel seem to work fine. I tried multiple times and tried to reproduce the malloc error without luck. 

Should we move forward with the ept-reader-parallel which is a bit more performant and uses all threads quite efficiently? Happy to update with master and submit a PR if that works for you.

**Comment by connormanning** [comment]
> Happy to update with master and submit a PR if that works for you.

Fine by me.
