### ISSUE TITLE
Can't build MrSID plugin

### ISSUE THREAD

**Issue by johntwill** [PDAL/PDAL#2460]
`[158/396] Building CXX object plugins/..._reader_mrsid.dir/io/MrsidReader.cpp.o
FAILED: plugins/mrsid/CMakeFiles/pdal_plugin_reader_mrsid.dir/io/MrsidReader.cpp.o 
/usr/bin/c++  -DHAVE_MRSID=1 -DUNIX -Dpdal_plugin_reader_mrsid_EXPORTS -I../vendor/gtest/include -I../vendor/gtest -Iinclude -I../ -I../io -I/usr/include/libgeotiff -I/opt/MrSID/Lidar_DSDK/include -fPIC   -Wall -Wextra -Wpointer-arith -Wcast-align -Wcast-qual -Wno-error=parentheses -Wno-error=cast-qual -Wredundant-decls -Wno-unused-parameter -Wno-unused-variable -Wno-long-long -Wno-unknown-pragmas -Wno-deprecated-declarations -std=gnu++11 -MD -MT plugins/mrsid/CMakeFiles/pdal_plugin_reader_mrsid.dir/io/MrsidReader.cpp.o -MF plugins/mrsid/CMakeFiles/pdal_plugin_reader_mrsid.dir/io/MrsidReader.cpp.o.d -o plugins/mrsid/CMakeFiles/pdal_plugin_reader_mrsid.dir/io/MrsidReader.cpp.o -c ../plugins/mrsid/io/MrsidReader.cpp
../plugins/mrsid/io/MrsidReader.cpp: In member function ‘void pdal::MrsidReader::LayoutToPointInfo(const pdal::PointLayout&, LizardTech::PointInfo&) const’:
../plugins/mrsid/io/MrsidReader.cpp:213:53: error: ‘CHANNEL_NAME_GPSTime’ was not declared in this scope
         if (Utils::iequals(name, "GpsTime")) name = CHANNEL_NAME_GPSTime;
                                                     ^
../plugins/mrsid/io/MrsidReader.cpp: In member function ‘virtual pdal::point_count_t pdal::MrsidReader::read(pdal::PointViewPtr, pdal::point_count_t)’:
../plugins/mrsid/io/MrsidReader.cpp:311:47: error: ‘CHANNEL_NAME_GPSTime’ was not declared in this scope
                        m_pointInfo.hasChannel(CHANNEL_NAME_GPSTime))
                                               ^
[159/396] Building CXX object plugins/...les/mrsidtest.dir/test/MrsidTest.cpp.o
ninja: build stopped: subcommand failed.
`

**Comment by abellgithub** [comment]
Apparently the MrSid API has changed.  We have no access to the MrSid API.  You will have to submit a PR with a fix.

Thanks,
