### ISSUE TITLE
Use of filters.delaunay

### ISSUE THREAD

**Issue by KillianPremel** [PDAL/PDAL#2466]
Hi, 

I try to create a ply object using the Delaunay triangulation like it is written in https://pdal.io/stages/filters.delaunay.html, it doesn't work : 
_Couldn't create filter stage of type 'filters.delaunay'_ .

When I execute _pdal --drivers_, I found out that filters.delaunay is not included.
Thanks in advance

**Comment by abellgithub** [comment]
What version of PDAL are you using?  How was it installed?

**Comment by KillianPremel** [comment]
I use pdal 1.8.0. I install it with conda in a specific environment.

**Comment by abellgithub** [comment]
In PDAL version 1.8 the delaunay filter was a plugin, but not part of the conda package.  To use this filter with a 1.8 PDAL conda package you'd have to build the plugin yourself from source.

In PDAL version 1.9 the delaunay filter is a built-in stage and has no dependencies.
