### ISSUE TITLE
add pdal::Geometry::Point class

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#2477]
It would be very convenient to have a `pdal::Geometry::Point` class, especially for one-off reprojection or geometry algebra operations.

**Comment by abellgithub** [comment]
I guess I don't know the use case.  We don't usually do anything with a single point.  There's already support for processing lots of points against geometry (filters.crop) or reprojection (filters.reprojection).

**Comment by hobu** [comment]
The use case is I have to manually use GDAL to reproject a point or do a point-in-poly test in my own filter, and it would be very convenient to have a Point class here. Is it a problem to have one?
