### ISSUE TITLE
filters.colorization output zeros

### ISSUE THREAD

**Issue by spiegelss** [PDAL/PDAL#2487]
Good afternoon,

For my point cloud classification I'm using image segmentation techniques by exporting the point cloud to a tif.  That worked great and I was able to make a labeled tif.  I would like to apply that to the point cloud now via **filters.colorization**.  I have the following pipeline:
```json
 {
            "pipeline":[
                   {
                       "type":"readers.las",
                       "filename":"input.las"
                   },
                    {
                    "type":"filters.colorization",
                    "dimensions":"Cluster:1",
                    "raster":"labeled_raster.tif"
                   },

                    {
                        "type":"writers.las",
                        "filename":"new_labeled_las.las"
                    }
                
            ]
    
    
    
}
```
via the [PDAL documentation](https://pdal.io/stages/filters.colorization.html?highlight=colorization), it appears I can make a new dimension called "Cluser".  

Everything seemed to work out, however all of my cluster values are either -2.335989e-310 or 0.0.  Am I doing something wrong?  If so I'm not sure what it is.  I can provide more information if you need.  Thanks!

**Comment by hobu** [comment]
Can you post a small raster file and small las file with the pipeline so we can work the bug?

**Comment by spiegelss** [comment]
Sure thing.  Attached is the las file (input for the TIF).  It's the autzen_trim_7.las file.  The tif contains the labels (I quickly did this so the labels may not be perfect).  
[autzen_trim_7.txt](https://github.com/PDAL/PDAL/files/3139597/autzen_trim_7.txt)
![label_img](https://user-images.githubusercontent.com/40045042/57100690-38564800-6ce5-11e9-88d6-ce83663553de.jpg)

**Comment by spiegelss** [comment]
Also I'm doing a lot of this via Jupyter notebook.  I don't know if that helps at all but I've been running the pipeline via Jupyter so I can look at normals, curvature, eigenvalues, etc.

**Comment by hobu** [comment]
Can you attached the geotiff? I don't think the jpg has coordinates so it will overlay.

**Comment by spiegelss** [comment]
Sorry I tried to attach it as a geotiff and it wouldn't let me.  I put it in a zip folder here.  I should have done that originally.
[original_crop_ground_classified_seg.zip](https://github.com/PDAL/PDAL/files/3139657/original_crop_ground_classified_seg.zip)

**Comment by hobu** [comment]
After wiping the quotes off the csv file (#2201), with the following pipeline, I appear to get good output:

```
 {
            "pipeline":[
                   {
                       "type":"readers.text",
                       "filename":"autzen_trim_7.txt"
                   },
                    {
                    "type":"filters.colorization",
                    "dimensions":"Cluster:1",
                    "raster":"original_crop_ground_classified_seg.tif"
                   },
                    {
                    "type":"filters.ferry",
                    "dimensions":"Cluster => GPSTime"
                   },
                    {
                        "type":"writers.las",
                        "filename":"labeled.las"
                    }
            ]
}
```

```
pdal info labeled.las --all --enumerate GpsTime| jq '.stats.statistic[] | select (.name == "GpsTime")'
```

```
{
  "average": 1.430534504,
  "count": 109522,
  "maximum": 36,
  "minimum": 0,
  "name": "GpsTime",
  "position": 15,
  "stddev": 5.265962562,
  "values": [
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21,
    22,
    23,
    24,
    25,
    26,
    27,
    28,
    29,
    30,
    31,
    32,
    33,
    34,
    35,
    36
  ],
  "variance": 27.7303617
}
```

**Comment by spiegelss** [comment]
sorry, **output_file** is the tif, and **las_input** is the las I'm trying to segment

**Comment by spiegelss** [comment]
Makes sense, that's basically what is happening to me.  Let me try running it from just PDAL, see if that works.  I'll try and read it in to my jupyter notebook after I do that.

**Comment by spiegelss** [comment]
Ok.  it looks like when I run the pipeline outside of PDAL, it brings it in just fine.  If it's possible, I would like to do it all within python in the future, but for now this seems to work.  Thank you!

![group_by_2](https://user-images.githubusercontent.com/40045042/57105615-ddc2e900-6cf0-11e9-9605-ac727d39c54d.JPG)

**Comment by spiegelss** [comment]
I meant outside of python, not PDAL

**Comment by hobu** [comment]
This should work properly in Python too. Reopening it until I figure it out and fix it.
