### ISSUE TITLE
PDAL to PCD conversions in ICP should compute and pass bounds

### ISSUE THREAD

**Issue by chambbj** [PDAL/PDAL#2492]
Without this, the conversion to PCD can be suspect (especially in UTM) with a direct impact on ICP results.

https://github.com/PDAL/PDAL/blob/7acd9d35855dab937f0f0a29737cb285d6cbce43/plugins/pcl/filters/IcpFilter.cpp#L91

https://github.com/PDAL/PDAL/blob/7acd9d35855dab937f0f0a29737cb285d6cbce43/plugins/pcl/filters/IcpFilter.cpp#L93

**Comment by abellgithub** [comment]
It looks like we're just scaling everything to the existing bounds box with this.  Why do we need to do this?

**Comment by chambbj** [comment]
The snippets here are the existing behavior. The conversions to PCD, when executed without providing bounds, will attempt to convert without first subtracting offsets, which can lead to loss of precision.

#2493 implements my proposed fix, which is to subtract the offsets (min bounds) of the fixed point cloud from both clouds prior to running ICP, then adding the offset back to the transformed cloud.

**Comment by abellgithub** [comment]
Wonder if this should be done in PDALtoPCD, rather than for a particular filter.  Are we using the bounds/scaling elsewhere for some other purpose?

**Comment by chambbj** [comment]
It is used in several other PCL filters, yes. The problem with simply moving it inside of PDALtoPCD is that I want to subtract a common offset in this case.

**Comment by abellgithub** [comment]
What do you mean by "common offset"?  The PR change looks like you're just offsetting by the point view bounds.

**Comment by chambbj** [comment]
The ICP filters operates on two point views: one fixed and one moving. The bounds are computed for the fixed view, but applied to both.

**Comment by abellgithub** [comment]
Ah, OK.  Thx.

**Comment by abellgithub** [comment]
Fixed by #2493
