### ISSUE TITLE
Broken links to conda on quickstart page

### ISSUE THREAD

**Issue by sunapi386** [PDAL/PDAL#2494]
Many broken links on https://pdal.io/quickstart.html 

For example, https://conda.io/docs/user-guide/getting-started.html#managing-envs. 

> It is actually a very good idea to install PDAL in it’s own environment (or add it to an existing one). You will NOT want to add it to your default environment named base. Managing environments is beyond the scope of the quickstart, but you should read more about it over at https://conda.io/docs/user-guide/getting-started.html#managing-envs.

**Comment by abellgithub** [comment]
I guess conda moved things around.  If you would like to fix the links and submit a PR that would be great.

**Comment by chambbj** [comment]
Closed via #2514
