### ISSUE TITLE
LAS header metadata output should output the header.pointLen attribute

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#2505]
There are situations where extra bytes are written into the data, but no eb VLRs are written. We can't figure out this situation right now without doing a bunch of math.

**Comment by abellgithub** [comment]
This isn't correct.  We always write an EB VLR when writing extra bytes.  If you have a case where this isn't happening, please attach a use case.

**Comment by hobu** [comment]
> We always write an EB VLR when writing extra bytes.

Other software doesn't, and we don't have a way to diagnose.

**Comment by abellgithub** [comment]
After further discussion, the issue is simply as described in the title.  The `point_length` seems to have been accidentally omitted from the LAS header metadata.
