### ISSUE TITLE
DelaunayFilterTest.cpp build failed in FreeBSD

### ISSUE THREAD

**Issue by wenheping** [PDAL/PDAL#2509]
The build log say :

/wrkdirs/usr/ports/math/pdal/work/PDAL-1.9.1/test/unit/filters/DelaunayFilterTest.cpp:95:47: error: non-constant-expression cannot be narrowed from type 'pdal::PointId' (aka 'unsigned long long') to 'unsigned int' in initializer list [-Wc++11-narrowing]
        std::vector<size_t> triangleVector = {triangle.m_a, triangle.m_b, triangle.m_c};
                                              ^~~~~~~~~~~~
/wrkdirs/usr/ports/math/pdal/work/PDAL-1.9.1/test/unit/filters/DelaunayFilterTest.cpp:95:47: note: insert an explicit cast to silence this issue
        std::vector<size_t> triangleVector = {triangle.m_a, triangle.m_b, triangle.m_c};
                                              ^~~~~~~~~~~~
                                              static_cast<unsigned int>( )
/wrkdirs/usr/ports/math/pdal/work/PDAL-1.9.1/test/unit/filters/DelaunayFilterTest.cpp:95:61: error: non-constant-expression cannot be narrowed from type 'pdal::PointId' (aka 'unsigned long long') to 'unsigned int' in initializer list [-Wc++11-narrowing]
        std::vector<size_t> triangleVector = {triangle.m_a, triangle.m_b, triangle.m_c};
                                                            ^~~~~~~~~~~~
/wrkdirs/usr/ports/math/pdal/work/PDAL-1.9.1/test/unit/filters/DelaunayFilterTest.cpp:95:61: note: insert an explicit cast to silence this issue
        std::vector<size_t> triangleVector = {triangle.m_a, triangle.m_b, triangle.m_c};
                                                            ^~~~~~~~~~~~
                                                            static_cast<unsigned int>( )
/wrkdirs/usr/ports/math/pdal/work/PDAL-1.9.1/test/unit/filters/DelaunayFilterTest.cpp:95:75: error: non-constant-expression cannot be narrowed from type 'pdal::PointId' (aka 'unsigned long long') to 'unsigned int' in initializer list [-Wc++11-narrowing]
        std::vector<size_t> triangleVector = {triangle.m_a, triangle.m_b, triangle.m_c};
                                                                          ^~~~~~~~~~~~
/wrkdirs/usr/ports/math/pdal/work/PDAL-1.9.1/test/unit/filters/DelaunayFilterTest.cpp:95:75: note: insert an explicit cast to silence this issue
        std::vector<size_t> triangleVector = {triangle.m_a, triangle.m_b, triangle.m_c};
                                                                          ^~~~~~~~~~~~
                                                                          static_cast<unsigned int>( )
3 errors generated.

**Comment by abellgithub** [comment]
What compiler/version are you using?
