### ISSUE TITLE
PDAL crashes on empty text file input

### ISSUE THREAD

**Issue by plimkilde** [PDAL/PDAL#2513]
PDAL segfaults when an empty file is passed to `readers.text`.

**Comment by plimkilde** [comment]
Well, at least when the Delaunay filter is used. Minimal sample pipeline (tested on Windows, PDAL 1.9.0):
```
[
    "emptytest.txt",
    {
        "type":"filters.delaunay"
    },
    {
        "type":"writers.null"
    }
]
```

**Comment by plimkilde** [comment]
Sorry about the lack of useful details earlier, I've now been able to reproduce the error on Ubuntu with PDAL built from the most recent commit as of this writing (489fb20).

It seems to originate in the Delaunay part. GDB log with the above pipeline and an empty text file (not including `readers.text`'s warning to `stderr`):
```
Starting program: /[REDACTED]/bin/pdal pipeline delaunay-empty-pipeline.json
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe0149700 (LWP 13706)]
[New Thread 0x7fffdf948700 (LWP 13707)]
[New Thread 0x7fffdb147700 (LWP 13708)]

Thread 1 "pdal" received signal SIGSEGV, Segmentation fault.
0x00007ffff74db54c in delaunator::Delaunator::Delaunator (this=0x7fffffffd040, 
    in_coords=std::vector of length 0, capacity 0)
    at /[REDACTED]/PDAL/filters/private/delaunator.hpp:291
291	    const double i0x = coords[2 * i0];
```

**Comment by abellgithub** [comment]
You can test https://github.com/PDAL/PDAL/tree/issue-2513 if you like.
