### ISSUE TITLE
New dimension with filters.ferry: how to set its data type?

### ISSUE THREAD

**Issue by jliempt** [PDAL/PDAL#2532]
I am trying to create a new dimension in my point cloud with filters.ferry, and to consequently assign values to it in a Python script (with filters.python). The values are rather big - 15 digits each, and stored in an array with dtype=uint64.

Running the pipeline, I am getting the following error:
PDAL: dtype of array has size 80 but PDAL dimension 'bag_id' has byte size of 8 bytes.

However, I can't seem to figure out how to set the type of my created dimension.

Pipeline:

 ```
{
    "pipeline":
    [
        {
                	"type":"readers.las",
                	"filename":"MLS_pmf_and_bag_filtered_subset.las"
        },
		{
			"type":"filters.ferry",
			"dimensions":"=>bag_id"
		},
        {
                	"type":"filters.python",
			"add_dimension":"bag_id",
                	"module":"anything",
                	"function":"bag_id",
                	"script":"bag_link.py"				
        },
		{
			"type":"writers.las",
			"filename":"bag_test.las",
			"extra_dims":"all"
		}
    ]
}
 ```

The piece of code that is supposed to assign values to the created dimension:

> outs['bag_id'] = a_uint64_array

**Comment by abellgithub** [comment]
The ferry filter always creates dimension as double-precision floating point.  The error that you're generating is coming from the python filter, and it believes the numpy array you're trying to assign to `bag_id` has 80 byte entries.  I'd have to see the python code to comment more, but there's no way we can store an 80 byte entry into a PDAL dimension.

Perhaps users should be able to specify the size of dimensions that are created by `filters.ferry` or `filters.python`.

**Comment by jliempt** [comment]
Thank you for your swift response! I have now cast the array to float64 and while it is not ideal, it's working. Indeed it would be nice to be able to specify the dimension type.
