### ISSUE TITLE
proj_create_from database: Cannot find proj.db

### ISSUE THREAD

**Issue by AmmarAkran** [PDAL/PDAL#2544]
Hi,
This error is showing when I try to perform this filter "filters.crop"
FYI, This error did not happen before, but after I have formatted my PC and install pdal with its all dependencies this what I got when try to perform that filter :

proj_create_from database: Cannot find proj.db
proj_create_from database: Cannot find proj.db
proj_create_from database: Cannot find proj.db

I am sorry for my bad english.

**Comment by hobu** [comment]
I believe this is related to GDAL's update to 3.0 in Conda.

**Comment by abellgithub** [comment]
This is indeed an issue with the proj library.  Normally when the library is built, a directory is embedded that indicates where the database can be found.  You can override this location by setting an environment variable "PROJ_LIB", whose value should be the directory containing the file "proj.db".

**Comment by hobu** [comment]
I think the conda package needs to be properly setting PROJ_LIB.

**Comment by abellgithub** [comment]
When you build, the default value is set to ${CMAKE_INSTALL_PREFIX}/${DATADIR}

**Comment by AmmarAkran** [comment]
As you suggest by setting the environment variable "PROJ_LIB" to the directory containing the file "proj.db". It was a good suggestion and solved my problem in the local PC.

After that, I have built a docker image including pdal and all its depencencies, and I then deploy it to the IBM cloud , but unfortunately there is another error appeared that is:  
```stderr: proj_create_from_database: Open of /opt/conda/share/proj failed"
   stderr: proj_create_from_database: Open of /opt/conda/share/proj failed"
   stderr: proj_create_from_database: Open of /opt/conda/share/proj failed"
   stderr: proj_create_from_database: Open of /opt/conda/share/proj failed"
   pj_obj_create: Open of /opt/conda/share/proj failed"```

Also I created an environment for pdal and its dependencies, but the same problem. Could I find a solution or any suggestion?

**Comment by abellgithub** [comment]
I have no idea what you've done or why you'd be seeing that message.  Sorry.

**Comment by hobu** [comment]
> I have no idea what you've done or why you'd be seeing that message. Sorry.

We are seeing this in new GDAL 3.0 conda builds of PDAL now

**Comment by MBrandt-NASA** [comment]
I see "Cannot find proj.db" using pdal 2.0.2, gdal 3.0.2, proj 6.2.1 -- all installed with conda-forge.  I can see that conda is indeed setting the environment variable in my conda env:
PROJ_LIB= ... /anaconda3/envs/gdal/share/proj, which contains proj.db, so I'm not sure why it's complaining that it can find proj.db.

Specifically, I see these errors when reading a GeoTiff with readers.gdal:

(readers.gdal Error) GDAL failure (1) PROJ: pj_obj_create: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: createGeodeticReferenceFrame: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_as_wkt: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_create_from_wkt: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_as_wkt: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_create_from_wkt: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: createGeodeticReferenceFrame: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: pj_obj_create: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_as_wkt: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_as_wkt: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_create_from_wkt: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_as_wkt: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_create_from_wkt: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_as_wkt: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_create_from_wkt: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_as_wkt: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_create_from_wkt: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_create_from_wkt: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_create_from_wkt: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_as_proj_string: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_create_from_wkt: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_as_wkt: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_create_from_wkt: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_as_wkt: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_create_from_wkt: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_as_wkt: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_create_from_wkt: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_create_from_wkt: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_as_wkt: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_create_from_wkt: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_create_from_wkt: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_create_from_wkt: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_as_proj_string: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_create_from_wkt: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_as_wkt: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_create_from_wkt: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_as_wkt: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_create_from_wkt: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_as_wkt: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_create_from_wkt: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: pj_obj_create: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: createGeodeticReferenceFrame: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_as_wkt: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_create_from_wkt: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_as_wkt: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_create_from_wkt: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: createGeodeticReferenceFrame: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: pj_obj_create: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_as_wkt: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_as_wkt: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_create_from_wkt: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_as_wkt: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_create_from_wkt: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_as_wkt: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_create_from_wkt: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_as_wkt: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_create_from_wkt: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_create_from_wkt: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_create_from_wkt: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_as_proj_string: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_create_from_wkt: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_as_wkt: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_create_from_wkt: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_as_wkt: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_create_from_wkt: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_as_wkt: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_create_from_wkt: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_create_from_wkt: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_as_wkt: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_create_from_wkt: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_create_from_wkt: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_create_from_wkt: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_as_proj_string: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_create_from_wkt: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_as_wkt: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_create_from_wkt: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_as_wkt: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_create_from_wkt: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_as_wkt: Cannot find proj.db
(readers.gdal Error) GDAL failure (1) PROJ: proj_create_from_wkt: Cannot find proj.db

Process finished with exit code 0

**Comment by MBrandt-NASA** [comment]
I mean using pdal 2.0.1...  typo.

**Comment by hobu** [comment]
Can you recreate a new environment and retest? I recently incremented the PDAL conda build which has about a 12.34% chance of fixing this issue.

` conda update --all` 

Conda has this bad habit of nuking environment variables for GDAL_DATA and PROJ_LIB, but I don't understand which situations it is happening in.

**Comment by E3V3A** [comment]
Why was this closed??

**Comment by sudhirsilwal23** [comment]
Try setting below environment for anaconda as there is no proper solution available. write below lines in your code for smooth execution

import os
os.environ['GDAL_DATA'] = '/home/server/anaconda3/share/gdal'
os.environ['PROJ_LIB'] = '/home/server/anaconda3/share/proj'

**Comment by sudhirsilwal23** [comment]
And why was this thread closed on 1 Jan 2020?

**Comment by antoinebio** [comment]
Hi,
I've just tested on 2 different machines.
on the first machine where PDAL was "run" on (base) I've got the same kind of behaviour => ...Cannot find proj.db
on the second machine where PDAL was "run" on (myenv) the tindex is working fine without "Cannot find proj.db" alert...
however it looks like the tindex function disregards the Native bbox and CRS of the input LAZ... 
![image](https://user-images.githubusercontent.com/30265851/83743033-6fbac500-a65a-11ea-978a-8a1e552a266e.png)

consequenlty the resulting SHP is written in EPSG4326 (lat/long) and not in the source CRS of the LAZ...
any reason for that ?

**Comment by haytastan** [comment]
I can not find  the file **proj.db** either when I run the python code **harita.py** (see below) in eclipse IDE with pre-defined paths  in **pyqgis-eclipse.bat** (see below)

**The errors I got are**
_proj_create_from_wkt: Cannot find proj.db
proj_identify: Cannot find proj.db
ERROR 1: PROJ: proj_identify: Cannot find proj.db_
***************************************************************
**pyqgis-eclipse.bat:**
@echo off
rem pyqgis-eclipse.bat
rem ===================================================
rem Hayati TAŞTAN, PhD in Geospatial IT
rem 23.07.2020
rem ===================================================
set OSGEO4W_ROOT=C:\OSGeo4W64
call "%OSGEO4W_ROOT%"\bin\o4w_env.bat"
call "%OSGEO4W_ROOT%"\bin\qt5_env.bat
call "%OSGEO4W_ROOT%"\bin\py3_env.bat
call "%OSGEO4W_ROOT%\apps\grass\grass78\etc\env.bat"

path %PATH%;%OSGEO4W_ROOT%\apps\qgis\bin;
path %PATH%;%OSGEO4W_ROOT%\apps\grass\grass78\lib;

path %PATH%;%OSGEO4W_ROOT%\apps\Qt5\bin
path %PATH%;%OSGEO4W_ROOT%\apps\Python37\Scripts

set QT_QPA_PLATFORM_PLUGIN_PATH=%OSGEO4W_ROOT%\apps\Qt5\plugins\platforms
set QGIS_PREFIX=%OSGEO4W_ROOT%\apps\qgis
set PYTHONHOME=%OSGEO4W_ROOT%\apps\Python37
set PYTHONPATH=%PYTHONPATH%; %OSGEO4W_ROOT%\apps\qgis\python;
set PYTHONPATH=%PYTHONPATH%;%OSGEO4W_ROOT%\apps\Python37\lib\site-packages

set PATH=%PATH%;C:\Program Files\Git\bin

set QT_PLUGIN_PATH=%OSGEO4W_ROOT%\apps\qgis\qtplugins;%OSGEO4W_ROOT%\apps\qt5\plugins
set GDAL_FILENAME_IS_UTF8=YES
set VSI_CACHE=TRUE
set VSI_CACHE_SIZE=1000000

set PATH=%PATH%;C:\Program Files\JetBrains\PyCharm 2020.1\bin"
set ECLIPSE="C:\Users\hayati.tastan\eclipse\jee-2020-06\eclipse\eclipse.exe"

set JAVA_HOME="C:\Program Files\Java\jdk1.8.0_261"
set PATH=%PATH%;%JAVA_HOME%\bin

set PROJ_LIB="C:\OSGeo4W64\share\proj"
set PATH=%PATH%;%PROJ_LIB%

start "Eclipse with QGIS 3.14" /B %ECLIPSE% %*

cmd.exe

************************************************************************************
**harita.py:**
#===================================================
#harita.py 
#Hayati TAŞTAN, Phd in Geospatial IT
#23.07.2020
#===================================================
import subprocess
subprocess.call('python-qgis', shell=True)
from qgis.core import *
from qgis.gui import *
from PyQt5 import *
from PyQt5.QtGui import *
from PyQt5.QtCore import *
from PyQt5.QtWidgets import *


import sys
import os
        canvas.setLayers([layer])

        layout = QVBoxLayout()
        layout.addWidget(canvas)
        contents = QWidget()
        contents.setLayout(layout)

        self.setCentralWidget(canvas)

viewer = MapViewer("C:/OSGeo4W64/data/vector/iller/iller.shp")
viewer.show()
app.exec_()

QgsApplication.exitQgis()

**Comment by steo85it** [comment]
As info, within a linux installation using spack, I managed to remove the warning (which became an error in pyproj@2.6.1) by setting the PROJ_LIB variable to the proj share dir (where proj.db is) located; e.g.,
export PROJ_LIB=$SPACK_ROOT/opt/spack/linux-debian8-broadwell/gcc-9.3.0/proj-6.3.1-wosgaaf7fqh5u7iaiu4ucpbkyk2l5tv4/share/proj

**Comment by disarticulate** [comment]
hot fix in conda appears to be:
```
import os
os.environ['PROJ_LIB'] = '/opt/conda/share/proj'
```
There's certainly some strange incorrect setting, since the error:
```
pj_obj_create: Open of /opt/conda/share/proj failed
```
Is non-sensical in the locality, since this folder does exist, but it's not a file
_shrug_
