### ISSUE TITLE
Interpolating points to grid with writers.gdal IDW produced unexpected results

### ISSUE THREAD

**Issue by AndrewCunliffe** [PDAL/PDAL#2545]
While using writers.gdal to interpolate a raster from four points, we encountered some unexpected behaviour. Together, these issues cause IDW in writers.gdal to function very differently to IDW implemented in other geospatial software (e.g. ArcGIS, QGIS, Surfer). 

1. Values were only returned for cells in columns or rows containing at least one point, resulting in holes in the raster. We expected a continuous surface across the entire area, bounded by Xmax/Xmin and Ymax/Ymin. This behaviour appears to be independent of the radius argument, as this parameter was set much higher (~10) than the actual distance between points (~1). This issue probably only appears when resolution is lower than point spacing.

2. Interpolation only actually happened for cells lying on an intersection of rows or columns containing two or more points. In columns or rows containing a single point, all cells have the exactly the same value as the point. This is not how spatial interpolation should work, and results in artificial striping of the resultant raster.

3. Implementations of IDW normally take a ‘power’ argument, to control the distance weighting. There does not appear to be an argument for power in writers.gdal. This restricts the way in which this points-to-grid function can be employed and tuned to specific applications.

_Example output raster, with four point locations shown as black dots._
![screen](https://user-images.githubusercontent.com/25197948/58557512-74ae9280-8216-11e9-89fb-6a71c03225cc.png)

_Code used:_
(tested on Windows, PDAL v1.9.0)

dtm_pipeline = {
            "pipeline": [
                {
                    "type": "readers.text",
                    "filename": input_file,
                    "skip": 1,
                    "spatialreference": EPSG
                },
                {
                    "type": "writers.gdal",
                    "dimension": "Z",
                    "resolution": 0.1, 
                    "radius": 10, 
                    "output_type": "idw",
                    "gdaldriver": "GTiff",
                    "filename": dtm_outfile
                }
            ]
        }

**Comment by abellgithub** [comment]
Can you please provide the input file?

**Comment by AndrewCunliffe** [comment]
Sorry, input file attached.

[inputfile.txt](https://github.com/PDAL/PDAL/files/3232629/inputfile.txt)

**Comment by abellgithub** [comment]
Confirmed this issue.  Item 3 (power) is unrelated.  You should open another issue for that with a detailed description of what's desired.

**Comment by abellgithub** [comment]
If you are able to build from source, you can test this: https://github.com/PDAL/PDAL/tree/issue-2545

Note that if you run a test like yours in stream mode you may get somewhat unexpected effects, so I would suggest either setting bounds or using the `--nostream` option to `pdal pipeline`.

**Comment by AndrewCunliffe** [comment]
Thanks Andrew. As suggested, I have created a [new issue #2550]((https://github.com/PDAL/PDAL/issues/2550)) regarding the power.  

Unfortunately I'm not currently able to build form source, but let me know if there is another way I can help test behaviour? Thanks for the tip about stream mode, I will try to bear that in mind.
