### ISSUE TITLE
Request for user-specified power in IDW with writers.gdal

### ISSUE THREAD

**Issue by AndrewCunliffe** [PDAL/PDAL#2550]
Spatial interpolation using inverse distance weighting (IDW) requires a power term (AKA weighting coefficient). The power term currently employed in writers.gdal is not reported in the the documentation, which limits reproducibility (_I would have expected to see it [here](https://pdal.io/stages/writers.gdal.html) under IDW, apologies if I missed it elsewhere_).

I think it would be helpful to:
 
1.  State the default power term in the documentation (_2 is a common default, e.g. [ESRI's ArcMap](https://pro.arcgis.com/en/pro-app/tool-reference/spatial-analyst/idw.htm)_)

2. Implement an optional 'power' argument to writers.gdal, to allow users to customise this parameter for different applications.

Less important, but it might also be helpful to be explicit in the documentation about how coincident (identical) points are handled, as this can differ between implementations of IDW (some will take all points, others the first/last only; for further discussion of this nuance see [here](https://pro.arcgis.com/en/pro-app/tool-reference/spatial-analyst/idw.htm)).

**Comment by AndrewCunliffe** [comment]
It would also be helpful to update description of the 'secondary algorithm' in writers.gdal, to explicitly state the power value used here.

**Comment by chambbj** [comment]
I wonder if it would be sufficient to instruct users to insert `filters.returns` prior to `writers.gdal` if they'd like to limit it to first or last returns.

See https://pdal.io/stages/filters.returns.html#filters-returns.

**Comment by abellgithub** [comment]
You're going to have to help me out and explain how `filters.returns` is related to this.

**Comment by chambbj** [comment]
Only based on the secondary objective of handling coincident points.
> some will take all points, others the first/last only
My thought was that `filters.returns` would help to segregate first/last returns, but I'm now remembering that they would actually be two separate views, so that doesn't actually help.

**Comment by AndrewCunliffe** [comment]
Thanks for the suggestion Chambbj. I think the `filters.returns` the approach might only work for datasets containing return numbers, so one downside is that it might not accommodate coincident points in clouds originating from combined terrestrial point clouds or photogrammetrically-derived clouds?
