### ISSUE TITLE
PDAL JSON output is not valid

### ISSUE THREAD

**Issue by connormanning** [PDAL/PDAL#2558]
JSON output from PDAL info can be invalid.  Specifically I've noticed they can't be consumed by either [jq](https://stedolan.github.io/jq/) through the CLI or PDAL's own [JSON library](https://github.com/nlohmann/json) through the C++ API.  To reproduce, assuming `jq` is installed:

```
$ pdal info --metadata https://entwine.io/data/red-rocks.laz | jq
parse error: Invalid string: control characters from U+0000 through U+001F must be escaped at line 62, column 35
```

At a glance I think it's from `SpatialReference::getWKT()` ending with control characters.  This is the case on both `master` and `1.9-maintenance` branches.  I think there was some sanitization code that was removed recently because no one (including me) could remember why it was there - maybe this was it.

**Comment by msmitherdc** [comment]
I ran into this consuming some usgs ept just today. It was in the wkt data that there was some non utf-8 data

**Comment by abellgithub** [comment]
Our old approach was to simply remove control characters.  Ummm....
