### ISSUE TITLE
[pcl::PCDReader::readHeader] Invalid COUNT value specified.

### ISSUE THREAD

**Issue by Dinatorehanova** [PDAL/PDAL#2572]
When I am trying to convert my pcd file into las file I am getting this error ([pcl::PCDReader::readHeader] Invalid COUNT value specified.) 

Can anyone please tell me how I can resolve this issue? Also, is there any tool available that can merge multiple pcd files into a single one ?

Herewith I have attached the PCD file for your kind review and consideration.

https://drive.google.com/file/d/1HEXfvimqXowpthvIUiH0t7C0oW1a7BJ_/view?usp=sharing

Thanks

**Comment by abellgithub** [comment]
The PCD code depends on the file matching what's expected exactly.  In this case, it means that you must have the fields X, Y, Z, Intensity, Red, Green, Blue and Alpha.  This isn't well-documented.

We have done some work to read PCD files without PCL, making any files readable, but it is incomplete at this moment.

**Comment by Dinatorehanova** [comment]
Hi, abellgithub,

Thank you very much for your kind reply. I believe my pcd file has all the fields except RGB since it’s from my LiDAR unit. I assume, it’s the file format for what the pdal can’t translate it. Can you please spare some of your time to look int the file that I shared ? And can you tell me any tool that may merge multiple pcd files into a single one ?

Thank you for your time

**Comment by abellgithub** [comment]
I've looked at the file.  Here's the header:

```
# .PCD v0.7 - Point Cloud Data file format
VERSION 0.7
FIELDS x y z _ intensity t reflectivity ring _ noise _ range _
SIZE 4 4 4 1 4 4 2 1 1 2 1 4 1
TYPE F F F U F U U U U U U U U
COUNT 1 1 1 4 1 1 1 1 0 1 0 1 15
WIDTH 512
HEIGHT 64
VIEWPOINT 0 0 0 1 0 0 0
POINTS 32768
DATA binary
```

Sorry, I don't know what other tools might exist to solve your problem.
