### ISSUE TITLE
Converting PCD into LAS file error

### ISSUE THREAD

**Issue by Ewaolx** [PDAL/PDAL#2575]
While running

`PDAL translate input.pcd output.las `

getting following error

`Failed to load "/home/user_name/anaconda3/envs/myenv/lib/libpdal_plugin_reader_pcd.so": libpcl_segmentation.so.1.9: cannot open shared object file: No such file or directoryPDAL: Couldn't create reader stage of type 'readers.pcd'.
`

I have installed PDAL through conda in Ubuntu 16.04.

I already have` libpcl_segmentation.so.1.9` and `libpdal_plugin_reader_pcd.so` in `/home/user_name/anaconda3/envs/myenv/lib/` folder.

And my `$PDAL_DRIVER_PATH` is `/home/user_name/anaconda3/envs/myenv/lib`

Any insights on this issue would be helpful.

Thanks.

**Comment by abellgithub** [comment]
You can certainly set LD_LIBRARY_PATH to `/home/user_name/anaconda3/envs/myenv/lib` and things should work.  Conda builds should have an internal rpath set, but you'd have to search through the binaries/.so with readelf to trace the issue.

**Comment by Ewaolx** [comment]
Thanks for the quick reply.

I just did that. But still ended up getting the same error.

I also noticed that my `/lib` folder also contains `libpcl_segmentation.so.1.8` and `libpcl_segmentation.so.1.8.1`

So, could it be concerning the version numbers?

**Comment by abellgithub** [comment]
This is a conda error, though your case seems different from mine.  PDAL for conda is configured for PCL version 1.9, but the conda install process only seems to provide 1.8.  I'm not sure what needs to be done to fix this.  @hobu?

**Comment by abellgithub** [comment]
Things should be fixed now.  You can try `conda update pcl`, or you can create a new environment and re-install from conda-forge.

**Comment by barnjamin** [comment]
I'm getting this error on a fresh install of pdal using miniconda.  All the libpcl_* shared libraries are 1.8.1 and I'm on Ubuntu 18.04.

**Comment by barnjamin** [comment]
running `conda install -c conda-forge pcl` seems to have worked

**Comment by hobu** [comment]
PCL and PDAL was rerendered, so things should work if you update your environment or create a new one. Closing for now.

**Comment by rob137** [comment]
> running `conda install -c conda-forge pcl` seems to have worked

I had the same issue as @Ewaolx and this worked for me too.

**Comment by Ewaolx** [comment]
@abellgithub thanks for the fix!
