### ISSUE TITLE
PDAL, entry point not found

### ISSUE THREAD

**Issue by Yukon-climate** [PDAL/PDAL#2578]
Hello, 
Any idea why this is happening?
![2019-06-20 20_36_00-Proc4 - TeamViewer](https://user-images.githubusercontent.com/12923598/59889806-1e0f2100-939c-11e9-905d-033357b44eec.png)
It uses to work fine and now every time i tried to use PDAL I get this error.
I tried changing my environments variable for GDAL etc... but without success.
It appears while trying to do this : 

set pdal_pipeline={"pipeline":["%source_path%",^
{"type":"filters.range","limits":"Classification[4:5]"},^
{"type":"writers.gdal","resolution": 0.01,"filename":"%destination_path%",^
"data_type":"uint8","gdalopts":"NBITS=1, TFW=YES","nodata":0,"output_type":"max"}]}

**Comment by chambbj** [comment]
If you could let us know the outputs of `conda info` and `conda list` it would be helpful.

**Comment by abellgithub** [comment]
It's not clear what your configuration is.  Are you using conda?  If so, why are you setting environment variables?

**Comment by abellgithub** [comment]
Closing due to lack of follow-up.  Reopen if you can provide more information.
