### ISSUE TITLE
PCD merge command for large number of pcd files

### ISSUE THREAD

**Issue by Dinatorehanova** [PDAL/PDAL#2584]
Hi,

Can anyone please tell me how I can combine a lot of pcd files with the pcd merge command.It seems like I need to put individual file name in the terminal in order to work with it which is very time consuming.
pdal merge 1.pcd 2.pcd 3.pcd - - - - - and so on

Is there anyway that it can simply merge all the pcd files in a folder.

Thanks

**Comment by abellgithub** [comment]
The Shell should do this for you:

pdal merge *.pcd out.las

**Comment by Dinatorehanova** [comment]
@abellgithub , thank you very much for your kind reply. It works.
