### ISSUE TITLE
Compile Greyhound

### ISSUE THREAD

**Issue by pewixg3** [PDAL/PDAL#2593]
Hi 

I have a probleme to compile greyhound with Cmake

![image](https://user-images.githubusercontent.com/45328945/60252949-7af26600-98cb-11e9-8cc5-057e8e02a8ca.png)

I have no idea how can I do this ...

**Comment by abellgithub** [comment]
We're not doing development on greyhound anymore.  You should look at EPT as a replacement.  You're on your own if you want to use greyhound at this point.  Good luck.

**Comment by hobu** [comment]
https://github.com/hobu/greyhound/issues/73#issuecomment-506325676
