### ISSUE TITLE
pgpointcloud writer causing (non breaking) 'unsupported frontend protocol' message in postgres

### ISSUE THREAD

**Issue by tomvantilburg** [PDAL/PDAL#2597]
I noticed the following error message in the postgres(10) log when starting the pipeline.
`FATAL:  unsupported frontend protocol 1234.5680: server supports 2.0 to 3.0`

This happens right away when opening the pipeline while the actual data insertion only starts minutes later after processing all the filters.

Likely nothing important, despite the FATAL notice, according to: https://pganalyze.com/docs/log-insights/connections/C31 so feel free to ignore if this is not an easy fix.

**Comment by abellgithub** [comment]
Should this be a ticket for postgres?

**Comment by tomvantilburg** [comment]
From what I understood from the post in the link above, it is caused by the program that is connecting with postgres. I assume this is PDAL in this case.

**Comment by abellgithub** [comment]
I've looked at the linked page.  It's not specific as to what may be incorrect.  We don't pass anything other than a simple connection string when calling PQconnectdb(), so I really have no idea what the issue might be.  If you want to follow-up with those in the know on Postgres, perhaps they can provide better information as to the call that might be wrong.

I'm seeing no such errors on my postgres server log.

**Comment by tomvantilburg** [comment]
Considering the low amount of online information on this topic and the advice from aforementioned website (_Recommended Action: No action necessary_) it may be better left untouched. I'll be reopening when I feel this is causing trouble but apart from some pollution in my logs I can't be bothered with it.
