### ISSUE TITLE
Merging IMU,GPS, and Point Cloud with PDAL for georeferencing

### ISSUE THREAD

**Issue by Ashik19** [PDAL/PDAL#2600]
Hi,

Is it possible to apply PDAL to merge the IMU data with the point cloud coordinate, and the GPS in order to geo-reference the clouds into real world coordinate system ?

Can anyone please guide me in this aspect?

Thanks

**Comment by hobu** [comment]
A github ticket is not an appropriate venue for this question. You might try asking this question on [GIS Stack Exchange](http://gis.stackexchange.com/).
