### ISSUE TITLE
Poisson filter, location, scale and density

### ISSUE THREAD

**Issue by RiskyRob** [PDAL/PDAL#2606]
Hi Guys,

I realise this question is similar to this issue https://github.com/PDAL/PDAL/issues/1840

I have come across two issues:

**Issue 1**
I am getting the same problem, the poisson filter normalises the point cloud to be 0 - 1 in the x, y and z coordinates (however it does fill in the holes in my dataset)

I could work out what the transformation is going to be before I run the pipeline and add a transformation stage object after the poisson filter to correct this but it is massively inconvenient and I would have expected the output from poisson filter to be in the same scale and location as the input.

**Issue 2**
My original point cloud is 4.7 million+ points, the output from the poisson filters is 800k points. This is a huge loss in data which will mean the point cloud won't scale well if I transform back to it's original size, I expected the filter to return a point cloud with more points as missing data is filled in.

......

My overall aim is to create a raster without holes and the less dense the data I have is, the lower the resolution has to be which means reduced accuracy.

Am I doing something incorrectly, are these issues bug or is this expected behaviour? I have pasted my pipeline below.

{
  "pipeline": [
    {
      "filename": "C:/InputDataset.las",
      "compression": "none",
      "type": "readers.las"
    },
    {
      "type": "filters.normal",
      "knn": 8
    },
    {
      "depth": 10,
      "type": "filters.poisson"
    },
    {
      "compression": "none",
      "type": "writers.las",
      "filename": "C:\\OutputDataset.las"
    }
  ]
}

**Comment by abellgithub** [comment]
This has been fixed with https://github.com/PDAL/PDAL/pull/2579 .  It will be in the next release or you can build the master branch.  As far as point density goes, you need to increase the `depth` to get higher density.  See https://pdal.io/stages/filters.poisson.html

**Comment by RiskyRob** [comment]
Thank you very much for the fast response, it has been extremely informative. I will try building the master branch and keep a look out for the the next release in the future.

I am using writers.gdal but found that it does not seem to fill in the holes, I thought poisson filter would help.

**Comment by abellgithub** [comment]
You can increase the `window_size` in https://pdal.io/stages/writers.gdal.html to fill holes in the data.

**Comment by RiskyRob** [comment]
I will try it, thank you
