### ISSUE TITLE
No error when trying to overwrite a file being used by another program

### ISSUE THREAD

**Issue by CUBICinfinity** [PDAL/PDAL#2609]
I can run `pdal pipeline class_color_to_ply.json` while the file I'm writing to is open in a text editor. PDAL won't complain but secretly it won't update the ply file. This is my json file:
```
{
  "pipeline":[
    {
      "type":"readers.las",
      "extra_dims":"red=uint16,green=uint16,blue=uint16",
      "filename":"wall_color.las"
    },
    {
      "type":"writers.ply",
      "filename":"wall_color.ply"
    }
  ]
}
```

**Comment by abellgithub** [comment]
I can't recreate this on OSX.  What is your OS/PDAL version?

**Comment by CUBICinfinity** [comment]
I'm using Windows 10. I'm running the command in Anaconda Prompt and I have PDAL 1.9.1. I had the ply file open in EmEditor. Running the script like this without the ply file being rewritten took a moment, but much less time than it takes to overwrite.

**Comment by CUBICinfinity** [comment]
Ok, I reproduced the problem using smaller files. As soon as I close EmEditor and try to run the pipeline again it correctly overwrites the ply file.

**Comment by abellgithub** [comment]
PDAL wasn't checking a file creation failure in the PLY writer, but I'm not sure this explains the behavior.  I'll test when I have a chance with Windows.
