### ISSUE TITLE
Solving environment: failed

### ISSUE THREAD

**Issue by Ashik19** [PDAL/PDAL#2613]
When Installing PDAL with anaconda I am getting the following erros 

![Screenshot from 2019-07-15 13-02-29](https://user-images.githubusercontent.com/52055757/61241599-10ca2580-a701-11e9-8988-1a141a0036be.png)

Can anyone please tell me how to remove this error ?

Thanks

**Comment by abellgithub** [comment]
This seems to have nothing to do with pdal.

**Comment by Ashik19** [comment]
@abellgithub ,

Thank you for your kind reply.

I have installed the pdal in a new environment called myenv but when I am trying to use the pdal its coming up with this error.

![Screenshot from 2019-07-15 14-09-06](https://user-images.githubusercontent.com/52055757/61245738-7242c200-a70a-11e9-8f3e-c4c41ae696b8.png)

Can you please help me with this ?

Thanks

**Comment by abellgithub** [comment]
See https://github.com/PDAL/PDAL/issues/2575

**Comment by Ashik19** [comment]
Thank you very much for your kind reply @abellgithuib
I think I am missing a package like libpdal_plugin_reader_pcd but when I am trying to install it I ma getting this error 

Can you please take a look into it ?

![Screenshot from 2019-07-15 14-31-46](https://user-images.githubusercontent.com/52055757/61247081-99e75980-a70d-11e9-842f-fa74f02d7d40.png)
 
Thank you very much for being patient with me.

**Comment by Ashik19** [comment]
solved forge pcl seems to be worked.

Thanks
