### ISSUE TITLE
LAS to PCD preserving coordinate system?

### ISSUE THREAD

**Issue by shukhrat811** [PDAL/PDAL#2615]
Hi,

I would like to convert LAS file into PCD format. 
"pdal translate input.las output.pcd"
converts into PCD format, but doesn't preserve original coordinates. Output file has some local coordinate system. Can we preserve original coordinate system?
Thanks,

**Comment by chambbj** [comment]
Please check the PCD writer options at https://pdal.io/stages/writers.pcd.html#options. If you get stuck, you might try the [GIS Stack Exchange](http://gis.stackexchange.com/) or post a question to the [mailing list](http://lists.osgeo.org/mailman/listinfo/pdal).
