### ISSUE TITLE
Trouble loading writers.pcd

### ISSUE THREAD

**Issue by apurl1** [PDAL/PDAL#2621]
I am having issues with translating from las to pcd. I am using pdal 1.9.1 and pcl 1.8.1 on Ubuntu 18.04. I installed pdal by following the instructions [here](https://pdal.io/quickstart.html). My conda version is 4.7.5.

Attempting to translate yields the following error:
`(pdal translate Error) Can't load library /home/apurl1/anaconda3/envs/myenv/lib/libpdal_plugin_writer_pcd.so: Failed to load "/home/apurl1/anaconda3/envs/myenv/lib/libpdal_plugin_writer_pcd.so": libpcl_segmentation.so.1.9: cannot open shared object file: No such file or directoryPDAL: Couldn't create writer stage of type 'writers.pcd'.
You probably have a version of PDAL that didn't come with a plugin
you're trying to load.  Please see the FAQ at https://pdal.io/faq
`

`pdal --drivers` does not have `writers.pcd`. However, under by `PDAL_DRIVER_PATH`, I can find `libpcl_<name>.so` and `libpdal_plugin_writer_pcd.so`.

The second Q&A [here](https://pdal.io/faq.html) is not applicable because I used conda install. Is the only way for pdal to recognize the pcl plugins to build it myself? If so, where can I find instructions on how to do this on Ubuntu. I found some direction for Windows platforms but not Linux.

Thanks!

**Comment by hobu** [comment]
I think there is an issue where the PCL conda package needs to be regenerated.

**Comment by abellgithub** [comment]
Please see this issue: https://github.com/PDAL/PDAL/issues/2575

**Comment by apurl1** [comment]
Wow, thanks for the quick responses!

I ran `conda install -c conda-forge pcl` and got the same error. I also created a new environment by running
`conda create  --name myenv --channel conda-forge pdal`
and
`conda install -c conda-forge pcl`

Am I missing something?

**Comment by hobu** [comment]
Using the `continuumio/miniconda` docker container, I get the following after installing pdal like you did:

```
conda install -c conda-forge pdal -y
```

```
(pdal) root@38bc5ae952d0:/# cat /etc/os-release|grep NAME
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
(pdal) root@38bc5ae952d0:/# conda --version
conda 4.7.5
(pdal) root@38bc5ae952d0:/# pdal --drivers|grep pcd
readers.pcd                  Read data in the Point Cloud Library (PCL) format.
writers.pcd                  Write data in the Point Cloud Library (PCL) format.
```

**Comment by apurl1** [comment]
I'm at a loss as to what could be wrong with my setup then.

I attempted all of this on my conda prompt in Windows 10 and successfully translated from las to pcd. Not sure why it won't work on Ubuntu, but I can work with what I have now.

Thanks for the help!

**Comment by hobu** [comment]
We have had a lot of trouble with the Linux PCL builds on Conda. I don't really understand the issue. PDAL 2.0 is working to remove most of the PCL dependency and PCD support is likely to be embedded and not need PCL linkage at all going forward.
