### ISSUE TITLE
writers.las.minor_version='0' gives error

### ISSUE THREAD

**Issue by mantbe** [PDAL/PDAL#2622]
I have a las 1.0 file that I am trying to add coordinate system info to the header.  Initially, I wanted to preserve the header info, so I tried:

pdal translate --writers.las.a_srs="EPSG:4326" --writers.las.forward="all" input.laz output.laz

But this will set the minor_version field to 2, when it should be 0.

As a test, I tried this:

pdal translate --writers.las.a_srs="EPSG:4326" --writers.las.minor_version=0 input.laz output.laz

Outputs the following error:
PDAL: writers.las: Invalid value '0' for argument 'minor_version'.

However, I was able to run the same commands with minor_version set to 1,2,3, or 4.

**Comment by hobu** [comment]
We had a discussion a long time ago and explicitly prevented writing 1.0 files. The rationale was:

* "why would anyone want this?" 😄 
* The 1.0 specification was ambiguous in many places
* The weird pad-bytes things in front of the data

lastools of course has support, and so does libLAS.
