### ISSUE TITLE
signature mismatch for OGRCreateCoordinateTransformation

### ISSUE THREAD

**Issue by WatXtract-Luca** [PDAL/PDAL#2631]
https://github.com/PDAL/PDAL/blob/28541f67430e5f3e4e96f7000b9cc9f6dd70e5b4/pdal/private/SrsTransform.cpp#L57

    m_transform.reset(OGRCreateCoordinateTransformation(
        static_cast<const OGRSpatialReference*>(&srcRef),
        static_cast<const OGRSpatialReference*>(&dstRef)));

**Comment by abellgithub** [comment]
If you're getting a compiler error, please provide the error / system / compiler version.

Thanks,

**Comment by WatXtract-Luca** [comment]
oops! cannot reproduce the link error.

It was reporting "unresolved external symbol "class OGRCoordinateTransformation * __cdecl OGRCreateCoordinateTransformation(OGRSpatialReference *, OGRSpatialReference *)" referenced in SrsTransform ...

My development Environment: Windows 10 Pro; Visual C++ 2017; GDAL 3.1.0

But I could not re-produce the error by trying to re-build several times.

Thx!
