### ISSUE TITLE
Add 'ignore' support for filters

### ISSUE THREAD

**Issue by abellgithub** [PDAL/PDAL#2633]
Many filters only have an interest in a subset of points.  These points can be filtered by each individual stage, but that is tedious.  It would be nice to make this functionality part of the stage with little trouble.  When a stage uses this "ignore" functionality, its output should be all ignored points plus those points returned by the stage's run() function.

One way this might be achieved is to make filters that support this derive from a special subclass of Filter.

**Comment by hobu** [comment]
I'd rather follow RDMS-style WHERE semantics #2638
