### ISSUE TITLE
python-pdal filters PMF and SMRF 'No returns to process.'

### ISSUE THREAD

**Issue by ignacioi96** [PDAL/PDAL#2634]
When the following Pipeline is executed, with either filters.pmf or filters.smrf

pdal.Pipeline(
    json.dumps(
        {'pipeline': ['input.las',
                             {'type':'filters.smrf'},
                         'output.laz']}))
or
pdal.Pipeline(
    json.dumps(
        ['input.las',
        {'type':'filters.smrf'},
        'output.laz']))

the output is:

RuntimeError: filters.smrf: No returns to process.
or
RuntimeError: filters.pmf: No returns to process.
...
Fullstacktrace:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/usr/anaconda3/envs/harv/lib/python3.7/site-packages/pdal/pipeline.py", line 40, in execute
    return self.p.execute()
  File "pdal/libpdalpython.pyx", line 177, in pdal.libpdalpython.PyPipeline.execute
RuntimeError: filters.smrf: No returns to process.

...
I have tried changing the input variables to both filters, but the output is the same. I have tried different input LAS files without avail. e.g. 'returns':'last', 'returns':'first', 'threshold':20, 'threshold':1, etc.

I am using a conda environment with Python 3.7 with everything up to date except for cfitsio which is not the latest version, but version 3.430 following https://github.com/conda-forge/gdal-feedstock/issues/303

Any help is welcome and gratefully accepted. Thank you in advance!

**Comment by abellgithub** [comment]
You don't say what version of PDAL you're using.  Perhaps you're hitting this issue: https://github.com/PDAL/PDAL/issues/2275

**Comment by ignacioi96** [comment]
Apologies for not making it explicit.

pdal version is 1.9.1
python-pdal version is 2.1.8

**Comment by luipir** [comment]
No numberOfReturns o returnNumber dimension bug? I supposed was fixed! Can you list dimensions of the input las? Or trying a workaround adiing these fake dimensions using filters.ferry.

**Comment by luipir** [comment]
@ignacioi96 please give a try to this warkaround to check if the problem is still the same e.g. https://github.com/PDAL/PDAL/issues/2275

I face it processing photogrammetric point clouds

'''
    {
        "type": "filters.ferry",
        "dimensions": "=>ReturnNumber, =>NumberOfReturns" 
    },
    {
        "type": "filters.assign",
        "assignment": "NumberOfReturns[:]=1"
    },
    {
        "type": "filters.assign",
        "assignment": "ReturnNumber[:]=1"
    },
'''

**Comment by chambbj** [comment]
Allowing processing to continue with missing ReturnNumber or NumberOfReturns was fixed in https://github.com/PDAL/PDAL/pull/2276, which is part of v1.9.1.

Handling invalid ReturnNumber/NumberOfReturns (e.g., zeros) was added in https://github.com/PDAL/PDAL/pull/2417, which is yet to be released. I'm guessing you are running into an issue here. I suggest you look at your ReturnNumber/NumberOfReturns values to make sure they make sense. Alternately, you could post some data to have someone here confirm.

**Comment by ignacioi96** [comment]
> @ignacioi96 please give a try to this warkaround to check if the problem is still the same e.g. #2275
> 
> I face it processing photogrammetric point clouds
> 
> ```
>    {
>         "type": "filters.ferry",
>         "dimensions": "=>ReturnNumber, =>NumberOfReturns" 
>     },
>     {
>         "type": "filters.assign",
>         "assignment": "NumberOfReturns[:]=1"
>     },
>     {
>         "type": "filters.assign",
>         "assignment": "ReturnNumber[:]=1"
>     },
> ```

This solved it for me!
Thank you very much for your time.

**Comment by abellgithub** [comment]
Are you both having this problem with version 1.9?  We have a test for this case, so I'm confused and will look into again if so.

**Comment by luipir** [comment]
> Are you both having this problem with version 1.9? We have a test for this case, so I'm confused and will look into again if so.

@abellgithub not tested sorry... btw @ignacioi96 can you share a subset that replicate the issue. Seems all should already work using 1.9.1

**Comment by chambbj** [comment]
I'd be curious to know if it still works removing the ferry filter and simply assigning.

**Comment by ignacioi96** [comment]
using only these filters (without ferry) works fine as well:

{'type':'filters.assign','assignment':'NumberOfReturns[:]=1'},{'type':'filters.assign','assignment':'ReturnNumber[:]=1'},
{'type':'filters.smrf'}

What would be the best method to send you a 21.6 MB LAS file that reproduces this issue using python-pdal 2.1.8 and pdal 1.9.1?

**Comment by chambbj** [comment]
That's good to hear.

Short of publishing the data, you could run the following command and share the results.

```
pdal info /path/to/file --stats --dimensions="NumberOfReturns,ReturnNumber"
```

I suspect you may have zeros in one or both dimensions.

**Comment by ignacioi96** [comment]
The output of such command is:

{
  "filename": "output.las",
  "pdal_version": "1.9.1 (git-version: 06c6f0)",
  "stats":
  {
    "statistic":
    [
      {
        "average": 0,
        "count": 636139,
        "maximum": 0,
        "minimum": 0,
        "name": "ReturnNumber",
        "position": 0,
        "stddev": 0,
        "variance": 0
      },
      {
        "average": 0,
        "count": 636139,
        "maximum": 0,
        "minimum": 0,
        "name": "NumberOfReturns",
        "position": 1,
        "stddev": 0,
        "variance": 0
      }
    ]
  }
}

I could publish the file if it would be necessary after looking at this results. I am unsure of where it would be best to upload it. Suggestions?

**Comment by chambbj** [comment]
No need to share the file as far as I'm concerned. This shows that you have all zeros in both dimensions, which explains perfectly the behavior you were seeing. The next release of PDAL will display a warning in this scenario, but proceed with filtering using ALL points.

**Comment by ignacioi96** [comment]
Thank you for your help!
