### ISSUE TITLE
(pdal translate readers.text Error) Line 2 in 'points.csv' contains 1 fields when 2 were expected.  Ignoring.

### ISSUE THREAD

**Issue by Ashik19** [PDAL/PDAL#2635]
Hi,

When I am trying to convert the folowing csv file into pcd file using the pdal translate command I am getting the following error

"(pdal translate readers.text Error) Line 2 in 'points.csv' contains 1 fields when 2 were expected.  Ignoring."

Herewith attached link is for the csv file

https://drive.google.com/file/d/1K6AuJSzY3hAbc3xQ0vwlV1RU3CLrg1Sh/view?fbclid=IwAR0W1xGbg7lqxDr-45q4P6cLGyFm2-bzhpJCQw0quPG9D70FwWJh7AyoL3Y

Thanks

**Comment by abellgithub** [comment]
Please just provide the first two lines and the exact command you're using.

**Comment by Ashik19** [comment]
Hi @abellgithub ,

Thank you for your reply. I am using the command "pdal translate points.csv out.pcd" but getting the above error.

**Comment by abellgithub** [comment]
If you want help with this, you should just post the first two lines of the file as I suggested.  But you may be able to solve this yourself by carefully reading [the documentation.](https://pdal.io/stages/readers.text.html)

**Comment by Ashik19** [comment]
Hi @abellgithub ,

Thank you very much for your kind reply.

Can you please take a look at the herewith attached picture regarding the file that I am trying to use in the PDAL

![Screenshot from 2019-07-29 20-12-12](https://user-images.githubusercontent.com/52055757/62095415-9d1a3380-b23d-11e9-99e5-3ccf5ce9e1a1.png)


Thank you very much for your valuable time.

Thanks 
Ashik

**Comment by abellgithub** [comment]
This file doesn't appear to meet the requirements that PDAL has for text files.  You should read the documentation carefully.
