### ISSUE TITLE
Comments are not supported in JSON pipelines

### ISSUE THREAD

**Issue by ahuarte47** [PDAL/PDAL#2669]
From https://github.com/PDAL/PDAL/pull/2470 the comments are not supported in JSON pipelines.

The [nlohmann json library](https://github.com/nlohmann/json#comments-in-json) does not support comments, and it will not support comments in the future.

Standards are standards as it was said in this closed [issue](https://github.com/nlohmann/json/issues/1513), but what about adding it with a similar work arround as [here](https://github.com/nlohmann/json/issues/1513#issuecomment-473564115) at least when parsing the `--json` pipeline parameter?

**Comment by luipir** [comment]
yes please!

**Comment by connormanning** [comment]
Can this not be better handled externally, so PDAL itself can concern itself only with conforming JSON?  `cat pipeline.json | jsmin | pdal pipeline --stdin`, for example.

**Comment by ahuarte47** [comment]
> Can this not be better handled externally, so PDAL itself can concern itself only with conforming JSON? `cat pipeline.json | jsmin | pdal pipeline --stdin`, for example.

Great tip thanks! But I suppose it is not available in Microsoft Windows systems. 

When the pipeline files get bigger and bigger with many filters and settings, it is very useful to write comments in order to explain the operations that you define. It is a shame to lose this feature, that is why I would know any opinions, the implementation looks easy.

**Comment by hobu** [comment]
Comments in JSON are not valid RFC JSON, and if PDAL is producing JSON with them, we are not producing valid JSON. That they worked in the past was an implementation detail of the JSON library we were using, and not a specifically intended feature. We do not want to be producing invalid JSON output.

**Comment by hobu** [comment]
I would add you can use the `user_data` member of every stage object to place a JavaScript object of your liking. That's not docs, of course, but you could cook something up.

**Comment by ahuarte47** [comment]
Ok, thanks to every one. I see your reasons, so I think it is better to close this issue.

**Comment by luipir** [comment]
> I would add you can use the `user_data` member of every stage object to place a JavaScript object of your liking. That's not docs, of course, but you could cook something up.

good idea... tnx
