### ISSUE TITLE
writers.gdal missing resolution parameter in pipeline

### ISSUE THREAD

**Issue by glw** [PDAL/PDAL#2673]
Hi Im getting confusing output for PDAL 1.9. I assuming its telling me that Im missing the resolution parameter in my json file, thought it is included in the file. Previously this workflow was working for version 1.8.

input:
```bash
docker run -it --rm -v $(pwd):/data pdal/pdal pdal pipeline --readers.las.filename=/data/in.laz --writers.gdal.filename=/data/out.tif /data/pipeline.json
```

output:
```bash
PDAL: writers.gdal: Missing value for positional argument 'resolution'.
```

json pipeline:
```json
{
  "pipeline":[
    "input.laz",
    {
        "gdaldriver":"GTiff",
        "output_type":"all",
        "resolution":"1.0",
        "type": "writers.gdal"
    },
    "output.tif"
  ]
}
```

**Comment by connormanning** [comment]
Do you get a different outcome if you specify `resolution` as a number instead of a string?

```
    "resolution": 1.0,
```

**Comment by abellgithub** [comment]
I think you want:

```
{
  "pipeline":[
    "input.laz",
    {
        "gdaldriver":"GTiff",
        "output_type":"all",
        "resolution":"1.0",
        "type": "writers.gdal",
        "output.tif"
    }
  ]
}
```

**Comment by glw** [comment]
@connormanning  - I tried it as a number and its still producing the same error
@abellgithub  - I also tried your json version and it appears as thought it insists on have a key-value pair within the braces where we specify the parameters. Here's the error:
```bash
PDAL: Pipeline: parse error at line 10, column 5: syntax error while parsing object separator - unexpected '}'; expected ':'
```

**Comment by connormanning** [comment]
Please try:
```
{
  "pipeline":[
    "input.laz",
    {
        "gdaldriver":"GTiff",
        "output_type":"all",
        "resolution":"1.0",
        "type": "writers.gdal",
        "filename": "output.tif"
    }
  ]
}
```

**Comment by abellgithub** [comment]
Well, that was my intended response ;)

**Comment by glw** [comment]
Thanks @connormanning and @abellgithub , updating the file to include "filename": "output.tif" worked!
