### ISSUE TITLE
writers.pgpointcloud selects wrong pcid

### ISSUE THREAD

**Issue by sensor-freak** [PDAL/PDAL#2692]
I believe that the pgpointcloud plugin contains an anomaly when creating a new table in the target database.

Steps to reproduce the issue:
- (create new database and enable reqquired extensions postgis, pointcloud and pointcloud_postgis)
- create a pipeline using a writer for `writers.pgpointcloud` (and arbitrary input data with no assigned SRS)
- define a valid SRS in the writer stage (e.g. `"srsid":"25832"`)
- execute the pipeline
- the database should now contain a new table with a column of type `PcPatch`
- create a seconds pipeline using a different table name and different valid SRS (e.g. `"srsid":"31467"`)
- execute the pipeline
- check the SRS assigned to the geometries in the two tables (e.g. `select st_srid(geometry(pa)) from <tablename>`). The results should have (IMHO) the respective srsid values as specified in the pipeline. Actually (as of version 1.9.1) both tables indicate the same srsid, specifically the one from the first table created.

The fix for this seems to be somewhat trivial: just add the srid argument when searching for a matching entry in the pointcloud_formats table. This might be done by adding a WHERE clause in line PgWriter.cpp:234 `WHERE srid = ?`, or by extending the SELECT statement to return column `srid` and compare the value against the variable `srid` in PgWriter.cpp:240.

(Currently i have no setup for building PDAL myself, therefore I cannot validate my suggestion.)

Any comments are welcome!

**Comment by hobu** [comment]
If you can turn these steps into SQL and provide some data that demonstrates the issue, we can make a test case and a bug fix that attacks it.

**Comment by sensor-freak** [comment]
I have not checked if the fix is compatible with master, since I currently have to stay with 1.9.1. But please feel free to pick the change also for the master branch.

**Comment by hobu** [comment]
Closing as this appears merged.
