### ISSUE TITLE
Reading Attributes of PCD File

### ISSUE THREAD

**Issue by ethan20120** [PDAL/PDAL#2697]
Hi !

Can anyone please tell me how I can read the attribute of the pcd file using the pdal?

This is a sample of my pcd file.

https://drive.google.com/file/d/1iCSzT7QYbBBod7YcuDmt5hPhP45EY09e/view?usp=sharing

Thanks 

Ethan

**Comment by chambbj** [comment]
PDAL does not have a rosbag reader. Contributions welcome.

PCD can hold additional attributes and PDAL should have no problem
reading/writing them in the latest release. What version are you using?

Brad

**Comment by chambbj** [comment]
Reported as fixed in #2700. If upgrading to PDAL 2.0.1 does not fix the issue, please reopen.
