### ISSUE TITLE
Field Attributes Transformation Issue

### ISSUE THREAD

**Issue by Dinatorehanova** [PDAL/PDAL#2700]
Hi,

Can anyone please help me with the following queries

Does changing the file format from pcd to las or csv also affects the x,y,z value?

And when I am converting my pcd file into other format (e.g. csv or las) it just giving  me the value for the x,y,z,intensity, and the rgb while my original pcd file generated from the rosbag contains more fields and values (timestamp,ring,noise, range, reflectivity).

Any help will be greatly appreciated.

Thanks

**Comment by chambbj** [comment]
I'd say best practice is to create a new, clean environment. Read the conda
docs for that (although we cover it some in ours as well, you'll just have
to look).

**Comment by Deer-1170** [comment]
ver2.0.1 has the same problem.

Any help will be greatly appreciated.
