### ISSUE TITLE
Converting all pcd file in a folder into csv

### ISSUE THREAD

**Issue by ethan20120** [PDAL/PDAL#2708]
Hi @chambbj ,

Is there any single command line available which converts all the pcd file in a folder into csv and create individual csv file for individual pcd file ?

Thanks

**Comment by hobu** [comment]
This is not the proper channel for user support. Please use [GIS StackExchange](https://gis.stackexchange.com/questions/tagged/pdal) or the [PDAL mailing list](https://pdal.io/community.html#mailing-list) venues to work this issue.
