### ISSUE TITLE
Data Filtering with PDAL

### ISSUE THREAD

**Issue by Ashik19** [PDAL/PDAL#2713]
Is it possible to  automatically filter points with x,y,z=0 from a pcd file using PDAL ?Can anyone please guide me on this ?

Any help will be very appreciated.

Thanks

**Comment by chambbj** [comment]
It is possible. I suggest you use [GIS StackExchange](https://gis.stackexchange.com/questions/tagged/pdal) or the [PDAL mailing list](https://pdal.io/community.html#mailing-list) to seek support from the community.
