### ISSUE TITLE
Calling `Stage::log()` from child class constructor is an access violation

### ISSUE THREAD

**Issue by wrenoud** [PDAL/PDAL#2715]
Not sure if this is a bug exactly, I just got hung up having to debug this. But maybe worth noting in docs that the log isn't constructed until `Stage::handleOptions()`.

**Comment by abellgithub** [comment]
It's unclear what you were doing and what behavior didn't meet your expectations.

**Comment by abellgithub** [comment]
PDAL stages take no constructor arguments, so I'm not sure how it would be otherwise.  Generally, we wouldn't recommend that any code be placed in a stage constructor.  Instead, place initialization code in initialize() or ready().

**Comment by wrenoud** [comment]
Trying to log from the constructor, ie:
```cpp
class MyReader : public Reader
{
public:
    MyReader()
    {
        log()->get(LogLevel::Debug) << "Constructed" << std::endl;
    }
}
```

Again, not particularly important, just surprised me until I debugged.

**Comment by abellgithub** [comment]
If you're trying to debug during development, I'd just recommend writing to stderr.
