### ISSUE TITLE
filter.returns gives no output with pdal 2.0.1

### ISSUE THREAD

**Issue by sarraghd** [PDAL/PDAL#2734]
**Describe the bug**
A clear and concise description of what the bug is, including steps to reproduce the behavior. This typically means providing the PDAL commands you are using (e.g., `pdal translate ...`) and if applicable the contents of any PDAL pipelines you are running.

```
$ pdal translate in.las out.las
```

<details>
```
{
  "pipeline":[
    "in.las",
    "out.las"
  ]
}
```
</details>

**Expected behavior**

**System/installation information:**
Please provide information on your PDAL version (`pdal --version`) and system (e.g., `uname -a` or `ver`).

```
$ uname -a
```

```
$ pdal --version
```

If installed via Conda, you may be asked to paste the output of `conda list` and `conda info` as well.

<details>
```
$ conda list
```
</details>

<details>
```
$ conda info
```
</details>

**Comment by chambbj** [comment]
This is a template, intended to be filled out to help us understand the problem. A subject line alone will not suffice.

**Comment by sarraghd** [comment]
I  am using PDAL 2.0.1 with python 3.7
{
       "type":"filters.returns",
       "groups":"last, only",
       "inputs": "crop",
       "tag": "last"
    },

this operation does not give any output but when i run the command LAS/output2.las" --stats --dimensions="NumberOfReturns,ReturnNumber" like the other issue i got

/LAS/output2.las",
  "pdal_version": "2.0.1 (git-version: Release)",
  "stats":
  {
    "statistic":
    [
      {
        "average": 0,
        "count": 124478,
        "maximum": 0,
        "minimum": 0,
        "name": "ReturnNumber",
        "position": 0,
        "stddev": 0,
        "variance": 0
      },
      {
        "average": 0,
        "count": 124478,
        "maximum": 0,
        "minimum": 0,
        "name": "NumberOfReturns",
        "position": 1,
        "stddev": 0,
        "variance": 0
      }
    ]
  }
}
i Dont know how to fix the problem
