### ISSUE TITLE
filters.returns in PDAL 2.0.1 does not give outputs

### ISSUE THREAD

**Issue by sarraghd** [PDAL/PDAL#2735]
I am using filter to extract point cloud within a radius  with PDAL 2.0.1 with python 3.7
{
"type":"filters.returns",
"groups":"last, only",
"inputs": "crop",
"tag": "last"
},

but using filters.returns  does not give any output and  when i run the command LAS/output2.las" --stats --dimensions="NumberOfReturns,ReturnNumber" like the other issue to verify the dimension  i got

/LAS/output2.las",
"pdal_version": "2.0.1 (git-version: Release)",
"stats":
{
"statistic":
[
{
"average": 0,
"count": 124478,
"maximum": 0,
"minimum": 0,
"name": "ReturnNumber",
"position": 0,
"stddev": 0,
"variance": 0
},
{
"average": 0,
"count": 124478,
"maximum": 0,
"minimum": 0,
"name": "NumberOfReturns",
"position": 1,
"stddev": 0,
"variance": 0
}
]
}
}
I dont know how to fix the problem

**Comment by abellgithub** [comment]
It looks like your input data contains no return numbers, so 'filters.returns' can't really do anything.

**Comment by chambbj** [comment]
The logger should currently warn that a requested return group is empty. Are warnings emitted by default? Or does the user have to crank up the verbosity to get anything other than errors?

**Comment by sarraghd** [comment]
Ididn't get any warning, but how to check if my data doesn't contain return numbers?

**Comment by chambbj** [comment]
In this case, the information you already provided shows us.

```json
{
    "average": 0,
    "count": 124478,
    "maximum": 0,
    "minimum": 0,
    "name": "ReturnNumber",
    "position": 0,
    "stddev": 0,
    "variance": 0
},
{
    "average": 0,
    "count": 124478,
    "maximum": 0,
    "minimum": 0,
    "name": "NumberOfReturns",
    "position": 1,
    "stddev": 0,
    "variance": 0
}
```

It has a `ReturnNumber` dimension, but all values are 0, therefore it cannot make any determination as to the ordering of the returns.
