### ISSUE TITLE
Support building naked plugins

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#2745]
Our build system assumes you are building plugins within the context of a full PDAL build. That doesn't need to be true. With some isolation, the CMakeLists.txt file of each plugin top-level could be its own "project" and users could fetch a copy of the source tree and build and install only the plugins they care about and not require a full PDAL build.

This scenario is especially useful with Conda builds, which might not have the plugin built that you need.

**Comment by hobu** [comment]
For example, this hackery allows me to build the RXP plugin against Conda without building PDAL first:

```
diff --git a/plugins/rxp/CMakeLists.txt b/plugins/rxp/CMakeLists.txt
index 3eb806c..e9e53bc 100644
--- a/plugins/rxp/CMakeLists.txt
+++ b/plugins/rxp/CMakeLists.txt
@@ -1,6 +1,12 @@
+cmake_minimum_required(VERSION 3.1)
+set(ROOT_DIR "../../${PROJECT_SOURCE_DIR}")
+include(../../cmake/common.cmake NO_POLICY_SCOPE)
+include(FeatureSummary)
+
 set(RXP_TEST_NAME rxptest)
 
 find_package(RiVLib COMPONENTS scanlib REQUIRED)
+find_package(PDAL REQUIRED)
 set_package_properties(RiVLib PROPERTIES
     TYPE REQUIRED
     PURPOSE "Read data from RIEGL sensors"
@@ -12,25 +18,9 @@ PDAL_ADD_PLUGIN(libname reader rxp
         io/RxpReader.cpp
     LINK_WITH
         ${RiVLib_SCANLIB_LIBRARY}
+	${PDAL_LIBRARIES}
     INCLUDES
         ${RiVLib_INCLUDE_DIRS}
+	${PDAL_INCLUDE_DIRS}
 )
 
-option(BUILD_RIVLIB_TESTS "Build rivlib tests" ON)
-if (BUILD_RIVLIB_TESTS)
-    configure_file(
-        test/Config.hpp.in
-        "${CMAKE_CURRENT_BINARY_DIR}/test/Config.hpp"
-    )
-
-    PDAL_ADD_TEST(${RXP_TEST_NAME}
-        FILES
-            test/RxpReaderTest.cpp
-        LINK_WITH
-            ${libname}
-        INCLUDES
-            ${RiVLib_INCLUDE_DIRS}
-            ${PROJECT_BINARY_DIR}/plugins/rxp/test
-            ${PROJECT_SOURCE_DIR}/plugins/rxp/io
-    )
-endif()

```

**Comment by abellgithub** [comment]
I don't understand this. The only requirement for a plug-in is the naming and existence of correct entry points.

**Comment by hobu** [comment]
> I don't understand this.

This ticket is about the CMakeLists.txt for our plugins, not the plugins themselves. It's about allowing easy building of them when an existing PDAL is available to link and build the plugin against.

**Comment by abellgithub** [comment]
This assumes that you have PDAL installed, which is not the case most of
the time when you're building using the standard system. If you're
suggesting a separate build for for plugins, that's fine, but seems like
extra maintenance work.

**Comment by hobu** [comment]
> If you're suggesting a separate build for for plugins, that's fine, but seems like extra maintenance work.

I've done this manually twice now, so I think it is time to do something. It will be a little bit of extra stuff, but I was hoping to templatize our plugin CMakeLists.txt a little more to take care of most of the boilerplate.

**Comment by hobu** [comment]
Recent improvements to the CMake configuration have made this more convenient in 2.4+. Closing for now.
