### ISSUE TITLE
DBSCAN clustering would be a nice addition to the filters toolbox

### ISSUE THREAD

**Issue by chambbj** [PDAL/PDAL#2748]
Wikipedia version of the algorithm is at https://en.wikipedia.org/wiki/DBSCAN

> Ester, Martin, et al. "A density-based algorithm for discovering clusters in large spatial databases with noise." Kdd. Vol. 96. No. 34. 1996.

**Comment by tomvantilburg** [comment]
Would you consider running this only on xyz or on an arbitrary list of dimensions?
We use it a lot on the normal vector of a point in conjunction with an xyz cluster to find clusters of the same plane.

**Comment by chambbj** [comment]
Fun thought. I had only been considering XYZ initially. We could do more
dimensions, but would need to move away from the 3D kd tree to support it.
Is your distance metric still just euclidean?

**Comment by tomvantilburg** [comment]
Good point. I'm running this on groups of smaller point sets (1000's of points max), so no index is used. My python use-case in it's core looks like
* Find cluster groups in XY plane (it's always roofs from aerial data) or use polygon to crop
* For points in groups
  * Calculate normals on all resulting points
  * Discard noise
  * Run XYZ dbscan clustering to find jumps
  * Run nXnYnZ dbscan clustering to find planes
  * Create new dimension based on combined clusterids from dbscan clusters

Now I'm thinking of it, this may be actually done by using the groupby filter?

**Comment by tomvantilburg** [comment]
On a side note: 
I have been playing with Hierachical-DBSCAN clustering on pointclouds as well which gave promising results. It permits you to throw in a lot more dimensions that do not need to have a certain spacing in between.

https://hdbscan.readthedocs.io/en/latest/how_hdbscan_works.html

**Comment by chambbj** [comment]
Yes, this is on my radar as well. I happened upon the DBSCAN implementation
in Open3D which made it very easy to port to PDAL. I have yet to read up on
HDBSCAN enough for me to feel comfortable implementing, but I understand it
to be better in many cases.

**Comment by chambbj** [comment]
> Now I'm thinking of it, this may be actually done by using the groupby filter?

Which part? Running your 2nd DBSCAN on the clusters generated by the first?

**Comment by tomvantilburg** [comment]
Yes, precisely. The `For points in groups` part

**Comment by chambbj** [comment]
It looks like nanoflann does have some support for n-dimensional indexing, we just don't wrap it up in KDIndex. I'll look into what things we can do to expose that, including specifying explicitly which dimensions to use.

**Comment by chambbj** [comment]
@tomvantilburg You should take a look at #2749 sometime. I've updated the filter to take a list of dimensions to use for clustering, which defaults to X, Y, Z. You should be able to pass a comma-separated string of your choice to the `dimensions` argument for it to cluster on those dimensions instead, enabling your workflow of clustering on normals in the second pass.

**Comment by tomvantilburg** [comment]
Woot! yes, will do. Give it some days.

**Comment by tomvantilburg** [comment]
Erm... did I say _some_ days? 
Finally got some time to look at this and the result looks very nice indeed!
![image](https://user-images.githubusercontent.com/1998463/71562675-1683af80-2a84-11ea-96e5-b49614e533f0.png)
The colors are based on the Normal ClusterIDs per building. 

Got this working with:
``` 
{
        "type":"filters.dbscan",
        "min_points":10,
        "eps":1.2,
        "dimensions":"X,Y,Z"
    },{
        "type":"filters.range",
        "limits":"ClusterID[0:]"
    },{
        "type":"filters.ferry",
        "dimensions":"ClusterID => XYZID"
    },{
        "type":"filters.groupby",
        "dimension":"XYZID"
    },{
        "type":"filters.dbscan",
        "min_points":10,
        "eps":0.02,
        "dimensions":"NormalX,NormalY,NormalZ"
    },{
        "type":"filters.merge"
    },{
        "type":"filters.range",
        "limits":"ClusterID[0:]"
    }
```

And since I now have 2 clusterID's (one for X,Y,Z and one for Normals) we would be only one step away of assigning a new ClusterID based on the two so we have truely unique roofsegments. As far as I can see there's just no simple way to do that with the current functionality.

**Comment by chambbj** [comment]
Very nice! I'll work to get the PR finalized and committed to master soon.
