### ISSUE TITLE
ZStandard not included in ept.reader

### ISSUE THREAD

**Issue by tomvantilburg** [PDAL/PDAL#2750]
The zstandandard compression format seems not to be included in ept.reader

Repeat:

- Configure and build PDAL with
```
$ cmake .. -DWITH_ZSTD=YES
```
- Build some ept with entwine, zstandard will be the default
- Try to read the ept repository with:
```
$ pdal info --driver readers.ept /my/path/to/ept.json
PDAL: readers.ept: Unrecognized EPT dataType: zstandard
```

```
$ pdal --version
pdal 2.0.1 (git-version: Release)
```
There was a merge request some time ago at:
https://github.com/PDAL/PDAL/pull/2561
that apparantly had no follow-up. Likely because this branch is waiting to be merged?
https://github.com/PDAL/PDAL/tree/ept-zstandard-updates

What is the current advise on using zstandard?

**Comment by connormanning** [comment]
I didn't realize we'd let this one slip.  I'm doing a bit of EPT reader work currently, I'll make sure to get the ZStandard code up to date and open a new PR for that while I'm at it.
