### ISSUE TITLE
pdal tool can not use - undefined symbol

### ISSUE THREAD

**Issue by tonylinquantw** [PDAL/PDAL#2751]
When I excute pdal of linux, it apears this message "undefined symbol: GDALDatasetCreateLayer".
And excute pdal of windows, it apears "not found gdal300.dll"
Please help me to solve this problems, thanks.

**Comment by tonylinquantw** [comment]
I got this message: 
./pdal: symbol lookup error: /home/tony/pdaltest/pdal-2.0.1-py37h7e15382_5/bin/../lib/libpdal_base.so.9: undefined symbol: GDALDatasetCreateLayer

**Comment by abellgithub** [comment]
It appears you don't have GDAL installed.

**Comment by tonylinquantw** [comment]
Thanks to your apply, when update gdal, it has been solved. 
But still has another problem.
./pdal: symbol lookup error: /home/tony/las2pcdtool/pdal/pdal-2.0.1-py37h7e15382_5/bin/../lib/libpdal_base.so.9: undefined symbol: _Z33OGRCreateCoordinateTransformationPK19OGRSpatialReferenceS1_RK34OGRCoordinateTransformationOptions

**Comment by tonylinquantw** [comment]
my gdal version is "GDAL 2.2.2, released 2017/09/15"

**Comment by abellgithub** [comment]
Without knowing more about how you've built/obtained GDAL we really can't help you. You might verify the GDAL library that you're using with `ldd` and then look at the symbols in that library with `nm` or `readelf`.
