### ISSUE TITLE
Ability to specify data types of custom dimensions when created by the Python filter stage

### ISSUE THREAD

**Issue by pramukta** [PDAL/PDAL#2755]
Thanks for all the work on PDAL, it's super awesome!  Was playing around prototyping a stage in Python and found that, currently, it looks like the `add_dimension` option always creates double precision floats:

https://github.com/PDAL/PDAL/blob/b65725eb7ecae77562f284f8f1e53f031389f370/plugins/python/filters/PythonFilter.cpp#L97

Also looks like a similar behavior happens in `filters.ferry`:

https://github.com/PDAL/PDAL/blob/08fb529e63db71491e530f3f1b737bf2b2ffe612/filters/FerryFilter.cpp#L97

The result is that I couldn't find a way to prototype a stage in Python that needs to return a uint64.  For example, this pipeline/script that tries to add a global 64-bit z-ordering: https://gist.github.com/pramukta/ff37596e180001cefbd49aa7030c3e99

Could/should a `datatype` option be added to the stage config to support this kind of use case?  I'm not very familiar with the codebase but will give it a shot as well.  If there's another way to approach this that I'm not seeing, that would be good to know too.

**Comment by abellgithub** [comment]
This can be done, but your use case is unusual. Needing 64 bits of integer
precision seems strange and isn't supported by the ply format anyway.

**Comment by pramukta** [comment]
Oh sorry, the ply writer is just a placeholder for testing.

**Comment by abellgithub** [comment]
I think I would just add an optional type to the current `add_dimensions` option:

```
"add_dimensions" : "foo, bar=uint64_t"
```

**Comment by pramukta** [comment]
AH, missed the ply writer example before this PR.  It looks like it does a type lookup and uses some utils I didn't realize existed.  Can update it on Monday if that is the preferred behavior.

**Comment by pramukta** [comment]
Moving discussion over to the PR

**Comment by pramukta** [comment]
Closing this issue following merge of #2756
