### ISSUE TITLE
NormalZ is positive but filters.range sometimes takes into account as negative

### ISSUE THREAD

**Issue by tomvantilburg** [PDAL/PDAL#2760]
Manual says: `By default, the Normal filter will invert normals such that they are always pointed “up” (positive Z). `

It seems that when running a filters.range after the filters.normal, it still uses a version of NormalZ that has negative values. This can be reproduced by:

Download the example data:
[example.zip](https://github.com/PDAL/PDAL/files/3649342/example.zip)

Run 'pdal pipeline' with the following pipeline:
```
[
        "example.las",
        {
         "type": "filters.normal",
         "knn": 8
        },{
         "type": "filters.range",
         "limits": "NormalZ[0:1]"
        },
        "filtered.las"
]
```
Expected result would be to have the same amount of points out as points in (since the range of `NormalZ` should not be negative).
Observed result is that it is cutting about half of the points (in this case one side of the roof). When using a range of `[-1:1]` all points are returned and with `NormalZ` values all between 0 and 1.

```
$pdal --version
pdal 2.0.1 (git-version: Release)
``` 
This behaviour was observed after upgrading from 1.9.x to 2.0.1

Related issue where NormalZ was made always up:
https://github.com/PDAL/PDAL/issues/1638

**Comment by chambbj** [comment]
I was able to recreate this with the release version of 2.0.1. I believe it's related to a bug in the alt_names for the normal dimensions that was fixed in https://github.com/PDAL/PDAL/pull/2723. If you run from master, I think you should be good.

**Comment by abellgithub** [comment]
This makes me wonder about case sensitivity in dimension names.  Perhaps we need a pass through the code to see where this is and isn't an issue and decide on a policy.

**Comment by chambbj** [comment]
It wasn't clear to me _exactly_ what was happening, but it was clear that the alternate names (and perhaps case) had something to do with it. I saw a number of strange things. In addition to the reported issue, I also noted that `pdal info` did not show NormalZ at all, but it was clearly being written, as I could load it into Quick Terrain Modeler.

**Comment by tomvantilburg** [comment]
Closing since currently I have no ability to build a new version but solution of @chambbj seems higly likely to have fixed this.
