### ISSUE TITLE
splitter pipeline only returns "Killed" in the terminal

### ISSUE THREAD

**Issue by spiegelss** [PDAL/PDAL#2775]
**Describe the bug**
Good morning!
I am attempting to run a pipeline to split up a large point cloud into smaller ones using the **filters.splitter**.  I have attempted this in both the conda version as well as the Docker version of PDAL and am getting the output "Killed" in my terminal window.  My pipeline is as follows:

```json
{
  "pipeline":[
                {
                  "type":"readers.las",
                  "filename":"/path/to/data/file.las"
                },
                {
                  "type":"filters.splitter",
                  "length":"500"
                },
                {
                  "type":"writers.las",
                  "filename":"/path/to/data/file_#.las"
                }
  ]
}
```

My PDAL version in Conda is 2.0.1 and the Docker version is 2.0.0.  Thank you!

**Comment by abellgithub** [comment]
Without knowing any more, I'd suspect you're running out of memory.  You might try `pdal tile` instead.

**Comment by spiegelss** [comment]
That worked!  I originally tried reducing the size with a voxelcentroid filter but I guess my cell size wasn't large enough.  Thanks!
