### ISSUE TITLE
Native ICP slower than previous ICP variant

### ISSUE THREAD

**Issue by chambbj** [PDAL/PDAL#2786]
User has reported that new ICP (PDAL v2.0.1) is 25x slower than the previous PCL version (PDAL v1.9.1). If the translation threshold is changed from default of 9e-8 to 1e-4, then the two algorithms run for about the same duration, but with degraded results.

Thresholds and defaults should be identical to PCL, though I seem to recall the convergence criteria not being 100% identical. I _think_ this is where I should start looking.

Quiver plot of results also appear to be different, mostly in magnitude of the vectors. Through closer analysis, using known distortions, 2.0.1 seems to recover the the motion better. In this test, ICP was only about 2x slower.

**Comment by hobu** [comment]
reopen with specific data and test scenarios.
