### ISSUE TITLE
filters.hag: Input PointView does not have any points classified as ground

### ISSUE THREAD

**Issue by antun008** [PDAL/PDAL#2787]
Can you help me?
I wanted to create height above ground but I always have this same error in Filters.hag: filters.hag: Input PointView does not have any points classified as ground.
Under this text is the code that Mathieu presented on his presentation. Please help me!:)

In filters.hag is problem!

Las file of the cathedral of Zagreb is on this link:
[https://www.dropbox.com/s/05sa4ww53pnsws1/KatedralaAntun.las?dl=0](url)

`from IPython.display import YouTubeVideo
YouTubeVideo('GSPcyhSAgTQ',start=7, end=31)

import glob
import io
import ipyleaflet
import IPython.display
import ipyvolume.pylab as p3
import json
import matplotlib.cm
import matplotlib.pyplot as plt
import numpy as np
import os
import pandas as pd
import pdal
import PIL
import pyproj
import requests
import shapely.geometry
import scipy.spatial
import sys
import urllib.request

%reload_ext autoreload
%autoreload 2

sys.path.append('C:\\Users\\Antun Jakopec\\Desktop\\point-cloud-processing-master\\src')
from pcl_utils import local_max

IVaerial = "https://geoservices.informatievlaanderen.be/raadpleegdiensten/ogw/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&CRS=EPSG:31370&BBOX={0},{1},{2},{3}&WIDTH=512&HEIGHT=512&LAYERS=OGWRGB13_15VL&STYLES=default&FORMAT=image/png"

%matplotlib inline

# Download the LAS data file if not already present
if not os.path.isdir('C:\\Users\\Antun Jakopec\\Desktop\\point-cloud-processing-master'):
    os.makedirs('C:\\Users\\Antun Jakopec\\Desktop\\point-cloud-processing-master')
lidar_filename = 'KatedralaAntun.las'`

`cropper = {
    "pipeline": list(glob.glob('C:\\Users\\Antun Jakopec\\Desktop\\point-cloud-processing-master\\KatedralaAntun.las')) + [ 
        {   "type":"filters.crop",
            'bounds':"([-134.235626,108.348953],[-112.379776,119.230927])"},
        {   "type":"filters.merge"},
        {   "type":"filters.hag"},  
        {   "type":"filters.crop",
            'polygon':"POLYGON((-134.235626 -112.379776, 108.348953 -112.379776, 108.348953 119.230927, -134.235626 119.230927, -134.235626 -112.379776))"},        
        {   "type":"filters.eigenvalues",
            "knn":16},
        {   "type":"filters.normal",
            "knn":16}        

    ]}

pipeline = pdal.Pipeline(json.dumps(cropper))
pipeline.validate()

%time n_points = pipeline.execute()`

**Comment by luipir** [comment]
No idea what version is... but cold be related with https://github.com/PDAL/PDAL/issues/2275 if PDAL version is less than 1.9?

**Comment by chambbj** [comment]
@antun008 `filters.hag` will not attempt to classify points as ground on it's own. You must have ground classifications from some other source. In many cases, I'd suggest `filters.smrf`, but this may not work all that well with your data, as I see your ground surface seems to have multiple levels to it, perhaps stitched together from multiple, poorly aligned scans.
