### ISSUE TITLE
PCD writer should write FIELD names in lowercase

### ISSUE THREAD

**Issue by spiegelss** [PDAL/PDAL#2789]
[issues.zip](https://github.com/PDAL/PDAL/files/3768077/issues.zip)
**Describe the bug**
Good morning! 
I am attempting to utilize the [writer.pcd](https://pdal.io/stages/writers.pcd.html).  I am using the region growing segmentation algorithm similar to the one found in [point cloud library tutorial](http://pointclouds.org/documentation/tutorials/region_growing_segmentation.php).  However, when I convert the las to a pcd, it is not viewable in software such as cloud compare, as there seems to be something wrong with the PCD file (see png in the zip folder).  Below is my pipeline.  Thank you!

```
{
  "pipeline":[
    {
      "type":"readers.las",
      "filename":"autzen.las"
    },
    {
      "type":"writers.pcd",
      "filename":"autzen.pcd",
      "order":"X=Float,Y=Float,Z=Float,Intensity=Unsigned32",
      "keep_unspecified":"false"
    }
  ]
}
```

**Expected behavior**
I expect the pcd file to load and be viewable.  

**System/installation information:**
PDAL version 2.0.0 in a Docker container running on Linux 18.04.

**Comment by spiegelss** [comment]
Indeed, manually editing the header did the trick.  Thank you!

**Comment by chambbj** [comment]
Reopening to remember to fix this.
