### ISSUE TITLE
About creating a raster from a point cloud

### ISSUE THREAD

**Issue by KeoChi** [PDAL/PDAL#2803]
I know that the writers.gdal can creates a raster from a point cloud using an interpolation algorithm. And I know another way that creates a raster grid based on [a Delaunay triangular irregular network](https://jblindsay.github.io/wbt_book/available_tools/lidar_tools.html#LidarTinGridding). Do you plan to implement the method in pdal?

**Comment by abellgithub** [comment]
I don't think this is currently in the plans, though it has come requested previously.  If it's something you need and would be willing to fund, please let us know.
