### ISSUE TITLE
Allow OAMS_TRADITIONAL_GIS_ORDER for GDAL 3+

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#2804]
Because of the inadequacies in how SRSs can be defined with WKT1 and their interaction with GDAL/PROJ, it is sometimes necessary for users to override the axis ordering of the definition. GDAL provides 

`srs->SetAxisMappingStrategy(OAMS_TRADITIONAL_GIS_ORDER)`

to achieve this task. Background for reasons why can be found in the [GDAL Barn RFC](https://gdal.org/development/rfc/rfc73_proj6_wkt2_srsbarn.html).

PDAL needs a mechanism for the user to control the behavior of `OAMS_AUTHORITY_COMPLIANT` or `OAMS_TRADITIONAL_GIS_ORDER` when it uses GDAL 3.0+.

**Comment by hobu** [comment]
I think this should be provided as part of the ``spatialreference`` option.

For example, this would use the SRS of the LAS file but switch the axis ordering:
```
{
    "type": "readers.las",
    "spatialreference": "OAMS_TRADITIONAL_GIS_ORDER"
}
```
Overriding the SRS would follow the same adhoc SRS definition syntax we're using for assigning it on geometries: 
```
{
    "type": "readers.las",
    "spatialreference": "EPSG:4326 / OAMS_TRADITIONAL_GIS_ORDER"
}
```

I think that we should NOT default to assigning OAMS_TRADITIONAL_GIS_ORDER, however. It is too easy to get the wrong behavior, and we should let GDAL/PROJ figure it out.

**Comment by msmitherdc** [comment]
we will need this as not having this will negatively affect existing data. But shouldn't that perhaps be an option on the spatial reference. I don't really like the " srs / option" syntax

**Comment by hobu** [comment]
> an option on the spatial reference.

`spatialrefernce` isn't compound (and neither is `bounds` or `geometry`). I like the compound syntax better myself, but that's not what PDAL does.

**Comment by abellgithub** [comment]
What do you mean that it isn't compound?  It's an opaque string to us.

**Comment by hobu** [comment]
I think @msmitherdc is asking for this style of definition:

```
{ 
    "spatialreference": 
    {
        "definition": "PROJ_CS ....",
        "axis_ordering": "OAMS_TRADITIONAL_GIS_ORDER"
    }
}
```

**Comment by abellgithub** [comment]
I don't care, but I don't think using a GDAL environment variable name is the way to go.

Does this only matter when you're doing a transform?

**Comment by hobu** [comment]
> I don't think using a GDAL environment variable name is the way to go.

I disagree. GDAL users are going to be searching for that variable name too. Why would we we change the name of the behavior?

**Comment by abellgithub** [comment]
Because we're not GDAL.  Maybe we'll decide not to use GDAL for transforms.  And it's a long and confusing name.

If this is just an issue for transforms (I'm 99% sure it is - I spent some time in that GDAL code), then allow people to specify the exact order in that filter, IMO.

**Comment by hobu** [comment]
> then allow people to specify the exact order in that filter, IMO.

Please illustrate with some syntax.

**Comment by abellgithub** [comment]
GDAL just uses numbers internally:

SetDataAxisToSRSAxisMapping({1, 2}) or {2, 1} or {3, 1}.

Seems reasonable to support that.  Traditional mapping is {2, 1, 3}.  Standard is {1, 2, 3}.  But you can map in any way you want.  I would just let people set the order as above:

```
  axis_order = [3, 1, 2];
```

**Comment by hobu** [comment]
I like this syntax just fine. It would mean making `spatialreference` a compound object though.

**Comment by abellgithub** [comment]
No.  You just stick that option on `filters.reprojection`, I think.

**Comment by hobu** [comment]
it's about more than just reprojecting data with `filters.reprojection`. It's about any downstream consumers of the spatial reference. We should force people to reproject data to simply swap the axis interpretation.
