### ISSUE TITLE
filters.colorinterp seams to be broken

### ISSUE THREAD

**Issue by vilaa** [PDAL/PDAL#2813]
**Describe the bug**
A clear and concise description of what the bug is, including steps to reproduce the behavior. This typically means providing the PDAL commands you are using (e.g., `pdal translate ...`) and if applicable the contents of any PDAL pipelines you are running.

```
$ pdal translate --filters.colorinterp.mad=true --filters.colorinterp.dimension="Z" --filters.colorinterp.k=2 --filters.colorinterp.ramp="pestel_shades" point_cloud.las test_colorinterp.las filters.colorinterp



```
Point cloud colors are set to 0,0,0 into the valid range, and outside original value are kept. (See attached screenshot, and files). I've tried other color map and default values for all parameters. Output shows black color everywhere. 

Screenshot :
![image](https://user-images.githubusercontent.com/45284585/69253474-ff17f380-0bb4-11ea-836b-315fa31681eb.png)

Files :
[point_cloud_files.zip](https://github.com/PDAL/PDAL/files/3870035/point_cloud_files.zip) 

**Expected behavior**

Colors should be set with the "pestel_shade" default color ramp, according to "Z" dimension values, scaled with k parameter using mad method. 

**System/installation information:**

I use the docker images pulled from docker hub (pdal/pdal). However I've tried with my local install with pdal 2.0.1 and gdal 3.0, using same command and also using python API. I observed the same behavior. 

```
$ uname -a
Linux 932efcc81333 4.15.0-70-generic #79-Ubuntu SMP Tue Nov 12 10:36:11 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ pdal --version
$-----------------------------------------------------------------------------------------------------
pdal 2.0.0 (git-version: b02be4)
-----------------------------------------------------------------------------------------------------
```

**Comment by abellgithub** [comment]
I'm not able to recreate this.  I'm seeing values on the input file from 0-65535 (or about that) and on output from 0-255, which matches the color ramp.

**Comment by vilaa** [comment]
You're right, Using the "force 8 bit color" loading flags of cloudcompare my problem is fixed.
