### ISSUE TITLE
assignment based on a bounding box

### ISSUE THREAD

**Issue by spiegelss** [PDAL/PDAL#2818]
Good morning,

I know that "filters.assign" can be used to assign values based on a condition but I was wondering if this was possible with a bounding box.  I know that I could use the "filters.crop" combined with "filters.assign" to create separate point clouds and then merge them back together but I would like to avoid that if possible.  Is this something that can be done or maybe can this be a feature request?  Feel free to close this if this would be more appropriately posted in the mailing list.  Thank you!

**Comment by abellgithub** [comment]
See `filters.overlay`.
