### ISSUE TITLE
filters.assign only accepts a single condition

### ISSUE THREAD

**Issue by abellgithub** [PDAL/PDAL#2825]
The documentation says otherwise.

**Comment by tomvantilburg** [comment]
Just hit this for the second time (completely forgot about it). IMHO just changing the docs would be fine, adding a new assignment filter for every assignment is not that big deal for me.

**Comment by abellgithub** [comment]
Fixed in documentation. Suggest people use new 'value' syntax. 99230c2904c42cae53455c6b5da44a406da05626
