### ISSUE TITLE
Tindex does not interpret driver options

### ISSUE THREAD

**Issue by jratike80** [PDAL/PDAL#2830]
With a plain x y z file "test.xyz" that is space separated and without header line

```
601732.520 6854107.550 -6.17
601737.520 6854107.550 -6.45
```
pdal info can read the data when helped with extra parameters
`pdal info --driver readers.text --readers.text.header="x y z" test.xyz`

However, extra parameters do not help with tindex
```
pdal tindex create --tindex boundary.sqlite --driver readers.text --readers.text.header="x y z" --filespec test.xyz -f sqlite
PDAL: Cannot determine reader for input file: test.xyz
```
PDAL version is "pdal 1.8.0 (git-version: Release)" installed with OSGeo4W on Windows 10.

**Comment by jratike80** [comment]
New test with pdal 2.0.1 with the same error as a result.

**Comment by hobu** [comment]
Added in #4098
