### ISSUE TITLE
Enforce GDAL_FIX_ESRI_WKT in pdal::SpatialReference

### ISSUE THREAD

**Issue by gui2dev** [PDAL/PDAL#2839]
Using `pdal::SpatialReference::getWKT()` string does not allow to generate a good `QgsCoordinateReferenceSystem` in QGIS (for instance).

This is related to QGIS issue [#5598 ](https://issues.qgis.org/issues/5598) and GDAL issue [#4673](https://trac.osgeo.org/gdal/ticket/4673) and [solved ](https://qgis.org/api/qgscoordinatereferencesystem_8cpp_source.html#l00356) in QGIS by setting `GDAL_FIX_ESRI_WKT` to `GEOGCS`
It does not impact the PDAL internal behaviour, but it allows bad WKT SRS to be written in LAS headers.

**Comment by hobu** [comment]
I'm anxious about enforcing this in such a way that PDAL users can't control it themselves. `GDAL_FIX_ESRI_WKT=GEOGCS`? Users can set this environment variable and control the behavior without intervention from PDAL. 

Can you provide a scenario where "bad WKT" is emitted?

**Comment by gui2dev** [comment]
In our application, we use qgis ui to select a default CRS for our point clouds before loading, as it is not systematically define in the LAS header, or if we want to reproject the point to another system (using PDAL API).

Then we provide the `table::spatialReference()` as WKT to qgis ui to set the map canvas CRS (so back to agis CRS). Most of the time, the CRS (as WKT) is badly interpreted.

The thing is that QGIS only sets `GDAL_FIX_ESRI_WKT=GEOGCS` when it has to read create a CRS from WKT string.

**Comment by rouault** [comment]
GDAL_FIX_ESRI_WKT is mostly a hacky attempt of the GDAL 1.x and 2.x era to try to massage ESRI WKT into the WKT1 variant that GDAL supported. In GDAL 3, this option has completely disappeared. PROJ 6 does all this massaging work, and in a much better way than GDAL_FIX_ESRI_WKT ever did.

**Comment by hobu** [comment]
>  In GDAL 3, this option has completely disappeared.

I'm not enthused to add this given that it is removed in GDAL 3 and you can control it by setting an environment variable before you start QGIS.

**Comment by gui2dev** [comment]
Guess I'll just have to update to gdal 3 and proj 6 then 😊
Thanks.
