### ISSUE TITLE
Set operations with PDAL?

### ISSUE THREAD

**Issue by jgrn307** [PDAL/PDAL#2840]
Is it possible to use PDAL to do set operations (given some distance threshold) between two point cloud datasets?  This would be a filter such as intersections, unions, differences, etc.  Related: is there a point-to-point distance tool between two lidar datasets?  This would be a feature request if it doesn't already exist.

**Comment by abellgithub** [comment]
We don't have such a filter.  Sorry.

**Comment by chambbj** [comment]
For the point-to-point distances between clouds, closest I can think of is our [`hausdorff`](https://pdal.io/apps/hausdorff.html) subcommand. Not sure how well this aligns with what you are looking for.
