### ISSUE TITLE
Additions for pdal info

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#2848]
- [x] `filesize` entry for formats for which this has meaning
- [x] `stage` entry to denote which reader was used to read the data
- [ ] point count histograms from `readers.las` output  ( number of point records / number of points by return)
- [ ] `header_offset` for `readers.las` output
- [ ] `file_extension` (`.las` or `.laz` for LAS content, `.bpf` or `bpz` for BPF, empty for `readers.ept`, etc)
- [ ] If the driver that read it was a plugin
- [ ] BPF matrices
- [ ] BPF ULEM info
- [ ] any extra options passed in via CLI

**Comment by hobu** [comment]
#2899 is tracking some of this

**Comment by davelajoie** [comment]
Hello! was wondering if there is a python equivalent of pdal info --all? I looked at filter.stats but I am not sure it would yield the same output. Also technically I could do a system call do achieve this as well :)

**Comment by hobu** [comment]
There is https://pdal.io/stages/filters.info.html which is a stage you can put in your pipelines to get this stuff.

**Comment by davelajoie** [comment]
Tx, I wasn't sure it would yield the same output as pdal info. I will test and report back
