### ISSUE TITLE
Assert failed for pdal::geometry destruction

### ISSUE THREAD

**Issue by gui2dev** [PDAL/PDAL#2850]
Hi there,

I'm using pdal with MSVC14.
In debug, I'm getting an assertion failure from [`std::unique_ptr<OGRGeometry> Geometry::m_geom;`](https://github.com/PDAL/PDAL/blob/25939eead241838adb7bf637f0d2e14763cabba5/pdal/Geometry.hpp#L86) destruction, at the end of [`void HexBin::done(PointTableRef table)`](https://github.com/PDAL/PDAL/blob/25939eead241838adb7bf637f0d2e14763cabba5/filters/HexBinFilter.hpp#L80)

From 

> C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\memory

```C++
void operator()(_Ty *_Ptr) const _NOEXCEPT
	{	// delete a pointer
	static_assert(0 < sizeof (_Ty),"can't delete an incomplete type"); //FAILED HERE
	delete _Ptr;
	}
};
```
<details>
Custom build (master / 510bc65ca222fcbda3be90b51f5055a82367699a) on Windows using MSVC14 / CMAKE 3.16.1 and latest osgeo redist.

```C++
#include <memory>
#include <pdal/PointTable.hpp>
#include <pdal/PointView.hpp>
#include <pdal/LasReader.hpp>
#include <pdal/filters/HexBinFilter.hpp>
#include <pdal/Options.hpp>

using namespace pdal;

int main(int argc, char* argv[])
{
FixedPointTable table(100);
LasReader reader;

Option las_opt("filename",filename);
Options las_opts;
las_opts.add(las_opt);
reader.setOptions(las_opts);

  auto convertOne = [&](PointRef& point) { return true;};

  StreamCallbackFilter f;
  f.setCallback(convertOne);
  f.setInput(reader);

HexBin  hex;
hex.setInput(f);

hex.prepare(table);
hex.execute(table); //will fail here in debug

return 0;
}
```
</details>

**Comment by abellgithub** [comment]
You'll need to provide a complete report for us to look into this.  Please see the issue template.  You can omit the conda information if you aren't using conda, but then do say how you built/installed PDAL.

**Comment by gui2dev** [comment]
@abellgithub, I added some details.

**Comment by abellgithub** [comment]
OSGEO does not support debug builds.  Unless you're building all dependent packages yourself in debug mode, PDAL will not work reliably.  Sorry.

**Comment by gui2dev** [comment]
That's ok, I'll figure a workaround to be able to dig deeper.

**Comment by abellgithub** [comment]
This may be helpful:

https://docs.microsoft.com/en-us/cpp/build/how-to-debug-a-release-build?view=vs-2019
