### ISSUE TITLE
PlyWriter with filters.cluster

### ISSUE THREAD

**Issue by joaobrittoneto** [PDAL/PDAL#2851]
The cluster filter seems not to work with a ply file, providing following message:

`PDAL: writers.ply: Can't write dimension of type 'uint64_t'.`

Testing with 2.0.1 with:

`pdal translate in.ply out.ply -f filters.cluster`.
with `in.ply`
```
ply
format ascii 1.0 
comment Generated by PDAL
element vertex 3
property float64 x
property float64 y
property float64 z
property int32 i
end_header
1.234 2.345 3.456 10
2.345 3.456 4.567 12
0.000 0 0 0
```

Maybe it's the case to use uint32_t in the cluster filter?

**Comment by abellgithub** [comment]
You can specify the dimensions and types for output with `writers.ply`.  See the `dims` option of the [PLY writer](https://pdal.io/stages/writers.ply.html).

**Comment by joaobrittoneto** [comment]
Thanks for the reply.

Sorry for that, but I'm still not sure how to use it.

I'm trying 
```
pdal translate in.ply out_test.ply -f filters.cluster -w writers.ply --writers.ply.dims="X,Y,Z,i,ClusterId=uint32"
```
but I am getting `PDAL: writers.ply: Unknown dimension 'ClusterId' in provided dimension list.`
Also tried with `clusterid`, without the type, but still the same result.

Thanks in advance

**Comment by abellgithub** [comment]
I noticed that the specific dimension name was omitted from the documentation.  I have made a change to rectify this.

**Comment by joaobrittoneto** [comment]
Thanks again.

One more related question:
Is there a way to get the properties of the input ply file?
If one property is omitted, e.g. `i` in the above example, it is excluded in the output ply file.

If the properties of the input ply are unknown, would be nice to have a way to just pass them forward  to the output ply, and just add the properties of the current filter (while being able to change its type).

**Comment by abellgithub** [comment]
`i` is read properly as far as I'm aware.  If the example file is `in.ply`, `pdal translate in.ply out.ply` will generate `out.ply` containing the variable `i`.

**Comment by joaobrittoneto** [comment]
Without specifying the dimension, yes.

But in this example: 
```
pdal translate in.ply out_test.ply -f filters.cluster -w writers.ply --writers.ply.dims="X,Y,Z,ClusterID=uint32"
```
provides the output without `i`:
```
ply
format ascii 1.0 
comment Generated by PDAL
element vertex 3
property float64 x
property float64 y
property float64 z
property uint32 clusterid
end_header
1.234 2.345 3.456 1
2.345 3.456 4.567 2
0 0 0 3
```
```

**Comment by abellgithub** [comment]
You didn't ask for `i` to be written.

**Comment by joaobrittoneto** [comment]
Sorry if I was not clear.

My question is how to propagate all the properties from the input to the output ply, without explicitly asking for each property individually.

Lets says the `in.ply` is:

```
```

**Comment by abellgithub** [comment]
The issue is the one that opened this ticket -- PLY doesn't support 64-bit integers.  If you weren't including a field that was stored as a 64-bit integer, things would work as you're wanting.

I think this is an unusual case and I don't think it warrants special code since there is a reasonable workaround.

There may be a case for allowing `filters.cluster` to store the cluster ID in some dimension with a specific type.
