### ISSUE TITLE
filter.neighborclassifier does nothing

### ISSUE THREAD

**Issue by vsantalov** [PDAL/PDAL#2861]
Filter neighborclassifier appears to do nothing. The image below shows misclassified points on the building edge due to a nearby tree. I experimented with many "k" values ranging from 1 to 1000. There is no change to the ranking anywhere in the file with filter application. I also tried ferrying "Rank" values to "Classification" and applying neighborclassifier to "Classification" - no effect. 
No errors are shown when I run the pipeline.
PDAL version 2.0.1

```
{
    "pipeline": [
        {
            "type": "filters.elm"
        },
        {
            "type": "filters.outlier"
        },
        {
            "type": "filters.range",
            "limits": "Classification[0:6]"
        },
        {
            "type": "filters.estimaterank",
            "knn": 120,
            "thresh": 0.05
        },
        {
            "type": "filters.neighborclassifier",
            "domain": "Rank[3:3]",
            "k": 3
        }
    ]
}
```

![image](https://user-images.githubusercontent.com/12448681/71821546-c8187700-3068-11ea-82eb-bba7597db045.png)

**Comment by vsantalov** [comment]
I got it to work. The filter only works on "Classification" field. Last time I tested with "Classification", I specified the wrong range ([2:2] instead of [3:3]). Here is the working pipeline:
```
{
    "pipeline": [
        {
            "type": "filters.elm"
        },
        {
            "type": "filters.outlier"
        },
        {
            "type": "filters.range",
            "limits": "Classification[0:6]"
        },
        {
            "type": "filters.estimaterank",
            "knn": 120,
            "thresh": 0.05
        },
        {
            "type": "filters.ferry",
            "dimensions": "Rank=>Classification"
        },
        {
            "type": "filters.neighborclassifier",
            "domain": "Classification[3:3]",
            "k": 100
        }
    ]
}
```

**Comment by chambbj** [comment]
Glad you got it to work @vsantalov, but are you sure that it wouldn't have simply worked with the correct range (`Rank[3:3]`) using your first pipeline? I very quick glance at both the docs and the code indicate that it should not be limited to classification, but rather any correctly specified `DimRange`. If it still does not work, we may need to take a closer look and should update either the filter or the docs so that they at least match.

**Comment by vsantalov** [comment]
I just reran it with Rank[3:3]. I can confirm, it does not work. In the documentation, when you specify a candidate you don't need to specify a dimension. That's why I initially got the idea that "Classification" might be hard-coded.

**Comment by abellgithub** [comment]
I don't understand the problem.  Can you specific about what you think the issue is?

**Comment by vsantalov** [comment]
@abellgithub - neighborclassifier appears to only work with ```Classification``` and not any other DimRange. As a suggestion for improvement, this could be addressed either in the documentation or in the filter itself to accept other dimensions. The observed behavior is that if any other dimension is provided for the ```domain``` option, for example, ```Rank[3,3]```, the pipeline will run without errors but produce no results from the filter.

**Comment by chambbj** [comment]
@vsantalov I finally stepped through what you were actually trying to do. Your first attempt, using Rank as the domain in `filters.neighborclassifier` with no `filters.ferry` involved, does in fact write the updated values, but back to the Rank dimension, which perhaps you did not expect (I'm guessing you were looking in Classification). If you want that in Classification, you can ferry it, before or after the `filters.neighborclassifier`. You can also write to a format that can store Rank, including possibly to an LAS `extra_dim`.

**Comment by vsantalov** [comment]
@chambbj Hmm. I did inspect the Rank dimension, the file I used had all Classification set to 0. I've written to ascii format to preserve the Rank dimension

**Comment by abellgithub** [comment]
@vsantalov: If you still think there's a bug, you should provide a test file (preferably small), a specific test case and describe the expected output that differs from actual output.  Thanks.

**Comment by vsantalov** [comment]
As requested. Here is everything you need to reproduce the behavior.

### My test file
[nogr.zip](https://github.com/PDAL/PDAL/files/4027365/nogr.zip)

### neighborclassifier with Rank dimension
json:
[neighbor_classifier_rank.txt](https://github.com/PDAL/PDAL/files/4027449/neighbor_classifier_rank.txt)
resulting point cloud:
[rank.txt](https://github.com/PDAL/PDAL/files/4027426/rank.txt)
unexpected result image:
![rank_result](https://user-images.githubusercontent.com/12448681/71841456-d466f900-3095-11ea-845e-a70a8c0f2bbf.jpg)

### neighborclassifier with Classification dimension and ferry
json:
[neighbor_classifier_classification.txt](https://github.com/PDAL/PDAL/files/4027358/neighbor_classifier_classification.txt)
resulting point cloud:
[classification.txt](https://github.com/PDAL/PDAL/files/4027429/classification.txt)
expected result image:
![classification_result](https://user-images.githubusercontent.com/12448681/71841507-f06a9a80-3095-11ea-87b8-f3515e8ba0b5.jpg)

**Comment by abellgithub** [comment]
I don't see any difference in these pictures.

I've looked at the code.  We only modify the Classification dimension.  The two pipelines that you've provided aren't really comparable, as `neighbor_classifier_classification.txt` overwrites the input classification with rank values.

I still don't understand what you think your problem is.  Perhaps using `pdal info` on the output file would allow you to provide a clear story about the difference you're seeing that you think is wrong.

**Comment by abellgithub** [comment]
To be clear, the way the code reads to me, it appears that your first case -- the one that filters on rank, will ONLY modify the classification of points that have a rank of 3.  Then it will only modify the classification if the neighboring points "vote" for some other classification other than the current one.

**Comment by vsantalov** [comment]
In ```neighborclassifier_classification.txt``` when I overwrite the input classification with rank values, I can successfully update the classification 3 values by neighbor votes. If I apply neighborclassifier directly to rank dimension as in ```neighbor_classifier_rank.txt```, the rank 3 values remain unchanged when I write the output to some some format that supports extra dimensions (or extra_dims option).
You can see the results in circled areas, where in the first image the roof edges next to trees contain red points (rank 3), that were not voted out by green neighbors (rank 2). The roof edges in the second image are green. The first image shows values from Rank dimension after applying neighborclassifier directly to the Rank dimension. The second image shows values from Classification where neighborclassifier was applied to Classification with copied Rank values in it. What I am seeing, is that I can write neighbor vote results to Classification but not to Rank.

**Comment by abellgithub** [comment]
Well, this is how it works.  The `domain` argument is a filter, it has nothing to do with setting classifications.  In your initial example, you only wanted the voting algorithm applied to points with a `Rank` of 3.

**Comment by vsantalov** [comment]
Correct. But the algorithm in my case does nothing when applied to direcy to Rank dimension. I get the same ranks in the output file as the input. Please run my neighbor_classifier_rank on the last file I shared and see if any of the Rank 3 points change to neighboring Rank 2. In my case they don't.
For some reason if you essentially rename the Rank dimension to Classification dimension, the points get reranked as expected.

**Comment by abellgithub** [comment]
I'm not sure how many ways I can say this.  The filter ONLY modifies the Classification.  It never modifies Rank.  That's how it works.

**Comment by vsantalov** [comment]
I am sorry I have missed all the other times you have said this. This answers my question. I went down this rabbit hole because @chambbj  was able to modify the Rank field directly as the quoted reply shows. Since this is the expected behavior, I will close the issue. Thank you for your time.

> @vsantalov I finally stepped through what you were actually trying to do. Your first attempt, using Rank as the domain in `filters.neighborclassifier` with no `filters.ferry` involved, does in fact write the updated values, but back to the Rank dimension, which perhaps you did not expect (I'm guessing you were looking in Classification). If you want that in Classification, you can ferry it, before or after the `filters.neighborclassifier`. You can also write to a format that can store Rank, including possibly to an LAS `extra_dim`.

**Comment by chambbj** [comment]
That was my mistake @vsantalov. My apologies for leading you down the rabbit hole. Once it was confirmed by @abellgithub that the code only writes to Classification, I realized that the behavior I thought I'd observed was in fact wrong. I think we've made a note that the documentation surrounding this filter may be a bit misleading and will work to improve it.

**Comment by abellgithub** [comment]
I'm sorry if I came across as gruff.  It just seemed we weren't communicating and I wasn't sure what else to say.  I think it may be a good idea to make a way to use this filter to modify other dimensions, but that's a separate task.  As @chambbj suggests, I'll make a pass at the documentation to make it more clear.  I think the first example might be a little misleading.

Thanks,
