### ISSUE TITLE
Using Poisson Filter twice causes a segfault

### ISSUE THREAD

**Issue by bgutz001** [PDAL/PDAL#2873]
**Describe the bug**
A segfault occurs when executing two PoissonFilters. The first one executes fine. The second one causes a crash.

Stacktrace:
> C  [pdalcpp.dll+0x1a1079]  Octree<double>::init<Point3D<double> >+0x409
C  [pdalcpp.dll+0x1a1a07]  loadOctTree<double>+0xb7
C  [pdalcpp.dll+0x1bf4f6]  PoissonRecon<double>::readData+0x186
C  [pdalcpp.dll+0x1bb617]  PoissonRecon<double>::execute+0x197
C  [pdalcpp.dll+0x1c2864]  pdal::PoissonFilter::run+0x224
C  [pdalcpp.dll+0x34ead7]  pdal::StageRunner::run+0x57
C  [pdalcpp.dll+0x34c7da]  pdal::Stage::execute+0x69a
C  [pdalcpp.dll+0x34d378]  pdal::Stage::execute+0x578

Stepping through, its seems [PoissonRecon.h Line 498](https://github.com/PDAL/PDAL/blob/58b41990bada8d9f2f84c010e87299e087f9bb56/vendor/kazhdan/PoissonRecon.h#L498) breaks the m_tree object.

**System/installation information:**
pdal 2.0.1

**Comment by abellgithub** [comment]
Please provide the pipeline & PDAL command you're using or the code that invokes filter.

**Comment by bgutz001** [comment]
I couldn't reproduce the error with a pipeline, but I am using the cpp API
Here is a barebones example where the error occurs

```
#include <string>
#include <pdal/Options.hpp>
#include <pdal/PointTable.hpp>
#include <pdal/io/EptReader.hpp>
#include <pdal/filters/PoissonFilter.hpp>

void run() {
	pdal::PointTable table;

	pdal::Options readerOpts;
	readerOpts.add("filename", "C:/testdata/ept/ept.json");
	readerOpts.add("resolution", 10);
	pdal::EptReader readerStage;
	readerStage.setOptions(readerOpts);

	pdal::PoissonFilter poissonStage;
	pdal::Options poissonOpts;
	poissonStage.setOptions(poissonOpts);
	poissonStage.setInput(readerStage);

	poissonStage.prepare(table);
	poissonStage.execute(table);
}

int main() {
	run();
	run();
}
```

**Comment by abellgithub** [comment]
Thanks.  I'll take a look at this.

**Comment by abellgithub** [comment]
I've verified this.  I don't see anything obvious in our code.  I suspect an initialization issue with the vendor code that does the actual triangulation.
