### ISSUE TITLE
Improve handling of synthetic points

### ISSUE THREAD

**Issue by chambbj** [PDAL/PDAL#2876]
I've started a branch https://github.com/PDAL/PDAL/tree/synthetic-handling that aims to improve handling of synthetic points within PDAL.

The first baby step it takes is to test the parsing of the synthetic bit when reading/writing LAS. The tests are far from exhaustive, and should probably also give similar attention to keypoint and withheld bits as well.

Second, it implements a method to segment an incoming PointView into Kept/Ignored PointViews (perhaps these should instead be named Real/Synthetic for clarity and to not be too presumptuous). This segmentation is exercised in SMRFilter to optionally passthrough synthetic points without them having any bearing on the ground extraction.

The multiple SMRF options for ignoring DimRanges, returns by ReturnNumber/NumberOfReturns, and now synthetic bit makes the code a bit of a hot mess, and it still feels like a general purpose, filter-level solution would make this cleaner, especially if we want to implement similar for other filters. Perhaps priority can be given to #2638, with the additional requirement that the WHERE syntax be able to support the synthetic (and other) bits.

Thoughts?

**Comment by abellgithub** [comment]
ClassLabel::Synthetic = 32;

**Comment by chambbj** [comment]
For synthetic `CreatedNeverClassified` perhaps, but what about all the other classes that could also be synthetic?

**Comment by abellgithub** [comment]
It's just a name to use in place of (1 << 5)
