### ISSUE TITLE
Unable to get RGB value from pcd

### ISSUE THREAD

**Issue by Deer-1170** [PDAL/PDAL#2880]
Hi,

Can anyone please help me.

Does changing the file format from pcd to las or csv also rgb value cannot be obtained.

using version pdal 2.0.1.

Any help will be greatly appreciated.

Thanks

**Comment by abellgithub** [comment]
It's unclear what you're doing.  You'll have to provide a file/command/pipeline in order for others to help you.

**Comment by Deer-1170** [comment]
When you convert a file from pcd to las or csv, you get only x, y, z, but the original pcd file contains fields such as (x, y, z, RGB values). Why are RGB values lost?

The command used was ↓
  pdal translate input.pcd output.csv

original file in text
![image](https://user-images.githubusercontent.com/52154444/72946200-9bcb5d00-3dc1-11ea-8946-2bbb1f78377b.png)

file converted in csv
![image](https://user-images.githubusercontent.com/52154444/72946161-6fafdc00-3dc1-11ea-86f9-4fbf97849e5f.png)

**Comment by abellgithub** [comment]
Your input appears to be invalid.  The strings that you've provided for rgb as floating point are generally outside the valid range of floating point values.

In the future, please don't paste pictures into the ticket.  Instead, provide a file containing the actual data.  Thanks.

**Comment by abellgithub** [comment]
I've opened a ticket (#2882) to make this more clear to users.

**Comment by Deer-1170** [comment]
Be careful from next.
And thanks for the hints on the problem.
I'll try it.

**Comment by zoeeer** [comment]
I think the rgb field in pcd cannot be interpreted as a floating number (although the header defines it as F).

The 4 bytes Float number 7.7520167e-39 (as posted by @Deer-1170 ) in binary is: 0x78 0x69 0x54 0x00 (LSB -> MSB), which is reasonable RGB data 0x546978 or [84, 105, 120]. (I'm not 100% sure about the order of the channels, but we get the idea.)

![image](https://github.com/user-attachments/assets/4dcbf3e9-4bb3-45ff-8688-53e3d8b03f8b)

Can we support the parsing of rgb field for pcd files?
