### ISSUE TITLE
filters.cluster does not work in docker container

### ISSUE THREAD

**Issue by vsantalov** [PDAL/PDAL#2885]
When using pdal from a docker container filters.cluster fails to generate dimension "ClusterID". Filter works as expected when PDAL is installed with Anaconda.
Tested with latest image based on f364adf commit.
I made sure output supports additional fields.

**Comment by abellgithub** [comment]
This has nothing to do with docker.  You appear to be using different versions of PDAL.  A recent change omitted the registration of the ClusterID dimension.  I've fixed this in #2887
