### ISSUE TITLE
PDAL `validate` changes stage metadata

### ISSUE THREAD

**Issue by normanb** [PDAL/PDAL#2891]
In the process of debugging https://github.com/PDAL/PDAL/pull/2838 we found that the stage metadata is changed when using Python and calling the `validate` function. e.g.

```
pipeline = pdal.Pipeline(req)
pipeline.validate()
pipeline.execute()
```

The stage metadata becomes `[]` after `validate` is called.

**Comment by jomey** [comment]
Issue #2437 sounds potentially related.

**Comment by abellgithub** [comment]
Is this still an issue? If so, can you provide specific input that gets removed/eliminated?
