### ISSUE TITLE
filters.crop does not work with 3D bounds

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#2904]
``filters.crop`` currently [downcasts bounds](https://github.com/PDAL/PDAL/blob/master/filters/CropFilter.cpp#L124) to 2d for cropping. We should be able to support 3D box clipping with ``filters.crop``

NOTE: Spherical cropping, where the user inputs a point and a radius, does work in 3D.

**Comment by abellgithub** [comment]
I wouldn't consider this a bug.

Is the suggestion that we support 3D surfaces, or just rectangular solids?

**Comment by pdal-docs** [comment]
My bug is your feature. 

I was proposing only supporting rectangular boxes. No polyhedrals.

**Comment by hobu** [comment]
Done in #2929
