### ISSUE TITLE
Support direct access to XYZ dimensions

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#2906]
PDAL currently copies to return coordinates, but in combination with #2902, direct access to the special XYZ dimensions could be provided for read/write access. This should significantly speed up some operations that heavily use them.

The plan will be to roll out direct access APIs in 2.1 and then backfill support for their usage in 2.2.

**Comment by hobu** [comment]
Done in #2932

**Comment by abellgithub** [comment]
This has not yet been done.
