### ISSUE TITLE
ELM does not check for an empty PointView and can hang

### ISSUE THREAD

**Issue by chambbj** [PDAL/PDAL#2921]
As originally reported in https://github.com/PDAL/python/issues/48...

filters.elm hangs infinitely when passed a header-only .las.

It's possible that some other functions could hang as well, but I noticed it with filters.elm.

To recreate this, create a text file with ending .xyz (file ending probably not relevant) with content:

`X,Y,Z,scan_angle\n`

Where there's a newline \n / enter after the header.

Then use the following code to convert it to .las and then try to pass it through filter.elm.

```
import pdal
import json

inputfile = "yourpathto\\haltinput.xyz"
outputfile = "yourpathto\\haltoutput.las"

xyztolas = \
{
  "pipeline": [
    {
      "type": "readers.text",
      "filename": "yourpathto\\haltinput.xyz",
    },
    {
      "type": "writers.las",
      "filename": "yourpathto\\haltinput.las"
    }
  ]
}

# tree extraction
haltdict = \
{
  "pipeline": [
    {
      "type": "readers.las",
      "filename": "yourpathto\\haltinput.las"
    },
    {
      "type": "filters.elm",
    },
    {
      "type": "writers.las",
      "filename": "yourpathto\\haltoutput.las"
    }
  ]
}

somepipeline = json.dumps(xyztolas)

pipeline = pdal.Pipeline(somepipeline)
pipeline.validate()
count = pipeline.execute()

somepipeline = json.dumps(haltdict)

pipeline = pdal.Pipeline(somepipeline)
pipeline.validate()
count = pipeline.execute() # enters infinite loop
```

**Comment by abellgithub** [comment]
Simplified test case:

test.json:

[
  {
    "type":"filters.elm"
  }
]

pdal pipeline test.json

-- 
Andrew Bell
andrew.bell.ia@gmail.com

**Comment by chambbj** [comment]
Exactly, this has nothing to do with Python. I've fixed this and am looking for other possible offenders.
