### ISSUE TITLE
Can't read polygon from entwine

### ISSUE THREAD

**Issue by gui2dev** [PDAL/PDAL#2935]
Hi there,

When trying to use the `polygon` option from `readers.ept` I get the following error :

```
$ pdal pipeline pipeline.json
PDAL: Geometry::transform() failed.  NULL source SRS.
```

<details>
  
```
[
   {
      "type": "readers.ept",
      "filename": "http://gdevaltametris.blob.core.windows.net/livraison/RER_D/entwine/ept.json",
      "polygon": "POLYGON((659001.410 6849073.820,659010.800 6849072.180,659015.600 6849078.130,659019.470 6849080.570,659018.670 6849082.910,659016.440 6849085.100,659011.110 6849084.730,659010.020 6849081.240,659010.240 6849079.600,659012.570 6849075.840,659007.020 6849077.980,659007.530 6849076.720,659007.090 6849076.080,659007.120 6849075.240,659001.410 6849073.820))"
   },
   "coupe.las"
]
```

</details>

One would expect to get a clean exit and a nicely populated ouput.

**System/installation information:**

```
$ uname -a
Linux DESKTOP-N8C3JIA 4.4.0-18362-Microsoft #476-Microsoft Fri Nov 01 16:53:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ pdal --version
pdal 2.0.0 (git-version: 5c2dab)
```

**Comment by hobu** [comment]
Please try master. A number of issues related to this have been fixed there.

**Comment by gui2dev** [comment]
Same thing with
```
pdal 2.1.0 (git-version: b40acc)
```

**Comment by hobu** [comment]
you can assign an SRS for the poly like:

```
"polygon":"POLYGON((num num)) / EPSG:4326"
```

This should get you over the immediate error. Does your EPT not have an SRS?

**Comment by gui2dev** [comment]
Thanks @hobu , adding the right SRS fixed it.

I would suggest that is the optionnal polygon does not have a SRS, it should get the EPT one by default.

**Comment by hobu** [comment]
> I would suggest that is the optionnal polygon does not have a SRS, it should get the EPT one by default.

I thought it is supposed to be doing that

**Comment by gui2dev** [comment]
> I thought it is supposed to be doing that

Something's wrong then.
