### ISSUE TITLE
E57 plugin doesn't support relative filepaths.

### ISSUE THREAD

**Issue by sheikware** [PDAL/PDAL#2936]
When creating a pipeline to read a local file, the full filepath is required. This is not required for other readers.

This pipeline does not work:

test_pipeline = {
    "pipeline": [
        {
            'type': 'readers.e57',
            'filename': 'site.e57'
        },
        {
            'type': 'writers.las',
            'filename': 'outputfile.las'
        }
    ]
}

Error: RuntimeError: readers.e57: Invalid root path

This pipeline does work:

test_pipeline = {
    "pipeline": [
        {
            'type': 'readers.e57',
            'filename': '/mnt/data/e57/site.e57'
        },
        {
            'type': 'writers.las',
            'filename': 'outputfile.las'
        }
    ]
}

This pipeline also works

test_pipeline_laz = {
    "pipeline": [
        {
            'type': 'readers.las',
            'filename': 'site.laz'
        },
        {
            'type': 'writers.las',
            'filename': 'outputfile.las'
        }
    ]
}

Issue is in the vendor package Arbiter. Not sure why it was necessary to use that package (main benefit is for remote resources, but I don't think other readers support remote resources). Fix would either require changes to that package, or to follow what other readers do in only using local resources.

**Comment by abellgithub** [comment]
I can't recreate this using the following pipeline:

```
[
    {
        "type":"readers.e57",
        "filename":"./A4.e57"
    },
    "./out.las"
]
```

It looks like you are using a python interface.  Have you tried using PDAL directly from the command line?  What is your PDAL version/platform?

**Comment by hobu** [comment]
Repopen if there is any more information.

**Comment by MenschMitHut** [comment]
I have the same problem when using the python interface. I have to specify the full path for `.e57` files.
When I use relative paths I get this error `RuntimeError: readers.e57: Invalid root path`

This only applies to e57 files and via the python interface. The `.laz`  files work without a problem.

Files which are not on the root drive (C: (Sorry windows user 😀)) do not work, even with absolute paths. For other file types or via the cli there is no issue

**Comment by abellgithub** [comment]
Have you tried the command-line interface? If so, can you post a pipeline?

**Comment by MenschMitHut** [comment]
## Relative path issue

### Python absolute path e57

```python
json = """
[
    "C:/Files/test.e57"
]
"""

import pdal

pipeline = pdal.Pipeline(json)
count = pipeline.execute()
arrays = pipeline.arrays
metadata = pipeline.metadata
log = pipeline.log
```

✔️ This does work

### CLI absolute path

`pdal info C:/Files/test.e57`

✔️ This does work

### Python relative path e57

```python
json = """
[
    "./test.e57"
]
"""

import pdal

pipeline = pdal.Pipeline(json)
count = pipeline.execute()
arrays = pipeline.arrays
metadata = pipeline.metadata
log = pipeline.log
```

❌ This does not work

### Python relative path laz
```python
json = """
[
    "./autzen.laz"
]
"""

import pdal

pipeline = pdal.Pipeline(json)
count = pipeline.execute()
arrays = pipeline.arrays
metadata = pipeline.metadata
log = pipeline.log
```

✔️ This does work

### CLI relative path

`pdal info ./test.e57`

✔️ This does work

## Path separator issue

There also seems an issue with windows paths. But only for e57 files

### cli e57

`pdal info ./test.e57`

✔️ This does work

`pdal info .\test.e57`

❌ This does not work

### cli laz

`pdal info ./autzen.laz`

✔️ This does work

`pdal info .\autzen.laz`

✔️ This does work

**Comment by MenschMitHut** [comment]
e57 files on different drives (e.g F:\) do work. So my statement before was false. Maybe I tried it with windows path separators...
