### ISSUE TITLE
Broken references in documentation

### ISSUE THREAD

**Issue by jrobichaud** [PDAL/PDAL#2949]
**Describe the bug**

When building the documentation there are warnings about filters not being in any toctree and missing files (undefined label). I think this should be fixed.

```bash
sphinx-build doc doc/build/html -b html
```

```bash
reading sources... [100%] stages/filters
~/git/PDAL/doc/stages/filters.rst:376: WARNING: toctree contains reference to nonexisting document 'stages/filters.gridprojection'
~/git/PDAL/doc/stages/filters.rst:376: WARNING: toctree contains reference to nonexisting document 'stages/filters.movingleastsquares'
~/git/PDAL/doc/stages/filters.rst:426: WARNING: toctree contains reference to nonexisting document 'stages/filters.voxelgrid'
looking for now-outdated files... none found
pickling environment... done
checking consistency... ~/git/PDAL/doc/stages/filters.shell.rst: WARNING: document isn't included in any toctree
~/git/PDAL/doc/stages/readers.hdf.rst: WARNING: document isn't included in any toctree
~/git/PDAL/doc/stages/writers.fbx.rst: WARNING: document isn't included in any toctree
~/git/PDAL/doc/workshop/qgis.rst: WARNING: document isn't included in any toctree
done
preparing documents... done
writing output... [100%] stages/filters
~/git/PDAL/doc/stages/filters.rst:394: WARNING: undefined label: filters.gridprojection (if the link has no caption the label must precede a section header)
~/git/PDAL/doc/stages/filters.rst:397: WARNING: undefined label: filters.movingleastsquares (if the link has no caption the label must precede a section header)
~/git/PDAL/doc/stages/filters.rst:439: WARNING: undefined label: filters.voxelgrid (if the link has no caption the label must precede a section header)
```

**Expected behavior**

Unincluded filters to be present there:
![image](https://user-images.githubusercontent.com/12142702/75549279-46f0b700-59fd-11ea-96a3-ba1114677fa5.png) 

or deleted if the code no longer exist.

Missing files should be recovered or references to the files removed.

**System/installation information:**

Latest documentation on https://pdal.io/index.html and the master branch

**Notes**
Some of them can be found using the search:
https://pdal.io/stages/filters.shell.html?highlight=filters%20shell 
https://pdal.io/stages/writers.fbx.html?highlight=writers%20fbx
https://pdal.io/workshop/qgis.html?highlight=qgis

But not hdf:
https://pdal.io/search.html?q=hdf&check_keywords=yes&area=default

**Comment by hobu** [comment]
The latest docs in master are not pushed to the pdal.io website until they are in the corresponding ``2.x-maintenance`` branch. The CI does build the docs with every pull request and puts a temporary version of them on S3 for you to look at and test rendered output. Rummage around the "docs" builder type when you make a doc pull request to see. This should help us clean up warnings and missing items like this.

As for ``filters.shell`` it was our agreement to never document it or highlight its usage 😄 so as to not encourage people to use it. That said, if you're using PDAL pipeline as your workflow engine, it is quite useful.

**Comment by jrobichaud** [comment]
I've been using pdal for a little while and knowing the filters.shell existed would have been useful. Maybe add a sub section "advanced filters" for power users?

I believe it is possible to configure sphinx to treat warnings as errors and I think it could be a good step for the CI to run. `rst` files are so easily broken. What do you think? Could that be a good pull request or it is something you do not need in your workflow?

**Comment by hobu** [comment]
A bunch of sphinx warnings aren't configurable, so -Wall can be kind of annoying. Now that we have a doc builder in the CI, it would be reasonable to turn that on, however.
