### ISSUE TITLE
writers.gltf uses incorrect file extension

### ISSUE THREAD

**Issue by jedfrechette** [PDAL/PDAL#2968]
writers.gltf outputs binary glTF files but uses the extension .gltf. According to the glTF docs:

https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#file-extension

the extension should be .glb. The files currently produced by PDAL fail to validate at:

https://github.khronos.org/glTF-Validator/

and in my limited testing the only application that was able to open them was Blender. Changing the file extension to .glb allows them to pass validation and the other applications I've tested are able to open them without issues.

**Comment by jedfrechette** [comment]
Other writers don't seem to sanity check file extensions either, so, to maintain consistency, perhaps just updating the docs to indicate that the binary variant is written and using the correct extension in the example is enough?

**Comment by hobu** [comment]
We should update the docs and maybe update the StageExtensions map to use glb instead of gltf for auto-selection of the driver.

**Comment by abellgithub** [comment]
PDAL uses whatever filename you choose.  I'll make a mod to the docs and add ".glb" to the extension list for the GLTF writer.

**Comment by jedfrechette** [comment]
> ... and add ".glb" to the extension list for the GLTF writer.

Since PDAL writes .glb files not .gltf files shouldn't 'glb' replace 'gltf' in the extension list?

**Comment by hobu** [comment]
Some people (me) were using the gltf extension. It only effects being able to do `pdal translate in.las out.gltf` at the moment without having to specify `--writer`.

**Comment by jedfrechette** [comment]
What software are those files going in to? Mostly, I'm just curious how widespread support for mixing formats like that is in the wild?

**Comment by abellgithub** [comment]
I don't think we're mixing anything.  We write binary glTF.  You can use whatever name you like for the file.  The extension support simply says that if you don't specify a writer in a pipeline, but use just a filename, we'll assume that you want to use the glTF writer if the filename has either the extension ".gltf" or ".glb".  I have no idea what software supports ingest of these files, though IMO, any software that would be reading these files should be able to determine whether the file is binary or not regardless of the filename.

**Comment by jedfrechette** [comment]
> IMO, any software that would be reading these files should be able to determine whether the file is binary or not regardless of the filename.

Maybe I'm being pedantic, but that's not what the format's specification or the associated validator say. According to them, .gltf files written by PDAL are invalid.

Now whether or not PDAL should enforce how users name their files is another question, that I personally don't have a strong opinion on as long as the behavior is documented. In general though I think following available specifications as closely as possible is a good thing, especially when they come with a validator to reduce this type of ambiguity as much as possible.

This is the first time I've run across software writing glb files as .gltf so I don't have a sense of how common support for that practice is, hence my question to @hobu about where the files were going.

**Comment by abellgithub** [comment]
We don't choose the filenames.  You do.  I guess you should name them with a .glb extension if you care about the validator (my experience with that validator isn't good).  I have fixed the documentation to say that we write binary glTF.  Hopefully that eliminates confusion.

I'm not sure what else you're asking for.

**Comment by jedfrechette** [comment]
I'm not necessarily asking for any other changes. I just find it odd that
the example given by @hobo allows the user to implicitly request a .gltf
file, but then gives them something else.

--
Jed Frechette

**Comment by hobu** [comment]
> the example given by @Hobo allows the user to implicitly request a .gltf file, but then gives them something else.

PDAL doesn't enforce formats-by-extension conventions. It provides some conveniences (like `pdal translate` trying to open a .las file when it sees it with the appropriate reader), but users can do what they want.
