### ISSUE TITLE
`pdal` missing from Alpine

### ISSUE THREAD

**Issue by tyrcog** [PDAL/PDAL#2970]
**Describe the bug**
In the PDAL [documentation](https://pdal.io/download.html#alpine), it describes that `pdal` is available as an Alpine package, however I'm no longer able to find this package (or `pdal-dev`) at  https://pkgs.alpinelinux.org/packages?name=*pdal*&branch=edge

Perhaps there was an error in packaging? I see a very recent update to `py3-pdal`, but it does not list a `pdal` dependency, which seems incorrect?

**Expected behavior**
This install worked until very recently.
```
apk --no-cache add \
    --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing \
    --repository=http://dl-cdn.alpinelinux.org/alpine/edge/main \
    --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community \
    pdal \
    pdal-dev
```

**System/installation information:**
Here is a condensed version of the Dockerfile I'm using.
```
FROM python:3.8.1-alpine
RUN apk update && \
    apk --no-cache add build-base
RUN apk --no-cache add \
    --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing \
    --repository=http://dl-cdn.alpinelinux.org/alpine/edge/main \
    --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community \
    pdal \
    pdal-dev
```

**Comment by abellgithub** [comment]
It seems that the Alpine packaging people dropped it at some point.  Not sure why.  I'll try to get the next version in the repo if the packagers don't give me too much grief, as they sometimes do.

**Comment by tyrcog** [comment]
Thanks @abellgithub, do you have a rough timeframe? Anything I can do to help? I have a project that depends on `pdal` and I'm hunting for a work around.

**Comment by hobu** [comment]
[hobu.co](https://hobu.co) is available for contract if you need to accelerate your timeline and need support. Otherwise, this task will be completed as priorities allow.

**Comment by tyrcog** [comment]
I also noticed [this change](https://github.com/PDAL/PDAL/commit/a1883d8e46576d2d824d4b2e9baedd864c8d8760#diff-2f5a091e699bc9d34772e36a7ae1dbcdR11) to use https://mirror.clarkson.edu/. Not sure if it is related.

**Comment by abellgithub** [comment]
PDAL is easy to build with docker in Alpine by pulling from github and building with cmake.  You really only need GDAL as a dependency and it's there.  You should take a look at our CI script for how to do it:

https://github.com/PDAL/PDAL/blob/master/scripts/docker/alpine/Dockerfile.dependencies
https://github.com/PDAL/PDAL/blob/master/scripts/docker/alpine/Dockerfile.master

You probably don't need to fetch all the dependencies that we do for CI.

**Comment by tyrcog** [comment]
Thank you @hobu and @abellgithub for the pointers!

**Comment by mmacata** [comment]
Hi, I hope this is not outdated but I did run into the same problem end of February. At this time, it was due to a failing test that the package was removed, I guess. I created a repo which builds the alpine PDAL package without the test as a quickfix: https://github.com/mmacata/alpine-pdal/blob/master/APKBUILD#L46 and uploaded the packages as release: https://github.com/mmacata/alpine-pdal/releases.


Due to dependency mismatch with another software we use, we ended up compiling it ourselves: https://github.com/mundialis/docker-pdal/blob/master/Dockerfile
Hope, this helps someone, although it is not the final solution and will not be updated.

**Comment by abellgithub** [comment]
We build on Alpine regularly, so I'm not sure what the issue would have been.  I'd be interested in seeing the actual test failure.  Seems odd that the Alpine maintainers didn't contact us before removing the package so that we could have fixed the failure.

**Comment by neteler** [comment]
FYI:

PDAL-2.1.0 is back with date "2020-08-17", in "testing":

https://pkgs.alpinelinux.org/packages?name=*pdal*&branch=edge
