### ISSUE TITLE
filters.transformation does not default to`dataformat_id` to 3 in final output las

### ISSUE THREAD

**Issue by jomey** [PDAL/PDAL#2982]
**Description**
`filters.transformation` does not preserve all point information (colors and timestamp).

*Pipeline*
```
[
    "/Path/To/Moving_point_cloud.laz",
    {
        "type": "filters.transformation",
        "matrix": "0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0"
    },
    {
        "type": "writers.las",
        "compression": "laszip",
        "forward": "all",
        "filename": "/Path/To/Moved_point_cloud.laz"
    }
]
```

Explicitly setting the `dataformat_id` addresses this issue.

```
[
    "/Path/To/Moving_point_cloud.laz",
    {
        "type": "filters.transformation",
        "matrix": "0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0"
    },
    {
        "type": "writers.las",
        "compression": "laszip",
        "dataformat_id": 3,
        "forward": "all",
        "filename": "/Path/To/Moved_point_cloud.laz"
    }
]
```
**Expected behavior**
The documentation of [writers.las](https://pdal.io/stages/writers.las.html) states that `dataformat_id` of `3` is the default value and maintains the information of color and timestamp.

**System/installation information:**
```
$ pdal --version
----------------------------------------------------------------------------------------------------------------------
pdal 2.1.0 (git-version: c4cc22)
----------------------------------------------------------------------------------------------------------------------

```

**Comment by abellgithub** [comment]
I'm guessing your input data wasn't data format 3.  When you specify "forward": "all", it does what you say.

**Comment by abellgithub** [comment]
I don't understand.  The pipeline you provided in this ticket shows that you're forwarding all header values from the input.  So if your input data format is 0, your output data format will also be 0 unless you override it, which is what you did in your second example.

**Comment by jomey** [comment]
Pardon the confusion.

To step back and highlight the steps I made to get to this assumption of a bug:
1. Align a subset two clouds with filters.icp
2. Take the result of filters.icp and apply transformation to the complete cloud
3. Compare metadata of the output cloud produced by the ICP versus the transformation filter

`aligned_icp.laz`
```
{
  "file_size": 219600749,
  "filename": "aligned_icp.laz",
  "metadata":
  {
    "comp_spatialreference": "...",
    "compressed": true,
    "count": 35052384,
    "creation_doy": 75,
    "creation_year": 2020,
    "dataformat_id": 3,
```

`aligned_transformation.laz`
```
{
  "file_size": 219425883,
  "filename": "aligned_transformation.laz",
  "metadata":
  {
    "comp_spatialreference": "...",
    "compressed": true,
    "count": 35052384,
    "creation_doy": 48,
    "creation_year": 2020,
    "dataformat_id": 0,
```

Notice the difference in file size and data format. Both times the input file was:
```
{
  "file_size": 219425625,
  "filename": "moving.laz",
  "metadata":
  {
    "comp_spatialreference": "...",
    "compressed": true,
    "count": 35052384,
    "creation_doy": 48,
    "creation_year": 2020,
    "dataformat_id": 0,
```

Is the identical header all down to forwarding "all"?

**Comment by jomey** [comment]
I think I understand the behavior now. Closing this and Thank you for the help.

**Comment by abellgithub** [comment]
Filters won't modify the data format ID.  If you don't specify any options, output LAS/LAZ files will have a dataformat ID of 3.  If you specify the `dataformat_id` in the pipeline, the output dataformat will be what you have specified with that option.  If you set `forward` to `all`, the output file will have the dataformat ID of the input file UNLESS you have explicitly set it by using the `dataformat_id` option.

Hope that helps.
