### ISSUE TITLE
Segfault in Poisson Filter

### ISSUE THREAD

**Issue by jtfell** [PDAL/PDAL#2990]
When running `filters.poisson` on a specific `.laz` file (which can be run through other filters without issue), PDAL is reporting a segfault. This is possibly related to #2873 

```
$ pdal translate test.laz -o out.gltf poisson --filters.poisson.depth=2
```

The `.laz` file in question is available [here](https://github.com/jtfell/PDAL/blob/e1220e2b86655ecf1fd7d07432b9309724468e07/test.laz)

**Expected behavior**

No segfault, GLTF output as normal

**System/installation information:**

```
Linux server.example.com 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux
```

```
pdal 2.1.0 (git-version: 99a88e)
```

**Comment by abellgithub** [comment]
This is interesting and a good catch.  Thanks for the report.  Fix coming shortly.
