### ISSUE TITLE
Problems with inputs in pipeline

### ISSUE THREAD

**Issue by gmaillet** [PDAL/PDAL#3002]
I'm trying to export, for example, one raster per class. To do this, I use different range filters in a pipeline associated with different gdal.writer using tags and inputs, but only the first image is actually created (with the pdal pipeline command line or in a python script).

Is this a bug or did I miss something?

<details>
```
[
    {
        "tag": "in",
        "type": "readers.ept",
        "bounds": "([-10425171.940, -10423171.940], [5164494.710, 5166494.710])",
        "filename": "https://s3-us-west-2.amazonaws.com/usgs-lidar-public/IA_FullState"
     },
    {
        "tag": "c1",
        "inputs": ["in"],
        "type": "filters.range",
        "limits":"Classification[1:1]"
    },
    {
        "inputs": ["c1"],
        "type":"writers.gdal",
        "filename":"c1.tif",
        "dimension":"Classification",
        "data_type":"uint8_t",
        "output_type":"mean",
        "resolution": 5
    },
    {
        "tag": "c7",
        "inputs": [ "in" ],
        "type":"filters.range",
        "limits":"Classification[7:7]"
    },
    {
        "inputs": ["c7"],
        "type":"writers.gdal",
        "filename":"c7.tif",
        "dimension":"Classification",
        "data_type":"uint8_t",
        "output_type":"mean",
        "resolution": 5
    }
]
```
</details>

with :  pdal 2.0.1 (git-version: Release) installed with conda
on : Darwin Kernel Version 17.7.0

**Comment by abellgithub** [comment]
Unfortunately, PDAL supports only a single terminal writer.  However, in this case you can use the capability of the GDAL writer to create two outputs at once.  I think something like this would work for what you're trying to do:

```
[
    {
        "tag": "in",
        "type": "readers.ept",
        "bounds": "([-10425171.940, -10423171.940], [5164494.710, 5166494.710])",
        "filename": "https://s3-us-west-2.amazonaws.com/usgs-lidar-public/IA_FullState"
     },
    {
        "type":"filters.range",
        "limits":"Classification[1:1], Classification[7:7]"
    },
    {
        "type":"filters.groupby",
        "dimension":"Classification"
    },
    {
        "type":"writers.gdal",
        "filename":"class#.tif",
        "dimension":"Classification",
        "data_type":"uint8_t",
        "output_type":"mean",
        "resolution": 5
    }
]

Hope that helps

**Comment by gmaillet** [comment]
Thank you very much, your solution seems good for me. 
But I'm a little surprised, because I used to export several images in a pipeline (for example the DTM + the classification, or the DTM before and after a ground filter) and it always works, except when I try to use different inputs.

**Comment by abellgithub** [comment]
Without seeing the pipelines in question I really can't answer. Sorry.
