### ISSUE TITLE
Add collar clipping to writers.gdal

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#3004]
For DEM/DTM generation scenarios, it is common to compute over a larger footprint than desired and then clip to remove edge effects. ``writers.gdal`` currently has the ``bounds`` argument to control the extent of the file, and this corresponds to the final extent of the raster. It would be very useful to add a ``collar`` argument that adjusts the final output to the extent defined by the ``bounds`` minus (or plus) the ``collar`` expressed in X/Y units. 

I could be convinced to call this ``buffer`` too, but that word is so overloaded as to not have much meaning.

**Comment by Jean-Roc** [comment]
Hi @hobu, did you close this issue as a "wontfix" or were you able to get this behaviour in another way ?

**Comment by abellgithub** [comment]
This can be achieved by setting the origin in writers.gdal.

**Comment by Jean-Roc** [comment]
as I see it, the difference is that you have to define it for each file while a "collar":"-20" equal to "buffer":"20" of tile/splitters would be easier to use

**Comment by abellgithub** [comment]
It could be done.  It's not trivial.

**Comment by adamsteer** [comment]
from my view (gluing stuff together with bash or python) it seems far more painless to pass a slightly larger-than-needed boundary to PDAL for `writers.gdal`, then pass the resulting raster output to `gdal_translate` with the desired output boundary...
