### ISSUE TITLE
Wrong constant type in member function causes VS 2017 warning

### ISSUE THREAD

**Issue by cgodkin** [PDAL/PDAL#3008]
**Describe the bug**

Under VS 2017, PointTable.hpp contains a reset() function that assigns `int` 0 to `vector<char>` which causes a [Visual Studio C4244 warning](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-levels-3-and-4-c4244?view=vs-2017).
```
    virtual void reset()
        { std::fill(m_buf.begin(), m_buf.end(), 0); }
```
Since m_buf is vector<char>, this is assigning an int to a char.  Easy to fix with this
```
    virtual void reset()
        { std::fill(m_buf.begin(), m_buf.end(), '\0'); }
```
**Expected behavior**

No warning.

**System/installation information:**

Microsoft Visual Studio 2017 with -W4 

PR to follow.

**Comment by abellgithub** [comment]
This is a silly warning. 0 is 0. There is no ambiguity. No other compiler warns about this and in my opinion, the change makes the code less clear.

**Comment by cgodkin** [comment]
Okay.  0 is not 0 in this context since an int is 4 bytes long but a char is 1 byte.  

I have had similar fixes rejected on other open source projects in the past as well so I'll just wrap my PDAL includes with #pragma push(disable: 4244)/#pragma pop statements.  Thanks for looking at it.

**Comment by abellgithub** [comment]
On Mon, Mar 30, 2020, 21:29 cgodkin <notifications@github.com> wrote:

> Okay. 0 is not 0 in this context since an int is 4 bytes long but a char
> is 1 byte.
>
It's a well-defined assignment. Using 0 rather than a character
representation helps to make clear that this is an array of bytes, rather
than characters in a string.
