### ISSUE TITLE
Unable to read some nitf wrapped las files

### ISSUE THREAD

**Issue by msmitherdc** [PDAL/PDAL#3010]
pdal --version
pdal 2.1.0 (git-version: 828987)

pdal --drivers | grep nitf
readers.nitf                 NITF Reader
writers.nitf                 NITF Writer

```
pdal info --metadata --boundary /test/pointcloud/fixtures/synth_points.ntf
PDAL: readers.nitf: wrong file_signature. not a LAS/LAZ file.
```
nitf file: https://github.com/CRREL/GRiD/blob/releases/v1.4.8.2/apps/pointcloud/fixtures/synth_points.ntf

Readable with 2.0

**Comment by abellgithub** [comment]
Fixed by #3017
