### ISSUE TITLE
Matlab filter plugin

### ISSUE THREAD

**Issue by OgreTransporter** [PDAL/PDAL#3013]
**Environment:**
- Windows 10
- Visual Studio 2017, 2019
- PDAL commit f4a651c

**Bug**

The line
https://github.com/PDAL/PDAL/blob/f4a651c24fbc7c6a43d97f877cb4b83145c49387/plugins/matlab/filters/MatlabFilter.cpp#L54
must be replaced by
```
CREATE_SHARED_STAGE(MatlabFilter, s_info)
```
Furthermore, the line
https://github.com/PDAL/PDAL/blob/f4a651c24fbc7c6a43d97f877cb4b83145c49387/plugins/matlab/filters/MatlabFilter.hpp#L42
must be deleted from the file plugins/matlab/filters/MatlabFilter.hpp.

**Comment by OgreTransporter** [comment]
See #3012 for error message:

>       "D:\dev\workspace\test3\build\INSTALL.vcxproj" (Standardziel) (1) ->
>       "D:\dev\workspace\test3\build\ALL_BUILD.vcxproj" (Standardziel) (3) ->
>       "D:\dev\workspace\test3\build\plugins\matlab\libpdal_plugin_filter_matlab.vcxproj" (Standardziel) (9) ->
>         d:\dev\workspace\test3\src\plugins\matlab\filters\MatlabFilter.hpp(42): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "json/json.h": No such file or directory (Quelldatei wird kompiliert D:\dev\workspace\test3\src\plugins\matlab\filters\MatlabFilter.cpp) [D:\dev\workspace\test3\build\plugins\matlab\libpdal_plugin_filter_matlab.vcxproj]

**Comment by abellgithub** [comment]
Fixed in #3024
