### ISSUE TITLE
[Feature Request] Allow spaces between key-value pairs when parsing the command line

### ISSUE THREAD

**Issue by hawkaa** [PDAL/PDAL#3016]
Hi there,

Thanks for PDAL! We use it a lot in my company.

I must apologize as this is an odd feature request. It is not a big deal, but it could be a low hanging fruit.

Most command line tools allow for spaces between the key value pairs, like this `--readers.las.filename input.laz`. PDAL requires a `=` between the key value pairs like this: `--readers.las.filename=input.laz`.

The benefit of allowing for spaces is auto completion in the command line. My file gets long and it would be neat to be able to press tab to get some help filling in the file names.

Let me know what you guys think!

**Comment by abellgithub** [comment]
Fixed by #3037
