### ISSUE TITLE
Fails to build with GCC-10

### ISSUE THREAD

**Issue by sebastic** [PDAL/PDAL#3031]
As reported by Matthias Klose in [Debian Bug #957668](https://bugs.debian.org/957668):
> The package fails to build in a test rebuild on at least amd64 with
> gcc-10/g++-10, but succeeds to build with gcc-9/g++-9. The
> severity of this report will be raised before the bullseye release,
> so nothing has to be done for the buster release.
> 
> The full build log can be found at:
> http://people.debian.org/~doko/logs/gcc10-20200225/pdal_2.0.1+ds-1_unstable_gcc10.log
> The last lines of the build log are at the end of this report.
> 
> To build with GCC 10, either set CC=gcc-10 CXX=g++-10 explicitly,
> or install the gcc, g++, gfortran, ... packages from experimental.
> ```
>   apt-get -t=experimental install g++ 
> ```
> Common build failures are new warnings resulting in build failures with
> -Werror turned on, or new/dropped symbols in Debian symbols files.
> For other C/C++ related build failures see the porting guide at
> http://gcc.gnu.org/gcc-10/porting_to.html
> ```
> [...]
> /<<PKGBUILDDIR>>/plugins/python/plang/Redirector.cpp:118:1: warning: missing initializer for member ‘_typeobject::tp_print’ [-Wmissing-field-initializers]
> /<<PKGBUILDDIR>>/plugins/python/plang/Redirector.cpp:172:6: error: no declaration matches ‘void pdal::plang::Redirector::set_stdout(std::ostream*)’
>   172 | void Redirector::set_stdout(std::ostream* ostr)
>       |      ^~~~~~~~~~
> In file included from /<<PKGBUILDDIR>>/plugins/python/plang/Redirector.cpp:9:
> /<<PKGBUILDDIR>>/plugins/python/plang/Redirector.hpp:44:10: note: candidates are: ‘void pdal::plang::Redirector::set_stdout(pdal::plang::Redirector::stdout_write_type, pdal::plang::Redirector::stdout_flush_type)’
>    44 |     void set_stdout(stdout_write_type write, stdout_flush_type flush);
>       |          ^~~~~~~~~~
> /<<PKGBUILDDIR>>/plugins/python/plang/Redirector.hpp:37:10: note:                 ‘void pdal::plang::Redirector::set_stdout(int*)’
>    37 |     void set_stdout(std::ostream* ostr);
>       |          ^~~~~~~~~~
> /<<PKGBUILDDIR>>/plugins/python/plang/Redirector.hpp:30:7: note: ‘class pdal::plang::Redirector’ defined here
>    30 | class Redirector
>       |       ^~~~~~~~~~
> make[4]: *** [plugins/python/io/CMakeFiles/pdal_plugin_reader_numpy.dir/build.make:92: plugins/python/io/CMakeFiles/pdal_plugin_reader_numpy.dir/__/plang/Redirector.cpp.o] Error 1
> make[4]: *** Waiting for unfinished jobs....
> [ 49%] Building CXX object plugins/python/filters/CMakeFiles/pdal_plugin_filter_python.dir/__/plang/Redirector.cpp.o
> cd /<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/plugins/python/filters && /usr/bin/c++  -DPDAL_DLL_EXPORT -DPDAL_PYTHON_LIBRARY=\"/usr/lib/x86_64-linux-gnu/libpython3.8.so\" -DUNIX -Dpdal_plugin_filter_python_EXPORTS -I/<<PKGBUILDDIR>>/vendor/gtest/include -I/<<PKGBUILDDIR>>/vendor/gtest -I/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/include -I/<<PKGBUILDDIR>> -I/<<PKGBUILDDIR>>/vendor/nlohmann -I/usr/include/geotiff -I/usr/include/gdal -isystem /usr/include/python3.8 -isystem /usr/lib/python3/dist-packages/numpy/core/include  -g -O2 -fdebug-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wdate-time -D_FORTIFY_SOURCE=2 -O2 -g -DNDEBUG -fPIC   -Wno-implicit-fallthrough -Wno-int-in-bool-context -Wno-dangling-else -Wno-noexcept-type -Wall -Wextra -Wpointer-arith -Wcast-align -Wcast-qual -Wno-error=parentheses -Wno-error=cast-qual -Wredundant-decls -Wno-unused-parameter -Wno-unused-variable -Wno-long-long -Wno-unknown-pragmas -Wno-deprecated-declarations -std=gnu++11 -o CMakeFiles/pdal_plugin_filter_python.dir/__/plang/Redirector.cpp.o -c /<<PKGBUILDDIR>>/plugins/python/plang/Redirector.cpp
> In file included from /<<PKGBUILDDIR>>/plugins/python/plang/Redirector.cpp:9:
> /<<PKGBUILDDIR>>/plugins/python/plang/Redirector.hpp:37:26: error: ‘std::ostream’ has not been declared
>    37 |     void set_stdout(std::ostream* ostr);
>       |                          ^~~~~~~
> /<<PKGBUILDDIR>>/plugins/python/plang/Redirector.hpp:40:37: error: ‘string’ is not a member of ‘std’
>    40 |     typedef std::function<void(std::string)> stdout_write_type;
>       |                                     ^~~~~~
> /<<PKGBUILDDIR>>/plugins/python/plang/Redirector.hpp:18:1: note: ‘std::string’ is defined in header ‘<string>’; did you forget to ‘#include <string>’?
>    17 | #include <Python.h>
>   +++ |+#include <string>
>    18 | 
> /<<PKGBUILDDIR>>/plugins/python/plang/Redirector.hpp:40:44: error: template argument 1 is invalid
>    40 |     typedef std::function<void(std::string)> stdout_write_type;
>       |                                            ^
> [ 49%] Building CXX object plugins/python/filters/CMakeFiles/pdal_plugin_filter_python.dir/__/plang/Script.cpp.o
> cd /<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/plugins/python/filters && /usr/bin/c++  -DPDAL_DLL_EXPORT -DPDAL_PYTHON_LIBRARY=\"/usr/lib/x86_64-linux-gnu/libpython3.8.so\" -DUNIX -Dpdal_plugin_filter_python_EXPORTS -I/<<PKGBUILDDIR>>/vendor/gtest/include -I/<<PKGBUILDDIR>>/vendor/gtest -I/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/include -I/<<PKGBUILDDIR>> -I/<<PKGBUILDDIR>>/vendor/nlohmann -I/usr/include/geotiff -I/usr/include/gdal -isystem /usr/include/python3.8 -isystem /usr/lib/python3/dist-packages/numpy/core/include  -g -O2 -fdebug-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wdate-time -D_FORTIFY_SOURCE=2 -O2 -g -DNDEBUG -fPIC   -Wno-implicit-fallthrough -Wno-int-in-bool-context -Wno-dangling-else -Wno-noexcept-type -Wall -Wextra -Wpointer-arith -Wcast-align -Wcast-qual -Wno-error=parentheses -Wno-error=cast-qual -Wredundant-decls -Wno-unused-parameter -Wno-unused-variable -Wno-long-long -Wno-unknown-pragmas -Wno-deprecated-declarations -std=gnu++11 -o CMakeFiles/pdal_plugin_filter_python.dir/__/plang/Script.cpp.o -c /<<PKGBUILDDIR>>/plugins/python/plang/Script.cpp
> /<<PKGBUILDDIR>>/plugins/python/plang/Redirector.cpp: In function ‘PyObject* pdal::plang::Stdout_write(PyObject*, PyObject*)’:
> /<<PKGBUILDDIR>>/plugins/python/plang/Redirector.cpp:42:28: error: expression cannot be used as a function
>    42 |         selfimpl->write(str);
>       |                            ^
> /<<PKGBUILDDIR>>/plugins/python/plang/Redirector.cpp: At global scope:
> /<<PKGBUILDDIR>>/plugins/python/plang/Redirector.cpp:118:1: warning: missing initializer for member ‘_typeobject::tp_vectorcall’ [-Wmissing-field-initializers]
>   118 | };
>       | ^
> /<<PKGBUILDDIR>>/plugins/python/plang/Redirector.cpp:118:1: warning: missing initializer for member ‘_typeobject::tp_print’ [-Wmissing-field-initializers]
> /<<PKGBUILDDIR>>/plugins/python/plang/Redirector.cpp:172:6: error: no declaration matches ‘void pdal::plang::Redirector::set_stdout(std::ostream*)’
>   172 | void Redirector::set_stdout(std::ostream* ostr)
>       |      ^~~~~~~~~~
> In file included from /<<PKGBUILDDIR>>/plugins/python/plang/Redirector.cpp:9:
> /<<PKGBUILDDIR>>/plugins/python/plang/Redirector.hpp:44:10: note: candidates are: ‘void pdal::plang::Redirector::set_stdout(pdal::plang::Redirector::stdout_write_type, pdal::plang::Redirector::stdout_flush_type)’
>    44 |     void set_stdout(stdout_write_type write, stdout_flush_type flush);
>       |          ^~~~~~~~~~
> /<<PKGBUILDDIR>>/plugins/python/plang/Redirector.hpp:37:10: note:                 ‘void pdal::plang::Redirector::set_stdout(int*)’
>    37 |     void set_stdout(std::ostream* ostr);
>       |          ^~~~~~~~~~
> /<<PKGBUILDDIR>>/plugins/python/plang/Redirector.hpp:30:7: note: ‘class pdal::plang::Redirector’ defined here
>    30 | class Redirector
>       |       ^~~~~~~~~~
> make[4]: *** [plugins/python/filters/CMakeFiles/pdal_plugin_filter_python.dir/build.make:92: plugins/python/filters/CMakeFiles/pdal_plugin_filter_python.dir/__/plang/Redirector.cpp.o] Error 1
> make[4]: *** Waiting for unfinished jobs....
> make[4]: Leaving directory '/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu'
> make[3]: *** [CMakeFiles/Makefile2:974: plugins/python/filters/CMakeFiles/pdal_plugin_filter_python.dir/all] Error 2
> make[4]: Leaving directory '/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu'
> make[3]: *** [CMakeFiles/Makefile2:1033: plugins/python/io/CMakeFiles/pdal_plugin_reader_numpy.dir/all] Error 2
> make[3]: Leaving directory '/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu'
> make[2]: *** [Makefile:166: all] Error 2
> make[2]: Leaving directory '/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu'
> dh_auto_build: error: cd obj-x86_64-linux-gnu && make -j4 returned exit code 2
> make[1]: *** [debian/rules:39: override_dh_auto_build] Error 25
> make[1]: Leaving directory '/<<PKGBUILDDIR>>'
> make: *** [debian/rules:21: build] Error 2
> dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
> ```

**Comment by abellgithub** [comment]
GCC 10?

https://gcc.gnu.org/releases.html

**Comment by sebastic** [comment]
Yes, while not released yet snapshots from trunk are available in Debian:

 https://tracker.debian.org/pkg/gcc-10

>    * GCC snapshot, taken from the trunk (20200411, f883c46b487).

Also in Fedora (32 and later):

 https://apps.fedoraproject.org/packages/gcc

Which also pulls from the upstream trunk.

**Comment by hobu** [comment]
Can they please try with PDAL 2.1? The Python stuff has been removed for PDAL 2.1.

**Comment by sebastic** [comment]
Confirmed fixed in 2.1.0, it built successfully with gcc from Debian experimental.
