### ISSUE TITLE
Conversion from pcd bin to las

### ISSUE THREAD

**Issue by ChaturvediShilpa** [PDAL/PDAL#3034]
Hi, 

I am trying to convert a pcd.bin file to las using translate command but getting error "PDAL: Unable to fetch data and convert as requested: Intensity:float(-2.13603) -> unsigned short "

Please help. 

Thanks,

**Comment by abellgithub** [comment]
Your input contains a negative value for intensity that you're trying to
store in an unsigned value. Usually intensity values are non-negative.

**Comment by ChaturvediShilpa** [comment]
Thank you for the prompt reply. 
Is there any way to directly convert pcd bin to laz format ? Currently I am trying to use translate command. Is there any better way for conversion ? 

I will be your grateful.

**Comment by ChaturvediShilpa** [comment]
Hi team,

Your codebase for pcd reder shows support for pcd binary format. Is there any options to pass from command line to detect binary format or it reads that from header. 
I am passing pcd.bin files with no header and hence getting error message for parsing ?

Plese suggest.

**Comment by abellgithub** [comment]
Binary input is detected automatically.

**Comment by abellgithub** [comment]
You'll have to add a header to the file to make it valid.

**Comment by ChaturvediShilpa** [comment]
Thanks for the reply. I want to know what is difference between binary pcd and binary compressed pcd. 

Any reason why binary compressed reader is not supported in the current release ?

**Comment by abellgithub** [comment]
I have never heard of compressed PCD.  Can you point me to information?

**Comment by ChaturvediShilpa** [comment]
Hi, 

Earlier I believe there is only pcd ascii and pcd binary as mentioned on this pcd format page link. 

There is reference of binary compressed pcd dataset in [PDAL library](https://github.com/PDAL/PDAL/blob/58e7c35ee74723424c1e5edfc3b9adc60911a907/io/PcdReader.cpp) and [PCL library](https://github.com/PointCloudLibrary/pcl/blob/619948b6c3cbcb99ea0e64aa1c46f1c2462d8f46/io/tools/converter.cpp). Also the [Apollo autonomous vehicle dataset](http://apolloscape.auto/tracking.html) provides there lidar data in pcd binary compressed format. 

Are binary and binary compressed similar or how they differ ?
Please help.

**Comment by abellgithub** [comment]
I didn't know there was compressed binary, but it doesn't appear too complicated.  PDAL obviously doesn't support it.  You may be able to use a PCL utility to translate compressed PCD to uncompressed PCD.

I don't think we have any plan of implementing this.  If you'd like to do the work I could integrate it. We could also do it under contract.

**Comment by ChaturvediShilpa** [comment]
Thanks for the prompt reply. 

Does laszip or pdal truncates precision ? I converted a pcd file to laz and then back to pcd. I see the values are rounded off to say two digits after decimal. 

Is this the reason for better compression in laz format ? Is the rounding off done in PDAL transformation ?

Thanks,
Shilpa Chaturvedi

**Comment by abellgithub** [comment]
If you're writing LAS, you need to specify the scaling that you want.  See the `scale_x`... [here](https://pdal.io/stages/writers.las.html)

**Comment by ChaturvediShilpa** [comment]
Thanks for the reply. 

Is there a way I can specify the transformation to be lossless i.e without any loss of precision ? Also how can I specify the scale x value in the command pdal translate ?

**Comment by hobu** [comment]
The link above explains it. https://pdal.io/workshop/exercises/translation/reprojection.html might also be informative

**Comment by ChaturvediShilpa** [comment]
Hi, 

When I give a scale_x value as 0.0000001 to avoid precision loss, I am getting this error .
"Unable to convert scaled value (-3.123731852e+10) to int32 for dimension 'X' when writing LAS/LAZ file"

Please let me know how can I avoid precision loss of data while converting from pcd to laz format using pdal translate command. As I know laszip is lossless so the conversion process is where precision loss is happening I guess. 

Thanks

**Comment by abellgithub** [comment]
See item 3 in the [FAQ](https://pdal.io/faq.htm)
