### ISSUE TITLE
Problem with numpy reader

### ISSUE THREAD

**Issue by ChaturvediShilpa** [PDAL/PDAL#3035]
Hi, 

I am trying to use Numpy reader to read lidar data stored in numpy array. The reader is mapping the fields wrongly. For example my data is having 4 columns (x,y,z,intensity)  but reader is mapping them to fields as (x,y,intensity).

Please help and suggest

**Comment by abellgithub** [comment]
You'll have to provide your input command/pipeline for us to look at this.
