### ISSUE TITLE
PDAL_BUILD_VERSION not in X.Y.Z format (breaks package upgrade)

### ISSUE THREAD

**Issue by sebastic** [PDAL/PDAL#3039]
PDAL 2.0.1 used:
```cmake
set(PDAL_API_VERSION "9")
set(PDAL_BUILD_VERSION "10")
```
This results in:
```
-rw-r--r-- root/root   6694296 2019-09-04 08:38 ./usr/lib/libpdal_base.so.10
lrwxrwxrwx root/root         0 2019-09-04 08:38 ./usr/lib/libpdal_base.so.9 -> libpdal_base.so.10
lrwxrwxrwx root/root         0 2019-09-04 08:38 ./usr/lib/libpdal_base.so -> libpdal_base.so.9
```

PDAL 2.1.0 uses:
```cmake
set(PDAL_API_VERSION "10")
set(PDAL_BUILD_VERSION "11")
```
Which results in:
```
-rw-r--r-- root/root   7038392 2020-04-21 21:44 ./usr/lib/libpdal_base.so.11
lrwxrwxrwx root/root         0 2020-04-21 21:44 ./usr/lib/libpdal_base.so.10 -> libpdal_base.so.11
lrwxrwxrwx root/root         0 2020-04-21 21:44 ./usr/lib/libpdal_base.so -> libpdal_base.so.10
```

This breaks the Debian package upgrade because libpdal-base9 (2.0.1+ds-1) contains `libpdal_base.so.10` as a real file, which is also in libpdal-base10 (2.1.0+ds-1) as a symlink.

Why is `PDAL_BUILD_VERSION` no longer a version number?

Using a typical version number format would prevent this issue, like PROJ does for example:
```cmake
set(PROJ_API_VERSION "19")
set(PROJ_BUILD_VERSION "19.0.0")
```

**Comment by hobu** [comment]
> Why is PDAL_BUILD_VERSION no longer a version number?

It was a regression. Addressed in #3042 and will be fixed in the next PDAL 2.1.1 release.
