### ISSUE TITLE
pdal tile couldn't open file for output

### ISSUE THREAD

**Issue by balazsdukai** [PDAL/PDAL#3041]
**Describe the bug**
I'm running `pdal tile` on a set of LAZ files. The LAZ files are rectangular and large, about 5x6 km, and several of them have parts without points.

```
$ pdal \
--verbose 2 \
tile \
--input "*.LAZ" \
--output "<path>/a_#.laz" \
--length 200;
```

After running for a while and producing some tiles, it errors with:

```
PDAL: writers.las: Couldn't open file '<path>/a_68_22.laz' for output.

LazPerfVlrCompressor destroyed without a call to done() <repeated many many times>
```
The file `<path>/a_68_22.laz` is not created.

**Expected behavior**
To produce the tiles

**System/installation information:**

```
$ uname -a
```
Linux godzilla 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

```
$ pdal --version
```
pdal 2.1.0 (git-version: d48e25)

**Comment by abellgithub** [comment]
I would guess that you're running out of file descriptors.  `pdal tile` holds the output files open while processing.  Have you checked `ulimit -n`?

**Comment by balazsdukai** [comment]
Yes indeed, that was the cause.

**Comment by jerstlouis** [comment]
For very large dataset, it is not practical to keep all output tiles open. Should a separate issue be opened to implement a maximum number of open files?

**Comment by hobu** [comment]
> Should a separate issue be opened to implement a maximum number of open files?

Yes, if you want to address this with a patch, please open a pull request with your implementation.

**Comment by danielrode** [comment]
Workaround on Linux (tested on Fedora 40):
```
ulimit -n 99999
pdal tile --buffer 40 --input "./my_collection/*.las" --output "./buffered_collection/tile_#.las"
```

A descriptor limit of 99999 might not be sufficient depending on how large your collection is, but it was sufficient for mine.  You can find out what your machine's max (hard) limit is by running `ulimit -n` (without a number argument).
