### ISSUE TITLE
pdal tile memory footprint

### ISSUE THREAD

**Issue by balazsdukai** [PDAL/PDAL#3048]
**Describe the bug**
I'm running `pdal tile` on a set of LAZ files. The LAZ files are rectangular and large, about 5x6 km. The total size of LAZ to split in tiles is about 200GB (in one area). I have several of such areas. The memory use of `pdal tile` for a single area of ~200GB LAZ files, ~170k tiles creeps up over 40GB (resident size), and increasing. Is this what can be expected?

I didn't get to observe the upper limit of the memory creep since I assumed a lower memory footprint and I started several `pdal tile` processes simultaneously, but each of them got killed by the OS after two days of processing as it ran out of ram. 

```
$ pdal \
      --verbose 2 \
      tile \
      --readers.las.override_srs="EPSG:7415" \
      --writers.las.a_srs="EPSG:7415" \
      --input "*.LAZ" \
      --output "<path>/ahn3_#.laz" \
      --origin_x 13565 \
      --origin_y 306846 \
      --length 200;
```

**Expected behavior**
Since the documentation says that `pdal tile` streams the points to limit the memory use, I expected a much lower memory footprint, in the magnitude of couple of GBs at maximum.

**System/installation information:**

```
$ uname -a
```
Linux godzilla 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

RAM 126GB physical + 32GB swap

```
$ pdal --version
```
pdal 2.1.0 (git-version: d48e25)

**Comment by abellgithub** [comment]
This isn't a bug.  If you're interested in investigating memory usage, you're welcome to do so.

Note that `pdal tile` allocates space for 10,000 points regardless of need and RSS measures all process memory use, not just that allocated by the application at run-time.

**Comment by balazsdukai** [comment]
Yes, I think I understand that `pdal tile` allocates memory for 10,000 points for an output tile, and I assumed that it de-allocates that memory once the output tile is written to disk.

However, what I meant to describe above is that `pdal tile` does not free up memory during the process. At least that is what its memory consumption/footprint indicates, see the graph below.

I ran `pdal tile` again with the same command above for about 8 hours and logged its memory use:

![image](https://user-images.githubusercontent.com/7190603/80450699-671bf400-8922-11ea-8368-00aa17ec3a69.png)

**Comment by abellgithub** [comment]
Yeah, `pdal tile` isn't written to create 170,000 tiles.  Sorry.
