### ISSUE TITLE
Pipeline execution fails using docker image - no error message

### ISSUE THREAD

**Issue by JmeCS** [PDAL/PDAL#3058]
**Bug**
Executing the following pipeline fails inside of the `pdal/pdal` docker container (version 2.1, hosted on dockerhub). There is no error message other than "killed" being printed to the console after several minutes of computation. The same pipeline executes on my machine outside of the container (MacBook Pro, 32GB ram) with no issues. I've increased the memory of the running container incrementally all the way up to 30GB so it does not appear to be a memory overhead problem. 

This is part of a cloud-based data pipeline, so executing this as part of an application inside of a container is critical. 

```
$ pdal pipeline config.json
```

Contents of `config.json`:
 
```
{
    "pipeline": [
        "./data/2020_01_24_175745_180640_epsg3424.LAS",
        {
            "type": "filters.elm"
        },
        {
            "type": "filters.outlier"
        },
        {
            "type": "filters.smrf"
        },
        {
            "filename": "./data/2020_01_24_175745_180640_epsg3424_classified.las",
            "type": "writers.las"
        }
    ]
}
```

The file being classified, `2020_01_24_175745_180640_epsg3424.LAS`, is large - 1.8GB, so my initial instinct was that it was a memory issue.  

**Expected behavior**
Pipeline execution completes without error, and `2020_01_24_175745_180640_epsg3424_classified.las` is written to disk. 

**System/installation information:**
```
$ pdal --version
pdal 2.1.0 (git-version: 554898)
```

**Comment by hobu** [comment]
> This is part of a cloud-based data pipeline, so executing this as part of an application inside of a container is critical.

Here are your options as I see them:

* Post the data here so we can maybe replicate the issue if we have time
* Build your own container and run in debug mode to provide a stack trace in hopes we see something significant in the trace.
* Hire us to work the bug

**Comment by JmeCS** [comment]
@hobu Thanks for the reply. Would you be ok with me reaching out directly, e.g. to your email listed on your github profile? I'm unable to post the data here due to confidentiality restrictions. This is pretty mission critical for us so we'd potentially be open to hiring your team to assist with debugging.

**Comment by abellgithub** [comment]
Does it work with other files?  Smaller files? What does memory use look like when you run locally?  I'd lay money that it's a memory problem, though that seems like a lot of memory to burn through.

**Comment by abellgithub** [comment]
What is the point type of your LAS file?

**Comment by hobu** [comment]
> Would you be ok with me reaching out directly, e.g. to your email listed on your github profile?

Yes, it is no problem to email directly.

**Comment by JmeCS** [comment]
OK false alarm folks my apologies. It turns out issuing a memory size argument, e.g. `-m 16g` to a `docker run` command does not override the memory allocated via the docker app on my machine (which was set to 4GB). Increasing the memory via an `-m` flag works fine on a VM, so problem has been resolved.
