### ISSUE TITLE
Pdal pipeline pgpointcloud plugins do not work in docker image 2.1 while they work in 2.0. 

### ISSUE THREAD

**Issue by dvanderleij** [PDAL/PDAL#3059]
**Describe the bug**
pgpointcloud plugins do not work in 2.1 docker image. I test it with exactly the same input on 2.0 and it works. The documentation mentions that the docker version contains the plugin.
The following is error is given on 2.1 
```
STDIN: Couldn't create reader stage of type 'readers.pgpointcloud'.You probably have a version of PDAL that didn't come with a pluginyou're trying to load.  Please see the FAQ at https://pdal.io/faq
```
I insert the pipeline with the standard in flag as follows
```
$ pdal pipeline -s
```

<details>
  
```
{
    "pipeline": [
        {
            "type": "readers.pgpointcloud",
            "connection": "dbname=mydbname user=myuser password=mypass hostaddr=myip port=myport",
            "table": "mytablename"
        },
        {
            "type": "writers.las",
            "filename": "mypath/test_1.laz",
            "compression": "true"
        }
    ]
}
```

</details>

**Expected behavior**
Run the pipeline successfully like on 2.0

**System/installation information:**

```
$Linux my-hostname 5.4.0-29-generic #33-Ubuntu SMP Wed Apr 29 14:32:27 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ pdal 2.1.0 (git-version: 554898)
```

**Comment by abellgithub** [comment]
I forgot to push a fix to the 2.1 branch.  You should be able to get things working by setting the following environment variables in your docker container:

ENV GDAL_DATA=/usr/share/gdal
ENV PDAL_DRIVER_PATH=/usr/lib
ENV PROJ_LIB=/usr/share/proj

**Comment by abellgithub** [comment]
A working image for 2.1 should build whenever docker hub gets around to it ;)

**Comment by dvanderleij** [comment]
Great! thanks for the quick response.
