### ISSUE TITLE
A possible PDAL 2.1.0 EPTReader / Delaunay regression

### ISSUE THREAD

**Issue by pomadchin** [PDAL/PDAL#3076]
**Describe the bug**

I tried to upgrade PDAL from 2.0.1 to 2.1.0 and noticed a possible regression in PDAL EPTReader / Delaunay filter.

In all pipelines I'm using the [red-rocks dataset from the entwine README.md](https://github.com/connormanning/entwine#usage).

```
# the command to run
$ time pdal translate pipeline test.json
```

`test.json` contents:
  
```
{
    "pipeline" : [
        {
            "filename" : "path/to/red-rocks",
            "bounds" : "([481968.0, 4390186.0], [482856.0, 4391074.0])",
            "resolution" : 0.216796875,
            "type" : "readers.ept"
        },
        {
            "type" : "filters.delaunay"
        }
    ]
}
```

**Expected behavior**
Execute the command.

Running the same with PDAL 2.0.1 CLI would produce the following result:

```bash
$ pdal --version
# pdal 2.0.1 (git-version: Release)
$ time pdal pipeline test.json

# real	0m9.007s
# user	0m12.173s
# sys	0m0.544s
```

**The current behavior:**

#### Linux

Hangs.

I noticed that this pipeline would work without the `filters.delaunay` step; `test_nd.json` contents:

```json
{
    "pipeline" : [
        {
            "filename" : "path/to/red-rocks",
            "bounds" : "([481968.0, 4390186.0], [482856.0, 4391074.0])",
            "resolution" : 0.216796875,
            "type" : "readers.ept"
        }
    ]
}
```

```bash
$ pdal --version
# pdal 2.1.0 (git-version: Release)
$ time pdal pipeline test_nd.json

# real	0m4.849s
# user	0m9.675s
# sys	0m0.352s
```

It would work with `pdal:2.1.0` Docker image as well though it would take more than a minute to execute it:

```bash
$ pdal --version
# pdal 2.1.0 (git-version: bd6beb)
$ time pdal pipeline test_nd.json

# real	0m50.849s
# user	1m17.058s
# sys	0m0.299s
```

#### MacOS
It _would work with no regressions_ on MacOS Catalina with PDAL installed via brew:

```bash
$ uname -a
# Darwin macbook.local 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64
$ pdal --version 
# pdal 2.1.0 (git-version: Release)
$ time pdal pipeline test.json
# pdal pipeline test.json  9.80s user 0.54s system 147% cpu 7.030 total
```

**System/installation information:**

* uname -a: `Linux e433f4ca4502 4.14.173-137.229.amzn2.x86_64 #1 SMP Wed Apr 1 18:06:08 UTC 2020 x86_64 GNU/Linux` (to prepare this issue I used an EC2 machine with installed docker)
* I used a debian based docker: [Dockerfile](https://github.com/PDAL/java/blob/master/scripts/docker/2.0.0/debian/Dockerfile); it is published as `daunnc/pdal-debian:2.1.0`
  * PDAL Version: `pdal 2.1.0 (git-version: Release)`
* I also tried the official `pdal:2.1.0` image:
  * PDAL Version: `pdal 2.1.0 (git-version: bd6beb)`

**Comment by abellgithub** [comment]
I'm having no problem with the current master branch and this pipeline on OSX:
```
{
    "pipeline" : [
        {
            "filename" : "https://na-c.entwine.io/red-rocks/ept.json",
            "bounds" : "([481968.0, 4390186.0], [482856.0, 4391074.0])",
            "resolution" : 0.216796875,
            "type" : "readers.ept"
        },
        {
            "type" : "filters.delaunay"
        },
        {
            "type": "writers.ply",
            "filename": "rr.ply",
            "faces": true
        }
    ]
}
```

**Comment by pomadchin** [comment]
@abellgithub thanks for checking that! I can confirm that I had problems only with prebuilt debian package and with the `pdal/pdal:2.1.0` image on EMR.

**Comment by abellgithub** [comment]
This is a problem in libstd++.  It has to do with the way data is being cached in a comparator passed to std::sort in the delaunay code.  I'm going to submit a bug report on gcc and fix the delaunator code the avoid the issue.

Thanks for finding.  This was interesting.
