### ISSUE TITLE
gdal.writer not using bounds as given

### ISSUE THREAD

**Issue by jomey** [PDAL/PDAL#3078]
Not sure if this is an GDAL or PDAL issue, but starting here and let me know if that needs to be reported on the GDAL end.

**Description**
Using the gdal.writer to create a GeoTiff adds one more pixel to the max-x and max-y than given with the 'bounds' option in the pipeline. I used the following pipeline and then looked at the bounds via `gdalinfo`.
This happens consistently with different laz source files. Below a sample output for one laz file.

_Pipeline_:
```JSON
{
    "pipeline": [
        {
            "type": "readers.las"
        },
        {
            "type": "writers.gdal",
            "gdaldriver": "GTiff",
            "data_type": "float32",
            "output_type": "count,idw",
            "bounds": "([322521.0, 336549.0], [4305591.0, 4322442.0])",
            "resolution": 3.0
        }
    ]
}
```

_GDAL output_  
```
...
Corner Coordinates:
Upper Left  (  322521.000, 4322445.000) (107d 3' 1.69"W, 39d 1'58.99"N)
Lower Left  (  322521.000, 4305591.000) (107d 2'45.95"W, 38d52'52.58"N)
Upper Right (  336552.000, 4322445.000) (106d53'18.42"W, 39d 2' 8.84"N)
Lower Right (  336552.000, 4305591.000) (106d53' 3.93"W, 38d53' 2.38"N)
Center      (  329536.500, 4314018.000) (106d58' 2.49"W, 38d57'30.80"N)
...
```

_Source file_
```
$ pdal info
...
  "file_size": 2713027378,
  "filename": "scratch/ERW_20180524/Lidar/ERW_20180524_merge.laz",
  "now": "2020-05-19T09:17:42-0600",
  "pdal_version": "2.1.0 (git-version: 46c336)",
  "reader": "readers.las",
  "summary":
  {
    "bounds":
    {
      "maxx": 336546.72,
      "maxy": 4322441.47,
      "maxz": 4116.53,
      "minx": 322522.95,
      "miny": 4305592.34,
      "minz": 2602.35
    },
...
```

**Expected behavior**
Bounds as given with the option in the pipeline.

**System/installation information:**
```
Linux 3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ pdal --version
--------------------------------
pdal 2.1.0 (git-version: 46c336)
--------------------------------
```

```
$ gdalinfo --version
GDAL 3.0.4, released 2020/01/28
```

**Comment by abellgithub** [comment]
The bounds you provide PDAL are inclusive (thus the [] syntax).  If it's easier, you can specify an origin and width/height.

**Comment by jomey** [comment]
So should the correct bounds be:
```
"bounds" : "([322521.0, 336549.0), [4305591.0, 4322442.0))"
```

**Comment by abellgithub** [comment]
Sure?  The bounds are allowable values for points.  It's kind of up to you.

Thinking in one dimension...  If your input is 0, .5, 1, 1.5, 2, then you need 3 cells with origin 0 of width 1 in order to handle data, as the value "2" belongs in the 3rd cell, rather than the second.  PDAL will make a sufficient number of cells to hold all potential data as you've described with `bounds`.

**Comment by jomey** [comment]
I understand your example.

I was mainly surprised to see the extra cell as it feels different then doing a target window with GDAL. The command I use there for instance is:
```
gdalwarp -te 322521 4305591 336549 4322442
```
and that does produces this output:
```
Corner Coordinates:
Upper Left  (  322521.000, 4322442.000) (107d 3' 1.69"W, 39d 1'58.89"N)
Lower Left  (  322521.000, 4305591.000) (107d 2'45.95"W, 38d52'52.58"N)
Upper Right (  336549.000, 4322442.000) (106d53'18.54"W, 39d 2' 8.74"N)
Lower Right (  336549.000, 4305591.000) (106d53' 4.05"W, 38d53' 2.38"N)
```

**Comment by jomey** [comment]
Noting that the upper bounds example won't work.

Error message:
```
PDAL: No closing ']' in range.
```

**Comment by abellgithub** [comment]
Sorry, I missed your example.

Here's the GDAL calculation:
```
nPixels = (int) ((dfMaxX - dfMinX + (dfXRes/2.0)) / dfXRes);
```

It rounds by adding half a cell.  With a cell size of one In the X dimension If your bounds were [0, 1.4] you'd get 1 cell, with [0, 1.5], you'd get two.  I don't know the thinking behind the GDAL way.

**Comment by jomey** [comment]
For my specific example, I would be nice to somehow get to the bounding box as given.

Could the `)` be supported for the bounds, so I don't have to specify a `.9999` value?
