### ISSUE TITLE
Groupby not accepting signed integers

### ISSUE THREAD

**Issue by tomvantilburg** [PDAL/PDAL#3079]
Not sure if this is an issue or not, but I have difficulty working around the following situation:
```
{
        "type":"filters.dbscan",
        "min_points":10,
        "eps":1.2,
        "dimensions":"X,Y,Z"
    },{
        "type":"filters.groupby",
        "dimension":"ClusterID"
    }
```
The output of dbscan is signed because of the unclassified points receiving a -1
Groupby does not accept this and errs out with
`PDAL: Unable to fetch data and convert as requested: ClusterID:int64_t(-1) -> unsigned long`

The use case is that I do another iteration in the pipeline where I want the unclustered points to be considered as well. Currently I can circumvent this by assigning a very high integer to ClusterID=-1 but this doesn't feel like the right way.
Would it make sense to have groupby accept signed longints?

**Comment by abellgithub** [comment]
Can you please post the entire pipeline?

**Comment by tomvantilburg** [comment]
On @abellgithub 's request, the full pipeline:
```
{
    "pipeline":[{   
        "type": "readers.las",
        "filename": "test.las"
      },{
        "type": "filters.range",
        "limits": "Classification[6:6],NumberOfReturns[1:10]"
      },{
          "type":"filters.crop",
          "polygon": "%s"
      },{
        "type": "filters.sample",
        "radius": 0.25
      },{
        "type": "filters.normal",
        "knn": 8
      },
      {
        "type": "filters.range",
        "limits": "NormalZ[0.2:1]"
    },{
        "type":"filters.dbscan",
        "min_points":10,
        "eps":1.2,
        "dimensions":"X,Y,Z"
    },{
        "type":"filters.range",
        "limits":"ClusterID[0:]"
    },{
        "type":"filters.assign",
        "assignment" : "ClusterID[-1:-1]=99"
    },{
        "type":"filters.ferry",
        "dimensions":"ClusterID => XYZCID"
    },{
        "type":"filters.groupby",
        "dimension":"XYZCID"
    },{
        "type":"filters.dbscan",
        "min_points":8,
        "eps":0.02,
        "dimensions":"NormalX,NormalY" 
    },{
        "type":"filters.range",
        "limits":"ClusterID[0:]"
    },{
        "type":"filters.assign",
        "assignment" : "ClusterID[-1:-1]=99"
    },{
        "type":"filters.merge"
    },{
       
        "type":"filters.outlier",
        "method":"statistical",
        "mean_k":8,
        "multiplier":1.1
    }]
}
```

**Comment by abellgithub** [comment]
@chambbj : Do you have any thoughts on this?

**Comment by chambbj** [comment]
My initial thought is that the negative values used as flags internally were probably based off the paper or another codebase. That said, I see the value in having this behave more like `filters.cluster` in which class 0 is the noise. I'll take a closer look today to confirm these thoughts and can look at making a change to `filters.dbscan` if we are on the same page.

**Comment by chambbj** [comment]
Ah yes, it is somewhat commonplace for DBSCAN to spit out a -1 for noise, at least in Open3D and scikit-learn. Open3D is where I lifted the bulk of our implementation from, so no wonder we have inherited it. That said, I'm still not completely opposed to shifting all cluster labels emitted from DBSCAN up one value and having it behave more like `filters.cluster`. We can simply state in the docs that the noise cluster is 0.

**Comment by abellgithub** [comment]
Is there any downside to changing the type interpreted by `filters.cluster` to signed?  I find it hard to believe that losing that bit is going to be a problem.

**Comment by chambbj** [comment]
We could do this, along with an update to groupby, if you'd rather.

**Comment by tomvantilburg** [comment]
I didn't consider you might change the output of dbscan since it would be a breaking change and indeed unconformant to the existing implementations. Having a groupby on negative numbers seems more straightforward to me and perhaps even useful for edge cases where you group on things like aspect or re-classed but negative Z values.
