### ISSUE TITLE
Issue in Finding the Boundary Exercise

### ISSUE THREAD

**Issue by kcpelletier** [PDAL/PDAL#3082]
The output boundary file using tindex in the Finding the Boundary exercise from the PDAL workshop is rotated when opened in QGIS 3.10.3-A Coruña. North is up in the screenshot below. I checked the uncompahgre.laz file in QT Modeler and it was oriented correctly. I was using PDAL from the CMD.exe Prompt (0.0.1) in Anaconda Navigator 1.9.12.

![image](https://user-images.githubusercontent.com/65681155/82488918-63edd100-9aa6-11ea-91ff-10db3011ee28.png)

Thanks!

**Comment by hobu** [comment]
This is a result of the axis-ordering -aware changes to GDAL 3.0.x. If you add `--t_srs EPSG:26913` to the command in the workshop for `pdal tindex create`, you'll get the correct orientation. 

This is related to the change added in https://github.com/PDAL/PDAL/issues/2804
