### ISSUE TITLE
Las 1.4 readers.las -> writers.las corrupts Classification

### ISSUE THREAD

**Issue by jrobichaud** [PDAL/PDAL#3092]
As requested by @abellgithub this is a simpler way to reproduce #3091 with a single point and a single pipeline.

**Describe the bug**

Download this point cloud: 

https://github.com/jrobichaud/pdal-las-bug/blob/master/output/bug_single_point/text_to_las.las

It has a single point to 0,0,0 with classification 71.

pipeline.json:
```json
{
  "pipeline": [
    {
      "type": "readers.las",
      "filename": "text_to_las.las"
    },
    {
      "type": "writers.las",
      "minor_version": "4",
      "extra_dims": "all",
      "compression": "laszip",
      "filename": "las_to_las.las"
    }
  ]
}
```

For the bug to happen it requires `"minor_version": "4"` and `"compression": "laszip"`.

```bash
$ pdal pipeline pipeline.json
```

Then if you run:
`pdal translate text_to_las.las text_to_las_translated_to_txt.txt`
`pdal translate las_to_las.las las_to_las_translated_to_txt.txt`
`diff text_to_las_translated_to_txt.txt las_to_las_translated_to_txt.txt`

You get this diff:

```diff
2c2
< 0.000,0.000,0.000,0.000,1.000,1.000,0.000,0.000,71.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
---
> 0.000,0.000,0.000,0.000,1.000,1.000,0.000,0.000,7.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000

```

You can notice the classification change from 71 to 7. It will change any classification to  `classification % 32`. Ex: 255 -> 31. See table below.

**Expected behavior**
The classification should be preserved

| Input Classification | Expected Classification | Result Classification | Works |
|----|----|----|---|
| 0 | 0 | 0 | :white_check_mark: |
| 1 | 1 | 1 | :white_check_mark: |
| 2 | 2 | 2 | :white_check_mark: |
| 3 | 3 | 3 | :white_check_mark: |
| 4 | 4 | 4 | :white_check_mark: |
| 5 | 5 | 5 | :white_check_mark: |
| 6 | 6 | 6 | :white_check_mark: |
| 7 | 7 | 7 | :white_check_mark: |
| 9 | 9 | 9 | :white_check_mark: |
| 10 | 10 | 10 | :white_check_mark: |
| 11 | 11 | 11 | :white_check_mark: |
| 13 | 13 | 13 | :white_check_mark: |
| 14 | 14 | 14 | :white_check_mark: |
| 15 | 15 | 15 | :white_check_mark: |
| 17 | 17 | 17 | :white_check_mark: |
| 18 | 18 | 18 | :white_check_mark: |
| 64 | 64 | 0 | :x: |
| 65 | 65 | 1 | :x: |
| 66 | 66 | 2 | :x: |
| 67 | 67 | 3 | :x: |
| 68 | 68 | 4 | :x: |
| 69 | 69 | 5 | :x: |
| 70 | 70 | 6 | :x: |
| 71 | 71 | 7 | :x: |
| 72 | 72 | 8 | :x: |
| 73 | 73 | 9 | :x: |
| 74 | 74 | 10 | :x: |
| 75 | 75 | 11 | :x: |
| 76 | 76 | 12 | :x: |
| 77 | 77 | 13 | :x: |
| 78 | 78 | 14 | :x: |
| 79 | 79 | 15 | :x: |
| 80 | 80 | 16 | :x: |
| 81 | 81 | 17 | :x: |
| 82 | 82 | 18 | :x: |
| 83 | 83 | 19 | :x: |
| 84 | 84 | 20 | :x: |
| 85 | 85 | 21 | :x: |
| 86 | 86 | 22 | :x: |
| 87 | 87 | 23 | :x: |
| 88 | 88 | 24 | :x: |
| 89 | 89 | 25 | :x: |
| 90 | 90 | 26 | :x: |
| 91 | 91 | 27 | :x: |
| 92 | 92 | 28 | :x: |
| 93 | 93 | 29 | :x: |
| 94 | 94 | 30 | :x: |
| 95 | 95 | 31 | :x: |
| 96 | 96 | 0 | :x: |
| 97 | 97 | 1 | :x: |
| 98 | 98 | 2 | :x: |
| 99 | 99 | 3 | :x: |
| 100 | 100 | 4 | :x: |
| 101 | 101 | 5 | :x: |
| 102 | 102 | 6 | :x: |
| 103 | 103 | 7 | :x: |
| 104 | 104 | 8 | :x: |
| 105 | 105 | 9 | :x: |
| 106 | 106 | 10 | :x: |
| 107 | 107 | 11 | :x: |
| 108 | 108 | 12 | :x: |
| 109 | 109 | 13 | :x: |
| 110 | 110 | 14 | :x: |
| 111 | 111 | 15 | :x: |
| 112 | 112 | 16 | :x: |
| 113 | 113 | 17 | :x: |
| 114 | 114 | 18 | :x: |
| 115 | 115 | 19 | :x: |
| 116 | 116 | 20 | :x: |
| 117 | 117 | 21 | :x: |
| 118 | 118 | 22 | :x: |
| 119 | 119 | 23 | :x: |
| 120 | 120 | 24 | :x: |
| 121 | 121 | 25 | :x: |
| 122 | 122 | 26 | :x: |
| 123 | 123 | 27 | :x: |
| 124 | 124 | 28 | :x: |
| 125 | 125 | 29 | :x: |
| 126 | 126 | 30 | :x: |
| 127 | 127 | 31 | :x: |
| 128 | 128 | 0 | :x: |
| 129 | 129 | 1 | :x: |
| 130 | 130 | 2 | :x: |
| 131 | 131 | 3 | :x: |
| 132 | 132 | 4 | :x: |
| 133 | 133 | 5 | :x: |
| 134 | 134 | 6 | :x: |
| 135 | 135 | 7 | :x: |
| 136 | 136 | 8 | :x: |
| 137 | 137 | 9 | :x: |
| 138 | 138 | 10 | :x: |
| 139 | 139 | 11 | :x: |
| 140 | 140 | 12 | :x: |
| 141 | 141 | 13 | :x: |
| 142 | 142 | 14 | :x: |
| 143 | 143 | 15 | :x: |
| 144 | 144 | 16 | :x: |
| 145 | 145 | 17 | :x: |
| 146 | 146 | 18 | :x: |
| 147 | 147 | 19 | :x: |
| 148 | 148 | 20 | :x: |
| 149 | 149 | 21 | :x: |
| 150 | 150 | 22 | :x: |
| 151 | 151 | 23 | :x: |
| 152 | 152 | 24 | :x: |
| 153 | 153 | 25 | :x: |
| 154 | 154 | 26 | :x: |
| 155 | 155 | 27 | :x: |
| 156 | 156 | 28 | :x: |
| 157 | 157 | 29 | :x: |
| 158 | 158 | 30 | :x: |
| 159 | 159 | 31 | :x: |
| 160 | 160 | 0 | :x: |
| 161 | 161 | 1 | :x: |
| 162 | 162 | 2 | :x: |
| 163 | 163 | 3 | :x: |
| 164 | 164 | 4 | :x: |
| 165 | 165 | 5 | :x: |
| 166 | 166 | 6 | :x: |
| 167 | 167 | 7 | :x: |
| 168 | 168 | 8 | :x: |
| 169 | 169 | 9 | :x: |
| 170 | 170 | 10 | :x: |
| 171 | 171 | 11 | :x: |
| 172 | 172 | 12 | :x: |
| 173 | 173 | 13 | :x: |
| 174 | 174 | 14 | :x: |
| 175 | 175 | 15 | :x: |
| 176 | 176 | 16 | :x: |
| 177 | 177 | 17 | :x: |
| 178 | 178 | 18 | :x: |
| 179 | 179 | 19 | :x: |
| 180 | 180 | 20 | :x: |
| 181 | 181 | 21 | :x: |
| 182 | 182 | 22 | :x: |
| 183 | 183 | 23 | :x: |
| 184 | 184 | 24 | :x: |
| 185 | 185 | 25 | :x: |
| 186 | 186 | 26 | :x: |
| 187 | 187 | 27 | :x: |
| 188 | 188 | 28 | :x: |
| 189 | 189 | 29 | :x: |
| 190 | 190 | 30 | :x: |
| 191 | 191 | 31 | :x: |
| 192 | 192 | 0 | :x: |
| 193 | 193 | 1 | :x: |
| 194 | 194 | 2 | :x: |
| 195 | 195 | 3 | :x: |
| 196 | 196 | 4 | :x: |
| 197 | 197 | 5 | :x: |
| 198 | 198 | 6 | :x: |
| 199 | 199 | 7 | :x: |
| 200 | 200 | 8 | :x: |
| 201 | 201 | 9 | :x: |
| 202 | 202 | 10 | :x: |
| 203 | 203 | 11 | :x: |
| 204 | 204 | 12 | :x: |
| 205 | 205 | 13 | :x: |
| 206 | 206 | 14 | :x: |
| 207 | 207 | 15 | :x: |
| 208 | 208 | 16 | :x: |
| 209 | 209 | 17 | :x: |
| 210 | 210 | 18 | :x: |
| 211 | 211 | 19 | :x: |
| 212 | 212 | 20 | :x: |
| 213 | 213 | 21 | :x: |
| 214 | 214 | 22 | :x: |
| 215 | 215 | 23 | :x: |
| 216 | 216 | 24 | :x: |
| 217 | 217 | 25 | :x: |
| 218 | 218 | 26 | :x: |
| 219 | 219 | 27 | :x: |
| 220 | 220 | 28 | :x: |
| 221 | 221 | 29 | :x: |
| 222 | 222 | 30 | :x: |
| 223 | 223 | 31 | :x: |
| 224 | 224 | 0 | :x: |
| 225 | 225 | 1 | :x: |
| 226 | 226 | 2 | :x: |
| 227 | 227 | 3 | :x: |
| 228 | 228 | 4 | :x: |
| 229 | 229 | 5 | :x: |
| 230 | 230 | 6 | :x: |
| 231 | 231 | 7 | :x: |
| 232 | 232 | 8 | :x: |
| 233 | 233 | 9 | :x: |
| 234 | 234 | 10 | :x: |
| 235 | 235 | 11 | :x: |
| 236 | 236 | 12 | :x: |
| 237 | 237 | 13 | :x: |
| 238 | 238 | 14 | :x: |
| 239 | 239 | 15 | :x: |
| 240 | 240 | 16 | :x: |
| 241 | 241 | 17 | :x: |
| 242 | 242 | 18 | :x: |
| 243 | 243 | 19 | :x: |
| 244 | 244 | 20 | :x: |
| 245 | 245 | 21 | :x: |
| 246 | 246 | 22 | :x: |
| 247 | 247 | 23 | :x: |
| 248 | 248 | 24 | :x: |
| 249 | 249 | 25 | :x: |
| 250 | 250 | 26 | :x: |
| 251 | 251 | 27 | :x: |
| 252 | 252 | 28 | :x: |
| 253 | 253 | 29 | :x: |
| 254 | 254 | 30 | :x: |
| 255 | 255 | 31 | :x: |

**System/installation information:**
pdal/pdal:latest from docker

```
$ uname -a
Linux d00aef754199 4.19.76-linuxkit #1 SMP Fri Apr 3 15:53:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

```

```
$ pdal --version
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
pdal 2.1.0 (git-version: 6ec91b)
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


```

**Comment by abellgithub** [comment]
I haven't looked at the details here.  That is up to you.  You need to find a single transition that is invalid.  This means finding an issue with output given your single-point input. You need to investigate both the input and output classification/class flags at each step to determine where the data becomes invalid.  I suspect that what you're seeing is due to the fact that you're taking LAS 1.4 classifications that range from 0-255 and storing them in a LAS 1.2, which only supports 5 bits of real information, using the remaining three bits for flags that are stored elsewhere in version 1.4.  What should happen with a conversion of a classification greater than 31 when converting from 1.4 to 1.2 is up for debate.  There is an existing issue that you noted (#1701) that highlights this.  That said, I don't believe the current handling is wrong, as such.

If you can find an invalid transformation in a single PDAL command, I'd be happy to investigate.

**Comment by jrobichaud** [comment]
The Point cloud used as input is a 1.4 format created using pdal "writers.las", not a 1.2 format.

The problem occurs with a single pdal command running the pipeline. The other `pdal translate` commands are only to be able to read the points as a human.

I believe the bug comes from readers.las where it creates a ClassFlag dimension with 0 for each points and then reuse that invalid information in the writer.

**Comment by abellgithub** [comment]
Which single command causes the problem?  What is the input classification/class flags?  What is the output classification/class flags?

**Comment by jrobichaud** [comment]
# Which single command causes the problem? 

```bash
pdal pipeline pipeline.json
```

with pipeline:
```json
{
  "pipeline": [
    {
      "type": "readers.las",
      "filename": "text_to_las.las"
    },
    {
      "type": "writers.las",
      "minor_version": "4",
      "extra_dims": "all",
      "compression": "laszip",
      "filename": "las_to_las.las"
    }
  ]
}
```

# What is the input classification/class flags?

Classification: 71
ClassFlags: does not exist

Note: I created the pointcloud using a `readers.txt` and `writers.las`

# What is the output classification/class flags?
Classification: 7
ClassFlags: 0
