### ISSUE TITLE
pdal tindex: srs column format

### ISSUE THREAD

**Issue by klassenjs** [PDAL/PDAL#3100]
`pdal tindex` drops the vertical component of a compound SRS when creating a tile index.  For example an input file in EPSG:3071+5703 is stored as EPSG:3071 in the SRS column.

(This is currently causing an issue for me because `readers.tindex` uses the SRS stored in the tile index to override the SRS set in the source files and thus ignores the vertical component of the source file's compound srs.)

@hobu suggested pdal should instead store the compound WKT in the SRS column instead of guessing a EPSG code.

https://lists.osgeo.org/pipermail/pdal/2020-May/002141.html

**Comment by hobu** [comment]
Fixed in #3122
