### ISSUE TITLE
readers.tindex: srs column

### ISSUE THREAD

**Issue by klassenjs** [PDAL/PDAL#3101]
`readers.tindex` defaults to reading individual file srs information from the `srs` column of the tileindex.  This causes issues when reading from files that contain their own srs information when the srs stored in the tileindex is wrong (or incomplete) as in #3100.

It would help if `readers.tindex` read the SRS from the source files by default (and only override with the value from the SRS column if it is set in the pipeline).

@hobu said "This should maybe be the default behavior anyway for readers.tindex. The SRS column in the tile index is a convenience for upstream users of the tile index files themselves, not for PDAL. It would be one way to do some kind of default/override scenario, but that is not as common as do the expected thing of reading the SRS from the files."

https://lists.osgeo.org/pipermail/pdal/2020-May/002141.html

**Comment by hobu** [comment]
Implemented in #3102

**Comment by klassenjs** [comment]
Tested it works as expected both with and without "srs_column".
