### ISSUE TITLE
Multi Dimension Pipeline Support for HDF5 Files

### ISSUE THREAD

**Issue by trevorskaggs** [PDAL/PDAL#3107]
When working with ICESAT2 data, there are up to 6 different beam returns in a single file.  Currently I will need to process each file 6 times and merge the results into a single laz file.
Would be nice if we could pass multiple sets of values to the dimensions stage.

Example Pipeline for a given Beam Pair:
```[
    {
        "type": "readers.hdf",
        "filename": "something.h5",
        "dimensions": [
            {
                "X": "gt1l/land_ice_segments/longitude",
                "Y": "gt1l/land_ice_segments/latitude",
                "Z": "gt1l/land_ice_segments/h_li",
                "GpsTime": "gt1l/land_ice_segments/delta_time"
            },
            {
                "X": "gt1r/land_ice_segments/longitude",
                "Y": "gt1r/land_ice_segments/latitude",
                "Z": "gt1r/land_ice_segments/h_li",
                "GpsTime": "gt1r/land_ice_segments/delta_time"
            }
        ]
    },
    {
        "type": "filters.range",
        "limits": "Z[0:100000]"
    },
    {
        "type": "filters.reprojection",
        "in_srs": "EPSG:4326",
        "out_srs": "EPSG:32757"
    },
]```

**Comment by hobu** [comment]
I would propose the following:

* Each `dimension` entry is a different PointView
* Given that we don't have Named Views, the addition of an entry of `OriginId:42` to the map would attribute the points for the particular `dimension` entry.

    ```
       prepare()
        if 'OriginId' in map: add Dimension::Id::OriginId
    ```

    ```
     if name == 'OriginId':
        if not h5.attribute.exists(value):
            point.setField(Id::OriginId, value)
    ```

**Comment by connormanning** [comment]
Sounds reasonable to me.  So in the pipeline spec that might look something like (could use OriginId or PointSourceId or some other custom thing):
```
"dimensions": [
    {
        "X": "gt1l/land_ice_segments/longitude",
        "Y": "gt1l/land_ice_segments/latitude",
        "Z": "gt1l/land_ice_segments/h_li",
        "GpsTime": "gt1l/land_ice_segments/delta_time",
        "PointSourceId": 0
    },
    {
        "X": "gt1r/land_ice_segments/longitude",
        "Y": "gt1r/land_ice_segments/latitude",
        "Z": "gt1r/land_ice_segments/h_li",
        "GpsTime": "gt1r/land_ice_segments/delta_time",
        "PointSourceId": 1
    }
]
```

All this functionality could potentially be done by stacking 6 tagged readers pointing at the same filename followed by assign filters, but this driver is kind of special among the others since it uses tabular data.  So I think this functionality makes sense in the driver itself rather than having to stack 6 (or 12 if tagging point sources) stages to extract a single file's worth of data.

**Comment by hobu** [comment]
> I don't think the request was to have the various sets separated out, just to read them in one go.

True, but the very next request is to be able to separate them by specification 😄

**Comment by abellgithub** [comment]
I don't believe in speculative features.

**Comment by hobu** [comment]
*I* want to be able to separate the groupings. If we had Named PointViews, this wouldn't matter.

**Comment by abellgithub** [comment]
And what's wrong with just stacking a bunch of readers?  The OP wants to merge anyway.

**Comment by hobu** [comment]
A typical ICESat-2 HDF file has 6 groupings of points. That's 12 stages of `readers.hdf` and `filters.assign` plus all of the tagging. 🤮

**Comment by abellgithub** [comment]
Well, someone argued that we should make an icesat-2 reader.

**Comment by connormanning** [comment]
Seems reasonable if this is too "special" to be applicable to other HDF formats.  I don't know enough about what's out there in the wild for HDF to have an opinion there.

**Comment by trevorskaggs** [comment]
I am currently working with other HDF datasets and they are definitely not all multi beamed. SMAP is a dataset that is stored in HDF5, but has a completely different configuration.  I will try to dig in to the other ICE specs and see if there is some commonality to glean.

**Comment by hobu** [comment]
It is possible to do this using multiply-defined readers. Let's close for now and revisit an explicit ICESat-2 driver (one for each of the 10 ATL products?) at the time it is needed.
