### ISSUE TITLE
filters.hag_delaunay throws when PointView has 0 points too

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#3112]
https://github.com/PDAL/PDAL/blob/9a3a9445bc3f6e452c2fadf8970df1eb75ab28bc/filters/HagNnFilter.cpp#L149 is too aggressive. We correctly can't do HAG if we have no points with ground values, but it is not an error to pass 0 points through a filter. We need to not throw and not do any work in that scenario.

**Comment by connormanning** [comment]
After some discussion on appropriate behavior for when HAG can't assign a real value, like when there are 0 or very few points or no ground points, I lean toward the behavior of adding a `nodata_value` option.  I'd choose a default of 0 which seems the most conservative, rather than something like -999 or 999 which would be range-filtered in many common workflows.

This `nodata_value` would assigned when a) there are no ground points at all or b) the point is outside the ground surface and `extrapolate` is `false`, following the existing pattern.

I'll let someone else put forth the masking suggestion which was also discussed.

**Comment by hobu** [comment]
I lean toward a solution that sets a ClassBits flag for the`HeightAboveGround` dimension that masks points to be ignored if HAG can't be run. This way downstream filters can discriminate if needed, and it would give a mechanism for upstream filters to inform the HAG filter to not process particular points without removing them from the stream entirely.

**Comment by chambbj** [comment]
For `nodata_value`, even a value of 0 could be filtered. Doesn't mean we shouldn't go this route, or that 0 is an incorrect default, but we should make it configurable. This should be combined with ClassBits or an extra dimension mask. I don't think it works on it's own, especially with a value that could be easily confused like 0.

I'd be a little concerned with ClassBits being hidden for most users. How many other software packages will support the non-traditional ClassBits? Even traditional ones, you have to think to check them. I suppose the same argument could be made against using extra dimensions.

If we go the route of ClassBits, we'll just need to extend our existing `ignoreClassBits` code to work with extra flags if we want our enabled filters to be able to ignore them. If we use extra dimensions, then the existing `ignoreDimRange` just works out of the box.

I still think that at some level, if you are encountering this situation, you probably need to rethink something about your data/processing pipeline. But maybe this at least allows you to defer such decision making.

**Comment by hobu** [comment]
> I'd be a little concerned with ClassBits being hidden for most users. How many other software packages will support the non-traditional ClassBits? Even traditional ones, you have to think to check them. I suppose the same argument could be made against using extra dimensions.

There's a distinction between what's needed by pipeline processors and what should be serialized. ClassBits is more of a serialization thing than a pipeline processing marker. This whole topic (masking, ignoreds, dontprocess) is an area where PDAL is really messy and inconsistent.

**Comment by abellgithub** [comment]
This is because LAS.

**Comment by hobu** [comment]
> This is because LAS.

That masking is messy in PDAL? Yes that's true, but the filters aren't completely consistent with respect to `ignore` or `where` and filters are left to themselves to add masking dimensions that other downstream filters have to know about to do anything with.
