### ISSUE TITLE
using PDAL functions and filters with FWF LAS data (Point Data Record Format 4)

### ISSUE THREAD

**Issue by antoinebio** [PDAL/PDAL#3128]
Dear ALL
I'd like to  generate LAS boundary using the – filters.hexbin
Do we have any chance to have readers.las supporting LAS/LAZ with FWF data ?

![image](https://user-images.githubusercontent.com/30265851/84604168-66203100-ae94-11ea-9c98-8c6b989e11f7.png)

thanks
antoine

**Comment by hobu** [comment]
> Do we have any chance to have readers.las supporting LAS/LAZ with FWF data ?

For "real" waveform support of LAS in PDAL? No. PDAL isn't a waveform manipulation library and will never be. Use something like PulseWaves to address the topic.

For the ability to read point data (but not waveforms) from LAS files that have per-point waveform entries? Please submit a pull request with an implementation. Alternatively, you could contract with [Hobu](https://hobu.co) to directly address the topic before the next PDAL release.
