### ISSUE TITLE
Georeferencing with different file formats (GPS, IMU, LIDAR)

### ISSUE THREAD

**Issue by yyunon** [PDAL/PDAL#3142]
Hey,

I am working on Georeferencing of LIDAR data. I have looked at the issues and discussions online.  It is apparent that Georeferencing feature for PDAL is supported only with csd file format. 

I know that there exists many different vendor-specific data formats for each sensor and ways to combine them all. I will use "csv" for IMU, "GPX or track files saved in csv" for GPS and "pcd" for pointclouds (all with the same timestamp). Will PDAL support other formats soon (What if I want to provide two or three different files for GPS, IMU and Lidar data) for georeferencing? How can I proceed with appending different data formats to PDAL for this application? 

I am aware of the fact that using different format for each sensor increases the complexity (in terms of association of each information with same timestamp etc.). Briefly, I am trying to understand the feasibility of this process.

Thanks in advance!

**Comment by hobu** [comment]
Please post this inquiry on the mailing list. GitHub is for bugs and development traffic.
