### ISSUE TITLE
Assertion Reading E57 File

### ISSUE THREAD

**Issue by AlbionS** [PDAL/PDAL#3163]
I have an e57 that I want to decimate with the sample filter and convert it to a las file.
--------------------------------------------------------------------------------

When I run this command : 
**-pdal translate /home/data/pump.e57 /home/data/pump_decimated.las sample --filters.sample.radius=0.005**
I get the error : 
**_-pdal: ../pdal/PointView.cpp:100: virtual void pdal::PointView::setFieldInternal(pdal::Dimension::Id, pdal::PointId, const void*): Assertion `m_temps.empty()' failed._**

I thought that maybe pdal is not able convert the e57 file to a las file and decimate it at the same time, so I tried just to decimate the e57 file : 
**-pdal translate /home/data/pump.e57 /home/data/pump_decimated.e57 sample --filters.sample.radius=0.005**
Same error.

So then I tested this filter with a las file and it works fine, but not with e57 files : 
**pdal translate /home/data/pump.las /home/data/pump_decimated.las sample --filters.sample.radius=0.005 (this works)**

I have the readers.e57 and writers.e57, I can convert an e57 file to las there's no problem for that.
I even tried another filter to decimate the e57 file and convert it to a las file and it worked : 
**pdal translate /home/data/pump.e57 /home/data/pump_decimated.las decimation --filters.decimation.step=10 (this works)**

Why does the sample filter not work with e57 files ? is there a bug or it is just not supported for the e57 files ? Meanwhile other filters do work !

--------------------------------------------------------------------------------

Here is the file that I used, so you can reproduce the error.

https://wetransfer.com/downloads/213b6d93ebf2c0401b1841e7d8c64dec20200709084633/61fc3be5e49928a7e239b4dd2dfdde6e20200709084654/dbfb74

My PDAL version is : 
pdal 2.1.0 (git-version: c2e6bb)

Best,
Albion

**Comment by chambbj** [comment]
Can replicate at stated version (works with Conda PDAL v2.1.0 install though).

**Comment by AlbionS** [comment]
Thank you very much, this is works now. 

Is it normal that this filter -filters.sample.radius=0.005 uses a lot of ressources while the decimation --filters.decimation.step=10 is stable and uses a fixed amount of ressources (CPU and RAM) ?
