### ISSUE TITLE
num_points in info summary

### ISSUE THREAD

**Issue by kjwaters** [PDAL/PDAL#3199]
I think there's a bug in the num_points output from pdal info --summary. I'm working with pdal 2.1.0 (git-version: 1d5e8a). If I try to get the summary info on one of the USGS entwine data sets, I get a ridiculous answer for the number of points.

$ pdal info --summary -i https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_NC_Phase4_Alexander_2017_LAS_2019/ept.json
{
  "filename": "https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_NC_Phase4_Alexander_2017_LAS_2019/ept.json",
  "now": "2020-07-30T14:34:11-0400",
  "pdal_version": "2.1.0 (git-version: 1d5e8a)",
  "reader": "readers.ept",
  "summary":
  {
    "bounds":
    {
      "maxx": -9017120,
      "maxy": 4307226,
      "maxz": 845,
      "minx": -9055642,
      "miny": 4270201,
      "minz": 250
    },
    "dimensions": "X, Y, Z, Intensity, ReturnNumber, NumberOfReturns, ScanDirectionFlag, EdgeOfFlightLine, Classification, ScanAngleRank, UserData, PointSourceId, GpsTime, ScanChannel, ClassFlags, OriginId",
    **"num_points": 18446744072589792349,**
    "srs":

That's something like 1.8e19.  The ept.json file shows "points": 28945011805.

**Comment by abellgithub** [comment]
This is a duplicate: https://github.com/PDAL/PDAL/issues/3120
