### ISSUE TITLE
Add JSON Schema for stage options 

### ISSUE THREAD

**Issue by rjpals** [PDAL/PDAL#3209]
Add the ability to PDAL to output the [JSON schema](https://json-schema.org/) for the options of each stage. Do this by adding a member method to the `Stage` class that converts the `ProgramArgs` structure into a JSON-schema, which a user can then use to validate the arguments passed to any stage of a PDAL pipeline.

**Comment by rjpals** [comment]
For example, if I were a user trying to learn how to use the text reader, I could query the JSON schema of the reader via the CLI, the C++ api or the Python api and receive something like this:
```javascript

{
    "type":"object",
    "properties":{
        "filename":{
            "type":"string",
            "description":"text file to read"
        },
        "count":{
            "type":"number",
            "description":"Maximum number of points to read. "
        },
        "override_srs":{
            "type":"string",
            "description":"Spatial reference to apply to the data. Overrides any SRS in the input itself. Can be specified as a WKT, proj.4 or EPSG string."
        },
        "header":{
            "type":"string",
            "description":"String to use as the file header. All lines in the file are assumed to be records containing point data unless skipped with the skip option"
        },
        "separator":{
            "type":"string",
            "description":"Separator character to override that found in header line."
        },
        "skip":{
            "type":"integer",
            "description":"Number of lines to ignore at the beginning of the file."
        }
    },
  	"required": ["filename"]
}
```
As a CLI user, I could read through the options and get information about the arguments that the reader requires/accepts. I could also use this schema to validate my options before passing them to PDAL. An example usage of this from the CLI app might look like:
```bash
$ pdal getschema readers.text > schema.json
$ ajv -s schema.json -d pipeline.json # validates arguments with ajv CLI app
$ pdal pipeline pipeline.json
```
*This allows us to validate the options for the text reader in a standardized, programmatic fashion*.

PDAL currently has a similar feature in the Python API, which validates the pipeline by running `prepare()` on each stage. This is not always desirable, as `prepare()` can have unwanted side effects, such as opening files. The schema would provide a high-level validation of the stage's options without side effects.

**Comment by abellgithub** [comment]
I'm not sure where you're going to get the type information. I also don't know how you'd validate things. Maybe someone should just write the schema if they really want this, rather than try to infer it from the ProgramArgs, which really can't be done.

**Comment by hobu** [comment]
> I'm not sure where you're going to get the type information.

ctor each stage, Stage::addAllArgs and then walk the ProgramArgs for the stage. 

>  I also don't know how you'd validate things.

We don't want to validate the values of the arguments. We want to validate the structure of the pipeline and the types of the arguments.

**Comment by abellgithub** [comment]
As I said, there is no run-time type information in ProgramArgs. ProgramArgs takes any type that converts to/from a string, so the proper way to go is to call every argument a string. We already have dump3(), which creates JSON infomation about programArgs. If you want to convert that output (or any of the other existing formats) to JSON schema with some outside program, that seems fine.
