### ISSUE TITLE
PLY reader may be retaining resources after `done`

### ISSUE THREAD

**Issue by connormanning** [PDAL/PDAL#3224]
Reported as connormanning/entwine#236, a quick glance at the code indicates to me that the PLY reader might need to clean up some resources (other than the filehandle) during `done`.  See [comment](https://github.com/connormanning/entwine/issues/236#issuecomment-682707444).

**Comment by abellgithub** [comment]
The `m_elements` is read from the header. It's small. If the reader is re-used, it's cleared. I don't see how this would lead to memory bloat.

**Comment by connormanning** [comment]
Gotcha - thought it might be a per-point thing at a glance.
