### ISSUE TITLE
writers.gdal processing Noise Points (7) oddly

### ISSUE THREAD

**Issue by rphillips91** [PDAL/PDAL#3232]
Ran the following python script which gave an unexpected output. Red areas denote pulse density < 2.99 per cell.

```
import json
import os
import pdal

point_cloud_files = "E:/test_density/CL2_AT24_2018_1000_1529.las"
pulse_density_raster = "E:/test_density/pdal_density.tif"
    
pipeline = [
    {
        "type" : "readers.las",
        "filename" : point_cloud_files
    },
    {
        "type": "filters.returns",
        "groups": "first, only"
    },        
    {
        "type" : "writers.gdal",
        "resolution": 2,
        "nodata" : -9999,
        "filename": pulse_density_raster
    }    
    ]

pipeline = pdal.Pipeline(json.dumps(pipeline))
pipeline.execute()
```
My tiff output
![Example_1 output](https://user-images.githubusercontent.com/36900458/92061370-35dc9480-edea-11ea-8682-cb97cba81c91.png)

--
To analyze each step, I made a intermediary LAS file containing first and only returns. 
Then ran this point cloud file as the input file for writers.gdal which gave me the correct output.
(Confirmed by my current lastools /arcpy output and pulse density of the source point cloud file) e.g.

1st Step
```
import json
import os
import pdal

point_cloud_files = "E:/test_density/CL2_AT24_2018_1000_1529.las"
pulse_density_pointcloud_file = "E:/test_density/output_file.las"
    
pipeline = [
    {
        "type" : "readers.las",
        "filename" : point_cloud_files
    },
    {
        "type": "filters.returns",
        "groups": "first, only"
    },       
    {
        "type" : "writers.las",
        "filename": pulse_density_pointcloud_file
    }    
    ]

pipeline = pdal.Pipeline(json.dumps(pipeline))
pipeline.execute()
```
2nd Step 

```
import json
import os
import pdal

point_cloud_files = "E:/test_density/output_file.las"
pulse_density_raster = "E:/test_density/pdal_density_second_step.tif"

pipeline = [
    {
        "type" : "readers.las",
        "filename" : point_cloud_files
    },     
    {
        "type" : "writers.gdal",
        "resolution": 2,
        "nodata" : -9999,
        "filename": pulse_density_raster
    }    
    ]

pipeline = pdal.Pipeline(json.dumps(pipeline))
pipeline.execute()
```

![Example_Two_Second_Step_Output](https://user-images.githubusercontent.com/36900458/92061928-91f3e880-edeb-11ea-9c58-5446494405b7.png)

The red area in the first image looks like Noise points (7) e.g.
![image](https://user-images.githubusercontent.com/36900458/92063052-4db61780-edee-11ea-88db-62efc9f35c74.png)

(Unfortunately this example point cloud file hasn't been published yet, would have to share in confidence)

**Comment by abellgithub** [comment]
I'm not sure why you believe noise points would be filtered out by your procedure. If you want to filter noise, you should use a filter designed for that purpose, like `filters.outlier`. See https://pdal.io/workshop/exercises/analysis/denoising/denoising.html

**Comment by rphillips91** [comment]
I don't believe noise points would be filtered out by my procedure. 
Long story short the writers.gdal output does not make sense, there are more than 2.99 pulses in each cell in the red area.

**Comment by hobu** [comment]
> Long story short the writers.gdal output does not make sense, there are more than 2.99 pulses in each cell

The ``writers.gdal`` summary output is for the interpolation window/region, not the cell. See #3215
