### ISSUE TITLE
.Net

### ISSUE THREAD

**Issue by petrasvestartas** [PDAL/PDAL#3239]
Hi,

Is there any supporr for .Net users i.e. c#?

If, no can someone point me to tutorial how to run PDAL via command line?

**Comment by hobu** [comment]
You can use the PDAL [C API](https://github.com/PDAL/CAPI) and PINVOKE, but there's no explicit .NET API for PDAL. The [PDAL workshop ](https://pdal.io/workshop/index.html) has numerous examples of how to use PDAL from the command line.
