### ISSUE TITLE
readers.las won't use Geotiff for version 1.4 and point formats 0-5

### ISSUE THREAD

**Issue by abellgithub** [PDAL/PDAL#3242]

**Comment by hobu** [comment]
It won't, it doesn't, or it shouldn't? I'm confused on what the problem is.

**Comment by abellgithub** [comment]
Doesn't, but should when it's requested.

**Comment by dbrookes96** [comment]
I take it this would allow for readers.las to support point format 4 LAS files in the future?

We use PDAL to support importing and exporting LAS (and other formats) in our application. We recently had a customer try to use a LAS point format 4 file which readers.las does not support currently.

**Comment by abellgithub** [comment]
@dbrookes96 : No, I don't think that's in the plan.

**Comment by dbrookes96** [comment]
Ah okay thanks for clearing that up. I don't know a lot about LAS format honestly so I was unsure.

Thanks for the heads-up about lastools!
