### ISSUE TITLE
EPT reader report arbitrary json metadata at top level

### ISSUE THREAD

**Issue by msmitherdc** [PDAL/PDAL#3279]
for ept reader, return metadata stored at the ept.json level as json when metadata fetched

**Comment by abellgithub** [comment]
I don't understand exactly what's being requested. Can you please provide an example?

**Comment by msmitherdc** [comment]
ept.json can take additional json keys. For the key named "metadata", return the json under that key as metadata at the summary level and and in addition to the file level metadata when that is accessed

**Comment by hobu** [comment]
If ``readers.ept`` simply adds the ept.json tree as a metadata entry in its entirety, this need would be satisfied. The goal is to bring up EPT metadata to clients using PDAL to consume the data.
