### ISSUE TITLE
TEST(FauxReaderTest, uniform) broken

### ISSUE THREAD

**Issue by manisandro** [PDAL/PDAL#3280]
The test calls [1]

    ops.add("bounds", BOX3D(0, 100, 0, 100, 0, 100));

I suppose assuming that the `BOX3D` constructor takes the arguments `(minx, maxx, miny, maxy, minz, maxz)`, but in fact the `BOX3D` constructor takes the arguments in the order `(minx, miny, minz, maxx, maxy, maxz)`. This leads to the box being constructed with `miny=100, maxy=0`, which causes the test to fail:

    /usr/include/c++/10/bits/random.h:1751: std::uniform_real_distribution<_RealType>::param_type::param_type(_RealType, _RealType) [with _RealType = double]: Assertion '_M_a <= _M_b' failed.

[1] https://github.com/PDAL/PDAL/blob/master/test/unit/io/FauxReaderTest.cpp#L244

**Comment by abellgithub** [comment]
Please provide compiler/system info.

**Comment by manisandro** [comment]
FWIW, Fedora rawhide and gcc version 10.2.1 20201016 (Red Hat 10.2.1-6) (GCC).

But really, It's just a matter of constructor argument orders, see [1].

[1] https://github.com/PDAL/PDAL/blob/master/pdal/util/Bounds.hpp#L350

**Comment by abellgithub** [comment]
I understand. I was trying to determine why this hadn't come up on other platforms. I think tests aren't usually getting run in debug mode, and perhaps this is a new assertion in GCC 10.2?
