### ISSUE TITLE
Provide WHERE type syntax to range filter

### ISSUE THREAD

**Issue by chambbj** [PDAL/PDAL#3283]
We recently provided the ability to process subsets of data using the `where` option which is available to all PDAL filter stages. At the same time, the assign filter was also given the ability to use the same syntax when making assignments. This syntax would also be valuable when range filtering.

As a simple example, if I wanted to use the range filter to pass only points not classified as either low noise (Classification 7) or high noise (Classification 18), I would have to use the following JSON.

```json
{
    "type": "filters.range",
    "limits": "Classification[0:6], Classification[8:17], Classification[19:)"
}
```

Unfortunately, while it may seem intuitive at first, `"limits": "Classification![7:7], Classification![18:18]"` does not in fact work because of the way the two conditions are ORed together; Classification 7 is contained in the set specified by `Classification![18:18]` and vice versa.

This issue is being created to discuss the implementation of a means of providing `where` syntax support for the range filter, such that the above scenario could be specified simply as `Classification != 7 && Classification != 18` (or conversely `!(Classification == 7 || Classification == 18)`). Whether this can/should be passed using the existing `limits` option of the range filter, or should be provided as a new option altogether can be discussed.

**Comment by hobu** [comment]
`filters.expression` is now available in 2.5. Please reopen if that implementation does not support what is being requested here.
