### ISSUE TITLE
Add an environment variable to prevent plugin loading entirely

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#3287]
Some systems will want to prevent all loading of plugins and ``dlopen`` activity. I suggest adding a ``PDAL_PLUGIN_DISABLED`` environment variable that when set prevents any dlopen plugin loading.

**Comment by abellgithub** [comment]
Why?

**Comment by abellgithub** [comment]
If we must do such a thing, how about just setting the existing environment variable to something dumb.

**Comment by hobu** [comment]
> how about just setting the existing environment variable to something dumb.

That would satisfy my requirement.
