### ISSUE TITLE
LAS 1.4 - can't write |ScanAngle| larger than 90°

### ISSUE THREAD

**Issue by gui2dev** [PDAL/PDAL#3288]
Trying to write LAS 1.4 las file with `dataformat_id >= 6` raises conversion errors

```
$ pdal pipeline pipeline.json
PDAL: Unable to fetch data and convert as requested: ScanAngleRank:double(-151.833) -> signed char
```

With:
```
$ cat pipeline.json
[
    {
        "type":"readers.text",
        "filename":"inputfile.txt"
    },
    {
        "type":"writers.las",
        "filename":"outputfile.laz",
        "minor_version":4,
        "format":6,
        "dataformat_id":6
    }
]


inputfile.txt could be like :

"X","Y","Z","OffsetTime","ScanAngleRank"
377445.342,986746.942,7.062,0.000,-77.520
153439.692,343086.078,43.236,1.000,-80.169
486603.802,577837.919,59.571,2.000,-151.832
625694.164,798825.733,50.864,3.000,70.421
290093.456,989942.758,45.545,4.000,131.727
656883.274,964617.060,33.903,5.000,-161.3098
...
```

**Expected behavior**
A 1.4 laz file with `ScanAngle` field (as a `short`)

**System/installation information:**

```
$ uname -a
Linux DESKTOP-N8C3JIA 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ pdal --version
pdal 2.2.0 (git-version: a3dceb)
```

**Comment by abellgithub** [comment]
This an issue with the way that data is written for LAZ (rather than LAS). The LASZIP interface takes both the 1.4 ScanAngleRank and the pre-1.4 ScanAngle, which only has a range of [-90,90]. I'll have to investigate the LASZIP code to determine what should be done.

Note that writing to LAS (rather than LAZ) works fine.

**Comment by gui2dev** [comment]
Ok, but then `$ pdal translate outputfile.las outputfile.laz` yields the same error

**Comment by abellgithub** [comment]
Yes. You're writing to LAZ.

**Comment by gui2dev** [comment]
@abellgithub I guess it comes from this line no ?
https://github.com/PDAL/PDAL/blob/0f9407ab531780b4eef4d859685dd412ef81574f/io/LasWriter.cpp#L938
