### ISSUE TITLE
Dead appveyor links in "Building Under Windows" section

### ISSUE THREAD

**Issue by Crghilardi** [PDAL/PDAL#3289]
There are a few `404` links in the [windows build section](https://pdal.io/development/compilation/windows.html) of the docs. They all point at an `appveyor.yml` that does not exist anymore.

**Comment by hobu** [comment]
Yes, all of the windows build recipes for CI are now using Github Actions. You can find them at https://github.com/PDAL/PDAL/tree/master/scripts/ci/win

We would happily take a pull request that fixed up the Building Under Windows docs to point at this and expand upon it.
