### ISSUE TITLE
libnsl.so.1 in conda package

### ISSUE THREAD

**Issue by tvery42** [PDAL/PDAL#3293]
The version of pdal installed with conda is linked to libnssl.so.1 which is not installed by default on RedHat 8.
Since the library is considered deprecated would it be possible to have a version with its replacement https://github.com/thkukuk/libnsl ?

There is a workaround if you install the legacy package.

```
conda create -n test-pdal -c conda-forge python=3.7
conda activate test-pdal
conda install -c conda-forge pdal
$ pdal autzen.laz -p 0
pdal: error while loading shared libraries: libnsl.so.1: cannot open shared object file: No such file or directory
```

**System/installation information:**

```
$ uname -a
Linux jean-zay1 4.18.0-147.24.2.el8_1.x86_64 #1 SMP Tue Jul 21 14:11:32 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ pdal --version
```

If installed via Conda, you may be asked to paste the output of `conda list` and `conda info` as well.

<details>
  
```
$ conda list

#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
boost-cpp                 1.74.0               h9359b55_0    conda-forge
bzip2                     1.0.8                h516909a_3    conda-forge
c-ares                    1.17.1               h36c2ea0_0    conda-forge
ca-certificates           2020.11.8            ha878542_0    conda-forge
cairo                     1.16.0            h9f066cc_1006    conda-forge
certifi                   2020.11.8        py37h89c1867_0    conda-forge
cfitsio                   3.470                h2e3daa1_7    conda-forge
curl                      7.71.1               he644dc0_8    conda-forge
expat                     2.2.9                he1b5a44_2    conda-forge
fontconfig                2.13.1            h7e3eb15_1002    conda-forge
freetype                  2.10.4               h7ca028e_0    conda-forge
freexl                    1.0.5             h516909a_1002    conda-forge
geos                      3.8.1                he1b5a44_0    conda-forge
geotiff                   1.6.0                h5d11630_3    conda-forge
gettext                   0.19.8.1          hf34092f_1004    conda-forge
giflib                    5.2.1                h36c2ea0_2    conda-forge
glib                      2.66.3               h58526e2_0    conda-forge
hdf4                      4.2.13            hf30be14_1003    conda-forge
hdf5                      1.10.6          nompi_h54c07f9_1110    conda-forge
icu                       67.1                 he1b5a44_0    conda-forge
jpeg                      9d                   h36c2ea0_0    conda-forge
json-c                    0.13.1            hbfbb72e_1002    conda-forge
jsoncpp                   1.8.4             hc9558a2_1002    conda-forge
kealib                    1.4.13               h33137a7_1    conda-forge
krb5                      1.17.2               h926e7f8_0    conda-forge
laszip                    3.4.3                he1b5a44_1    conda-forge
laz-perf                  1.5.0                he1b5a44_0    conda-forge
ld_impl_linux-64          2.35.1               hed1e6ac_0    conda-forge
libblas                   3.9.0                3_openblas    conda-forge
libcblas                  3.9.0                3_openblas    conda-forge
libcurl                   7.71.1               hcdd3856_8    conda-forge
libdap4                   3.20.6               h1d1bd15_1    conda-forge
libedit                   3.1.20191231         h14c3975_1  
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.2.1             hf484d3e_1007  
libgcc-ng                 9.1.0                hdf63c60_0  
libgdal                   3.1.4                h670eac6_0    conda-forge
libgfortran-ng            7.5.0               hae1eefd_17    conda-forge
libgfortran4              7.5.0               hae1eefd_17    conda-forge
libglib                   2.66.3               hbe7bbb4_0    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
libkml                    1.3.0             h74f7ee3_1012    conda-forge
liblapack                 3.9.0                3_openblas    conda-forge
libnetcdf                 4.7.4           nompi_hefab0ff_106    conda-forge
libnghttp2                1.41.0               h8cfc5f6_2    conda-forge
libopenblas               0.3.12          pthreads_hb3c22a3_1    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libpq                     12.3                 h5513abc_2    conda-forge
libspatialite             5.0.0                h4dde289_0    conda-forge
libssh2                   1.9.0                hab1572f_5    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.1.0                h4f3a223_6    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libwebp-base              1.1.0                h36c2ea0_3    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.10               h68273f3_2    conda-forge
lz4-c                     1.9.2                he1b5a44_3    conda-forge
ncurses                   6.2                  he6710b0_1  
nitro                     2.7.dev6             he1b5a44_3    conda-forge
numpy                     1.19.4           py37h7e9df27_1    conda-forge
openjpeg                  2.3.1                h981e76c_3    conda-forge
openssl                   1.1.1h               h516909a_0    conda-forge
pcre                      8.44                 he1b5a44_0    conda-forge
pdal                      2.3.5                    pypi_0    pypi
pip                       20.2.4           py37h06a4308_0  
pixman                    0.40.0               h36c2ea0_0    conda-forge
poppler                   0.89.0               h4190859_1    conda-forge
poppler-data              0.4.10                        0    conda-forge
postgresql                12.3                 h8573dbc_2    conda-forge
proj                      7.1.1                h966b41f_3    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
python                    3.7.8           h8bdb77d_2_cpython    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
readline                  8.0                  h7b6447c_0  
setuptools                50.3.1           py37h06a4308_1  
sqlite                    3.33.0               h62c20be_0  
tiledb                    2.1.3                h17508cd_0    conda-forge
tk                        8.6.10               hbc83047_0  
tzcode                    2020a                h516909a_0    conda-forge
wheel                     0.35.1             pyhd3eb1b0_0  
xerces-c                  3.2.3                hfe33f54_1    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.12               h516909a_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.5                h7b6447c_0  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.4.5                h6597ccf_2    conda-forge
```

</details>

<details>
  
```
$ conda info
active environment : test-pdal
active env location : xxx
            shell level : 2
       user config file :xxx
 populated config files : xxx
          conda version : 4.8.5
    conda-build version : 3.19.2
         python version : 3.7.6.final.0
       virtual packages : __glibc=2.28
       base environment : /xxx/anaconda-py3/2020.02  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /xxx/anaconda-py3/2020.02/pkgs
                          /xxx/.conda/pkgs
       envs directories : /xxx/.conda/envs
                          /xxx/anaconda-py3/2020.02/envs
               platform : linux-64
             user-agent : conda/4.8.5 requests/2.24.0 CPython/3.7.6 Linux/4.18.0-147.24.2.el8_1.x86_64 rhel/8.1 glibc/2.28
                UID:GID : 300278:300225
             netrc file : None
           offline mode : False
```

</details>

**Comment by hobu** [comment]
```
error while loading shared libraries: libnsl.so.1: cannot open shared object file:
```

Can you use ``ldd`` to print which library is linking to "libnsl.so"? Is it really PDAL linking this directly, or one of the conda dependencies?

**Comment by tvery42** [comment]
It seems that pdal is directly linked.
<details>

$ ldd `which pdal`
    linux-vdso.so.1 (0x00007fd290088000)                                                                                                                                                     
    libpdal_base.so.12 => /xxx/.conda/envs/test-pdal/bin/../lib/libpdal_base.so.12 (0x00007fd28f710000)
    libpdal_util.so.12 => /xxx/.conda/envs/test-pdal/bin/../lib/libpdal_util.so.12 (0x00007fd290024000)
    libstdc++.so.6 => /xxx/.conda/envs/test-pdal/bin/../lib/libstdc++.so.6 (0x00007fd28feb0000)
    libgcc_s.so.1 => /xxx/.conda/envs/test-pdal/bin/../lib/libgcc_s.so.1 (0x00007fd28fe9c000)
    libc.so.6 => /lib64/libc.so.6 (0x00007fd28f33a000)
    libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fd28f11a000)
    libgdal.so.27 => /xxx/.conda/envs/test-pdal/bin/../lib/./libgdal.so.27 (0x00007fd28da72000)
    libgeotiff.so.5 => /xxx/.conda/envs/test-pdal/bin/../lib/./libgeotiff.so.5 (0x00007fd28da3d000)
    liblaszip.so.8 => /xxx/.conda/envs/test-pdal/bin/../lib/./liblaszip.so.8 (0x00007fd28d9ce000)
    libxml2.so.2 => /xxx/.conda/envs/test-pdal/bin/../lib/./libxml2.so.2 (0x00007fd28d866000)
    libz.so.1 => /xxx/.conda/envs/test-pdal/bin/../lib/./libz.so.1 (0x00007fd28d846000)
    libzstd.so.1 => /xxx/.conda/envs/test-pdal/bin/../lib/./libzstd.so.1 (0x00007fd28d77b000)
    libcurl.so.4 => /xxx/.conda/envs/test-pdal/bin/../lib/./libcurl.so.4 (0x00007fd28d6ec000)
    libcrypto.so.1.1 => /xxx/.conda/envs/test-pdal/bin/../lib/./libcrypto.so.1.1 (0x00007fd28d420000)
    libm.so.6 => /lib64/libm.so.6 (0x00007fd28d09e000)
    /lib64/ld-linux-x86-64.so.2 (0x00007fd28fe62000)
    libtiledb.so.2.1 => /xxx/.conda/envs/test-pdal/bin/../lib/././libtiledb.so.2.1 (0x00007fd28c9da000)
    libpoppler.so.100 => /xxx/.conda/envs/test-pdal/bin/../lib/././libpoppler.so.100 (0x00007fd28c689000)
    libjson-c.so.4 => /xxx/.conda/envs/test-pdal/bin/../lib/././libjson-c.so.4 (0x00007fd28c677000)
    libfreexl.so.1 => /xxx/.conda/envs/test-pdal/bin/../lib/././libfreexl.so.1 (0x00007fd28fe8a000)
    libgeos_c.so.1 => /xxx/.conda/envs/test-pdal/bin/../lib/././libgeos_c.so.1 (0x00007fd28c63c000)
    libwebp.so.7 => /xxx/.conda/envs/test-pdal/bin/../lib/././libwebp.so.7 (0x00007fd28c5b0000)
    libkmlbase.so.1 => /xxx/.conda/envs/test-pdal/bin/../lib/././libkmlbase.so.1 (0x00007fd28c58a000)
    libkmldom.so.1 => /xxx/.conda/envs/test-pdal/bin/../lib/././libkmldom.so.1 (0x00007fd28c4c5000)
    libkmlengine.so.1 => /xxx/.conda/envs/test-pdal/bin/../lib/././libkmlengine.so.1 (0x00007fd28c484000)
    libkmlxsd.so.1 => /xxx/.conda/envs/test-pdal/bin/../lib/././libkmlxsd.so.1 (0x00007fd28c46f000)
    libkmlregionator.so.1 => /xxx/.conda/envs/test-pdal/bin/../lib/././libkmlregionator.so.1 (0x00007fd28c460000)
    libexpat.so.1 => /xxx/.conda/envs/test-pdal/bin/../lib/././libexpat.so.1 (0x00007fd28c42a000)
    libxerces-c-3.2.so => /xxx/.conda/envs/test-pdal/bin/../lib/././libxerces-c-3.2.so (0x00007fd28c0a3000)
    libopenjp2.so.7 => /xxx/.conda/envs/test-pdal/bin/../lib/././libopenjp2.so.7 (0x00007fd28c046000)
    libnetcdf.so.18 => /xxx/.conda/envs/test-pdal/bin/../lib/././libnetcdf.so.18 (0x00007fd28bef4000)
    libmfhdf.so.0 => /xxx/.conda/envs/test-pdal/bin/../lib/././libmfhdf.so.0 (0x00007fd28bec8000)
    libdf.so.0 => /xxx/.conda/envs/test-pdal/bin/../lib/././libdf.so.0 (0x00007fd28be17000)
    libgif.so.7 => /xxx/.conda/envs/test-pdal/bin/../lib/././libgif.so.7 (0x00007fd28be08000)
    libjpeg.so.9 => /xxx/.conda/envs/test-pdal/bin/../lib/././libjpeg.so.9 (0x00007fd28bdca000)
    libtiff.so.5 => /xxx/.conda/envs/test-pdal/bin/../lib/././libtiff.so.5 (0x00007fd28bd48000)
    libpng16.so.16 => /xxx/.conda/envs/test-pdal/bin/../lib/././libpng16.so.16 (0x00007fd28bd0f000)
    libcfitsio.so.8 => /xxx/.conda/envs/test-pdal/bin/../lib/././libcfitsio.so.8 (0x00007fd28b9f4000)
    libpq.so.5 => /xxx/.conda/envs/test-pdal/bin/../lib/././libpq.so.5 (0x00007fd28b9a3000)
    libproj.so.19 => /xxx/.conda/envs/test-pdal/bin/../lib/././libproj.so.19 (0x00007fd28b6af000)
    libsqlite3.so.0 => /xxx/.conda/envs/test-pdal/bin/../lib/././libsqlite3.so.0 (0x00007fd28b58a000)
    libdap.so.25 => /xxx/.conda/envs/test-pdal/bin/../lib/././libdap.so.25 (0x00007fd28b3fa000)
    libdapserver.so.7 => /xxx/.conda/envs/test-pdal/bin/../lib/././libdapserver.so.7 (0x00007fd28b3e8000)
    libdapclient.so.6 => /xxx/.conda/envs/test-pdal/bin/../lib/././libdapclient.so.6 (0x00007fd28b39f000)
    liblzma.so.5 => /xxx/.conda/envs/test-pdal/bin/../lib/././liblzma.so.5 (0x00007fd28b376000)
    libicui18n.so.67 => /xxx/.conda/envs/test-pdal/bin/../lib/././libicui18n.so.67 (0x00007fd28b088000)
    libicuuc.so.67 => /xxx/.conda/envs/test-pdal/bin/../lib/././libicuuc.so.67 (0x00007fd28aea3000)
    libicudata.so.67 => /xxx/.conda/envs/test-pdal/bin/../lib/././libicudata.so.67 (0x00007fd28938c000)
    libuuid.so.1 => /xxx/.conda/envs/test-pdal/bin/../lib/././libuuid.so.1 (0x00007fd289383000)
    libspatialite.so.7 => /xxx/.conda/envs/test-pdal/bin/../lib/././libspatialite.so.7 (0x00007fd288cc5000)
    libpcre.so.1 => /xxx/.conda/envs/test-pdal/bin/../lib/././libpcre.so.1 (0x00007fd288c7e000)
    libiconv.so.2 => /xxx/.conda/envs/test-pdal/bin/../lib/././libiconv.so.2 (0x00007fd288b98000)
    libkea.so.1.4 => /xxx/.conda/envs/test-pdal/bin/../lib/././libkea.so.1.4 (0x00007fd288b2c000)
    libhdf5_cpp.so.103 => /xxx/.conda/envs/test-pdal/bin/../lib/././libhdf5_cpp.so.103 (0x00007fd288ab5000)
    libhdf5.so.103 => /xxx/.conda/envs/test-pdal/bin/../lib/././libhdf5.so.103 (0x00007fd288726000)
    librt.so.1 => /lib64/librt.so.1 (0x00007fd28851d000)
    libdl.so.2 => /lib64/libdl.so.2 (0x00007fd288319000)
    libnghttp2.so.14 => /xxx/.conda/envs/test-pdal/bin/../lib/././libnghttp2.so.14 (0x00007fd2882f1000)
    libssh2.so.1 => /xxx/.conda/envs/test-pdal/bin/../lib/././libssh2.so.1 (0x00007fd2882ad000)
    libssl.so.1.1 => /xxx/.conda/envs/test-pdal/bin/../lib/././libssl.so.1.1 (0x00007fd28821d000)
    libgssapi_krb5.so.2 => /xxx/.conda/envs/test-pdal/bin/../lib/././libgssapi_krb5.so.2 (0x00007fd2881cc000)
    libkrb5.so.3 => /xxx/.conda/envs/test-pdal/bin/../lib/././libkrb5.so.3 (0x00007fd2880f3000)
    libk5crypto.so.3 => /xxx/.conda/envs/test-pdal/bin/../lib/././libk5crypto.so.3 (0x00007fd2880d4000)
    libcom_err.so.3 => /xxx/.conda/envs/test-pdal/bin/../lib/././libcom_err.so.3 (0x00007fd2880ce000)
    libbz2.so.1.0 => /xxx/.conda/envs/test-pdal/bin/../lib/./././libbz2.so.1.0 (0x00007fd2880ba000)
    liblz4.so.1 => /xxx/.conda/envs/test-pdal/bin/../lib/./././liblz4.so.1 (0x00007fd288082000)
    libfreetype.so.6 => /xxx/.conda/envs/test-pdal/bin/../lib/./././libfreetype.so.6 (0x00007fd287fcd000)
    libfontconfig.so.1 => /xxx/.conda/envs/test-pdal/bin/../lib/./././libfontconfig.so.1 (0x00007fd287f86000)
    libgeos-3.8.1.so => /xxx/.conda/envs/test-pdal/bin/../lib/./././libgeos-3.8.1.so (0x00007fd287dcf000)
    libminizip.so => /xxx/.conda/envs/test-pdal/bin/../lib/./././libminizip.so (0x00007fd287dbf000)
    liburiparser.so => /xxx/.conda/envs/test-pdal/bin/../lib/./././liburiparser.so (0x00007fd287d9c000)
    libkmlconvenience.so.1 => /xxx/.conda/envs/test-pdal/bin/../lib/./././libkmlconvenience.so.1 (0x00007fd287d77000)
    libnsl.so.1 => not found
    libhdf5_hl.so.100 => /xxx/.conda/envs/test-pdal/bin/../lib/./././libhdf5_hl.so.100 (0x00007fd287d52000)
    libcharset.so.1 => /xxx/.conda/envs/test-pdal/bin/../lib/./././libcharset.so.1 (0x00007fd287d4b000)
    libkrb5support.so.0 => /xxx/.conda/envs/test-pdal/bin/../lib/./././libkrb5support.so.0 (0x00007fd287d3c000)
    libresolv.so.2 => /lib64/libresolv.so.2 (0x00007fd287b25000)

```

</details>

**Comment by abellgithub** [comment]
This is an issue with new RedHat/Centos.

**Comment by tvery42** [comment]
Actually the dependency is from libxerces-c-3.2.so which is a dependency of gdal.

**Comment by abellgithub** [comment]
That xerces needs NIS+ is very strange.

**Comment by tvery42** [comment]
```
readelf -d libxerces-c-3.2.so

Dynamic section at offset 0x35c790 contains 32 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libnsl.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libicui18n.so.67]
 0x0000000000000001 (NEEDED)             Shared library: [libicuuc.so.67]
 0x0000000000000001 (NEEDED)             Shared library: [libicudata.so.67]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x000000000000000e (SONAME)             Library soname: [libxerces-c-3.2.so]
```
