### ISSUE TITLE
Add option to dump geotiff keys using pdal info

### ISSUE THREAD

**Issue by msmitherdc** [PDAL/PDAL#3299]
in many cases, seeing the geotiff keys for LAS can help diagnose issues with the spatial reference. system. Add an option to dump the geotiff keys for geotiff key based formats. This was available in liblas.

**Comment by abellgithub** [comment]
Is `lasinfo` not sufficient?

**Comment by msmitherdc** [comment]
liblas is no longer supported, correct? If `lasinfo` was added to pdal, that would be sufficient

**Comment by abellgithub** [comment]
If this is just for investigative purposes, why wouldn't you just run lasinfo when necessary. That's what I do.

**Comment by msmitherdc** [comment]
1. liblas doesn't support compression on las 1.4
2. liblas is no longer approved on NGA networks since its no longer being maintained
3. simplification of deployment as we already deploy pdal

**Comment by hobu** [comment]
4. liblas doesn't support LAS 1.4 at all

**Comment by msmitherdc** [comment]
yes, correct.

its brew on osx that doesn't support compression.

**Comment by abellgithub** [comment]
Why are we talking about liblas at all? Isn't this info easy to get with lasinfo?

**Comment by hobu** [comment]
> Why are we talking about liblas at all?

`lasinfo` exists in both LAStools and libLAS. The LAStools variant is not approved for @msmitherdc's network either.

**Comment by hobu** [comment]
This now exists in master
