### ISSUE TITLE
How to loop las files through a pipeline to filter ground on Ubuntu

### ISSUE THREAD

**Issue by May7331** [PDAL/PDAL#3306]
Hello,
 I would like to filter ground and non-ground on each .las in a directory. This is what i have in the directory (48 .las files) : 
pt01.las
pt02.las
pt03.las
pt04.las
...(48 .las files)

I have tried [loop-a-directory-and-filter-it-through-a-pipeline](https://pdal.io/tutorial/reading.html#loop-a-directory-and-filter-it-through-a-pipeline) by typing 
`ls *.las | cut -d. -f1 | xargs -P20 -I{} pdal translate --json pipeline.json readers.las--readers.las.filename={}.las writers.las--writers.las.filename=ground/{}.las`
in the terminal, but in return, showing 
![image](https://user-images.githubusercontent.com/54517878/100878469-32d66a80-34e5-11eb-964e-8c7b30d448a3.png)

Here is the full json code I used :
![image](https://user-images.githubusercontent.com/54517878/100878996-d889d980-34e5-11eb-8ecc-a869e58c9894.png)

Also, I would like to know if it's possible to divide a las file into 2 las files at once through a filtering pipeline, e.g.
pt01.las  ->  pt01_ground.las  &  pt01_nonground.las
pt02.las  ->  pt02_ground.las  &  pt02_nonground.las
...

Thank you very much
new to pdal and first time posting issue, if anything is unclear please inform me

May Chang

**Comment by abellgithub** [comment]
Looks like you need a space after "readers.las" before "--"

**Comment by May7331** [comment]
Thank you @abellgithub It works fine! But wondering why it's missing some of the .las files. I have 48 files, but it seems like only 19 of them gone through the pipeline. I've tried to work on single file each time with the same json code, and it sure does filter out the ground. Not knowing why some of them are missing while looping the directory > <
These are the files that succeeded in filtering (19/48) :
![image](https://user-images.githubusercontent.com/54517878/100971542-1f251580-3572-11eb-981f-aea5c9a9eb34.png)

**Comment by abellgithub** [comment]
Sorry, but I have no way of knowing. You'll have to trace through the process.
