### ISSUE TITLE
Filtering extra.dim issue with writers.las

### ISSUE THREAD

**Issue by GGuidiRontani** [PDAL/PDAL#3312]
Hello,
I'm facing an issue while compressing a bunch of LAS to LAZ with PDAL 2.2.0 in Conda on Win10.

My natives LAS have 3 extra dimensions : one with infrared data I want to keep, and two empties I'd like to erase. 
I used --writers.las.extra_dims Infrared=uint16 to preserve the IR dimension and skip the others but, at the end, the two unexpected extra dimensions are still presents.

Here is the command I used :
pdal translate --writers.las.forward=header --writers.las.compression=laszip --writers.las.a_srs=EPSG:2154 --writers.las.scale_x=0.01 --writers.las.scale_y=0.01 --writers.las.scale_z=0.01 --writers.las.extra_dims Infrared=uint16 --writers.las.discard_high_return_numbers=true "input.las" "output.laz"

Just in case, I don't use dataformat_id cause my data are not strictly encoded in any point data record format from 6. It returns the error (pdal translate readers.las Error) Global encoding WKT flag not set for point format 6 - 10.

Thanx by advance.
Gabriel

**Comment by GGuidiRontani** [comment]
With pdal translate --verbose=Info "input.las" "ouput.laz", my extra dims are skiped. Also, return number, number of returns and scan angle rank are roughly modified.
It sent you a link on your gmail adress to download my input.

**Comment by abellgithub** [comment]
I'm not able to recreate this behavior. The output of the LAZ file on my system shows:
```
variable length header record 1 of 3:
  reserved             0
  user ID              'LASF_Spec'
  record ID            4
  length after header  192
  description          'Extra Bytes Record'
    Extra Byte Descriptions
      data type: 3 (unsigned short), name "Infrared", description: "Infrared", scale: 1 (not set), offset: 0 (not set)
```

**Comment by GGuidiRontani** [comment]
You mean you manage to preserve any extra dim except IR ? Did you also used pdal translate --verbose=Info "input.las" "ouput.laz" ?

**Comment by abellgithub** [comment]
I'm sorry, but I don't understand your question, or maybe the issue in general. Perhaps you can state more precisely what you mean when you say "I used --writers.las.extra_dims Infrared=uint16 to preserve the IR dimension and skip the others but, at the end, the two unexpected extra dimensions are still presents."

When running the command you provided on the input you provided, the only extra dimension that was written was `Infrared`, as shown by the output above.

**Comment by GGuidiRontani** [comment]
Sorry for the misunderstanding.
In order to rationally store data I'd like to convert LAS to LAZ and, at the same time, avoid saving two empties dims (ScanChannel and ClassFlags).

Here is the return of pdal info --summary on the LAS I sent you. If I get it right, regarding to LAZ 1.4 specs, NIR dimension is stored as Infrared and, ScanChannel and ClassFlags doesn't belong to the regular specs.
(pdal info readers.las Error) Global encoding WKT flag not set for point format 6 - 10.        
{                                                                                              
  ....                                                                                         
    "dimensions": "X, Y, Z, Intensity, ReturnNumber, NumberOfReturns, ScanDirectionFlag, EdgeOf
FlightLine, Classification, ScanAngleRank, UserData, PointSourceId, GpsTime, Red, Green, Blue, 
Infrared, ScanChannel, ClassFlags",                                                            
    "num_points": 12359425                                                                     
  }                                                                                            
}

With --writers.las.extra_dims Infrared=uint16, Infrared, ScanChannel and ClassFlags dims are both erased. Works for me for ScanChannel and ClassFlags, but not for Infrared, the one I want to save.
With --writers.las.forward=header  and --writers.las.extra_dims Infrared=uint16, the three are save.

Might it be a problem in the natives data, a misuse of translation options or a bug ?

**Comment by abellgithub** [comment]
I think you misunderstand the LAS format. You can't eliminate `ScanChannel`, `ClassFlags` or `Infrared`. They are ALL part of the 1.4 LAS spec for data format 8, which is what you're using.  When you ask for `Infrared` to be stored as an extra dimension, you're actually storing a copy of the one that's already part of the point record.  If what you're trying to do is to set the *values* of these fields to zero, you'll have to use `filters.assign`.

If that's not what you're trying to do, I don't understand, because you can't eliminate `ClassFlags`, `ScanChannel` or `Infrared` from LAS output when using data format 8 as they're part of the specification.

**Comment by GGuidiRontani** [comment]
Dammed it, you're right !
Scanner Channel = ScanChannel, Classification Flags = ClassFlags and Infrared = NIR. So nothing like extra dimensions... At least this thing is clearer in my mind now. 
Sorry to bother you with it none-issue. Thanx !
