### ISSUE TITLE
PDAL translate not erroring on GDAL failure

### ISSUE THREAD

**Issue by EvertEt** [PDAL/PDAL#3316]
**Describe the bug**
Whenever GDAL fails to reproject, PDAL will just output a 0 point las instead. 
```
$ pdal translate -i in.las -o out.las -f filters.reprojection --filters.reprojection.out_srs=ENGCRS["unnamed",EDATUM[""],CS[Cartesian,2],AXIS["easting",east,ORDER[1],LENGTHUNIT["metre",1,ID["EPSG",9001]]],AXIS["northing",north,ORDER[2],LENGTHUNIT["metre",1,ID["EPSG",9001]]]] 
```
Logs the following and exits with status code 0.
```
(pdal translate Error) GDAL failure (6) Cannot find coordinate operations from 
...
(pdal translate writers.las Debug) Wrote 0 points to the LAS file
```

**Expected behavior**
The call should fail and return a non-zero status code.

**System/installation information:**
PDAL 2.1 on Ubuntu 18.04 and PDAL 2.2 on MacOS 10.15

```
pdal 2.2.0 (git-version: Release)
```

**Comment by abellgithub** [comment]
There is no "call". You're running a program. If you are using the PDAL API, it is possible to determine which points couldn't be projected.

There are cases where reprojection may fail for some points and not others. The behavior you note is not new and not unreasonable, IMO.

**Comment by EvertEt** [comment]
Thank you for your answer.

By call I meant invocation of pdal, and it returns 0 which indicates success which is confusing to me.
If this behaviour is wanted, maybe we could add a flag that would change the behaviour here?

>There are cases where reprojection may fail for some points and not others.

Erroring when none have succeeded, would that be acceptable?

Do you have any proposals for how I can catch or notice this happening outside of PDAL as a workaround??

**Comment by abellgithub** [comment]
If you wanted to add an option to `filters.reprojection` to throw in the case of an error, that seems fine and I'd support it.

**Comment by EvertEt** [comment]
Sadly I am not experienced in C++ thus I cannot help with creating this feature myself.

For others ending up here, I currently work around it with the following Python code checking the stderr:
```
if "GDAL failure" in output and "Wrote 0 points" in output:
    raise Exception("Error in reprojection")
```

**Comment by EvertEt** [comment]
Many thanks @abellgithub ! Is there a fixed release timeline for PDAL to check when this would be included in a published version?

**Comment by abellgithub** [comment]
Not at this time.
