### ISSUE TITLE
Poor LAS point format error.

### ISSUE THREAD

**Issue by abellgithub** [PDAL/PDAL#3324]
If a LAS point format is incompatible with a LAS version, the error is "Unsupported LAS output point format: <>", which is not terribly helpful or descriptive.

**Comment by dbrookes96** [comment]
Maybe not related but could also be nice to prefix LASzip errors thrown from LasReader::handleLaszip to help indicate the origin of the error is from LASzip. 

We had a 5GB .laz file that was outputting the error "readers.las: reading point 164070284 of 456480750 total points". That error comes from laszip_read_point. fyi I think what happened here was the user just running out of memory when not streaming.

**Comment by hobu** [comment]
> Maybe not related but could also be nice to prefix LASzip errors thrown from LasReader::handleLaszip to help indicate the origin of the error is from LASzip.

Please provide a PR implementing this and we will review.
