### ISSUE TITLE
Feature Request: SLPK Writer

### ISSUE THREAD

**Issue by mgg-scudnet** [PDAL/PDAL#3335]
Hi there,

The mesh generating capability of PDAL would be an awesome method to write SLPK mesh surfaces for use in Esri products. Would this be something you could consider including?
Regards,
Marc

**Comment by hobu** [comment]
There isn't an I3S writer at this time, so that would have to be developed to do what you are requesting. If a contributor provided this as a pull request, we would likely merge it if it also provided tests and worked on all three major platforms that PDAL supports.
