### ISSUE TITLE
cmake error about absl

### ISSUE THREAD

**Issue by frank0123** [PDAL/PDAL#3349]
cmake -G Ninja ..

CMake Error at cmake/gtest.cmake:17 (target_link_libraries):
  Attempt to add link library "absl::algorithm" to target "gtest" which is
  not built in this directory.
Call Stack (most recent call first):
  CMakeLists.txt:184 (include)

CMake Error at cmake/gtest.cmake:17 (target_link_libraries):
  Attempt to add link library "absl::base" to target "gtest" which is not
  built in this directory.
Call Stack (most recent call first):
  CMakeLists.txt:184 (include)

CMake Error at cmake/gtest.cmake:17 (target_link_libraries):
  Attempt to add link library "absl::debugging" to target "gtest" which is
  not built in this directory.
Call Stack (most recent call first):
  CMakeLists.txt:184 (include)

CMake Error at cmake/gtest.cmake:17 (target_link_libraries):
  Attempt to add link library "absl::numeric" to target "gtest" which is not
  built in this directory.
Call Stack (most recent call first):
  CMakeLists.txt:184 (include)

CMake Error at cmake/gtest.cmake:17 (target_link_libraries):
  Attempt to add link library "absl::strings" to target "gtest" which is not
  built in this directory.
Call Stack (most recent call first):
  CMakeLists.txt:184 (include)

CMake Error at cmake/gtest.cmake:17 (target_link_libraries):
  Attempt to add link library "absl::utility" to target "gtest" which is not
  built in this directory.
Call Stack (most recent call first):
  CMakeLists.txt:184 (include)

CMake Error at cmake/gtest.cmake:17 (target_link_libraries):
  Attempt to add link library "absl::failure_signal_handler" to target
  "gtest" which is not built in this directory.
Call Stack (most recent call first):
  CMakeLists.txt:184 (include)

-- Could NOT find LIBEXECINFO (missing: LIBEXECINFO_LIBRARY) 
-- The following features have been enabled:

 * PostgreSQL PointCloud plugin, read/write PostgreSQL PointCloud objects
 * E57 plugin, read/write data to and from e57 format
 * Unit tests, PDAL unit tests

-- The following OPTIONAL packages have been found:

 * ZSTD
   General compression support
 * LibXml2
 * PkgConfig
 * OpenSSL (required version >= 1.1)
 * PythonInterp
 * absl
 * Libunwind

-- The following RECOMMENDED packages have been found:

 * LASzip (required version >= 3.1)
   Provides LASzip compression
   Provides LASzip compression

-- The following REQUIRED packages have been found:

 * GDAL (required version >= 2.2.0)
   Provides general purpose raster, vector, and reference system support
 * GeoTIFF
 * ZLIB
   Compression support in BPF
 * CURL
 * PostgreSQL
 * XercesC
 * Threads, The thread library of the system

-- The following features have been disabled:

 * Bash completion, completion for PDAL command line
 * CPD plugin, Coherent Point Drift (CPD) computes rigid or nonrigid transformations between point sets
 * I3S plugin, Read from a I3S server or from a SLPK file
 * Icebridge plugin, read data in the Icebridge format
 * HDF plugin, read data in the HDF format
 * Matlab plugin, write data to a .mat file
 * MrSID plugin, read data in the MrSID format
 * NITF plugin, read/write LAS data wrapped in NITF
 * OpenSceneGraph plugin, read/write OpenSceneGraph objects
 * Oracle OCI plugin, Read/write point clould patches to Oracle
 * RiVLib plugin, read data in the RXP format
 * rdblib plugin, read data in the RDB format
 * MBIO plugin, add features that depend on MBIO
 * FBX plugin, add features that depend on FBX
 * TEASER++ plugin, TEASER++ computes transformations between point sets
 * TileDB plugin, read/write data from TileDB

-- The following OPTIONAL packages have not been found:

 * Libexecinfo

-- Configuring incomplete, errors occurred!

ENV: Ubuntu 18.05  abseil_cpp  

What's wrong with absl?

**Comment by abellgithub** [comment]
What is your cmake version?

**Comment by abellgithub** [comment]
You can just remove all the abseil-related stuff in gtest.cmake and should be good to build for now.

**Comment by frank0123** [comment]
@abellgithub thanks! After upgrade my cmake-3.12.0 to 3.13.0，the problem solved!

**Comment by hobu** [comment]
> After upgrade my cmake-3.12.0 to 3.13.0，the problem solved!

3.13.0 was released in Nov 2018. That's a maybe a bit too recent, and we maybe should update the configuration to support and older cmake. Maybe we should just check the cmake version and shut the abseil stuff off if cmake version is too old. It is quite special and just a developer thing.
