### ISSUE TITLE
PDAL 2.1 LAZ 1.4 output causes EVLR offset error.

### ISSUE THREAD

**Issue by ntr-808** [PDAL/PDAL#3350]
I am running PDAL 2.0.1 on Ubuntu 20.04.
My colleague is running PDAL 2.1 on Ubuntu 20.

We use the output voxel downsample clouds of the following pipeline in a rust application that reads the LAZ headers for bounding box information using the `las` crate.

```
$ pdal pipeline pipeline.json
```

  
```
[
    "qcat-elvis-clip.laz",
    {
        "type": "filters.voxelcenternearestneighbor",
        "cell": 0.25
    },
    {
        "type": "writers.las",
        "scale_x": "0.001",
        "scale_y": "0.001",
        "scale_z": "0.001",
        "offset_x": "auto",
        "offset_y": "auto",
        "offset_z": "auto",

        "filename": "qcat-elvis-clip.voxel.laz",

        "minor_version": 4,
        "forward": "all",
        "extra_dims": "all"
    },
]
```

In my setup this works correctly, however with PDAL 2.1 the headers fail to parse with the error:

```
Error: offset to the start of the evlrs is too small: 2629817
```

However, if we remove the `minor_version` `forward` `extra_dims` fields from the pipeline, the output file is read successfully.
(Edit: I'm told it is specifically setting the laz minor version to 4)

Possibly related to #3348 ?
This file in particular is originally from https://elevation.fsdf.org.au/ as a las that has been compressed to laz with PDAL 2.2 when I was still building from source. The issue also occurs with other laz source files.

Files in question: https://www.dropbox.com/s/pb63f8nwrviiw8l/pdal-issue.zip?dl=0

**Expected behavior**
The output .laz header should be parsed successfully.

**System/installation information:**
Please provide information on your PDAL version (`pdal --version`) and system (e.g., `uname -a` or `ver`).

```
Linux obsidian 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

```
pdal 2.0.1 (git-version: Release)
```

**Comment by abellgithub** [comment]
I don't understand the problem you're trying to convey. What command are you using that generates the error in question? I don't believe the error message you're seeing is coming from PDAL.

**Comment by ntr-808** [comment]
Sorry @abellgithub I was getting mixed signals, your fix in #2824 caused us to get errors downstream as the EVLR offset was previously missing.

The root cause of our issue was that `las-rs` interpreted a nonzero `Start of First Extended Variable Length Record` in the header as indicative of there being EVLRs present, even though `Number of Extended Variable Length Records` was set to 0.
In this case PDAL 2.1 sets the `Start of First Extended Variable Length Record` value to be the end of the point data.

I am interested to get your thoughts on what the correct interpretation of such a value should be as the [LAS spec](http://www.asprs.org/wp-content/uploads/2019/07/LAS_1_4_r15.pdf#subsection.0.2.4) makes no recommendations of its own.

**Comment by abellgithub** [comment]
I honestly didn't think about this. It should probably be set to zero but I should amend the PR I already have on the LAS spec to clarify this. Really, though, it shouldn't matter. That field should be ignored if there are no EVLRs, IMO.

**Comment by ntr-808** [comment]
I agree, I have submitted a patch to `las-rs` that requires the number of EVLRs to be nonzero before attempting to parse their values.
