### ISSUE TITLE
ninja: Ilvis2MetadataReader.cpp:405:5: error: ‘CPLFree’ was not declared in this scope?

### ISSUE THREAD

**Issue by frank0123** [PDAL/PDAL#3351]
This is a strange problem. I'm not compile the PDAL by ubuntu docker or missing deps, so I had encountered this problem is werid. Some of you who solved this error by changed the version of gdal, so after had installed gdal by:

`apt install libgdal-dev`

I had compiled source code from github/gdal.git, now there're three .so in my system:

```
/usr/lib/libgdal.so.20.3.2
/usr/lib/ogdi/libgdal.so
/usr/local/lib/libgdal.so.27.0.0
```

If it's not the gdal problem, where's the problem come from?

**Comment by frank0123** [comment]
```
gdalinfo --version
GDAL 3.2.0dev-813cc2d678-dirty, released 2020/07/17
```

**Comment by abellgithub** [comment]
You'll have to provide a compile/link line in order for someone to help you.

**Comment by frank0123** [comment]
```
ninja
[87/463] Building CXX object CMakeFiles/pdal_base.dir/io/Ilvis2MetadataReader.cpp.o
FAILED: CMakeFiles/pdal_base.dir/io/Ilvis2MetadataReader.cpp.o 
/usr/bin/c++  -DUNIX -Dpdal_base_EXPORTS -I../vendor/gtest/include -I../vendor/gtest -I../ -Iinclude -I../vendor -I../vendor/eigen -I../vendor/pdalboost -I../vendor/nlohmann -I/usr/include/geotiff -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include/libxml2 -I/usr/include/gdal -fPIC   -Wno-implicit-fallthrough -Wno-int-in-bool-context -Wno-dangling-else -Wno-noexcept-type -Wall -Wextra -Wpointer-arith -Wcast-align -Wcast-qual -Wno-error=parentheses -Wno-error=cast-qual -Wredundant-decls -Wno-unused-parameter -Wno-unused-variable -Wno-long-long -Wno-unknown-pragmas -Wno-deprecated-declarations -std=c++11 -MD -MT CMakeFiles/pdal_base.dir/io/Ilvis2MetadataReader.cpp.o -MF CMakeFiles/pdal_base.dir/io/Ilvis2MetadataReader.cpp.o.d -o CMakeFiles/pdal_base.dir/io/Ilvis2MetadataReader.cpp.o -c ../io/Ilvis2MetadataReader.cpp
../io/Ilvis2MetadataReader.cpp: In member function ‘void pdal::Ilvis2MetadataReader::parseGPolygon(xmlNodePtr, pdal::MetadataNode*)’:
../io/Ilvis2MetadataReader.cpp:402:5: error: ‘CPLFree’ was not declared in this scope
     CPLFree(polyStr);
     ^~~~~~~
../io/Ilvis2MetadataReader.cpp:402:5: note: suggested alternative: ‘xmlFree’
     CPLFree(polyStr);
     ^~~~~~~
     xmlFree
[89/463] Building CXX object CMakeFiles/pdal_base.dir/io/GltfWriter.cpp.o
ninja: build stopped: subcommand failed.
```

**Comment by abellgithub** [comment]
Something is strange with you GDAL installation. The file you're having trouble with includes `ogr_geometry.h`, which should provide a reference to `CPLFree`.

**Comment by pvazteixeira** [comment]
Ran into this issue when building pdal (`tags/2.2.0`) on Ubuntu 18.04:

```
/home/pvt/workspace/libraries/PDAL/io/Ilvis2MetadataReader.cpp: In member function ‘void pdal::Ilvis2MetadataReader::parseGPolygon(xmlNodePtr, pdal::MetadataNode*)’:
/home/pvt/workspace/libraries/PDAL/io/Ilvis2MetadataReader.cpp:402:5: error: ‘CPLFree’ was not declared in this scope
     CPLFree(polyStr);
     ^~~~~~~
```

I have installed gdal through apt, version 2.2.3. Unfortunately, updating gdal isn't trivial as a newer version is not available from apt, and building from source requires building and installing `PROJ` as well (latest version from apt is 4.9.3 and gdal requires at least 6.

Is gdal 2.2.3 too old to build pdal 2.2.0? If so, can the CMake config be modified accordingly?

**Comment by abellgithub** [comment]
This is strange. We test with Ubuntu 18, so something must have changed
recently. If you want to build on Unix, you should be able to simply
replace CPLFree with free and build in release mode. Or you can determine
the GDAL header file on your system that includes CPLFree and include that
in the file that's giving you trouble.

You can also just comment that line out.

I'll try to recreate next week to see what's changed in the GDAL that
they're providing on Ubuntu 18.

**Comment by frank0123** [comment]
re-build gdal from [github](https://github.com/OSGeo/gdal), can't find symbol **CPLFree** from [ogr_geometry.h](https://github.com/OSGeo/gdal/blob/master/gdal/ogr/ogr_geometry.h).

**Comment by pvazteixeira** [comment]
same here: `CPLFree` is not present `ogr_geometry.h` in the apt-provided gdal (version 2.2.3)

**Comment by abellgithub** [comment]
Maybe someone would like to make a PR that includes cpl_conv.h?

**Comment by pvazteixeira** [comment]
Thanks! `CPLFree` does show up on gdal 2.2.3 - line 81 in `/usr/include/gdal/cpl_conv.h`:

```c
/** Alias of VSIFree() */
#define CPLFree VSIFree
```

adding it as an include to `io/Ilvis2MetadataReader.cpp` and `pdal/Geometry.cpp`  fixes the issue with `CPLFree` on both `2.2.0` and `2.2-maintenance`. 

As for the PR - #3263 fixes this (and the remaining problems in the build) - could you please reopen it and merge?

**Comment by StevenBunkley** [comment]
I compiled with `make` instead of `Ninja` and it completed without error.

**Comment by hobu** [comment]
PDAL 2.3+ will [require GDAL 3.0](https://github.com/PDAL/PDAL/issues/3428), which should no longer have this issue. Please reopen if this isn't the case.
