### ISSUE TITLE
Linking CXX executable bin/pdal_info_test ld: warning: libzstd.so.1, needed by libgdal.so.20, not found

### ISSUE THREAD

**Issue by philwilkes** [PDAL/PDAL#3352]
**Describe the bug**

Trying to install pdal from source following these [instructions](https://pdal.io/development/compilation/unix.html)

I do not have root privileges so am installing dependencies with conda, after some trial and error this is my create environment

`conda create -n pdal -c conda-forge/label/gcc7  -c creditx gdal=2 ninja cmake=3.5 gcc-7 zstd`

cmake 3.5.0, gcc 7.1.0 and gdal 2.3.2

When I run `cmake -G Ninja ..` from `build`

-- The CXX compiler identification is GNU 7.1.0
-- The C compiler identification is GNU 7.1.0
-- Check for working CXX compiler using: Ninja
-- Check for working CXX compiler using: Ninja -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler using: Ninja
-- Check for working C compiler using: Ninja -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found GDAL: /home/ucfaptv/opt/miniconda/envs/rxp6/lib/libgdal.so (Required is at least version "2.2.0") 
-- Found GeoTIFF: /home/ucfaptv/opt/miniconda/envs/rxp6/lib/libgeotiff.so  
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found ZLIB: /home/ucfaptv/opt/miniconda/envs/rxp6/lib/libz.so (found version "1.2.11") 
-- Found LibXml2: /usr/lib64/libxml2.so (found version "2.9.1") 
-- Found CURL: /home/ucfaptv/opt/miniconda/envs/rxp6/lib/libcurl.so (found version "7.63.0") 
-- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR: Found unsuitable version "1.0.2k", but required is at least "1.1" (found /usr/lib64/libssl.so;/usr/lib64/libcrypto.so)
OpenSSL NOT found - `export OPENSSL_ROOT_DIR=___`
Google storage IO will not be available
-- Found PostgreSQL: /home/ucfaptv/opt/miniconda/envs/rxp6/include  
-- Found PythonInterp: /home/ucfaptv/opt/miniconda/envs/rxp6/bin/python (found version "3.6.6") 
-- Could NOT find LIBEXECINFO (missing:  LIBEXECINFO_LIBRARY) 
-- Could NOT find LIBUNWIND (missing:  LIBUNWIND_LIBRARY LIBUNWIND_INCLUDE_DIR) 
-- 
-- The following features have been enabled:

 * PostgreSQL PointCloud plugin , read/write PostgreSQL PointCloud objects
 * Unit tests , PDAL unit tests

-- The following OPTIONAL packages have been found:

 * ZSTD
   General compression support
 * LibXml2
 * PkgConfig
 * PythonInterp

-- The following REQUIRED packages have been found:

 * GDAL (required version >= 2.2.0)
   Provides general purpose raster, vector, and reference system support
 * GeoTIFF
 * ZLIB
   Compression support in BPF
 * CURL
 * PostgreSQL
 * Threads , The thread library of the system

-- The following features have been disabled:

 * Bash completion , completion for PDAL command line
 * CPD plugin , Coherent Point Drift (CPD) computes rigid or nonrigid transformations between point sets
 * I3S plugin , Read from a I3S server or from a SLPK file
 * Icebridge plugin , read data in the Icebridge format
 * HDF plugin , read data in the HDF format
 * Matlab plugin , write data to a .mat file
 * MrSID plugin , read data in the MrSID format
 * NITF plugin , read/write LAS data wrapped in NITF
 * OpenSceneGraph plugin , read/write OpenSceneGraph objects
 * Oracle OCI plugin , Read/write point clould patches to Oracle
 * RiVLib plugin , read data in the RXP format
 * rdblib plugin , read data in the RDB format
 * MBIO plugin , add features that depend on MBIO
 * FBX plugin , add features that depend on FBX
 * TEASER++ plugin , TEASER++ computes transformations between point sets
 * TileDB plugin , read/write data from TileDB
 * E57 plugin , read/write data to and from e57 format

-- The following OPTIONAL packages have not been found:

 * OpenSSL (required version >= 1.1)
 * absl
 * Libexecinfo
 * Libunwind

-- The following RECOMMENDED packages have not been found:

 * LASzip (required version >= 3.1)
   Provides LASzip compression

-- Configuring done
-- Generating done
-- Build files have been written to: /home/ucfaptv/opt/PDAL/build

Looks OK to me?

Then when I run `ninja` everything seems ok until:

> [248/479] Linking CXX executable bin/pdal_app_test
> /home/ucfaptv/opt/miniconda/bin/ld: warning: libzstd.so.1, needed by /home/ucfaptv/opt/miniconda/lib/libgdal.so.20, not found (try using -rpath or -rpath-link)

And this repeats until the compilation finishes

Then

```
$ ls lib/libpdalcpp*
lib/libpdalcpp.8.dylib
lib/libpdalcpp.dylib
lib/libpdalcpp.9.0.0.dylib
```
returns nothing

**Comment by abellgithub** [comment]
Something is very confused with your environment, as cmake finds GDAL using this path:

/home/ucfaptv/opt/miniconda/envs/rxp6/lib/libgdal.so

but when linking the tests uses this one:

/home/ucfaptv/opt/miniconda/envs/rxp6/lib/libgdal.so

**Comment by philwilkes** [comment]
Thanks @abellgithub 

Cleaned up a my base conda environment (uninstalled GDAL - how did it get there!) and that did it ... after a few more tweaks!
