### ISSUE TITLE
Implement parallel processing for filters which use batch mode processing

### ISSUE THREAD

**Issue by whereskenneth** [PDAL/PDAL#3358]
Although not possible for streaming filters, the ability to utilize concurrency for batch processing point clouds is a much needed feature in end-user applications where quick turnaround is desired.

Using the STL in C+11, in particular the `<thread>` library, this can be easily implemented without adding additional dependencies to the codebase. 

There are two main classes of parallel problems that I've recognized - deterministic and non-deterministic time. The deterministic time problems are fairly easy to parallelize - the work is distributed among available threads evenly. In non-deterministic time, the time to perform the calculation is dependent on the dataset. This occurs notably in nearest neighbor searches, of which a sizeable amount of point cloud algorithms rely on. In this case, a worker queue is preferable for two reasons. 
  
1.  A worker thread can grab a new point to work on from a queue as it finishes it's calculations.
2. K-d tree index search functions are const, so no internal parameters are changed during thread execution, and should be thread safe (!!!)

One scheme which can be used is a queue - infinite loop scheme, where an infinite loop in a worker thread 

1. Locks a queue mutex, and pops a point to process from a deque, or breaks if none left.
2. Performs some expensive calculation.
3. Locks an output mutex, and stores the results of the expensive calcuation.

The general scheme in C++ would look like this.

```
#include <deque>
#include <numeric>
#include <thread>

size_t point_count;
std::deque<size_t> queue(point_count);
std::iota(queue.begin(), queue.end(), 0);

// Or some other initialization scheme.

std::mutex queue_lock, write_lock;

unsigned int num_threads;
std::vector<std::thread> thread_pool;
thread_pool.reserve(num_threads);

for (size_t i = 0; i < num_threads; i++) {
  thread_pool.emplace_back([&] {
    for (;;) {
      size_t point_to_process;
      {
        std::lock_guard<std::mutex> lock(queue_lock);
        if (queue.empty())
          break;
        point_to_process = queue.front();
        queue.pop_front();
      }
      
      Result r = expensive_calculation(point_to_process);

      {
        std::lock_guard<std::mutex> lock(write_lock);
        store_result(r);
      }
    }
  });
}
for (std::thread &t : thread_pool) {
  if (t.joinable())
    t.join();
}
```

One downside to this approach is the extra overhead added by mutex lock acquisition/freeing in the scope blocks, which could add some additional time to single threaded processing. This should not be too noticeable as there should be no contention for the mutexes. Generally, the more expensive the calculation, the lower the mutex contention will be, which should hold true for neighbor searches, as they are quite expensive.

Another downside is the additional code complexity which is unavoidable when implementing concurrency using standard C++, but I believe this scheme is relatively simple to follow, and is preferable to adding additional dependencies such as OpenMP or TBB.

**Comment by abellgithub** [comment]
There are examples of threading in some filters.  Usually the points are broken up into chunks and assigned to as many threads as are specified, rather than dealing with a separate thread for each point algorithm execution.

We also have https://github.com/PDAL/PDAL/blob/master/pdal/util/ThreadPool.hpp

**Comment by whereskenneth** [comment]
I couldn't actually find any uses of ThreadPool in any filters in master. Is it possible they exist in some other branch?

**Comment by abellgithub** [comment]
It's not used in the filters, but it's elsewhere in the codebase. It's simple to use.
