### ISSUE TITLE
Small bug in iowa-entwine tutorial?

### ISSUE THREAD

**Issue by gsakkis** [PDAL/PDAL#3365]
Unless I am missing something, shouldn't [this line](https://github.com/PDAL/PDAL/blob/master/doc/tutorial/iowa.json#L42) be `"inputs": [ "classify" ]` in the [Reading data from EPT](https://pdal.io/tutorial/iowa-entwine.html) tutorial? Also the [gdal](https://github.com/PDAL/PDAL/blob/master/doc/images/pipeline-example-writers.gdal.png) and [las](https://github.com/PDAL/PDAL/blob/master/doc/images/pipeline-example-writers.las.png) writer images are not quite in sync with the pipeline json.

**Comment by hobu** [comment]
Please make a pull request fixing these issues and we can merge it.

**Comment by hobu** [comment]
Small fix added at ea0ff391723d9920ab768f7e461fab709909e1e9 but the fix in this PR is not correct. The LAS writer needs to connect to the ``writers.gdal`` for things to work. If the pictures are incorrect, please reopen.
