### ISSUE TITLE
Bad file name in SpatialReferenceTest

### ISSUE THREAD

**Issue by aaronyonas** [PDAL/PDAL#3370]
TEST(SpatialReferenceTest, set_srs) references `Support::datapath("ilvis2/ILVIS_TEST_FILE.txt"));`.
But `ilvis2/ILVIS_TEST_FILE.txt` does not exist.

The correct file name appears to be [ilvis2/ILVIS2_TEST_FILE.TXT](https://github.com/PDAL/PDAL/blob/master/test/data/ilvis2/ILVIS2_TEST_FILE.TXT).

I'm not sure how this test was passing for everyone.

**Comment by abellgithub** [comment]
Thanks.

This is probably a missing header file, but I don't know for sure and it seems strage. I'll investigate.

**Comment by abellgithub** [comment]
This is just a bad test (and the ilvis2 reader is kind of bad here too). Did you get an error that led to this finding?

**Comment by aaronyonas** [comment]
Because our build system requires explicitly declaring the input files for each unit test, this showed up for me as a build failure.

**Comment by abellgithub** [comment]
I just deleted the test as it does nothing valuable: https://github.com/PDAL/PDAL/commit/59e2bad86071aa9a7bdcb86d627442c06e52f127
