### ISSUE TITLE
Feature request: Make Arbiter support optional

### ISSUE THREAD

**Issue by aaronyonas** [PDAL/PDAL#3372]
In some security sensitive contexts, allowing access to remote resources is a deal breaker.  If would be great if PDAL's dependence on Arbiter could be controlled at configuration/compile time, as with PDAL's other optional features.
Please consider adding `PDAL_HAVE_ARBITER`.

**Comment by hobu** [comment]
> Please consider adding ``PDAL_HAVE_ARBITER``.

We would consider merging such a patch. It was there at one time but maintenance of it was a hassle when it was basically never used.

**Comment by abellgithub** [comment]
I think this needs discussion. I'm trying to understand why this kind of
security should be at the application/API level and if there are better
ways to deal.

Indeed, it was a hassle.

**Comment by aaronyonas** [comment]
> Indeed, it was a hassle.

It would help to understand what led to the complexity and hassle.  I don't want to create a burden.

> why this kind of security should be at the application/API level 

It's a compile-time issue: I doubt I can bring the Arbiter library into our code base.

One possible solution: I could write a class that handles local files itself and (if #defined) delegates remote files to Arbiter. 
 PDALUtils.cpp already does a lot of that work.

**Comment by hobu** [comment]
> It would help to understand what led to the complexity and hassle. I don't want to create a burden.

* To actually test ``ON`` vs. ``OFF`` means doubling our CI footprint. 
* So we didn't, and then an update would happen and it would break the ``OFF` case because we weren't testing it.
* Users would compile with ``OFF`` and complain that remote access didn't work.

What do you guys do in GDAL's situation? Could you instead link to a libcurl library that no-op's and fails all the methods?

**Comment by aaronyonas** [comment]
Ok, let's not double the testing footprint. 

What if I created a "pinch point?"  I'm thinking of a factory function that would instantiate either a remote file handler or a local file handler.  In our fork of the code, we'd just comment out the "if remote" and verify that the tests we need still work. 

(I don't know what we do in GDAL, but @schwehr probably does.)

If the consensus settles on leaving PDAL as is, the fallback for me would be to write, in our fork, a local-file-only implementation of the Arbiter interface and link to that.

**Comment by hobu** [comment]
> What if I created a "pinch point?" I'm thinking of a factory function that would instantiate either a remote file handler or a local file handler. In our fork of the code, we'd just comment out the "if remote" and verify that the tests we need still work.

I think we're supportive as long as we don't sprinkle ``#ifdef PDAL_HAVE_ARBITER`` all over the codebase.

**Comment by aaronyonas** [comment]
Sounds good.  I'll experiment a bit and see if I can come up with something clean.

**Comment by schwehr** [comment]
I can share a bit of what we do about GDAL.  This is all an aggregate of things that are all already public knowledge, but you'd have to look at quite a few sources.

Most of this is never noticed by developers inside of Google.

We don't enable curl or any other of the networking code.  The list of libraries that GDAL depends on is less than 15 (libtiff, expat, libz, geos, proj, libjpeg,... but no curl).  I've also removed the gdal client server code and a few other places that had networking bits.  Data files for GDAL are built into the binary and written into /vsimem when first used.  User facing code that uses GDAL runs GDAL in a sandbox that uses the vsi layer to pass blocks of files across the sandbox boundary using the sandboxes' API.  The results are written the same way back through the sandbox wall.  If any networking code does still exist hidden away inside GDAL gets run, there will be a sandbox violation triggered and the entire sandbox is immediately halted.  The overall parent process lives in a walled garden without direct access to any disk.  Networking is handled by a process outside of the jail the parent process is in.  And even that separate process can't talk to anything outside of the datacenters.

Unit testing is done on isolated environments created for each test and data is accessed from a read-only [CAS](https://en.wikipedia.org/wiki/Content-addressable_storage) filesystem.  Calls like `readlink` generally fail to find what they were looking for as every data file is in its own directory.  We run the unit tests many times an hour and several times a day, they are run in asan and msan modes.  As a part of those tests, the fuzzers run a large corpus of files to make sure there are no regressions... a large portion of those files are corrupt/garbage input that exercise specific code paths.  

Our BUILD file (e.g. bazel) only has:

```
egrep '  "[-]DHAVE' third_party/gdal/BUILD 
    "-DHAVE_EXPAT",
    "-DHAVE_LIBZ",
    "-DHAVE_GEOS",
    "-DHAVE_MITAB",
    "-DHAVE_LIBJPEG",
```

We don't even have the source to most of the networking code in our local repository (the one big google3 repo):

```
ls -1 third_party/gdal/port/cpl_vsil*.cpp

third_party/gdal/port/cpl_vsil_abstract_archive.cpp
third_party/gdal/port/cpl_vsil_buffered_reader.cpp
third_party/gdal/port/cpl_vsil_cache.cpp
third_party/gdal/port/cpl_vsil.cpp
third_party/gdal/port/cpl_vsil_crypt.cpp
third_party/gdal/port/cpl_vsil_curl.cpp
third_party/gdal/port/cpl_vsil_gzip.cpp
third_party/gdal/port/cpl_vsil_sparsefile.cpp
third_party/gdal/port/cpl_vsil_stdin.cpp
third_party/gdal/port/cpl_vsil_stdout.cpp
third_party/gdal/port/cpl_vsil_subfile.cpp
third_party/gdal/port/cpl_vsil_tar.cpp
third_party/gdal/port/cpl_vsil_unix_stdio_64.cpp
```

Compare that to what GDAL head has:

```
ls -1 gdal/port/cpl_vsil*.cpp
gdal/port/cpl_vsil_abstract_archive.cpp
gdal/port/cpl_vsil_adls.cpp
gdal/port/cpl_vsil_az.cpp
gdal/port/cpl_vsil_buffered_reader.cpp
gdal/port/cpl_vsil_cache.cpp
gdal/port/cpl_vsil.cpp
gdal/port/cpl_vsil_crypt.cpp
gdal/port/cpl_vsil_curl.cpp
gdal/port/cpl_vsil_curl_streaming.cpp
gdal/port/cpl_vsil_gs.cpp
gdal/port/cpl_vsil_gzip.cpp
gdal/port/cpl_vsil_hdfs.cpp
gdal/port/cpl_vsil_oss.cpp
gdal/port/cpl_vsil_plugin.cpp
gdal/port/cpl_vsil_s3.cpp
gdal/port/cpl_vsil_simple.cpp
gdal/port/cpl_vsil_sparsefile.cpp
gdal/port/cpl_vsil_stdin.cpp
gdal/port/cpl_vsil_stdout.cpp
gdal/port/cpl_vsil_subfile.cpp
gdal/port/cpl_vsil_swift.cpp
gdal/port/cpl_vsil_tar.cpp
gdal/port/cpl_vsil_unix_stdio_64.cpp
gdal/port/cpl_vsil_uploadonclose.cpp
gdal/port/cpl_vsil_webhdfs.cpp
gdal/port/cpl_vsil_win32.cpp
```

**Comment by abellgithub** [comment]
Why don't you simply make your own arbiter that does nothing and drop that in? Then you don't have to mess with PDAL at all. There aren't many calls that are actually used. They can just fail.

**Comment by aaronyonas** [comment]
> Why don't you simply make your own arbiter that does nothing and drop that in? Then you don't have to mess with PDAL at all. There aren't many calls that are actually used. They can just fail.

Yes, that's a perfectly good option.  If that's your preference, I'll just go ahead and do that.
