### ISSUE TITLE
PointContextTest.cpp includes nonexistent file PointContext.hpp

### ISSUE THREAD

**Issue by aaronyonas** [PDAL/PDAL#3373]
[test/unit/PointContextTest.cpp](https://github.com/PDAL/PDAL/blob/master/test/unit/PointContextTest.cpp) contains the line `#include <pdal/PointContext.hpp>`. However, that file doesn't appear to exist.

I'm guessing that PointContextTest.cpp is never compiled or run.

**Comment by abellgithub** [comment]
Well that's some old, dead code.

**Comment by aaronyonas** [comment]
Delete PointContextTest.cpp?
