### ISSUE TITLE
laszip version file unsuccessfully searched for in /usr/bin

### ISSUE THREAD

**Issue by kannes** [PDAL/PDAL#3380]
**Describe the bug**
This might be purely PEBKAC but I am trying to compile PDAL from git using the Archlinux AUR recipe https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=pdal-git

It does not manage to find the installed laszip (3.4.3-1):

> 
> -- The following RECOMMENDED packages have not been found:
> 
>  * LASzip (required version >= 3.1)
>    Provides LASzip compression

I do have the following files in my system:

```
/usr/bin/laszip
/usr/include/laszip
/usr/include/laslib/laszip.hpp
/usr/include/laslib/laszip_common_v1.hpp
/usr/include/laslib/laszip_common_v2.hpp
/usr/include/laslib/laszip_common_v3.hpp
/usr/include/laslib/laszip_decompress_selective_v3.hpp
/usr/include/laszip/laszip_api.h
/usr/include/laszip/laszip_api_version.h
/usr/lib/liblaszip.so
/usr/lib/liblaszip.so.8
/usr/lib/liblaszip.so.8.0.5
/usr/lib/liblaszip_api.so
/usr/lib/liblaszip_api.so.8
/usr/lib/liblaszip_api.so.8.0.5
```

I checked what cmake searches via strace -e file and spotted it only trying `/usr/bin/laszip/laszip_api_version.h` for some reason which seems super weird:

```
...
access("/home/user/pdal-git/src/PDAL/cmake/laszip.cmake", R_OK) = 0
newfstatat(AT_FDCWD, "/home/user/pdal-git/src/PDAL/cmake/laszip.cmake", {st_mode=S_IFREG|0644, st_size=1011, ...}, 0) = 0
openat(AT_FDCWD, "/home/user/pdal-git/src/PDAL/cmake/laszip.cmake", O_RDONLY) = 3
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=1011, ...}, AT_EMPTY_PATH) = 0
access("/home/user/pdal-git/src/PDAL/cmake/modules/FindLASzip.cmake", R_OK) = 0
access("/usr/share/cmake-3.19/Modules/FindLASzip.cmake", R_OK) = -1 ENOENT (No such file or directory)
access("/home/user/pdal-git/src/PDAL/cmake/modules/FindLASzip.cmake", R_OK) = 0
newfstatat(AT_FDCWD, "/home/user/pdal-git/src/PDAL/cmake/modules/FindLASzip.cmake", {st_mode=S_IFREG|0644, st_size=3489, ...}, 0) = 0
openat(AT_FDCWD, "/home/user/pdal-git/src/PDAL/cmake/modules/FindLASzip.cmake", O_RDONLY) = 3
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=3489, ...}, AT_EMPTY_PATH) = 0
access("/usr/bin/laszip/laszip_api_version.h", R_OK) = -1 ENOTDIR (Not a directory)
access("/home/hannes/pdal-git/src/PDAL/cmake/threads.cmake", R_OK) = 0
newfstatat(AT_FDCWD, "/home/hannes/pdal-git/src/PDAL/cmake/threads.cmake", {st_mode=S_IFREG|0644, st_size=175, ...}, 0) = 0
...
```

I have no idea how to read that `.cmake` file and why it might end up searching in `/usr/bin` so any help would be appreciated.

**Comment by hobu** [comment]
I think this is a cmake configuration issue. It searches BINDIR. It could certainly be cleaned up. Please open a PR if you run it down and we can merge it.

**Comment by kannes** [comment]
So I took a look at this:

In `FindLASzip.cmake`:

```
FIND_PATH(LASZIP_INCLUDE_DIR
  laszip_api.h
  NAMES laszip
  PATHS
  /usr/include
  /usr/local/include
  ${OSGEO4W_INCLUDE_DIR})
```

searches for `laszip_api.h` in the three paths specified, non-recursively. On my system it is in a subdirectory of `/usr/include/` called `laszip/`so this fails and `LASZIP_INCLUDE_DIR` is not set.

Further down the following lines try to find the sibling `laszip_api_version.h`:

```
SET(LASZIP_VERSION_H "${LASZIP_INCLUDE_DIR}/laszip/laszip_api_version.h")
IF(LASZIP_INCLUDE_DIR AND EXISTS ${LASZIP_VERSION_H})
...
```
It tries to set `LASZIP_VERSION_H` to `"${LASZIP_INCLUDE_DIR}/laszip/laszip_api_version.h"`. So the include dir it could not find because the `laszip_api.h` file is not directly in it and then the path INTO the subdirectory where it and `laszip_api_version.h` are.

My installed laszip is built from https://github.com/archlinux/svntogit-community/blob/packages/laszip/trunk/PKGBUILD, so no custom changes to where the `.h` files go to. 3.4.3 is the latest release from https://github.com/LASzip/LASzip/releases
This suggest that the location of `laszip_api.h` in `/usr/include/laszip/laszip_api.h` is normal and the `FIND_PATH` for `LASZIP_INCLUDE_DIR` doesn't actually ever work anywhere. 🧐🤔🤪

**Comment by kannes** [comment]
I see now that https://github.com/PDAL/PDAL/issues/1774 had the same issue and it seems to be a laszip issue.

(Warm thoughts go out to Martin :heart:)

**Comment by hobu** [comment]
A new laszip release is still possible if I need to do it.

**Comment by hobu** [comment]
This ticket should be resolved by https://github.com/PDAL/PDAL/pull/3675 which embeds laz-perf into PDAL for all LAZ support. PDAL should no longer need an external library for LAZ going forward from 2.4.

**Comment by kannes** [comment]
Thank you very much @hobu!

**Comment by kannes** [comment]
Compiles just fine now! :)
