### ISSUE TITLE
Fails to build with GCC-11

### ISSUE THREAD

**Issue by sebastic** [PDAL/PDAL#3388]
As reported by Matthias Klose in [Debian Bug #984285](https://bugs.debian.org):
> The package fails to build in a test rebuild on at least amd64 with
> gcc-11/g++-11, but succeeds to build with gcc-10/g++-10. The
> severity of this report will be raised before the bookworm release,
> so nothing has to be done for the bullseye release.
>
> The full build log can be found at:
> http://people.debian.org/~doko/logs/20210228/filtered/gcc11/pdal_2.2.0+ds-1_unstable_gcc11.log
> The last lines of the build log are at the end of this report.
>
> To build with GCC 11, either set CC=gcc-11 CXX=g++-11 explicitly,
> or install the gcc, g++, gfortran, ... packages from experimental.
> ```
> apt-get -t=experimental install g++  
> ```
> Common build failures are new warnings resulting in build failures with
> -Werror turned on, or new/dropped symbols in Debian symbols files.
> For other C/C++ related build failures see the porting guide at
> http://gcc.gnu.org/gcc-11/porting_to.html
>
> GCC 11 defaults to the GNU++17 standard.  If your package installs
> header files in /usr/include, please don't work around C++17 issues
> by choosing a lower C++ standard for the package build, but fix these
> issues to build with the C++17 standard.

From the buildlog:
```
/<<PKGBUILDDIR>>/plugins/e57/libE57Format/src/E57XmlParser.cpp: In member function â€˜virtual XMLSize_t E57FileInputStream::readBytes(XMLByte*, XMLSize_t)â€™:
/<<PKGBUILDDIR>>/plugins/e57/libE57Format/src/E57XmlParser.cpp:149:39: error: â€˜numeric_limitsâ€™ is not a member of â€˜stdâ€™
  149 |         const int64_t size_max = std::numeric_limits<size_t>::max();
      |                                       ^~~~~~~~~~~~~~
/<<PKGBUILDDIR>>/plugins/e57/libE57Format/src/E57XmlParser.cpp:149:60: error: expected primary-expression before â€˜>â€™ token
  149 |         const int64_t size_max = std::numeric_limits<size_t>::max();
      |                                                            ^
/<<PKGBUILDDIR>>/plugins/e57/libE57Format/src/E57XmlParser.cpp:149:67: error: no matching function for call to â€˜max()â€™
  149 |         const int64_t size_max = std::numeric_limits<size_t>::max();
      |                                                                   ^
```

**Comment by abellgithub** [comment]
To my understanding, GCC 11 hasn't even been released.

**Comment by hobu** [comment]
Isn't the fix here just `#include <limits>` being added to E57XmlParser.cpp?

**Comment by abellgithub** [comment]
Fix it if you want. I don't really want to field bug reports from unreleased compilers.

**Comment by sebastic** [comment]
> To my understanding, GCC 11 hasn't even been released.

It's not, but the it's a real issue that will still need to be fixed once GCC 11 is more widely available.

**Comment by abellgithub** [comment]
I understand. I test everything on the latest GCC/Clang before we cut a release.

**Comment by sebastic** [comment]
GCC 11 is now more widely available and the default compiler in Debian unstable.

**Comment by sebastic** [comment]
> Isn't the fix here just `#include <limits>` being added to E57XmlParser.cpp?

Yes, and upstream fixed it already:

 https://github.com/asmaloney/libE57Format/blob/master/src/E57XmlParser.cpp#L45

You should update the embedded copy.
