### ISSUE TITLE
Correct behavior of IStream::get(std::string& s, size_t size) ?

### ISSUE THREAD

**Issue by aaronyonas** [PDAL/PDAL#3390]
Hi Andrew, 

Following up on #3384, which is now closed...

@abellgithub :
>  The issue is that this function is used to read a specific number of bytes from a stream into a string. If you can't read that number of bytes, something is wrong...

It sounds like you're saying that it's always the caller's responsibility to ensure that there are at least `size` bytes available to read in the stream.  If so, that's fine, but then please update the function's documentation comment to say so.  It currently defines `size` as `Maximum number of bytes to extract.` which implies that it might extract fewer bytes.

Also maybe add `assert(size == m_stream->gcount());` after the read.

On the other hand, maybe you're just saying that the _current_ callers of this function expect the stream to contain at least `size` bytes.  In that case, the documentation is correct, the function should support gcount() < size, and the current code is correct (though a little inefficient). 

Whatever you decide is fine with me.
Thanks!
Aaron

**Comment by aaronyonas** [comment]
Here's a  cleaner, more general approach: don't allow any truncated or malformed streams.
 
When stream is opened, set 
`istream->exceptions(std::ifstream::failbit | std::ifstream::badbit | std::ifstream::eofbit);`

IStream::get() would then just throw if fewer than `size` bytes are read from the stream.

What do you think?

**Comment by abellgithub** [comment]
I thought the fix I committed addressed your concern. What problem are you wanting to solve at this point?

In order for me to get excited about doing more, I'd like to see some real issue that can be solved by such change. Do you have a test case?

**Comment by aaronyonas** [comment]
Hi Andrew,

> What problem are you wanting to solve at this point?

Reliable handling of truncated and corrupted files.

I liked your earlier comment:

>  I think most of these cases where we're reading from a file that's invalid can't reasonably be addressed without obtrusive tests that can also slow things down, but if there are easy one-time checks that can be done, I'd like to add them.

...so I went looking for efficient, unobtrusive changes that catch a wide variety of file corruptions.   Setting ifstream exceptions fits the bill, yes?

(BTW, if we enable ifstream exceptions, I think #3384 is redundant and can be rolled back.)

I have three corrupted .las files that ifstream exceptions take care of.  Should I send them to you?  If there's a way for me to make a PDAL unit test that runs under MSan, let me know and I'll send you a PR.

**Comment by abellgithub** [comment]
Sure, send me the files.

**Comment by abellgithub** [comment]
@aaronyonas : Were you going to send some files?

**Comment by aaronyonas** [comment]
Sorry for the delay.  Will send the files later today.

**Comment by abellgithub** [comment]
Closing without followup.
