### ISSUE TITLE
BPF v1 Issues

### ISSUE THREAD

**Issue by murphke1** [PDAL/PDAL#3394]
All BPF V1 files that I attempt to ingest via PDAL come in with scrambled bounds,, such that:

PDAL minx = BPF minx
PDAL maxx = BPF maxy
PDAL miny = BPF maxx
PDAL maxy = BPF minz
PDAL minz = BPF miny
PDAL maxz = BPF maxz

Note that old-style BPF v1 bounds were written like this:
// Rectangle bounds on point set.
typedef struct
{
	double xmin;
	double xmax;
	double ymin;
	double ymax;
	double zmin;
	double zmax;
}
PointSetBounds;

I have attached a complete test matrix of BPF files, representing all of the major options generated by the standard PointSet BPF code.  Note that BPF v1 supports none of the compression and file layout options in BPF v3.

[apl_bpf_flavors.zip](https://github.com/PDAL/PDAL/files/6166813/apl_bpf_flavors.zip)

**Comment by hobu** [comment]
Thanks so much for the matrix of test files!

**Comment by murphke1** [comment]
In general if you have any early BPF-related questions, need files, etc., I can probably either get answers or hook you up with someone who can.  All the folks who directed BPF up through being open-sourced are direct co-workers, and I have the whole codebase at my fingertips.

**Comment by abellgithub** [comment]
Fixed by #3396
