### ISSUE TITLE
Howto set osr_Strip_towgs84 option to NO

### ISSUE THREAD

**Issue by Woutervb1** [PDAL/PDAL#3411]
Hi, 

Not sure if this is the place to ask, but I looked all over for this: when merging 2 lasfiles I get this message:

_(pdal merge readers.las Debug) GDAL debug: OSR: TOWGS84 information has been removed. It can be kept by setting the OSR_STRIP_TOWGS84 configuration option to NO_

I would like to keep exact the same information in the merged lasfile as in the initial ones. So the question is: how can I set this option to NO? Command?

Thanks a lot,

Wouter

**Comment by abellgithub** [comment]
You should post queries like this on the mailing list or gitter.

You'd have to post your pipeline in order to determine what's going on.
