### ISSUE TITLE
Refine function not working within filters.normal

### ISSUE THREAD

**Issue by xiaoxiaozhu007** [PDAL/PDAL#3435]
**Describe the bug**
The refine function can not be enabled within the filters.normal.

Sample scrip of python 3.6
```
import numpy as np
import pdal
import json
jsondict = {
            "pipeline": [
                {
                    "type": "readers.las",
                    "filename": "{}".format(file_name),
                    # "type": "readers.text",
                    # "filename": "{}".format(file_name),
                    # "header": "X Y Z",
                    # "separator": ' '
                },
                {
                    "type": "filters.normal",
                    "knn": 8,
                    "refine": True
                }
            ]
        }
jsonstring = json.dumps(jsondict)
p = pdal.Pipeline(jsonstring)
p.validate()
p.execute()
```

**Expected behavior**
Return error message "RuntimeError: filters.normal: Unexpected argument 'refine'."

**System/installation information:**
```
$ conda list
```
pdal                      2.0.1            py36h12372d9_5    conda-forge
python-pdal               2.3.7            py36h5b5db76_0    conda-forge
```
$ conda info
```
conda version : 4.9.2
conda-build version : 3.10.5
python version : 3.6.5.final.0
platform : win-64
user-agent : conda/4.9.2 requests/2.18.4 CPython/3.6.5 Windows/10 Windows/10.0.18362

**Comment by hobu** [comment]
> pdal 2.0.1

I think your PDAL version is too old here. Please reopen if you have this issue with PDAL 2.1

**Comment by xiaoxiaozhu007** [comment]
The function works after updating PDAL to the latest version.
Thanks for your help!
