### ISSUE TITLE
EPT overlap determination with an SRS Bounds may miss data

### ISSUE THREAD

**Issue by connormanning** [PDAL/PDAL#3438]
When using an `SrsBounds` as the `readers.ept.bounds` option, there are 2 separate issues:
- The bounds is reprojected from the target SRS into the EPT SRS by reprojecting the min and max corners.  Depending on the reprojection, this may not capture the full volume of the bounds.  Reprojecting all 8 corners to accumulate these extents would fix this in most cases.
- After the node selection, the per-point comparison currently happens in the EPT projection rather than the SrsBounds projection.

See [here](https://gist.github.com/connormanning/0e9e8f6f2b4afa225d0cc856fad8a99d) for some pipelines which demonstrate the issue with missing data between two adjacent SRS bounds, as well as non-square output since the comparisons happen in EPT's SRS rather than the target.

![gap](https://user-images.githubusercontent.com/5015470/116260282-2b398b80-a73c-11eb-814c-926931bb59a0.png)

**Comment by abellgithub** [comment]
Fixed by #3460
