### ISSUE TITLE
Locale unsafe

### ISSUE THREAD

**Issue by jjimenezshaw** [PDAL/PDAL#3450]
**Describe the bug**
PDAL library is not safe on different "locale".
I noticed the problem getting the error `X scale of 0.0 is invalid!` (when I wrote clearly 1e-3 for the scale) in my German computer, that was not the case in other computers.
The library is used in a program that sets the locale to the one defined in the system (German in my case)
Numbers in German and in other languages (like Spanish) are written with comma `,` as decimal separator, not the dot `.`

Detected in Ubuntu 20.04, but probably happening in other operating systems.

**Way to reproduce in the tests**
in the file `pdal/pdal_test_main.hpp`, add the line `std::locale::global(std::locale("de_DE.utf8"));` before calling `RUN_ALL_TESTS`. You need the locale to be installed in you OS.
You can also add `std::locale::global(std::locale(""));` to use the default locale from your system (German in my case).
(I do not know how to set it if the proper locale is not installed... it can be tricky for future tests. Maybe we need a docker with the locale installed).

**Possible solution**
`std::stringstream` family supports setting an specific locale with the method `imbue`. Something like `oss.imbue(std::locale::classic());` makes that object locale immune to the configuration done in the application. We want that PDAL library writes (and read) `1.2` as a number, not `1,2` when parsing a string. (it is the case, right?)
That means adding this `imbue` in many places.
Unfortunately `std::stod` and `str::strtod` do not support a different locale, and use the global one. That means that they shouldn't be used.

Example from a test: ([55,55],[55,55]) is a BOX2D with 4 numbers (55). However in German locale, reads 2 numbers (55.55)... and fails.

I started working in a branch (https://github.com/jjimenezshaw/PDAL/tree/locale-safe) to fix that, replacing `std::stod` with `stringstream` (so far the Bounds parsing) and setting `imbue(locale::classic())` wherever it is used. Once it is done, it will become a PR.

Before spending so much time on it, I want to know if it makes sense to you, or if you have a better suggestion.

Thanks.

PS: changing the locale does not change the language of the OS. It affects things like date format (another nightmare), currency, number format (the problem that we address here), etc.

**Comment by abellgithub** [comment]
I'm not sure I understand. I get that tests might fail, but if you have set
your locale to German, shouldn't you generally expect to enter your numbers
using that style?

I can see that there may be cases where we are making assumptions in doing
our own parsing, but I guess if have to know what those situations are to
comment.

I guess if we're using a comma as a separator this could be an issue, but
that seems a basic issue and I'm not sure how we can address it at this
point.

**Comment by jjimenezshaw** [comment]
It is not a matter of the interface with the user, but the internal serialization. As JSON format does not depend on the locale, and always use a period for decimal separator, I understand that PDAL should do the same.

Actually, the  application (and not this library) should take care of that possible format conversion. When the user types "0,01", the library should receive a `double a = 1e-2` (I use eng notation to make it more clear).

PDAL is doing a lot of internal serialization as I have seen in the code. Like for the X scale. This simple test fails due to the locale. Notice that there is not a single double number or string on it:

``` C++
void normal_mode_write_example(const std::string &fileName) {
  std::locale::global(std::locale("de_DE.utf8"));

  using namespace pdal;
  using namespace pdal::Dimension;

  PointTable table;
  table.layout()->registerDims(
      {Id::X, Id::Y, Id::Z, Id::Red, Id::Green, Id::Blue});
  PointViewPtr view(new PointView(table));

  auto index = 0;
  for (int i = 0; i < 10; i++) {
    view->setField(Id::X, index, i);
    view->setField(Id::Y, index, i);
    view->setField(Id::Z, index, i);
    auto color = uint16_t(65535 / 2);
    view->setField(Id::Red, index, color);
    view->setField(Id::Green, index, color);
    view->setField(Id::Blue, index, color);
    ++index;
  }

  BufferReader bufferReader;
  bufferReader.addView(view);

  Options writerOps;
  writerOps.add("filename", fileName);
  writerOps.add("a_srs", "EPSG:32632");
  writerOps.add("software_id", "PDAL_Test_App_Normal_Write");

  LasWriter writer;
  writer.setOptions(writerOps);
  writer.setInput(bufferReader);

  writer.prepare(table);

  writer.execute(table);
}
```

**Comment by abellgithub** [comment]
I tried the program but it failed when setting locale, probably because I don't have something installed.

What would be helpful to evaluate this issue are some specific failures that occur because of the different locale.

**Comment by hobu** [comment]
@jjimenezshaw, please provide a PR that implements a locale test scenario and provides the fixes necessary using PDAL's test suite and GitHub Actions. I don't doubt there are some issues here, but we do not have the resources to make PDAL completely locale aware on our own. 

Closing for now. Please open with PRs to implement what is needed.

**Comment by jjimenezshaw** [comment]
Hi @hobu 
I am implementing such PR. Yesterday I configured in my branch the tests in Linux CI to install a locale in the OS, and use it easily on every test (in addition to the "normal" tests) (example here: https://github.com/jjimenezshaw/PDAL/actions/runs/3075157116/jobs/4968361773#step:9:4153 , failing of course).
I am half a way done (it is my first interaction with that code). I would appreciate if anybody has a quick look at the changes I'm doing to get something like "Yes, go ahead with that", or "Oh, no, we should do something totally different", ... or anything else.

Here you can compare my branch with master (please, do not click the button that creates a PR)
https://github.com/PDAL/PDAL/compare/master...jjimenezshaw:PDAL:locale-safe

I do not want to create a PR yet. There are many unit tests to fix first!

Thanks!

**Comment by hobu** [comment]
Some comments:

* The period is the decimal separator in JSON. The `bounds` definition (such as it is, alas), is JSON, and IMO this shouldn't be something that's made locale-aware. This also means none of the pipeline stuff should be locale agnostic either.
* Applying locale-sensitive output in some of the text-based formats is quite likely to break things.
* Without windows tests of this stuff in our CI (which is the most difficult place to do locale-sensitive stuff), these changes are going to rot really quickly. I don't know what the story on doing locale-sensitive CI is with GHA, but a while ago, this was very difficult due to the trouble with installing the language packs.
*

**Comment by abellgithub** [comment]
I scratch my head wondering what the benefit is of making PDAL locale aware. I think you need to make a strong case before considering changes.

**Comment by jjimenezshaw** [comment]
It is the other way around. PDAL is so far "locale sensitive", and I want to make PDAL "locale insensitive" (I mean, to ignore whatever locale is configured anyhow by whoever, and parse strings always using the "classic" locale).
As PDAL is a library, it has not control on what the "host program" is doing with the locale. In my case, a program was doing `std::locale::global(...)` with the locale installed and configured in the system. In my case the German locale, that uses the comma as decimal separator. PDAL was not working at all, while a colleague with an American configuration had no problem with exactly the same inputs.

Unfortunately some C/C++ functions, like `strtod`, `atof` or simply the `<<` and `>>` operators of a stream do take in consideration the locale set in the function I mention above. I do not like that, but it is how it works.

The consequence is that PDAL (in that program, in my German computer) was not recognizing the string `0.5` as one half... it was expecting `0,5`.
As you say JSON is locale insensitive. And all that parsing in PDAL should be as well. Both reading and writing.

One way to avoid the problem is to `imbue` the stream with `std::locale::clasic()`.
This proto-PR is trying to make PDAL insensitive.

If you just take the changes in `pdal_test_main.hpp` (that tries to replicate "the program" setting whatever locale it wants), with a locale that uses comma, like German, Spanish, French, etc, the results should be the same: all green. It is not the case. Of course, you need the locale to be installed in the computer to use it.

About Windows, I do not have a computer to test it. Or to research how to install it.

**Comment by wrenoud** [comment]
> I scratch my head wondering what the benefit is of making PDAL locale aware. I think you need to make a strong case before considering changes.

As @jjimenezshaw mentioned it is the opposite, he is concerned about PDAL (the library) being "locale sensitive" without explicit support, and arguing that it should be "locale agnostic".

Right now if an application linking against PDAL chooses to use a computer's locale which doesn't use a period as the decimal separator then PDAL tips over because it is sensitive to what the application chose as the locale but isn't correctly using the locale.

PDAL could either correctly handle locale or chose to be agnostic of the application's local. @jjimenezshaw is proposing the later with his branch. He is insulating call sites that are locale sensitive by expliciting "imbue"ing with `std::locale::classic()`.

I have a windows machine and NL localization and can give this a try at least as a side investigation.

**Comment by wrenoud** [comment]
@jjimenezshaw I tested your branch on my windows machine with the Dutch and English locale, so I set the environment variable you added to the test to `TEST_SET_LOCALE=nl_NL` and `TEST_SET_LOCALE=en_EN` respectively. Dutch still has 7 test failures from 4 suites on your branch.

* `PolygonTest.test_json_in`
* `PolygonTest.test_json_out`
* `PolygonTest.smooth`
* `GDALWriterTest.btint`
* `IcpFilterTest.RecoverRotation`
* `HexbinFilterTest.HexbinFilterTest_test_1`
* `HexbinFilterTest.issue_2507`

**Comment by wrenoud** [comment]
It's worth adding that I also ran into an issue with `minwindef.h` getting included. I didn't dig into why yet, I just had to `#undef` the `max` macro in `filters/private/DimRange.cpp`. But I think there is a more elegant way to protect against these MSVC specific defines.

**Comment by hobu** [comment]
> Why should PDAL ignore a locale that someone has set on their system?

Because the formats we're reading from text are getting the user's locale injected into them. PDAL certainly isn't expecting this.

> What is the point of setting locale if you don't want programs to use the locale you've set?

So their keyboards work as expected? 😄 


> `LC_ALL=C pdal translate ...`, for example?

This is why I asked about GDAL. There aren't `imbue` calls sprinkled all over the GDAL or PROJ codebases. I don't think we want to do that in PDAL either.

**Comment by jjimenezshaw** [comment]
I am not sure what GDAL or PROJ are doing.
About using `std::setlocale`, it is not thread safe: https://en.cppreference.com/w/cpp/locale/setlocale

```Because setlocale modifies global state which affects execution of locale-dependent functions, it is undefined behavior to call it from one thread, while another thread is executing any of the following functions:...```

so I found `imbue` safer. Even without the race condition, whatever other thread is doing between your "disable" and "enable" scope will be affected by that locale. As PDAL is a library without any control or knowledge on other running threads, I thought it was important to not affect or be affected by them.

Also I find the same risk on forgetting the `imbue` than forgetting to set the locale before (and after) a piece of code that needs it.

**Comment by wrenoud** [comment]
PROJ `imbue`s in an internal function used for converting strings to doubles. See [`double c_locale_stod(const std::string &s)`](https://github.com/OSGeo/PROJ/blob/master/src/iso19111/internal.cpp#L242-L283)

**Comment by jjimenezshaw** [comment]
After talking with @wrenoud looking for a nice but safe solution, we think that this may make sense:

- Keep the `imbue` only in `utils` folder, mainly in`Utils.hpp`
  - functions like `c_locale_stod` and `toString` "copied" from `PROJ` (they use "imbue", as expected)
  - functions to make streams like `template <typename T> T c_locale_stream(...)` to make streams that must be in C locale.
-  Use those functions instead of the traditional std::stringstream, ifstream, etc, where needed. 

Does it make sense?

**Comment by hobu** [comment]
> Does it make sense?

yes.

> Use those functions instead of the traditional std::stringstream, ifstream, etc, where needed.

Is this going to cause a lot of churn throughout the codebase? IMO, we should consciously and selectively use this only where we need it, not replace every strinstream/ifstream/ofstream in the codebase.
