### ISSUE TITLE
bad alloc and range error when write data to a las file

### ISSUE THREAD

**Issue by OrdinaryChen** [PDAL/PDAL#3452]
![1620879594(1)](https://user-images.githubusercontent.com/31204657/118077303-70211b80-b3e6-11eb-9dcd-6fd269b1dec2.jpg)
hello everyone, I use PDAL with vs2017 in windows and C++, but when I write data to a las file, it goes wrong, and cast a error that bad alloc and range error. each time I debug to "stage * writer"  it shut down and exit with code  -1073740791. 

and even I use liblas ,this problem still happened so what should I do?

**Comment by abellgithub** [comment]
This simply isn't enough information to diagnose, but there's some error in your code/build.  Is `writer` NULL? If so and you're trying to open an LAZ file, have you build PDAL with LAZ support?

**Comment by abellgithub** [comment]
Reopen if you have evidence of a real problem in PDAL. Thanks.
