### ISSUE TITLE
viewToEigen should be exported or should have its comment updated

### ISSUE THREAD

**Issue by lakinwecker** [PDAL/PDAL#3461]
https://github.com/PDAL/PDAL/blob/master/pdal/private/MathUtils.hpp#L222-L229

The current comment seems to indicate that this is part of the API for external code, and that the code is not used internally.
> This method exists (as of this writing) **purely as a convenience method in the API**. It is **not currently used in the PDAL codebase itself.**

(emphasis mine).  However, it is used in the IterativeClosestPoint filter: https://github.com/PDAL/PDAL/blob/a00819d42cfd1ecd7ab85c6d77ec277fa278aac9/filters/IterativeClosestPoint.cpp#L201
and in the CpdFilter https://github.com/PDAL/PDAL/blob/a00819d42cfd1ecd7ab85c6d77ec277fa278aac9/plugins/cpd/filters/CpdFilter.cpp#L152 and it's not currently exported, so you can't use it from a Visual Studio produced .dll.  You can use it when compiling with g++, which makes it inconsistent and the documentation for it confusing. 

Updating the comment is probably the easiest fix:
> This method is used internally in a few filters and plugins, but is currently not exported and you shouldn't depend on this as part of your API

On the other hand, it's a useful method, so if it was possible to provide it as part of the API, I'd certainly welcome being able to use it. However, I'm not really up to speed on the API design considerations - so I won't complain if the docs are just updated to reflect it's real purpose.

**Comment by abellgithub** [comment]
We've been trying to make the public interface smaller. This allows us to make changes to PDAL without breaking things for those who are calling PDAL functions from their code.  But you can modify the library as you like and rebuild PDAL, or you can extract the functions you're interested in into your own source.

Note that the PDAL utility code is in its own library and has no dependencies on the PDAL main library, if that's at all helpful to you.

**Comment by lakinwecker** [comment]
Thanks!  I went ahead and copied the function I was using into my source. Which works fine for my purposes and I'm happy to continue with this method. The updated comment addresses it just fine.
