### ISSUE TITLE
Create writers.ept

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#3474]
Create a `writers.ept` that adopts and embeds the [Untwine codebase](https://github.com/hobu/untwine).

* Relicense the Untwine code to BSD to align with PDAL
* Support interrupted insertion   
    ```
     pdal translate in1.las out.ept
     pdal translate in2.las out.ept
     pdal translate in3.las out.ept
    ```
* DO NOT support multi-threaded or multi-process insertion – go use [Entwine](https://github.com/connormanning/entwine) for that.
* addon support as convenient
* Blob, LAZ, zstd, and Draco content encoding support

**Comment by julienlau** [comment]
Why the Untwine codebase was preferred over of the Entwine Codebase ?
The Untwine one seems to have a lot less users ?

Untwine is more lightweight ?

**Comment by julienlau** [comment]
is it linked to https://github.com/PDAL/PDAL/pull/3490 ?

**Comment by hobu** [comment]
> Why the Untwine codebase was preferred over of the Entwine Codebase ? The Untwine one seems to have a lot less users ? Untwine is more lightweight ?

Untwine is a bottom-up builder rather than a top-down one. This means it can consume much less memory, and more importantly, *predictably* consume memory when building trees. For local-system building, this feature is quite important.

> What about GPL license in Untwine vs BSD in PDAL ?

We will relicense Untwine to BSD if we duplicate any of its code into the PDAL source tree.

**Comment by hobu** [comment]
No plans to do this now. Maybe a `writers.copc` will be provided in the future, however.
