### ISSUE TITLE
pgpointcloud reader/writer with same pcid fails

### ISSUE THREAD

**Issue by autra** [PDAL/PDAL#3480]
## Description

With a custom pcid containing one integer metadata on last position, trying to read and write to the same pcid results in:

> PDAL: ERROR:  pc_patch_uncompressed_from_wkb: wkb size and expected data size do not match

## Step to reproduce

- pass the following 
<details>
<summary>sql script</summary>

```sql
begin;
create extension if not exists pointcloud_postgis cascade;

-- Insert the format needed for points
INSERT INTO pointcloud_formats (pcid, srid, schema) VALUES (1, 4326,
'<?xml version="1.0" encoding="UTF-8"?>
<pc:PointCloudSchema xmlns:pc="http://pointcloud.org/schemas/PC/1.1"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <pc:dimension>
    <pc:position>1</pc:position>
    <pc:size>4</pc:size>
    <pc:description>X coordinate as a long integer. You must use the
                    scale and offset information of the header to
                    determine the double value.</pc:description>
    <pc:name>X</pc:name>
    <pc:interpretation>int32_t</pc:interpretation>
    <pc:scale>0.0000001</pc:scale>
  </pc:dimension>
  <pc:dimension>
    <pc:position>2</pc:position>
    <pc:size>4</pc:size>
    <pc:description>Y coordinate as a long integer. You must use the
                    scale and offset information of the header to
                    determine the double value.</pc:description>
    <pc:name>Y</pc:name>
    <pc:interpretation>int32_t</pc:interpretation>
    <pc:scale>0.0000001</pc:scale>
  </pc:dimension>
  <pc:dimension>
    <pc:position>3</pc:position>
    <pc:size>4</pc:size>
    <pc:description>Z coordinate as a long integer. You must use the
                    scale and offset information of the header to
                    determine the double value.</pc:description>
    <pc:name>Z</pc:name>
    <pc:interpretation>int32_t</pc:interpretation>
    <pc:scale>0.001</pc:scale>
  </pc:dimension>
  <pc:dimension>
    <pc:position>4</pc:position>
    <pc:size>4</pc:size>
    <pc:description>metadata id</pc:description>
    <pc:name>metadata_id</pc:name>
    <pc:interpretation>uint32_t</pc:interpretation>
    <pc:scale>1</pc:scale>
  </pc:dimension>
  <pc:metadata>
    <Metadata name="compression">dimensional</Metadata>
  </pc:metadata>
</pc:PointCloudSchema>')
-- but just don't bother me and update if needed
on conflict(pcid) do update set srid=excluded.srid, schema=excluded.schema;

create table if not exists point_test(
  patch pcpatch(1)
);

insert into point_test(patch) values(pc_makepatch(1, ARRAY[1.2, 1.3, 1.4, 12]));

commit;
```
</details>

- then edit the connexion informations in this pipeline

<details>
<summary>test pipeline</summary>

```json
[
    {
        "type":"readers.pgpointcloud",
        "connection":"dbname=test user=postgres port=5434",
        "table":"point_test",
        "schema":"public",
        "column":"patch",
        "spatialreference":"EPSG:4326"
    },
    {
        "type":"filters.chipper",
        "capacity":"400"
    },
    {
        "type":"writers.pgpointcloud",
        "connection":"dbname=test user=postgres port=5434",
        "compression":"dimensional",
        "srid":"4326",
        "schema": "public",
        "table": "point_test2",
        "column": "patch",
        "pcid": "1"
    }
]

```

</details>

- and pass it with pdal: `pdal pipeline --input test.json`

**Expected behavior**
The pipeline executes without errors. The metadata_id is correctly inserted and a pc_get(point, 'metadata_id') returns the correct values.

**actual behavior**
The pipeline fails with

> PDAL: ERROR:  pc_patch_uncompressed_from_wkb: wkb size and expected data size do not match
LINE 1: ...ERT INTO "public"."point_test2" ("patch") VALUES ('010100000...

## Additional information

- The pipeline executes correctly if metadata_id is in position 1.
- if no pcid is specified for the writer, pdal creates a new format with metadata_id in position 1 instead of 4.

## System/installation information:

```
ᐅ uname -a
Linux augustin-Oslandia 5.4.0-73-generic #82-Ubuntu SMP Wed Apr 14 17:39:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

```

```
ᐅ pdal --version
--------------------------------------------------------------------------------------------------------
pdal 2.0.1 (git-version: Release)
--------------------------------------------------------------------------------------------------------

```
---

Please let me know if additional infos / tests are needed.

Thanks a lot!

**Comment by abellgithub** [comment]
PDAL tries to look for a schema that matches one that it would create. If it finds one, that is used. But in your case you've created a schema that is different from what PDAL would create, so it attempts to make a new entry into `pointcloud_formats`, but this fails (though I'm not sure on the details of why it fails).

We would suggest not pre-creating the schema and let PDAL do it for you on first insert, which will make sure that PDAL creates the proper schema for the data being written.

**Comment by autra** [comment]
> We would suggest not pre-creating the schema and let PDAL do it for you on first insert, which will make sure that PDAL creates the proper schema for the data being written.

Yes, that's the workaround we are using, followed by a manual `pc_transform` to transform it back into the proper schema.

In our case, it's not acceptable to keep the PDAL generated format: PDAL generates doubles for x, y, z. However, we know exactly the precision and range of our data, so we can store them a lot more efficiently by using integers (and scale). We're talking about 224 bits for each points in double vs 128. For a DB that will contain more than 10 billions points, this is a deal breaker unfortunately.

Moreover, writers.pgpointcloud allows to specify a pcid, I would expect it to be able to use it, as a user POV.

My favorite behaviour in terms of user experience: if using both pgpointcloud reader and writer, PDAL should keep the exact same format between source and destination.

Thanks!

**Comment by abellgithub** [comment]
See the `scale_<x/y/z>` and `offset_<x/y/z>` option for the pgpointcloud writer: https://pdal.io/stages/writers.pgpointcloud.html

**Comment by autra** [comment]
@abellgithub it works, thanks! It's an acceptable way of avoiding this issue for me.

I think it is still a good thing to be able to infer these from the pcid given, so I'm leaving this open. Please don't hesitate to close, as this might be low priority.

**Comment by abellgithub** [comment]
We don't assume that a matching PCID means that the schema should be used -- the schema also has to match. Perhaps it should be otherwise, but it's been this way from the beginning. I wasn't around for the original design, so can't really comment, but there are issues when schemas don't match and figuring out what should be done is non-trivial.
