### ISSUE TITLE
filters.csf saves files in the current directory

### ISSUE THREAD

**Issue by Pilat66** [PDAL/PDAL#3488]
Any time you run filters.csf, files (cloth_nodes.txt, collision-notes.txt and others) are created in the current directory that look like they are not needed. Their size can be very large. The code for saving these files to Cloth.cpp does not show how they are used later.
The suggestion is to remove the saving of these files.

**Comment by chambbj** [comment]
I did not remember that we left it this way. It looks like `do_filtering` includes a boolean option that controls at least some of these outputs. We could allow the curious user to specify an output directory for such exports (empty/undefined by default), and only enable the outputs in the event that the output directory is defined. We should look into a reasonable solution, as I agree that it is messy as is.

**Comment by Pilat66** [comment]
The problem is on two levels. 1) unnecessary huge files and resources for their creation, 2) when two copies of pdal are run in parallel from the same directory (as background processes), the files conflict.

Here is the code from branch 2.3:

```

void Cloth::terrCollision() {
...
    saveToFile("collision-notes.txt");
}

void Cloth::saveToFile(string path) {
    string filepath = "cloth_nodes.txt";

    if (path == "") {
        filepath = "cloth_nodes.txt";
    } else {
        filepath = path;
    }

    ofstream f1(filepath.c_str());

    if (!f1)
        return;

    for (size_t i = 0; i < particles.size(); i++) {
        f1 << fixed << setprecision(8) << particles[i].getPos().f[0] << "	"<< particles[i].getPos().f[2] << "	"<< -particles[i].getPos().f[1] << endl;
    }

    f1.close();
}
```

**Comment by abellgithub** [comment]
I think you should have to ask for supplemental output with an option.

**Comment by chambbj** [comment]
Agreed. I'm thinking similar to what we do with SMRF.

https://pdal.io/stages/filters.smrf.html?highlight=dir
