### ISSUE TITLE
[document feedback] --drivers and --options usage

### ISSUE THREAD

**Issue by hiroyuki-sato** [PDAL/PDAL#3497]
Hello, Developers.

Thank you for developing great software.
I've just started to use PDAL.

I believe this is not a general how-to question. 
Please let me know If I should post this to another place.
I'll post this next time.

https://pdal.io/apps/index.html

It seems that `--drivers` and `--options` description is wrong.

```
$ pdal info --help
$ pdal translate --drivers
$ pdal pipeline --options writers.las
```

I think the correct commands are the following. Is this correct?

```
pdal --drivers
pdal --options writers.las
```

I can create a PR. please let me know. (Should I  modify http s://github.com/PDAL/PDAL/blob/master/doc/apps/index.rst?)

I got the following results.

```
pdal translate --drivers
PDAL: kernels.translate: Missing value for positional argument 'input'.
```

```
pdal pipeline --options writers.las
PDAL: Input filename required.
```

my environment.

```
pdal --version
--------------------------------------------------------------------------------
pdal 2.3.0 (git-version: 0800a2)
--------------------------------------------------------------------------------
```

Best regards.

**Comment by abellgithub** [comment]
Thanks for the report.

Fixed with 2c529c0aae40f7927f32671d4bb410f3a6107aac
