### ISSUE TITLE
Test failures

### ISSUE THREAD

**Issue by manisandro** [PDAL/PDAL#3501]
PDAL-2.3.0 as well as git fb3d8928c20300f193922521ae027f67975fefd6 tests fail on Fedora rawhide x86_64 as follows (see [1] for full logs, and root.log for used dependencies):

    [ RUN      ] EptReaderTest.boundedCropReprojection
    /home/sandro/rpmbuild/BUILD/PDAL-fb3d8928c20300f193922521ae027f67975fefd6/test/unit/io/EptReaderTest.cpp:692: Failure
    Expected equality of these values:
    eptNp
        Which is: 45
    47u
        Which is: 47
    /home/sandro/rpmbuild/BUILD/PDAL-fb3d8928c20300f193922521ae027f67975fefd6/test/unit/io/EptReaderTest.cpp:693: Failure
    Expected equality of these values:
    sourceNp
        Which is: 45
    47u
        Which is: 47
    [  FAILED  ] EptReaderTest.boundedCropReprojection (72 ms)
    [ RUN      ] EptReaderTest.ogrCrop
    /home/sandro/rpmbuild/BUILD/PDAL-fb3d8928c20300f193922521ae027f67975fefd6/test/unit/io/EptReaderTest.cpp:734: Failure
    Expected equality of these values:
    eptNp
        Which is: 89
    sourceNp
        Which is: 86
    /home/sandro/rpmbuild/BUILD/PDAL-fb3d8928c20300f193922521ae027f67975fefd6/test/unit/io/EptReaderTest.cpp:735: Failure
    Expected equality of these values:
    eptNp
        Which is: 89
    86u
        Which is: 86

and

    [ RUN      ] CropFilterTest.test_crop_polygon_reprojection
    /home/sandro/rpmbuild/BUILD/PDAL-fb3d8928c20300f193922521ae027f67975fefd6/test/unit/filters/CropFilterTest.cpp:253: Failure
    Expected equality of these values:
    view->size()
        Which is: 45
    47u
        Which is: 47
    [  FAILED  ] CropFilterTest.test_crop_polygon_reprojection (42 ms)

[1] https://koji.fedoraproject.org/koji/taskinfo?taskID=72317934

**Comment by abellgithub** [comment]
This is exceedingly hard to debug without access to the system in question, but I expect it has something to do with the version of PROJ that you're linked against. You should try to compare detailed results with a system that passes.

**Comment by manisandro** [comment]
Last successful build used proj-8.1.0 and gdal-3.2.2, whereas this one uses proj-8.1.0 and gdal-3.3.1, I'd very much suspect one of those is triggered the failure.

(I'm going through all the failures of the Fedora mass rebuild and reporting issues upstream as I find them, sorry but don't have the capacity to debug further)

**Comment by hobu** [comment]
Please reopen if there are still issues with PROJ 8.2 and gdal 3.2.3.
