### ISSUE TITLE
Memory Usage

### ISSUE THREAD

**Issue by xq198109** [PDAL/PDAL#3503]
```
        pdal::Option las_opt("filename", FileName);//
	pdal::Options las_opts;
	las_opts.add(las_opt);
	pdal::LasReader las_reader;
	las_reader.setOptions(las_opts);
	pdal::PointTable table;
	las_reader.prepare(table);
	pdal::PointViewSet point_view_set = las_reader.execute(table);
```
 
Using PDAL 2.3.1 to read las file，size of memory usage  is more than twice size of the file

**Comment by abellgithub** [comment]
This is expected. Read about stream mode if you're concerned about memory use: https://pdal.io/pipeline.html. Also see the https://github.com/PDAL/PDAL/pull/3311/files for an example of how to limit loaded dimensions via the API.
