### ISSUE TITLE
COPC Reader Support

### ISSUE THREAD

**Issue by timodwhit** [PDAL/PDAL#3519]
While the COPC format is still in a draft spec, wanted to get this issue in to track work for a reader of that format. 

Even though it is LAZ 1.4 format, I am guessing there are optimizations the reader will have that will allow it function more similarly to EPT.

**Comment by timodwhit** [comment]
@leo-stan ping.

**Comment by leo-stan** [comment]
@abellgithub I am working on implementing this feature, you seem like you are currently making a lot of progress on COPC with PDAL. Can you tell me if you had any particular plans for a reader?

**Comment by abellgithub** [comment]
@leo-stan (@hobu) Are you still pursuing this? We're considering putting some work into it.

**Comment by leo-stan** [comment]
@abellgithub I had to prioritize work on the copc-lib, so I would eventually, but not for another week probably. If you get started I'd be happy to jump on whenever I have some time.

**Comment by julienlau** [comment]
readers.copc implementation #3598 
I think it was merged recently
