### ISSUE TITLE
PDAL: Conda vs Source Build Performance

### ISSUE THREAD

**Issue by xycarto** [PDAL/PDAL#3521]
I have been testing PDAL with both Conda and source build installs and have been getting significant performace results. For a number of reasons, we cannot use the Conda install in our current process.

I am running Ubuntu 20.04 and did a source build of PDAL with LAZ reading capabilities using the following process:

Install LasTools
```
git clone https://github.com/LASzip/LASzip.git
mkdir LASzip/build && cd LASzip/build
cmake ..
sudo make install
```

Build and install  PDAL
```
git clone git@github.com:PDAL/PDAL.git
cd PDAL
mkdir build
cd build
cmake -G Ninja # make sure make sees LAStools in compilation
ninja
ninja install
```

Minor errors running `cmake`:

```
Total Test time (real) = 117.49 sec

The following tests FAILED:
	  1 - pgpointcloudtest (Failed)
	 71 - pdal_filters_gpstimeconvert_test (Failed)
Errors while running CTest
```

I have been testing some LAZ processing using the following pipeline:

```
{
    "pipeline":[
        {
            "filename":"in.laz"
        },
        {
            "type": "filters.reprojection",
            "in_srs": "EPSG:6420",
            "out_srs": "EPSG:6420"
        },
        {
            "filename":"out.tif",
            "gdaldriver":"GTiff",
            "output_type":"idw",
            "resolution": 1,
            "window_size": 4,
            "type": "writers.gdal",
            "bounds": "([6053281.234, 6054999.999],[1952500, 1954999.999])"
        }
    ]
  }
```

One performance issue I noticed immediately is in the time difference between processing with Conda and processing from the source build:

Process with Conda environment:

```
 time pdal pipeline ./dtmTemplate.json

real    1m22.587s
user    1m22.299s
sys     0m0.268s
```

Process using source build:

```
time pdal pipeline ./dtmTemplate.json

real    12m51.715s
user    12m50.890s
sys     0m0.328s
```

Perhaps I am missing something in the source build? This is a significant difference in processing time.

A second, minor issue I have found is in the filter reprojection. If I run `filters.reprojection` in the Conda environment and only specify the `out_srs`, PDAL reprojects the LAZ as expected.  

```
pdal translate in.laz \
out_CONDA.laz \
-f filters.reprojection \
--filters.reprojection.out_srs="EPSG:6420"
```

If I run the same command using my source build, PDAL produces an empty LAZ.  This can be fixed, however, specifying the `in_srs` as follows:

```
pdal translate in.laz \
out_CONDA.laz \
-f filters.reprojection \
--filters.reprojection.in_srs="EPSG:6420"
--filters.reprojection.out_srs="EPSG:6420"
```

Perhaps these two issues are related by an incorrect source build on my part?

CONDA pdal version:

```
pdal 2.3.0 (git-version: 0800a2)
```

Source build PDAL version:

```
pdal 2.3.0 (git-version: 82eefc)
```

**Comment by hobu** [comment]
Source builds default to Debug, which are going to be quite a bit slower than Release builds. Set CMAKE_BUILD_TYPE when configuring

**Comment by xycarto** [comment]
Cheers @hobu 

`CMAKE_BUILD_TYPE ` set to `Release` works perfect thanks.

With this sort of speed, I'll see if I can set up a more logical test why see why `filters.reprojection` is producing empty LAZ if `in_srs` is not set

**Comment by hobu** [comment]
Closing this ticket. I have no idea why things don't work in your self-built environment, but follow the Conda environment for listing of libraries and environment variables. If you have a specific file that does not work, you will need to provide it along with a conda-based scenario demonstrating its failure.
