### ISSUE TITLE
Segmentation fault with multiple inputs

### ISSUE THREAD

**Issue by gsakkis** [PDAL/PDAL#3548]
The following pipeline crashes with a segmentation fault. I tried it with several different input files in place of `fileA.las`, the crash is consistent. I tried both the latest stable 2.3.0 release from Conda and building from source from the latest master. 

```
$ pdal pipeline pipeline.json 
Segmentation fault (core dumped)
```

`pipeline.json`:
  
```json
[
  "fileA.las",
  {
    "type": "writers.text",
    "filename": "fileA.txt",
     "tag": "fileA"
  },
  {
    "type": "filters.range",
    "limits": "Intensity[80:120)",
    "tag": "intensity"
  },
  {
    "type": "writers.text",
    "filename": "fileB.txt",
    "inputs": ["fileA", "intensity"]
  }
]
```

**Comment by abellgithub** [comment]
See https://github.com/PDAL/PDAL/issues/1537

I didn't think this would cause a crash, but I'm also not sure what should happen. I suppose just some error saying that this isn't supported.

**Comment by gsakkis** [comment]
That was quick, thanks! Closing as duplicate.

**Comment by abellgithub** [comment]
Actually, this should work, though not probably as you expect. Pipelines like this get linearized, meaning:

```
Input -> writerA -> Intensity filter
                                     -> writer B
Input -> writerA ------------------
```
The data gets read twice. File A gets written twice. The intensity filter is applied to one set of the data and then it's merged with a non-filtered set and written to B. I'll look to see why it's crashing.

**Comment by gsakkis** [comment]
Thanks for looking into this and the quick fix!

On a somewhat related note, the docs [mention](https://pdal.io/development/overview.html#stage-execution) "It is important to note that ready() and done() are called only once for each stage (...)". By going over the code and adding a debug statement in ready() and done(), this is not the case if a stage is part of more than one paths such as the Reader in the following pipeline:
```
Reader -> Filter1 ---\
                     |----> Writer
Reader -> Filter2----/
```
Reader.ready() and Reader.done() are called twice here, so there is a discrepancy between the documentation and the current behavior.
