### ISSUE TITLE
BufferReader with PipelineManager

### ISSUE THREAD

**Issue by joaobrittoneto** [PDAL/PDAL#3581]
Not really a bug, but more a question/request.

Is it possible to use a BufferReader as input to a PipelineManager in C++?

I'd like to apply a generic pipeline defined in json to a point cloud (using BufferReader as in the [example](https://pdal.io/development/writing.html#writing)) in C++, but I've being not able to make it work and could not find an example or test of it. 

It seems to be similar to https://github.com/PDAL/PDAL/issues/3564, so I guess it's not possible, right?
Or is there a way?

I'm using pdal 2.0.1

Thanks

**Comment by abellgithub** [comment]
Take a look at void TranslateKernel::makeJSONPipeline(). I think it essentially does what you're wanting. It calls the reader `r`, so in your case that would be your buffer reader.

**Comment by joaobrittoneto** [comment]
Thanks for the tip.

This is how I'm doing it:
```
pdal::PipelineManager pipe_mng;
pipe_mng.readPipeline(pipeline_file);

pipe_mng.pointTable().layout()->registerDims({Id::X, Id::Y, Id::Z, Id::Intensity});
pdal::PointViewPtr view(new pdal::PointView(pipe_mng.pointTable()));

pdal::BufferReader reader;
std::vector<pdal::Stage*> roots = pipe_mng.roots();
roots[0]->setInput(reader);

fillView(view);
reader.addView(view);

auto res = pipe_mng.execute();
auto result_view = pipe_mng.views().begin();
```

A few problems that I have are:
1. Not sure if I need to call `pipe_mng.addReader("readers.buffer")` but I can't do it since `readers.buffer` is not a plugin.
2. Not sure if it is the correct way to define the table and the view to fill it, but it's not working that way. The result_view doesn't have the proper values.

Am I doing something deeply wrong or missing something?

**Comment by abellgithub** [comment]
This is not a complete program so I really can't tell what you're doing incorrectly. There are examples of using BufferReader in the tests and in various filters. I would suggest looking at those. There's no reason that you can't do what you're wanting, if I understand correctly. You don't need to call `PipelineManager::addReader()` for a BufferReader.

**Comment by abellgithub** [comment]
Please post more questions to the mailing list.

**Comment by joaobrittoneto** [comment]
Just to register:

I could make it work by adding `pipe_mgn.prepare()` before `fillView(view)` in the code above :)

ps: Sorry for using the issues for such questions.
