### ISSUE TITLE
pdal writer cannot save a large value

### ISSUE THREAD

**Issue by licheng0794** [PDAL/PDAL#3596]
I have a las file where y coordinates have a value like 6.30601e+06.  My pdal writer is a standard one as below. 

Stage* writer = factory.createStage("writers.las");

writer->setInput(xjBufferReader);
writer->setOptions(las_opt);
writer->prepare(table);
writer->execute(table);

When code is running to the line 'writer->execute(table);', I got the error pdal.dll memory error. 

If I changed the y value above to  6.30601e+05 for example, the code works. Anyone has the same issue. Can we fix that? 

Thank you.

**Comment by abellgithub** [comment]
There's not sufficient information here to diagnose and problem. You'll have to submit a program and data that reproduces the issue.

Are you sure an exception isn't being thrown that you're not catching?

**Comment by licheng0794** [comment]
> There's not sufficient information here to diagnose and problem. You'll have to submit a program and data that reproduces the issue.
> 
> Are you sure an exception isn't being thrown that you're not catching?

I just solved the issue. If I set the scale_x, scale_y and scale_z to be 0.001, the issue reported exists. After I changed them to the default one (0.01), everything works well. Thank you.
