### ISSUE TITLE
Error : 'Pipeline' object has no attribute 'validate'

### ISSUE THREAD

**Issue by mdupays** [PDAL/PDAL#3605]
I install PDAL 
1) Instal LASZip 
cd /opt 
git clone https://github.com/LASzip/LASzip.git
cd LASzip
cmake .
make
sudo make install

2) Install PDAL
cd /opt 
git clone https://github.com/LASzip/LASzip.git / ou télécharger https://pdal.io/download.html#source
cd PDAL
cmake .
make
sudo make install
pip install PDAL

When I test this script : 
information = {}
information = {
    "pipeline": [
        {
            "type": "readers.las",
            "filename": "/home/mdupays/Documents/REPOSITORY/data/pointcloud_ilot75105_1793.las"
        },
        {
            "type": "filters.stats",
            "dimensions": "Z"
        }
    ]
} 

import pdal
import json
import logging

try:
    # # Create json
    json_zstats = json.dumps(information, sort_keys=True, indent=4)
    pipeline = pdal.Pipeline(json_zstats)
    # # Check if our JSON and options were good
    pipeline.validate()
    # # Really noisy
    #pipeline.loglevel = 8
    pipeline.execute()
    result = json.loads(pipeline.metadata)
    zmin = round(result['metadata']['filters.stats'][0]['statistic'][0]['minimum'],2)
    zmax = round(result['metadata']['filters.stats'][0]['statistic'][0]['maximum'],2)
    logging.info("To extract the stat of ground's pointcloud")
except Exception as e:
    logging.critical(e)

I have a message : 
CRITICAL:root:'Pipeline' object has no attribute 'validate'

**Comment by hobu** [comment]
validate() was deprecated last release and removed this release. Simply drop your call to it.
