### ISSUE TITLE
PDAL Application cannot automatically load custom reader plugin

### ISSUE THREAD

**Issue by longhuan2018** [PDAL/PDAL#3609]
I customized a reader plugin, named it  libpdal_plugin_reader_dtm.dll, and put it in the directory pdal.exe.
However, when I use the "pdal.exe info test.dtm" command, I receive the following prompt
```
PDAL: Cannot determine reader for input file: test.dtm
```
when I use the "pdal.exe --drivers" command, I receive the following prompt.  readers.dtm  already be identified.
```
============================ ===================================================
Name                         Description
============================ ===================================================
filters.approximatecoplanar  Estimates the planarity of a neighborhood of
                             points using eigenvalues.
filters.assign               Assign values for a dimension range to a specified
                             value.
filters.chipper              Organize points into spatially contiguous,
                             squarish, and non-overlapping chips.
......
readers.bpf                  "Binary Point Format" (BPF) reader support. BPF is
                             a simple DoD and research format that is used by
                             some sensor and processing chains.
readers.dtm                  Read dtm files.
readers.faux                 Faux Reader
readers.gdal                 Read GDAL rasters as point clouds.
......
============================ ===================================================
```
In addition to writing the pipeline. json file, is there any other way to make the customized plugin work normally directly on the pdal.exe command line?

**Comment by longhuan2018** [comment]
I have several minor modifications here that can realize this function, but I don't know whether it is appropriate.
Add "PluginManager<Stage>::loadAll()" into apps/pdal.cpp file
```
int App::execute(StringList& cmdArgs, LogPtr& log)
{
     .......
    PluginManager<Stage>::loadAll();
    m_command = Utils::tolower(m_command);
    if (!m_command.empty())
    {
        int ret = 0;
        std::string name(findKernel());
   ........
```
Add "PDAL_DLL" into pdal/StageExtensions.hpp file
```
class PDAL_DLL StageExtensions
 {
 public:
     StageExtensions(LogPtr log);
```
In the plugin project, use StaticPluginInfo instead of PluginInfo
eg.   examples/writing-reader/MyReader.cpp
```
  static StaticPluginInfo const s_info
  {
    "readers.myreader",
    "My Awesome Reader",
    "http://link/to/documentation",
     { "test" }
  };
```

**Comment by hobu** [comment]
maybe you need to set `PDAL_DRIVER_PATH` so that PDAL looks for your specially-named DLL. Additionally, make sure you are calling the `CREATE_SHARED_STAGE` macro with your `StaticPluginInfo` object, or the symbols won't be named correctly.

**Comment by abellgithub** [comment]
If you make a plugin (CREATE_SHARED_STAGE), you can't have the PDAL use the filename extension automatically without also modifying StageFactory::inferReaderDriver() or StageFactory::inferWriterDriver(). It seems odd to have to do this for a plugin, but that's how it is now. You can typically use the `--driver` option to specify the driver you want to use. See #2714. If you're making a static stage (CREATE_STATIC_STAGE), then it just works if you build your stage into the PDAL library and you specify the extension in the `StaticPluginInfo` structure, like this:

```
static StaticPluginInfo const s_info {
    "readers.las",
    "ASPRS LAS 1.0 - 1.4 read support. LASzip support is also \n" \
        "enabled through this driver if LASzip was found during \n" \
        "compilation.",
    "http://pdal.io/stages/readers.las.html",
    { "las", "laz" }
};
```
