### ISSUE TITLE
Erratic output of writers.ogr

### ISSUE THREAD

**Issue by gui2dev** [PDAL/PDAL#3611]
I'm trying to export part of a point cloud using `writers.ogr`. Most of the time the file ends up being empty, without warnings or errors.
Implementing the same pipeline with the c++ API works every time.

```
$ pdal pipeline cut.json
```

<details>
  
```
{
  "pipeline":[
    "in/ept.json",
     {
        "type": "writers.ogr",
        "filename": "cut.dxf",
        "ogrdriver": "DXF"
    }
  ]
}
```

</details>

**Expected behavior**
File should be filled with proper values.

**System/installation information:**
Windows, pdal 2.3.0, custom build

Any idea what might cause the issue ?

**Comment by abellgithub** [comment]
I think you'll need to provide a reproducible test case for this to be addressed.

**Comment by gui2dev** [comment]
Sorry @abellgithub for my late response, here some simple example : 
```
[
    {
        "type": "readers.ept",
        "filename": "http://na.entwine.io/autzen/ept.json",
        "polygon": "POLYGON((635577 848882,635577 853538,639004 853538,639004 848882,635577 848882)) / PROJCS[\"NAD_1983_HARN_Lambert_Conformal_Conic\",GEOGCS[\"GCS_North_American_1983_HARN\",DATUM[\"NAD83_High_Accuracy_Reference_Network\",SPHEROID[\"GRS 1980\",6378137,298.2572221010002,AUTHORITY[\"EPSG\",\"7019\"]],AUTHORITY[\"EPSG\",\"6152\"]],PRIMEM[\"Greenwich\",0],UNIT[\"degree\",0.0174532925199433]],PROJECTION[\"Lambert_Conformal_Conic_2SP\"],PARAMETER[\"standard_parallel_1\",43],PARAMETER[\"standard_parallel_2\",45.5],PARAMETER[\"latitude_of_origin\",41.75],PARAMETER[\"central_meridian\",-120.5],PARAMETER[\"false_easting\",1312335.958005249],PARAMETER[\"false_northing\",0],UNIT[\"foot\",0.3048,AUTHORITY[\"EPSG\",\"9002\"]]]"
    },
    {
        "type": "writers.ogr",
        "filename": "cut.dxf",
        "ogrdriver": "DXF"
    }
]
```
that would just somehow crash as it ends up with two empty files (cut.dxf and cut.dxf.tmp).
If replace `writers.ogr` stage by `writers.las` stage, it outputs a correct las/laz file.
If you keep the stage `writers.ogr` and add the `writers.las` stage after, you won't get a las file.

**Comment by gui2dev** [comment]
Using vs debugger, it ends up there :
`double m = point.getFieldAs<double>(m_measureDim);` with a non initialized value and then a `vector subscript out of range` exception

**Comment by gui2dev** [comment]
But adding a `measure_dim` option would crash as I guess the driver does not supports it, as it yields a `GDAL` exception : 
> (pdal pipeline writers.ogr Error) GDAL failure (1) No known way to write feature with geometry 'None'.
PDAL: writers.ogr: Couldn't create feature.

**Comment by gui2dev** [comment]
And then, other error, it's that `m_curCount` is only initialized in non stream mode.
