### ISSUE TITLE
cannot build static library

### ISSUE THREAD

**Issue by christian-rauch** [PDAL/PDAL#3621]
**Describe the bug**
I am unable to build with `PDAL_BUILD_STATIC=ON`

```
mkdir build
cd build
cmake .. -DPDAL_BUILD_STATIC=ON
```
gives me:
```
CMake Error: install(EXPORT "PDALTargets" ...) includes target "pdal_base" which requires target "pdal_arbiter" that is not in any export set.
CMake Error: install(EXPORT "PDALTargets" ...) includes target "pdal_base" which requires target "pdal_kazhdan" that is not in any export set.
CMake Error in CMakeLists.txt:
  export called with target "pdal_base" which requires target "pdal_arbiter"
  that is not in any export set.


CMake Error in CMakeLists.txt:
  export called with target "pdal_base" which requires target "pdal_kazhdan"
  that is not in any export set.
```

**Expected behavior**
PDAL should build static *.a libraries.

**System/installation information:**

```
Linux gungnir 5.11.0-40-generic #44~20.04.2-Ubuntu SMP Tue Oct 26 18:07:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by abellgithub** [comment]
We don't support building a static PDAL library, though conan was doing it. You might check to see what they were doing.

**Comment by christian-rauch** [comment]
> We don't support building a static PDAL library

What is `PDAL_BUILD_STATIC` then used for?

**Comment by abellgithub** [comment]
Didn't realize it existed. It's probably been there for years with no use. If there are simple things you can do to get things working and want to submit a PR, that would be fine. There is a recent gitter conversation about this (search for lakinwecker).
