### ISSUE TITLE
Maintain all fields of a las file after filtering?

### ISSUE THREAD

**Issue by LuyenKhacBui** [PDAL/PDAL#3633]
I am interested in filtering ground/nonground points from a las file by CSF and SMRF. I filtered to get a file with a smaller area first by filters.range.limts but not all fields were maintained after this. Specifically, fields named, e.g., "COV11", "COV12", were not included in the output file while others, e.g., 'X', 'Y', 'Z', 'Intensity', are included. I guess that only fields with standard ASPRS names are maintained in the output file? I am wondering if there is an option I can overcome this?

**Comment by hobu** [comment]
Yes, write a LAS 1.4 file and use the `extra_dims` option to list what you want. It is documented at https://pdal.io/stages/writers.las.html

Another option is to use `filters.ferry` to copy values from one dimension to one of the official LAS dimensions.
