### ISSUE TITLE
PDAL is NOW missing gitsha.h, which is inside hexer .

### ISSUE THREAD

**Issue by jiapei100** [PDAL/PDAL#3639]
As title:
**PDAL is NOW missing gitsha.h, which is inside hexer .**

**Comment by abellgithub** [comment]
You'll need to be more specific about the error you're experiencing. Please include a compilation error and platform information.

**Comment by jiapei100** [comment]
Problem solved... Just copy https://github.com/hobu/hexer/blob/master/include/hexer/gitsha.h down into **PDAL**.
