### ISSUE TITLE
PDAL: readers.las: Invalid VLR - exceeds specified file range

### ISSUE THREAD

**Issue by dezhi-l** [PDAL/PDAL#3640]
**Symptoms:**
When I try to read a LAZ file, I  get the following error:
`PDAL: readers.las: Invalid extended VLR offset - exceeds  specified file range.`

I am not sure why this error is triggered , then i use lastools to check this file , i found some warning message ,but lastools can read it. (ps : CloudCompare and Qt Modeler also could open this file ),   Is there a way to make pdal support reading and writing point cloud data like this? 

**Details:**
pdal 2.3.0 (git-version: b7aaa4)
pdal info 10-10-10-10.las (format is 1.2
![info](https://user-images.githubusercontent.com/96613044/147335401-b1f8a0b3-bb5f-4769-b7c8-6da868d054c6.png)
)

**Comment by abellgithub** [comment]
Your file is invalid. You should contact the data provider.

**Comment by dezhi-l** [comment]
I guess it may be caused by irregular VLR field，it's there a way to ignore VLR ? like CloudCompare supports ignore irregular VLR field
I upload my laz for you here : https://filebin.net/idx4w553cbb0snpn
Thank for your assistance :)

**Comment by yonggandeliuguang** [comment]
you can download LAStools and execute `las2las -i in.las -o out.las -remove_all_vlrs`
