### ISSUE TITLE
Huge Gaps/Holes in DTM

### ISSUE THREAD

**Issue by shubham9436** [PDAL/PDAL#3645]
I have generated DTM from a point cloud. There are huge gaps/holes in the DTM. It has not interpolated the gaps left in the point cloud.
![Capture](https://user-images.githubusercontent.com/19433739/147747194-57a29cc0-0b4b-4a5b-ac94-c863a6a3018b.PNG)

I have used the following json:
`
{
    "pipeline": [
        "ground.las",
        {
            "filename":"dtm_btif",
            "gdaldriver":"GTiff",
            "output_type":"idw",
            "data_type":"float",
            "resolution":"0.5",
            "type": "writers.gdal"
        }
    ]
}
`
I have zipped the DTM file
[dtm-b.zip](https://github.com/PDAL/PDAL/files/7792657/dtm-b.zip)

**Comment by abellgithub** [comment]
You can try using the `window_size` option, but otherwise, there is currently no support for filling missing data.

**Comment by shubham9436** [comment]
> You can try using the `window_size` option, but otherwise, there is currently no support for filling missing data.

What could be the optimal `window_size` that generally fills the missing data?

**Comment by abellgithub** [comment]
It depends on your data. You might use something like `gdal_fillnodata` or another raster processing program.

Whether the algorithm is reasonable depends totally on your data. One would have to understand *why* the data was missing in order to evaluate an algorithm.

**Comment by shubham9436** [comment]
The reason behind missing the data in between is because I have separated the ground and non ground point cloud. So, buildings, trees have been removed from the point cloud (in ground point cloud) and hence they create gaps. Hence, it should not be filled with no data. I just want it to be interpolated.
