### ISSUE TITLE
Writing an LAZ file with lazperf and 0 points crashes

### ISSUE THREAD

**Issue by abellgithub** [PDAL/PDAL#3652]

**Comment by klassenjs** [comment]
My guess is LazPerfVlrCompressorImpl::compress() is never getting called, so m_compressor is null, but that condition isn't being checked in LazPerfVlrCompressorImpl::done() before calling m_compress->done().  I'm not sure how much of LazPerfVlrCompressorImpl::done() should be skipped if m_compressor is null (there were no points to process).

I've verified that m_compress is null in LazPerfVlrCompressorImpl::done() when the crash occurs.

**Comment by abellgithub** [comment]
Fixed by https://github.com/PDAL/PDAL/pull/3657
