### ISSUE TITLE
Cannot compile PDAL with LAZPERF

### ISSUE THREAD

**Issue by julienlau** [PDAL/PDAL#3655]
Hi,
I observe that last docker image does not embed LAZPERF : 
> docker run -it -v "$PWD":/mnt pdal/pdal:2.3.0 /mnt/time -v pdal translate --writers.las.compression=lazperf -i /mnt/${las} -o /mnt/${las%%.las}.laz
> PDAL: writers.las: Can't write LAZ output. PDAL not built with LAZperf.

So I wanted to build PDAL on ubuntu 20.04 from scratch using last release of LAZPERF: 3.0.0 and PDAL 2.3.0.

LAZPERF 3.0.0 install ok with following commands:
```
    cd /home/opt/laz-perf-3.0.0/
    mkdir build
    cd build
    cmake ..
    make
    sudo make install
```

LAZPERF 2.1.0 install ok with following commands:
```
    cd /home/opt/laz-perf-2.1.0/
    mkdir build
    cd build
    cmake ..
    make
```

PDAL install ok without LAZPERF links:
```
    cd /home/opt/laz-perf-2.1.0/
    mkdir build
    cd build
    cmake -G "Unix Makefiles" -DLAZPERF_DIR=/home/opt/laz-perf-3.0.0/build -DWITH_LAZPERF=OFF ..
    make
```

However cmake crash without  -DWITH_LAZPERF=OFF.
I think something is wrong with the "pthread" test but I don't know how to fix it:
The error is the same with Lazperf 2.1.0 and 3.0.0:
```
tail  /home/opt/PDAL-2.3.0-src/build/CMakeFiles/CMake*.log
==> /home/opt/PDAL-2.3.0-src/build/CMakeFiles/CMakeError.log <==
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_9a018.dir/link.txt --verbose=1
/usr/bin/cc  -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTC_9a018.dir/CheckFunctionExists.c.o  -o cmTC_9a018  -lpthreads 
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
make[1]: *** [CMakeFiles/cmTC_9a018.dir/build.make:87: cmTC_9a018] Error 1
make[1]: Leaving directory '/home/opt/PDAL-2.3.0-src/build/CMakeFiles/CMakeTmp'
make: *** [Makefile:121: cmTC_9a018/fast] Error 2


==> /home/opt/PDAL-2.3.0-src/build/CMakeFiles/CMakeOutput.log <==
make[1]: Entering directory '/home/opt/PDAL-2.3.0-src/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_d121b.dir/CheckFunctionExists.c.o
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_d121b.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.16/Modules/CheckFunctionExists.c
Linking C executable cmTC_d121b
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_d121b.dir/link.txt --verbose=1
/usr/bin/cc  -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTC_d121b.dir/CheckFunctionExists.c.o  -o cmTC_d121b  -lpthread 
make[1]: Leaving directory '/home/opt/PDAL-2.3.0-src/build/CMakeFiles/CMakeTmp'

```

**/usr/bin/ld: cannot find -lpthreads**

from my test "-lpthreads" library is not available on my system but "-lpthread" is OK.
I cannot see how to skip the pthread tests and force make to directly use "-lpthread"
or any other way to fix the pthread tests

Any help appreciated !

In addition, I observe that the dockerfile I found on github  let me think that PDAL should have been built with LAZPERF linking as the flag would let think :
`        -DWITH_LAZPERF=ON \`
except LAZPERF library is not included in the image https://github.com/PDAL/PDAL/blob/master/scripts/docker/ubuntu/Dockerfile  or its base image https://github.com/PDAL/PDAL/blob/master/scripts/docker/ubuntu/Dockerfile.dependencies

**Comment by abellgithub** [comment]
The dockerfile you list does not use the 2.3 release, it uses PDAL master. PDAL master requires lazperf.

**Comment by julienlau** [comment]
Problems : 
1/ docker image pdal/pdal:2.3.0 does not allow using `translate --writers.las.compression=lazperf`
Is there any other docker image providing this ?

2/ cmake on pdal crash when linking with LAZPERF probably due to some mix-up between the pthread check in these two projects ?
` /usr/bin/ld: cannot find -lpthreads`

**Comment by abellgithub** [comment]
1) We don't provide one.

2) It's hard to know what's wrong with the information you've provided. I have not recently seen an error regarding thread libraries.  Perhaps it's unique to your system. You should look at the scripts that we use to build PDAL daily to see if they help: https://github.com/PDAL/PDAL/tree/master/scripts/ci/linux
