### ISSUE TITLE
write point clouds with color to ply

### ISSUE THREAD

**Issue by avispi** [PDAL/PDAL#3656]
Hi.
Im trying to read las and save as ply.
the las has xyzrgb.
I see the rgb darta when I open the ply as text but it doesnt open in any software (i.e cloud compare) as a cloud with colors.

**Comment by abellgithub** [comment]
You're not provided enough information to determine if there is a problem or what the problem might be if there is one.

I would suggest trying to figure out why cloud compare or other software won't load the file as you expect.

I'm closing this ticket, but reopen if you can determine that PDAL has a bug and you can provide details.
