### ISSUE TITLE
Sync Docker image

### ISSUE THREAD

**Issue by gsakkis** [PDAL/PDAL#3658]
The latest PDAL Docker image comes with TileDB 2.3 instead of 2.6 which is installed by [conda](https://github.com/conda-forge/pdal-feedstock/commit/bc9604de986957c3222203c7237e223702a9b9f0).

More generally, it would be nice to keep the Docker image in sync with Conda when any PDAL dependency changes.

**Comment by hobu** [comment]
I presume this is a matter of updating https://github.com/PDAL/PDAL/blob/master/scripts/docker/ubuntu/Dockerfile.dependencies and then @abellgithub pushing a new PDAL dependencies container.
