### ISSUE TITLE
Feature Request : implement potree2 reader

### ISSUE THREAD

**Issue by julienlau** [PDAL/PDAL#3660]
Potree2 now provides : 
- a more efficient datalayer : single datafile instead of a myriad of small files.
- in a lot of case potree data loss is 0% (at least it was the case from my experience with potree1.8)

In such scenario it could be useful to provide read capability on Potree2 datasets so that LAZ files could be stored in inexpensive tapes/glacier storage and potree2 could be used for analytics with PDAL.

Potree writer would also be nice in PDAL, but since PotreeConverter is already super efficient I am not sure the added value would be great compared to pdal reader.potree... in fact there are no tools that I know doing conversion from Potree to LAZ.

Thanks and regards

**Comment by hobu** [comment]
Potree2 is implementing COPC support. If it was clear that Potreeconverter2 output was being used as a data interchange throughout the industry, we would consider merging a pull request implementing it. Given that Potree2 is going to support COPC, however, and the convenience that COPC provides for interchange with LAZ, this is not something on our roadmap.

**Comment by julienlau** [comment]
I know about COPC, but I do not agree there is no space for a potree reader. 
From my tests generating a Potree is ~50x faster using PotreeConverter than using entwine or untwine.
My use case rely on this to perform dataset updates.
I periodically rebuild octrees to manage updates.

Still I understand COPC is a higher priority in the roadmap.

**Comment by hobu** [comment]
> I know about COPC, but I do not agree there is no space for a potree reader.

As I said, *we* are not implementing such a thing.

@m-schuetz has indicated that he was working to add COPC output to Potreeconverter2 as well.

**Comment by m-schuetz** [comment]
Yeah, I'm planning on doing COPC output format for PotreeConverter together with WebGPU-based Potree rewrite. I'm guessing this might take half a year, which somewhat reflects the expected (but not guaranteed) release date of WebGPU in chrome.
