### ISSUE TITLE
Feature Request : implement new format for streaming LAS+snappy compression 

### ISSUE THREAD

**Issue by julienlau** [PDAL/PDAL#3661]
Hi,

In the field of compressor gzip is optimized for better compression ratio and is not recommended for streaming pipelines.

snappy is the most standard algorithm when doing streaming pipeline since compression throughput is very high and compression ratio not too bad. This is for example the compressor used in Cassandra NoSQL-DB and on datalakes using Parquet format.

Since PDAL support streaming pipelines I would suggest supporting a LAS+snappy format. I don't know if should still be named LAS, maybe LASS but it may be useful to improve global throughput of streaming pipelines.

Thanks and regards

**Comment by hobu** [comment]
LAS is designed to be a mmap'able data structure, and LAZ is a storage-efficient compression of that data structure that sacrifices the mmap'able feature (although it does store the data in seekable chunks). Our experimentation with gzip-style approaches got us at best ~2x compression and destroyed the mmap'ability of the data in the process. LAZ regularly gets 5x compression. At scale, that storage and network transmission cost difference can be quite large. 

If you make a LASS format, what is it actually good for relative to LAZ? It is going to decompress and compress faster, for sure, but it is going to take up a lot more disk, a lot more network bandwidth to transmit, and you're going to always have to transform it into a different format to archive it or interchange unless you permeate LASS support throughout the software industry. I talked about tradeoff and why we developed toward COPC in a recent presentation https://www.youtube.com/watch?v=-EmcW2UWD4k&t=5591s 

Additionally, these kinds of tickets are more appropriate for discussion on the PDAL mailing list https://pdal.io/community.html#mailing-list unless they have software attached to them. "Feature Request" seems like you are asking us to implement something without financial support and the research to show its consequences relative to existing approaches.
