### ISSUE TITLE
Converting Lidar .las / .laz to .tif 

### ISSUE THREAD

**Issue by RitaAguiar** [PDAL/PDAL#3688]
I would like to suggest a new feature to be able to convert a lidar .las / .laz to a .tif file.
Does PDAL provide an automated functionality to do this without requiring to install a software?

**Comment by hobu** [comment]
> I would like to suggest a new feature to be able to convert a lidar .las / .laz to a .tif file.

https://pdal.io/workshop/exercises/analysis/dtm/dtm.html provides one example of using PDAL to construct DTMs. 


> Does PDAL provide an automated functionality to do this without requiring to install a software?

No.

Please refrain from posting questions like this on bug tracking systems of software you are researching. One such very recent example of the same question is at https://github.com/laspy/laspy/issues/203. Bug trackers like this are for coordinating the development of the software, and are not an efficient venue for help like this. If you are completely unfamiliar with the software, tools, and approaches of the space, I would suggest identifying and hiring a consultant to help you navigate.
