### ISSUE TITLE
Feature Request - writers.slpk (readers.slpk already exists)

### ISSUE THREAD

**Issue by geoeki** [PDAL/PDAL#3707]
A single I3S data set, referred to as a Scene Layer, is a container for arbitrarily large amounts of heterogeneously distributed 3D geographic data. Scene Layers are designed to be used in mobile, desktop, and server-based workflows and can be accessed over the web or as local files. [It's based on open OGC specifications.](https://www.ogc.org/standards/i3s)

PDAL offers a [readers.slpk](https://pdal.io/stages/readers.slpk.html) already, we'd find a slpk writer in PDAL extremely useful as slpks are a great open web format. It's an open format ([Point Cloud Scene Layers](https://github.com/Esri/i3s-spec/blob/master/docs/2.0/pcsl_ReadMe.md)), but so far only proprietary software like Pix4D, FME or ArcGIS Pro can write slpk files from point clouds.

**Comment by hobu** [comment]
> we'd find a slpk writer in PDAL extremely useful as slpks are a great open web format

Only substantial funding or a pull request providing an implementation is going to make this request materialize into features in the PDAL codebase.
