### ISSUE TITLE
Prevent user from losing their data if input and output file path are the same

### ISSUE THREAD

**Issue by kannes** [PDAL/PDAL#3717]
This is a feature request, not a bug report (at least in my view).

If a user (hello!) accidentally specifies the output file path to be the same as the input file path, their file will be truncated and PDAL will stop with an error:

```
$ ls -sh file.laz 
703M file.laz
$ pdal translate -i file.laz -o file.laz 
PDAL: Unexpected end of file.
$ ls -sh file.laz 
0 file.laz
```

It would be awesome if PDAL would recognize user-supplied nonsense like that and quit with an error before the damage is done.

GDAL's ogr2ogr for example does it like this:
```
$ ogr2ogr -f GPKG asd.gpkg asd.gpkg
ERROR 1: Source and destination datasets must be different in non-update mode.
```

**Comment by hobu** [comment]
Done in #3794

**Comment by kannes** [comment]
Awesome, thank you!
