### ISSUE TITLE
Improve error message for `pdal info` for non-existent copc.laz files

### ISSUE THREAD

**Issue by TomAugspurger** [PDAL/PDAL#3723]
**Describe the bug**

The current error message for `pdal info foo.copc.laz` makes it sound like there's a problem with the LAZ encoding of a file, when really the file isn't present

```
$ pdal info foo.copc.laz
PDAL: readers.copc: Invalid LAS header in COPC file
```

**Expected behavior**

The error message for a non-existent `foo.laz` is clearer

```
$ pdal info foo.laz
PDAL: Unable to open stream for 'foo.laz' with error 'No such file or directory'
```

**System/installation information:**
Please provide information on your PDAL version (`pdal --version`) and system (e.g., `uname -a` or `ver`).

```
$ uname -a
Linux 75b6487243e8 5.10.60.1-microsoft-standard-WSL2 #1 SMP Wed Aug 25 23:20:18 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ pdal --version
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
pdal 2.3.0 (git-version: 64d396)
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


```

**Comment by hobu** [comment]
I think you might have an older PDAL. This was updated before the PDAL 2.4 release to be a more helpful error message

**Comment by TomAugspurger** [comment]
Huh, I have `pdal --version` outputting

```
pdal 2.3.0 (git-version: 64d396)
```

Ahh... right now I'm on a branch https://github.com/pdal/pdal/tree/arbiter-updates-with-copc-reader which might not have that.
