### ISSUE TITLE
Additionnal datum not included anymore in docker image >2.1

### ISSUE THREAD

**Issue by julienlau** [PDAL/PDAL#3745]
**Describe the bug**
When I read the header my LAS file with a version of PDAL > 2.2 it is not correctly parsed whereas it is OK with 2.1 or 2.0. Vertical CRS is null.

```
$ pdal info in.las --metadata
```
gives 

- "pdal_version": "2.0.1 (git-version: Release)" :
```
      "units":
      {
        "horizontal": "US survey foot",
        "vertical": "US survey foot"
      },
      "vertical": "VERT_CS[\"unknown\",VERT_DATUM[\"unknown\",2005],UNIT[\"US survey foot\",0.304800609601219,AUTHORITY[\"EPSG\",\"9003\"]],AXIS[\"Up\",UP]]"
```
- "pdal_version": "2.3.0 (git-version: c05871)" :
```
      "units":
      {
        "horizontal": "US survey foot",
        "vertical": ""
      },
      "vertical": ""
```
</details>

**Expected behavior**
header should still be interpreted the same as before 

**System/installation information:**
Linux apt or docker images

**Probable solutions**

I saw in docker images that this part is missing since v2.2:
```
RUN \
    mkdir gridzip && \
    cd gridzip && \
    curl -LOs http://download.osgeo.org/proj/proj-datumgrid-1.8.zip &&  unzip -j -u -o proj-datumgrid-1.8.zip  -d /usr/share/proj && rm proj-datumgrid-1.8.zip ; \
    curl -LOs http://download.osgeo.org/proj/proj-datumgrid-europe-1.2.zip &&  unzip -j -u -o proj-datumgrid-europe-1.2.zip -d /usr/share/proj && rm proj-datumgrid-europe-1.2.zip ; \
    curl -LOs http://download.osgeo.org/proj/proj-datumgrid-oceania-1.0.zip &&  unzip -j -u -o proj-datumgrid-oceania-1.0.zip -d /usr/share/proj && rm proj-datumgrid-oceania-1.0.zip; \
    curl -LOs http://download.osgeo.org/proj/proj-datumgrid-world-1.0.zip &&  unzip -j -u -o proj-datumgrid-world-1.0.zip -d /usr/share/proj && rm proj-datumgrid-world-1.0.zip; \
    curl -LOs http://download.osgeo.org/proj/proj-datumgrid-north-america-1.2.zip &&  unzip -j -u -o proj-datumgrid-north-america-1.2.zip -d /usr/share/proj && rm proj-datumgrid-north-america-1.2.zip


```

**Comment by hobu** [comment]
> When I read the header my LAS file with a version of PDAL > 2.2 it is not correctly parsed whereas it is OK with 2.1 or 2.0. Vertical CRS is null.

PROJ was updated to support the [PROJ CDN](https://cdn.proj.org/). If you set `PROJ_NETWORK=ON` in your environment, PROJ should call out to the CDN to fetch its grids in a lazy fashion. Please reopen with any specific issues related to this behavior.
