### ISSUE TITLE
PDAL:Readers.las unable to read a large size las file

### ISSUE THREAD

**Issue by narayaba** [PDAL/PDAL#3749]
I get the following error when using pdal in linux. 
PDAL: readers.las: Invalid point count: 252159048. Number of points too large for file size.

On windows reading the same las file does not yield an error. 

OS is centos 7 
pdal version is 3.1.2
python-pdal is also 3.1.2

**Comment by abellgithub** [comment]
This error is saying that file is too small given the point count and point type information in the header. The code that tests this is the same on Windows, so perhaps you had an error when copying the file. Perhaps you should run some sort of checksum program. You could also run lasinfo (from [lastools](http://lastools.org/)) if you don't trust the PDAL output.
