### ISSUE TITLE
error when using transformation matrix that starts with a negative number

### ISSUE THREAD

**Issue by philwilkes** [PDAL/PDAL#3752]
I am trying to pass a rotation matrix to `--filters.transformation` but I get this error

> PDAL: kernels.translate: Unexpected argument '-.'.

The string I am passing is this:

> "-0.0044437434716889 -0.0227128914991981 -0.9997321529808388 -0.2746913430631829
-0.0208533086029720 0.9995267266034600 -0.0226155328409836 -0.0035802080536322
0.9997726704927808 0.0207472254800022 -0.0049152793018213 -0.2806760485514632
0.0000000000000000 0.0000000000000000 0.0000000000000000 1.0000000000000000"

Which I generate this using ` "$(cat ../matrix/ScanPos002.DAT)"`. If I pass the string directly I get the same error. 

Matrices that start with positive numbers work OK even if they include negative numbers.

Full command I am running in this:

`pdal translate -i ../ScanPos${sp}/??????_??????.rxp -o ${sp}.ply filters.transformation filters.voxelcentroidnearestneighbor --filters.voxelcentroidnearestneighbor.cell 0.2 --writers.ply.storage_mode 'little endian' --readers.rxp.sync_to_pps "false" --writers.ply.dims "X,Y,Z,reflectance,deviation,InternalTime" --filters.transformation.matrix "$(cat ../matrix/ScanPos${sp}.DAT)"`

**Comment by abellgithub** [comment]
See #2062
