### ISSUE TITLE
Differences between PDAL Anaconda and PDAL Docker

### ISSUE THREAD

**Issue by Raventech-x21** [PDAL/PDAL#3762]
I am trying to use filters.crop on a LAZ file and I am experiencing different behaviour between running PDAL via Anaconda on Windows, and the PDAL [Docker image](https://hub.docker.com/r/pdal/pdal/). Both are running PDAL 2.4. When executing the crop using Anaconda it works fine with no errors. Using the exact same process in the Docker image gives me the following error;

ERROR 1: PROJ: Unrecognized horizontal grid format for filename 'au_icsm_GDA94_GDA2020_conformal_and_distortion.tif'

Is anybody able to explain why this is and how to fix it in the Docker image?

**Comment by abellgithub** [comment]
Have you checked PROJ versions? It seems they are different.

**Comment by Raventech-x21** [comment]
I have checked and PROJ is v9.0.0 in Anaconda and v8.2.0 in the Docker image. Updating to PROJ v9.0.0 doesn't resolve the problem, however your suggestion has pointed my in the right direction, so I think I'll be able to solve this.
