### ISSUE TITLE
escapeJSON can produce invalid JSON

### ISSUE THREAD

**Issue by abellgithub** [PDAL/PDAL#3772]
Utils::escapeJSON assumes that the input string contains only ASCII characters. If bytes not representing ASCII characters (bytes with the high bit set) are contained, they are left in place, which *may* result in output that isn't valid JSON as the bytes won't likely be valid UTF code points. Not sure what we should do. Perhaps a string should trim all data when it encounters an invalid UTF-8 code point. In any case, we should produce valid JSON.

**Comment by hobu** [comment]
Addressed in #3906
