### ISSUE TITLE
Interface to R

### ISSUE THREAD

**Issue by t-wojciech** [PDAL/PDAL#3775]
Are there plans to create an interface to R? There is currently [lidR](https://github.com/r-lidar/lidR) package for point cloud processing, but it would also be nice to use PDAL.

**Comment by hobu** [comment]
No intentions by the current PDAL development team to implement an R interface, but we would be happy to support an enthusiastic contributor by providing an organization repo at https://github.com/PDAL 

We would not support implementation of the bindings *inside* the main PDAL source tree. We made that mistake with Python and it took ~10 releases to fix it.

**Comment by hobu** [comment]
Closing for now. If someone starts an R interface and wants to initiate a repository in https://github.com/PDAL please reopen and we will get you set up.
