### ISSUE TITLE
filters.zsmooth does not appear in --drivers nor being recognized by pdal 2.4.2

### ISSUE THREAD

**Issue by siparcs** [PDAL/PDAL#3783]
**Describe the bug**
After two days, I suspect a bug but was unable to locate the problem.

filters.zsmooth is being compiled and linked (using ninja), and installed including header file
(-- Installing: /usr/local/include/pdal/filters/ZsmoothFilter.hpp), 
but is not being recognized when using pdal command and not listed in --drivers list.

Is there something missing or a typo that this filter is not showing up?

$ pdal pipeline xcloud_dsm_job.json --readers.text.filename=./tmp_xcloud.csv --writers.las.filename=./tmp_xcloud.laz
still results in:
PDAL: **Couldn't create filter stage of type 'filters.zsmooth'**.
You probably have a version of PDAL that didn't come with a plugin
you're trying to load.  Please see the FAQ at https://pdal.io/faq

FAQ states modifying CMakeCache.txt for plugins, but if I see it correctly, ZsmoothFilter should be an internal filter and not a plugin (and is not being mentioned in this file)
```

<details>
  
```
head -5 ./tmp_xcloud.csv 
x y z gray Red Green Blue disparity diff_3d_lines confidence
2808289.359397 1173430.700949 1909.208293 130 255 255 255 89 1900191
2808290.028459 1173430.927982 1909.878469 93 255 255 255 94 1900191
2808290.594260 1173430.726750 1909.882454 67 255 255 255 76 1900191
2808291.164550 1173430.544207 1909.915501 87 255 255 255 99 1900191

cat $SFM/templates/xcloud_dsm_job.json
{
    "pipeline": [
	{
	    "type":"readers.text",
	    "header":"X Y Z Intensity Red Green Blue UserData UserData2",
            "skip":1
	},
	{
	    "type":"filters.outlier",
	    "method":"statistical",
	    "mean_k":20,
	    "multiplier":2.2
	},
	{
	    "type":"filters.zsmooth",
	    "medianpercent":50,
	    "radius":1.5,
	    "dim":"Zadj"
	},
        {
            "type": "filters.assign",
            "value": "Z = Zadj"
        },
	{
	    "type":"filters.elm",
	    "threshold":2.0
	},
	{
            "type":"writers.las",
	    "forward": "all"
	}
    ]
}
```

</details>

**Expected behavior**
filters.zsmooth should be recognized

**System/installation information:**
pdal --version: 
uname -a: 

```
$ uname -a
Linux xxx 5.18.2-1-default SMP PREEMPT_DYNAMIC Tue Jun 7 06:08:54 UTC 2022 (695cfee) x86_64 x86_64 x86_64 GNU/Linux
```

```
$ pdal --version
pdal 2.4.2 (git-version: Release)
```

**Comment by siparcs** [comment]
Being a bad programmer, tried to find the problem anyway.
Changing line 53 in ZsmoothFilter.cpp from 
CREATE_SHARED_STAGE(ZsmoothFilter, ptstatInfo)
to 
CREATE_STATIC_STAGE(ZsmoothFilter, ptstatInfo)
made it work, both appearing in --drivers list and being found by pdal.

Maybe it is not the correct way of solving, but might give a hint where the problem is hiding...

**Comment by abellgithub** [comment]
This is the correct fix. I've already submitted this PR: https://github.com/PDAL/PDAL/pull/3785
