### ISSUE TITLE
Unable to fetch data and convert as requested when convert PCD to LAS

### ISSUE THREAD

**Issue by alanwanga** [PDAL/PDAL#3784]
**Describe the bug**
A clear and concise description of what the bug is, including steps to reproduce the behavior. This typically means providing the PDAL commands you are using (e.g., `pdal translate ...`) and if applicable the contents of any PDAL pipelines you are running.

```
$ pdal translate ./in.pcd ./out.las
```

<details>
  
```
{
  "pipeline":[
    "in.las",
    "out.las"
  ]
}
```

</details>

**Expected behavior**
I want to convert pcd to las but error occurred.
`PDAL: Unable to fetch data and convert as requested: Intensity:uint32_t(8.88154e+06) -> unsigned short`

Here is the header of input PCD:
```
"header = \"\"\"# .PCD v0.7 - Point Cloud Data file format\n",
"VERSION 0.7\n",
"FIELDS x y z intensity\n",
"SIZE 4 4 4 4\n",
 "TYPE F F F U\n",
"COUNT 1 1 1 1\n",
"WIDTH {}\n",
"HEIGHT 1\n",
"VIEWPOINT 0 0 0 1 0 0 0\n",
"POINTS 11934991\n",
"DATA ascii\n",
```

**System/installation information:**
Please provide information on your PDAL version (`pdal --version`) and system (e.g., `uname -a` or `ver`).

```
$ uname -a
```
Darwin CHCSMR-TWANG 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 x86_64
```
$ pdal --version
```
pdal 2.4.2 (git-version: Release)

I've tried serval commands (e.g. --writer.pcd.xyz=true) but it still doesn't work out. I only need xyz. Please help.

**Comment by abellgithub** [comment]
Please see item #3 in the [FAQ](https://pdal.io/faq.html)
