### ISSUE TITLE
Unable to read file created with copc writer using arbiter

### ISSUE THREAD

**Issue by msmitherdc** [PDAL/PDAL#3804]
output dataset at s3://grid-dev-publiclidar/public/angry_data/copc/L3432A1.copc.laz
input dataset at s3://grid-dev-publiclidar/public/angry_data/copc/L3432A1.laz

trying to read yields 
```
PDAL: readers.copc: Invalid LAS header in COPC file
```

**Comment by hobu** [comment]
Should be fixed by 006d06dc46d6667d5989dc367966ee0581bf6f69 reopen if not
