### ISSUE TITLE
las to bpf with GPM

### ISSUE THREAD

**Issue by ccollard24** [PDAL/PDAL#3805]
Could a pipeline be developed and tested for pdal to convert las files to bpf and preserve the GPM?

**Comment by hobu** [comment]
* Read the metadata from the LAS file, and use `jq` or something like it to write it to files with the names that you need
* Use multiple `bundledfile` options on `writers.bpf` to point at those files and they will be included in the BPF file

Please use GitHub for bugs or development, not support questions. The [PDAL Mailing List](https://pdal.io/community.html#mailing-list) is more appropriate for these types of questions.
