### ISSUE TITLE
PDAL in Embarcadero C++ Builder

### ISSUE THREAD

**Issue by Tobi1974** [PDAL/PDAL#3807]
Hallo,
did have anyone some experience how to use the PDAL library in C++ Builder? 

I made an test project but I can not create without:

[bcc32c Fehler] pdal_util_internal.hpp(46): "WIN32 without MSVC. Expected __MINGW32__ but not found."

Thanks for any help.

Tobias

**Comment by hobu** [comment]
This doesn't appear to be a specific bug in PDAL at this time. Please ask questions on the [mailing list](https://pdal.io/community.html) if they are specific to PDAL usage.
