### ISSUE TITLE
litree infiniti loop

### ISSUE THREAD

**Issue by Ja-Mong** [PDAL/PDAL#3810]
The litree operation is not smooth.

Same problem as litree #3518. It's been 24 hours and it's still running.

The lidar data I used is less than 1GB of data.

I need help to get litree up and running normally..!

this is my pipeline:
![화면 캡처 2022-07-12 095308](https://user-images.githubusercontent.com/62415956/178384870-b226d1f3-fb1d-429a-8b53-578fd3889885.png)

**Comment by abellgithub** [comment]
You need to provide data that recreates the problem.

**Comment by Ja-Mong** [comment]
hi!!!

this is my pipeline process and lidar data info


![화면 캡처 2022-07-12 164956](https://user-images.githubusercontent.com/62415956/178438182-b9f132d0-2226-4f29-a781-411af0fc0582.png)

![화면 캡처 2022-07-12 165008](https://user-images.githubusercontent.com/62415956/178438210-abc95239-74ac-4d40-91fc-0cad09811c37.png)

![화면 캡처 2022-07-12 165300](https://user-images.githubusercontent.com/62415956/178438594-385a7758-1764-4ef2-9acb-ed27a3eff8a9.png)

**Comment by Ja-Mong** [comment]
I accidentally pressed Done Issue. The problem still exists.

**Comment by abellgithub** [comment]
Please don't post screen shots.

You need to find a MINIMAL pipeline and provide it with the minimum data set that exhibits the problem.

**Comment by Ja-Mong** [comment]
my pipeline:

1. read las data
2. subsampling
3. outlier removal
4. ground extraction using smrf
5. litree => run continuously


All of the above steps were used to extract individual trees using litree.
The ground extraction is successful, but there is no output even if it takes a lot of time in the litree part.

**Pipeline**
*[
  {
    "type":"filters.hag_nn"
  },
  {
    "type":"filters.ferry",
    "dimensions":"HeightAboveGround=>Z"
  },
  {
    "type":"filters.sort",
    "dimension":"HeightAboveGround",
    "order":"DESC"
  },
  {
    "type":"filters.litree",
    "min_points":15,
    "min_height":10.0,
    "radius":2.0
  },
  {
    "type": "writers.las",
    "filename": "t_output.las"
  }
]

**Command**
*pdal pipeline test.json

**System info**
PDAL Version"2.4.2 (git-version: Release) 

lidar data zip file size is too big(480MB) so, if you give a e-mail address i will send test_las.zip data

**Comment by abellgithub** [comment]
Are all these steps required to reproduce the problem? Have you tried to find a smaller set of steps that reproduce the problem? Have you removed stages one by one? Have you tried creating a subset of points that reproduces the problem? I find it hard to believe that a 480 meg file is necessary to create the problem.

If you want to pay for support, you should contact info@hobu,co, but otherwise, you should do some work to minimize the issue so that the problem is clear.

**Comment by Ja-Mong** [comment]
Its pipeline is almost identical to the example in pdal filters.litree. (except for the filters.ferry part)

The initial data size of the lidar I used was 1GB, and it was reduced to 469MB through subsampling, outlier removal, SMRF, etc..!

Except for litree, steps 2, 3, and 4 all work normally, and I checked the output with plas.io.

Here's a slightly smaller file. (This file is a completed file including subsamping, outlier removal, and ground filter.)

[t_output.zip](https://github.com/PDAL/PDAL/files/9092706/t_output.zip)
[treeSeg_litree.zip](https://github.com/PDAL/PDAL/files/9092734/treeSeg_litree.zip)

**Comment by chambbj** [comment]
My hunch is that your inclusion of the ferry filter is causing problems. A KD-tree is built internally, and although it may seem as though a KD-tree built from HAG wouldn't be all that different from one built with Z, it is the key difference between your pipeline and the examples.

**Comment by chambbj** [comment]
There is a big difference here. The example in #3520 was about 100,000 points, with density of about 3 points per sq meter. Your example is over 2,000,000 points, with a density of nearly 1800 points per sq meter. One possible optimization would be to run litree on a subsampled dataset to get the rough cluster IDs, as I think you've already discovered. Anyway, I don't think there is a bug here per se. It's just not a great algorithm for gobs of dense data.
