### ISSUE TITLE
PDAL: Unable to open stream for ' ' with error 'No error'

### ISSUE THREAD

**Issue by davidpp9** [PDAL/PDAL#3825]
Hi everyone

Following pipeline is been tried to run: 

{
	"pipeline": [
		"C:/nicola/2021_a2q/AQ2_618_5586_UTM10_GrDef_SP000-3430_AP000-3430_v1.laz",
		{
			"type": "filters.range",
			"limits": "Classification[2:2]"
		},
		{
			"filename": "D:/nicola/output_2021_hsb/dem2/HSB_618_5586.tif",
			"gdaldriver": "GTiff",
			"output_type": "mean",
			"resolution": 1,
			"type": "writers.gdal"
		}
	]
}

When the pipeline is executed in the conda prompt following error pops up: 

(pc2dem) C:\Users\dpuhl>pdal pipeline "C:/Users/dpuhl/Documents/nicola/pipeline.json"
PDAL: Unable to open stream for 'C:/nicola/2021_a2q/AQ2_618_5586_UTM10_GrDef_SP000-3430_AP000-3430_v1.laz' with error 'No error'

I don't understand what the error is, especially since the error message says 'No error'

Thanks

**Comment by abellgithub** [comment]
We've seen this before but I don't remember what's up. Are things working
despite the message? What version are you using? You might check the
mailing list archive to see if you see anything similar.

**Comment by davidpp9** [comment]
No, things are not working unfortunately. I used version 2.4.1. Couldn't figure out how to fix it, so I'm using pdal / python (3.1.2) instead now and that seems to work.

**Comment by hobu** [comment]
https://gis.stackexchange.com/questions/436659/pdal-unable-to-open-stream-for
