### ISSUE TITLE
Unable to build PDAL from source, Linking CXX executable bin/lasdump

### ISSUE THREAD

**Issue by jsmoreau** [PDAL/PDAL#3826]
I'm trying to build PDAL 2.4.2 from source in a docker container.
GDAL 3.4.0 has already been built and is available.
My base docker image is python:3.8-slim-buster.
I followed the build instructions described here: https://pdal.io/development/compilation/unix.html

Here's the `cmake -G Ninja` output:
```
cmake: /usr/local/lib/libcurl.so.4: no version information available (required by cmake)
-- The CXX compiler identification is GNU 8.3.0
-- The C compiler identification is GNU 8.3.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found GDAL: /usr/local/lib/libgdal.so (Required is at least version "3.0")
-- Found GeoTIFF: /usr/local/lib/libgeotiff.so
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11")
-- Found LibXml2: /usr/lib/x86_64-linux-gnu/libxml2.so (found version "2.9.4")
-- Found CURL: /usr/local/lib/libcurl.so (found version "7.73.0")
-- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY OPENSSL_INCLUDE_DIR) (Required is at least version "1.1")
OpenSSL NOT found - `export OPENSSL_ROOT_DIR=___`
Google storage IO will not be available
-- Found PythonInterp: /usr/local/bin/python (found version "3.8.13")
-- Could NOT find LIBEXECINFO (missing: LIBEXECINFO_LIBRARY)
-- Could NOT find LIBUNWIND (missing: LIBUNWIND_LIBRARY LIBUNWIND_INCLUDE_DIR)
-- The following features have been enabled:

 * Unit tests, PDAL unit tests

-- The following OPTIONAL packages have been found:

 * ZSTD
   General compression support
 * LibXml2
 * PkgConfig
 * PythonInterp

-- The following REQUIRED packages have been found:

 * GDAL (required version >= 3.0)
   Provides general purpose raster, vector, and reference system support
 * GeoTIFF
 * ZLIB
   Compression support in BPF
 * CURL
 * Threads, The thread library of the system

-- The following features have been disabled:

 * Bash completion, completion for PDAL command line
 * CPD plugin, Coherent Point Drift (CPD) computes rigid or nonrigid transformations between point sets
 * Draco plugin, Read data in the draco format
 * I3S plugin, Read from a I3S server or from a SLPK file
 * Icebridge plugin, read data in the Icebridge format
 * HDF plugin, read data in the HDF format
 * Matlab plugin, write data to a .mat file
 * NITF plugin, read/write LAS data wrapped in NITF
 * OpenSceneGraph plugin, read/write OpenSceneGraph objects
 * PostgreSQL PointCloud plugin, read/write PostgreSQL PointCloud objects
 * RiVLib plugin, read data in the RXP format
 * rdblib plugin, read data in the RDB format
 * MBIO plugin, add features that depend on MBIO
 * FBX plugin, add features that depend on FBX
 * TEASER++ plugin, TEASER++ computes transformations between point sets
 * TileDB plugin, read/write data from TileDB
 * E57 plugin, read/write data to and from e57 format

-- The following OPTIONAL packages have not been found:

 * PostgreSQL
 * OpenSSL (required version >= 1.1)
 * absl
 * Libexecinfo
 * Libunwind

-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/PDAL-2.4.2-src/build
```

I got the following error:
```
[234/513] Linking CXX static library lib/libgtest.a
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[235/513] Linking CXX static library lib/libgtest_main.a
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[353/513] Linking CXX static library lib/libpdal_arbiter.a
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[357/513] Linking CXX static library lib/libpdal_kazhdan.a
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[377/513] Linking CXX static library lib/libpdal_lazperf.a
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[386/513] Creating library symlink lib/libpdal_util.so.14 lib/libpdal_util.so
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[389/513] Linking CXX executable bin/lasdump
FAILED: bin/lasdump
: && /usr/bin/c++     tools/lasdump/CMakeFiles/lasdump.dir/Dumper.cpp.o tools/lasdump/CMakeFiles/lasdump.dir/Header.cpp.o  -o bin/lasdump  -Wl,-rpath,/tmp/PDAL-2.4.2-src/build/lib lib/libpdal_util.so.14.2.0 lib/libpdal_lazperf.a && :
/usr/bin/ld: lib/libpdal_util.so.14.2.0: undefined reference to `std::filesystem::__cxx11::path::parent_path() const'
/usr/bin/ld: lib/libpdal_util.so.14.2.0: undefined reference to `std::filesystem::__cxx11::directory_iterator::operator*() const'
/usr/bin/ld: lib/libpdal_util.so.14.2.0: undefined reference to `std::filesystem::remove(std::filesystem::__cxx11::path const&)'
/usr/bin/ld: lib/libpdal_util.so.14.2.0: undefined reference to `typeinfo for std::filesystem::__cxx11::filesystem_error'
/usr/bin/ld: lib/libpdal_util.so.14.2.0: undefined reference to `std::filesystem::__cxx11::path::has_root_directory() const'
/usr/bin/ld: lib/libpdal_util.so.14.2.0: undefined reference to `std::filesystem::file_size(std::filesystem::__cxx11::path const&, std::error_code&)'
/usr/bin/ld: lib/libpdal_util.so.14.2.0: undefined reference to `std::filesystem::current_path[abi:cxx11]()'
/usr/bin/ld: lib/libpdal_util.so.14.2.0: undefined reference to `std::filesystem::status(std::filesystem::__cxx11::path const&)'
/usr/bin/ld: lib/libpdal_util.so.14.2.0: undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
/usr/bin/ld: lib/libpdal_util.so.14.2.0: undefined reference to `std::filesystem::create_directories(std::filesystem::__cxx11::path const&)'
/usr/bin/ld: lib/libpdal_util.so.14.2.0: undefined reference to `std::filesystem::remove_all(std::filesystem::__cxx11::path const&)'
/usr/bin/ld: lib/libpdal_util.so.14.2.0: undefined reference to `std::filesystem::__cxx11::directory_iterator::operator++()'
/usr/bin/ld: lib/libpdal_util.so.14.2.0: undefined reference to `std::filesystem::rename(std::filesystem::__cxx11::path const&, std::filesystem::__cxx11::path const&)'
/usr/bin/ld: lib/libpdal_util.so.14.2.0: undefined reference to `std::filesystem::create_directory(std::filesystem::__cxx11::path const&)'
/usr/bin/ld: lib/libpdal_util.so.14.2.0: undefined reference to `std::filesystem::__cxx11::directory_iterator::directory_iterator(std::filesystem::__cxx11::path const&, std::filesystem::directory_options, std::error_code*)'
/usr/bin/ld: lib/libpdal_util.so.14.2.0: undefined reference to `std::filesystem::absolute(std::filesystem::__cxx11::path const&)'
/usr/bin/ld: lib/libpdal_util.so.14.2.0: undefined reference to `std::filesystem::__cxx11::path::has_filename() const'
collect2: error: ld returned 1 exit status
[391/513] Linking CXX shared library lib/libpdal_base.so.14.2.0
ninja: build stopped: subcommand failed.
```

Any tips would be welcome!
Thanks

**Comment by hobu** [comment]
PDAL 2.4.0+ requires C++17. It seems as though something isn't linking properly with GCC8 on your system to get C++17.

**Comment by abellgithub** [comment]
Your installation is for some reason not linking std::filesystem or it is not installed. No idea why this might be.

**Comment by hobu** [comment]
Paste the dockerfile here otherwise we're just guessing.

**Comment by jsmoreau** [comment]
FROM python:3.8-slim-buster as builder

ENV NODE_EXTRA_CA_CERTS="/usr/local/share/ca-certificates/nrcan_ssl_cert.crt"

RUN apt-get update
RUN apt-get install -y --no-install-recommends \
    cmake build-essential ninja-build wget ca-certificates unzip pkg-config \
    zlib1g-dev libfreexl-dev libxml2-dev nasm libpng-dev

WORKDIR /tmp

ENV CPUS 3

# GDAL BUILD

ENV WEBP_VERSION 1.0.0
RUN wget -q https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-${WEBP_VERSION}.tar.gz && \
    tar xzf libwebp-${WEBP_VERSION}.tar.gz && \
    cd libwebp-${WEBP_VERSION} && \
    CFLAGS="-O2 -Wl,-S" ./configure --enable-silent-rules && \
    echo "building WEBP ${WEBP_VERSION}..." \
    make --quiet -j${CPUS} && make --quiet install

ENV ZSTD_VERSION 1.3.4
RUN wget -q -O zstd-${ZSTD_VERSION}.tar.gz https://github.com/facebook/zstd/archive/v${ZSTD_VERSION}.tar.gz \
    && tar -zxf zstd-${ZSTD_VERSION}.tar.gz \
    && cd zstd-${ZSTD_VERSION} \
    && echo "building ZSTD ${ZSTD_VERSION}..." \
    && make --quiet -j${CPUS} ZSTD_LEGACY_SUPPORT=0 CFLAGS=-O1 \
    && make --quiet install ZSTD_LEGACY_SUPPORT=0 CFLAGS=-O1

ENV LIBDEFLATE_VERSION 1.7
RUN wget -q https://github.com/ebiggers/libdeflate/archive/v${LIBDEFLATE_VERSION}.tar.gz \
    && tar -zxf v${LIBDEFLATE_VERSION}.tar.gz \
    && cd libdeflate-${LIBDEFLATE_VERSION} \
    && echo "building libdeflate ${LIBDEFLATE_VERSION}..." \
    && make -j${CPUS} \
    && make --quiet install

ENV LIBJPEG_TURBO_VERSION 2.0.5
RUN wget -q https://github.com/libjpeg-turbo/libjpeg-turbo/archive/${LIBJPEG_TURBO_VERSION}.tar.gz \
    && tar -zxf ${LIBJPEG_TURBO_VERSION}.tar.gz \
    && cd libjpeg-turbo-${LIBJPEG_TURBO_VERSION} \
    && echo "building libjpeg-turbo ${LIBJPEG_TURBO_VERSION}..." \
    && cmake -G"Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_BUILD_TYPE=Release . \
    && make -j${CPUS} \
    && make --quiet install

ENV GEOS_VERSION 3.9.1
RUN wget -q https://download.osgeo.org/geos/geos-${GEOS_VERSION}.tar.bz2 \
    && tar -xjf geos-${GEOS_VERSION}.tar.bz2  \
    && cd geos-${GEOS_VERSION} \
    && ./configure --prefix=/usr/local \
    && echo "building geos ${GEOS_VERSION}..." \
    && make --quiet -j${CPUS} && make --quiet install

ENV SQLITE_VERSION 3330000
ENV SQLITE_YEAR 2020
RUN wget -q --no-check-certificate https://sqlite.org/${SQLITE_YEAR}/sqlite-autoconf-${SQLITE_VERSION}.tar.gz \
    && tar -xzf sqlite-autoconf-${SQLITE_VERSION}.tar.gz && cd sqlite-autoconf-${SQLITE_VERSION} \
    && ./configure --prefix=/usr/local \
    && echo "building SQLITE ${SQLITE_VERSION}..." \
    && make --quiet -j${CPUS} && make --quiet install

ENV LIBTIFF_VERSION=4.2.0
RUN wget -q --no-check-certificate https://download.osgeo.org/libtiff/tiff-${LIBTIFF_VERSION}.tar.gz \
    && tar -xzf tiff-${LIBTIFF_VERSION}.tar.gz \
    && cd tiff-${LIBTIFF_VERSION} \
    && ./configure --prefix=/usr/local \
    && echo "building libtiff ${LIBTIFF_VERSION}..." \
    && make --quiet -j${CPUS} && make --quiet install

ENV NGHTTP2_VERSION 1.42.0
RUN wget --no-check-certificate https://github.com/nghttp2/nghttp2/releases/download/v${NGHTTP2_VERSION}/nghttp2-${NGHTTP2_VERSION}.tar.gz \
    && tar -xzf nghttp2-${NGHTTP2_VERSION}.tar.gz \
    && cd nghttp2-${NGHTTP2_VERSION} \
    && echo "building NGHTTP2 ${NGHTTP2_VERSION}..." \
    && ./configure --enable-lib-only --prefix=/usr/local \
    && make --quiet -j${CPUS} && make --quiet install

ENV CURL_VERSION 7.73.0
RUN wget -q https://curl.haxx.se/download/curl-${CURL_VERSION}.tar.gz \
    && tar -xzf curl-${CURL_VERSION}.tar.gz && cd curl-${CURL_VERSION} \
    && ./configure --prefix=/usr/local \
    && echo "building CURL ${CURL_VERSION}..." \
    && make --quiet -j${CPUS} && make --quiet install

ENV PROJ_VERSION 7.2.1
RUN wget -q --no-check-certificate https://download.osgeo.org/proj/proj-${PROJ_VERSION}.tar.gz \
    && tar -xzf proj-${PROJ_VERSION}.tar.gz \
    && cd proj-${PROJ_VERSION} \
    && ./configure --prefix=/usr/local \
    && echo "building proj ${PROJ_VERSION}..." \
    && make --quiet -j${CPUS} && make --quiet install

ENV LIBGEOTIFF_VERSION=1.6.0
RUN wget -q https://github.com/OSGeo/libgeotiff/releases/download/${LIBGEOTIFF_VERSION}/libgeotiff-${LIBGEOTIFF_VERSION}.tar.gz \
    && tar -xzf libgeotiff-${LIBGEOTIFF_VERSION}.tar.gz \
    && cd libgeotiff-${LIBGEOTIFF_VERSION} \
    && ./configure --prefix=/usr/local --with-zlib \
    && echo "building libgeotiff ${LIBGEOTIFF_VERSION}..." \
    && make --quiet -j${CPUS} && make --quiet install

ENV OPENJPEG_VERSION 2.3.1
RUN wget -q -O openjpeg-${OPENJPEG_VERSION}.tar.gz https://github.com/uclouvain/openjpeg/archive/v${OPENJPEG_VERSION}.tar.gz \
    && tar -zxf openjpeg-${OPENJPEG_VERSION}.tar.gz \
    && cd openjpeg-${OPENJPEG_VERSION} \
    && mkdir build && cd build \
    && cmake .. -DBUILD_THIRDPARTY:BOOL=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local \
    && echo "building openjpeg ${OPENJPEG_VERSION}..." \
    && make --quiet -j${CPUS} && make --quiet install

ENV GDAL_SHORT_VERSION 3.4.0
ENV GDAL_VERSION 3.4.0
RUN wget -q https://download.osgeo.org/gdal/${GDAL_SHORT_VERSION}/gdal-${GDAL_VERSION}.tar.gz
RUN tar -xzf gdal-${GDAL_VERSION}.tar.gz && cd gdal-${GDAL_SHORT_VERSION} && \
    ./configure \
    --disable-debug \
    --prefix=/usr/local \
    --disable-static \
    --with-curl=/usr/local/bin/curl-config \
    --with-geos \
    --with-geotiff=/usr/local \
    --with-hide-internal-symbols=yes \
    --with-libtiff=/usr/local \
    --with-jpeg=/usr/local \
    --with-png \
    --with-openjpeg \
    --with-sqlite3 \
    --with-proj=/usr/local \
    --with-rename-internal-libgeotiff-symbols=yes \
    --with-rename-internal-libtiff-symbols=yes \
    --with-threads=yes \
    --with-webp=/usr/local \
    --with-zstd=/usr/local \
    --with-libdeflate \
    && echo "building GDAL ${GDAL_VERSION}..." \
    && make -j${CPUS} && make --quiet install

RUN ldconfig

# https://proj.org/usage/environmentvars.html#envvar-PROJ_NETWORK
ENV PROJ_NETWORK ON

#PDAL BUILD
ENV PDAL_VERSION 2.4.1
RUN wget -q https://github.com/PDAL/PDAL/releases/download/${PDAL_VERSION}/PDAL-${PDAL_VERSION}-src.tar.gz \
    && tar -xvf PDAL-${PDAL_VERSION}-src.tar.gz \
    && cd PDAL-${PDAL_VERSION}-src \
    && mkdir build \
    && cd build \
    && cmake -G Ninja .. \
    && ninja

**Comment by jsmoreau** [comment]
```
FROM python:3.8-slim-buster as builder

ENV NODE_EXTRA_CA_CERTS="/usr/local/share/ca-certificates/nrcan_ssl_cert.crt"

RUN apt-get update
RUN apt-get install -y --no-install-recommends \
    cmake build-essential ninja-build wget ca-certificates unzip pkg-config \
    zlib1g-dev libfreexl-dev libxml2-dev nasm libpng-dev

WORKDIR /tmp

ENV CPUS 3

# GDAL BUILD

ENV WEBP_VERSION 1.0.0
RUN wget -q https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-${WEBP_VERSION}.tar.gz && \
    tar xzf libwebp-${WEBP_VERSION}.tar.gz && \
    cd libwebp-${WEBP_VERSION} && \
    CFLAGS="-O2 -Wl,-S" ./configure --enable-silent-rules && \
    echo "building WEBP ${WEBP_VERSION}..." \
    make --quiet -j${CPUS} && make --quiet install

ENV ZSTD_VERSION 1.3.4
RUN wget -q -O zstd-${ZSTD_VERSION}.tar.gz https://github.com/facebook/zstd/archive/v${ZSTD_VERSION}.tar.gz \
    && tar -zxf zstd-${ZSTD_VERSION}.tar.gz \
    && cd zstd-${ZSTD_VERSION} \
    && echo "building ZSTD ${ZSTD_VERSION}..." \
    && make --quiet -j${CPUS} ZSTD_LEGACY_SUPPORT=0 CFLAGS=-O1 \
    && make --quiet install ZSTD_LEGACY_SUPPORT=0 CFLAGS=-O1

ENV LIBDEFLATE_VERSION 1.7
RUN wget -q https://github.com/ebiggers/libdeflate/archive/v${LIBDEFLATE_VERSION}.tar.gz \
    && tar -zxf v${LIBDEFLATE_VERSION}.tar.gz \
    && cd libdeflate-${LIBDEFLATE_VERSION} \
    && echo "building libdeflate ${LIBDEFLATE_VERSION}..." \
    && make -j${CPUS} \
    && make --quiet install

ENV LIBJPEG_TURBO_VERSION 2.0.5
RUN wget -q https://github.com/libjpeg-turbo/libjpeg-turbo/archive/${LIBJPEG_TURBO_VERSION}.tar.gz \
    && tar -zxf ${LIBJPEG_TURBO_VERSION}.tar.gz \
    && cd libjpeg-turbo-${LIBJPEG_TURBO_VERSION} \
    && echo "building libjpeg-turbo ${LIBJPEG_TURBO_VERSION}..." \
    && cmake -G"Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_BUILD_TYPE=Release . \
    && make -j${CPUS} \
    && make --quiet install

ENV GEOS_VERSION 3.9.1
RUN wget -q https://download.osgeo.org/geos/geos-${GEOS_VERSION}.tar.bz2 \
    && tar -xjf geos-${GEOS_VERSION}.tar.bz2  \
    && cd geos-${GEOS_VERSION} \
    && ./configure --prefix=/usr/local \
    && echo "building geos ${GEOS_VERSION}..." \
    && make --quiet -j${CPUS} && make --quiet install

ENV SQLITE_VERSION 3330000
ENV SQLITE_YEAR 2020
RUN wget -q --no-check-certificate https://sqlite.org/${SQLITE_YEAR}/sqlite-autoconf-${SQLITE_VERSION}.tar.gz \
    && tar -xzf sqlite-autoconf-${SQLITE_VERSION}.tar.gz && cd sqlite-autoconf-${SQLITE_VERSION} \
    && ./configure --prefix=/usr/local \
    && echo "building SQLITE ${SQLITE_VERSION}..." \
    && make --quiet -j${CPUS} && make --quiet install

ENV LIBTIFF_VERSION=4.2.0
RUN wget -q --no-check-certificate https://download.osgeo.org/libtiff/tiff-${LIBTIFF_VERSION}.tar.gz \
    && tar -xzf tiff-${LIBTIFF_VERSION}.tar.gz \
    && cd tiff-${LIBTIFF_VERSION} \
    && ./configure --prefix=/usr/local \
    && echo "building libtiff ${LIBTIFF_VERSION}..." \
    && make --quiet -j${CPUS} && make --quiet install

ENV NGHTTP2_VERSION 1.42.0
RUN wget --no-check-certificate https://github.com/nghttp2/nghttp2/releases/download/v${NGHTTP2_VERSION}/nghttp2-${NGHTTP2_VERSION}.tar.gz \
    && tar -xzf nghttp2-${NGHTTP2_VERSION}.tar.gz \
    && cd nghttp2-${NGHTTP2_VERSION} \
    && echo "building NGHTTP2 ${NGHTTP2_VERSION}..." \
    && ./configure --enable-lib-only --prefix=/usr/local \
    && make --quiet -j${CPUS} && make --quiet install

ENV CURL_VERSION 7.73.0
RUN wget -q https://curl.haxx.se/download/curl-${CURL_VERSION}.tar.gz \
    && tar -xzf curl-${CURL_VERSION}.tar.gz && cd curl-${CURL_VERSION} \
    && ./configure --prefix=/usr/local \
    && echo "building CURL ${CURL_VERSION}..." \
    && make --quiet -j${CPUS} && make --quiet install

ENV PROJ_VERSION 7.2.1
RUN wget -q --no-check-certificate https://download.osgeo.org/proj/proj-${PROJ_VERSION}.tar.gz \
    && tar -xzf proj-${PROJ_VERSION}.tar.gz \
    && cd proj-${PROJ_VERSION} \
    && ./configure --prefix=/usr/local \
    && echo "building proj ${PROJ_VERSION}..." \
    && make --quiet -j${CPUS} && make --quiet install

ENV LIBGEOTIFF_VERSION=1.6.0
RUN wget -q https://github.com/OSGeo/libgeotiff/releases/download/${LIBGEOTIFF_VERSION}/libgeotiff-${LIBGEOTIFF_VERSION}.tar.gz \
    && tar -xzf libgeotiff-${LIBGEOTIFF_VERSION}.tar.gz \
    && cd libgeotiff-${LIBGEOTIFF_VERSION} \
    && ./configure --prefix=/usr/local --with-zlib \
    && echo "building libgeotiff ${LIBGEOTIFF_VERSION}..." \
    && make --quiet -j${CPUS} && make --quiet install

ENV OPENJPEG_VERSION 2.3.1
RUN wget -q -O openjpeg-${OPENJPEG_VERSION}.tar.gz https://github.com/uclouvain/openjpeg/archive/v${OPENJPEG_VERSION}.tar.gz \
    && tar -zxf openjpeg-${OPENJPEG_VERSION}.tar.gz \
    && cd openjpeg-${OPENJPEG_VERSION} \
    && mkdir build && cd build \
    && cmake .. -DBUILD_THIRDPARTY:BOOL=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local \
    && echo "building openjpeg ${OPENJPEG_VERSION}..." \
    && make --quiet -j${CPUS} && make --quiet install

ENV GDAL_SHORT_VERSION 3.4.0
ENV GDAL_VERSION 3.4.0
RUN wget -q https://download.osgeo.org/gdal/${GDAL_SHORT_VERSION}/gdal-${GDAL_VERSION}.tar.gz
RUN tar -xzf gdal-${GDAL_VERSION}.tar.gz && cd gdal-${GDAL_SHORT_VERSION} && \
    ./configure \
    --disable-debug \
    --prefix=/usr/local \
    --disable-static \
    --with-curl=/usr/local/bin/curl-config \
    --with-geos \
    --with-geotiff=/usr/local \
    --with-hide-internal-symbols=yes \
    --with-libtiff=/usr/local \
    --with-jpeg=/usr/local \
    --with-png \
    --with-openjpeg \
    --with-sqlite3 \
    --with-proj=/usr/local \
    --with-rename-internal-libgeotiff-symbols=yes \
    --with-rename-internal-libtiff-symbols=yes \
    --with-threads=yes \
    --with-webp=/usr/local \
    --with-zstd=/usr/local \
    --with-libdeflate \
    && echo "building GDAL ${GDAL_VERSION}..." \
    && make -j${CPUS} && make --quiet install

RUN ldconfig

# https://proj.org/usage/environmentvars.html#envvar-PROJ_NETWORK
ENV PROJ_NETWORK ON

#PDAL BUILD
ENV PDAL_VERSION 2.4.1
RUN wget -q https://github.com/PDAL/PDAL/releases/download/${PDAL_VERSION}/PDAL-${PDAL_VERSION}-src.tar.gz \
    && tar -xvf PDAL-${PDAL_VERSION}-src.tar.gz \
    && cd PDAL-${PDAL_VERSION}-src \
    && mkdir build \
    && cd build \
    && cmake -G Ninja .. \
    && ninja
```

**Comment by jsmoreau** [comment]
Do you have any clues on what might be the problem?

**Comment by abellgithub** [comment]
You can just turn off building lasdump.

**Comment by jsmoreau** [comment]
> You can just turn off building lasdump.

How would I do that?

**Comment by hobu** [comment]
> #20 16.14 /usr/bin/ld: ../../../thirdparty/lib/libpng.a(pngrutil.c.o): in function `png_read_filter_row':
#20 16.14 pngrutil.c:(.text+0x5d34): undefined reference to `png_init_filter_functions_neon'
#20 16.14 collect2: error: ld returned 1 exit status
#20 16.14 make[2]: *** [src/bin/jp2/CMakeFiles/opj_decompress.dir/build.make:194: bin/opj_decompress] Error 1
#20 16.14 make[1]: *** [CMakeFiles/Makefile2:541: src/bin/jp2/CMakeFiles/opj_decompress.dir/all] Error 2
#20 16.15 /usr/bin/ld: ../../../thirdparty/lib/libpng.a(pngrutil.c.o): in function `png_read_filter_row':

This dockerfile does not compile to the PDAL part successfully for me. I don't understand why you're building everything from source yourself. Can you move to a newer Debian or run the @conda-forge builds?

**Comment by jsmoreau** [comment]
> > #20 16.14 /usr/bin/ld: ../../../thirdparty/lib/libpng.a(pngrutil.c.o): in function `png_read_filter_row': #20 16.14 pngrutil.c:(.text+0x5d34): undefined reference to `png_init_filter_functions_neon'
> > #20 16.14 collect2: error: ld returned 1 exit status
> > #20 16.14 make[2]: *** [src/bin/jp2/CMakeFiles/opj_decompress.dir/build.make:194: bin/opj_decompress] Error 1
> > #20 16.14 make[1]: *** [CMakeFiles/Makefile2:541: src/bin/jp2/CMakeFiles/opj_decompress.dir/all] Error 2
> > #20 16.15 /usr/bin/ld: ../../../thirdparty/lib/libpng.a(pngrutil.c.o): in function `png_read_filter_row':
> 
> This dockerfile does not compile to the PDAL part successfully for me. I don't understand why you're building everything from source yourself. Can you move to a newer Debian or run the @conda-forge builds?

I'll take look at the conda-forge builds. Thanks for the link! I might go back to using conda in docker altogether. We were having trouble using our docker image as a devcontainer in vscode because of the conda activation routines. By building GDAL and PDAL from sources, I had hoped to be able to install the remaining python dependancies using pypi.

**Comment by rcoup** [comment]
Under GCC8, you need something along these lines to make it work consistently:

Add to the bottom of `pdal/util/CMakeLists.txt`
```
target_link_libraries(${PDAL_UTIL_LIB_NAME} PRIVATE -lstdc++fs)
```

Unfortunately just adding `-lstdc++fs` via `LDFLAGS`/`CMAKE_*_LINKER_FLAGS`/etc doesn't work properly because it ends up too early on the linker line.

There's a couple of [conditional approaches in a CMake forum thread](https://discourse.cmake.org/t/correct-way-to-link-std-filesystem-with-gcc-8/4121/6), but seems the CMake developers aren't likely to fix it now GCC9 is out.

Maybe something like this would work (untested):

```cmake
target_link_libraries(
  ${PDAL_UTIL_LIB_NAME}
  PRIVATE
  "$<$<AND:$<CXX_COMPILER_ID:GNU>,$<VERSION_LESS:$<CXX_COMPILER_VERSION>,9.0>>:-lstdc++fs>"
)```

**Comment by Sinan81** [comment]
having the same problem with gcc@7.5. wanted to apply the patch suggested above but there's no `pdal/util/CMakeLists.txt` in the source files.

**Comment by hobu** [comment]
The patch was adapted for PDAL 2.6+ due to the fact that we removed the pdal_util library as an externally installed thing at that point. If this is still an issue on PDAL 2.6+, please open a new ticket with the specific error message and procedure to reproduce it.
