### ISSUE TITLE
Looks like this might be happening again.

### ISSUE THREAD

**Issue by maria-yuda** [PDAL/PDAL#3827]
Looks like this might be happening again. 
I installed into a new environment with `conda install -c conda-forge pdal python-pdal pdal`  activated it, and get ` ImportError: DLL load failed while importing libpdalpython: The specified module could not be found. ` trying to import pdal in python.

_Originally posted by @dkeatin2 in https://github.com/PDAL/PDAL/issues/2299#issuecomment-1071509060_

**Comment by hobu** [comment]
working for me with a fresh environment 
![image](https://user-images.githubusercontent.com/87751/181572591-20583356-c883-411e-a634-51468fa08f2c.png)

**Comment by maria-yuda** [comment]
yeah, it just worked. thanks!

**Comment by lowbrows** [comment]
Getting the same error. I'm not on conda but trying to install from the wheels - pdal-3.2.2-cp310-cp310-win_amd64.whl  - 
 Error: ImportError: DLL load failed while importing libpdalpython: The specified module could not be found.

**Comment by j9ac9k** [comment]
> Getting the same error. I'm not on conda but trying to install from the wheels - pdal-3.2.2-cp310-cp310-win_amd64.whl - Error: ImportError: DLL load failed while importing libpdalpython: The specified module could not be found.

this message is a bit of a catch-all and not an indication of one specific issue.  This error can occur when one of the dependencies that has a DLL could not be imported for some reason.

Easiest thing to do is create a new conda environment and install pdal from that go from there.  You can attempt to debug, but fair warning, [DLL hell](https://en.wikipedia.org/wiki/DLL_Hell) is a real thing

**Comment by hobu** [comment]
I think the python-pdal configuration is baking in rpath settings from scikit-build and this is causing us trouble. We should explore relaxing the rpath'ing.

**Comment by Mitko88** [comment]
I could not manage to run it
![image](https://user-images.githubusercontent.com/8992310/229991952-bc9375ef-ce82-4ff6-8b2a-db8fd781ac0d.png)

**Comment by network-mapping-dev** [comment]
I get this issue with python 3.10 but not if I let python-pdal install python - it installs python 3.11

**Comment by j9ac9k** [comment]
> I get this issue with python 3.10 but not if I let python-pdal install python - it installs python 3.11

That error is a catch-all for some kind of environment related issue.  Best you can do is recreate the environment, if you're still getting issues, post the output of `conda list`

**Comment by Acoustic6** [comment]
@j9ac9k I tried many conda envs and each time end up with import pdal error. Here are my conda lists of two of them:

1.
I have error '//Python.Runtime.PythonException: 'DLL load failed: The specified module could not be found.'' on Windows 11. 

Code is: 
using Python.Runtime; // using Python.Net
using (Py.GIL())
{
    dynamic conda_site_packages_path2 = "C:\\Users\\***\\anaconda3\\envs\\pdal-option3\\Lib\\site-packages"; 
    sys.path.append(conda_site_packages_path2);

}

Detailed view show:
  File "C:\Users\***\anaconda3\envs\pdalno3d\Lib\site-packages\pdal\__init__.py", line 4, in <module>
    from . import libpdalpython
   at Python.Runtime.PythonException.ThrowLastAsClrException()
   at Python.Runtime.NewReferenceExtensions.BorrowOrThrow(NewReference& reference)
   at Python.Runtime.PyModule.Import(String name)
   at Python.Runtime.Py.Import(String name)
   at Program.<Main>$(String[] args) in D:\Development\dotNet\VisualStudio\PythonnetConsole\ConsoleApp1\Program.cs:line 26

conda list:

# Name                    Version                   Build  Channel
blosc                     1.21.4               hdccc3a2_0    conda-forge
boost-cpp                 1.78.0               h9f4b32c_3    conda-forge
brotli                    1.0.9                hcfcfb64_9    conda-forge
brotli-bin                1.0.9                hcfcfb64_9    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2023.7.22            h56e8100_0    conda-forge
cairo                     1.16.0            hd694305_1014    conda-forge
certifi                   2023.7.22          pyhd8ed1ab_0    conda-forge
cfitsio                   4.1.0                h5a969a9_0    conda-forge
curl                      8.1.2                h68f0423_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
draco                     1.5.6                h181d51b_0    conda-forge
eigen                     3.4.0                h91493d7_0    conda-forge
entwine                   2.2.0                h4d86461_6    conda-forge
expat                     2.5.0                h63175ca_1    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.2               hbde0cde_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.38.0           py37h51bd9d9_0    conda-forge
freetype                  2.12.1               h546665d_1    conda-forge
freexl                    1.0.6                h67ca5e6_1    conda-forge
gdal                      3.5.2            py37h1fef14a_5    conda-forge
geos                      3.11.0               h39d44d4_0    conda-forge
geotiff                   1.7.1                h4ffd875_4    conda-forge
gettext                   0.21.1               h5728263_0    conda-forge
glib                      2.76.4               h12be248_0    conda-forge
glib-tools                2.76.4               h12be248_0    conda-forge
gst-plugins-base          1.22.5               h001b923_0    conda-forge
gstreamer                 1.22.5               hb4038d2_0    conda-forge
hdf4                      4.2.15               h1b1b6ef_5    conda-forge
hdf5                      1.12.2          nompi_h57737ce_101    conda-forge
icu                       70.1                 h0e60522_0    conda-forge
intel-openmp              2023.2.0         h57928b3_49496    conda-forge
jpeg                      9e                   hcfcfb64_3    conda-forge
kealib                    1.4.15               hdf81f3a_1    conda-forge
kiwisolver                1.4.4            py37h8c56517_0    conda-forge
krb5                      1.20.1               heb0366b_0    conda-forge
lcms2                     2.14                 h90d422f_0    conda-forge
lerc                      4.0.0                h63175ca_0    conda-forge
libaec                    1.0.6                h63175ca_1    conda-forge
libblas                   3.9.0              17_win64_mkl    conda-forge
libbrotlicommon           1.0.9                hcfcfb64_9    conda-forge
libbrotlidec              1.0.9                hcfcfb64_9    conda-forge
libbrotlienc              1.0.9                hcfcfb64_9    conda-forge
libcblas                  3.9.0              17_win64_mkl    conda-forge
libclang                  15.0.7          default_h77d9078_3    conda-forge
libclang13                15.0.7          default_h77d9078_3    conda-forge
libcurl                   8.1.2                h68f0423_0    conda-forge
libdeflate                1.14                 hcfcfb64_0    conda-forge
libexpat                  2.5.0                h63175ca_1    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libgdal                   3.5.2                h283e77c_5    conda-forge
libglib                   2.76.4               he8f3873_0    conda-forge
libhwloc                  2.9.1                h51c2c0f_0    conda-forge
libiconv                  1.17                 h8ffe710_0    conda-forge
libkml                    1.3.0             hf2ab4e4_1015    conda-forge
liblapack                 3.9.0              17_win64_mkl    conda-forge
libnetcdf                 4.8.1           nompi_h8c042bf_106    conda-forge
libogg                    1.3.4                h8ffe710_1    conda-forge
libpng                    1.6.39               h19919ed_0    conda-forge
libpq                     14.5                 ha9684e8_5    conda-forge
librttopo                 1.1.0               h2842628_11    conda-forge
libspatialite             5.0.1               hd560d62_21    conda-forge
libsqlite                 3.42.0               hcfcfb64_0    conda-forge
libssh2                   1.11.0               h7dfc565_0    conda-forge
libtiff                   4.4.0                hc4f729c_5    conda-forge
libvorbis                 1.3.7                h0e60522_0    conda-forge
libwebp-base              1.3.1                hcfcfb64_0    conda-forge
libxcb                    1.13              hcd874cb_1004    conda-forge
libxml2                   2.10.4               hc3477c8_0    conda-forge
libzip                    1.9.2                h519de47_1    conda-forge
libzlib                   1.2.13               hcfcfb64_5    conda-forge
lz4-c                     1.9.4                hcfcfb64_0    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
matplotlib                3.5.3            py37h03978a9_2    conda-forge
matplotlib-base           3.5.3            py37hbaab90a_2    conda-forge
mkl                       2022.1.0           h6a75c08_874    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
nitro                     2.7.dev8             h1537add_0    conda-forge
numpy                     1.21.6           py37h2830a78_0    conda-forge
openjpeg                  2.5.0                hc9384bd_1    conda-forge
openssl                   3.1.2                hcfcfb64_0    conda-forge
packaging                 23.1               pyhd8ed1ab_0    conda-forge
pcre                      8.45                 h0e60522_0    conda-forge
pcre2                     10.40                h17e33f8_0    conda-forge
pdal                      3.2.0                    pypi_0    pypi
pillow                    9.2.0            py37h42a8222_2    conda-forge
pip                       23.2.1             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h8ffe710_0    conda-forge
ply                       3.11                       py_1    conda-forge
poppler                   22.10.0              ha6c1112_0    conda-forge
poppler-data              0.4.12               hd8ed1ab_0    conda-forge
postgresql                14.5                 hd87cd2b_5    conda-forge
proj                      9.1.0                h3863b3b_0    conda-forge
pthread-stubs             0.4               hcd874cb_1001    conda-forge
pthreads-win32            2.9.1                hfa6e2cd_3    conda-forge
pyparsing                 3.1.1              pyhd8ed1ab_0    conda-forge
pyqt                      5.15.7           py37h15e4627_1    conda-forge
pyqt5-sip                 12.11.0          py37h7f67f24_1    conda-forge
python                    3.7.12          h900ac77_100_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-pdal               3.2.0            py37h80650fd_0    conda-forge
python_abi                3.7                     3_cp37m    conda-forge
qt-main                   5.15.8               h720456b_6    conda-forge
setuptools                68.0.0             pyhd8ed1ab_0    conda-forge
sip                       6.7.2            py37h7f67f24_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.10               hfb803bf_0    conda-forge
sqlite                    3.42.0               hcfcfb64_0    conda-forge
tbb                       2021.9.0             h91493d7_0    conda-forge
tiledb                    2.11.3               h3132609_1    conda-forge
tk                        8.6.12               h8ffe710_0    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tornado                   6.2              py37hcc03f2d_0    conda-forge
typing-extensions         4.7.1                hd8ed1ab_0    conda-forge
typing_extensions         4.7.1              pyha770c72_0    conda-forge
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
unicodedata2              14.0.0           py37hcc03f2d_1    conda-forge
vc                        14.3                h64f974e_17    conda-forge
vc14_runtime              14.36.32532         hfdfe4a8_17    conda-forge
vs2015_runtime            14.36.32532         h05e6639_17    conda-forge
wheel                     0.41.1             pyhd8ed1ab_0    conda-forge
xerces-c                  3.2.4                h63175ca_2    conda-forge
xorg-libxau               1.0.11               hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
zlib                      1.2.13               hcfcfb64_5    conda-forge
zstd                      1.5.2                h12be248_7    conda-forge

"python import pdal works" fine

2.
Another conda environment gives another error: 
"//Python.Runtime.PythonException: 'cannot import name 'libpdalpython' from 'pdal' (C:\Users\***\anaconda3\envs\pdal-option2\Lib\site-packages\pdal\__init__.py)'"

conda list: 

# Name                    Version                   Build  Channel
boost-cpp                 1.67.0                   vc14_0  [vc14]  conda-forge/label/cf201901
bzip2                     1.0.6                    vc14_1  [vc14]  conda-forge/label/cf201901
ca-certificates           2018.11.29           ha4d7672_0    conda-forge/label/cf201901
certifi                   2018.11.29            py36_1000    conda-forge/label/cf201901
curl                      7.60.0                   vc14_0  [vc14]  conda-forge/label/cf201901
expat                     2.2.5                    vc14_0  [vc14]  conda-forge/label/cf201901
flann                     1.9.1             ha6687fd_1005    conda-forge/label/cf201901
freexl                    1.0.5                    vc14_0  [vc14]  conda-forge/label/cf201901
gdal                      2.3.3           py36h1d93c02_1000    conda-forge/label/cf201901
geos                      3.7.0             he025d50_1000    conda-forge/label/cf201901
geotiff                   1.4.3             h8408f58_1000    conda-forge/label/cf201901
hdf4                      4.2.13                   vc14_0  [vc14]  conda-forge/label/cf201901
hdf5                      1.10.4          nompi_hcc15c50_1105    conda-forge/label/cf201901
intel-openmp              2023.2.0         h57928b3_49496    conda-forge
jpeg                      9c                hfa6e2cd_1001    conda-forge/label/cf201901
jsoncpp                   1.8.4             h1ad3211_1001    conda-forge/label/cf201901
kealib                    1.4.10            heacb130_1002    conda-forge/label/cf201901
krb5                      1.14.6                   vc14_0  [vc14]  conda-forge/label/cf201901
laszip                    3.2.2                    vc14_0  [vc14]  conda-forge/label/cf201901
laz-perf                  1.2.0                    vc14_1  [vc14]  conda-forge/label/cf201901
libblas                   3.9.0                     8_mkl    conda-forge
libcblas                  3.9.0                     8_mkl    conda-forge
libgdal                   2.3.3             h8467d11_1000    conda-forge/label/cf201901
libiconv                  1.15              hfa6e2cd_1004    conda-forge/label/cf201901
libkml                    1.3.0             h6c56937_1008    conda-forge/label/cf201901
liblapack                 3.9.0                     8_mkl    conda-forge
libnetcdf                 4.6.2             h396784b_1001    conda-forge/label/cf201901
libpng                    1.6.36            h7602738_1000    conda-forge/label/cf201901
libpq                     9.6.3                    vc14_0  [vc14]  conda-forge/label/cf201901
libspatialite             4.3.0a            h41117f9_1025    conda-forge/label/cf201901
libssh2                   1.8.0             hc4dcbb0_1003    conda-forge/label/cf201901
libtiff                   4.0.10            h36446d0_1001    conda-forge/label/cf201901
libxml2                   2.9.8             h9ce36c8_1005    conda-forge/label/cf201901
m2w64-expat               2.1.1                         2    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gettext             0.19.7                        2    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libiconv            1.14                          6    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
m2w64-xz                  5.2.2                         2    conda-forge
mkl                       2020.4             hb70f87d_311    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
nitro                     2.7.dev2                 vc14_0  [vc14]  conda-forge/label/cf201901
numpy                     1.17.5           py36hc71023c_0    conda-forge
openjpeg                  2.3.0             h25a6d84_1003    conda-forge/label/cf201901
openssl                   1.0.2p            hfa6e2cd_1002    conda-forge/label/cf201901
packaging                 18.0                       py_0    conda-forge/label/cf201901
pcl                       1.8.1                h0a54bab_2    conda-forge/label/cf201901
pcre                      8.41                     vc14_1  [vc14]  conda-forge/label/cf201901
pdal                      1.8.0            py36h727dd4b_7    conda-forge/label/cf201901
pip                       18.1                  py36_1000    conda-forge/label/cf201901
postgresql                9.6.3                    vc14_4  [vc14]  conda-forge/label/cf201901
proj4                     5.2.0             hfa6e2cd_1001    conda-forge/label/cf201901
pyparsing                 2.3.0                      py_0    conda-forge/label/cf201901
python                    3.6.6                he025d50_0    conda-forge/label/cf201901
python-pdal               2.1.8            py36hf75dd32_0    conda-forge/label/cf201901
setuptools                40.6.3                   py36_0    conda-forge/label/cf201901
six                       1.12.0                py36_1000    conda-forge/label/cf201901
sqlite                    3.26.0            hfa6e2cd_1000    conda-forge/label/cf201901
vc                        14                            0    conda-forge/label/cf201901
vs2015_runtime            14.0.25420                    0    conda-forge/label/cf201901
wheel                     0.32.3                   py36_0    conda-forge/label/cf201901
wincertstore              0.2                   py36_1002    conda-forge/label/cf201901
xerces-c                  3.2.2             h6538335_1001    conda-forge/label/cf201901
xz                        5.2.4             h2fa13f4_1001    conda-forge/label/cf201901
zlib                      1.2.11                   vc14_0  [vc14]  conda-forge/label/cf201901

**Comment by network-mapping-dev** [comment]
Above I said that the issue was with python 3.10 but in the end this was not the case. I was trying to build an environment with the following packages: 

conda install python=3.10 tensorflow tensorflow-gpu cython pandas scikit-learn PyYAML laszip tensorflow-probability pdal python-pdal seaborn -c conda-forge

I could build this on Linux, but not on windows - it give a conflicts error. I spent several hours trying various versions and pip installs and gave up.

**Comment by Acoustic6** [comment]
@network-mapping-dev I recommend to go "anaconda.org" and search for python-pdal. choose certain channel and open Files section. There you will be able to search for let's say win-64 versions. click on (i) icon and check all dependencied you need. Create myenv.yml file with all this deps and run 'conda env create -f myenv.yml'.

You will have environment created in root folder of which python of the selected version will be installed. Like 'C:\Users\user\anaconda3\envs\my_environment\'

What I did next is changed PATH values from default python installation folder to python installed in created env like
C:\Users\user\AppData\Local\Programs\Python\Python38 => C:\Users\user\anaconda3\envs\my_environment
C:\Users\user\AppData\Local\Programs\Python\Python38\Scripst => C:\Users\user\anaconda3\envs\my_environment\Scripts
(or you can just put new path values above default ones instead of changing one to another)

Also I added new env variables
PYTHONHOME: C:\Users\user\anaconda3\envs\my_environment
PYTHONPATH: C:\Users\user\anaconda3\envs\my_environment\Lib

the only issue with this approach is that conda command is not found untill I delete PYTHONHOME and PYTHONPATH variables.

May be certain env variable can show anaconda how to find python in conda environment dir but I havnt find it yet. If someone knows hot wo fix this issue please reply


and 

My *.yml:
name: pdal38
channels:
  - defaults
  - conda-forge
dependencies:
  - numpy>=1.21.6,<2.0a0
  - pdal>=2.5.4,<2.6.0a0
  - python>=3.8,<3.9.0a0
  - python_abi=3.8.*
  - ucrt>=10.0.20348.0
  - vc>=14.2,<15
  - vc14_runtime>=14.29.30139
  - python-pdal=3.2.3
  - 
![photo1691660070](https://github.com/PDAL/PDAL/assets/5627993/d6390345-d157-4b9f-a231-5cde62a1914c)
![photo1691660128](https://github.com/PDAL/PDAL/assets/5627993/8e38de83-8749-4734-b773-7dbd2066a427)
