### ISSUE TITLE
readers.numpy not working even though it is found

### ISSUE THREAD

**Issue by segments-tobias** [PDAL/PDAL#3830]
**Describe the bug**
I'm getting an error saying a numpy reader stage couldn't be created, even though `pdal --drivers` shows the numpy reader is found.

```
RuntimeError: Couldn't create reader stage of type 'readers.numpy'.
```
  
```
pipeline = [
    {
        "type": "readers.numpy",
        "filename": filename
    },
    {
        "type": "writers.las",
        "filename": filename_las,
    },
]
```

**System/installation information:**
Please provide information on your PDAL version (`pdal --version`) and system (e.g., `uname -a` or `ver`).

```
$ uname -a
Linux pc-back-end-image 4.4.0 #1 SMP Sun Jan 10 15:06:54 PST 2016 x86_64 GNU/Linux

```

```
$ pdal --version
pdal 2.4.2 (git-version: 36788c)
```

```
$ pdal --drivers
...
readers.numpy
...
```

**Comment by hobu** [comment]
Are you using @conda-forge environments, or are you building your own? The following works for me:

```
conda create -n pdal-python -c conda-forge python-pdal -y
conda activate pdal-python
pdal --drivers|grep py
pdal translate in.npy out.las --reader numpy
```

```

filters.ferry                Copy data from one dimension to another.
filters.python               Manipulate data using inline Python
readers.numpy                Read data from .npy files.

PDAL: 'Traceback (most recent call last):\n''  File "/Users/hobu/miniforge3/envs/pdal-python/lib/python3.9/site-packages/numpy/lib/npyio.py", line 390, in load\n    fid = stack.enter_context(open(os_fspath(file), "rb"))\n'"FileNotFoundError: [Errno 2] No such file or directory: 'in.npy'\n"

```

**Comment by segments-tobias** [comment]
Yes I'm using a conda-forge environment just like your comment.
Running `pdal translate in.npy out.las --reader numpy` from the console also gives the same result.

It crashes when running my pipeline from Python. This is the error message:
```
  File "/app/main.py", line 221, in convert_npy
    pipeline.execute()
RuntimeError: Couldn't create reader stage of type 'readers.numpy'.
You probably have a version of PDAL that didn't come with a plugin
you're trying to load. Please see the FAQ at https://pdal.io/faq
```

**Comment by hobu** [comment]
oh, you're using `readers.numpy` *inside* Python itself.

If you're in Python, you can pass numpy arrays directly without using `readers.numpy`. See https://github.com/PDAL/python/blob/master/test/test_pipeline.py#L370 for an example

**Comment by segments-tobias** [comment]
Ah cool, didn't know that was possible. Thank you!
