### ISSUE TITLE
PDAL writers.gdal

### ISSUE THREAD

**Issue by Vicent-Ribas** [PDAL/PDAL#3833]
Hi, I am trying to run a PDAL pipeline in a Python script to create a Digital Terrain Model from a LiDAR las file. This is my code:

**CODE**
`    print("PDAL pipeline for DSM")
    pipeline = (
        pdal.Reader(input_las)
        | pdal.Filter.reprojection(in_srs=lidar_src, out_srs=shp_src)
        | pdal.Filter.range(limits="returnnumber[1:1]")
        | pdal.Writer.gdal(dsm, output_type="idw", gdaldriver="GTiff", resolution=0.5, radius=1)
    )
    print("Executing DTM pipeline")
    pipeline.execute()
`

But for some reason I get the next error:

**ERROR**
'RuntimeError: writers.gdal: Grid width out of range.'

I have tried with other gdal drivers and I get the same error. The .las file is 3.5 GB and the raster .tif file is supposed to be 0.5 GB. The size of the box that englobes the area is 6.7 km long and 4.7 km wide. 

Is there any other way to obtain the raster file? Is the problem the size of the files? I would have said that GDAL can handle those without major issue... The filters work fine but the problem is at the writers function. 

I am sorry if this is not the place to post this, but any help is appreciated. Thanks! :)

**Comment by abellgithub** [comment]
Is your data in meters? km? something else?

PDAL doesn't keep track of the units. What this is saying is that the range of the X coordinate of your data (unitless) / resolution (.5) is larger than 2^31 -1 OR the data is empty. Data can be empty if you're filtering it all out.

Perhaps you should run the pipeline (without the writer) into the stats filter and see what you get as output.

**Comment by Vicent-Ribas** [comment]
Thank you very much for your answer. The units are meters (las file is in EPSG:5703).

I have done as you suggest and this is part of the stats filter output:

`{
          "average": 0,
          "count": 0,
          "maximum": -1.797693135e+308,
          "minimum": 1.797693135e+308,
          "name": "X",
          "position": 0,
          "stddev": 0,
          "variance": 0
        },`

And same as above for X, Y and Z and Classification.  Does this mean that the data is empty? 

I know data has points classified as 1 and other stuff, my goal is to keep the 1; that is why I was adding the range filter `limits="returnnumber[1:1]"` and I also tried with `limits="Classification[1:1]` with the same output in the stats filter and the same problem with the writer. 

Thank you again.

**Comment by abellgithub** [comment]
Count is 0. You have no data to write.

**Comment by Vicent-Ribas** [comment]
Yes, the reprojection filter was messing things up. I fixed it. Thank you very much, I can now close this.
