### ISSUE TITLE
compiling rdb for use with PDAL

### ISSUE THREAD

**Issue by philwilkes** [PDAL/PDAL#3849]
Hi there

I would like to compile PDAL with RIEGL database (rdb) functionality. In my attempts it appears I need to compile `rdblib` first as PDAL is looking for `riegl/rdb.h` which does not exist.

> In file included from /home/ucfaptv/opt/rdblib-2.4.0-x86_64-linux/interface/cpp/riegl/rdb.hpp:38,
>                  from /home/ucfaptv/opt/PDAL-2.4.3-src/plugins/rdb/io/RdbPointcloud.hpp:41,
>                  from /home/ucfaptv/opt/PDAL-2.4.3-src/plugins/rdb/io/RdbReader.hpp:42,
>                  from /home/ucfaptv/opt/PDAL-2.4.3-src/plugins/rdb/test/RdbReaderTest.cpp:45:
> /home/ucfaptv/opt/rdblib-2.4.0-x86_64-linux/interface/cpp/riegl/rdb/error.hpp:50:10: fatal error: riegl/rdb.h: No such file or directory

The README.txt in `rdblib-2.4.0-x86_64-linux/interface/cpp/riegl` states that:

> ________________________________________________________________________________
> 
>  Using RDB Library in C++
> ________________________________________________________________________________
> 
>  1) Add "interface/c" to the include paths.
>  2) Add "interface/cpp" to the include paths.
>  3) Compile and link "riegl/rdb.cpp".
>  4) Link library "rdblib.dll" or "librdb.so".
> 
> Alternative approach with explicit run-time linking:
> 
>  1) Add #define RDB_RUNTIME_LINKING
>  2) Add "interface/c" to the include paths.
>  3) Add "interface/cpp" to the include paths.
>  4) Compile and link "riegl/rdb.cpp".
>  5) Linux only: link library "libdl" (-ldl)
>  6) Call riegl::rdb::library::load() before using any other RDB library function
> ________________________________________________________________________________

This is where I get a bit lost! If anyone can help with what and how I can proceed that would be great! 

Just to note I have edited `cmake/options.cmake` so that  _"Choose if rdblib support should be built" TRUE_, `rdb_DIR` set as `export rdb_DIR=/home/ucfaptv/opt/rdblib-2.4.0-x86_64-linux/interface/cpp/`, PDAL version 2.3.4 and rdblib version as above

Many thanks. Phil

**Comment by hobu** [comment]
The last time I built RDB support was with

```
-Drdb_DIR=/Users/hobu/dev/release/riegl/rdblib-2.2.3-x86_64-darwin/interface/cpp/
```

Maybe something has changed in their source layout, or we need to add another include directory to the RDB targets.

**Comment by hobu** [comment]
Fixed in cfa827b66bd8e3f04628fb35d9722b0394dc44b2

**Comment by philwilkes** [comment]
Thanks @hobu 

I can get PDAL to compile now - but I can't process rdbx files yet. 

`pdal info 220725_152030.rdbx`

> PDAL: Couldn't create reader stage of type 'readers.rdb'.
> You probably have a version of PDAL that didn't come with a plugin
> you're trying to load.  Please see the FAQ at https://pdal.io/faq

So I ran the test

`./pdal_io_rdb_reader_test`

which returned

> (pdal) -bash-4.2$ ./pdal_io_rdb_reader_test 
> [==========] Running 7 tests from 1 test suite.
> [----------] Global test environment set-up.
> [----------] 7 tests from RdbReaderTest
> [ RUN      ] RdbReaderTest.Reader
> [       OK ] RdbReaderTest.Reader (0 ms)
> [ RUN      ] RdbReaderTest.Missing
> [       OK ] RdbReaderTest.Missing (4 ms)
> [ RUN      ] RdbReaderTest.Metadata
> [       OK ] RdbReaderTest.Metadata (119 ms)
> [ RUN      ] RdbReaderTest.Dimensions
> [       OK ] RdbReaderTest.Dimensions (98 ms)
> [ RUN      ] RdbReaderTest.Points
> [       OK ] RdbReaderTest.Points (113 ms)
> [ RUN      ] RdbReaderTest.Filter
> [       OK ] RdbReaderTest.Filter (108 ms)
> [ RUN      ] RdbReaderTest.Extras
> unknown file: Failure
> C++ exception with description "Can't create dimension with invalid name 'riegl.end_of_scan_line'." thrown in the test body.
> [  FAILED  ] RdbReaderTest.Extras (107 ms)
> [----------] 7 tests from RdbReaderTest (549 ms total)
> 
> [----------] Global test environment tear-down
> [==========] 7 tests from 1 test suite ran. (549 ms total)
> [  PASSED  ] 6 tests.
> [  FAILED  ] 1 test, listed below:
> [  FAILED  ] RdbReaderTest.Extras
> 
>  1 FAILED TEST

Are the two related?

**Comment by hobu** [comment]
`PDAL_DRIVER_PATH` must point to where the `readers.rdb` lives.

As for your test failure, we tightened up dimension names since that code was written. It will need to call the sanitize function or something. 

I don't have a working RIEGL environment at the moment. They haven't released osx-arm packages, and I think the developer who was working on them has left the company.

**Comment by philwilkes** [comment]
Setting `PDAL_DRIVER_PATH` worked for `pdal info`. I haven't had to do this for other readers such as `readers.rxp`.

Thanks again :)
