### ISSUE TITLE
"PDAL: Can't create dimension with invalid name" when specifying "extras" with readers.rdb

### ISSUE THREAD

**Issue by philwilkes** [PDAL/PDAL#3851]
Trying to read an .rdbx file with `readers.rdb`, works great when specifying `readers.rdb.extras` is `false`. But when specifying `readers.rdb.extras` is `true` e.g.:

```
pdal info 220725_152030.rdbx --readers.rdb.extras "true" 
```

I get the error:

> PDAL: Can't create dimension with invalid name 'riegl.mta_zone'.

Many thanks with this and previous queries.

**Comment by abellgithub** [comment]
PDAL doesn't accept dimension names with periods. You'd have to change the name in your data or modify the reader. Some readers handle this by converting disallowed characters to '_' (see the `fix_dims` option in readers.las).

**Comment by philwilkes** [comment]
Very much a beginner at C++ but my ugly hack of _RdbPointcloud.cpp_ looks like this:
```
const auto buffer = std::make_shared<AttributeBuffer>(
    pdal::Dimension::Id::Unknown, // see addDimensions()
    typePDAL,
    namePDAL.str().substr(6, namePDAL.str().length() - 6), 
    m_buffer_size
);  
m_select_query.bind(
    nameRDB.str().substr(6, nameRDB.str().length() - 6), 
    typeRDB,
    buffer->data.data()
); 
```
which removes _riegl._ from the beginning of each dimension name.

**Comment by hobu** [comment]
Call `DimUtil::fixName` on it https://github.com/PDAL/PDAL/blob/a00819d42cfd1ecd7ab85c6d77ec277fa278aac9/pdal/DimUtil.hpp#L202
