### ISSUE TITLE
Update conan recipe for latest release 2.4.3

### ISSUE THREAD

**Issue by vovo-4K** [PDAL/PDAL#3855]
Hi! I'm using conan package manager and PDAL from conan center.
The latest available version is 2.3.0 and I have a build issues on 22.04 related to the newest CMake version.

I created an issue in conan repo [https://github.com/conan-io/conan-center-index/issues/11484](https://github.com/conan-io/conan-center-index/issues/11484) but it seems that PDAL is not very popular for conan users.

Maybe someone have an experience to update the conan recipe.
Thanks!

**Comment by hobu** [comment]
Someone from the Conan community will have to take this up.

**Comment by trns1997** [comment]
Hey guys,
PDAL on conan center is out dated especially since conan 2.0 has released. If you guys accept i am willing to update the recipe as it interests me to build pdal via conan.

**Comment by vovo-4K** [comment]
> Hey guys, PDAL on conan center is out dated especially since conan 2.0 has released. If you guys accept i am willing to update the recipe as it interests me to build pdal via conan.

That would be awesome!
