### ISSUE TITLE
How to use PDAL in my c++ codes

### ISSUE THREAD

**Issue by Toseethebiggerworld** [PDAL/PDAL#3857]
hi,in https://pdal.io/, I just find install  c++ binary files of PDAL by conda,then use the PADL function by running the pdal command. However,i didn't find how to use static library or dynamic library of PADL in https://pdal.io. I'm not sure if I didn't find a method in  https://pdal.io, or if I need to download and compile the source codes of PDAL,then bulid the dynamic library.As you know, there are often various errors in C + + compilation .So ,why not release the static library or dynamic library of PADL,and provide code examples like PCL?

**Comment by hobu** [comment]
You must build your own.
