### ISSUE TITLE
Filters.zsmooth can't be used in python

### ISSUE THREAD

**Issue by yoann-apel** [PDAL/PDAL#3858]
**Describe the bug**
When i want to call the filter zsmooth in Python, i have the error "AttributeError: module 'pdal' has no attribute 'zsmooth'"
pdal.Filter.zsmooth(dim="zsmooth")
```
$ pdal filters zsmooth in.las out.las
```

**Expected behavior**
I want to have a new dimension with the calculated zsmooth

**System/installation information:**
pdal version : 2.4.2 installed on windows with Conda

**Comment by hobu** [comment]
Please try with a new PDAL-python version and conda environment. Things should be working now. reopen if not.
