### ISSUE TITLE
ioctl returns an empty winsize object is running older version of mac and newer version of xcode.

### ISSUE THREAD

**Issue by kylemann16** [PDAL/PDAL#3870]
**Describe the bug**
When running `lldb` from the terminal and interacting with a locally built pdal I find this error:
```
(lldb) run bin/pdal --drivers
error: invalid target, create a target using the 'target create' command
(lldb) target create bin/pdal
Current executable set to '/Users/kmann/code/pdal/build/bin/pdal' (x86_64).
(lldb) run --drivers
Process 28654 launched: '/Users/kmann/code/pdal/build/bin/pdal' (x86_64)
libc++abi.dylib: terminating with uncaught exception of type std::bad_alloc: std::bad_alloc
Process 28654 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x00007fff72e0833a libsystem_kernel.dylib`__pthread_kill + 10
libsystem_kernel.dylib`__pthread_kill:
->  0x7fff72e0833a <+10>: jae    0x7fff72e08344            ; <+20>
    0x7fff72e0833c <+12>: movq   %rax, %rdi
    0x7fff72e0833f <+15>: jmp    0x7fff72e02629            ; cerror_nocancel
    0x7fff72e08344 <+20>: retq   
Target 0: (pdal) stopped.
```
Which is created from [these lines](https://github.com/PDAL/PDAL/blob/master/pdal/util/Utils.cpp#L536-L541), where `ioctl` is called to determine the terminal window size. Because I am running an older version of macos, but xterm continues to receive updates, an unexpected bug occurred as above, where it returns 0 instead of the correct amount. [Here](https://github.com/PDAL/PDAL/blob/master/apps/pdal.cpp#L134-L137) operations are done on the returned value assuming it to be correct. The above bug comes from trying to form a negative number of `=` characters into a string.

**Expected behavior**
I expected `ioctl` to return the correct terminal column length, but instead it returned 0.

**System/installation information:**
Mac version 10.15.7
XCode version 12.4

```
$ uname -a
Darwin Kyles-MBP 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64
```

```
$ pdal --version
----------------------------------------------------------------------------------------------------------------
pdal 2.5.0 (git-version: db4257)
----------------------------------------------------------------------------------------------------------------
```

**Comment by hobu** [comment]
done in https://github.com/PDAL/PDAL/pull/3892
