### ISSUE TITLE
Procedure to install PDAL on Databricks Cluster

### ISSUE THREAD

**Issue by robertwood62** [PDAL/PDAL#3872]
Would it be possible to include a step-by-step guide for installing PDAL into a Databricks cluster?  Attempt to install the Python library using the following lead to a slew of errors that are difficult for me to understand.   Has anyone come up with a recipe for Databricks & PDAL?

In Databricks using pip would be the ideal method...

%pip install pdal

But many errors occur what are difficult to understand.

Python interpreter will be restarted. Using pip 22.2.2 from /local_disk0/.ephemeral_nfs/envs/pythonEnv-00a26a8a-4b1b-4f24-8d5b-e151309b640b/lib/python3.8/site-packages/pip (python 3.8) Collecting pdal==2.4.0   Downloading PDAL-2.4.0.tar.gz (947 kB)      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 947.5/947.5 kB 29.7 MB/s eta 0:00:00   Installing build dependencies: started   Running command pip subprocess to install build dependencies   Collecting wheel     Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)   Collecting scikit-build     Using cached scikit_build-0.15.0-py2.py3-none-any.whl (77 kB)   Collecting cmake     Using cached cmake-3.24.1.1-py2.py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (23.3 MB)   Collecting ninja     Using cached ninja-1.10.2.4-py2.py3-none-manylinux_2_5_x86_64.manylinux1_x86_64.whl (120 kB)   Collecting pytest     Downloading pytest-7.1.3-py3-none-any.whl (298 kB)        ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 298.2/298.2 kB 15.8 MB/s eta 0:00:00   Collecting cython     Downloading Cython-0.29.32-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (1.9 MB)        ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 48.1 MB/s eta 0:00:00   Collecting packaging     Using cached packaging-21.3-py3-none-any.whl (40 kB)   Collecting numpy     Using cached numpy-1.23.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.1 MB)   Collecting setuptools>=28.0.0     Using cached setuptools-65.4.1-py3-none-any.whl (1.2 MB)   Collecting distro     Using cached distro-1.7.0-py3-none-any.whl (20 kB)   Collecting tomli>=1.0.0     Downloading tomli-2.0.1-py3-none-any.whl (12 kB)   Collecting iniconfig     Downloading iniconfig-1.1.1-py2.py3-none-any.whl (5.0 kB)   Collecting pluggy<2.0,>=0.12     Downloading pluggy-1.0.0-py2.py3-none-any.whl (13 kB)   Collecting py>=1.8.2     Downloading py-1.11.0-py2.py3-none-any.whl (98 kB)        ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.7/98.7 kB 13.7 MB/s eta 0:00:00   Collecting attrs>=19.2.0     Downloading attrs-22.1.0-py2.py3-none-any.whl (58 kB)        ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.8/58.8 kB 7.2 MB/s eta 0:00:00   Collecting pyparsing!=3.0.5,>=2.0.2     Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)   Installing collected packages: ninja, iniconfig, cmake, wheel, tomli, setuptools, pyparsing, py, pluggy, numpy, distro, cython, attrs, packaging, scikit-build, pytest   ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.   scipy 1.6.2 requires numpy<1.23.0,>=1.16.5, but you have numpy 1.23.3 which is incompatible.   Successfully installed attrs-22.1.0 cmake-3.24.1.1 cython-0.29.32 distro-1.7.0 iniconfig-1.1.1 ninja-1.10.2.4 numpy-1.23.3 packaging-21.3 pluggy-1.0.0 py-1.11.0 pyparsing-3.0.9 pytest-7.1.3 scikit-build-0.15.0 setuptools-65.4.1 tomli-2.0.1 wheel-0.37.1   Installing build dependencies: finished with status 'done'   Getting requirements to build wheel: started   Running command Getting requirements to build wheel   running egg_info   creating PDAL.egg-info   writing manifest file 'PDAL.egg-info/SOURCES.txt'   writing manifest file 'PDAL.egg-info/SOURCES.txt'   Getting requirements to build wheel: finished with status 'done'   Preparing metadata (pyproject.toml): started   Running command Preparing metadata (pyproject.toml)   running dist_info   creating /tmp/pip-modern-metadata-zic3gk4b/PDAL.egg-info   writing manifest file '/tmp/pip-modern-metadata-zic3gk4b/PDAL.egg-info/SOURCES.txt'   writing manifest file '/tmp/pip-modern-metadata-zic3gk4b/PDAL.egg-info/SOURCES.txt'   Preparing metadata (pyproject.toml): finished with status 'done' Building wheels for collected packages: pdal   Building wheel for pdal (pyproject.toml): started   Running command Building wheel for pdal (pyproject.toml)   Not searching for unused variables given on the command line.   -- The C compiler identification is GNU 9.4.0   -- Detecting C compiler ABI info   -- Detecting C compiler ABI info - done   -- Check for working C compiler: /usr/bin/cc - skipped   -- Detecting C compile features   -- Detecting C compile features - done   -- The CXX compiler identification is GNU 9.4.0   -- Detecting CXX compiler ABI info   -- Detecting CXX compiler ABI info - done   -- Check for working CXX compiler: /usr/bin/c++ - skipped   -- Detecting CXX compile features   -- Detecting CXX compile features - done   -- Configuring done   -- Generating done   -- Build files have been written to: /tmp/pip-install-icexqrxo/pdal_2cea893c72c1474f84c022a14f086391/_cmake_test_compile/build   -- The C compiler identification is GNU 9.4.0   -- The CXX compiler identification is GNU 9.4.0   -- Detecting C compiler ABI info   -- Detecting C compiler ABI info - done   -- Check for working C compiler: /usr/bin/cc - skipped   -- Detecting C compile features   -- Detecting C compile features - done   -- Detecting CXX compiler ABI info   -- Detecting CXX compiler ABI info - done   -- Check for working CXX compiler: /usr/bin/c++ - skipped   -- Detecting CXX compile features   -- Detecting CXX compile features - done   -- Found Python3: /local_disk0/.ephemeral_nfs/envs/pythonEnv-00a26a8a-4b1b-4f24-8d5b-e151309b640b/bin/python (found version "3.8.10") found components: Interpreter Development NumPy Development.Module Development.Embed   CMake Error at CMakeLists.txt:17 (find_package):     By not providing "FindPDAL.cmake" in CMAKE_MODULE_PATH this project has     asked CMake to find a package configuration file provided by "PDAL", but     CMake did not find one.     Could not find a package configuration file provided by "PDAL" (requested     version 2.1) with any of the following names:       PDALConfig.cmake       pdal-config.cmake     Add the installation prefix of "PDAL" to CMAKE_PREFIX_PATH or set     "PDAL_DIR" to a directory containing one of the above files.  If "PDAL"     provides a separate development package or SDK, be sure it has been     installed.   -- Configuring incomplete, errors occurred!   See also "/tmp/pip-install-icexqrxo/pdal_2cea893c72c1474f84c022a14f086391/_skbuild/linux-x86_64-3.8/cmake-build/CMakeFiles/CMakeOutput.log".     File "/tmp/pip-build-env-pa250uk7/overlay/lib/python3.8/site-packages/skbuild/setuptools_wrap.py", line 637, in setup       env = cmkr.configure(     File "/tmp/pip-build-env-pa250uk7/overlay/lib/python3.8/site-packages/skbuild/cmaker.py", line 328, in configure       raise SKBuildError(   --------------------------------------------------------------------------------   -- Trying "Ninja" generator   --------------------------------   ---------------------------   ----------------------   -----------------   ------------   -------   --   --   -------   ------------   -----------------   ----------------------   ---------------------------   --------------------------------   -- Trying "Ninja" generator - success   --------------------------------------------------------------------------------   Configuring Project     Working directory:       /tmp/pip-install-icexqrxo/pdal_2cea893c72c1474f84c022a14f086391/_skbuild/linux-x86_64-3.8/cmake-build     Command:       cmake /tmp/pip-install-icexqrxo/pdal_2cea893c72c1474f84c022a14f086391 -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-icexqrxo/pdal_2cea893c72c1474f84c022a14f086391/_skbuild/linux-x86_64-3.8/cmake-install -DPYTHON_VERSION_STRING:STRING=3.8.10 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-pa250uk7/overlay/lib/python3.8/site-packages/skbuild/resources/cmake -DPython3_EXECUTABLE:FILEPATH=/local_disk0/.ephemeral_nfs/envs/pythonEnv-00a26a8a-4b1b-4f24-8d5b-e151309b640b/bin/python -DPython3_INCLUDE_DIR:PATH=/usr/include/python3.8 -DPython3_LIBRARY:PATH=/usr/lib/x86_64-linux-gnu/libpython3.8.so -DPython3_NumPy_INCLUDE_DIRS:PATH=/databricks/python/lib/python3.8/site-packages/numpy/core/include -DPython_EXECUTABLE:FILEPATH=/local_disk0/.ephemeral_nfs/envs/pythonEnv-00a26a8a-4b1b-4f24-8d5b-e151309b640b/bin/python -DPython_INCLUDE_DIR:PATH=/usr/include/python3.8 -DPython_LIBRARY:PATH=/usr/lib/x86_64-linux-gnu/libpython3.8.so -DPython_NumPy_INCLUDE_DIRS:PATH=/databricks/python/lib/python3.8/site-packages/numpy/core/include -DPYTHON_EXECUTABLE:FILEPATH=/local_disk0/.ephemeral_nfs/envs/pythonEnv-00a26a8a-4b1b-4f24-8d5b-e151309b640b/bin/python -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.8 -DPYTHON_LIBRARY:PATH=/usr/lib/x86_64-linux-gnu/libpython3.8.so -DPYTHON_NumPy_INCLUDE_DIRS:PATH=/databricks/python/lib/python3.8/site-packages/numpy/core/include -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-pa250uk7/overlay/lib/python3.8/site-packages/ninja/data/bin/ninja -DCMAKE_BUILD_TYPE:STRING=Release   Traceback (most recent call last):   An error occurred while configuring with CMake.     Command:       cmake /tmp/pip-install-icexqrxo/pdal_2cea893c72c1474f84c022a14f086391 -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-icexqrxo/pdal_2cea893c72c1474f84c022a14f086391/_skbuild/linux-x86_64-3.8/cmake-install -DPYTHON_VERSION_STRING:STRING=3.8.10 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-pa250uk7/overlay/lib/python3.8/site-packages/skbuild/resources/cmake -DPython3_EXECUTABLE:FILEPATH=/local_disk0/.ephemeral_nfs/envs/pythonEnv-00a26a8a-4b1b-4f24-8d5b-e151309b640b/bin/python -DPython3_INCLUDE_DIR:PATH=/usr/include/python3.8 -DPython3_LIBRARY:PATH=/usr/lib/x86_64-linux-gnu/libpython3.8.so -DPython3_NumPy_INCLUDE_DIRS:PATH=/databricks/python/lib/python3.8/site-packages/numpy/core/include -DPython_EXECUTABLE:FILEPATH=/local_disk0/.ephemeral_nfs/envs/pythonEnv-00a26a8a-4b1b-4f24-8d5b-e151309b640b/bin/python -DPython_INCLUDE_DIR:PATH=/usr/include/python3.8 -DPython_LIBRARY:PATH=/usr/lib/x86_64-linux-gnu/libpython3.8.so -DPython_NumPy_INCLUDE_DIRS:PATH=/databricks/python/lib/python3.8/site-packages/numpy/core/include -DPYTHON_EXECUTABLE:FILEPATH=/local_disk0/.ephemeral_nfs/envs/pythonEnv-00a26a8a-4b1b-4f24-8d5b-e151309b640b/bin/python -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.8 -DPYTHON_LIBRARY:PATH=/usr/lib/x86_64-linux-gnu/libpython3.8.so -DPYTHON_NumPy_INCLUDE_DIRS:PATH=/databricks/python/lib/python3.8/site-packages/numpy/core/include -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-pa250uk7/overlay/lib/python3.8/site-packages/ninja/data/bin/ninja -DCMAKE_BUILD_TYPE:STRING=Release     Source directory:       /tmp/pip-install-icexqrxo/pdal_2cea893c72c1474f84c022a14f086391     Working directory:       /tmp/pip-install-icexqrxo/pdal_2cea893c72c1474f84c022a14f086391/_skbuild/linux-x86_64-3.8/cmake-build   Please see CMake's output for more information.   error: subprocess-exited-with-error     × Building wheel for pdal (pyproject.toml) did not run successfully.   │ exit code: 1   ╰─> See above for output.     note: This error originates from a subprocess, and is likely not a problem with pip.   full command: /local_disk0/.ephemeral_nfs/envs/pythonEnv-00a26a8a-4b1b-4f24-8d5b-e151309b640b/bin/python /local_disk0/.ephemeral_nfs/envs/pythonEnv-00a26a8a-4b1b-4f24-8d5b-e151309b640b/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmp5kfjoc0q   cwd: /tmp/pip-install-icexqrxo/pdal_2cea893c72c1474f84c022a14f086391   Building wheel for pdal (pyproject.toml): finished with status 'error'   ERROR: Failed building wheel for pdal Failed to build pdal

**Comment by hobu** [comment]
> Would it be possible to include a step-by-step guide for installing PDAL into a Databricks cluster?

Sure. A user contribution of this as some kind of tutorial or build recipe would be welcomed. Alternatively, my company is available for hire to develop such things.

**Comment by mnovovil** [comment]
Hello, 
Currently using the following command, but I have issues when writing data back to s3. ( I am using AWS Databricks with apache spark 13.3 and a mounted S3 bucket). I have a hypothesis that it might be linked to the PDAL installation setting, as I can for example run info commands. 


```
rm -r /var/cache/apt/archives/* /var/lib/apt/lists/*
sudo apt-get clean
sudo apt-get update
sudo add-apt-repository -y ppa:ubuntugis/ppa && apt-get update
sudo apt-get install -y gdal-bin libgdal-dev
# sudo apt install libgdal-dev
sudo apt install ninja-build

# Build and install PDAL
git clone https://github.com/PDAL/PDAL.git &&     cd PDAL &&     mkdir build &&     cd build &&     cmake -G Ninja -DLazperf_DIR=/usr/local/ -DWITH_LAZPERF=ON .. &&     ninja &&     ninja install
```

**Comment by robertwood62** [comment]
In my case, we gave up trying to use the libraries directly from our Python code.  We had a need for a very specific version and it was a nightmare to get the python/databricks/linux versions to all line up.  Instead, we were able to install PDAL (the version we wanted) on the servers and we ended up calling the command line tools directly from our Python code.  We found this was very reliable and most of the error codes and outputs from the command line interface matched the library capabilities.  We ran the command line, that outputed files, then we imported and parse the files as required.

________________________________
