### ISSUE TITLE
Add a_srs option to writers.copc

### ISSUE THREAD

**Issue by peterwjacko** [PDAL/PDAL#3874]
The `writers.copc` stage does not have an option for `a_srs` like its `writers.las` counterpart. This is not an issue if the pipeline is end-to-end/read-to-write because the SRS information is forwarded from the reader.

It is a problem in pdal-python if the `writers.copc` stage is used alone. In my case, I read the array and perform some manipulations on the data using NumPy, then write the array to a file. 

```python
tindex_reader = pdal.Reader.tindex(**kwargs).pipeline()
tindex_reader = tindex_reader.execute()
arr = tindex_reader.arrays[0]
modified_arr = do_things(arr)
copc_writer = pdal.Writer(type='writers.copc', **kwargs).pipeline(modified_arr)
copc_writer.execute()
```
There is no way to specify the SRS in the `writers.copc` stage directly or forward the SRS from `readers.xxxx` stage. I also imagine this might be useful if the point cloud is generated synthetically using NumPy and needs to be written to a file. Alternatively, it is possible to define the SRS using a `filters.reprojection` stage before the `writers.copc` stage (thanks for that tip @hobu).

**Comment by peterwjacko** [comment]
> This is an issue only with the python interface, which seems to let you treat a writer as a reader. I don't know that this will always work, but I'm also not sure it won't. 

Are you saying that using writer stages in isolation is a bug or an intentional feature in the python support? I can see how it could be intentional so that writing a numpy array to file is supported, but if it's a bug I can open an issue on PDAL/python.

> The c++ code had no intent of supporting this.

Are you referring to using writer stages in isolation? Or support for `a_srs` in `writers.copc`?

**Comment by hobu** [comment]
Added in #3908
