### ISSUE TITLE
C++ API - filters.estimaterank - scrambles point table

### ISSUE THREAD

**Issue by scudelari** [PDAL/PDAL#3881]
Hello Everyone!
First and foremost, thank you for the amazing work you are doing with this library. It rocks.

I strongly believe I have found a bug in the **filters.estimaterank** filter.

** Environment:
Windows 11 21H2
Visual Studio 2022 17.3
I am using the pdal library version that is installed through the VCPKG. All packages are up to date and the version of PDAL installed is the 2.4.3

** Reproduction - Code that fails
A simple C++ console application using the template of Visual Studio and linking with the libs through VCPKG.

First, the includes and helper function - mostly a copy of the PDAL/writing/tutorial.cpp file **** NOTE - the BufferReader.hpp include file moved so I had to change also the include.

```
// Debug Console CPP.cpp : This file contains the 'main' function. Program execution begins and ends there.
//

#include <pdal/io/BufferReader.hpp>
#include <pdal/PointTable.hpp>
#include <pdal/Dimension.hpp>
#include <pdal/Options.hpp>
#include <pdal/StageFactory.hpp>

#include <vector>

#include <iostream>

void fillView(pdal::PointViewPtr view)
{
    struct Point
    {
        double x;
        double y;
        double z;
    };

    for (int i = 0; i < 1000; ++i)
    {
        Point p;

        p.x = -93.0 + i * 0.001;
        p.y = 42.0 + i * 0.001;
        p.z = 106.0 + i;

        view->setField(pdal::Dimension::Id::X, i, p.x);
        view->setField(pdal::Dimension::Id::Y, i, p.y);
        view->setField(pdal::Dimension::Id::Z, i, p.z);
    }
}
```

Now, a code that **WORKS** - simply writing the output to a text file

```
int main(int argc, char* argv[])
{
    using namespace pdal;

    Options options;
    options.add("filename", "myfile.las");

    PointTable table;
    table.layout()->registerDim(Dimension::Id::X);
    table.layout()->registerDim(Dimension::Id::Y);
    table.layout()->registerDim(Dimension::Id::Z);

    PointViewPtr view(new PointView(table));

    fillView(view);

    BufferReader reader;
    reader.addView(view);

    StageFactory factory;
    Stage* writer = factory.createStage("writers.text");

    writer->setInput(reader);
    writer->setOptions(options);
    writer->prepare(table);
    writer->execute(table);
}
```

The HEAD of the output file 1 is something like this:

```
"X","Y","Z"
-93.000,42.000,106.000
-92.999,42.001,107.000
-92.998,42.002,108.000
```

Now, adding a filter (for example, the filters.eigenvalues) that also **WORKS**:

```
int main(int argc, char* argv[])
{
    using namespace pdal;

    Options options;
    options.add("filename", "myfile.las");

    PointTable table;
    table.layout()->registerDim(Dimension::Id::X);
    table.layout()->registerDim(Dimension::Id::Y);
    table.layout()->registerDim(Dimension::Id::Z);

    PointViewPtr view(new PointView(table));

    fillView(view);

    BufferReader reader;
    reader.addView(view);

    StageFactory factory;

    // FILTER
    pdal::Stage* filter1 = factory.createStage("filters.eigenvalues");
    filter1->setInput(reader);
    // Setting up the options
    pdal::Options filter1Opt;
    filter1Opt.add("knn", std::to_string(8));
    filter1->addOptions(filter1Opt);

    Stage* writer = factory.createStage("writers.text");

    writer->setInput(*filter1);
    writer->setOptions(options);
    writer->prepare(table);
    writer->execute(table);
}
```

The HEAD of the output file 2 is something like this - so far so good

```
"X","Y","Z","Eigenvalue0","Eigenvalue1","Eigenvalue2"
-93.000,42.000,106.000,-0.000,0.000,30.000
-92.998,42.002,108.000,-0.000,0.000,30.000
-92.996,42.004,110.000,-0.000,0.000,30.000
```

Now the code that causes the bug. Let's use the **filters.estimaterank** with default options. There is no error code nor exception being thrown. 

```
int main(int argc, char* argv[])
{
    using namespace pdal;

    Options options;
    options.add("filename", "myfile.las");

    PointTable table;
    table.layout()->registerDim(Dimension::Id::X);
    table.layout()->registerDim(Dimension::Id::Y);
    table.layout()->registerDim(Dimension::Id::Z);

    PointViewPtr view(new PointView(table));

    fillView(view);

    BufferReader reader;
    reader.addView(view);

    StageFactory factory;

    // FILTER
    pdal::Stage* filter1 = factory.createStage("filters.estimaterank");
    filter1->setInput(reader);

    Stage* writer = factory.createStage("writers.text");

    writer->setInput(*filter1);
    writer->setOptions(options);
    writer->prepare(table);
    writer->execute(table);
}
```

The HEAD of the filters.estimaterank output file 3 is something like this - it seems there is some ugly memory problem?

```
"X","Y","Z","Rank"
-93.000,42.000,106.000,2.000
-31574854740288212928329621313746917142735531183595518468700939014876761505751878460513734932866780570942971511919243114243414708498045412519097595399762472228699059876003840.000,0.000,0.000,3.000
1164761898885073897963745292623725124946702099863184605184.000,0.000,-0.000,3.000
-35988309273083040250181349007148829313508176684141708417494577349104359775554172264835448832.000,0.000,-1761727357938517001268777289733912014094336.000,3.000
0.000,0.000,0.000,0.000
-0.000,0.000,-0.000,0.000
0.000,0.000,0.014,1.000
```

Thank you for your time reviewing this.

**Comment by abellgithub** [comment]
The bug is in your code. You need to add the Rank dimension along with X/Y and Z.

**Comment by abellgithub** [comment]
You are writing code using the API. If you're going to use the API, you must understand the API. Please be a bit humble until you have carefully checked what you're doing and understand things sufficiently.

You can't add data to a point table until the layout is finalized. You are adding data to the  table before it is finalized. This may work if the layout doesn't change after you add data, but it will break otherwise. Your use of the eigenvalues filter is also incorrect and produces bad output.

The following code is a reliable way to use a BufferReader:

```
int main(int argc, char* argv[])
{
    using namespace pdal;

    PointTable table;
    table.layout()->registerDim(Dimension::Id::X);
    table.layout()->registerDim(Dimension::Id::Y);
    table.layout()->registerDim(Dimension::Id::Z);

    PointViewPtr view(new PointView(table));

    BufferReader reader;
    reader.addView(view);

    StageFactory factory;

    Stage *filter = factory.createStage("filters.estimaterank");
    filter->setInput(reader);

    Stage* writer = factory.createStage("writers.text");
    Options options;
    options.add("filename", "out.txt");

    writer->setInput(*filter);
    writer->setOptions(options);
    writer->prepare(table);
    table.finalize();
    fillView(view);
    writer->execute(table);
}
```

**Comment by scudelari** [comment]
@abellgithub Thank you, very, very much. This is really good clarification - and **must** be added to the documentation at [https://pdal.io/en/stable/development/writing.html]

Check the example therein. My "code" is a basically a copy and paste of the example. In the example, data is indeed added to the table before any call to prepare and the finalize method is not mentioned at all. 
Nor does the tutorial.ccp file at [https://github.com/PDAL/PDAL/blob/master/examples/writing/tutorial.cpp]

You are absolutelly right when you say that one needs to understand before criticizing, otherwise it is just BS thrown to the wind. But this is not the case. First, reporting a bug is not criticizing - it is assisting. Secondly, I did go after the information by myself, but the official information is misleading.

My final word is just words of gratitude. You went out on your day to answer me, and that counts a lot. Thanks.

**Comment by hobu** [comment]
> Secondly, I did go after the information by myself, but the official information is misleading.

Docs lie and rot, especially for a project like this. Code does too, but not as fast. As you mentioned in #3882, our docs are currently task-focused for people using the utilities and filters in a command line context. 

A good place to find example code how to do something in PDAL is to rummage through the test suite. While it covers edge cases, it also covers how things were expected to behave when we developed them.

**Comment by abellgithub** [comment]
The finalize() method does not actually need to be called in this case. I added it for emphasis (execute() calls finalize()). I'm sorry that the example was misleading, but when you find what you think is an error, the first thing you should do is to figure you what is going on and confirm what you are doing is correct. Asking questions is the better route when something happens that you don't expect and can't figure out on your own.
