### ISSUE TITLE
C++ API - Documentation Cleanup

### ISSUE THREAD

**Issue by scudelari** [PDAL/PDAL#3882]
Hello Everyone,

This is more a suggestion. I have been developing an application using PDAL's C++ API. 

It is great, really. But most of the documentation focus on the development of PDAL plugins (readers, filters, writers). The use case of having a C++ project linking to PDAL is not considered direcly, and I had to gather pieces everywhere to be able to make sense of how to do it.

For example, the https://pdal.io/en/stable/development/writing.html documentation is outdated:
1- The BufferReader include has been moved to #include <pdal/io/BufferReader.hpp>
2- There is no second argument anymore on the createStage function:
```
    // Set second argument to 'true' to let factory take ownership of
    // stage and facilitate clean up.
    Stage *writer = factory.createStage("writers.las");
```

Perhaps it would make sense to 
1- Write a slightly better example, where a couple of filters are included in this pipeline, with a loop reading programatically the output before using a writer stage to send the points elsewhere?
2- Better explain how to access dimensions that are added by some of the filters.

Thank you and have a great day!

**Comment by hobu** [comment]
These are useful suggestions. Please feel free to make pull requests updating the documentation in ways that would have helped you more along your development journey.
