### ISSUE TITLE
writers.copc does not allow configuration of number of threads

### ISSUE THREAD

**Issue by wonder-sk** [PDAL/PDAL#3909]
**Describe the bug**

`writers.copc` uses a thread pool to build COPC hierarchy in parallel. Right now the thread pool size is fixed to 10 threads, not allowing user configuration of it:
https://github.com/PDAL/PDAL/blob/master/io/private/copcwriter/PyramidManager.cpp#L51

It would be useful to have it configurable, to better fit the environment where the code runs.

**Expected behavior**

A configuration option for `writers.copc` similar to what `readers.copc` has - `threads` (and/or its synonym `requests`)

**System/installation information:**

PDAL master

**Comment by hobu** [comment]
Added in #3910
