### ISSUE TITLE
filters.overlay fails to reproject polygon geometries

### ISSUE THREAD

**Issue by wonder-sk** [PDAL/PDAL#3932]
**Describe the bug**

When using `filters.overlay` with data where the input point cloud CRS and input polygon layer CRS do not match up, the polygon geometries should get transformed to the CRS of the point cloud - however this is not happening, and there is no warning/error thrown either - as a result, no points get modified.

A sample pipeline - the LAS file and GPKG (or SHP) need to have different CRS:
  
```json
[
    "trencin-epsg-5514.las",
    {
        "type":"filters.overlay",
        "dimension":"Classification",
        "datasource":"polygons-epsg-4326.gpkg",
        "column":"polygon_id"
    },
    "overlay.las"
]
```

**Expected behavior**

Geometries are transformed correctly and overlay works - or throw an error that the CRS do not match instead of proceeding.

**Possible fix**

It looks like the CRS transform gets done in the code, but incorrectly it uses the same CRS on input and output. This quick hack seems to fix the issue:

```diff
--- a/filters/OverlayFilter.cpp
+++ b/filters/OverlayFilter.cpp
@@ -41,6 +41,7 @@
 #include <pdal/Polygon.hpp>
 #include <pdal/util/ProgramArgs.hpp>
 #include <pdal/private/gdal/GDALUtils.hpp>
+#include <pdal/private/gdal/SpatialRef.hpp>
 
 namespace pdal
 {
@@ -125,13 +126,17 @@ void OverlayFilter::ready(PointTableRef table)
             throwError("No column name '" + m_column + "' was found.");
     }
 
+    gdal::SpatialRef sref;
+    sref.setFromLayer(m_lyr);
+    SpatialReference layerSrs(sref.wkt());
+
     do
     {
         OGRGeometryH geom = OGR_F_GetGeometryRef(feature.get());
         int32_t fieldVal = OGR_F_GetFieldAsInteger(feature.get(), field_index);
 
         m_polygons.push_back(
-            { Polygon(geom, table.anySpatialReference()), fieldVal} );
+            { Polygon(geom, layerSrs), fieldVal} );
 
         feature = OGRFeaturePtr(OGR_L_GetNextFeature(m_lyr), featureDeleter);
     }
```

**System/installation information:**

PDAL master (but also seems to be present in older - e.g. 2.3)

**Comment by hobu** [comment]
Merged in #3940
