### ISSUE TITLE
writers.gdal: grid size has +1 pixel when using bounds

### ISSUE THREAD

**Issue by wonder-sk** [PDAL/PDAL#3934]
Not sure if this is a bug or a feature...

When I set bounds for writers.gdal so that they perfectly match grid resolution, I am getting one extra pixel horizontally and vertically. For example, resolution=1 and bounds being:
```
minx = 5000
miny = 5000
maxx = 6000
maxy = 6000
```
Then I will get a raster grid with sized 1001x1001 instead of 1000x1000 that I expected.

I believe it is due to this code in writers.gdal:
```cpp
    double d_width = std::floor((bounds.maxx - bounds.minx) / m_edgeLength) + 1;
    double d_height = std::floor((bounds.maxy - bounds.miny) / m_edgeLength) + 1;
```

Wouldn't it be more correct to use `ceil((bounds.maxx - bounds.minx) / m_edgeLength)` instead?

**Comment by abellgithub** [comment]
What do you do with the value 6000? What cell does it go in?  If you're thinking [5000, 6000), you're correct, but if you're thinking [5000, 6000], you need 1001 cells in each direction. I'm pretty sure that we have code dating back over 10 years that expected the upper bound to be a valid value.

**Comment by wonder-sk** [comment]
I assumed working with tiled data, so [5000,6000) really. Good point that the closed interval [5000,6000] actually needs 1001 cells, and if the code expects upper bound to be a valid value, then that's fine... I guess I will just switch to using origin_x, origin_y, width and height arguments to make it more clear.

Thanks for the clarification - I will close this ticket given the formula is a deliberate choice to include the upper bound.

**Comment by abellgithub** [comment]
FYI, I kind of wish it were [min, max), but it hasn't been this way since before I started on PDAL. We had (perhaps still have) tests that would fail if you didn't include the max value as a first class value. People will complain no matter what you do on this, I think.
