### ISSUE TITLE
filters.delaunay: 32-bit indices instead of size_t ?

### ISSUE THREAD

**Issue by wonder-sk** [PDAL/PDAL#3935]
The delaunay triangulation with delaunator-cpp uses these major arrays for the computation (added comments on memory use of each vector):

```cpp
    std::vector<double> const& coords;   // 2 * double * N
    std::vector<std::size_t> triangles;  // 2 * 3 * size_t * N
    std::vector<std::size_t> halfedges;  // 2 * 3 * size_t * N
    std::vector<std::size_t> hull_prev;  // size_t * N
    std::vector<std::size_t> hull_next;  // size_t * N
    std::vector<std::size_t> hull_tri;   // size_t * N
```

On 64-bit machines, that will be 136 bytes per point.

I am wondering if it would make sense to switch to smaller sized values (e.g. 32-bit unsigned ints instead of size_t) for all those indices:

 - we could nearly halve the memory consumption (only 76 bytes per point instead of 136 bytes)
 - the execution could be faster - smaller amount of memory touched
 - it is probably unlikely that people want/need to run this on more than 4 billion points

**Comment by hobu** [comment]
Does this ticket belong upstream? https://github.com/delfrrr/delaunator-cpp 

Defaulting to uint32_t for the array sizes seems reasonable to me. Please make a PR.

**Comment by abellgithub** [comment]
This probably should be a typedef in delaunator, like we have point_count_t in PDAL.

**Comment by wonder-sk** [comment]
> Does this ticket belong upstream? https://github.com/delfrrr/delaunator-cpp

Upstream seems to be unmaintained, Andrew's fork has some more fixes: https://github.com/abellgithub/delaunator-cpp

**Comment by abellgithub** [comment]
I think I'm the owner of what's up to date.

**Comment by hobu** [comment]
Leaving this open until it gets upstreamed, but what's merged now is good enough to go forward for the PDAL 2.5.0 release.
