### ISSUE TITLE
SpatialReference::getHorizontalUnits() may return incorrect units

### ISSUE THREAD

**Issue by wonder-sk** [PDAL/PDAL#3946]
I have come across a dataset with this compound CRS:
```
"COMPD_CS[\"NAD83(2011) + unknown\",GEOGCS[\"NAD83(2011)\",DATUM[\"NAD83_National_Spatial_Reference_System_2011\",SPHEROID[\"GRS 1980\",6378137,298.257222101004,AUTHORITY[\"EPSG\",\"7019\"]],AUTHORITY[\"EPSG\",\"1116\"]],PRIMEM[\"Greenwich\",0],UNIT[\"degree\",0.0174532925199433,AUTHORITY[\"EPSG\",\"9122\"]],AXIS[\"Latitude\",NORTH],AXIS[\"Longitude\",EAST],AUTHORITY[\"EPSG\",\"6318\"]],VERT_CS[\"NAVD88 height\",VERT_DATUM[\"North American Vertical Datum 1988\",2005,AUTHORITY[\"EPSG\",\"5103\"]],UNIT[\"metre\",1,AUTHORITY[\"EPSG\",\"9001\"]],AXIS[\"Gravity-related height\",UP],AUTHORITY[\"EPSG\",\"5703\"]]]","horizontal": "GEOGCS[\"NAD83(2011)\",DATUM[\"NAD83_National_Spatial_Reference_System_2011\",SPHEROID[\"GRS 1980\",6378137,298.257222101004,AUTHORITY[\"EPSG\",\"7019\"]],AUTHORITY[\"EPSG\",\"1116\"]],PRIMEM[\"Greenwich\",0],UNIT[\"degree\",0.0174532925199433,AUTHORITY[\"EPSG\",\"9122\"]],AXIS[\"Latitude\",NORTH],AXIS[\"Longitude\",EAST],AUTHORITY[\"EPSG\",\"6318\"]]"
```
It is a mixture of horizontal CRS with lat/lon in degrees, and vertical CRS in meters (fun!)

However PDAL reports in `pdal info` and through SpatialReference::getHorizontalUnits() that horizontal units are meters, not degrees:
```json
      "units":
      {
        "horizontal": "metre",
        "vertical": "metre"
      },
```

The problem is likely related to the implementation in SpatialReference, where the compound WKT is used to call OGRSpatialReference::GetLinearUnits(), for which documentation says that vertical units will be returned for 3D CRS (see https://gdal.org/api/ogrspatialref.html#_CPPv4NK19OGRSpatialReference14GetLinearUnitsEPPc) - which is probably not what we want.

When I tried using GetLinearUnits() with only horizontal CRS from this WKT, it returns `unknown` - which also does not seem correct, but at least it is less wrong than meters :-)  ... but that one could be an issue in GDAL.

**Comment by rouault** [comment]
> When I tried using GetLinearUnits() with only horizontal CRS from this WKT, it returns `unknown`

GetLinearUnits() doesn't make sense for the latitude and longitude axis of a Geographic CRS, which are of angular units (Degree in 99% of the case), not linear.
Probably using OGRSpatialReference::GetAxis() and checking that fabs(*pdfConvFactor - M_PI / 180) < EPS (EPS = 1e-14 for example) is the best way to confirm that the horizontal unit is degree.

**Comment by wonder-sk** [comment]
> GetLinearUnits() doesn't make sense for the latitude and longitude axis of a Geographic CRS, which are of angular units (Degree in 99% of the case), not linear.
> Probably using OGRSpatialReference::GetAxis() and checking that fabs(*pdfConvFactor - M_PI / 180) < EPS (EPS = 1e-14 for example) is the best way to confirm that the horizontal unit is degree.

Thanks for the clarification and the suggestion... it was not obvious to me from the api docs that it does not make sense for lat/lon.

**Comment by hobu** [comment]
> The problem is likely related to the implementation in SpatialReference, where the compound WKT is used to call OGRSpatialReference::GetLinearUnits(), for which documentation says that vertical units will be returned for 3D CRS (see https://gdal.org/api/ogrspatialref.html#_CPPv4NK19OGRSpatialReference14GetLinearUnitsEPPc) - which is probably not what we want.

I don't really want to fix PDAL here. OSR should be embedding all this logic, and it should return the correct units for COMP_CS with different units between vertical and horizontal.
