### ISSUE TITLE
COPC reader and remote files: Could not read from ...

### ISSUE THREAD

**Issue by wonder-sk** [PDAL/PDAL#3949]
Using PDAL 2.5 with COPC reader, trying to access a remote file:
```
pdal info --metadata "https://download-telecharger.services.geo.ca/pub/elevation/pointclouds_nuagespoints/NRCAN/Hamilton_Niagara_2021_2/ON_Niagara_20210525_NAD83CSRS_UTM17N_1km_E567_N4807_CLASS.copc.laz"
```

I get this error:
```
PDAL: Could not read from download-telecharger.services.geo.ca/pub/elevation/pointclouds_nuagespoints/NRCAN/Hamilton_Niagara_2021_2/ON_Niagara_20210525_NAD83CSRS_UTM17N_1km_E567_N4807_CLASS.copc.laz
```

The file exists, and QGIS COPC client is able to stream data from it, so it is unclear why this is failing, the error message does not give much context.

But for example `pdal info --metadata https://s3.amazonaws.com/hobu-lidar/melbourne-2018.copc.laz` works fine.

Running in debugger, this is the backtrace (sorry this is release build of pdal):
![image](https://user-images.githubusercontent.com/193367/213476668-881b329a-5934-4171-aa1d-aa58f1c64ece.png)

**Comment by hobu** [comment]
Something is up with the server here. Both `--summary` and `--metadata` work for our file in S3.

```
pdal info --summary https://s3.amazonaws.com/hobu-lidar/montreal-2015.copc.laz
```

Using `VERBOSE=1` environment variable, I get this output:

```
(pdal-python) hobu-mbp-14 git/pdal/conda-build ~[master|✚8…237⚑104] % pdal info https://download-telecharger.services.geo.ca/pub/elevation/pointclouds_nuagespoints/NRCAN/Hamilton_Niagara_2021_2/ON_Niagara_20210525_NAD83CSRS_UTM17N_1km_E567_N4807_CLASS.copc.laz --metadata
Curl config:
	timeout: 5s
	followRedirect: true
	verifyPeer: true
	caBundle: (default)
	caInfo: (default)
	Proxy: (default)
*   Trying 18.172.122.96:443...
* Connected to download-telecharger.services.geo.ca (18.172.122.96) port 443 (#0)
* ALPN: offers h2
* ALPN: offers http/1.1
*  CAfile: /Users/hobu/miniforge3/envs/pdal-python/ssl/cacert.pem
*  CApath: none
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=download-telecharger.services.geo.ca
*  start date: Dec  5 00:00:00 2022 GMT
*  expire date: Jan  3 23:59:59 2024 GMT
*  subjectAltName: host "download-telecharger.services.geo.ca" matched cert's "download-telecharger.services.geo.ca"
*  issuer: C=US; O=Amazon; CN=Amazon RSA 2048 M01
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* h2h3 [:method: GET]
* h2h3 [:path: /pub/elevation/pointclouds_nuagespoints/NRCAN/Hamilton_Niagara_2021_2/ON_Niagara_20210525_NAD83CSRS_UTM17N_1km_E567_N4807_CLASS.copc.laz]
* h2h3 [:scheme: https]
* h2h3 [:authority: download-telecharger.services.geo.ca]
* h2h3 [accept: */*]
* h2h3 [accept-encoding: deflate, gzip]
* h2h3 [range: bytes=0-588]
* Using Stream ID: 1 (easy handle 0x125036400)
> GET /pub/elevation/pointclouds_nuagespoints/NRCAN/Hamilton_Niagara_2021_2/ON_Niagara_20210525_NAD83CSRS_UTM17N_1km_E567_N4807_CLASS.copc.laz HTTP/2
Host: download-telecharger.services.geo.ca
accept: */*
accept-encoding: deflate, gzip
range: bytes=0-588

* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 403
< content-type: text/html
< content-length: 88
< x-amz-id-2: RI41l9SvaGaF7Emnl++nB6fibMltStkSdNQM1Gd7OMN4k0FUzi+cCEnkFaHOVnsJOaJDrP90SaY=
< x-amz-request-id: 5SK5BYGNJYT95W7R
< date: Thu, 19 Jan 2023 15:14:40 GMT
< last-modified: Mon, 05 Dec 2022 20:27:58 GMT
< etag: "3e014d925bcf694b680fee7709cbfe3f"
< x-amz-server-side-encryption: AES256
< x-amz-version-id: mnSluYkyHfwJBuasBJCyb6HFAU6LqmYM
< accept-ranges: bytes
< server: AmazonS3
< x-cache: Error from cloudfront
< via: 1.1 980a93b7b3ab04fa4e420e9bd003b66a.cloudfront.net (CloudFront)
< x-amz-cf-pop: ORD56-P6
< x-amz-cf-id: SMMFd71483Z9UY6c2EHW_2oFSUUDj6C3esY7lJdUYLl9MRwQBFcGig==
< x-xss-protection: 1; mode=block
< x-frame-options: SAMEORIGIN
< referrer-policy: strict-origin-when-cross-origin
< x-content-type-options: nosniff
< strict-transport-security: max-age=31536000
< vary: Origin
<
* Connection #0 to host download-telecharger.services.geo.ca left intact
PDAL: Could not read from download-telecharger.services.geo.ca/pub/elevation/pointclouds_nuagespoints/NRCAN/Hamilton_Niagara_2021_2/ON_Niagara_20210525_NAD83CSRS_UTM17N_1km_E567_N4807_CLASS.copc.laz
```

**Comment by connormanning** [comment]
I think there's something in the Cloudfront settings requiring a `User-Agent` header to be set.  The below works for me, but without that header I get a 403 status code:
```
pdal info \
  --metadata "https://download-telecharger.services.geo.ca/pub/elevation/pointclouds_nuagespoints/NRCAN/Hamilton_Niagara_2021_2/ON_Niagara_20210525_NAD83CSRS_UTM17N_1km_E567_N4807_CLASS.copc.laz" \
  --readers.copc.header='{"User-Agent":"curl/7.87.0"}'
```

The value of the user-agent can be any arbitrary value, but it does appear to be required by this endpoint configuration.

**Comment by connormanning** [comment]
I don't think this is something we want to address in PDAL - I think this should be upstreamed to the provider of the data.

**Comment by wonder-sk** [comment]
Ah nice catch! Agreed that it's a provider problem... But on a related note, wouldn't it be useful to always specify some default `User-Agent` header in PDAL? It would be certainly good for some analyses on the server side to see which clients and in which versions are being used...

**Comment by jsmoreau** [comment]
I just got confirmation that it will be fixed in the next days.
I kind of agree with @wonder-sk though. In aws, requiring User-Agent header is part of the [general protection rules](https://docs.aws.amazon.com/waf/latest/developerguide/aws-managed-rule-groups-baseline.html) against common threats. This could easily happen again with another provider.

**Comment by hobu** [comment]
To be addressed in #3954 3954

**Comment by jsmoreau** [comment]
It is now fixed on the provider side.

**Comment by hobu** [comment]
> It is now fixed on the provider side.

Can we get a CORS policy?

<img width="1407" alt="image" src="https://user-images.githubusercontent.com/87751/214348362-6fd6aa63-e2dc-4cf2-9fa2-e5736e7f5258.png">


https://viewer.copc.io/?copc=https://download-telecharger.services.geo.ca/pub/elevation/pointclouds_nuagespoints/NRCAN/Hamilton_Niagara_2021_2/ON_Niagara_20210525_NAD83CSRS_UTM17N_1km_E567_N4807_CLASS.copc.laz

**Comment by jsmoreau** [comment]
> > It is now fixed on the provider side.
> 
> Can we get a CORS policy?
> 
> <img alt="image" width="1407" src="https://user-images.githubusercontent.com/87751/214348362-6fd6aa63-e2dc-4cf2-9fa2-e5736e7f5258.png">
> 
> https://viewer.copc.io/?copc=https://download-telecharger.services.geo.ca/pub/elevation/pointclouds_nuagespoints/NRCAN/Hamilton_Niagara_2021_2/ON_Niagara_20210525_NAD83CSRS_UTM17N_1km_E567_N4807_CLASS.copc.laz

Was this run today? I got confirmation that both User-Agent header and CORS were fixed. I tested the CORS requests using a local client and it worked.

**Comment by hobu** [comment]
ah, ok. maybe just the cloudfront timeouts need to happen.

**Comment by jsmoreau** [comment]
<img width="481" alt="2023-01-24 11_48_01-cors-test" src="https://user-images.githubusercontent.com/5244630/214355676-c36cab39-0a50-4329-9706-d07e31b30609.png">
Here is what I get doing a simple AJAX request. It was failing before but now works.
