### ISSUE TITLE
DLL load failed while importing libpdalpython

### ISSUE THREAD

**Issue by Kurtaja** [PDAL/PDAL#3972]
Hi,
I'm getting this error "DLL load failed while importing libpdalpython: The specified module could not be found." when the python execution encounters the "import pdal" command. I'm using a Python 3.11 (64-bit) environment on windows 11 (I'm not running on conda but through a Flask project in Visual Studio). The virtual environment is all fresh and only have 'pdal', 'Pybind11', 'Numpy' and 'scikit-build' installed. I've tried with a Python 3.9 environment, but still getting same error. The pdal version is (3.2.2), though I have tried all the older versions, all giving the same error. The environment is installed in my 'C:\Program Files (x86)\Microsoft Visual Studio\Shared\' folder, and I have tried to add the 'C:\Program Files (x86)\Microsoft Visual Studio\Shared\Pyton_3_11_pdal_env\Lib\site-packages\pdal' folder to the 'environments variables', because I see that the 'libpdalpython.cp311-win_amd64.pyd' is located there. But that does not help either. I've also tried to install the venv in this folder instead 'C:\pyvirtuals\Python_3_11_pdal_env' that does not help either. Greatly appreciated if anybody have an idea what I should do to resolve this.
Kind regards
Kurt

**Comment by hobu** [comment]
you need the conda forge `python-pdal` package installed, and https://github.com/PDAL/Python/ is the more appropriate place for this ticket. Please reopen there if you still have issues after installing the python-pdal package.
