### ISSUE TITLE
filters.projpipeline unable to use a velocity grid in a proj pipeline transformation

### ISSUE THREAD

**Issue by jsmoreau** [PDAL/PDAL#3975]
I'm trying to apply an epoch conversion using a [velocity grid](https://cdn.proj.org/ca_nrc_NAD83v70VG.tif). Here's the pdal pipeline:

```[
    "22_2025210F07_dc.laz",
    {
        "type":"filters.projpipeline",
        "coord_op":"+proj=pipeline +step +inv +proj=tmerc +lat_0=0 +lon_0=-70.5 +k=0.9999 +x_0=304800 +y_0=0 +ellps=GRS80 +step  +proj=cart +ellps=GRS80 +step +proj=deformation +grids=ca_nrc_NAD83v70VG.tif +t_epoch=1997 +step +inv +proj=cart +ellps=GRS80 +step +proj=utm +zone=18 +ellps=GRS80 +geoidgrids=HT2_1997_CGG2013a.tif"
    },
    {
        "type":"writers.las",
        "filename":"22_2025210F07_dc_velocity.laz"
    }
]
```
We execute the pipeline using this command and got the following error:
```
(D:\conda\proj-9.1.1) D:\test_lidar\gridshift\conversion_pdal>pdal pipeline pipeline_velocity_grid.json
(pdal pipeline filters.projpipeline Error) GDAL failure (1) Point outside of projection domain
(pdal pipeline filters.projpipeline Error) GDAL failure (1) Point outside of projection domain
(pdal pipeline filters.projpipeline Error) GDAL failure (1) Point outside of projection domain
(pdal pipeline filters.projpipeline Error) GDAL failure (1) Point outside of projection domain
(pdal pipeline filters.projpipeline Error) GDAL failure (1) Point outside of projection domain
(pdal pipeline filters.projpipeline Error) GDAL failure (1) Point outside of projection domain
(pdal pipeline filters.projpipeline Error) GDAL failure (1) Point outside of projection domain
(pdal pipeline filters.projpipeline Error) GDAL failure (1) Point outside of projection domain
(pdal pipeline filters.projpipeline Error) GDAL failure (1) Point outside of projection domain
(pdal pipeline filters.projpipeline Error) GDAL failure (1) Point outside of projection domain
(pdal pipeline filters.projpipeline Error) GDAL failure (1) Point outside of projection domain
(pdal pipeline filters.projpipeline Error) GDAL failure (1) Point outside of projection domain
(pdal pipeline filters.projpipeline Error) GDAL failure (1) Point outside of projection domain
(pdal pipeline filters.projpipeline Error) GDAL failure (1) Point outside of projection domain
(pdal pipeline filters.projpipeline Error) GDAL failure (1) Point outside of projection domain
(pdal pipeline filters.projpipeline Error) GDAL failure (1) Point outside of projection domain
(pdal pipeline filters.projpipeline Error) GDAL failure (1) Point outside of projection domain
(pdal pipeline filters.projpipeline Error) GDAL failure (1) Point outside of projection domain
(pdal pipeline filters.projpipeline Error) GDAL failure (1) Point outside of projection domain
(pdal pipeline filters.projpipeline Error) GDAL failure (1) Reprojection failed, err = 2050, further errors will be suppressed on the transform object.
```
An empty file gets created.

The proj pipeline was first tested using the cct tool as follow:
```echo 193591.650 5360999.550 236.198 2010 | cct -vv +proj=pipeline +step +inv +proj=tmerc +lat_0=0 +lon_0=-70.5 +k=0.9999 +x_0=304800 +y_0=0 +ellps=GRS80 +step  +proj=cart +ellps=GRS80 +step +proj=deformation +grids=ca_nrc_NAD83v70VG.tif +t_epoch=1997 +step +inv +proj=cart +ellps=GRS80 +step +proj=utm +zone=18 +ellps=GRS80 +geoidgrids=HT2_1997_CGG2013a.tif```
722032.7355   5362647.2287      235.9888     2010.0000

We made sure that the output coordinates are the desired ones. The transformation works if I remove the deformation step in the proj pipeline.

We are using proj 9.1.1 and pdal 2.5.0.

Is the deformation step of proj supported in this filter?

**Comment by hobu** [comment]
> Is the deformation step of proj supported in this filter?

Should be. All the filter does is pass everything down to PROJ. See https://github.com/PDAL/PDAL/blob/master/filters/ProjPipelineFilter.cpp#L124 for details

**Comment by jsmoreau** [comment]
> I'm not completely sure why you get the error, but one reason might be that PDAL doesn't provide the 2010 epoch of the input coordinate. So what is used currently is a bit unspecified. You should probably try to insert `+step +proj=set +v_4=2010` as the first step of the pipeline (see https://proj.org/operations/conversions/set.html). So `+proj=pipeline +step +proj=set +v_4=2010 +step +inv +proj=tmerc +lat_0=0 +lon_0=-70.5 +k=0.9999 +x_0=304800 +y_0=0 +ellps=GRS80 +step +proj=cart +ellps=GRS80 +step +proj=deformation +grids=ca_nrc_NAD83v70VG.tif +t_epoch=1997 +step +inv +proj=cart +ellps=GRS80 +step +proj=utm +zone=18 +ellps=GRS80 +geoidgrids=HT2_1997_CGG2013a.tif` This assumes that the pipeline is only run in its forward direction. If it can be taken in the reverse direction, this would require duplication some steps and using the +omit_fwd / +omit_inv keywords.

Thank you @rouault . I don't get the error anymore. I will still validate the output coordinates to make sure they are ok.
