### ISSUE TITLE
Reading of test file simple.laz fails

### ISSUE THREAD

**Issue by nilason** [PDAL/PDAL#3978]
**Describe the bug**

A copy of the `simple.laz` is used as a test file with GRASS, this is how I came across this issue (https://github.com/OSGeo/grass/issues/2840). Reading the file causes an error on at least Mac (personally tested with arm64):

```
pdal info test/data/laz/simple.laz 
PDAL: Invalid version 1 found in LAZ chunk table.
```

Similar issue has been reported with Ubuntu (https://github.com/OSGeo/grass/pull/2841).

**Expected behavior**
The file should be readable. Alternatively removed if not valid or used (the latter seems to be the case).

**System/installation information:**

```
uname -smr
Darwin 21.6.0 arm64

pdal --version                     
-------------------------------------------------------------------------------------
pdal 2.5.1 (git-version: Release)
-------------------------------------------------------------------------------------
```

**Comment by hobu** [comment]
This is a very old LAZ file
> LASzip compression (version 1.2r0 c1): POINT10 1 GPSTIME11 1 RGB12 1

When PDAL was updated in 2.4, its LAZ support was refactored to use [laz-perf](https://github.com/hobuinc/laz-perf/) which does not have support for the "1.0" version of LAZ.

If you encounter these files, use lastools to convert them to the newer version(s) of LAZ (simple `las2las in.laz out.laz` should be sufficient).

**Comment by nilason** [comment]
Thanks for the tip, managed to convert the file with las2las!

I leave it to you to take further decision on the file in source tree (upgrade, leave it as is, remove...) and close this ticket as you see fit.

**Comment by neteler** [comment]
My 0.02 cents: the existence of `simple.laz` has been of great help in setting up PDAL tests in docker pipelines and elsewhere.
To keep the file (with a needed LAZ format update) would be wonderful - and the PDAL repo the best place for it.

**Comment by hobu** [comment]
yes, I will plan to keep the old LAZ version of `simple.laz` and make a new one.

* `simple.laz` -- LASzip 1.3 compressor compatible
* `simple-laszip-compressor-1.2.laz` -- the current `simple.laz` file renamed

**Comment by neteler** [comment]
(A working version is fine for me, I don't know if the old 1.0 LAZ file is of any value of it cannot be read with current PDAL. My request was just to not delete the small test file completely).

**Comment by hobu** [comment]
Done in #3985
