### ISSUE TITLE
Poisson filter degrades colors (assumes uint8 instead of uint16)

### ISSUE THREAD

**Issue by alexismanin** [PDAL/PDAL#3980]
[LAS format specification](https://www.ogc.org/standard/las/) states that color channels (Red, Green, Blue) are encoded as *unsigned short value*, i.e. `uint16`.

However, code of the Poisson filter copy colors to a uint8. There are multiple places in the filter code where colors are stored using `uint8` : When [copying a point](https://github.com/PDAL/PDAL/blob/master/filters/PoissonFilter.cpp#L212) or [creating a point without density](https://github.com/PDAL/PDAL/blob/master/filters/PoissonFilter.cpp#L146) or [creating a point with density](https://github.com/PDAL/PDAL/blob/master/filters/PoissonFilter.cpp#L159).

As is, a point cloud triangulated using Poisson filters lose its colors if they were normalized as 16 bits values in input, as required by the LAS format specification.

**Comment by hobu** [comment]
The code at https://github.com/PDAL/PDAL/blob/master/filters/PoissonFilter.cpp#L212 needs to be updated.

**Comment by alexismanin** [comment]
Note: As a *temporary workaround*, it is possible to prepend a filter to scale colors to 8bits, thanks to [PDAL assignment filter](https://pdal.io/en/latest/stages/filters.assign.html#example-1). This way, colors are preserved, even if they may lose "depth". A simple example:

```json
{
    "pipeline": [
        { "type": "readers.las", "filename": "dataset.las" },
        // WORKAROUND START: manually scale down colors
        { 
          "type": "filters.assign",
          "value": [
            "Red = Red / 256", 
            "Green = Green / 256", 
            "Blue = Blue / 256"
          ] 
        },
        // WORKAROUND END
        { "type": "filters.poisson" }
    ]
}
```

**Comment by hobu** [comment]
The 8-bit issue is in the Kazhdan code:

```
namespace Kazhdan
{

struct Point
{
    std::array<double, 3> m_position;
    std::array<uint8_t, 3> m_color;
    double m_density;
};
}
```

I think the workaround is going to have to suffice and this is just a limitation unless someone wants to thread uint16_t throughout the Kazhdan code too.

**Comment by alexismanin** [comment]
Then, maybe the documentation of the poisson filter should warn about this limitation, and talk about the possible workaround ?

So that future users have a chance to be aware of the problem before applying the filter ?

**Comment by hobu** [comment]
> Then, maybe the documentation of the poisson filter should warn about this limitation, and talk about the possible workaround ?

I would be happy to merge a PR that did this.
