### ISSUE TITLE
Clang -Wunknown-pragmas compiler warnings

### ISSUE THREAD

**Issue by nilason** [PDAL/PDAL#3981]
**Describe the bug**

The newly introduced #pragma statements in ProgramArgs.hpp are not recognised by Clang and issues warnings. See:

```
/opt/local/include/pdal/util/ProgramArgs.hpp:34:9: warning: unknown pragma ignored [-Wunknown-pragmas]
#pragma warning (push)
        ^
```

This could be fixed by enclosing the pragma blocks:

```c
#if !defined(__clang__)
...
#endif
```

<details>
  
```
/opt/local/bin/clang++-mp-devel -I/opt/local/include -g -pipe -std=c++17 -stdlib=libc++ -I/opt/local/include -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk -arch arm64 -Wall -Wextra -Wno-deprecated-non-prototype  -I/Users/nilason/dev/grass/dist.aarch64-apple-darwin21.6.0/include -I/Users/nilason/dev/grass/dist.aarch64-apple-darwin21.6.0/include   -I/opt/local/include -I/opt/local/include -DPACKAGE=\""grassmods"\"  -I/opt/local/include/postgresql13 -I/opt/local/lib/proj9/include -I/opt/local/include -I/opt/local/include -I/opt/local/include/libxml2 -I/Users/nilason/dev/grass/dist.aarch64-apple-darwin21.6.0/include -I/Users/nilason/dev/grass/dist.aarch64-apple-darwin21.6.0/include -DRELDIR=\"raster/r.in.pdal\" -o OBJ.aarch64-apple-darwin21.6.0/grasslidarfilter.o -c grasslidarfilter.cpp
In file included from grasslidarfilter.cpp:18:
In file included from ./grasslidarfilter.h:31:
In file included from /opt/local/include/pdal/Filter.hpp:39:
In file included from /opt/local/include/pdal/Stage.hpp:45:
In file included from /opt/local/include/pdal/PluginHelper.hpp:43:
In file included from /opt/local/include/pdal/Kernel.hpp:46:
/opt/local/include/pdal/util/ProgramArgs.hpp:34:9: warning: unknown pragma ignored [-Wunknown-pragmas]
#pragma warning (push)
        ^
/opt/local/include/pdal/util/ProgramArgs.hpp:35:9: warning: unknown pragma ignored [-Wunknown-pragmas]
#pragma warning (disable: 4251)
        ^
/opt/local/include/pdal/util/ProgramArgs.hpp:56:9: warning: unknown pragma ignored [-Wunknown-pragmas]
#pragma warning (pop)
        ^
3 warnings generated.

```

</details>

**Expected behavior**

There should be no compiler warnings.

**System/installation information:**

```
uname -smr                                                                                                         
Darwin 21.6.0 arm64
```

```
pdal --version
-----------------------------------------------------------------------
pdal 2.5.1 (git-version: Release)
-----------------------------------------------------------------------
```

```
/opt/local/bin/clang++-mp-devel --version
clang version 16.0.0
Target: arm64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /opt/local/libexec/llvm-devel/bin
```

**Comment by abellgithub** [comment]
These have been this way for years. If you're not going to use the PDAL
cmake process, fixing things is on you.

**Comment by hobu** [comment]
I don't understand this issue. PDAL has used clang since it existed and we didn't have this warning. 

What version is `clang++-mp-devel` and did that remove support for `#pragma warning`?

**Comment by nilason** [comment]
> I don't understand this issue. PDAL has used clang since it existed and we didn't have this warning.

It's a dev version, still not released, of version 16. See above in issue description.

**Comment by abellgithub** [comment]
We suppress that warning. Either the standard build process isn't being used or this compiler/platform isn't yet supported by cmake or something.

**Comment by nilason** [comment]
MacPorts distribution: https://ports.macports.org/port/clang-devel/details/

**Comment by abellgithub** [comment]
Maybe macports should fix things.

**Comment by nilason** [comment]
I should note, these are not warnings from _building_ PDAL, but using the library API from GRASS.

There are some files that issues warnings which need to be suppressed in code, now:
```c
#if defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunused-parameter"
#endif
```

and now `#pragma clang diagnostic ignored "-Wunknown-pragmas"` will have to be added.

**Comment by nilason** [comment]
I see now this (#pragma warning) is not a complete new thing to PDAL, only to the specific file which happened to be included to GRASS. No new feature of Clang either. Closing.

**Comment by abellgithub** [comment]
So I must apologize because I thought you were building PDAL, rather than using the library. The pragma in question is new. I don't know the best way to address this. We have tried to avoid littering the code with #ifdef __clang__ because it's error-prone and ugly.

**Comment by hobu** [comment]
I suppose since grass is using `pdal-config`, it's not getting the proper warnings suppressions. 

See https://github.com/PDAL/PDAL/issues/3979

**Comment by nilason** [comment]
> I suppose since grass is using `pdal-config`, it's not getting the proper warnings suppressions.
> 
> See #3979

As we finally have reached `-Wall -Wextra -Werror` on both gcc and clang on the CI runners, I'd prefer not to insert suppressing flags in the related GRASS code, which would suppress GRASS code too.
As it now stands only 4 files needs the `#if defined(__clang__) ...` directive in GRASS, which is probably better solution for the time being anyway. If I'm not mistaken, Clang 17 will also support, at least partly, these pragmas (https://reviews.llvm.org/D110668 and https://clang.llvm.org/docs/DiagnosticsReference.html#wunknown-pragmas).

**Comment by abellgithub** [comment]
Running `-Werror` is problematic when you're integrating the code of others. I think it's fine running it on your own code, but it's very hard to keep up (or expect others to keep up) with the ever-balooning warnings of numerous compilers. I will think on the issue in ProgramArgs, though @hobu added that MSVC warning suppression that I don't really understand (I understand the warning istself, but I don't understand why it became a problem).

**Comment by hobu** [comment]
> though @hobu added that MSVC warning suppression that I don't really understand (I understand the warning istself, but I don't understand why it became a problem).

The latest version of MSVC started complaining about a usage of it. I didn't look into the details and simply suppressed it.

**Comment by abellgithub** [comment]
Are you explicitly including ProgramArgs.hpp or is it coming along with
other files?

**Comment by nilason** [comment]
> Are you explicitly including ProgramArgs.hpp or is it coming along with other files?

From explicitly including `Filter.hpp`:

```
...
In file included from ./grasslidarfilter.h:31:
In file included from /opt/local/include/pdal/Filter.hpp:39:
In file included from /opt/local/include/pdal/Stage.hpp:45:
In file included from /opt/local/include/pdal/PluginHelper.hpp:43:
In file included from /opt/local/include/pdal/Kernel.hpp:46:
/opt/local/include/pdal/util/ProgramArgs.hpp:34:9: warning: unknown pragma ignored [-Wunknown-pragmas]
#pragma warning (push)
        ^
...
```

**Comment by hobu** [comment]
CharBuf.hpp and a few others have this same pragma. Maybe we should just guard them:

```
#if defined(_MSC_VER)
```
