### ISSUE TITLE
SRS issue with FBI driver, 

### ISSUE THREAD

**Issue by ValentinSchmittDeer** [PDAL/PDAL#3988]
Hi,

## Issue
I would like to convert FBI files to COPC files. There, I noticed an issue in the FBI driver: it does not read the FBI's SRS. I am not a FBI expert, it may be possible that TerraSolid does not record the SRS information into the file itself since it is linked to the project file (.prj).

## Circumvent 
I found 2 ways to circumvent that issue:
1. Export laz file from TerraSolid, convert LAZ to COPC with PDAL
2. Apply a reprojection filter along the way:
```
[
    {
        "type" : "readers.fbi",
        "filename" : "pathIn.fbi"
    },
    {
        "type":"filters.reprojection",
        "in_srs":"EPSG:32628",
        "out_srs":"EPSG:32628"
    },
    {
        "type" : "writers.copc",
        "filename" : "pathOut.laz"
    }
]
```

## Request
Hence, I wondered whether it would not be easier/possible to include a "default_srs" attribute in the readers.fbi. That would lead to this command:
```
[
    {
        "type" : "readers.fbi",
        "filename" : "pathIn.fbi",
        "default_srs": "EPSG:32628"
    },
    {
        "type" : "writers.copc",
        "filename" : "pathOut.laz"
    }
]
```

At that point, would it be also possible to include an "override_srs" attribute in writers to force the output? That would lead to this command:
```
[
    {
        "type" : "readers.fbi",
        "filename" : "pathIn.fbi"
    },
    {
        "type" : "writers.copc",
        "filename" : "pathOut.laz",
        "override_srs": "EPSG:32628"
    }
]
```
  
Thanks
Valentin

**Comment by abellgithub** [comment]
All readers support `default_srs`. It looks like whoever did the doc missed adding the SRS options.

**Comment by ValentinSchmittDeer** [comment]
Great, thanks
