### ISSUE TITLE
Proposal: add in_coord_epoch and out_coord_epoch optional argments in filters.reprojection for time-based coordinate transformations

### ISSUE THREAD

**Issue by rouault** [PDAL/PDAL#3995]
There's currently no easy way to do coordinate transformations with PDAL's filters.reprojection.

For example in https://github.com/PDAL/PDAL/issues/3975, for static CRS -> dynamic CRS or dynamic CRS -> static CRS, the workaround is to write a PROJ pipeline using +set v_4= to set the source or target coordinate epoch.
In the future PROJ may also support dynamic CRS at epoch A -> dynamic CRS at epoch B transformations, that would make writing such pipelines even more complicated.

One possibility currenly would be to use the WKT2:2019 [COORDINATEMETADATA](https://docs.ogc.org/is/18-010r7/18-010r7.html#130) construct that is supported since PROJ 9.2 to fill the in_srs and out_srs arguments of filters.reprojection. But this is quite verbose. I would propose to add ``in_coord_epoch`` and ``out_coord_epoch`` optional arguments, pass them to PDAL's  SrsTransform, which will forward them to GDAL's OGRSpatialReference::SetCoordinateEpoch().

This will allow users to use EPSG codes in ``in_srs`` and ``out_srs`` for compactness , like ``in_srs="EPSG:8255"``, ``out_srs="EPSG:8255"``, ``in_coord_epoch=2023.1``, ``out_coord_epoch=2002``, instead of ``in_srs=COORDINATEMETADATA[GEOGCRS[\"NAD83(CSRS)v7\",DATUM[\"North American Datum of 1983 (CSRS) version 7\",ELLIPSOID[\"GRS 1980\",6378137,298.257222101,LENGTHUNIT[\"metre\",1]]],PRIMEM[\"Greenwich\",0,ANGLEUNIT[\"degree\",0.0174532925199433]],CS[ellipsoidal,2],AXIS[\"geodetic latitude (Lat)\",north,ORDER[1],ANGLEUNIT[\"degree\",0.0174532925199433]],AXIS[\"geodetic longitude (Lon)\",east,ORDER[2],ANGLEUNIT[\"degree\",0.0174532925199433]],USAGE[SCOPE[\"Horizontal component of 3D system.\"],AREA[\"Canada - onshore and offshore - Alberta; British Columbia; Manitoba; New Brunswick; Newfoundland and Labrador; Northwest Territories; Nova Scotia; Nunavut; Ontario; Prince Edward Island; Quebec; Saskatchewan; Yukon.\"],BBOX[38.21,-141.01,86.46,-40.73]],ID[\"EPSG\",8255]],EPOCH[2023.1])`` and ``out_srs=COORDINATEMETADATA[GEOGCRS[\"NAD83(CSRS)v7\",DATUM[\"North American Datum of 1983 (CSRS) version 7\",ELLIPSOID[\"GRS 1980\",6378137,298.257222101,LENGTHUNIT[\"metre\",1]]],PRIMEM[\"Greenwich\",0,ANGLEUNIT[\"degree\",0.0174532925199433]],CS[ellipsoidal,2],AXIS[\"geodetic latitude (Lat)\",north,ORDER[1],ANGLEUNIT[\"degree\",0.0174532925199433]],AXIS[\"geodetic longitude (Lon)\",east,ORDER[2],ANGLEUNIT[\"degree\",0.0174532925199433]],USAGE[SCOPE[\"Horizontal component of 3D system.\"],AREA[\"Canada - onshore and offshore - Alberta; British Columbia; Manitoba; New Brunswick; Newfoundland and Labrador; Northwest Territories; Nova Scotia; Nunavut; Ontario; Prince Edward Island; Quebec; Saskatchewan; Yukon.\"],BBOX[38.21,-141.01,86.46,-40.73]],ID[\"EPSG\",8255]],EPOCH[2002])``

**Comment by hobu** [comment]
I see this as the PDAL analog of https://gdal.org/development/rfc/rfc81_coordinate_epoch.html 

No geospatial point cloud format has a standardized way to describe epoch. LAS, for example, cannot store WKT2019 in any standard way, but we could make our own `pdal` VLR that stored it and preferred to consume it when seen. This would break some downstream interoperability however.
