### ISSUE TITLE
Better support for ClassificationFlags

### ISSUE THREAD

**Issue by wonder-sk** [PDAL/PDAL#4000]
The ClassificationFlags dimension has a bitwise combination of flags (Synthetic, Key-Point, Withheld, Overlap).

Working with these flags is somewhat complicated:
- it is pretty much undocumented how to access those flags (user needs to consult LAS spec and understand bitwise operations)
- it is hard to use expressions to filter them correctly due to missing bitwise ops (e.g. `ClassificationFlags == 2 || Classification == 3 || Classification == 6 || Classification == 10` for key point flag)

It would be useful to have some more direct way of working with them when needed - two solutions that come to mind:
1. have a new parameter in `las.reader` that would add extra true/false dimension(s) for these flags - at the expense of having each point using more memory
2. have "virtual" dimensions - with no extra memory usage. When a value from `KeyPoint` dimension would be requested, PDAL would internally do the bitwise check on ClassificationFlags and return 1/0

**Comment by abellgithub** [comment]
Maybe the easiest thing from an implementation standpoint would be a special operator for the assignment syntax. Maybe something like "dimension[start bit, cnt = 1] to get a value from a bit. You could also use standard C bitwise operations, but currently, all the math currently happens as double-precision floating point, so it would be a bunch of work to do something where you have to know types.

I think maybe this would solve most problems. If you have a 1.3 file and you want to merge it with a 1.4 file, you could do this in an assign filter before merging with 1.4 data:

"value" : "ClassFlags = Classification[5, 3]" // Extract the flags bits
"value" : "Classification = Classification[0, 5]" // Strip the flags bits

Or if you just want to ignore synthetic points at some point, you could extract that bit:
"value" : "Synthetic = Classification[5]"

**Comment by hobu** [comment]
Fixed (hopefully for good) in #4186
