### ISSUE TITLE
filter.decimation changes z-value of output points

### ISSUE THREAD

**Issue by klainkaliber** [PDAL/PDAL#4009]
Applying a pipeline with filter.decimate changes the z-value of points.
It creates steps in the z-values as if they numbers are rounded.

Pipeline:
`
[
	"input.laz",   
   {
        "type":"filters.decimation",
        "step": 5
   },
   {
	"type":"writers.las",
       "compression":"laszip"
	"filename":"output_dec.laz"
   }
]
`

A profile of the original point cloud:
![grafik](https://user-images.githubusercontent.com/3832138/227447759-36b4598a-3e71-4dfe-81fe-6df122ff6277.png)

A profile of the decimated point cloud:
![grafik](https://user-images.githubusercontent.com/3832138/227447865-b1e94562-56df-4e71-822e-9e3080706c68.png)

In comparision, detail:
![grafik](https://user-images.githubusercontent.com/3832138/227447911-4dfdb24f-2aa4-4618-8a38-0f000b455a0c.png)

**Comment by abellgithub** [comment]
You are probably changing the scale of the LAS file when it is written. See
the notes and scale options for writers.las.

**Comment by klainkaliber** [comment]
Thanks for the pointer, I changed scale_x, scale_y, scale_z to 1 - but the result is not as expected (profile in transversal direction):
![grafik](https://user-images.githubusercontent.com/3832138/227865385-50d8cb01-2e2f-4c1e-a2c4-368c8cf96ccf.png)

`
[
	"input.laz",   
   {
        "type":"filters.decimation",
        "step":2
   },
   {
	"type":"writers.las",
    "compression":"laszip",
	"scale_x":1,
	"scale_y":1,
	"scale_z":1,
	"filename":"output_dec.laz"
   }
]
`
I am now getting a 1 by 1 m raster in all directions.
What am I missing here? My expectation would be that scale=1 does take the nominal values into the output file.

**Comment by chambbj** [comment]
You are missing the fact that LAS stores these values as scaled integers. It's covered in the [writers.las](https://pdal.io/en/2.5.2/stages/readers.las.html#readers-las) documentation with a hint as to what to do about it.
