### ISSUE TITLE
Does this error mean my LAS file is corrupted?

### ISSUE THREAD

**Issue by themightyoarfish** [PDAL/PDAL#4010]
https://github.com/PDAL/PDAL/blob/9b4b3f8a9b06820c694f6b776a4d28867b45150c/io/private/las/Header.cpp#L130

I'm running into this problem with a LAS file which displays fine in http://lidarview.com/, but when I run 

```
 pdal info <file>
```

I get 

```
PDAL: readers.las: Invalid point count: 1984602. Number of points too large for file size.
```

Is this evidence of a somehow corrupted file or are there other reasons this might occur?

For the record, CloudCompare 2.11.1 on macOS also swallows this file.

**Comment by abellgithub** [comment]
Yes. It means the file size is too small to contain the number of points
indicated in the header.

**Comment by themightyoarfish** [comment]
Maybe cloudcompare manages to load just the number of points which are readable?
