### ISSUE TITLE
pdal::Geometry copy constructor may segfault

### ISSUE THREAD

**Issue by wonder-sk** [PDAL/PDAL#4016]
The following code crashes:

```cpp
    pdal::Geometry a;
    pdal::Geometry b = a;
```

The copy constructor expects that the source Geometry always has valid OGRGeometryH object, which is not the case here
https://github.com/PDAL/PDAL/blob/master/pdal/Geometry.cpp#L69

PDAL 2.5

**Comment by hobu** [comment]
Should it clone the OGRGeometryH? I suspect sometimes it is a wrapper for geometries owned by OGR datasources, and other times it is our own geometry object.

**Comment by abellgithub** [comment]
It just needs to be protected. I can do it.
