### ISSUE TITLE
PDAL: writers.gdal: Missing value for positional argument 'resolution'

### ISSUE THREAD

**Issue by donharter** [PDAL/PDAL#4023]
PDAL: writers.gdal: Missing value for positional argument 'resolution'
I get this message even though the parameter is there.  I tried it without quotes and as an integer neither works.

Here is my command line
for nam in ` ls *.las`; do base=$(basename $nam .las) ; basetif=$base.tif;pdal translate   $nam $basetif --json pipeline.json ;done
And here is my .json pipeline file:
{
"pipeline":[
    {

      "type":"filters.reprojection",

      "out_srs":"EPSG:4326"

    },

    {

      "type":"filters.assign",

      "assignment":"Classification[:]=0"

    },

    

    
    {

      "type":"filters.smrf",

      "returns":"last",

      "ignore":"Classification[7:7]",

      "slope":0.2,

      "window":16,

      "threshold":0.45,

      "scalar":1.2

    },

    {

      "type":"filters.range",

      "limits":"Classification[2:2]"

    },

    {
    	    "gdaldriver":"GTiff",
            "resolution":"1.0",
            "output_type":"all",
            "type": "writers.gdal"
                      
     }
  
]
}

**Comment by donharter** [comment]
pdal 2.3.0 (git-version: Release)

**Comment by abellgithub** [comment]
You have specified the value as a string rather than a number.

**Comment by donharter** [comment]
I get the same error message if i change it to:
       "resolution":1.0,

**Comment by hobu** [comment]
You are missing a `filename` placeholder on your `writers.gdal`, and I think the error message is confused because `resolution` is the second positional argument on `writers.gdal`.

**Comment by donharter** [comment]
That did not fix it.  I also want to use the filename from the script.
This did not work nor did an empty string.
{
	
	"gdaldriver":"GTiff",
        "resolution":1.0,
        "output_type":"all",
        "type": "writers.gdal",
        "filename":"$basetif" 
                  
 }
