### ISSUE TITLE
Add `stac` item key to pdal info output

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#4027]
```
gdalinfo myfile.tif -json | jq .stac
```

Returns a skeleton STAC item for a resource. We should provide the same for point cloud output in `pdal info --metadata`, `pdal info --summary` or `pdal info --all`.

**Comment by m-mohr** [comment]
Afterwards, we should probably remove/update https://github.com/stac-extensions/pointcloud/blob/main/pdal-to-stac.py
