### ISSUE TITLE
Translating a directory of pcd files

### ISSUE THREAD

**Issue by vttitta** [PDAL/PDAL#4034]
Hello, not sure if this is a dumb question but here it goes: I have a directory of hundreds of pcd-files, how would I go about translating all of them to las? I know how to translate one file at a time but thats a bit too tedious for this many files

**Comment by hobu** [comment]
https://pdal.io/en/latest/workshop/exercises/batch_processing/batch-processing.html provides some example. PDAL is specifically suited for doing batch operations.

Please refrain from using github tickets as support.
