### ISSUE TITLE
Accept reasonable alternative spellings for 'bounds'

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#4042]
# Proposed alternative spellings for `bounds`

PDAL's bounds argument doesn't match anyone else's. It is frustrating when composing pipelines to reformat to match to it. The `bounds` argument as currently spelled is not valid JSON either, and it must be wrapped in a string. The nice thing about that property is we could allow alternative spellings of `bounds` that pivots on whether or not the `bounds` argument is a string or an object

PDAL will continue to emit PDAL-style bounds in pipeline content it writes.

##  Explicitly defined object-style

Explicit object style is commonly used. The only complication for PDAL is what to do about `minz`/`maxz` for situations where they are not defined or unknown. I propose `null`.

We will support explicit bounds style if the following conditions are met:

* Provided `bounds` is a JSON Object
* Each member of `minx`, `miny`, `maxx`, `maxy` MUST exist
* If `minz` or `maxz` is provided, BOTH must be provided
* `crs` member can OPTIONALLY be provided to match PDAL-style capabilities

```
{
    "minx": -10374605,
    "miny": 5431365,
    "minz": null,
    "maxx": -10364394,
    "maxy": 5437681,
    "maxz": null
}

{
    "minx": -10374605,
    "miny": 5431365,
    "maxx": -10364394,
    "maxy": 5437681
}

{
    "minx": -10374605,
    "miny": 5431365,
    "maxx": -10364394,
    "maxy": 5437681,
    "crs":"EPSG:3857"
    
}
```

## GeoJSON bbox style

We will support GeoJSON bbox style if the following conditions are met:

* Must be JSON array
* Must be 4-tuple or 6-tuple
* Must follow GeoJSON ordering
* Must NOT be a string or contained in a string
```
// [minx, miny, maxx, maxy]
[-10374605, 5431365, -10364394, 5437681]
```

```
// [minx, miny, minz, maxx, maxy, maxz]
[-10374605, 5431365, 0, -10364394, 5437681, 100]
```

## Degenerate PDAL style

* If the node provided is a string, it will always be assumed to be a PDAL-style bounds

```
// ([minx, maxx], [miny, maxy])
"([-10374605, -10364394], [5431365, 5437681])"
```

```
// ([minx, maxx,], [miny, maxy], [minz, maxz])
"([-10374605, -10364394], [5431365, 5437681], [0, 100])"
```

**Comment by connormanning** [comment]
Can you attach an SRS to the object style?  Since the existing string one has the magical `"([0,1],[0,1]) / EPSG:1234"` to specify an `SrsBounds`.  Maybe add an optional `srs` key which is forwarded to proj (in which case we don't care whether it's projjson, wkt, proj string, etc).

I'd much rather use either of the 2 new options all the time but without an SRS option that's not always possible.

**Comment by hobu** [comment]
```
{
    "minx": -10374605,
    "miny": 5431365,
    "minz": null,
    "maxx": -10364394,
    "maxy": 5437681,
    "maxz": null
    "crs": "EPSG:26915"
}
```

I like that and it would be straightforward to support. No support for SRS in GeoJSON-style bbox could be provided.

**Comment by hobu** [comment]
Done in #4046
