### ISSUE TITLE
pdal failing to import on Mac M1

### ISSUE THREAD

**Issue by maboualidev** [PDAL/PDAL#4048]
Trying to install pdal and issuing the following command:

```Python
conda install -c conda-forge pdal python-pdal gdal
```

When importing, i.e. `import pdal`, I get bunch of errors as follows:

```bash
Referenced from: 'REDACTED_PATH/lib/libpdal_plugin_reader_nitf.15.3.0.dylib'                                                     
  Expected in: 'REDACTED_PATH/lib/libnitf-cpp.dylib'(PDAL Error) Can't load library REDACTED_PATH/lib/libpdal_plugin_writer_nitf.dylib: Failed to load "REDACTED_PATH/lib/libpdal_plugin_writer_nitf.dylib": dlopen(REDACTED_PATH/lib/libpdal_plugin_writer_nitf.dylib, 0x0002): Symbol not found: (_ACCHZB_handler)
```

This is just one of the errors; Couple of similar errors are shown.

How to fix? any idea? (used to work on the same MAC before; python 3.10 is used here)

**Comment by hobu** [comment]
ouch. I had refreshed the Conda packages the other day and the NITF one is broken. 

The quickest workaround is to remove `$CONDA_PREFIX/lib/libpdal_plugin_reader_nitf*`

**Comment by maboualidev** [comment]
by removing do you mean just deleting them? or do you recommend a different approach.

BTW, thanks for the quick response.

**Comment by hobu** [comment]
yep, just `rm $CONDA_PREFIX/lib/libpdal_plugin_reader_nitf*` from within your activated conda environment.

**Comment by maboualidev** [comment]
I did delete both rm `$CONDA_PREFIX/lib/libpdal_plugin_reader_nitf*` and rm `$CONDA_PREFIX/lib/libpdal_plugin_writer_nitf*`. Now when importing I am not getting those errors anymore. I am assuming this is not affecting reading and writing laz files. because I have not tested that yet.

Thanks for the help.

**Comment by hobu** [comment]
nope, it's just for a driver that is hardly used anymore. Maybe it is time to remove it on OSX.

**Comment by maboualidev** [comment]
Issue addressed. Closing the ticket.
