### ISSUE TITLE
readers.stac.reader_args fails with multiple settings

### ISSUE THREAD

**Issue by connormanning** [PDAL/PDAL#4059]
The [doc](https://pdal.io/en/latest/stages/readers.stac.html) for `readers.stac.reader_args` states that multiple options blocks may be specified for different readers:
```
--readers.stac.reader_args \
  '[{"type": "readers.ept", "resolution": 100}, {"type": "readers.las", "nosrs": true}]'
```

However it doesn't appear to work with an example `pipeline.json` (no other files like `stac.json` are actually needed to reproduce this, it fails immediately due to the `reader_args` option below):
```
[
  {
    "type": "readers.stac",
    "filename": "./stac.json",
    "reader_args": [
      { "type": "readers.ept", "resolution": 100 },
      { "type": "readers.las", "nosrs": true }
    ]
  }
]
```

Reproduction:
```
$ pdal pipeline ./pipeline.json
PDAL: readers.stac: Attempted to set value twice for argument 'reader_args'.
```

If the `reader_args` array has a length of 1 then it works, but with multiple items this failure occurs.

**Comment by kylemann16** [comment]
Ahhh. Yeah I feel like I've had to mess with this exact problem several times now. I thought I had it fixed, but I'm pretty sure I know what this is.

**Comment by hobu** [comment]
reopen if still an issue
