### ISSUE TITLE
PDAL readers.ept issue

### ISSUE THREAD

**Issue by mahtabforoughnia** [PDAL/PDAL#4074]
Hello,
For the ICP registration, I needed to create an EPT index for my LiDAR data, and I used the “entwine build -i ./mydata -o ./myindex” command in the Conda environment. I managed to create one; however, PDAL cannot read the ept.json file of my ept data. I used the following pipeline to read the ept data:

pre_event_index = './pipelines/ept/pre/ept.json'
post_event_index = './pipelines/ept/post/ept.json'
        pipeline = [
            {
                'type':'readers.ept',
                'filename':post_event_index,
                'bounds':'([{},{}],[{},{}])'.format(x - 2,
                                                    x + window_size + 2,
                                                    y - 2,
                                                    y + window_size + 2)
            },
            {
                'type':'readers.ept',
                'filename':pre_event_index,
                'bounds':'([{},{}],[{},{}])'.format(x,
                                                    x + window_size,
                                                    y,
                                                    y + window_size)
            },
            {
                'type':'filters.icp'
            }
        ]

I get the error below:

“ File "D:\PhD_project\NAPA EQ\pdal-icp-example-master\pdal_icp_example.py", line 53, in <module>
    p.execute()
RuntimeError: readers.ept: Error reading tile 0-0-0-0: Unable to open stream for './pipelines/ept/post/ept-data/0-0-0-0.laz' with error 'No error'.

I have tried to create the ept.json file several times and also compared my ept.json with that of the PDAL workshop file. However, I could not see any difference between them to figure out the problem. I really do not know what causes the issue. May you please give me some advice on where the problem can come from? 

I appreciate your time and help.

**Comment by kcotar** [comment]
Which pdal version? I had problems creating ept data with the latest pdal versions, when files do not have a proper global encoding flag or have no srs defined. The same might goes for reading them.

**Comment by mahtabforoughnia** [comment]
The latest one.
the data have a CRS defined, but not sure about the encoding flag. Do you know how to fix it?

**Comment by mahtabforoughnia** [comment]
For whom they might have the same issue:
I solved the issue by using untwine instead of entwine to create ept files from my LiDAR data.

**Comment by mahtabforoughnia** [comment]
For whom they might have the same issue:
I solved the issue by using untwine instead of entwine to create ept files from my LiDAR data.
