### ISSUE TITLE
Pdal tile procedure dropping 0.01% of points 

### ISSUE THREAD

**Issue by kcotar** [PDAL/PDAL#4076]
We have noticed that the tile command consistently drops 0.01% of all input points during the tiling procedure. If I reproject points from tiled files back to the original files and mark "missing" points, a consistent pattern appears. The missing points have indices 9999, 19999, 29999, etc. This looks like an off-by-one error somewhere in pdal tile stream data reader or tile writer, where the reader reads 10k points per batch (my assumption). This is probably a quick fix, but I lack the knowledge about the pdal architecture to tackle.

Example on any LAS file that has more than 10k points (can be stored locally or on S3)
```
$ pdal tile any_file.las tile_#.laz
```

This happens with any of the latest pdal versions, any combination of origin_x, origin_y and length options. Even if only one tile file is produced. The sum of points in created tile_X_Y.laz files will always be smaller than in the original file. The sum of points in tilled files is consistent if only one or countless small tiles are produced, therefore this points me to a reader problem.

Also tested on many different architectures and operating systems, therefore this probably is not a factor here. In all environments, pdal was installed via conda.

**Comment by gui2dev** [comment]
> Noticed this problem with difference between splitting a 11 000 000 points .laz file using kernel.tile or filter.splitter in a pipeline ... Always 1point /10000 missing in the sum of points with kernel.tile vs input file and tiles produced with pipeline (with several files tested). I tried sorting points by X, Y or Z (+ asc and desc) to see if it becomes from the points themselves but 10 000th point, 20 000th, (pdal info -p 9999, 19999,...) and so on always missing whereas the dimension and order of sorting input files. Happens even if each tile is less than 10 000 points so the problem occurs before creation of tiles. Initialy noticed with v2.20 (Debian11 repository version), same results with a 2.5.4 built today from tar.bz2 ... After a look in TileKernel.cpp, seems to me there is perhaps something around these lines where 10 000 -1 = 9 999 ...
> 
> https://github.com/PDAL/PDAL/blob/4030cb3f6557773012a70e84c4be658b6bc59f66/kernels/TileKernel.cpp#L54
> 
> 
> https://github.com/PDAL/PDAL/blob/4030cb3f6557773012a70e84c4be658b6bc59f66/kernels/TileKernel.cpp#L234-L245
> 
> Not able to propose a fix myself (C++ and Github are new worlds for me ... ;-) but if it can help ...

As `idx` starts at 0, when you reach a value of 10k for `idx` it means that the next point to be read will  have `idx` 10 000 in the table.
As capacity of the table is 10k, point index can only yield from 0 to 9 999, therefore meaning that table is full.
