### ISSUE TITLE
readers.las: Extra byte specification exceeds point length beyond base format length.

### ISSUE THREAD

**Issue by claytharrison** [PDAL/PDAL#4078]
Hello! I'm working with some LiDAR data from the Estonian Land Board, and while my pipeline works perfectly on newer data, there's some older data that throws this error:

```
Traceback (most recent call last):
  File "/home/claymsc/estonia_ecolidar/pdal_min_example.py", line 36, in <module>
    vlr_info = read_laz_vlr(laz_file_path)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/claymsc/estonia_ecolidar/pdal_min_example.py", line 19, in read_laz_vlr
    pipeline.execute()
RuntimeError: readers.las: Extra byte specification exceeds point length beyond base format length.
```

Below is a minimal working example to reproduce the above error. Simply un-comment the line that sets `laz_file_path` to the value of the desired LAZ file. It should just write the readers.las record to a text file, but readers.las encounters the above error when running on the 2019 data. All other years work. (They run a scanning campaign yearly in the summer)

```
import pdal

def read_laz_vlr(laz_file_path):
    pipeline_json = """
    {
        "pipeline": [
            {
                "type": "readers.las",
                "filename": "%s"
            },
            {
                "type": "filters.info"
            }
        ]
    }
    """ % laz_file_path

    pipeline = pdal.Pipeline(pipeline_json)
    pipeline.execute()

    vlr_info = pipeline.metadata['metadata']['readers.las']
    return vlr_info

def write_vlr_info_to_file(vlr_info, output_file_path):
    with open(output_file_path, 'w') as f:
        for record in vlr_info:
            f.write(str(record) + '\n')

# Path to the LAZ file
# laz_file_path = "385643_2017_mets.laz"
# laz_file_path = "533524_2018_mets.laz"
laz_file_path = "413524_2019_mets.laz"
# laz_file_path = "385643_2020_mets.laz"
# laz_file_path = "385643_2021_mets.laz"

# Path to the output text file
output_file_path = "min_example_output.txt"

# Read VLR information
vlr_info = read_laz_vlr(laz_file_path)

# Write VLR information to a text file
write_vlr_info_to_file(vlr_info, output_file_path)
```

I can see the issue something to do with the VLR info but I'm new to this and haven't been able to diagnose exactly what is wrong with it. I tried using laspy to check out the VLR info for these files (and a few others from other years) and see what the difference is, but this is where I've gotten stuck. I don't know enough about the LiDAR specification to glean any significance from this, and I'm struggling to dive into this data further with laspy.

```
import laspy

with laspy.open('385643_2017_mets.laz') as fh:
    print('2017 data', fh.header.vlrs)

with laspy.open('533524_2018_mets.laz') as fh:
    print('2018 data', fh.header.vlrs)

with laspy.open('423524_2019_mets.laz') as fh:
    print('2019 data', fh.header.vlrs)

with laspy.open('385643_2020_mets.laz') as fh:
    print('2020 data', fh.header.vlrs)

with laspy.open('385643_2021_mets.laz') as fh:
    print('2021 data', fh.header.vlrs)
```

returns...

```
2017 data [<GeoKeyDirectoryVlr(5 geo_keys)>, <laspy.vlrs.known.WktCoordinateSystemVlr object at 0x7f84fe502690>]
2018 data [<GeoKeyDirectoryVlr(5 geo_keys)>, <laspy.vlrs.known.WktCoordinateSystemVlr object at 0x7f84fe502550>, <VLR(user_id: 'LAStools', record_id: '10', data len: 28)>]
2019 data [<GeoKeyDirectoryVlr(5 geo_keys)>, <laspy.vlrs.known.WktCoordinateSystemVlr object at 0x7f84fe4f5610>, <VLR(user_id: 'LAStools', record_id: '10', data len: 28)>]
2020 data [<ExtraBytesVlr(extra bytes structs: 2)>, <GeoKeyDirectoryVlr(5 geo_keys)>, <laspy.vlrs.known.WktCoordinateSystemVlr object at 0x7f84fe4f7010>, <VLR(user_id: 'LAStools', record_id: '10', data len: 28)>]
2021 data [<GeoKeyDirectoryVlr(5 geo_keys)>, <ExtraBytesVlr(extra bytes structs: 4)>, <laspy.vlrs.known.WktCoordinateSystemVlr object at 0x7f84fe4f6f90>]
```

All 2019 data that I've tried so far is affected, and no other years, so it's not a single corrupted file here but rather a systematic difference in the way they generated the LAZ files in this year. I expect it's not actually a bug on PDAL's end, but I still post the issue here, as I believe you are the most likely folks to be able to tell me what could be going on here, and identify a simple fix on my end if one exists :) I'm hoping I can just tweak or convert the VLR info with laspy somehow before feeding it into PDAL.

You can get the data for the working example directly from the links below, or, if you'd rather grab it from the portal than trust the link, that portal is [here](https://geoportaal.maaamet.ee/eng/Maps-and-Data/Elevation-data/Download-Elevation-Data-p664.html). You can just enter those map sheet numbers ('413524', '385643', etc), and select the appropriate files from the selections returned (`413524_2019_mets.laz`, `385643_2021_mets.laz`, etc).

[working 2017 data](https://geoportaal.maaamet.ee/index.php?lang_id=2&plugin_act=otsing&kaardiruut=385643&andmetyyp=lidar_laz_mets&dl=1&f=385643_2017_mets.laz&no_cache=648453213d975&page_id=664)
[working 2018 data](https://geoportaal.maaamet.ee/index.php?lang_id=2&plugin_act=otsing&kaardiruut=533524&andmetyyp=lidar_laz_mets&dl=1&f=533524_2018_mets.laz&no_cache=6484533c08703&page_id=664)
[non-working 2019 data](https://geoportaal.maaamet.ee/index.php?lang_id=2&plugin_act=otsing&kaardiruut=413524&andmetyyp=lidar_laz_mets&dl=1&f=413524_2019_mets.laz&no_cache=64844a4d724d0&page_id=664)
[working 2020 data](https://geoportaal.maaamet.ee/index.php?lang_id=2&plugin_act=otsing&kaardiruut=385643&andmetyyp=lidar_laz_mets&dl=1&f=385643_2020_mets.laz&no_cache=6484535519778&page_id=664)
[working 2021 data](https://geoportaal.maaamet.ee/index.php?lang_id=2&plugin_act=otsing&kaardiruut=385643&andmetyyp=lidar_laz_mets&dl=1&f=385643_2021_mets.laz&no_cache=648449e5006b3&page_id=664)

I really appreciate any feedback!

**Comment by abellgithub** [comment]
This is not a bug in PDAL. Your data doesn't meet the LAS specification.
Each point has a "point format" that is associated with a certain number of bytes. For instance, point format 1 is 28 bytes. You can add data after the 28 bytes by specifying a point length longer than the point specification. For point format 1, you could specify a point length of 38, which means that there are 10 bytes following those described by the point format. More recent versions of LAS allow (or require) the addition of a VLR that describes these "extra" 10 bytes. Your data has such a specification but is describes more than 10 bytes, thus the error.

You should have your data provider fix the file. You could also fix the file by re-writing the extra bytes VLR to be correct (you'd have to know the data format to do so). You should read the LAS specification for details.

**Comment by mccarthyryanc** [comment]
@claytharrison old issue, but I just ran into the same thing and a quick read/write with laspy seems to work. I'm not sure exactly what is wrong the older Estonian laz data (laspy says point format 8 and point size of 38 :shrug: ) but here is the function I used to fix the data:
```python
def laspy_write(
    source: str,
    dest: str,
    chunk_size: int = 1_234_567,
) -> None:
    """Fix bad laz"""

    with laspy.open(source) as f:
        with laspy.open(dest, mode="w", header=f.header) as writer:
            for points in f.chunk_iterator(chunk_size):
                writer.write_points(points)
```
After that pdal was able to read the `dest` file without error.

**Comment by mccarthyryanc** [comment]
Ah that's why, my method simply drops those attributes because `laspy` isn't even reading that VLR `LASF_Spec/4`, I wasn't interested in them anyway :laughing: I think your fix is the better one, it doesn't drop data!

Thanks for the note on `global_encoding`!
