### ISSUE TITLE
[nanoflann] Errors due to upstream API changes

### ISSUE THREAD

**Issue by MonicaLiu0311** [PDAL/PDAL#4081]
**Describe the bug**
I am the maintainer of vcpkg, and I found that there are some changes in the new version of upstream `nanoflann`. When I updated it to `1.5.0` and installed `pdal`, the following two errors occurred, and `pdal` needs to make corresponding changes. For details, see the upstream: [CHANGELOG.md?plain=1#L2-L13](https://github.com/jlblancoc/nanoflann/blob/v1.5.0/CHANGELOG.md?plain=1#L2-L13)
```
E:\vcpkg01\buildtrees\pdal\src\2.5.3-f9d28ae14f\pdal\private/KDImpl.hpp(100): error C2039: 'SearchParams': is not a member of 'nanoflann'
E:\vcpkg01\buildtrees\pdal\src\2.5.3-f9d28ae14f\pdal\private/KDImpl.hpp(100): error C3861: 'SearchParams': identifier not found
```
```
E:\vcpkg01\buildtrees\pdal\src\2.5.3-f9d28ae14f\pdal\private/KDImpl.hpp(128): error C2664: 'unsigned __int64 nanoflann::KDTreeSingleIndexAdaptor<nanoflann::L2_Simple_Adaptor<double,pdal::KD2Impl,double,uint32_t>,pdal::KD2Impl,-1,size_t>::radiusSearch(const double *,const double &,std::vector<nanoflann::ResultItem<IndexType,double>,std::allocator<nanoflann::ResultItem<IndexType,double>>> &,const nanoflann::SearchParameters &) const': cannot convert argument 3 from 'std::vector<std::pair<size_t,double>,std::allocator<std::pair<size_t,double>>>' to 'std::vector<nanoflann::ResultItem<IndexType,double>,std::allocator<nanoflann::ResultItem<IndexType,double>>> &'
        with
        [
            IndexType=size_t
        ]
```

Vcpkg will temporarily solve this problem in the form of a patch, and remove it after pdal releases a new version. 
Related PR: https://github.com/microsoft/vcpkg/pull/32093

**Expected behavior**
Installation succeeded.

**System/installation information:**
```
2.5.3
```

**Comment by abellgithub** [comment]
@hobu: Are we no longer using vendor'd nanoflann?

**Comment by hobu** [comment]
>  @hobu: Are we no longer using vendor'd nanoflann?

Nothing has changed here. It was last updated 3 years ago https://github.com/PDAL/PDAL/tree/master/vendor/nanoflann 

That ticket looks to me that the target name is clashing with our vendored version.

**Comment by hobu** [comment]
The issue is vcpkg updated nanoflann in-place and we need to update some calls to be able to use that. As I [pointed out in the ticket](https://github.com/microsoft/vcpkg/pull/32093#issuecomment-1602764780), the new nanoflann is slower for our usage, however. I didn't spend the time to figure out why.
