### ISSUE TITLE
Intel ICC/ICPC Support 

### ISSUE THREAD

**Issue by kmilo9999** [PDAL/PDAL#4084]
I noticed in the cmake scripts that intel compilers are not supported. Are there any plans to support this platform?
I would like to build PDAL in a cluster environment, and intel2020 is the suggested compiler to build soft in the system.

**Comment by hobu** [comment]
I'm not sure what you mean by 'not supported'. You're asking about the intel hardware platform, but you haven't stated windows or linux (or OSX). Each of these has an intel compiler. There isn't anything specific in the CMake config about the intel compiler stack, but you should be able to set `CC` and `CXX` variables to point at it and configure cmake and have success.

If not please provide patches necessary to make our CMake configuration work with them.

**Comment by kmilo9999** [comment]
```
Google storage IO will not be available
 CMake Error at cmake/unix_compiler_options.cmake:20 (message):
   Unsupported C++ compiler
 Call Stack (most recent call first):
   cmake/macros.cmake:140 (pdal_target_compile_settings)
   plugins/faux/CMakeLists.txt:5 (PDAL_ADD_PLUGIN)

 Configuring incomplete, errors occurred!
 See also "/gpfs/runtime/opt/pdal/2.5.5/build/CMakeFiles/CMakeOutput.log".
 See also "/gpfs/runtime/opt/pdal/2.5.5/build/CMakeFiles/CMakeError.log".

```

This is my cmake config:
![pdal_error](https://github.com/PDAL/PDAL/assets/16551165/f74a4152-a539-48e2-82ef-bb0bffb71889)

**Comment by hobu** [comment]
Your compiler string is an MPI wrapper

`openmpi_4.0.7_Intel_2020.2_sturm22/bin/mp1cxx`

I could add a conditional to test for the Intel compiler as described by https://cmake.org/cmake/help/latest/variable/CMAKE_LANG_COMPILER_ID.html but I don't have the Intel compiler to test anything.
