### ISSUE TITLE
Hide nanoflann in pdal-specific namespace

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#4085]
>  As far as I can see PDAL doesn't move the vendored copy's symbols into a private namespace. 

Evidently PDAL its leaking its nanoflann usage, so we should probably investigate hiding this.

**Comment by abellgithub** [comment]
I thought you made all symbols private unless specifically exported.

**Comment by hobu** [comment]
> I thought you made all symbols private unless specifically exported, to deal with precisely this issue.

We did, and we do, and we are. I think this is a false report and the ticket can be closed.
