### ISSUE TITLE
Creating surface meshes misses vertex colors in ply output

### ISSUE THREAD

**Issue by khelkun** [PDAL/PDAL#4090]
**Describe the bug**
As reported in https://github.com/PDAL/PDAL/issues/1553#issuecomment-1611333978 I had troubles to understand how to get a surface mesh following the [workshop exercise](https://pdal.io/en/latest/workshop/generation/meshing/meshing.html). Now it works fine with the [autzen.laz](https://github.com/PDAL/data/raw/master/autzen/autzen.laz) sample and this command:
```
$ pdal translate --verbose 4 -i autzen.laz -o autzen.ply poisson --filters.poisson.depth=8 --writers.ply.faces=true
```
[As explained in the exercise](https://pdal.io/en/latest/workshop/generation/meshing/meshing.html#mesh-command), I open the `autzen.ply` in CloudCompare and set the "Colors" property of the mesh to RGB so I can see the colors.

My issue:
I have a `tile_1.las` generated by `pdal split` from a huge LAS file. The huge LAS and the splitted `tile_1.las` load fine into CloudCompare and colors are there.

Running the same upper `pdal translate` command on `tile_1.las` generates a PLY with a correct surface mesh, but the color of all vertices is set to white (225,255,255) in the PLY file.

I converted it to LAZ with `pdal translate tile_1.las tile_1.laz` but the issue remains the same. Here is the [tile_1.zip](https://github.com/PDAL/PDAL/files/11896553/tile_1.zip) containing the  `tile_1.laz`.

I cannot figure out what's the difference between `autzen.laz` & my  `tile_1.laz` but I don't know much about point cloud formats:
- `pdal info --schema` is almost identical for both files (except name, size, timestamp).
- `pdal info --metadata` are different but I don't know what could be related to my issue. Here is the metadata of  `tile_1.laz` [tile_1.metadata.log](https://github.com/PDAL/PDAL/files/11896560/tile_1.metadata.log)

**Expected behavior**
The following command should output a PLY including the colors of vetices:
```
$ pdal translate --verbose 4 -i tile_1.laz -o tile_1.ply poisson --filters.poisson.depth=8 --writers.ply.faces=true
```

**System/installation information:**
Please provide information on your PDAL version (`pdal --version`) and system (e.g., `uname -a` or `ver`).

```
$ ver
Microsoft Windows [Version 10.0.19045.3086]
```

```
$ pdal --version
--------------------------------------------------------------------------------
pdal 2.5.5 (git-version: Release)
--------------------------------------------------------------------------------
```

conda:
<details>
  
```
$ conda list
# packages in environment at C:\Users\xxx\.conda\envs\pdalenv:
#
# Name                    Version                   Build  Channel
blas                      1.0                         mkl
blosc                     1.21.4               hdccc3a2_0    conda-forge
boost-cpp                 1.78.0               h9f4b32c_3    conda-forge
bzip2                     1.0.8                he774522_0
ca-certificates           2023.05.30           haa95532_0
cairo                     1.16.0            hdecc03f_1016    conda-forge
ceres-solver              2.1.0                hb02fd38_1    conda-forge
cfitsio                   4.2.0                h9ebe7e4_0    conda-forge
curl                      8.1.2                h68f0423_0    conda-forge
draco                     1.5.6                h6d14046_0
eigen                     3.4.0                h2d74725_0    conda-forge
expat                     2.5.0                h63175ca_1    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hd3eb1b0_0
font-ttf-inconsolata      2.001                hcb22688_0
font-ttf-source-code-pro  2.030                hd3eb1b0_0
font-ttf-ubuntu           0.83                 h8b1ccd4_0
fontconfig                2.14.2               hbde0cde_0    conda-forge
fonts-anaconda            1                    h8fa9717_0
fonts-conda-ecosystem     1                    hd3eb1b0_0
freetype                  2.12.1               ha860e81_0
freexl                    1.0.6                h2bbff1b_0
geos                      3.11.2               h1537add_0    conda-forge
geotiff                   1.7.1                h4e61e90_9    conda-forge
gettext                   0.21.1               h5728263_0    conda-forge
gflags                    2.2.2                ha925a31_0
glog                      0.6.0                h4797de2_0    conda-forge
hdf4                      4.2.15               h1334946_6    conda-forge
hdf5                      1.14.0          nompi_h918d9b7_103    conda-forge
icu                       72.1                 h63175ca_0    conda-forge
intel-openmp              2023.1.0         h59b6b97_46319
kealib                    1.5.1                hc8369a0_3    conda-forge
krb5                      1.20.1               h5b6d351_0
lcms2                     2.15                 h3e3b177_1    conda-forge
lerc                      4.0.0                h63175ca_0    conda-forge
libaec                    1.0.6                h63175ca_1    conda-forge
libarchive                3.6.2                h6f8411a_1    conda-forge
libblas                   3.9.0                     6_mkl    conda-forge
libcblas                  3.9.0                     6_mkl    conda-forge
libcurl                   8.1.2                h68f0423_0    conda-forge
libdeflate                1.18                 hcfcfb64_0    conda-forge
libexpat                  2.5.0                h63175ca_1    conda-forge
libffi                    3.4.4                hd77b12b_0
libgdal                   3.7.0                h32ef8ef_2    conda-forge
libglib                   2.76.3               he8f3873_0    conda-forge
libiconv                  1.17                 h8ffe710_0    conda-forge
libjpeg-turbo             2.1.5.1              hcfcfb64_0    conda-forge
libkml                    1.3.0             hf2ab4e4_1015    conda-forge
liblapack                 3.9.0                     6_mkl    conda-forge
liblapacke                3.9.0                     6_mkl    conda-forge
libnetcdf                 4.9.2           nompi_ha5afab8_105    conda-forge
libpng                    1.6.39               h8cc25b3_0
libpq                     15.3                 ha9684e8_1    conda-forge
librttopo                 1.1.0               he1da8c1_13    conda-forge
libspatialite             5.0.1               hf8d749d_27    conda-forge
libsqlite                 3.42.0               hcfcfb64_0    conda-forge
libssh2                   1.10.0               he2ea4bf_2
libtiff                   4.5.1                h6c8260b_0    conda-forge
libwebp-base              1.3.0                hcfcfb64_0    conda-forge
libxml2                   2.11.4               hc3477c8_0    conda-forge
libzip                    1.9.2                h519de47_1    conda-forge
libzlib                   1.2.13               hcfcfb64_5    conda-forge
lz4-c                     1.9.4                h2bbff1b_0
lzo                       2.10                 he774522_2
mkl                       2020.4             hb70f87d_311    conda-forge
nitro                     2.7.dev6             h6c2663c_0
openjpeg                  2.5.0                ha2aaf27_2    conda-forge
openssl                   3.1.1                hcfcfb64_1    conda-forge
pcre2                     10.40                h17e33f8_0    conda-forge
pdal                      2.5.5                h22e3bf8_0    conda-forge
pixman                    0.40.0               h2bbff1b_1
poppler                   23.05.0              h45d20d0_1    conda-forge
poppler-data              0.4.11               haa95532_1
postgresql                15.3                 h96452e4_1    conda-forge
proj                      9.2.1                h660b3b0_0    conda-forge
snappy                    1.1.10               hfb803bf_0    conda-forge
sqlite                    3.41.2               h2bbff1b_0
suitesparse               5.4.0                h5d0cbe0_1    conda-forge
tbb                       2021.8.0             h59b6b97_0
tiledb                    2.13.2               h3132609_0    conda-forge
ucrt                      10.0.20348.0         haa95532_0
vc                        14.2                 h21ff451_1
vc14_runtime              14.36.32532         hfdfe4a8_16    conda-forge
vs2015_runtime            14.36.32532         h05e6639_16    conda-forge
xerces-c                  3.2.4                hd77b12b_0
xz                        5.4.2                h8cc25b3_0
zlib                      1.2.13               hcfcfb64_5    conda-forge
zstd                      1.5.5                hd43e919_0
```

</details>

<details>
  
```
$ conda info

     active environment : pdalenv
    active env location : C:\Users\xxx\.conda\envs\pdalenv
            shell level : 2
       user config file : C:\Users\xxx\.condarc
 populated config files : C:\ProgramData\Miniconda3\.condarc
          conda version : 4.11.0
    conda-build version : not installed
         python version : 3.9.16.final.0
       virtual packages : __cuda=12.0=0
                          __win=0=0
                          __archspec=1=x86_64
       base environment : C:\ProgramData\Miniconda3  (read only)
      conda av data dir : C:\ProgramData\Miniconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\Miniconda3\pkgs
                          C:\Users\xxx\.conda\pkgs
                          C:\Users\xxx\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\xxx\.conda\envs
                          C:\ProgramData\Miniconda3\envs
                          C:\Users\xxx\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.11.0 requests/2.29.0 CPython/3.9.16 Windows/10 Windows/10.0.19045
          administrator : False
             netrc file : None
           offline mode : False

```

</details>

**Comment by abellgithub** [comment]
Colors are included if they exist in the input. I would suspect that your input file does not have RGB. You should run `pdal info` on your source laz file to verify the point format/dimensions,

**Comment by khelkun** [comment]
@abellgithub
As far as I know the tile_1.laz and tile_1.las inputs have color data because colors are visible in CloudCompare, as I said in my first post:

> I have a tile_1.las generated by pdal split from a huge LAS file. The huge LAS and the splitted tile_1.las load fine into CloudCompare and colors are there.

**Comment by abellgithub** [comment]
Sorry. I didn't see that.

I still don't understand what you're doing. Are you viewing the PLY output in cloud compare? A las file?

**Comment by khelkun** [comment]
No prob. To make it way shorter an clear:

The `tile_1.laz` in [tile_1.zip](https://github.com/PDAL/PDAL/files/11896553/tile_1.zip) loads in ComputeCloud  v2.13.alpha with colors. 

My issue is that the `tile_1.ply` output by `pdal translate --verbose 4 -i tile_1.laz -o tile_1.ply poisson --filters.poisson.depth=8 --writers.ply.faces=true` loads in ComputeCloud  v2.13.alpha but without colors, even after selecting RGB for the "Colors" property of the "CC Object" section of the ply mesh.

Interesting fact is:
- Loads `tile_1.laz` in [tile_1.zip](https://github.com/PDAL/PDAL/files/11896553/tile_1.zip) in ComputeCloud  
- Select the tile_2.laz entity in the "DB Tree" tab of CloudCompare and save it as `tile_1_pcloud.ply` 
- Choose BINARY when prompted to choose between BINARY or ASCII
- Run `pdal translate --verbose 4 -i tile_1_pcloud.ply -o tile_1_from_ply_pcloud.ply poisson --filters.poisson.depth=8 --writers.ply.faces=true`
- Loads `tile_1_fromply_pcloud.ply` in CloudCompare and you get the surface mesh with colors.

**Comment by abellgithub** [comment]
I am having no problem using the following command:

bin/pdal translate tile_1.laz tile_1.ply --writers.ply.faces=true
> (pdal) $ head -30 tile_1.ply
ply
format ascii 1.0
comment Generated by PDAL
element vertex 994008
property float64 x
property float64 y
property float64 z
property uint16 intensity
property uint8 returnnumber
property uint8 numberofreturns
property uint8 scandirectionflag
property uint8 edgeofflightline
property uint8 classification
property float32 scananglerank
property uint8 userdata
property uint16 pointsourceid
property float64 gpstime
property uint16 red
property uint16 green
property uint16 blue
element face 0
property list uint8 uint32 vertex_indices
end_header
-7.65 -18.13 184.92 0 0 0 0 0 0 0 0 0 0 18944 13568 9216
-7.65 -18.13 184.92 0 0 0 0 0 0 0 0 0 0 19200 13824 8960
-7.65 -18.13 184.92 0 0 0 0 0 0 0 0 0 0 15872 11264 7168
-7.65 -18.13 184.93 0 0 0 0 0 0 0 0 0 0 19712 14080 8704
-7.65 -18.13 184.93 0 0 0 0 0 0 0 0 0 0 17664 12288 7680
-7.65 -18.2 184.94 0 0 0 0 0 0 0 0 0 0 16896 11008 6144
-7.65 -18.2 184.94 0 0 0 0 0 0 0 0 0 0 16128 10240 5888
