### ISSUE TITLE
class flags are getting set when they shouldn't when converting text to las

### ISSUE THREAD

**Issue by kjwaters** [PDAL/PDAL#4094]
When reading a text file (readers.text) that contains points with classes over 31 and then writing the file to an LAS 1.4 record type 6 file, the class flags are getting set as if the class bytes were from LAS 1.2.

```
$ pdal pipeline pipe
```

input file points.txt:

```
X,Y,Z,Classification,Time
50000,10032,0,1,34.3
50001,10033,0,32,34.4
50002,10034,0,64,34.5
```

file pipe  

```
[
{
        "type":"readers.text",
        "filename":"points.txt",
        "default_srs":"EPSG:3717+5703"
},
{
        "type":"writers.las",
        "minor_version":4,
        "dataformat_id":6,
        "filename":"points_pdal.las",
        "forward":"all"
}
]


```

**Expected behavior**
pdal info should show classflags as all zeros. Instead it shows this:
```
{
        "average": 1,
        "count": 3,
        "maximum": 2,
        "minimum": 0,
        "name": "ClassFlags",
        "position": 14,
        "stddev": 1,
        "variance": 1
      }
```

**System/installation information:**

```
pdal 2.5.5 (git-version: 9d28a2)
```

**Comment by kjwaters** [comment]
clearly messed up the formatting on this one. Sorry.

**Comment by abellgithub** [comment]
I don't understand why you think class flags should be zero.

**Comment by kjwaters** [comment]
They should be zero because I didn't set any flags. Zero would be no flags
set. If I set the class to 32, that should be class 32 without setting any
of the classification flags (synthetic, key-point, withheld, or overlap).
Instead, it sets class 32 and synthetic. I suspect classes 128 to 191 would
always be marked as withheld, which would not be intended. I haven't
checked to see if there is a way to set the classification flags from a
text file, but it shouldn't be based on the class number.

Kirk

**Comment by abellgithub** [comment]
This has all become very complex. When receiving input from a text reader, there's no way to know if classification should be interpreted as it would be for LAS 1.3 or LAS 1.4. If the input is 1.3, people often want the flags embedded in the classification to be set in the classFlags for output. I blame this on the way that LAS changed between 1.3 and 1.4, but that can't be changed. Changes have been made to the associated logic to satisfy various demands over time, but I don't believe that we can make everyone's use case work without some sort of user-specified option.

Someone else can chime in WRT their take on the behavior.

**Comment by LFraser** [comment]
I am having the same issue when converting from ply to las. Just wondering if anyone was able to find a solution?

Thanks

**Comment by hobu** [comment]
Please reopen this after 2.6.0 if #4186 doesn't allow you to overcome the issue.
