### ISSUE TITLE
Driver 'writers.ply' is not streamable.

### ISSUE THREAD

**Issue by NanBlanc** [PDAL/PDAL#4095]
**Describe the bug**
I want to tile a 1km*1km .las  file and save tiles as .ply. Sadly .ply writers do not accept "#" placeholder. 
When doing :
```
pdal tile --length 20 -i /home/ostocker/travaux/classified.laz -o /home/ostocker/travaux/test/classified_#.ply
```
PDAL yelds :
```
PDAL: Driver 'writers.ply' for input file '/home/ostocker/travaux/test/classified_#.ply' is not streamable.
```
I tried .las and .txt, and both of them are streamable.
To solve this I am first casting all tiles to .las and convert them afterwards. 

**Expected behavior**
1 : Placeholders on .ply writer
2 : Placeholders on all writers
3 : An update on the wiki to mention streamable and non-streamable writers (as .las has it explained, but not .txt while it works)

**System/installation information:**
pdal 2.5.0
```
$ uname -a
Linux ospc2 5.15.0-56-generic #62~20.04.1-Ubuntu SMP Tue Nov 22 21:24:20 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by abellgithub** [comment]
This appears to be some error in command-line parsing as an error is reported on an *input* file for that which is specified for *output*. I'll see what's up.

**Comment by abellgithub** [comment]
There was a misleading typo in the error message. This has been fixed. The issue that the ply reader is not streamable remains.
