### ISSUE TITLE
A vertical gap appear when reading EPT tiles.

### ISSUE THREAD

**Issue by yplin317** [PDAL/PDAL#4110]
Hello, I am trying to do some study about the lidar dataset near San Francisco area, and found something strange.

This is a screenshot grabbed directly from the Cesium viewer using `ARRA-CA_GoldenGate_2010` dataset ([link here](https://viewer.copc.io/?resources=https://s3-us-west-2.amazonaws.com/usgs-lidar-public/ARRA-CA_GoldenGate_2010/ept.json&options=eyJjb2xvciI6ImludGVuc2l0eSIsInJhbmdlcyI6W3siaWQiOiJpbnRlbnNpdHkiLCJyYW5nZSI6WzAsMjU1XX1dLCJmaWx0ZXJzIjpbeyJpZCI6ImNsYXNzaWZpY2F0aW9uIiwiY29uZGl0aW9uSWQiOiJsb3ctbm9pc2UifSx7ImlkIjoiY2xhc3NpZmljYXRpb24iLCJjb25kaXRpb25JZCI6ImhpZ2gtbm9pc2UifSx7ImlkIjoiY2xhc3NpZmljYXRpb24iLCJjb25kaXRpb25JZCI6IndpdGhoZWxkIn1dfQ==)). The cloud is colorized by elevation, and we can clearly see a gap which is around 30 meters.

![Screenshot 2023-07-17 at 8 00 31 PM](https://github.com/PDAL/PDAL/assets/6982742/f410be85-af6a-49e5-8266-bb154cf96f0c)

I have also tried to use PDAL pipeline described [here](https://pdal.io/en/latest/tutorial/iowa-entwine.html) to produce a laz point cloud of the same area, and I can see the gap as well. 
<details>

```
{
    "pipeline": [
        {
            "bounds": "([-13630000, -13625000], [4548000, 4553000])",
            "filename": "https://s3-us-west-2.amazonaws.com/usgs-lidar-public/ARRA-CA_GoldenGate_2010/ept.json",
            "type": "readers.ept",
            "tag": "readdata"
        },
        {
            "limits": "Classification![7:7]",
            "type": "filters.range",
            "tag": "nonoise"
        },
        {
            "assignment": "Classification[:]=0",
            "tag": "wipeclasses",
            "type": "filters.assign"
        },
        {
            "out_srs": "EPSG:32610",
            "tag": "reprojectUTM",
            "type": "filters.reprojection"
        },
        {
            "filename": "sf.laz",
            "inputs": [ "reprojectUTM" ],
            "tag": "writerslas",
            "type": "writers.las"
        }
    ]
}
```

</details>

However, if I download the laz files directly from TNM Downloader (see image below) and visualize them in CloudCompare, there is no such gap.
![Screenshot 2023-07-17 at 8 19 16 PM](https://github.com/PDAL/PDAL/assets/6982742/8fb02fe6-0617-4bc5-8364-306b493d5c67)

So I am suspecting the lidar data itself is okay, but the gap is introduced by the EPT reader (note the gap happens exactly on the tile boundary)?

**Comment by hobu** [comment]
The proper place for this type of issue is https://github.com/hobuinc/usgs-lidar/ 

That said, the problem is a result of a change in behavior of PROJ from 9.0 -> 9.1+. 

There are two different vertical coordinate system definitions for the files:

```
VERT_CS["NAVD88 height",VERT_DATUM["North American Vertical Datum 1988",2005,EXTENSION["PROJ4_GRIDS","g2012a_conus.gtx,g2012a_alaska.gtx,g2012a_guam.gtx,g2012a_hawaii.gtx,g2012a_puertorico.gtx,g2012a_samoa.gtx"],AUTHORITY["EPSG","5103"]],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["Up",UP],AUTHORITY["EPSG","5703"]]]
```

```
VERT_CS["unknown",VERT_DATUM["unknown",2005],UNIT["metre",1.0,AUTHORITY["EPSG","9001"]],AXIS["Up",UP]]]
```

When the data were processed, we used `EPSG:3857` without specifying any vertical coordinate system because many of the files either didn't have them labeled or they were mislabeled. The behavior of PROJ in regards to COMP_CS/vert_cs definitions changed between PROJ 9.0 and PROJ 9.1, and this is resulting in the discrepancy. The only option would be for @keythread to reprocess and push a new EPT set for this collection, but since it is so old and non-3DEP, it is unknown if @USGS wants to continue to do that.

**Comment by yplin317** [comment]
Thank you @hobu for the quick response and explanation 🙂.
