### ISSUE TITLE
Infinitely-running relaxationdartthrowing filter

### ISSUE THREAD

**Issue by SalzingerJ** [PDAL/PDAL#4119]
Hello, I am having issues with the relaxationdartthrowing filter used as below :

```
$ pdal translate in.laz out.laz relaxationdartthrowing <options>
```

I would expect the filter to throw errors or otherwise adapt to the following situations :

- the "count" parameter is more or equal to the starting number of points in in.laz
- several points are very close to eachother/have the same position

Instead, the current behaviour as far as I can see in those situations is that the filter simply gets stuck and runs "infinitely" (or at least, more than 10 minutes even for very small point clouds of <200 points).

This also happens is other cases when the parameter "count" is close but still strictly smaller than the number of points in in.laz, even after running the "sample" filter to remove very close points. However, I was not able to figure out the cause, nor a reason for which threshold for "count" would completely solve the issue.

**System/installation information:**

```
$ uname -a
Linux L1AAS87 5.19.0-46-generic #47~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jun 21 15:35:31 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ pdal --version
pdal 2.5.5 (git-version: 9d28a2)
```
(installed with conda)

**Comment by hobu** [comment]
> Instead, the current behaviour as far as I can see in those situations is that the filter simply gets stuck and runs "infinitely" (or at least, more than 10 minutes even for very small point clouds of <200 points).

Can you please post this file?

**Comment by chambbj** [comment]
I agree. We should clean this up. The filter can definitely get stuck running indefinitely if the count cannot be reached. It just keeps trying over and over again with smaller radii.

**Comment by chambbj** [comment]
Going to finally put this one to bed today. My plan is to

1. Check for input view smaller than requested number of output points, and return the input view if it's smaller.
2. Add a minimum radius parameter and terminate once it is reached. Will probably default this to 1 mm which is overkill for aerial lidar applications.

**Comment by SalzingerJ** [comment]
This seems like a decent fix, thanks.
