### ISSUE TITLE
core dump in latest code, also present in tagged version 2.5.5

### ISSUE THREAD

**Issue by elidwa** [PDAL/PDAL#4123]
I pulled latest pdal sources from git head/master and built successfully as per documentation. Checking pdal version core dumps.

$ bin/pdal --version
pdal 2.6.0 (git-version: eb9c3b)
free(): invalid pointer
Aborted (core dumped)

I tried the first recommended test:
bin/pdal info ../test/data/las/autzen_trim.las
...
free(): invalid pointer
Aborted (core dumped)

I discarded the build and pulled the tagged version 2.5.5 thinking that maybe the head/master is unstable. I got exactly the same core dump with 2.5.5:

$ bin/pdal --version
pdal 2.5.5 (git-version: da7bb9)
free(): invalid pointer
Aborted (core dumped)

```
$ uname -a
```
Linux ip-172-31-60-215 5.15.0-1040-aws #45~20.04.1-Ubuntu SMP Tue Jul 11 19:11:12 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux

**Comment by abellgithub** [comment]
This is unlikely a problem with PDAL since we build the application and run tests continuously.

You'll have to at least provide the cmake configuration output and the backtrace, but since you're building the application yourself, you probably need to debug this on your own.
