### ISSUE TITLE
PDAL info to s3 requester pay

### ISSUE THREAD

**Issue by xycarto** [PDAL/PDAL#4143]
I am curious if there is method to pass `--request-payer requester` to the following command in terminal:

```
pdal info --summary s3://usgs-lidar/Projects/CA_CarrHirzDeltaFires_2019_B19/CA_CarrHirzDeltaFires_1_2019/LAZ/USGS_LPC_CA_CarrHirzDeltaFires_2019_B19_10TDK0479244992.laz
```

My current PDAL version is: 2.6.0

I might be missing something basic, but I am curious if an operation like this, from terminal or Python, is even possible. 

The context is, I am trying to capture the Point Cloud summary data, without downloading the entire file.  If I know the summary, then I can determine if I really want the file.

**Comment by xycarto** [comment]
PDAL is by far the best tool for producing data rich information from the point cloud andI still think it would be interesting to learn how to do this. Instead I shifted my method so remove the need to do a `info` direct from S3.  Instead, I shifted to using `laspy`.  The method to extract only the information I want from the point cloud header is:

1. Download only the first 10kb of data from the point cloud on S3 (this can be done with `request-payer`)
2. Save as a 10kb LAZ
3. Parse the header using `laspy` to get extents and point count. Lazpy seems to be able to handle the limitied file without issue

It is not the most elegant solution and does not capture the crs or density, but it does help me build an index from 400K plus files in a relatively short amount of time. 

I think my downfall in this question was that I was under the assumption PDAL info would only read the necessary header info from S3. My guess is, PDAL needs the full point cloud file to make the `info` operation run correctly, therefore, it needs to scan the entire file first to account for records at the end. This operation negates a quick read from S3 for just the metadata. 

If I am correct, the COPC format might actually make just a header read from S3 possible in the future.

**Comment by hobu** [comment]
> If I am correct, the COPC format might actually make just a header read from S3 possible in the future.

the `preview()` method of both `readers.copc` and `readers.ept` will access content over S3 to determine what data to read, and they both can efficiently do that given how the data is organized and the metadata provided.

We can't really do that for regular LAS files. We've written some custom stuff to build indexes of big collections of data like you are doing, but it is very fragile. Are all of your SRS in VLR and not eVLR? Do you have extra byte dimensions? Which LAS point data record format? And so on. Generalized tools for doing that specialized task is out of scope for PDAL.

**Comment by hobu** [comment]
I would note that the ticket's question about passing S3 RequesterPays header info, you can do so with a `header` option of both `readers.ept` and `readers.copc`. That hasn't been added generically to any driver.

**Comment by xycarto** [comment]
> Are all of your SRS in VLR and not eVLR? Do you have extra byte dimensions? Which LAS point data record format?

It's all mixed data and formats. I am fortunate to be working with the WESM.gpkg provided by USGS, so I can capture the CRS from this file. For now, just having the extents and point count will suffice for indexing. The real purpose is to have a GPKG index file that points back the actual location of the point cloud on S3. I originally planning on attaching the metadata to the index file and had it working with PDAL 2.3, but it was pretty wonky.

More info here: https://github.com/xycarto/wesm-grids/tree/main

Thanks for the update. I'm very excited to work with COPC in the future
