### ISSUE TITLE
Url http://pdal.io/PDAL.pdf is broken on main docs index.html

### ISSUE THREAD

**Issue by jo-chemla** [PDAL/PDAL#4147]
In [main index page](https://pdal.io/en/latest/index.html) - link on repo: https://github.com/PDAL/PDAL/blob/master/doc/index.rst 
The link http://pdal.io/PDAL.pdf to `PDAL.pdf` is broken and redirects to https://pdal.io/en/latest/PDAL.pdf which returns `404 Not Found`

`The entire website is available as a single PDF at http://pdal.io/PDAL.pdf`

It could redirect to https://raw.githubusercontent.com/PDAL/pdal.github.io/master/PDAL.pdf which is served from https://github.com/PDAL/pdal.github.io/blob/master/PDAL.pdf

**Comment by hobu** [comment]
Will be fixed at 2.6
