### ISSUE TITLE
Support for 3D Polygons in filters.crop

### ISSUE THREAD

**Issue by cs23** [PDAL/PDAL#4151]
Hi,

Current filters.crop is limited to 3D cropping to only a sphere or rectangular bounding box shape. Adding the ability to do a full 3D crop defined by a polygon with a z coordinate opens up complex cropping operations such object segmentation and cropping over shape files that vary in height across horizontal coordinates.

Thanks!

**Comment by abellgithub** [comment]
You need to be specific about the behavior you desire. Are you talking
about a prism where the polygons lie in an xy plane? Something else?

 https://en.wikipedia.org/wiki/Prism_(geometry)

**Comment by cs23** [comment]
From your description, it would be similar to a truncated prism

https://en.wikipedia.org/wiki/Prism_(geometry)#Truncated_prism

But even a triangular prism would also be a starting point.

**Comment by hobu** [comment]
If I needed this today, I would:

1) Get a PDAL pipeline working in the Python bindings
2) Add or use some kind of flag dimension with `filters.attribute` 
3) Write a `filters.python` function that used a CGAL polyhedron representation to stream in X,Y,Z point positions and mark them as inside or outside
4) Write a `filters.expression.expression` that only keeps the points with `1` in the flag dimension as set in #3

**Comment by hobu** [comment]
We are not going to add 3D polyhedron intersection support in PDAL if the library functions that provide it require linking some additional library we're not currently linking. For us right now, that means the capability would need to be in GEOS and exposed through GDAL. I don't think that's currently the case. Please reopen with a pull request if you do implement in that direction.
