### ISSUE TITLE
readers.las always fetches the entire file, even if no points are requested

### ISSUE THREAD

**Issue by olsen232** [PDAL/PDAL#4165]
**Describe the bug**
Using readers.las with points=0 always fetches the entire file.
Eg the following command:
`pdal info https://some-large-las-file --driver readers.las --readers.las.count=0`
Or as a pipeline:
```
[
  {
    "type": "readers.las",
    "filename": "s3://some-large-las-file",
    "count": 0
  },
  {
    "type": "filters.info"
  }
]
```
Or by using the flag `--metadata` which only has output that doesn't depend on the points and requests no points:
`pdal info s3://some-large-las-file --driver readers.las --metadata`

**Expected behavior**
Ideally, this would only fetch the headers of the LAS file when no points are required, which could be 1000 times smaller.

**System/installation information:**
```
$ uname -a
Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:56 PDT 2023; root:xnu-8796.141.3~6/RELEASE_X86_64 x86_64
```

```
$ pdal --version
pdal 2.6.0
```

Bigger picture:
There may be other readers that fetch the entire file file regardless.
There may be other operations that would ideally fetch just the headers, or just the headers plus some sample of points.

**Comment by abellgithub** [comment]
Dare I ask what, exactly, you're trying to do?

**Comment by olsen232** [comment]
Indexing remote stores of point clouds, potentially as part of https://kartproject.org/

**Comment by abellgithub** [comment]
Can you be more specific? Precisely what fields do you want from the remote data? Can't this kind of thing be done through STAC access?

**Comment by rcoup** [comment]
> Can't this kind of thing be done through STAC access?

Sure, if there is STAC. But a STAC catalog also needs building/populating...

**Comment by olsen232** [comment]
The info I'm interested in currently is LAS version, whether LAS or LAZ, whether COPC or not, point-data-record-format, maybe extra dimensions, tile extent, point-count, and CRS. But happily the approach is generic and doesn't depend on which particular metadata fields are required, as long as it can be done while requesting zero points.

**Comment by j9ac9k** [comment]
> The info I'm interested in currently is LAS version, whether LAS or LAZ, whether COPC or not, point-data-record-format, maybe extra dimensions, tile extent, point-count, and CRS. But happily the approach is generic and doesn't depend on which particular metadata fields are required, as long as it can be done while requesting zero points.

Does `quickinfo` not provide that information?

**Comment by olsen232** [comment]
I wasn't aware of quickinfo so I've just had to learn a bit about it. It looks like quickinfo does provide the info I'm interested in, or at least most of it - haven't dug deeply. However, `QuickInfo LasReader::inspect()` depends on `LasReader::initialize` depends on `LasReader::initializeLocal`, which (when the file is remote) fetches the entire file, at least until you make a change like in #4166

The suggested change in #4166 could be improved to also make `QuickInfo LasReader::inspect()` return without fetching the entire file, if this is the desired behaviour.

**Comment by wonder-sk** [comment]
Also try `pdal info --metadata` ... it returns more details than quickinfo and does not read points.

**Comment by olsen232** [comment]
Yes that provides useful info and seems to have the same effect as setting count to zero - so again, this fetches the entire file if it is remote. Happily it doesn't if you make a change as in #4166 that only does range requests if no points are requested.

I've updated the bug description to include the fact that `pdal info --metadata` also fetches the entire file.

**Comment by hobu** [comment]
`pdal info --metadata https://server.com/myfile.la[s|z]` is not an easy thing to do. We made an entirely specific and streambable [LAS compatible format](https://copc.io) to do that 😏 

* The header size changes depending on the PDRF version
* For LAS 1.4+, it could have SRS info in an eVLR
* Is it LAZ? You don't know until you inspect a VLR that might be anywhere in the file.
* Does it have an extra bytes VLR? Extended point count?

It ends up being quite a flow chart. We have written our own "point cloud indexer" software that does this kind of thing to try to overcome these issues, but it didn't seem appropriate to put the complexity of range chatting with an endpoint inside `readers.las`.

**Comment by olsen232** [comment]
Have a look at #4166 - it is not a large change, and I believe it can handle all of those possibilities.
I agree it is good that COPC exists, but the fact that it does doesn't help me if I'm trying to index someone's non-COPC tiles - which is why you wrote your point cloud indexer software and why I'm trying to improve readers.las in this way

**Comment by hobu** [comment]
> which is why you wrote your point cloud indexer software

You're asking to put additional complexity that we get to maintain going forward into `readers.las` (not all the other drivers) to satisfy your needs. We wrote our own indexer outside of PDAL specifically so we didn't make those parts of PDAL complex (and so we could do fancier things without consequence).

> Have a look at #4166

I did, stuff like https://github.com/PDAL/PDAL/pull/4166/files#diff-826ea9b8b8b7e825e57482a92378a54c513a229ae320d2bd1283d14717dde895R293 is going to be straight busted for some files.

**Comment by olsen232** [comment]
Ah that's just an vague guess at how many bytes at the start of a file might be useful ie header plus VLRs. It makes another range request and gets some more bytes if the header + VLRs is more than that.

I'm not hearing a lot of encouragement, seems like this is "not something you're interested in", feel free to close if that's the case.

**Comment by connormanning** [comment]
I think there is precedent that this does *not* belong in PDAL - in Entwine for example I implemented [this functionality](https://github.com/connormanning/entwine/blob/master/entwine/util/io.cpp#L194-L283) downstream of PDAL after some discussion with @abellgithub about where it belonged.  It looks a little complex in C++ but it's pretty simple, 3 range requests and a bit of buffer twiddling:
- Fetch the header (375 bytes is the max header size for LAS)
- Get the VLR/EVLR offset/length, fetch them both
- Smash header/VLRs/EVLRs together, set the header point count to 0 and set the EVLR offset to be the end of the VLRs

Now you have the LAS file, but without any points, so you can run whatever `pdal info` variant you'd like against that as if it were a normal file.

**Comment by abellgithub** [comment]
The only general-purpose remote support that exists in PDAL that I'm aware of is to fetch a complete file.

**Comment by hobu** [comment]
> feels like since PDAL has committed to supporting remote files and is 95% of the way there,

The distinction has been whether or not the format is designed for remote files, ie COPC or EPT or I3S, not generically supporting "remoteness" for *any* file type. As @connormanning's too in Entwine shows, it's not alwaysa simple thing of fetching the first XXXX bytes of a file and making a decision.

Another complication with this particular implementation is `readers.nitf` uses the same code paths, but you can't conveniently figure out where to start range-reading bytes.

> The suggested change in https://github.com/PDAL/PDAL/pull/4166 could be improved to also make QuickInfo LasReader::inspect() return without fetching the entire file, if this is the desired behaviour.

I'm supportive of this approach, where you bury it all in the method, instead of spreading it into LasStreamIF with who-knows-what consequences. I think what you want here is quick scanning of VLRs and headers for LAS, not remote reading of arbitrary points from a LAS file. Doing it this way will get you that without adding lots of complication everywhere else.

**Comment by olsen232** [comment]
If I understand correctly, you're supportive of an approach where `QuickInfo LasReader::inspect()` uses a range-request based codepath, with the general case using the code as it exists today but with a minimum of changes.

Something to note - to meet this goal, there will still have to be some slight change on the main codepath, since right now the main codepath (ie `LasReader::initialize` etc) is the only code that knows how to parse a LAS file, and always causes the file to be fetched.

I'll rewrite my PR to get the new range request logic more isolated from the main code-path, to have the main code-path changed minimally from how it is now. I'll make the range-request codepath happen when `QuickInfo LasReader::inspect()`. Once you've had a look at that, you can decide a) if it's mergeable once comments are addressed and b) if the range-request codepath could also be used for other zero-points-required operations like the ones described in https://github.com/PDAL/PDAL/issues/4165#issue-1891372200

**Comment by olsen232** [comment]
> I'm supportive of this approach, where you bury it all in the method, instead of spreading it into LasStreamIF.

See #4166 again - I've done my best to reimplement it in line with this directive .

- LasStreamIf's actual implementation is now completely unchanged from what it is at master
  - However, it is now one of two implementations of a common interface, LasStream, the other being LasStreamRange
  - And the LasStream has a method `prepareRangeForReading(offset, size)`. LasStreamIf simply ignores this call since the entire file is already ready to read.
- `LasReader::initializeLocal` has minimal changes from the version at master.
  - the only thing that is changed is that three calls to prepareRangeForReading are made. Since this is a no-op when LasStreamIf is used, you can be confident that the code works as previously if this implementation is used.
  
Further comments can be found and of course made on the PR itself.

> Perhaps a kernel could be written to perform this information if PDAL needs to be involved...
Is this an approach you would be supportive of? If I understand correctly, this would work out not too dissimilar from the approach I am trying to take. That is, it would still involve updates to LasReader of the sort I am currently trying to make (although perhaps they could be cleaner or smaller than currently, if you can direct me how). LasReader as it is currently written does not support reading metadata from anything less than an entire file, so in order to write a `pdal remoteinfo` kernel that can do this, I would either have to modify LasReader - as I am trying to do - or write a new piece of code similar to `LasReader::initializeLocal` that can parse LAS headers from ranges. Probably you don't want me to try and contribute another piece of code to maintain that parses LAS headers.

> though as @connormanning showed, this doesn't seem necessary. 
This is true - this feature, like all features, could be implemented inside PDAL and could also be implemented by third parties outside PDAL. In fact we already have some python code that stitches smaller LAS files out of range requests of larger LAS files, that I see now is equivalent to Connor's C++ code... but, as an organisation, we try to contribute to open source projects if the functionality we are adding could also be useful to others. Of course, the final decision rests with you.

**Comment by abellgithub** [comment]
What about essentially just dropping @connormanning's code in a kernel?

**Comment by olsen232** [comment]
I can do this if this is the preferred approach. @hobu I did try to follow your instructions to write the latest version of #4166 - let me know if it currently looks like a good approach, or if perhaps you too would prefer to take Connor's code and make it into a kernel

**Comment by hobu** [comment]
> [implement as a kernel] I can do this if this is the preferred approach.

I think the kernel approach would have less risk of secondary effects, especially as PDAL continues to evolve. It could also be made as fancy as people want without impacting anything else. What would you call it? `scan`?

**Comment by olsen232** [comment]
Okay I've had another attempt - see #4178 

Here is what has changed in line with (some of) your suggestions.
- There are now no changes to LasReader at all. Only InfoKernel.cpp is affected, and that only if you do `pdal info FILENAME --summary --driver=readers.las`
  - it might be preferable if it worked for all filenames ending in .las / .laz if the driver is unspecified, haven't looked into that yet
- since it doesn't modify LasReader, it now instead uses Connor's code that stitches together a valid small LAS file which has the same metadata as the original LAS file.

However, I did not write a new separate kernel called `remoteinfo` or `scan`. I began in this endeavour but I wasn't happy as I saw that I was greatly enlarging PDAL's public interface for only a small piece of extra functionality. If I had completed this task (as I envisioned it, you may have had other plans) PDAL would have had the following options for extracting metadata remotely:
- `pdal info REMOTE-FILE` (extracts various metadata from remote file including stats)
- `pdal info --metadata REMOTE-FILE` (extracts metadata from remote file, but no info that needs individual points) 
- `pdal info --summary REMOTE-FILE` (extracts metadata from remote file, but nothing that needs individual points. Formats output slightly differently, and doesn't initialise the point decompressor stream)
- `pdal remoteinfo REMOTE-FILE` (not yet written. extracts metadata from remote file, but nothing that needs individual points, also doesn't even fetch the individual points, probably only works for LAS files).

I couldn't really imagine writing documentation for a new `remoteinfo` kernel in such a way that made it seem like a necessary addition to the PDAL family. It would always give the same output as one of the existing commands but faster, or not work at all - so, it would be a research problem for the end-user to decide which of the redundant kernels works fastest / works at all in a given situation, rather than PDAL deciding how to effectively do what the user is asking.

Anyway, that's how I ended up adding this functionality into `pdal info --summary` - let me know if it looks promising. If not, well, we can always close this and move on... as you say this doesn't necessarily have to be inside PDAL.

**Comment by olsen232** [comment]
Thanks Howard and team! Glad we could find something mergeable in the end

**Comment by hobu** [comment]
You will be the very first person pinged when users ask about this topic again 😄
