### ISSUE TITLE
Add alternative dimension name for normals with space

### ISSUE THREAD

**Issue by agisoft-metashape** [PDAL/PDAL#4173]
Agisoft Metashape exports LAS files using lowercase names with space for point normals ExtraBytes: `"normal x", "normal y", "normal z"`. This naming convention was chosen to match the one used in the official LAS wiki with [Standard ExtraByte Definitions](https://github.com/ASPRSorg/LAS/wiki/Standard-ExtraByte-Definitions) list, see discussion at https://github.com/ASPRSorg/LAS/issues/37#issuecomment-1708133319

**Note:** PDAL 2.4 and earlier correctly recognized point normals in Metashape LAS exports as `Dimension::fixName()` called in `LasReader::addDimensions()` replaced spaces with underscores in ExtraByte names normalizing `"normal x"` to `"normal_x"` and so on, and `"normal_x"` is listed alternative name for `"NormalX"` dimension. This was changed in PDAL 2.5 which allowed spaces in dimension names and removed them from normalization procedure: https://github.com/PDAL/PDAL/pull/3907

It will be very useful if the current list of alternative names for point normals
`"nx", "normal_x", "normalx"`
could be extended to
`"nx", "normal_x", "normalx", "normal x"`
to compensate for this change. This needs to be done for each X, Y and Z component.

While the problem with space in point normals ExtraBytes names is specific to Metashape software, there seems to be a similar issue for one of the standardized ExtraBytes, namely `HeightAboveGround`. PDAL doesn't list any alternative names for this dimension, but the [Standard ExtraByte Definitions](https://github.com/ASPRSorg/LAS/wiki/Standard-ExtraByte-Definitions) list in the official LAS wiki requires `"height above ground"` name for this property. Maybe it needs to be listed as alternative name in PDAL as well.

_Originally posted by @jo-chemla in https://github.com/PDAL/PDAL/issues/4144#issuecomment-1695337862_

**Comment by hobu** [comment]
Added in #4188
