### ISSUE TITLE
translate slpk to las issue

### ISSUE THREAD

**Issue by lordsalomon** [PDAL/PDAL#4182]
**bug Description**
Using pdal translate, I try to convert a cloud points slpk esri file to las format. The esri file can be downloaded here : https://github.com/Esri/arcgis-python-api/blob/master/samples/05_content_publishers/data/World_earthquakes_2000_2010.slpk
Below is the command used in windows (with anaconda installation of Pdal) :
```
$ pdal translate D:/World_earthquakes_2000_2010.slpk output.las
```
Below is the warning I get : 
(pdal translate readers.slpk Warning) Number of nodes per page not specified. Default is 64.

Do you know any fix for this ? Thanks

**Comment by hobu** [comment]
I don't think this is a point cloud SLPK. PDAL only translates point cloud SLPK. Also, it is a quite old version of the file, which is why the reader might be complaining with the warning about the node counts.
