### ISSUE TITLE
Options toMetadata method changes list to a joined string

### ISSUE THREAD

**Issue by kylemann16** [PDAL/PDAL#4185]
In [Options.hpp](https://github.com/PDAL/PDAL/blob/master/pdal/Options.hpp#L151-L170), PDAL is translating valid JSON lists into strings joined by a comma. This invalidates some key value pairs, in my case `filters.assign` where I am trying to apply multiple assignments at once, which is supported according to the docs. 

This
```
[
    "Classification = 0",
    "ReturnNumber = 1 WHERE ReturnNumber < 1",
    "NumberOfReturns = 1 WHERE NumberOfReturns < 1",
]
```

Is transformed into
```
"Classification = 0, ReturnNumber = 1 WHERE ReturnNumber < 1, NumberOfReturns = 1 WHERE NumberOfReturns < 1"
```

Minimal example: https://gist.github.com/kylemann16/31dd11192cf3c341272b268b6eacfb0a

The PDAL python library follows this path:

1. https://github.com/PDAL/python/blob/main/pdal/PyPipeline.cpp#L112-L117
2. https://github.com/PDAL/PDAL/blob/master/pdal/PipelineWriter.cpp#L98
3. https://github.com/PDAL/PDAL/blob/master/pdal/Stage.cpp#L100
4. https://github.com/PDAL/PDAL/blob/master/pdal/Options.hpp#L151

where it joins an iterable into a string.

**Comment by hobu** [comment]
Fixed in #4190
