### ISSUE TITLE
Error when creating more than ~500 tiles with PDAL tile "writers.las: Couldn't open file 'xxx' for output"

### ISSUE THREAD

**Issue by SuperMakai** [PDAL/PDAL#4194]
**Describe the bug**
I'm running the pdal tile command to split large LAS / LAZ files into 10x10m tiles on Windows 10. The command executes fine if no more than ~500 tiles are created in the process, which means if the length parameter is large enough. However, if the length parameter is set to a smaller value up to a point where more than ~500 tiles are created, the execution fails with this error:

`PDAL: writers.las: Couldn't open file 'c:/temp/tiles/tile_35_31.las' for output.`

I suspect this has something to do with the maximum number of files that may be open simultaneously at the stream I/O level, which seems to be limited to 512 by default in the runtime (more details here: https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/setmaxstdio?view=msvc-170).

```
$ pdal tile "c:\temp\test.laz" "c:\temp\tiles\tile_#.las" --origin_x=485200 --origin_y=6942502 --length=2 --readers.las.default_srs="EPSG:7856" --readers.las.nosrs=true --writers.las.forward="all"
```

**Expected behavior**
pdal tile should complete successfully on Windows if more than 500 tiles are created. If the issue is related to _setmaxstdio, the value should be increased to the maximum supported by the underlying platform. 

**System/installation information:**

```
Windows 10.0.19045.3448
```

```
pdal 2.5.6 (git-version: Release)
```

**Comment by hobu** [comment]
> I suspect this has something to do with the maximum number of files that may be open simultaneously at the stream I/O level, which seems to be limited to 512 by default in the runtime (more details here: https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/setmaxstdio?view=msvc-170).

Yep, definitely this. Use [PDAL Wrench](https://github.com/PDAL/wrench/) to overcome the windows limit issue, but you'll need to build it yourself on windows for now.

**Comment by abellgithub** [comment]
Dup of #3344

**Comment by abellgithub** [comment]
Dup of #3344
