### ISSUE TITLE
Question/Feature request: Make filters.randomize streamable

### ISSUE THREAD

**Issue by jo-chemla** [PDAL/PDAL#4195]
Hi PDAL community, 
I'm wondering what prevents the [filters.randomize](https://pdal.io/en/latest/stages/filters.randomize.html) from being `streamable`. Using this in combination with other pdal pipeline filters (head, stats, head, crop, splitter, merge, stats, etc) would allow for out-of-core operations that would process pointclouds with requirements higher than RAM capacity. 

Having thatrandomize filter produce a random list of indices, and processing points in subsequent pipeline stages entry by entry (or in batches of specified size), looks like this stage could support streaming. 
Best, Jonathan

**Comment by abellgithub** [comment]
I don't understand how this would work. You could theoretically reorder points that are in a loaded chunk (but this operation is not currently supported), but this seems of little use. You will have to provide some more detail on an implementation.

**Comment by jo-chemla** [comment]
Hi Andrew, 
It is true that even once the random indices have been computed, the entirety of the pointcloud file has to be crawled to retrieve each point (+ coords and attributes) to feed for other pipeline stages. This question should therefore more be rephrased something like: 

Can we execute `filters.randomize`, so that it process batches of points of the input pointcloud, without ever overflowing RAM? 

If so, one could then just chain two pipelines, one to use filter.randomize and produce a resulting intermediate pointcloud that could then be parsed as an input for a streamable pipeline. Thanks for the feedback!

**Comment by abellgithub** [comment]
This just isn't how PDAL works. We never perform random access on points in a pipeline. Access is always sequential. Random access with some file types (notably compressed files), just doesn't work well. I don't know what else to suggest.

**Comment by jo-chemla** [comment]
Closing this. The way to handle points transformation/pipeline by batches of primitives - eg for pointclouds that exceed RAM - can probably be done via pdal python scripts.

**Comment by jo-chemla** [comment]
Stumbling back on this thread, and giving this a second thought, I probably have formulated the problem the wrong way. The original idea was applying randomization before decimation via a pipeline such as below to make decimation more tolerant to how data is organized within the file. 

```json

[
    "input.las",
    {
        "type":"filters.randomize"
    },
    {
        "type":"filters.decimation",
        "step": 10,
        "offset": 0
    },
    "pointcloud_random_sampling.las"
]

```

`filters.decimation`/downsampling is already streamable. Would it be interesting to extend it to not sample exactly 1 out of N of the input, but also allow for that randomization, whilst staying streamable? Otherwise, this might be achieved via [filters.streamcallback](https://pdal.io/en/latest/stages/filters.streamcallback.html), passing it an sorted array of N IDs to select from the input pointcloud, and then process points in a streamable way but I could not find examples of this filter stage. 

I just came out with this more documented [filters.python](https://pdal.io/en/latest/stages/filters.python.html) similar to this one that should be streamable and meet the described requirements. Also great [thinning doc](https://pdal.io/en/latest/workshop/manipulation/thinning/thinning.html) for smaller pointclouds or when you have enough compute and time!

```py

import numpy as np

# K = thinning factor, e.g. keep ~1/K points
K = 10  

def filter(ins, outs):
    # Generate randoms in [0,1) sampling continuous uniform distribution 
    r = np.random.random(size=len(ins['X']))
    keep = r <= (1.0 / K)
    outs['Mask'] = keep
    return True

```

```json

[
    {
        "type": "readers.las",
        "filename": "autzen-classified.copc.laz"
    },
    {
        "type": "filters.python",
        "script": "pdal-random-thin.py",
        "function": "filter",
        "module": "pdal-random-thin"
    },
    {
        "type": "writers.las",
        "filename": "output.laz"
    }
]

```

EDIT: The resulting pipeline is not streamable when added the filters.python, I assumed it could be because of wording of [filters.python](https://pdal.io/en/latest/stages/filters.python.html), that would process points by chunks. There might be a way to do this streamable way via `filters.streamcallback`. 

```bash

pdal pipeline pdal-pipeline-random-thin.json --validate
{
    "error_detail": "",
    "streamable": false,
    "valid": true
}
```
