### ISSUE TITLE
photomesh 3d slpk to las point cloud

### ISSUE THREAD

**Issue by lordsalomon** [PDAL/PDAL#4215]
I want to convert a large 50 GB slpk file to las format using 
```
$ pdal translate input.slpk output.las
```
But I get some issues saying that :
```
(pdal translate readers.slpk Warning) Number of nodes per page not specified. Default is 64.
PDAL: readers.slpk: Attributes do not exist for this object
```

I am using Pdal, through a conda installation on windows. Thanks

**Comment by abellgithub** [comment]
Your file seems to be missing the
[attributeStorageInfo node](https://docs.ogc.org/cs/17-014r7/17-014r7.html#_attributestorageinfo). You should examine the JSON describing your SLPK file.

**Comment by hobu** [comment]
Did something change in SLPK that causes the attributes to no longer be there? Or maybe we are expecting there to be attributes when they are not required. 

The i3s code is not heavily used and some of these kinds of issues haven't been sorted. If you want to provide a patch that fixes this issue we would be happy to merge it. Alternatively, we are available [for hire](https://hobu.co/access.html) to investigate and deal with these kinds of issues if you want to go that route.

**Comment by abellgithub** [comment]
My guess from a quick look at the code is that it isn't required, but I wasn't sure and the spec is a bit unclear on this. If would be trivial to remove the check if someone wants to try it.
