### ISSUE TITLE
Python API Docs Link

### ISSUE THREAD

**Issue by jlaura** [PDAL/PDAL#4227]
This is born from the terrific idea in #4226. Are there python API level docs, similar to what one finds on RTD? I am seeing examples using python on [pdal.io](https://pdal.io/en/2.6.0/python.html). They are mostly write a JSON pipeline and run it via the pipeline syntax. Likewise, the docs on the [pypi](https://pypi.org/project/pdal/) package are largely similar. The [CoLab notebook](https://colab.research.google.com/drive/1JQpcVFFJYMrJCfodqP4Nc_B0_w6p5WOV#scrollTo=qiKI1JD9VqIr) linked through #4226 demonstrates more pythonic usage via the API. Additionally, I've see the `help()` style syntax available via the interpreter.   

All of these are great. 

In addition, are there python docs that describe the function signatures for exposed items? Should one be checking the C++ API (like one has to do frequently for GDAL)?

For example, from CoLab:

```python
reader = pdal.Reader.ept(url, 
                         resolution=resolution, 
                         polygon = extent['poly_wm'].wkt)
```
How does one know that that is the function signature? What other kwargs are passable?    

If these don't exist, I would consider this a feature request. If they do, I can put in a PR linking them into the documentation (and this can close as a question ill-posed as an enhancement request).

**Comment by hobu** [comment]
> How does one know that that is the function signature? What other kwargs are passable?

You can find out the options for a reader using the command line. These are what are reflected by the Python bindings into Reader/Filter/Writer classes and their args/kwargs:

```
pdal --options readers.ept
```

```
pdal --options readers.ept --showjson
["readers.ept",[{"description":"User JSON","name":"user_data"},{"description":"Debug output filename","name":"log"},{"description":"File from which to read additional options","name":"option_file"},{"description":"Name of file to read","name":"filename"},{"default":"18446744073709551615","description":"Maximum number of points read","name":"count"},{"description":"Spatial reference to apply to data","name":"override_srs"},{"description":"Spatial reference to apply to data if one cannot be inferred","name":"default_srs"},{"description":"Bounds to fetch","name":"bounds"},{"description":"Origin of source file to fetch","name":"origin"},{"default":"15","description":"Number of worker threads","name":"requests"},{"description":"Resolution limit","name":"resolution"},{"description":"Mapping of addon dimensions to their output directory","name":"addons"},{"description":"Bounding polygon(s) to crop requests","name":"polygon"},{"description":"Header fields to forward with HTTP requests","name":"header"},{"description":"Query parameters to forward with HTTP requests","name":"query"},{"description":"OGR filter geometries","name":"ogr"}]]
```
