### ISSUE TITLE
Error when specifying spatial reference in "bounds" option

### ISSUE THREAD

**Issue by freddyAtPacify** [PDAL/PDAL#4228]
**Describe the bug**
Using "bounds" option with COPC and EPT readers with a spatial reference causes the pipeline to fail.

```
$ pdal pipeline --input myPipeline.json
```

Here is the relevant part of my pipeline:
```
"bounds": "([-71.135695, -71.135491], [42.427430, 42.427709])/EPSG:4326"
```
I tried both with and without the 'EPSG'

**Expected behavior**
The documentation says that "The bounds can be followed by a slash (‘/’) and a spatial reference specification to apply to the bounds."

However, the pipeline terminates with this error:
```
"PDAL: Invalid character following valid bounds box."
```

**System/installation information:**
I'm using PDAL 2.5.6.

**Comment by abellgithub** [comment]
This is caused by a bug introduced in 0a83da03c725203ac1d27c09ba34f738211e55c9
