### ISSUE TITLE
Scalar fields destroyed by voxel centroid nearest-neighbour filter

### ISSUE THREAD

**Issue by SlapDrone** [PDAL/PDAL#4229]
**Describe the bug**
Scalar fields are destroyed even when using a voxel centroid nearest-neighbour filter to subsample.

```
$ pdal pipeline subsample.json
```

<details>
  
```
I'm running the following PDAL pipeline on a point cloud with a scalar field denoting its classification:

[
    {
        "type": "readers.las",
        "filename": "input.las"
    },
    {
        "type": "filters.voxelcenternearestneighbor",
        "cell": 0.05
    },
    {
        "type": "writers.las",
        "filename": "output.las"
    }
]

I get a nicely subsampled cloud, but it's missing the scalar field(s).

```

</details>

**Expected behavior**
I would expect that the subsampled cloud would retain their scalar field values, since the points are a subset of the original cloud.

**System/installation information:**
Please provide information on your PDAL version (`pdal --version`) and system (e.g., `uname -a` or `ver`).

```
$ uname -a
Linux bc03769b4265 6.5.8-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 19 Oct 2023 22:52:14 +0000 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ pdal --version
--------------------------------------------------------------------------------
pdal 2.6.0 (git-version: 597ab2)
--------------------------------------------------------------------------------
```

**Comment by chambbj** [comment]
Please provide your pipeline and data if you'd like someone to try to recreate.

**Comment by SlapDrone** [comment]
My bad, I eventually figured it out - I had to understand the details of how to use and match extra_dims on the reader and writer stages, i wrongly attributed these being misconfigured on my end to using the filter. Thanks for getting back to me. Closing the issue.
