### ISSUE TITLE
Convert e57 to laz cause error when using PDAL binaries on Alpine

### ISSUE THREAD

**Issue by Phong95** [PDAL/PDAL#4231]
Im going to build a Docker Image allows to convert e57 to laz file.
Im using Alpine Base, and download PDAL binaries follows instructions `apk add pdal`

When i execute command line `pdal translate -i test.e57 -o test.laz` , it return message:
`PDAL: Couldn't create reader stage of type 'readers.e57'.
You probably have a version of PDAL that didn't come with a plugin
you're trying to load.  Please see the FAQ at https://pdal.io/faq`

Then i try to install `apk add pdal libpdal-plugins` but it cause error: 
`ERROR: failed to solve: process "/bin/sh -c apk add pdal libpdal-plugins" did not complete successfully: exit code: 1`

Did i do something wrong or i should switch to conda?
Appreciate any comments.

**Comment by hobu** [comment]
`readers.e57` requires libxml2, and the Alpine container does not have that installed. Use the conda builds if you need E57 support.
