### ISSUE TITLE
How to read and write in streaming mode

### ISSUE THREAD

**Issue by oleg-alexandrov** [PDAL/PDAL#4234]
**Describe the bug**

The documentation could use an example of how to read and write from a las file in streaming mode. I've spent quite a lot of time reading the existing doc, looking at the tutorial, architecture overview, and unit tests, and I could not find one block of code that could be put to good use (there are some pieces here and there that maybe could be integrated somehow).

I think this is relevant since point cloud files are usually too large to store in memory, so streaming is likely the more usual approach.

**Comment by abellgithub** [comment]
I don't the understand. What, exactly, do you want to know how to do? Are you using the API? If so, what is unclear to you?

**Comment by oleg-alexandrov** [comment]
I want to read and write from a las file in streaming mode. There is no example of using the streaming API.

I've spent half a day reading through the code, and will do more today, and I am getting to the point I will cook up something. 

I hope you understand now. It is really a matter you using a new software and wishing those folks spelled out things some more for you.

**Comment by hobu** [comment]
> There is no example of using the streaming API.

Plenty of those in the test suite https://github.com/PDAL/PDAL/blob/master/test/unit/StreamingTest.cpp#L275

**Comment by oleg-alexandrov** [comment]
Thank you. I read this yesterday. The documentation says that the StreamPointTable class must be used. This example does not use that class. This example uses instead the Streamable class, which is not mentioned in the doc.  

So all the pieces are there, somehow, and by trial and error I've been making some progress.

**Comment by hobu** [comment]
Another place for good examples is the kernels. TranslateKernel makes heavy use of streaming https://github.com/PDAL/PDAL/blob/master/kernels/TranslateKernel.cpp

**Comment by oleg-alexandrov** [comment]
BTW, the doc mentions once StreamingPointTable, but the actual class is called StreamPointTable. 

I also worked with TranslateKernel yesterday and went 5 levels deep through the pipeline architecture before I thought there must be an easier way to figure this all out.

So you closed the issue, and that is fine, but the fact remains that there is no example of using the streaming code and the internals are inconsistent.

**Comment by hobu** [comment]
> So you closed the issue, and that is fine, but the fact remains that there is no example of using the streaming code and the internals are inconsistent.

Please use the mailing list for discussion and questions.

> I also worked with TranslateKernel yesterday and went 5 levels deep through the pipeline architecture before I thought there must be an easier way to figure this all out.

The Python bindings support streaming too. https://github.com/PDAL/python/blob/main/pdal/StreamableExecutor.cpp If you keep with it, please open a PR with a documentation update or tutorial that implements what you are asking for. Indeed it isn't conveniently availble.

**Comment by abellgithub** [comment]
The [architecture overview](https://pdal.io/en/2.6.0/development/overview.html) does discuss streaming. Perhaps the heading should be something like ” development with the API" rather than just "development”.
