### ISSUE TITLE
Feature request: Adding more options to filters.litree

### ISSUE THREAD

**Issue by korotuharry** [PDAL/PDAL#4237]
It would be really nice to be able to specify additional parameters for filters.litree. The paper the filter is based on has a couple which I was surprised to see weren't added in the PDAL implementation. The search radius R is the one that would be most useful to me because in the project I am working on, I want to process each point as if it were a local maximum by setting R to 0. It would be great if the search step for local maxima is skipped in this case like as implemented in [lidR](https://rdrr.io/cran/lidR/man/its_li2012.html)!

**Comment by hobu** [comment]
> The paper the filter is based on has a couple which I was surprised to see weren't added in the PDAL implementation.

Please provide a patch to implement such features as you see fit. The initial implementation was a prototype, and given that PDAL is a community resource, if the community needs these additional options, it should step forward to implement them.
