### ISSUE TITLE
New install of PDAL with new install of Conda (Win10) 'cannot find libdeflate.dll'

### ISSUE THREAD

**Issue by DelS-AGL** [PDAL/PDAL#4248]
I followed the process for installing Conda and PDAL with apparent success.
I tried 'pdal info' on a compressed file which aborted reporting 'libdeflate.dll was not found'
I did 'conda install libdeflate' and it reported the package was already installed.
Rebooted and tried again. Same result.

Any suggestions?

**Comment by hobu** [comment]
Maybe this is a Windows 10 thing or some SDK is missing? Or you haven't activated your account or shell correctly? No matter what, it seems more like a conda issue than a PDAL one.

**Comment by DelS-AGL** [comment]
You're right.  All good now.
Apologies.

**Comment by bkgelder** [comment]
> You're right. All good now. Apologies.

@DelS-AGL - What did you do to resolve this issue? I've got a student with the same problem with a PDAL 2.7 install in a fresh conda environment. I'm using older versions without issue.

**Comment by DelS-AGL** [comment]
> > You're right. All good now. Apologies.
> 
> @DelS-AGL - What did you do to resolve this issue? I've got a student with the same problem with a PDAL 2.7 install in a fresh conda environment. I'm using older versions without issue.

Sorry - I don't recall. I may have just repeated the Conda install.
