### ISSUE TITLE
include/pdal has too restrictive permission

### ISSUE THREAD

**Issue by bbhtt** [PDAL/PDAL#4258]
**Describe the bug**

PDAL when built and install creates the `include/pdal` directory with no permission for the owner to write or modify:

```
ls -lA pdal-2.6.0-1-x86_64.pkg/usr/include/     
total 0
dr-xr-xr-x. 1 bbhtt bbhtt 1578 Nov  9 19:28 pdal

ls -lA pdal-2.5.6-1-x86_64.pkg/usr/include 
total 0
drwxr-xr-x. 1 bbhtt bbhtt 1578 Aug 19 07:07 pdal
```

This is problematic because 

a) that is not the usual permission for headers in `/usr/inlcude`
b) Applications using pdal as a dependency often might cleanup that directory in build pipeline because it is only useful for build purposes and not in a final package. eg. in a flatpak environment.

The CI fails to delete the directory because it is run non-root. https://buildbot.flathub.org/#/builders/33/builds/10351/steps/1/logs/stdio and makes other unrelated build fails.

**Expected behavior**

This issue was not present in pdal 2.5.6. The directory should be `drwxr-xr-x` not `dr-xr-xr-x`

You can check the packages built by distributions, all of them have wrong permissions. 

https://kojipkgs.fedoraproject.org//packages/PDAL/2.6.0/5.fc40/x86_64/PDAL-devel-2.6.0-5.fc40.x86_64.rpm
https://archlinux.org/packages/extra/x86_64/pdal/download/

Compare it with 2.5.6: https://kojipkgs.fedoraproject.org//packages/PDAL/2.5.6/1.fc39/x86_64/PDAL-devel-2.5.6-1.fc39.x86_64.rpm

**System/installation information:**

Fedora 39

```
Linux fedora 6.5.12-300.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Nov 20 22:44:24 UTC 2023 x86_64 GNU/Linux
```

```
2.6.0
```

If installed via Conda, you may be asked to paste the output of `conda list` and `conda info` as well.

N/A

**Comment by hobu** [comment]
Please try https://github.com/PDAL/PDAL/pull/4259 and see if it resolves this issue and we will include it in the next 2.6.2 release

**Comment by bbhtt** [comment]
> Please try #4259 and see if it resolves this issue and we will include it in the next 2.6.2 release

Hey, I can try soonish. Unfortunately I hit https://github.com/PDAL/PDAL/issues/4256 while building on Fedora 39. I need to figure out to workaround that,

**Comment by hobu** [comment]
`-DWITH_BACKTRACE=OFF` should get you building

**Comment by bbhtt** [comment]
> WITH_BACKTRACE

I think it worked because inside the distrobox container libunwind/libexecinfo was missing so it turned off WITH_BACKTRACE, but I had libunwind in my host.
