### ISSUE TITLE
Documentation: Deprecated option "last" in ground filter tutorial

### ISSUE THREAD

**Issue by han16nah** [PDAL/PDAL#4270]
**The bug**

In the [Ground Filter Tutorial](https://pdal.io/en/2.6.1/tutorial/ground-filters.html), the [SMRF filter](https://pdal.io/en/2.6.1/stages/filters.smrf.html#filters-smrf) `filters.smrf` is used with the option "last", which seems to be deprecated. Recreating the [pipeline](https://pdal.io/en/2.6.1/tutorial/ground-filters.html#ground-segmentation) therefore raises an error: 
> PDAL: filters.smrf: Unexpected argument 'last'.

Instead of `"last":true`, one would use `"returns":"last"`. 

**System/installation information:**

```
$ pdal --version
```
> pdal 2.6.0

**Comment by hobu** [comment]
Fixed in #4329
