### ISSUE TITLE
Cannot convert .LAZ data set from NZVD2016 vertical datum to DUN58 local vertical datum. 

### ISSUE THREAD

**Issue by colhu258** [PDAL/PDAL#4275]
I will preface this with the fact I am relatively new to PDAL and Python in general. I am running a PDAL pipeline which is suppose to convert a pointclud in LAZ format from NZVD2016 to DUN58. I originally used example 2 found on the PDAL help page for "filters:reprojection" but have found that the "+init=epsg" syntax is deprecated in the current version of PROJ4. As such I found another query here on GIThub which supposedly solved the issue, linked here "https://github.com/PDAL/PDAL/issues/3231" and attempted to use Hobu's solution to no avail. 

this is .json file

{
    "pipeline": 
        [
            {
                 "type": "readers.las",
                 "filename": "Wingatui_NZVD2016_Filtered.laz"
            },
            {
                 "type": "filters.reprojection",
                 "in_srs": "EPSG:2193",
                 "out_srs": "EPSG:2193+5761"
            },
            {
                 "type": "writers.las",
                 "filename": "Wingatui_DUN58_Filtered.laz"
            }
        ]
}

and I am running it with the command 
pdal pipeline test.json in the anaconda powershell prompt. Any help will be greatly appreciated

**Comment by hobu** [comment]
set `PROJ_DEBUG=3` in your environment and run your pipeline with `PROJ_DEBUG=3 pdal pipeline test.json --debug --verbose 7` to see PROJ debug output

Try asking this question on the mailing list as GitHub is for bugs and such. https://pdal.io/en/latest/community.html#mailing-list
