### ISSUE TITLE
installation using conda fails

### ISSUE THREAD

**Issue by cusicand** [PDAL/PDAL#4333]
Hello,

I tried to install pdal and python-pdal using conda without succes. Below the outputs:

`mamba env create -f pdal_env.yml`

`pdal_env.yml` content:

name: pdal_py310
channels:
  - conda-forge
dependencies:
  - python==3.10
  - pdal==2.5.6
  - python-pdal
  - gdal
  - untwine
  - geopandas
  - python-wget
  - pathlib2

(PDAL Error) Can't load library /home/cusicand/miniconda3/envs/pdal_py310/lib/libpdal_plugin_reader_draco.so: Failed to load "/home/cusicand/miniconda3/envs/pdal_py310/lib/libpdal_plugin_reader_draco.so": libdraco.so.8: cannot open shared object file: No such file or directory(PDAL Error) Can't load library /home/cusicand/miniconda3/envs/pdal_py310/lib/libpdal_plugin_writer_draco.so: Failed to load "/home/cusicand/miniconda3/envs/pdal_py310/lib/libpdal_plugin_writer_draco.so": libdraco.so.8: cannot open shared object file: No such file or directory(PDAL Error) Can't load library /home/cusicand/miniconda3/envs/pdal_py310/lib/libpdal_plugin_reader_draco.so: Failed to load "/home/cusicand/miniconda3/envs/pdal_py310/lib/libpdal_plugin_reader_draco.so": libdraco.so.8: cannot open shared object file: No such file or directory(PDAL Error) Can't load library /home/cusicand/miniconda3/envs/pdal_py310/lib/libpdal_plugin_writer_draco.so: Failed to load "/home/cusicand/miniconda3/envs/pdal_py310/lib/libpdal_plugin_writer_draco.so": libdraco.so.8: cannot open shared object file: No such file or directory

When I run pdal only as comand-line, it work well. The problem is when I tried to import from python. The libraries `libpdal_plugin_reader_draco.so` exist on my computer. However, `libdraco.so.8` dosen't exist.

Thanks ins advance for your help.

**Comment by hobu** [comment]
set your `draco=1.5.6` and you should be good. There's a bad pin that hasn't been fixed.

**Comment by cusicand** [comment]
Thank you @hobu. The problem has been fixed.
