### ISSUE TITLE
PLY writers forgot faces

### ISSUE THREAD

**Issue by NanBlanc** [PDAL/PDAL#4339]
**Describe the bug**
`pdal translate --writers.ply.faces="true"` argument does not work, regardless of the inputed or outputed storage mode. Faces are not kept in the translation process `.ply` file.

**Reproduce the bug**
1. Get the file : [simple_faces.txt](https://github.com/PDAL/PDAL/files/14407412/simple_faces.txt)
2. Rename it to simple_faces.ply (I changed the extension for github)
3. do : `pdal translate 'simple_faces.ply' 'simple_faces_bin.ply' --writers.ply.storage_mode="little endian" --writers.ply.faces="true"
4. Viusalize on ClouCompare : no faces

To be sure lets retranslate to ascii, to see if he info is still here : 
1. do : `pdal translate '/home/ostocker/travaux/trash_test/simple_faces_bin.ply' '/home/ostocker/travaux/trash_test/simple_faces_bin_to_ascii.ply' --writers.ply.storage_mode="ascii" --writers.ply.faces="true"`
2. Open the file : no faces

**Expected behavior**
Information of the faces should have been kept in the files, as argument `--writers.ply.faces` is equal to `true`

**System/installation information:**
```
$ uname -a
Linux ospc2 5.15.0-83-generic #92~20.04.1-Ubuntu SMP Mon Aug 21 14:00:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```
```
$ pdal --version
pdal 2.6.3 (git-version: d12128)
```

**Comment by abellgithub** [comment]
The ply reader does not read face data. PDAL doesn't not in general read mesh data.
