### ISSUE TITLE
feature request: 'random' culling filter

### ISSUE THREAD

**Issue by craigds** [PDAL/PDAL#4340]
PDAL currently has multiple filters that cull based on distance from other points.

If I have a pointcloud with heterogenous density and I want to produce an overview file from it, one thing I want to preserve is the density information.

Using voxelisation to cull  points removes that information. The decimation filter sounds like it would work but it is apparently dependent on the _ordering_ of the source points, which means my overview tiling may not be representative of third-party data with different ordering.

Rather, I would like to have a simple culling filter which removes points at random, based on a threshold. The exact points that pass the filter wouldn't be based on distance from other points, or their position in the source file, or their spatial location, or any other attributes, but would be proportionally representative of all source file characteristics.

e.g. pass points if `rand() < 0.10`, thus removing (approx) 90% of points.

I can imagine this looking like:

```json
{"type": "filters.cull_random", "threshold": 0.1}
```

(there's already `filters.sample` and `filters.randomize`, but they're quite different things)

**Comment by abellgithub** [comment]
You can use filters.randomize on the points before decimating.

**Comment by craigds** [comment]
True, I suppose, although being a sorting operation I imagine it would increase the time and memory complexity a lot (from O(n) -> O(n log n).

I guess in most cases COPC writer will need to re-sort them anyway, but by then there will be less points to sort (because of the culling)

It would be better if there was a way to cull based on a random value _without_ having to sort

**Comment by hobu** [comment]
> Rather, I would like to have a simple culling filter which removes points at random, based on a threshold. The exact points that pass the filter wouldn't be based on distance from other points, or their position in the source file, or their spatial location, or any other attributes, but would be *proportionally representative of all source file characteristics*.

I don't understand what the italicized statement means. What are you actually after? 

https://pdal.io/en/2.6.3/workshop/manipulation/thinning/thinning.html

**Comment by craigds** [comment]
We've talked internally and decided that we can ignore supporting variable-density pointclouds for now. So I can use voxelisation after all. You can close this ticket if you like.
