### ISSUE TITLE
Did 2.7.1 tag get removed?

### ISSUE THREAD

**Issue by chenrui333** [PDAL/PDAL#4374]
👋 did 2.7.1 release get removed? Did not find in the repo, if so, can you update the website page accordingly as well? Thanks! 

https://web.archive.org/web/20240327002336/https://pdal.io/en/latest/download.html

![image](https://github.com/PDAL/PDAL/assets/1580956/c460a056-82bd-4e93-b8ed-2168b76ddfae)

**Comment by hobu** [comment]
Sorry. Was just bumping stuff for release tonight. I haven't yet tagged and cut the release.

**Comment by chenrui333** [comment]
I see, make sense. Closing via https://github.com/Homebrew/homebrew-core/pull/167279
