### ISSUE TITLE
PDAL Tile Module reduces precision

### ISSUE THREAD

**Issue by weidinger-c** [PDAL/PDAL#4379]
Hi, 
I want to tile a pointcloud, but the resulting tiles only have a precision of 2 floating-point digits. Is there anything I can do to get the precision of the input pointcloud or at least .3 or .4 floating digits?

Also, the LAS version is set to 1.2, altough the input file was of LAS version 1.4, which can be a problem, if I e.g. have some attributes of type uint64, which is only supported in LAS version 1.4.

Example points in input file:
![image](https://github.com/PDAL/PDAL/assets/126055535/cf670e26-06db-4933-bce4-37d48b10a30c)

Example points inside one resulting tile:
![image](https://github.com/PDAL/PDAL/assets/126055535/f2ff7b7b-322f-49c6-a3f0-512f705c62a4)

**Comment by abellgithub** [comment]
You can pass options to the writer as you wish: `pdal tile in.las out#.txt --writers.text.precision=5`

**Comment by weidinger-c** [comment]
@abellgithub sorry, I forgot to mention, that I am tiling las files. There is no precision setting in the las writer. Can I pass the settings of the input las file?

**Comment by abellgithub** [comment]
All the options work, including forwarding. Note that LAS doesn't really do precision, though you can set the scale factor(s).

**Comment by weidinger-c** [comment]
Thanks! Setting --las.writer.forward="all" worked
