### ISSUE TITLE
Installing GeoPandas breaks pdal

### ISSUE THREAD

**Issue by maboualidev** [PDAL/PDAL#4381]
Hi,

I create an enviroment using conda installing the following packages (All from conda-forge):

```bash
python=3.11
pdal
python-pdal
gdal
```

`pdal` will work up to this point.

However, the moment I install geopandas using `conda install -c conda-forge geopandas` then `pdal` stops working:

```bash
Python 3.11.8 | packaged by conda-forge | (main, Feb 16 2024, 20:40:50) [MSC v.1937 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pdal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\miniconda3\envs\env_name\Lib\site-packages\pdal\__init__.py", line 4, in <module>
    from . import libpdalpython
ImportError: DLL load failed while importing libpdalpython: The specified module could not be found.
```

Not sure if this helps, but when installing `geopandas` I see this message:

```bash
The following packages will be DOWNGRADED:

  gdal                                3.8.4-py311h21a6730_6 --> 3.8.4-py311h21a6730_5
  geotiff                                 1.7.1-hed9d743_16 --> 1.7.1-hbf5ca3a_15
  libgdal                                  3.8.4-hbda495f_6 --> 3.8.4-hf83a0e2_5
  libspatialite                            5.1.0-hf13de1f_5 --> 5.1.0-hf2f0abc_4
  proj                                     9.4.0-he13c7e8_0 --> 9.3.1-he13c7e8_0
```

any idea how to fix?

**Comment by maboualidev** [comment]
Downgrading pdal to 2.5.6 solves the issue

**Comment by maboualidev** [comment]
pdal 2.7.0 also crashes, but a different error pops up

**Comment by maboualidev** [comment]
2.6.3 also crashes. Some other error though, the same as 2.7.0.

Seems the version of pdal that does work with geopandas is 2.5.6

**Comment by hobu** [comment]
Cannot replicate on osx-arm64.

The Geopandas Conda Forge recipe has not been rerendered in quite a while, and it has a [hard pin on Fiona 1.8.21](https://github.com/conda-forge/geopandas-feedstock/blob/main/recipe/meta.yaml#L48), which I suspect has windows-specific pins for its dependencies. 

I think you are in DLL hell here, basically.

**Comment by maboualidev** [comment]
Yeah, the issue is on windows only. Doesn’t happen on linux either

**Comment by hobu** [comment]
Replicated at https://github.com/PDAL/python/issues/164#issuecomment-2045582609 not sure what I can do to fix it, however.

**Comment by hobu** [comment]
After some investigation, [it was shown](https://github.com/conda-forge/pyproj-feedstock/pull/148#issuecomment-2087188180) this issue was due to a PROJ version pin in `pyproj`. Please retest to confirm things are now working.
