### ISSUE TITLE
Ply file not supported

### ISSUE THREAD

**Issue by kundu03** [PDAL/PDAL#4382]
Hi,
I have a .ply file with the following header,

ply
format binary_little_endian 1.0
element vertex 57162848
property float32 x
property float32 y
property float32 z
property uint8 red
property uint8 green
property uint8 blue
property float32 nx
property float32 ny
property float32 nz
property list uint8 uint32 view_indices
property list uint8 float32 view_weights
end_header

and i am trying to convert it to a .las / .laz file using "pdal translate" command and i am getting the following error.

PDAL: readers.ply: List properties are not supported for the 'vertex' element.

I think ply file with this header is not supported. So, can you please add the code so that it can support ply file with above header.
Thanks in advance.

**Comment by hobu** [comment]
> So, can you please add the code so that it can support ply file with above header.

Please provide a pull request implementing support for these kind of PLY files along with a test and we will be happy to merge it.
