### ISSUE TITLE
make报错了--pdal-2.7.1

### ISSUE THREAD

**Issue by wwhwwxlz** [PDAL/PDAL#4399]
/root/PDAL/pdal/util/FileUtils.cpp:348:16: error: ‘weakly_canonical’ is not a member of ‘fs’
     return fs::weakly_canonical(toNative(filename)).u8string();
                ^~~~~~~~~~~~~~~~
make[2]: Entering directory '/root/PDAL/build'
Scanning dependencies of target pdal_test_support
make[2]: Leaving directory '/root/PDAL/build'
make[2]: Entering directory '/root/PDAL/build'
[ 13%] Building CXX object test/unit/CMakeFiles/pdal_test_support.dir/Support.cpp.o
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-class-memaccess’
make[2]: *** [tools/lasdump/CMakeFiles/lasdump.dir/build.make:102: tools/lasdump/CMakeFiles/lasdump.dir/__/__/pdal/util/FileUtils.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....

**Comment by wwhwwxlz** [comment]
gcc--7.3

**Comment by abellgithub** [comment]
PDAL requires a compiler that supports C++17 completely, including std::filesystem. gcc 7.3 does not support std::filesystem.

**Comment by wwhwwxlz** [comment]
又出现了别的问题
/home/PDAL/io/private/las/Geotiff.cpp: In function ‘void pdal::las::{anonymous}::PDALGTIFErrorFunction(GTIF*, int, const char*, ...)’:
/home/PDAL/io/private/las/Geotiff.cpp:129:18: error: ‘LIBGEOTIFF_WARNING’ was not declared in this scope; did you mean ‘LIBGEOTIFF_VERSION’?
  129 |     if( level == LIBGEOTIFF_WARNING )
      |                  ^~~~~~~~~~~~~~~~~~

**Comment by wwhwwxlz** [comment]
这也跟gcc有关系吗？

**Comment by abellgithub** [comment]
I believe you have an old version of libgeotiff. This usually comes with GDAL and the version is checked, so I'm not sure what's going on. Perhaps a version of geotiff is being found that we're not expecting or we haven't properly specified the geotiff version in the build process.

(The value of LIBGEOTIFF_WARNING is 0, so you can just use that instead of you want.)

**Comment by wwhwwxlz** [comment]
/opt/aarch64/KPGCC/gcc-10.3.1-2023.12-aarch64-linux/bin/../lib64/gcc/aarch64-linux-gnu/10.3.1/../../../../aarch64-linux-gnu/bin/ld: /usr/local/lib64/libgdal.so.34: undefined reference to `GEOSConcaveHull_r'
/opt/aarch64/KPGCC/gcc-10.3.1-2023.12-aarch64-linux/bin/../lib64/gcc/aarch64-linux-gnu/10.3.1/../../../../aarch64-linux-gnu/bin/ld: /usr/local/lib64/libgdal.so.34: undefined reference to `GEOSMakeValidWithParams_r'
/opt/aarch64/KPGCC/gcc-10.3.1-2023.12-aarch64-linux/bin/../lib64/gcc/aarch64-linux-gnu/10.3.1/../../../../aarch64-linux-gnu/bin/ld: /usr/local/lib64/libgdal.so.34: undefined reference to `GEOSMakeValidParams_setMethod_r'
/opt/aarch64/KPGCC/gcc-10.3.1-2023.12-aarch64-linux/bin/../lib64/gcc/aarch64-linux-gnu/10.3.1/../../../../aarch64-linux-gnu/bin/ld: /usr/local/lib64/libgdal.so.34: undefined reference to `GEOSMakeValidParams_setKeepCollapsed_r'
/opt/aarch64/KPGCC/gcc-10.3.1-2023.12-aarch64-linux/bin/../lib64/gcc/aarch64-linux-gnu/10.3.1/../../../../aarch64-linux-gnu/bin/ld: /usr/local/lib64/libgdal.so.34: undefined reference to `GEOSMakeValid_r'
/opt/aarch64/KPGCC/gcc-10.3.1-2023.12-aarch64-linux/bin/../lib64/gcc/aarch64-linux-gnu/10.3.1/../../../../aarch64-linux-gnu/bin/ld: /usr/local/lib64/libgdal.so.34: undefined reference to `GEOSMakeValidParams_destroy_r'
/opt/aarch64/KPGCC/gcc-10.3.1-2023.12-aarch64-linux/bin/../lib64/gcc/aarch64-linux-gnu/10.3.1/../../../../aarch64-linux-gnu/bin/ld: /usr/local/lib64/libgdal.so.34: undefined reference to `GEOSMakeValidParams_create_r'
能再帮我看下这个问题吗

**Comment by wwhwwxlz** [comment]
我的gdal是3.8.5版本
