### ISSUE TITLE
[Symbol lookup error] /usr/lib/libpdalcpp.so.17: undefined symbol: _Z15xmlCheckVersioni

### ISSUE THREAD

**Issue by waarmond** [PDAL/PDAL#4405]
**Describe the bug**
I've built [this PKGBUILD](https://gitlab.archlinux.org/archlinux/packaging/packages/pdal/-/blob/main/PKGBUILD?ref_type=heads) against current sources. The build is successful, but running PDAL leads to:
`pdal: symbol lookup error: /usr/lib/libpdalcpp.so.17: undefined symbol: _Z15xmlCheckVersioni`

**Expected behavior**
Earlier failure during compilation ;)

**System/installation information:**
* ArchLinux
* Python 3.10 (sic)
* pdal: git master (no working binary)

* jsoncpp 1.9.5
* libxml2 2.12.7 [added - removed - added again]

**Comment by waarmond** [comment]
I've recompiled with your patch but the same error remains.

Something with my libxml2 has to be wrong.

**Comment by abellgithub** [comment]
This symbol is missing from the XML library you're finding at *runtime* but it exists at build time. There is something inconsistent with the way your building vs. the way you're trying to run. You should verify the runtime path (RPATH) of your library and also make sure you aren't overriding with some environment variable.
