### ISSUE TITLE
undefined symbol: sqlite3_total_changes64

### ISSUE THREAD

**Issue by lishenyu1024** [PDAL/PDAL#4420]
Hi teams,

**Describe the bug**
I successfully downloaded the file but encountered an issue while compiling it. When using the command:

```
$ pdal info Pure.las
```
I received the following error message:

pdal: symbol lookup error: /local/home/lu/miniconda3/bin/../lib/./libgdal.so.35: undefined symbol: sqlite3_total_changes64
This error occurs when attempting to get details from the LAS file.

**Expected behavior**
I expected the command pdal info Pure.las to provide detailed information about the LAS file without encountering any errors.

**System/installation information:**

I installed the following packages using conda on Linux 2:

```
$ conda list
```
python                    3.12.2          hab00c5b_0_cpython    conda-forge
python-pdal               3.4.3           py312hf73f035_0    conda-forge
sqlite                    3.32.3               hcee41ef_1    conda-forge
conda                     24.5.0          py312h7900ff3_0    conda-forge
pdal                      2.7.1               hedfc232_11    conda-forge
pdal-plugins              1.5.0                    pypi_0    pypi
gdal                      3.9.0           py312h86af8fa_7    conda-forge

```
$ conda info
```

     active environment : base
    active env location : /home/lu/miniconda3
            shell level : 1
populated config files : 
          conda version : 24.5.0
    conda-build version : not installed
         python version : 3.12.2.final.0
                 solver : libmamba (default)
 platform : linux-64
             user-agent : conda/24.5.0 requests/2.31.0 CPython/3.12.2 Linux/2 glibc/2.26 solver/libmamba conda-libmamba-solver/24.1.0 libmambapy/1.5.8 

I'm encountering an issue and would appreciate debugging assistance. Please provide guidance on how to resolve the issue. Thank you：）

**Comment by akrherz** [comment]
`sqlite=3.32.3` is very ancient.  How/when did you install your current conda environment?  libgdal=3.9 should have a libsqlite requirement `>=3.45.3,<4.0a0`

**Comment by lishenyu1024** [comment]
I upgraded SQLite, and it works. However, there's a discrepancy between the information displayed on my local machine and my cloud desktop. When I extract the same file locally and on the cloud desktop, there's less information in the cloud desktop version of PDAL info.

In the cloud version of PDAL info, several lines of information are missing compared to the local version. These lines correspond to the statistics for additional dimensions or attributes present in the LAS file but not present in the LAZ file. Here are the missing lines from the cloud:

Intensity
ReturnNumber
NumberOfReturns
ScanDirectionFlag
EdgeOfFlightLine
Classification
ScanAngleRank
UserData
PointSourceId
GpsTime
Synthetic
KeyPoint
Withheld
Overlap
These lines represent various attributes or dimensions associated with the point cloud data. For example:

Intensity: Represents the intensity value of the returned pulse.
ReturnNumber: Indicates the return number for a given pulse.
Classification: Specifies the type of ground feature (e.g., ground, vegetation, building).
GpsTime: Records the GPS time for the point.
These attributes provide additional information about the points in the point cloud beyond just spatial coordinates (X, Y, Z) and color (Red, Green, Blue).

Appreciate debugging assistance：）
