### ISSUE TITLE
can not use pdal in c++program

### ISSUE THREAD

**Issue by WuSanxiao** [PDAL/PDAL#4424]
I install the pdal with conda command "conda install pdal=1.9.1 -c conda-forge", and test no problem with command "pdal --version".
But when I use pdal in my c++ program, there is many errors such as fllow:
    error: PointClouds.cpp:(.text+0x136): undefined reference to `vtable for pdal::PointTable'
    error: PointClouds.cpp:(.text+0x17a): undefined reference to `pdal::PointLayout::PointLayout()'
    ......
in project gdal is no problem,but pdal no work ,qt project setting as fllow:
    INCLUDEPATH += /home/wuhao/anaconda3/envs/pdal/include
    LIBS += -L/home/wuhao/anaconda3/envs/pdal/lib -lpdal_base -lpdal_util
    LIBS += -L/home/wuhao/anaconda3/envs/pdal/lib -lgdal

**Comment by abellgithub** [comment]
There's no way to know what the problem might be with the information you've provided. I would create a small test program that you can compile and link on the command line to help debug your linking issue.
