### ISSUE TITLE
Typo in `option_file` documentation

### ISSUE THREAD

**Issue by lpinner** [PDAL/PDAL#4425]
**Describe the bug**
The Option Files option documentation [(pipeline.rst#L267)](https://github.com/PDAL/PDAL/blob/master/doc/pipeline.rst?plain=1#L267) specifies `option file` (missing underscore) instead of `option_file`.  

**Expected behavior**
Suggest adding the underscore to avoid confusion (as written and without an example, the doc could be misinterpreted to mean `"option": "file"`) and be consistent with [pipeline.rst#L248](https://github.com/PDAL/PDAL/blob/master/doc/pipeline.rst?plain=1#L248) and [Stage.cpp#L124](https://github.com/PDAL/PDAL/blob/master/pdal/Stage.cpp#L124)

**Comment by hobu** [comment]
picked back to `2.7-maintenance` at 849f0e1ca831d3b93af7971777c35173352ef3ba
