### ISSUE TITLE
filters.crop with outside == true and multiple polygons , any point is removed. 

### ISSUE THREAD

**Issue by nakamura2000** [PDAL/PDAL#4427]
If I apply filters.crop with outside == true and with multiple geometies,
no point is removed.

two rectangles inside image are polygons of crop area.
![sample-data](https://github.com/PDAL/PDAL/assets/22187826/8670eaa5-6d5e-48fd-a254-f8e36422edb7)

I attached files to reproduce issue.

If I apply one geometry , it processed as I expected.

```
$ pdal pipeline pipeline-crop-1-2.json
```

<details>

```

[
     "source.las",
     {
        "type": "filters.crop", 
        "polygon": 
            ["POLYGON((-71 71,-71 28,-14 28,-14 71,-71 71))",
            "POLYGON((28 -28,28 -71,85 -71,85 -28,28 -28))"], 
        "outside": true
     },
     "crop-1-2.las"
]

```

[multiple-crop-issue.zip](https://github.com/user-attachments/files/15982584/multiple-crop-issue.zip)

</details>

**Expected behavior**
point inside any geometry are removed.

**System/installation information:**
```
Microsoft Windows [Version 10.0.22631.3737]
```
```
pdal 2.7.1 (git-version: Release)
```

**Comment by abellgithub** [comment]
Each input geometry is processed separately and a point view is created for each of the input polygons. The output of your test case should be all points in the input with those outside BOTH polygons repeated. If you want to filter out all points not in *any* polygon, you'll have to place each polygon in a separate filter and run them sequentially.

**Comment by hobu** [comment]
>  If you want to filter out all points not in any polygon, you'll have to place each polygon in a separate filter and run them sequentially.

An alternative approach is to label with `filters.overlay` and then cull with `filters.expression` as shown in the workshop at https://pdal.io/en/2.7-maintenance/workshop/manipulation/clipping/clipping.html

**Comment by nakamura2000** [comment]
Thank you. I will you filters.overlay and filters.expression.

**Comment by sachasmart** [comment]
> > If you want to filter out all points not in any polygon, you'll have to place each polygon in a separate filter and run them sequentially.
> 
> An alternative approach is to label with `filters.overlay` and then cull with `filters.expression` as shown in the workshop at https://pdal.io/en/2.7-maintenance/workshop/manipulation/clipping/clipping.html

Could you supply the link again? Looks like this one is broken

**Comment by abellgithub** [comment]
Link updated.
