### ISSUE TITLE
Missing release assets for 2.7.2

### ISSUE THREAD

**Issue by echoix** [PDAL/PDAL#4432]
**Describe the bug**
PDAL released 2.7.2 today.

Contrary to the other releases, that new release doesn't include the same assets that are used in build scripts. Thus, downloading with an url similar to `https://github.com/PDAL/PDAL/releases/download/${PDAL_VERSION}/PDAL-${PDAL_VERSION}-src.tar.gz` will fail.

For example, in a dockerfile:
```
Dockerfile:106
--------------------
 105 |     WORKDIR /src
 106 | >>> RUN wget -q \
 107 | >>>  https://github.com/PDAL/PDAL/releases/download/${PDAL_VERSION}/PDAL-${PDAL_VERSION}-src.tar.gz && \
 108 | >>>     tar xfz PDAL-${PDAL_VERSION}-src.tar.gz && \
 109 | >>>     cd /src/PDAL-${PDAL_VERSION}-src && \
 110 | >>>     mkdir build && \
 111 | >>>     cd build && \
 112 | >>>     cmake .. \
 113 | >>>       -G "Unix Makefiles" \
 114 | >>>       -DCMAKE_BUILD_TYPE=Release \
 115 | >>>       -DCMAKE_INSTALL_PREFIX=/usr \
 116 | >>>       -DCMAKE_C_COMPILER=gcc \
 117 | >>>       -DCMAKE_CXX_COMPILER=g++ \
 118 | >>>       -DCMAKE_MAKE_PROGRAM=make \
 119 | >>>       -DBUILD_PLUGIN_PYTHON=ON \
 120 | >>>       -DBUILD_PLUGIN_CPD=OFF \
 121 | >>>       -DBUILD_PLUGIN_GREYHOUND=ON \
 122 | >>>       -DBUILD_PLUGIN_HEXBIN=ON \
 123 | >>>       -DHEXER_INCLUDE_DIR=/usr/include/ \
 124 | >>>       -DBUILD_PLUGIN_NITF=OFF \
 125 | >>>       -DBUILD_PLUGIN_ICEBRIDGE=ON \
 126 | >>>       -DBUILD_PLUGIN_PGPOINTCLOUD=OFF \
 127 | >>>       -DBUILD_PGPOINTCLOUD_TESTS=OFF \
 128 | >>>       -DBUILD_PLUGIN_SQLITE=ON \
 129 | >>>       -DWITH_LASZIP=OFF \
 130 | >>>       -DWITH_LAZPERF=ON \
 131 | >>>       -DWITH_TESTS=ON && \
 132 | >>>     make -j $NUMTHREADS && \
 133 | >>>     make install
 134 |     
--------------------
``` 

**Expected behavior**
Either add the same release assets to the release (from an automated workflow would be best to be constant between releases),
or explicitly announce that these assets won't be supplied anymore and users must change their build scripts and integrations for this release, and use the dynamically generated source archives provided by GitHub, if there isn't any significant changes.

**System/installation information:**
See a failing Docker build here https://github.com/OSGeo/grass/actions/runs/9719096265/job/26828288072#step:7:3154, from this PR https://github.com/OSGeo/grass/pull/3937

**Comment by hobu** [comment]
Whoops!

https://github.com/PDAL/PDAL/releases/tag/2.7.2 has the artifacts now.

#4433 is a ticket to complete the automation so this is no longer a manual activity (I forgot!).
