### ISSUE TITLE
pgpointcloud is not installed, it is disabled when cmake, how to make it enabled

### ISSUE THREAD

**Issue by Garbage123King** [PDAL/PDAL#4437]
root@dashi-virtual-machine:~/git/PDAL/build# cmake -DCMAKE_BUILD_TYPE=Debug ..
-- Could NOT find LIBEXECINFO (missing: LIBEXECINFO_LIBRARY)
-- The following features have been enabled:

 * Unit tests, PDAL unit tests
 * Backtrace, build with backtrace (Libunwind/Libexecinfo) support
 * Google Cloud Storage, build with OpenSSL and others for Google storage IO support

-- The following OPTIONAL packages have been found:

 * Libunwind
 * ZSTD
   General compression support
 * LibXml2
 * PkgConfig
 * OpenSSL (required version >= 1.1)
 * Python

-- The following REQUIRED packages have been found:

 * PROJ (required version >= 9.0)
   Provides coordinate system transformation and definition support
 * GDAL (required version >= 3.4)
   Provides general purpose raster, vector, and reference system support
 * GeoTIFF
 * ZLIB
   Compression support in BPF
 * CURL
 * Threads, The thread library of the system

-- The following features have been disabled:

 * Bash completion, completion for PDAL command line
 * CPD plugin, Coherent Point Drift (CPD) computes rigid or nonrigid transformations between point sets
 * Draco plugin, Read data in the draco format
 * Icebridge plugin, read data in the Icebridge format
 * HDF plugin, read data in the HDF format
 * Matlab plugin, write data to a .mat file
 * NITF plugin, read/write LAS data wrapped in NITF
 * OpenSceneGraph plugin, read/write OpenSceneGraph objects
 * PostgreSQL PointCloud plugin, read/write PostgreSQL PointCloud objects
 * RiVLib plugin, read data in the RXP format
 * rdblib plugin, read data in the RDB format
 * MBIO plugin, add features that depend on MBIO
 * FBX plugin, add features that depend on FBX
 * TEASER++ plugin, TEASER++ computes transformations between point sets
 * TileDB plugin, read/write data from TileDB
 * Trajectory plugin, Compute trajectory from LAS input
 * E57 plugin, read/write data to and from e57 format
 * Abseil debugging support , unit tests

-- The following OPTIONAL packages have not been found:

 * PostgreSQL
 * Libexecinfo

-- Configuring done
-- Generating done
-- Build files have been written to: /root/git/PDAL/build

And I have run `sudo apt-get install postgresql libpq-dev`
why still  "PostgreSQL packages have not been found"?

**Comment by hobu** [comment]
try `--debug-find` on your CMake invocation in hopes of it complaining to you what it thinks it can't find.

**Comment by Garbage123King** [comment]
I make it enabled by this command:

cmake \
-DPostgreSQL_INCLUDE_DIR:PATH=/usr/local/pgsql/include \
-DPostgreSQL_LIBRARY_DEBUG:FILEPATH=/usr/local/pgsql/lib/libpq.so \
-DPostgreSQL_TYPE_INCLUDE_DIR:PATH=/usr/local/pgsql/include \
-DCMAKE_BUILD_TYPE=DEBUG ..
