### ISSUE TITLE
Installing python-pdal causes issue with projection

### ISSUE THREAD

**Issue by maboualidev** [PDAL/PDAL#4440]
When `python-pdal` is installed the following error is generated:

```bash
pj_obj_create: Open of /home/username/miniconda3/envs/env_name/share/proj failed
```

The following sequence on a Linux machine would end up to the above issue:

```bash
conda config --add channels conda-forge
conda create --name env_name python=3.11
conda activate env_name
conda install geopandas pyfiglet polyline fiona jupyterlab tqdm rioxarray ipywidgets ipympl matplotlib laspy
conda isntall python-pdal gdal
```

**Comment by hobu** [comment]
Verified, but I'm not sure how this is PDAL's fault. Continuing to investigate.

**Comment by maboualidev** [comment]
Thanks; I also look into this if I find more information, will share here.

**Comment by iswarup** [comment]
@hobu I'm having the same problem but while debugging a python code in vscode.
Same code works smoothly in a terminal

**Comment by hobu** [comment]
@iswarup check that your conda environment is activated and `PROJ_DATA` environment variable points to the conda environment's `$CONDA_PREFIX/share/proj`  directory containing `proj.db`.  If none of that makes sense to you, you will have to do more investigation. This is not a PDAL issue.

**Comment by maboualidev** [comment]
This issue was happening to me with certain combination of versions. If you could, update everything to their latest version and the issue goes away.
