### ISSUE TITLE
Tiff matters when not in /user/local (PATH) - Macos Monterey 

### ISSUE THREAD

**Issue by Laurent-777** [PDAL/PDAL#4455]
PDAL versions : all
IDE tool: Cmake
OS : Macos Monterey (12.7.5)
Compilers used : Clang 14.4.0.x (from Xcode or Command line tools 14.3.x, the last ones for Monterey)

Third parties such as TIFF library are never in /user/local : they all are saved in an external HD, or in an user folder dedicated for each library or each application.

The issue: make fails because the TIFF library is not found.

My current investigation :
- recompilation of Tiff and GeoTiff ;
- findTiff is missing, although one may find in the PDAL tree other modules for CMake ;
- rpath is not working in that case, even though it's working pretty well with GDal as an example.

So, PDAL cannot be used, because compilation fails.
Regrets.

Proposal : add findTiff in the CMake text file 

Thank you very much.

**Comment by hobu** [comment]
PDAL depends on GeoTIFF, which depends on libtiff. See its configuration at https://github.com/PDAL/PDAL/blob/master/cmake/geotiff.cmake

We are no longer including Find* CMake scripts whenever possible.

I do all of my development on Sonoma with Conda Forge dependencies. Your report is not specific enough to tell us how you've built or configured your setup, but you should report some CMake configuration errors if you want any more help with the topic.

**Comment by Laurent-777** [comment]
Dear Sir :

Thank you very much for your quick reply.

Currently, I am investigating what matters during the compilation process. However, I am happy to let you know that I suceeded to build and to install the first versions of PDAL, with some modifications of the third parties I am using.

So, as I told you before, I recompiled GeoTIFF and TIFF (NB Please remember that I am working on a Mac computer, the macOS version being Monterey, 12.7.5).

OK for TIFF, but a problem with GeoTIFF. In fact, for every version of the library, the option --with-proj=PATH_to_GeoTIFF_installed, the include file proj_api.h is never found (NB Different versions of PROJ installed were tested). Same issue when I use PKGCONFIG or the CPPFLAGS/LIBFLAGS. Then, I tried to compile GeoTIFF with a minimal configuration (even not JPEG was used). And after done this, the GeoTiff compilation was good.
Besides, I had another matter with GDAL. Depending on the versions installed (all were correctly installed and tested through a GIS software), the compilation of PDAL worked... or not. It appeared that GDAL versions beyond 3.6.x implied the make process to fail.

Consequently, beginning with PDAL v. 1.9.1 and with the "minimal" GeoTIFF and GDAL 3.6.x, PDAL was correctly compiled, installed, and tested through 2.2.0 at that time. Next versions will be investigated this afternoon.

Hence my issue was a GeoTIFFand Gdal sensitivity in fact.

As soon as I end these installations, I will send you a mini-report will all my results.

Kind regards,

L. Delphin

**Comment by Laurent-777** [comment]
Dear Sir :

Herefater my mini-report.

Kind regards,

L. Delphin

############

Preliminary remark : later versions failed because of a GEOTIFF (TIFF error within PDAL make) issue.
		I built GEOTIFF in a minimal set of variables to be configured to try fixing the error. In particular, I saw that PROJ.x makes its compilation failing=> with-proj=no. See the GEOTIFF script for Monterey. 

1.	PDAL 1.9.1
1a.	GDAL 3.5.x, GEOTIFF 1.4.3 minimal, with tests is no, no gtest, no PostGreSQL
	cURL, XML2, ZLIB : mines
	=> OK
1b.	Id 1.a, but GEOTIFF 1.5.1 (minimal + PROJ.7 : PROJ.x is needed ; last PROJ.x with proj_api.h)
	=> OK
1c.	Id 1.b but GEOTIFF 1.6.0 (minimal + PROJ.7)(but built with autotools : with CMake, it fails)
	=> OK
1d.	Id 1.c, WITH_TESTS=TRUE
	=> OK (but some tests)
1e.	Id 1.d, adding PostGreSQL
	=> no effect, so OK
1.f Id 1.e, but GDAL 3.6.x
	=> OK
1.g Id. 1f, but GDAL 3.7.x
	=> FAILED
1h. Id 1.g but GDAL 3.8.x
	=> FAILED
1i.	Id 1.h but GDAL 3.9.x
	=> FAILED
1j. Id 1.f, with PYTHON (Xcode or Command Line Tools : python3)
	=> OK

	So, are used :
		- mines : cURL, XML2, ZLIB, PostGreSQL ;
		- geoTIFF (autotools only, “minimal” ; no one built with CMake) ; up to 1.6.x
		- GDAL, up to 3.6.x (for this PDAL version)
		- PROJ.7 (for proj_api.h)
		- possibly python(3 - XCODE/CLTools)).

2. PDAL 2.0.1
2a. Id 1.j, plus OpenSSL (mine)
	=> OK
2b. Id 2a, testing GDAL 3.7.x
	=> FAILED

3.	PDAL 2.1.0
3a. Id 2a
	=> OK

4.	PDAL 2.2.0
4a. Id 2.a
	=> OK

5.	PDAL 2.3.0
5a. Id 2a
	=> OK

6.	PDAL 2.4.0
6a. Id 2a
	=>  OK
6b. With GDAL 3.7.x
	=> FAILED

7	PDAL 2.5.0
7a. Id 2a
	Error when make :
	In file included from /Volumes/External_7/_Mathematical-Softwares/_PDAL/_Source/PDAL-2.5.0-src/io/private/las/Geotiff.cpp:41:
In file included from /Users/laurentdelphin/_Ze-Libraries/_GeoTIFF/include/geo_tiffp.h:37:
/Users/laurentdelphin/_Ze-Libraries/_GeoTIFF/include/xtiffio.h:10:10: fatal error: 'tiffio.h' file not found
#include "tiffio.h"
	=> FAILED

8.	PDAL 2.5.6
8a. Id 2a
	Error when make :
	In file included from /Volumes/External_7/_Mathematical-Softwares/_PDAL/_Source/PDAL-2.5.6-src/io/private/las/Geotiff.cpp:41:
In file included from /Users/laurentdelphin/_Ze-Libraries/_GeoTIFF/include/geo_tiffp.h:37:
/Users/laurentdelphin/_Ze-Libraries/_GeoTIFF/include/xtiffio.h:10:10: fatal error: 'tiffio.h' file not found
#include "tiffio.h"
	=> FAILED

9.	PDAL 2.6.3
	Remark : “significant” change -> PROJ.x configuration variables are required 
9a. Id 2a, plus PROJ.7
	=> FAILED (tiffio.h error as above)
9b. Id 9a but PROJ.6
	=> FAILED (tiffio.h error)

10.	PDAL 2.7.2
10a. Id 2a, plus PROJ.9 + SQLite3 (mine). TIFF is set
	Remarks : significant changes
		- PROJ asks for a cmake file (DIR) : is given the “proj” subfolder
		- TIFF configuration varaiables are present
		- ditto SQLite(3)
	=> FAILED (TIFF error as before)

	!!!!!!	The TIFF used by the PDAL team probably is different from my own. TIFF6 has an extended package (xtif…). To be asked…
##############
