### ISSUE TITLE
Question regarding the gdal writer

### ISSUE THREAD

**Issue by trns1997** [PDAL/PDAL#4466]
https://pdal.io/en/2.7.2/stages/writers.gdal.html

Not sure if this is the right place to ask this question. 
The writer creates up to six rasters based on different statistics in the output dataset (from the doc). I was wondering is there a way to have our own criteria for example the (max - min) value to generated a tiff instead of the base 6 provided?

**Comment by hobu** [comment]
> this max-min feature and create a PR

definitely interested in this.

**Comment by abellgithub** [comment]
Can you make two rasters and then subtract them?

**Comment by trns1997** [comment]
@abellgithub i just tested, i generated 2 taster one with max and the other with min, then used gdal_calc to generate a new raster with the relative diff between min max in each cell (gdal_calc -a output_min.tif -b output_max.tif --calc="b - a" --outfile output.tif). This is great and all. But ideally i would like to do everything in a single cpp exec, without the need of creating and passing intermediate files. I could do it all using gdal, but i loved the idea of using pdal to generate the grid using the resolution i pass it and then using the writer and the (max-min) feature to generate the raster tile.

**Comment by hobu** [comment]
> This is great and all. But ideally i would like to do everything in a single cpp exec, without the need of creating and passing intermediate files

I get it, but there's a way to get the best of both without having to add more software to PDAL. [`filters.shell`](https://pdal.io/en/latest/stages/filters.shell.html) is a not-well-advertised capability that allows you to add pipeline stages that drop down to the shell to do various things. It is quite useful for this scenario where you want to create intermediate outputs and then do GDAL things to them.

Here's a pipeline that does your scenario all in a single invocation:

```
[
    {
        "type": "readers.copc",
        "tag": "reader",
        "filename": "https://s3.amazonaws.com/hobu-lidar/autzen-classified.copc.laz",
        "resolution": 1.0
    },
    {
        "type": "writers.gdal",
        "tag": "lowest",
        "filename": "lowest.tif",
        "resolution": 2.0,
        "output_type": "min",
        // binmode means only accumulate statistics for points *inside* the pixel
        "binmode": "true",
        "dimension": "Z",
        "data_type": "float32"
    },
    {
        "type": "writers.gdal",
        "tag": "highest",
        "filename": "highest.tif",
        "resolution": 2.0,
        "output_type": "max",
        "binmode": "true",
        "dimension": "Z",
        "data_type": "float32"
    },
    {
        "type": "filters.shell",
        "command": "gdal_calc -a lowest.tif -b highest.tif --calc=\"b - a\" --outfile range.tif"
    },
    {
        "type": "filters.shell",
        "command": "gdal_translate -f COG range.tif range.cog.tif"
    },
    // clean up temporaries
    {
        "type": "filters.shell",
        "command": "rm lowest.tif highest.tif range.tif"
    }
]

```
![image](https://github.com/user-attachments/assets/eca10987-7364-4dc8-ad94-7ba4f350c0ad)

>  down to the shell to do various things

This might be kind of bad though 😄. A user must set `PDAL_ALLOW_SHELL=ON` in their environment before shell calls can work. You probably don't want to do this if you're allowing people to pass pipeline fragments via the internet into your infrastructure, but caveat emptor.

**Comment by hobu** [comment]
> then passes that object to opencv without creating intermediate output files

Maybe try writing to [MEM driver](https://gdal.org/drivers/raster/mem.html) outputs? That would eliminate the intermediate file stuff, but you would have to be careful to stay in-process with all your access and usage.

Raster algebra is out of scope for PDAL. The simple $range=max-min$ would be fine to add a PR for, but anything more complex than this should be handled by tools made for it.

**Comment by abellgithub** [comment]
User-driven statistics would be difficult to do well. Even this conceptually simple statistic requires working with two rasters and right now rasters are independent.

**Comment by trns1997** [comment]
@abellgithub you are right, it is not really trivial to add. each criteria min, max, idw are their own `Rasterd` object. I do not know how complex is it to take the min raster object and max raster object and do a simple subtraction. But firstly @abellgithub i do not really understand the point of the radius option is the writer:
- radius
    Radius about cell center bounding points to use to calculate a cell value. [Default: [resolution](https://pdal.io/en/2.7.2/stages/writers.gdal.html#resolution) * sqrt(2)]

Correct me if i am wrong, but in the case if be use the min criteria to create a raster, when we generate the grid with a resolution, don't we simply need to look at the min value of the points that lie with in a given cell? Why the need to of the radius exactly? And why the choice of `resolution*sqrt(2)`, i am guessing because for a give length of cell, the hypotenus is `sqrt(2)*length_of_cell` but if you take that radius from the center of the cell, wouldn't that mean we look at points that lie outside the cell?

**Comment by abellgithub** [comment]
You can set `binmode` to true if you want cell statistics based on only those points in a cell.

**Comment by trns1997** [comment]
> You can set `binmode` to true if you want cell statistics based on only those points in a cell.

Yup i do that, i was just curious to why the option exists?

**Comment by hobu** [comment]
> why the option exists?

Why `binmode` exists? `writers.gdal` was originally developed to raster interpolation of point clouds. It only provides the one interpolation mode. This code originated a long time ago from OpenTopography's [points2grid](https://opentopography.org/otsoftware/points2grid). It has accreted features over the years, but one of the things that people have commonly wanted is simple bin statistics without the interpolation. That's why it was added.
