### ISSUE TITLE
Can't filter out points by Withheld flag

### ISSUE THREAD

**Issue by StrandedKitty** [PDAL/PDAL#4467]
I'm working with the [USGS 2015-2016 LA point cloud](https://noaa-nos-coastal-lidar-pds.s3.amazonaws.com/laz/geoid18/8651/index.html) and I'm trying to filter out the points that have `Withheld` flag set to true.
It's easy to see that this dataset has quite a bit of points that are marked as withheld: [Potree viewer](https://usgs.entwine.io/data/view.html?r=https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_CA_LosAngeles_2016_LAS_2018/ept.json)

For example, take this LAZ point cloud: https://noaa-nos-coastal-lidar-pds.s3.amazonaws.com/laz/geoid18/8651/20160220_CA_LosAngeles_2016_L4_6482_1836b.laz

I'm using this pipeline:

```
{
	"pipeline": [
		{
			"type": "readers.las",
			"filename": "data/in.laz"
		},
		{
			"type": "filters.expression",
			"expression": "Classification != 7 && Withheld == 0"
		},
		{
			"type": "filters.assign",
			"value": "Overlap = 0"
		},
		{
			"type": "filters.reprojection",
			"out_srs": "EPSG:3857+3855"
		},
		{
			"type": "writers.las",
			"filename": "data/out.laz"
		}
	]
}
```

The resulting laz file still has points that were marked as withheld in the original point cloud.

**Comment by abellgithub** [comment]
Ran your pipeline on the input and then ran `pdal info --stats out.laz`, which contained the following output:
``` 
{
        "average": 0,
        "count": 2500055,
        "maximum": 0,
        "minimum": 0,
        "name": "Withheld",
        "position": 18,
        "stddev": 0,
        "variance": 0
},
```
Running statistics on the original file gives:
```
{
        "average": 0.009811210562,
        "count": 2527313,
        "maximum": 1,
        "minimum": 0,
        "name": "Withheld",
        "position": 16,
        "stddev": 0.09856446902,
        "variance": 0.009714954554
      },
```

You should check your processing.

**Comment by StrandedKitty** [comment]
Thanks for looking into it but I think the statistics are a bit misleading. Something does get removed, but a lot of `Withheld` points are still there (if not all of them).

This is what this spot looks like in the USGS Potree viewer (cyan points are `Withheld`):
![image](https://github.com/user-attachments/assets/04074348-a1c2-4df7-9aa5-c3b338c59fef)

Here is the original LAZ file previewd on plas.io (note a lot of artifacts on top classified as `Withheld`):
![image](https://github.com/user-attachments/assets/98da7b6a-5df2-4a17-b030-820bc744cd09)

And this is what it looks like after applying `filters.expression` with `Withheld == 0`:
![image](https://github.com/user-attachments/assets/65feff3a-333a-4b10-81a1-23c0ea2937dc)

So `Withheld` data is still there, it doesn't go away.
I also noticed that there's a small chunk on the right that gets removed after applying the filter (yellow color on the second image). This looks very suspicios, maybe there's a bug somewhere in the LAZ reader and `Withheld` flag gets applied to wrong points or something?

**Comment by connormanning** [comment]
Those points appear to be marked as "High Noise" rather than Withheld ([link](https://viewer.copc.io?state=faa4e0ddbe5391ef3f9b55da5df4c3d63413420425e62ab40d07570cb7453293)).

![Eptium](https://github.com/user-attachments/assets/1b49f1b8-a700-4a84-87bc-71e164c14597)

In Potree they are the same color because they are "Default", but that doesn't mean that they are the same classification, just that they are uncategorized by the other values:
![Potree](https://github.com/user-attachments/assets/fe96db0c-9fde-48fd-8886-dd0a880794cc)

I think there may be some confusion here based on the above colorings.

**Comment by StrandedKitty** [comment]
Thanks a lot, adding `Classification != 18` to the expression helped! This concludes this issue.

I'm either using Potree wrong or there's some issue there. If I visit the [EPT viewer for this dataset](https://usgs.entwine.io/data/view.html?r=%22https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_CA_LosAngeles_2016_LAS_2018/ept.json%22) I can uncheck the "withheld" checkbox and the cyan points get hidden. At the same time, unchecking "high noise" checkbox does nothing.

**Comment by connormanning** [comment]
I think you're correct that there's an issue with that deployment of the Potree viewer.  It is a very old build, and I'm not sure Classification and its associated flags are handled correctly in it.  For the moment, I'd rely on viewer.copc.io for Classification/flags, or potentially a newer version of Potree.
