### ISSUE TITLE
writers.pgpointcloud: Missing value for positional argument 'filename'

### ISSUE THREAD

**Issue by mghildiy** [PDAL/PDAL#4472]
**Describe the bug**
I am following [this](https://pdal.io/en/2.7.2/stages/writers.pgpointcloud.html#example)  to populate point clouds data in postgres DB.

My input json is:

```
[
        {
            "type":"readers.las",
            "filename":"D:\\.......\\input.las",
            "spatialreference":"EPSG:26916"
        },
        {
            "type":"filters.chipper",
            "capacity":400
        },
        {
            "type":"writers.pgpointcloud",
            "connection":"host='localhost' dbname='Lidar' user='postgres' password='postgres' port='5432'",
            "table":"my_pointcloud",
            "compression":"dimensional",
            "srid":"26916"
        }
]
```

Buy trying to run it with command:

`pdal pipeline --input mypipeline.json`

..gives error:

`PDAL: writers.pgpointcloud: Missing value for positional argument 'filename'.`

I don't see any argument 'filename' for writers.pgpointcloud in official documentation.

**Comment by abellgithub** [comment]
This is a bug. We don't get much use of the pgpointcloud writer anymore, so this got missed. I've created the following [PR](https://github.com/PDAL/PDAL/pull/4474) to address the issue.

**Comment by fivecheesetortellini** [comment]
> This is a bug. We don't get much use of the pgpointcloud writer anymore, so this got missed. I've created the following [PR](https://github.com/PDAL/PDAL/pull/4474) to address the issue.

Hello! I'm just trying to understand why the pgpointcloud writer doesnt get used much anymore. Is there a more efficient way to do postgres imports of las data that you are aware of? Additionally, did this bug get updated in a certain numbered release?

**Comment by hobu** [comment]
> why the pgpointcloud writer doesnt get used much anymore

I think the answer to this is point cloud data are *read* many more times than their written. Putting data in PostgreSQL implies that you are transacting them. While there might be some analytical benefit to having big and heavy point clouds in a database, all of the database overhead, including most importantly the requirement to push all of your i/o through the database stack's i/o infrastructure, ends up not being worth it. 

If your analytical workflow is constant reads of data, you will get better performance and flexibility by using some kind of clustered data storage approach like EPT, COPC, or even Arrow/Parquet.

**Comment by abellgithub** [comment]
> Additionally, did this bug get updated in a certain numbered release?

If you follow the link for the PR, you will see the version numbers.

**Comment by fivecheesetortellini** [comment]
Thanks very much for these comments! I updated versions and this bug was resolved for me.
