### ISSUE TITLE
JNI interface for readers.pgpointcloud

### ISSUE THREAD

**Issue by mghildiy** [PDAL/PDAL#4473]
Not a bug as such, just want some inputs.

I want to use pdal in my java program on windows platform, and hence I have to write jni based interface so that I can call pdal's functions.

I want to specifically call functionality in plugin readers.pgpointcloud.

I am going through [code](https://github.com/PDAL/PDAL/blob/master/plugins/pgpointcloud/io/PgReader.cpp). But I am not able to figure which function exactly I would need to write JNI interface for. 

Any lead would help.

**Comment by mghildiy** [comment]
Clicking on link gives me 'Page not found'.

**Comment by hobu** [comment]
https://pdal.io/en/latest/community.html
