### ISSUE TITLE
Question: LAS/LAZ data comparison between files

### ISSUE THREAD

**Issue by witt-ma** [PDAL/PDAL#4480]
Hey guys.

I am quite new to this whole topic and wanted to ask if, by any chance, it is possible to efficiently compare files with PDAL (or any other software you may know of)?

To elaborate on this (and why it's needed):
LAS/Z files are processed in-house, sent to the customer and sent back to us. During this step, there is a chance of altering data unintentionally, for whatever reason. Since all metadata and points have to be checked, this needs to be performed quite efficiently. I'd like to save the differences in some sort of text file, so the result is easily accessible and nicely viewable to the human eye (like .csv).

I've tried iterating the points in a multiprocessing manner in Python, but it turned out to be way too slow. Maybe this issue stems from having to convert every LASPY ScaleAwarePointRecord because of pickle problems. So I guess the only other option is to use Python / C / C++ directly to iterate over the raw data, which implies most likely a lot of work to get it going initially. Any hints in any direction are more than welcome.

Thanks in advance.
Greetings.

**Comment by hobu** [comment]
Please use the [PDAL mailing list](https://pdal.io/en/latest/community.html#mailing-list) for such questions.
