### ISSUE TITLE
filters.neighborclassifier not restricted to specific naming convention

### ISSUE THREAD

**Issue by NanBlanc** [PDAL/PDAL#4530]
**Feature request :** 
Making filters.neighborclassifier not restricted to a specific naming convention.

**Example :**
if the Classification field is named differently, like "class" instead of "Classification" : 

_ply file header_:
```
ply
format binary_little_endian 1.0
element vertex 2063489
property float64 x
property float64 y
property float64 z
property float64 intensity
property int32 class
end_header
```

Ideal behaviour (that currently does not work) : 
```
[
    "in.ply",
    {
        "type" : "filters.neighborclassifier",
        "domain" : "class[0:0]",
        "k" : 10
    },
    { 
        "type" : "writers.ply",
        "filename":"out.ply",
        "precision":"6",
    }
]
```

Current work around to match the intendend behaviour :
```
[
    "in.ply",
    {
        "type" : "filters.ferry",
        "dimensions" : "class=>Classification"
    },
    {
        "type" : "filters.neighborclassifier",
        "domain" : "Classification[0:0]",
        "k" : 10
    },
    {
        "type" : "filters.ferry",
        "dimensions" : "Classification=>class"
    },
    { 
        "type" : "writers.ply",
        "filename":"out.ply",
        "precision":"6",
        "dims":"x,y,z,intensity,class"
    }
]
```

**System infos**
```
$ pdal --version
2.7.1
```
**Related issues**
https://github.com/PDAL/PDAL/issues/2861
https://github.com/PDAL/PDAL/issues/3545

**Comment by abellgithub** [comment]
This really has nothing to do with the neighbor classifier filter.

You want the name `class` to be a synonym for the dimension `Classification`. I don't have strong feelings on this, but with PLY, it's trivial to edit the file and change the name of the text and you've noted another easy workaround, so I'm not sure this warrants a change.

Note that if you're building PDAL from source you can edit `Dimension.json` in whatever way you like to support your needs in this regard.

**Comment by NanBlanc** [comment]
it's trivial to edit the file and change the name of the text, yes. But in my case it is cumbersome given the size of my database.
 
My feature request and related issues cited are linked to my understanding of the filters.neighborclassifier : to be able to "KNN spread" any dimension, not only the classification. 
I think i miss interpreted that because of the need of mentionning the field name "Classification" in the attribute `"domain" : "Classification[1:1]"`. Something like `"domain" : "[1:1]"` would had made it more clear.

Thanks @hobu for the addition alt_name addition to future 2.9.0.

**Comment by abellgithub** [comment]
I'm unclear as to what the problem is. Rather than suggest a change, can you provide the error and incorrect behavior that you're seeing?

**Comment by NanBlanc** [comment]
Also maybe an idea to avoid confusions : 
add an explicit error if you try to apply filters.neighborclassifier on anything else than a classification.

In my case, having "class" name filed : i did first :
`pdal translate class.ply class_n.ply neighborclassifier --filters.neighborclassifier.domain="Classification[0:0]" --filters.neighborclassifier.k="10" --writers.ply.precision="6"`
which outputs `PDAL: filters.neighborclassifier: Invalid dimension name in 'domain' option: 'Classification'.`

So obviously i thought yeah i should use my field name "class" so i did : 
`pdal translate class.ply class_n.ply neighborclassifier --filters.neighborclassifier.domain="class[0:0]" --filters.neighborclassifier.k="10" --writers.ply.precision="6"`
PDAL was able to process without error but did not applied the filter as intended.

**Comment by abellgithub** [comment]
> So obviously i thought yeah i should use my field name "class" so i did :
pdal translate class.ply class_n.ply neighborclassifier --filters.neighborclassifier.domain="class[0:0]" --filters.neighborclassifier.k="10" --writers.ply.precision="6"
PDAL was able to process without error but did not applied the filter as intended.

The filtering applied by `domain` is unrelated to the classification/voting and the dimension in use there. It's simply a filter of points. You could choose any valid dimension for filtering.

The filter had half-complete support for selecting a dimension on which to apply the algorithm. #4535 completes this work. Before #4535 it only used Classification.
