### ISSUE TITLE
portable_popen swallows /'s on windows

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#4546]
[portable_popen](https://github.com/PDAL/PDAL/blob/master/pdal/util/Utils.cpp#L323) eats `/`'s on windows and swaps them all to `\\`. That's normally ok, but in the case of passing GDAL VSI paths like `/vsistdout` we definitely don't want the `/` swapped to a `\\`.

I'm not sure what to do. Should it be the responsibility of portable_popen to be doing the swapping unbeknownst to the caller at this point?

**Comment by abellgithub** [comment]
All of that slash swapping should be killed.

**Comment by hobu** [comment]
> All of that slash swapping should be killed.

🔪

**Comment by hobu** [comment]
Fixed by #4547
