### ISSUE TITLE
Points lost when where_merge is true and filter returns no points

### ISSUE THREAD

**Issue by tom-neara** [PDAL/PDAL#4572]
**Describe the bug**

In [StageRunner.cpp](https://github.com/PDAL/PDAL/blob/master/pdal/private/StageRunner.cpp#L63-L68) there's this code:
```
    if (m_stage->mergeMode() == Filter::WhereMergeMode::True)
    {
        if (m_viewSet.size())
            (*m_viewSet.begin())->append(*m_skips);
                return;
    }
```

At a glance this looks like the return is always executed after the call to `append`, but in reality it should be indented like this:
```
    if (m_stage->mergeMode() == Filter::WhereMergeMode::True)
    {
        if (m_viewSet.size())
            (*m_viewSet.begin())->append(*m_skips);
        return;
    }
```

Because of the way it is written, a `filters.outlier` with a `where` clause that matches 0 points and `"where_merge": true` will return an empty ViewSet, which will result in an empty view set being passed to all subsequent filters.

See the early return code in [filters.outlier](https://github.com/PDAL/PDAL/blob/master/filters/OutlierFilter.cpp#L159-L161):
```
    PointViewSet viewSet;
    if (!inView->size())
        return viewSet;
```

**Expected behavior**
I'm not sure if the bug is in filters.outlier or StageRunner.cpp

**Comment by tom-neara** [comment]
Looks like the braces were removed in https://github.com/PDAL/PDAL/commit/99bdf0efa4978c0eed5c1e4ab6616ad64d59013a so this is indeed a bug.

**Comment by tom-neara** [comment]
![Screenshot 2024-12-10 at 2 49 35 pm](https://github.com/user-attachments/assets/05eb0c95-43c5-44db-90c1-c8e44526a3c2)

**Comment by abellgithub** [comment]
While your analysis may be correct, without a reproducible test case, there's no way to know. 

Please create an issue that describes the pipeline or API use, the expected behavior, and the behavior that you're seeing that you believe to be wrong. Please include data to reproduce the issue.  Reference this issue if you like.

**Comment by hobu** [comment]
Can you please provide a pipeline with some example data that demonstrates this issue? I'm curious about what caused you to track this down. Something that could act as a test would be helpful moving forward to protect the previous behavior.

**Comment by tom-neara** [comment]
Run this pipeline on `pdal/test/data/las/100-points.las`. On master the output should have zero points. After reintroducing the braces in `StageRunner.cpp` the output should have 100 points.

```
[
  {
    "type": "readers.las"
  },
  {
    "type": "filters.outlier",
    "method": "radius",
    "radius": 7,
    "min_k": 1,
    "where": "Classification == 0",
    "where_merge": true
  },
  {
    "type": "writers.las"
  }
]
```

**Comment by tom-neara** [comment]
Thanks for fixing this so quickly!
