### ISSUE TITLE
Ability to add images to NITF/LAS files

### ISSUE THREAD

**Issue by mpgerlek** [PDAL/PDAL#476]
The lidar profile of the NITF format allows - indeed, requires! - an image segment containing an "intensity" or "elevation" image.

The API for the (nitro-based) NITF writer should allow for the user to pass in a filename of such an image.

Normally, the caller to the NITF writer would know the properties of the image (number bands, pixel width/height, file format, etc) and could therefore set the various IM subheader fields. That won't be the case here, since we only have a filename handle. Indeed, we won't even be able to output the file into the IM chunk unless we can express the raw pixels in a NITF-approved way.

So, to add this feature, we'd need to either restrict the input image by convention ("only JPGs, and pass the width/height as options) or we'd need to crack open the image with GDAL to get the image props and raw pixel values.

**Comment by abellgithub** [comment]
Lack of interest.
