### ISSUE TITLE
The PDAL dimension registry

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#481]
PDAL will advertise its fixed set of dimensions, as output in #480, as JSON. It would be useful to have a website to allow outside parties to submit their own entries to this list. They could then simply be added and hard-coded to the next PDAL release, or alternatively, scooped up by PDAL processing operations dynamically via JSON. 

This mechanism would allow people doing weird things with weird dimension names to at least advertise them to others (BPF, various LAS 1.4+ providers).

**Comment by abellgithub** [comment]
Addressed with 01d34a24d12a3a9e1da54e037bd6760985b50de9
