### ISSUE TITLE
AppVeyor PDAL build

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#499]
http://www.appveyor.com provides free builds for open source projects. It's much like Travis except for windows. One of the things that would make its use much easier is NuGet packages for all of the OSGeo4W64 items we are currently depedent on. 

This item is a long term hope, not a blocker on anything.

**Comment by chambbj** [comment]
Closed in #813 via 80524809c2a2d4eb68ff33ecd9e052a368a21f14

The initial AppVeyor setup actually uses the OSGeo4W64 installer to setup the dependencies. It should still be a long term goal to create NuGet packages for these, but this works for the time being.
