### ISSUE TITLE
Addressing the requiredness of upstream projects

### ISSUE THREAD

**Issue by mpgerlek** [PDAL/PDAL#523]
At codesprint today, we agreed that our build/configuration should be changed as follows:

(1) GDAL is required to build, and therefore the PDAL_HAVE_GDAL macro goes away

(2) XML2 is required to build, iff one of the three DBs is being used

(3) ZLIB is required to build, and therefore the PDAL_HAVE_ZLIB macro goes away

(4) (no change should be made to GEOS)

(5) DEMANGLER is a windows-only thing, so the #ifdef PDAL_HAVE_DEMANGLER should be replaced with a windows macro

(6) MSGPACK is no longer an upstream project - remove entirely from CMakeLists

(7) PDAL_SRS_ENABLED should go away: it will always be enabled

No changes have been made with regard to the following:
- Geotiff
- Laszip
- Hexer
- Python
- P2G
- Caris
- HDF5
- MrSID
- Oracle
- PCL_VISUALIZATION
- PCL
- Nitro
- Boost
- ICONV
- JsonCPP
- WebSocket++

---
_1, 4, and 7 are fixed_
_2, 3, 5, 6 are fixed_

**Comment by abellgithub** [comment]
Decided it's as done as it's going to get for now.
