### ISSUE TITLE
Greyhound reader options

### ISSUE THREAD

**Issue by connormanning** [PDAL/PDAL#527]
Greyhound Options should accept a `filename` to be consistent with other drivers, and that filename should be interpreted as a complete Greyhound URL *including* the pipeline ID selection.

The current `pipelineId` option should be made optional, so that the `uri` parameter can also be interpreted as a full Greyhound URL including pipeline ID if the `pipelineId` is omitted.

**Comment by abellgithub** [comment]
@connormanning: Is this still a thing?

**Comment by connormanning** [comment]
No.
