### ISSUE TITLE
LAS return number of '0' not handled

### ISSUE THREAD

**Issue by abellgithub** [PDAL/PDAL#617]
Though invalid, many LAS/LAZ files apparently use a return number of '0', though this value is invalid according to the specification.  The proposal is to coerce these values to 1 when read into PDAL.  A warning message will be printed when this transformation occurs.

**Comment by ahmadshabbir2468** [comment]
Hi , I am Facing same  Problem of Return Number '0' Can You Please Guide me ?
Q 1 )What Should i do if my data Contains Return number 0 .? Is there any way to bypass this issues and use features of PDAL or  i must have  to change  Change this Return 0 to return number 1?
Q 2) Is It Safe to change the Return Number '0' to Return number '1'

**Comment by abellgithub** [comment]
You don't need to do a thing. Ignore the message if you don't care that
your data contains a return number of 0.

On Aug 2, 2017 5:02 AM, "ahmadshabbir2468" <notifications@github.com> wrote:

Hi , I am Facing same Problem of Return Number '0' Can You Please Guide me ?
Q 1 )What Should i do if my data Contains Return number 0 .? Is there any
way to bypass this issues and use features of PDAL or i must have to change
Change this Return 0 to return number 1?
Q 2) Is It Safe to change the Return Number '0' to Return number '1'

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/PDAL/PDAL/issues/617#issuecomment-319613470>, or mute
the thread

**Comment by abellgithub** [comment]
> Q 1 )What Should i do if my data Contains Return number 0 .? Is there any
> way to bypass this issues and use features of PDAL or i must have to change
> Change this Return 0 to return number 1?

That's up to you.  It's your data.

> Q 2) Is It Safe to change the Return Number '0' to Return number '1'

Again, it's up to you.  It's your data.  If you want to change the 0's to 1's, you can use [filters.assign](https://www.pdal.io/stages/filters.assign.html)
