### ISSUE TITLE
Cannot register a new kernel plugin without modifying PDAL source

### ISSUE THREAD

**Issue by gadomski** [PDAL/PDAL#666]
@chambbj I talked to @hobu yesterday and he said to file a ticket on you re: kernel plugins. Basically, making a new kernel plugin still requires a bit of modification of the main PDAL source. Specifically, you have to register the kernel in [`apps/pdal.cpp`](https://github.com/gadomski/PDAL/compare/cpd#diff-c6d4c52005249f4ac1ec91f2aa024826R55).

Not necessarily a dealbreaker, but just thought I'd bring it up. Don't know if you've thought about this one, but I'd be happy to take a stab at a fix if you're booked.

**Comment by chambbj** [comment]
Closed by #672
