### ISSUE TITLE
Bounds.hpp needs to live under ./include/pdal

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#699]
External users of PDAL should only have to refer to a single include path, `{prefix}/include/pdal`, and everything should live off of that.

Anything else ends up being miserable for outside developers (multiple include paths?!?) and can get screwed up by package managers who make choices when given the option to do so (we'll stuff all PDAL-related things in our own special prefix then).

I propose:

`./include/pdal/`
`./include/pdal/util`
`./include/pdal/third`

**Comment by abellgithub** [comment]
I think this can be closed.  After much discussion we moved several files to include/pdal/util and expect users to explicitly reference them using {prefix}/pdal/util/<filename> in code.
