### ISSUE TITLE
Properly install app bundles

### ISSUE THREAD

**Issue by chambbj** [PDAL/PDAL#710]

**Comment by hobu** [comment]
Is this in #711 dead now?

**Comment by chambbj** [comment]
No, this is for me. PCL installs the app bundles in /usr/local/opt I think, and maybe they are available via Applications. Don't quite remember, but right now pdal.app isn't installed at all.

**Comment by chambbj** [comment]
After taking a closer look, application bundles are installed. I'm still not sure we are using them quite right (e.g., plugins can be part of the bundle). CMake BundleUtilities may also play into the eventual solution here.

Closing this for now. May reopen with a better description at a later date.
