### ISSUE TITLE
`pdal info --summary` and `pdal info --schema` both return different dimension information

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#715]
`pdal info --summary` and `pdal info --schema` both return lists of dimensions, but the former simply returns names and the later returns an array of dim objects. The LasReader::inspect() method makes up a list of dimensions, but then passes in the names of those to QuickInfo

I would like to propose that QuickInfo have `std::vector<Dimension> m_dims` instead of m_dimNames.

**Comment by abellgithub** [comment]
What do you want to accomplish by this?

**Comment by hobu** [comment]
parity.

**Comment by abellgithub** [comment]
?  I don't understand.  If they're going to provide the same information, why have them both?

To me, the summary option was just file-perspective information and had nothing to do with PDAL.  The schema option provided PDAL-centric information, though I'm still not sure how useful it is.  I still don't see any great reason to expose the schema to end users.

**Comment by strk** [comment]
I'd like a flavour of "info" that doesn't take reading in the whole file. Is that available ?

**Comment by hobu** [comment]
I think `pdal info myfile.las --summary` is what you want.

--schema has to read the data because not all drivers know their dimensions until they compute stuff.

**Comment by strk** [comment]
On Tue, Mar 17, 2015 at 02:08:24PM -0700, Howard Butler wrote:
> I think `pdal info myfile.las --summary` is what you want.

It still takes more than just reading an header:

 $ time pdal info data.las --summary > /dev/null
 data.las: Found invalid value of '0' for point's return number.
 data.las: Found invalid value of '0' for point's number of returns.
 real    0m16.820s
 user    0m16.370s
 sys     0m0.136s

For comparison:

 $ time strings data.las | wc
  817059  849989 4477854
 real    0m1.675s
 user    0m1.694s
 sys     0m0.063s

The file size is 230,490,095 bytes.
