### ISSUE TITLE
Tutorial needs

### ISSUE THREAD

**Issue by chambbj** [PDAL/PDAL#724]
* Using PDAL in your own project
* ~~Architectural overview~~
* ~~Reading with PDAL~~
* ~~Writing with PDAL (explicit)~~
* Writing with PDAL (pipeline manager)
* ~~Filtering with PCL~~
* ~~Bare earth filtering with PMF~~
* Creating a DSM using PMF and P2G
* Creating a DTM using P2G
* Writing a reader driver/plugin
* Writing a writer driver/plugin
* Writing a filter driver/plugin
* Writing a kernel driver/plugin

**Comment by hobu** [comment]
Many of these are now done and available at http://pdal.io
