### ISSUE TITLE
Test for pgpointcloud fails

### ISSUE THREAD

**Issue by strk** [PDAL/PDAL#742]
It looks like the "pgpointcloudtest" script requires a database being created before running "make test", or it fails:
{{{
bin/pgpointcloudtest 
Running main() from gtest_main.cc
[==========] Running 2 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 2 tests from PgpointcloudWriterTest
[ RUN      ] PgpointcloudWriterTest.testWrite
unknown file: Failure
C++ exception with description "FATAL:  database "pdal_test_tmp" does not exist
" thrown in the test body.
[  FAILED  ] PgpointcloudWriterTest.testWrite (9 ms)
[ RUN      ] PgpointcloudWriterTest.testNoPointcloudExtension
unknown file: Failure
C++ exception with description "Not connected to test database for testing!" thrown in the test body.
[  FAILED  ] PgpointcloudWriterTest.testNoPointcloudExtension (3 ms)
[----------] 2 tests from PgpointcloudWriterTest (12 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 1 test case ran. (12 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] PgpointcloudWriterTest.testWrite
[  FAILED  ] PgpointcloudWriterTest.testNoPointcloudExtension

 2 FAILED TESTS
}}}

So I created the database and tried again, but it still failed:
{{{
[strk@cdb:/usr/src/pointcloud/pdal/pdal/b(master)] psql -c "select pc_version()" pdal_test_tmp
 pc_version 
------------
 1.0.0
(1 row)

[strk@cdb:/usr/src/pointcloud/pdal/pdal/b(master)] bin/pgpointcloudtest 
Running main() from gtest_main.cc
[==========] Running 2 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 2 tests from PgpointcloudWriterTest
[ RUN      ] PgpointcloudWriterTest.testWrite
unknown file: Failure
C++ exception with description "FATAL:  database "pdal_test_tmp" does not exist
" thrown in the test body.
[  FAILED  ] PgpointcloudWriterTest.testWrite (10 ms)
[ RUN      ] PgpointcloudWriterTest.testNoPointcloudExtension
unknown file: Failure
C++ exception with description "Not connected to test database for testing!" thrown in the test body.
[  FAILED  ] PgpointcloudWriterTest.testNoPointcloudExtension (3 ms)
[----------] 2 tests from PgpointcloudWriterTest (13 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 1 test case ran. (13 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] PgpointcloudWriterTest.testWrite
[  FAILED  ] PgpointcloudWriterTest.testNoPointcloudExtension

 2 FAILED TESTS
}}}

Can it be the test is not honouring the libpq environment variables ? I have a few set:
{{{
PGPORT=5493
PGHOST=/tmp
PGDATA=/home/postgresql-9.3/data
}}}

**Comment by alexsmartens** [comment]
Hi there,
I am also having pgpointcloud test failing:

```
$ env CTEST_OUTPUT_ON_FAILURE=1 make test
Running tests...
Test project /home/alex/Downloads/PDAL-1.5.0-src/build
      Start  1: pgpointcloudtest
 1/71 Test  #1: pgpointcloudtest ......................***Failed    0.02 sec
[==========] Running 5 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 5 tests from PgpointcloudWriterTest
[ RUN      ] PgpointcloudWriterTest.write
unknown file: Failure
C++ exception with description "could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
" thrown in SetUp().
[  FAILED  ] PgpointcloudWriterTest.write (1 ms)
[ RUN      ] PgpointcloudWriterTest.writeScaled
unknown file: Failure
C++ exception with description "could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
" thrown in SetUp().
[  FAILED  ] PgpointcloudWriterTest.writeScaled (0 ms)
[ RUN      ] PgpointcloudWriterTest.writeXYZ
unknown file: Failure
C++ exception with description "could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
" thrown in SetUp().
[  FAILED  ] PgpointcloudWriterTest.writeXYZ (0 ms)
[ RUN      ] PgpointcloudWriterTest.writetNoPointcloudExtension
unknown file: Failure
C++ exception with description "could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
" thrown in SetUp().
[  FAILED  ] PgpointcloudWriterTest.writetNoPointcloudExtension (0 ms)
[ RUN      ] PgpointcloudWriterTest.writeDeleteTable
unknown file: Failure
C++ exception with description "could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
" thrown in SetUp().
[  FAILED  ] PgpointcloudWriterTest.writeDeleteTable (0 ms)
[----------] 5 tests from PgpointcloudWriterTest (1 ms total)

[----------] Global test environment tear-down
[==========] 5 tests from 1 test case ran. (1 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 5 tests, listed below:
[  FAILED  ] PgpointcloudWriterTest.write
[  FAILED  ] PgpointcloudWriterTest.writeScaled
[  FAILED  ] PgpointcloudWriterTest.writeXYZ
[  FAILED  ] PgpointcloudWriterTest.writetNoPointcloudExtension
[  FAILED  ] PgpointcloudWriterTest.writeDeleteTable

 5 FAILED TESTS

...

99% tests passed, 1 tests failed out of 71

Total Test time (real) =  33.39 sec

The following tests FAILED:
	  1 - pgpointcloudtest (Failed)
Errors while running CTest
Makefile:61: recipe for target 'test' failed
make: *** [test] Error 8

```

Can someone help to fix this, please

**Comment by strk** [comment]
> C++ exception with description "could not connect to server: No such file or directory
> 	Is the server running locally and accepting
> 	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
> " thrown in SetUp().

The message seems clear to me:  you need a running PostgreSQL server
to run tests. Use libpq env variables if your server is running in a
non-standard location.

**Comment by abellgithub** [comment]
If you're not running a Postgres server, you can turn the tests off in CMakeCache.txt by setting BUILD_PGPOINTCLOUD_TESTS:BOOL=OFF

**Comment by elemoine** [comment]
This is what I've used for building the pgpointcloud plugin and running the pgpointcloud tests:

```shell
$ cmake -DBUILD_PLUGIN_PGPOINTCLOUD=ON ..
$ make
$ PGUSER=pdal PGPASSWORD=password PGHOST=localhost PGPORT=5432 make test
```

**Comment by alexsmartens** [comment]
All clear,
thank you
