### ISSUE TITLE
Database drivers need way to specify output dimensions

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#745]
There's no way to do what `filters.selector` used to do which was to limit which dimensions were ultimately written out into the flexible format drivers like Oracle or pgpointcloud. We need that added back as an option to the writer (just a simple list?).

**Comment by abellgithub** [comment]
Do we want to require X, Y and Z?

**Comment by hobu** [comment]
That seems reasonable to me.

**Comment by abellgithub** [comment]
Fixed with 26de271c8ffcdb3b4d5dc3bf84550adc1cea45d7

Ended up not requiring any particular dimensions.  DB drivers that require dimensions will check this.
