### ISSUE TITLE
pdal.io not available

### ISSUE THREAD

**Issue by walkermatt** [PDAL/PDAL#757]
Just noticed that the pdal.io website isn't available at the moment due to "a misconfigured custom domain".

Cheers,

Matt.

**Comment by hobu** [comment]
Thanks for the report. It redirects fine for me at the moment, but http://www.downforeveryoneorjustme.com/pdal.io isn't happy either. I'll look into it.

**Comment by hobu** [comment]
This is related to github's DNS change from quite a while ago that I never caught up with.

**Comment by walkermatt** [comment]
The error page I see is:

> Site Disabled
> 
> Oh no! It looks like this Pages site has been disabled due to a misconfigured custom domain.
> 
> Are you the site owner? You can quickly fix this issue by updating the DNS record for your Pages site:
> 
> If you're using a subdomain (coolthing.example.com, www.example.com, etc.), make sure you have a CNAME record that points to your-username.github.io.
> If you're not using a subdomain (example.com), make sure you have two A records set to the following IPs: 192.30.252.153 and 192.30.252.154
> More detailed instructions for setting up a custom domain with GitHub pages are also available if you need more guidance.
> 
> You can find more information about these changes in our GitHub Pages legacy IP deprecation blog post. If you have any questions, please contact support.

**Comment by hobu** [comment]
DNS propagating and hopefully this is up soon.  www.pdal.io should work right now without waiting if you need it.

**Comment by hobu** [comment]
I had of course botched the DNS. Confirmed that it's good now 

http://downforeveryoneorjustme.com/pdal.io
