### ISSUE TITLE
p2g Radius confusion

### ISSUE THREAD

**Issue by matthewhanson** [PDAL/PDAL#765]
I finally figured out the problem with the radius parameter that is given to the p2g plugin.   I had posted a message to the list but it seemed more of a points2grid issue.  I emailed them but to no avail. So after some digging...

It's more of an issue with PDAL.    There's nothing wrong with points2grid on it's own.  The main class there is the Interpolation class, which creates an OutCoreInterp instance.   The confusion I believe arises from the fact that Interpolation takes in "radius" which is the radius of the search area, but immediately passes it to OutCoreInterp as "radius*radius"...So OutCoreInterp actually stores "radius_sqr", more efficient to do the calculation if within distance as it avoids a sqrt calc for every point.

However, the parameter in PDAL is called "radius" and is passed to OutCoreInterp as is, without squaring it.    Thus, I was finding my point density image higher than expected because I was passing in what I thought was a radius of say, 0.5 (with grid size of 1.0) but it was actually a radius of ~0.7...a circle with area greater than the area of the pixel.

The simplest fix to this is to call the parameter in writers.p2g "radius_sqr"...but honestly it's not very intuitive to think of a search radius in terms of the square of what you really want.

So instead I would propose that the parameter is squared when creating the OutCoreInterp instance in the p2g plugin, and leaving the parameter really as the radius.

I will issue a PR.

**Comment by hobu** [comment]
Sounds great. Thanks for blazing the trail.
