### ISSUE TITLE
Should Charbuf be included as public header?

### ISSUE THREAD

**Issue by chambbj** [PDAL/PDAL#777]
`Charbuf` is currently only used by the BPF drivers. Its header can be safely relocated to `./src` or perhaps even `./io/bpf` to reduce the size of the public interface, unless we feel others will need access (Greyhound?). Thoughts?

**Comment by abellgithub** [comment]
Move to util would be my vote.  Along with istream, ostream, extractor, inserter

**Comment by chambbj** [comment]
Closed by #780
