### ISSUE TITLE
Option in BPF writer to write identity matrix

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#781]
QT modeler doesn't quite apply the scaling correctly in certain situations, and it would be useful to just hammer the transformation matrix to an identity matrix for debugging purposes.

**Comment by chambbj** [comment]
I'm told that QT and the BPF plugin should be fine with non-identity transform matrix. The catch is that the transformation matrix is not documented properly (this should be fixed with the draft spec that is under review). Transposing the matrix should fix this problem.

**Comment by abellgithub** [comment]
Well, not sure I buy this, because the transpose is the same for a symmetric matrix, which is what we were writing, but at this point I'm generally confused, so I'll withhold further judgment until I'm less confused.

**Comment by abellgithub** [comment]
I'm thinking that we can close this and suggest something in the documentations about using a scaling filter for the time being along with some explanation of what's going on.

**Comment by hobu** [comment]
scaling filter doesn't exist in master. We will want some mechanism to override the matrix. Maybe we could use `filters.transform` in some way to set and advertise the matrix and then an option on the writer to:

1. say whether or not to write a custom matrix from `filters.transform` 
2. set an identity matrix

**Comment by abellgithub** [comment]
The identity is set by default if the none of the scale_x|y|z options are set.  I'll put something in the docs to say that you shouldn't set these if you want to be sure to be readable by Qt.
