### ISSUE TITLE
PDAL LAS => TXT conversion

### ISSUE THREAD

**Issue by lyaunzbe** [PDAL/PDAL#785]
Hello! I had a question regarding using PDAL to convert a binary point cloud format to an ASCII format. I am always able to convert something like [this](https://github.com/PDAL/PDAL/blob/master/test/data/las/interesting.las) into ASCII format, using a command like `pdal translate interesting.las interesting.txt`. This works fine and I am able to visualize the ascii pointcloud just fine. However, PDAL is no longer able to work with this ASCII pointcloud it generates. For example, if I wanted to convert the text file to PCD or if I even just want to run `pdal info`, I recieve the following error:

`PDAL: Cannot determine input file type of interesting.txt`

Any help would be greatly appreciated, thank you!

**Comment by abellgithub** [comment]
Unfortunately PDAL has a writer for text files, but not a reader.  This explains the behavior you're seeing.  You're welcome to write one and contribute.  It's on the list of todos, but I'm not sure about priority.

**Comment by lyaunzbe** [comment]
Wow, thank you for such a quick response! That definitely makes sense though and I can probably work around it w/ LASTools.

Another small question/clarification if you don't mind (feel free to tell me to open a new, separate issue for it, if that's better). When I try to convert a LAS file (my own) to the PCD format, I get the following error message: `PDAL: Unable to fetch data and convert as requested: Red:uint16_t(26112) -> unsigned char`
I know that the RGB values in this LAS are 16bit, so should I downsample them to 8bit, so that they are in the 0-255 range? Is that what this error is complaining about?

Once again, thank you very much for your assistance, I really appreciate it!

**Comment by abellgithub** [comment]
Yes, you're correct.  If the LAS file contained only values that could be represented in 8 bits (despite the size of the datatype being 16 bits), things would be fine, but in this case the value is larger than 255.  PDAL doesn't attempt to downsample and leaves that to you.  There are fairly simple things that can be done.  You can create a filter that does the downsampling inline.  It's pretty simple with Python in the programmable filter (http://www.pdal.io/stages/filters.programmable.html).  If you need help, I'll be happy to give it a whirl in the AM.

**Comment by lyaunzbe** [comment]
Got it, that seems straightforward enough. Really appreciate the guidance, thank you!

**Comment by pbach3** [comment]
Hello! I have been working through the same issue with my outcome being PCD files instead of TXT. I am very new to PDAL as well as programming in general. Would there be a simple line I can add to my JSON pipeline file to filter uint16 to uint8? My current thought is to find a way to divide the input LAS by 65,535 then multiply by 255. However, not sure how I should implement this with my shallow knowledge. Thank You.

**Comment by chris-andrasick** [comment]
Hi, so this python filter seems to work: 
import numpy as np

def convert(ins, outs):
    r = ins["Red"]
    g = ins["Green"]
    b = ins["Blue"]
    r = r >> 8
    g = g >> 8
    b = b >> 8
    outs["Red"] = r
    outs["Green"] = g
    outs['Blue'] = b
    return True

then execute from the command line like this: 
pdal translate <input>.las <output>.pcd -f filters.python --filters.python.script="<script_name>.py" --filters.python.function="convert"
