### ISSUE TITLE
PDAL PCL command not recognized

### ISSUE THREAD

**Issue by lyaunzbe** [PDAL/PDAL#788]
Hey guys! I've installed PDAL, manually, but I've run each of the sh scripts listed in the vagrant file. For some reason, it seems that the pcl command is recognized. However, when I run `pdal --drivers`, filters.pclblock does show up. Will I able to use PCL through the pdal pipeline command at least? Any ideas why the pcl command is not recognized?

Thank you!

**Comment by lyaunzbe** [comment]
I've also noticed that the pdal.sh install script referenced in the vagrantfile checks out the laz-perf-vagrant branch (last updated jan 10th), could that be the issue?

**Comment by lyaunzbe** [comment]
So, I tried rebuilding PDAL and noticed the following.  The PCL plugin is enabled when I build pdal:
![screen shot 2015-03-05 at 2 19 20 pm](https://cloud.githubusercontent.com/assets/28675/6515936/194f0762-c343-11e4-93e9-959f51d7a9ad.png)
Yet, during the actual build steps, the kernels for pcl, ground, etc, are not built:
![screen shot 2015-03-05 at 2 21 57 pm](https://cloud.githubusercontent.com/assets/28675/6515958/3d8d2014-c343-11e4-98f2-481614660497.png)

**Comment by chambbj** [comment]
Sounds like perhaps PDAL can't find any of the "plugins." Have you set `PDAL_DRIVER_PATH` to point to the plugins? PDAL will guess some common locations (e.g., `/usr/local/lib`), but anything else and you are on your own and will need to set the path.

**Comment by chambbj** [comment]
Do you see any of the plugin libs in the lib directory under your build directory? For example, `libpdal_plugin_kernel_pcl.dylib`.

**Comment by lyaunzbe** [comment]
Super helpful! Setting the PDAL_DRIVER_PATH worked and built all the plugin kernels that were missing before (pcl, ground, etc). Thanks again, I really appreciate how responsive and helpful the entire PDAL group is :+1:

**Comment by lyaunzbe** [comment]
Sorry, one more weird issue I'm running into. For some odd reason, the ground/pcl commands only show up if I call pdal from within /usr/, /usr/bin or the build directory. Could this be a side effect of building PDAL multiple times?

Running pdal in ~/
![screen shot 2015-03-05 at 3 14 15 pm](https://cloud.githubusercontent.com/assets/28675/6516854/61eb0bb8-c34a-11e4-954a-0fd58d6536c8.png)

Running pdal in /usr
![screen shot 2015-03-05 at 3 14 33 pm](https://cloud.githubusercontent.com/assets/28675/6516860/72d7ed4c-c34a-11e4-9ba0-5ae3abbf6f14.png)

**Comment by hobu** [comment]
I would guess cmake rpath settings are at fault in some way.

**Comment by chambbj** [comment]
I'm still not an rpath expert. I was wondering if pdal got build multiple times, once with PCL enabled, once without.

**Comment by hobu** [comment]
Also possible. We are supposed to only be doing rpath stuff when doing OSX, but maybe that's not set correctly. Travis is happy right now, but I don't know if we've ever tested "installed" situations.

**Comment by lyaunzbe** [comment]
To be clear, I'm building on Ubuntu 14.04. I'm rebuilding on a new, fresh, clean instance, so I'll let you guys know how that goes.

**Comment by lyaunzbe** [comment]
Just finished building on a clean, new instance and still having the same issue (can only see pcl/ground commands when I run `pdal` in /usr/bin/ or ~/pdal/build/). It's odd, because from the build process, it does look like the libraries are getting linked:

![screen shot 2015-03-05 at 3 14 33 pm](https://cloud.githubusercontent.com/assets/28675/6518880/50844c42-c361-11e4-997e-ca9ad271c135.png)

@chambbj: Where exactly should I specify `PDAL_DRIVER_PATH`? I'm using the following script to install PDAL: https://github.com/PDAL/PDAL/blob/master/scripts/linux-install-scripts/pdal_install.sh. Would I just add a line like DPDAL_DRIVER_PATH=path_to_plugins ? Would path_to_plugins just be this: https://github.com/PDAL/PDAL/tree/master/plugins (relative to my own, cloned repo on the system of course)

**Comment by lyaunzbe** [comment]
Also, I can see all the plugin .so files (libpdal_plugin_kernel_pcl.so, libpdal_plugin_kernel_ground.so, etc) in the /usr/lib directory.

**Comment by chambbj** [comment]
@lyaunzbe I wasn't aware you were on linux at the time. The .so files are fine.

If you are installing to `/usr`, then `/usr/lib` is your `PDAL_DRIVER_PATH`. Just type:

    export PDAL_DRIVER_PATH=/usr/lib

As for the missing commands, I'm still at a loss. Hopefully, getting the driver path set correctly will mostly clear things up for you. If this continues to be a problem, let me know, and I can dig into it a little more/try to replicate.

**Comment by lyaunzbe** [comment]
@chambbj Ahhhhhh, now it is all clear. And setting the driver path exposed all the command globally as needed.

Thank you both again for all your help!!

**Comment by remuslupin** [comment]
Hi, I am new to PDAL. I installed it via OSGeo4W64 and also installed the RECOMMENDED dependancies.
but when I use pdal --drivers, I am not able to see filters.pclblock. would you please help me with this?

**Comment by abellgithub** [comment]
Sorry, but the OSGEO PDAL build doesn't contain support for PCL.

**Comment by remuslupin** [comment]
will OSGEO support PCL in the future?

**Comment by chambbj** [comment]
I'll let @hobu answer future OSGeo4W support questions. Unless you are
locked in to using OSGeo4W, there may be some other options for you. I'm
going to push a doc update this evening that details how to get up and
running on Windows (with PCL support) using Conda. If you are already a
Conda user, you can find PDAL on the conda-forge channel. If you are not,
then the docs should explain everything.

**Comment by chambbj** [comment]
@remuslupin The Conda portion is now documented at https://pdal.io/download.html#conda if this solution is of interest to you.
