### ISSUE TITLE
No std::isnan in MSVC2012

### ISSUE THREAD

**Issue by chambbj** [PDAL/PDAL#792]
In RangeFilter.cpp

**Comment by connormanning** [comment]
I was just discussing a similar issue for `isfinite` compatibility yesterday.  Maybe this will be useful when creating your fix:

```
#if defined(_MSC_VER) && _MSC_VER >= 1200 // VC++ 6.0 and above
#include <float.h>
#define isnan _isnan
#else
#define isnan std::isnan
#endif
```

**Comment by abellgithub** [comment]
That seems like a backwards fix to me.  Why not just:

#ifdef windows
namespace std
{
   bool isnan(...)
       { return _isnan(...); }
}
#endif 

That way what's in the code isn't our custom stuff and when MSVC is with the program, we just remove the specially-defined functions.

**Comment by connormanning** [comment]
My code was not intended as a drop-in fix - just an example of the native MSVC function you could defer to and what MSVC version it could be expected to handle, to be integrated in whatever way PDAL traditionally handles this type of override.
