### ISSUE TITLE
PDAL Programmable Filter Example Failing

### ISSUE THREAD

**Issue by lyaunzbe** [PDAL/PDAL#805]
Hey guys! I've been trying to work with the programmable filter and, as preliminary step, I've been attempting to run the example listed, exactly as it is written here: 
http://www.pdal.io/stages/filters.programmable.html

I get the following error:
`PDAL: Options::getOption: Required option 'filename' was not found on this stage`

Here is what my xml file looks like:
```
<?xml version="1.0" encoding="utf-8"?>
<Pipeline version="1.0">
  <Writer type="writers.las">
    <Option name="filename">mihama5gcp_test.laz</Option>
    <Option name="compression">true</Option>
    <Filter type="filters.programmable">
      <Option name="script">multiply_z.py</Option>
      <Option name="function">multiply_z</Option>
      <Option name="module">anything</Option>
      <Reader type="readers.las">
        <Option name="filename">mihama5gcp.las</Option>
      </Reader>
    </Filter>
  </Writer>
</Pipeline>
```

For further comparison, I have successfully been able to run the following pipeline using the decimation filter:
```
<?xml version="1.0" encoding="utf-8"?>
<Pipeline version="1.0">
  <Writer type="writers.las">
    <Option name="filename">mihama5gcp_sub.laz</Option>
    <Option name="compression">true</Option>
    <Filter type="filters.decimation">
      <Option name="step">20</Option>
      <Reader type="readers.las">
          <Option name="filename">mihama5gcp.laz</Option>
      </Reader>
    </Filter>
  </Writer>
</Pipeline>
```

Any ideas on what I'm doing incorrectly? Thank you!

**Comment by lyaunzbe** [comment]
Looking into the ProgrammableFilter code itself, it seems like there is a bit of a disconnect between the documentation and the actual required arguments for this filter. It seems that even though the docs ask for a `script` option and the code adds that as a default, the filter actually wants a `filename` option instead?

https://github.com/PDAL/PDAL/blob/945f4d62aee36b176e3af362b8254174d730ea9b/plugins/python/filters/ProgrammableFilter.cpp#L68

**Comment by lyaunzbe** [comment]
After some testing, it does indeed seem that the `filename` option should be used in lieu of the `script` option referenced in the docs. I will make a pull request correcting this in the documentation, if nobody is opposed.

**Comment by abellgithub** [comment]
@hobu: Do you care about which name is used for the option?  Makes no difference to me.

**Comment by hobu** [comment]
It should be put back to `script` for both `filters.programmable` and `filters.predicate`.
