### ISSUE TITLE
OCI reader producing empty files

### ISSUE THREAD

**Issue by oscarmartinezrubi** [PDAL/PDAL#811]
I tried the examples in 
test/data/oracle/write.xml
test/data/oracle/read.xml

with the data in

/home/oscar/sw/PDAL-trunk/test/data/autzen/autzen-dd.las

and the produced file by pdal pipeline read.xml is empy

I tested this with current development PDAL 

Thanks!

**Comment by abellgithub** [comment]
@hobu: Did we resolve this?  Can we put a note here saying what we did if so and close?

**Comment by hobu** [comment]
Yes this can be closed.

**Comment by oscarmartinezrubi** [comment]
I tried with current version an even though the OCI test passes when I use the OCI reader with same commands that in the OCI test for creation of tables in loading and the query for the reader still get empty files.

**Comment by hobu** [comment]
@oscarmartinezrubi Can you please test master again? @abellgithub fixed up a number of issues that may have cured this problem for you.

**Comment by oscarmartinezrubi** [comment]
I tested and it is working indeed! Thanks a lot!
BTW, my very first test with it reported that the crop method of PDAL returns less points than the equivalent CLIP_PC but I will test it further next days and tell you more :+1 :)

I used a XML like these one just in case you want to use it as example...

<?xml version="1.0" encoding="utf-8"?>
<Pipeline version="1.0">
  <Writer type="writers.las">
    <Option name="filename">outputfile.las</Option>
    <Filter type="filters.crop">
        <Option name="polygon">POLYGON ((85670.0 446469.0, 85670.0 446416.0, 85721.0 446416.0, 85721.0 446469.0, 85670.0 446469.0))</Option>
        <Reader type="readers.oci">
          <Option name="query">
SELECT l."OBJ_ID", l."BLK_ID", l."BLK_EXTENT",
       l."BLK_DOMAIN", l."PCBLK_MIN_RES",
       l."PCBLK_MAX_RES", l."NUM_POINTS",
       l."NUM_UNSORTED_POINTS", l."PT_SORT_DIM",
       l."POINTS", b.cloud
FROM SIMPLE_BLOCKS l, SIMPLE_CLOUD b
WHERE 
    l.obj_id = b.id
    AND
    SDO_FILTER(l.blk_extent,SDO_GEOMETRY('POLYGON ((85670.0 446469.0, 85670.0 446416.0, 85721.0 446416.0, 85721.0 446469.0, 85670.0 446469.0))', 28992)) = 'TRUE'
          </Option>
          <Option name="connection">test2/test2@pctest</Option>
          <Option name="populate_pointsourceid">false</Option>
          <Option name="spatialreference">EPSG:28992</Option>
        </Reader>
    </Filter>
  </Writer>
</Pipeline>

**Comment by hobu** [comment]
> BTW, my very first test with it reported that the crop method of PDAL returns less points than the equivalent CLIP_PC but I will test it further next days and tell you more :+1 :)

As far as I know, we've never tested that.

**Comment by hobu** [comment]
CLIP_PC is an Oracle query that essentially does a crop of a point set.

**Comment by oscarmartinezrubi** [comment]
I know that ;). My point was that using clippc with the same polygon used
in pdal crop returns more points. Later this week i will send another
message with the test that proves that ;)
