### ISSUE TITLE
CMake error when trying to open file: /usr/local/bin/laszip/laszip.hpp for reading.

### ISSUE THREAD

**Issue by strk** [PDAL/PDAL#820]
Configuration fails after manually installing LASTools:
``
CMake Error at cmake/modules/FindLASzip.cmake:62 (FILE):
  file Internal CMake error when trying to open file:
  /usr/local/bin/laszip/laszip.hpp for reading.
Call Stack (most recent call first):
  cmake/laszip.cmake:8 (find_package)
  CMakeLists.txt:202 (include)

CMake Error at cmake/modules/FindLASzip.cmake:87 (MESSAGE):
  Failed to open /usr/local/bin/laszip/laszip.hpp file
Call Stack (most recent call first):
  cmake/laszip.cmake:8 (find_package)
  CMakeLists.txt:202 (include)
``

I think this started happening after manually copying LASTools binaries under /usr/local/bin.

**Comment by strk** [comment]
I confirm that removing /usr/local/bin/las* fixes the configuration

**Comment by strk** [comment]
For the record, the successful build (with /usr/local/bin/las* removed) is still able to read LAS files.

**Comment by gadomski** [comment]
@strk when you have the broken setup, what's the content of `/usr/local/bin/laszip/laszip.hpp`? Also, can you get around the problem by manually setting `LASZIP_INCLUDE_DIR` and `LASZIP_LIBRARY` in your cmake configuration?

I think it's strange that cmake is trying to use a header file installed under `/usr/local/bin` — that's a non-standard location for an include file.

**Comment by strk** [comment]
First of all how to reproduce the broken setup:
```
cd LAStools/bin
sudo cp las2las las2txt lasdiff lasinfo lasindex lasmerge lasprecision laszip txt2las /usr/local/bin/
```

Then, laszip is a file, not a directory:
```
[strk@cdb:/usr/src/pointcloud/lastools/LAStools/bin(master)] ls -l /usr/local/bin/laszip
-rwxr-xr-x 1 root root 1043650 Mar 16 15:41 /usr/local/bin/laszip
```

But evidently FindLASzip.cmake is in confusion

**Comment by gadomski** [comment]
Thanks. I now can reproduce the original bug report:

```bash
$ ln -s ~/Repos/LAStools/bin/laszip /usr/local/bin/laszip
$ # do a fresh run of PDAL's cmake
```

This breaks PDAL's FindLASzip as reported. I'll look into a way to stop `find_path` from looking in `/usr/local/bin` (and other `**/bin/`s).
