### ISSUE TITLE
PDAL segfaults with error in lanczos_initializer

### ISSUE THREAD

**Issue by abellgithub** [PDAL/PDAL#829]
The boost math people changed the way that lanczos values were initialized between C++03 and C++11, making an application that is linked with both C++03 libraries and C++11 libraries both using the boost::math stuff crash.  You can detect this problem by looking at the symbol that causes the crash and seeing that the attributes are inconsistent.  This problem is only notable at this time on Ubuntu 12.04 & 14.04.

Opening this ticket mostly to provide a trail.  Not sure whether it is worth fixing, because it's not easy and should go away over time.

If you run into this, make sure you build your libraries that use boost::math with "-std=c++11" or the like.   The usual offender in this with respect to PDAL is PCL, which doesn't build with C++11 by default.

boost::math::lanczos::lanczos_initializer<boost::math::lanczos::lanczos17m64, long double>::init::init() (lanczos.hpp:49)

**Comment by strk** [comment]
For the record, this was also reported in #826 which confirms building PCL with C++11 fixes the issue.
