### ISSUE TITLE
trivial parallelization

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#832]
It would be really handy to be able to do some stuff like the following:

```
pdal translate laz-directory/*.laz output-directory/ -j 10 --t_srs EPSG:26915
```

```
pdal boundary laz-directory/* output-directory -j 10
```

```
pdal ground laz-directory/* output-directory/ -j 4
```

```
pdal info laz-directory/*.laz output-directory -j 10
```

**Comment by msmitherdc** [comment]
would just just be sucking in gnu parallel? can easily be done in *nix with xargs.

**Comment by hobu** [comment]
I didn't have an implementation in mind, I was just expressing a desire.

**Comment by msmitherdc** [comment]
`ls *.laz | xargs -I{} -P10 pdal translate --t_srs EPSG:26915 {}  newdir/{}`

**Comment by hobu** [comment]
nevermind then :smile:
