### ISSUE TITLE
Add p2g options for user-defined grid

### ISSUE THREAD

**Issue by matthewhanson** [PDAL/PDAL#843]
The option to specify a grid is now in points2grid, however the p2g PDAL plugin should be able to pass along these options to it.    Grid size is already passed in so it would need   minx, miny, and then either maxx, maxy OR xsize, ysize (in pixels)

**Comment by gadomski** [comment]
@matthewhanson I've started work on this issue over at https://github.com/gadomski/PDAL/tree/issues/843-p2g-user-defined-grid. However, I don't completely trust how points2grid is handling those user-specified bounds, so I'm going to dig into things over there and verify things are working the way that I want/expect. However, the branch *should* be testable, so feel free to check it out and give it a spin. All you need to do is provide the p2g writer a `bounds` option, e.g.:

```xml
<Option name="bounds">([0, 1], [2, 3])</Option>
```

where the bounds are arranged `([minx, maxx], [miny, maxy])`. As of now I don't have support for `xsize, ysize`, though that could be added if needed.

**Comment by matthewhanson** [comment]
Thanks Pete, it's fine with just the bounds, I will test this out today.

**Comment by matthewhanson** [comment]
I tested this out.   For one thing, the bounds you provide will be 0.5 pixel off, because p2grid uses that top left point as the center of the top left pixel.    Not a huge deal, but can be a bit confusing.

Running p2g on a bunch of lidar tiles with the new bounds option I get an error on some of them, but not all.

numFiles 1
[0,499]
[0,499]
0. file size: 18000000
findFileNum() error
OutCoreInterp::update() findFileNum() error!
data_x: 9.52 data_y: -0.39 grid_y: 0 fileNum: -1 open file: 0
PDAL: interp->update() error while processing 


When I remove the bounds option the same pipeline works fine.  I can provide test las if needed.

**Comment by gadomski** [comment]
Yeah, I think that error might have to do with the interaction between the true bounds of the data and the user-provided values — specifically, I think if the user-provided values encompass a larger area than the data bounds, bad things can happen. Part of the reason I want to go dive into p2g to possibly fix that up first.




Thanks for the heads up about the 1/2 pixel offset, that shouldn't be a problem to tweak.

**Comment by abellgithub** [comment]
@gadomski: Is this still a thing?

**Comment by gadomski** [comment]
Issue may (probably?) still exist, but I'm not actively working on it.

**Comment by abellgithub** [comment]
This is now obsolete, as we're no longer supporting p2g and in the next release writers.gdal allows a --bounds option that is essentially the same thing.
