### ISSUE TITLE
Generalize kernel extra options

### ISSUE THREAD

**Issue by abellgithub** [PDAL/PDAL#845]
Right now we have somewhat special handling for command-line stage options in all the kernels, which can lead to things getting missed.  It would be better if it weren't this way if possible.

**Comment by hobu** [comment]
Did this one get added? I thought I remembered seeing some extra options churn a while back.

**Comment by abellgithub** [comment]
It's better.  It's imperfect.  I suppose it can be closed for now and another opened if it seems worthwhile.
