### ISSUE TITLE
Formalize continuous integration testing of plugins

### ISSUE THREAD

**Issue by gadomski** [PDAL/PDAL#851]
This discussion started in #846, but I think it makes sense as its own issue so I've extracted the relevant bits below. The basic gist: we test some, but not all, of our plugins with Travis. Its sort of arbitrary which plugins we test and which we don't. Some plugins (pgpointcloud, p2g, hexer...) have only open-source dependencies and could therefore be easily built on Travis if we chose to. Other plugins (rivlib, ...) depend on proprietary libraries and probably couldn't be built with CI.

The whole thing probably could use some cleanup or formalization — we test these plugins but not these plugins, and here's why.

@gadomski:

> We've been over this ground before, but it seems like we're again bumping up against the "how much effort to we go through to CI the plugins?" This patch doesn't seem too bad (just apt-getting the postegres server and installing pgpointcloud from source) but there's a couple of other plugins that might be a similar level of complexity that we aren't testing (e.g. sqlite, p2g, hexer...).

> I wonder how much pain would we inflict upon ourselves by making a PDAL/PDAL-plugins repository, where we could stash all plugins that we don't CI (e.g. rivlib, mrsid...). Just musing...the seemingly arbitrary way we test some plugins but not others makes my anal-rentitive side twitch a bit :-P...

@chambbj:

> This probably deserves it's own issue/thread, but I tend to agree with testing more plugins if we can. I fear that separating them might lead to neglect. I know that some of the closed plugins are already outdated. This probably settles down some after a formal release, and is certainly mitigated if we set up a corresponding CI configuration for the separate plugins repo.

> If we keep the plugins in PDAL/PDAL, I think we may be able to save some Travis clock cycles by doing the following:

> 1) Pretty sure we no longer need to build cmake and ninja from source. I'm pretty sure this explains the delta between gcc and clang build times.
> 2) Though we lose some granularity, we could combine the optional components ON/OFF tests in the build script for each compiler. This would really just save on machine setup. I'm guessing we could also make sure that if optional components OFF fails, we do not proceed to optional components ON.

> Are these steps alone enough for us to turn on more dependencies? Maybe. PCL without a current distribution will probably always time out. Even with binaries, it likely won't be built the way we need it.

@strk:

> Could it make sense to also build with optimizations turned off ? (-O0)

Looks like @chambbj started on the cmake and ninja stuff in #849.

**Comment by abellgithub** [comment]
On Thu, Mar 26, 2015 at 8:56 AM, Pete Gadomski <notifications@github.com>
wrote:

> This discussion started in #846 <https://github.com/PDAL/PDAL/pull/846>,
> but I think it makes sense as its own issue so I've extracted the relevant
> bits below. The basic gist: we test some, but not all, of our plugins with
> Travis. Its sort of arbitrary which plugins we test and which we don't.
> Some plugins (pgpointcloud, p2g, hexer...) have only open-source
> dependencies and could therefore be easily built on Travis if we chose to.
> Other plugins (rivlib, ...) depend on proprietary libraries and probably
> couldn't be built with CI.
>
At the risk of getting slapped, I'll say "stubs."

-- 
Andrew Bell
andrew.bell.ia@gmail.com

**Comment by gadomski** [comment]
> stubs

For those plugins that depend on proprietary libraries? Sure. My instinct, though, is to quarantine the stubs (and, presumably, the related test mocks) somewhere where Joe Developer doesn't get confused by them.

Stubs are a pretty labor-intensive approach, though, and will only increase our workload as the number of plugins increases, since we'll not only be responsible for keeping plugins up-to-date but the stubs as well.

**Comment by abellgithub** [comment]
On Thu, Mar 26, 2015 at 9:40 AM, Pete Gadomski <notifications@github.com>
wrote:

> stubs
>
> For those plugins that depend on proprietary libraries? Sure. My instinct,
> though, is to quarantine the stubs (and, presumably, the related test
> mocks) somewhere where Joe Developer doesn't get confused by them.
>
Stubs are a pain.  But they serve a purpose for which we now have no answer.

> Stubs are a pretty labor-intensive approach, though, and will only
> increase our workload as the number of plugins increases, since we'll not
> only be responsible for keeping plugins up-to-date but the stubs as well.
>
I'd only mess with the plugins that were troublesome -- mostly proprietary
things or ones that required an unwieldy DB setup.

-- 
Andrew Bell
andrew.bell.ia@gmail.com

**Comment by gadomski** [comment]
Agreed. On the other hand, stubs become necessary only if we want to aim for 100% test coverage for plugins, which is still up in the air I think. If we don't care about 100% plugin test coverage, then we can just see no evil :see_no_evil:.

**Comment by abellgithub** [comment]
On Thu, Mar 26, 2015 at 9:47 AM, Pete Gadomski <notifications@github.com>
wrote:

> Agreed. On the other hand, stubs become necessary only if we want to aim
> for 100% test coverage for plugins, which is still up in the air I think.
> If we don't care about 100% plugin test coverage, then we can just see no
> evil [image: :see_no_evil:].
>
But it's not just about test coverage.  It's also that we (the guys who
work on this all the time), don't even build some of this code most of the
time.  It's nice not to throw code out there that doesn't even build.  CI
is a nice place to make sure that you get BUILD coverage.

-- 
Andrew Bell
andrew.bell.ia@gmail.com

**Comment by gadomski** [comment]
Fair point. My takeaway, then, is that we should push for 100% build coverage on Travis, recognizing that:

1. We will have to stub some proprietary libraries
2. We may not have unit tests for everything, but at least we'll be building

Some possible downsides:

1. Travis tests take longer (too long?) due to additional dependency install
2. Stubs are brittle — upstream dependencies may change, requiring updating our stubs, etc

Seems like the Travis dependency problem *could* potentially be lessened if we go down the custom ppa route for PDAL's un-apt-gettable dependencies — any words of warning about investigating that road?

Thoughts? Other input?

**Comment by abellgithub** [comment]
I looked into custom PPAs and thought it was a pain.  But perhaps my patience for such things is unusually low.

On stubs being brittle, I think they're normally not.  We (I) got burnt by the incredible mess and code churn that was in PCL.  All the template mess was an unusual interface, too.  Most people, like us, want stable code and a stable interface.

**Comment by gadomski** [comment]
Point taken on stubs. I'll do a bit of work on the feasibility/necessity of the ppa route, see how many projects we'd need to build from source and how much of a hit that would be.

**Comment by chambbj** [comment]
:-1: to stubs. We've been down that road. I found it to be a huge pain.

Travis has talked for quite some time about opening up cached dependencies to open source projects. So far, it is only available to private projects. That would help a fair bit.

PCL is the main plugin I'm concerned with. Maybe it is worth the time and effort to just create the PPA for that.

The other alternative that I see (but know very little about) would be deploying PDAL binaries through successful Travis builds to a service (maybe packagecloud.io). We could then pull these into the independent plugin repos for testing there.

**Comment by gadomski** [comment]
Alright, I'm going to close this issue as the underlying problem is solved. There's still many plugins that need PPA's but I'm slowly chipping away at those, and I don't think this issue needs to be open anymore.

For reference, a rough guide to PPA packaging has been posted to [our wiki](https://github.com/PDAL/PDAL/wiki/Creating-Debian-packages-for-use-in-PDAL's-Travis-CI).
