### ISSUE TITLE
Catch up GeoWave drivers to new plugin architecture

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#855]
The GeoWave plugin doesn't currently build due to changes in how plugin creation and registration have changed.

**Comment by hobu** [comment]
@jwomeara is there any chance you can catch this up to the current (better) plugin interface?

**Comment by jwomeara** [comment]
I'll try to take a look and get it updated by the end of this week.  Sound
good?

**Comment by hobu** [comment]
Sounds good. There's a chance I get to it sooner, and I'll update the ticket if I do.

Thanks

**Comment by jwomeara** [comment]
Is there a particular branch with the new plugin architecture, or is it already checked into master?

**Comment by jwomeara** [comment]
Looks like you beat me to it.  Thanks!
