### ISSUE TITLE
Need a `pdal split` kernel

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#862]
It would be useful to allow a user to `pdal split` via command-line using either `filters.splitter` or `filters.chipper` and then output some sort of uniquely named output with a specified driver.

Maybe it could work something like

`pdal split myfile.las outputdir/ --capacity 1000000 --driver writers.las `

`pdal split myfile.las outputdir/ --edge 100 --driver writers.bpf`

It would then write a bunch of outputdir/myfile-0.las and outputdir/myfile-1.las output with the metadata being forwarded where applicable from the original file.

**Comment by msmitherdc** [comment]
add a `--files N` or something and have it create that many output files

which would just be basically setting capacity to total/N

**Comment by abellgithub** [comment]
The real work with this is altering the writers to be able to do this.  The DB drivers deal with multiple views, but none of the other writers do.  I'm not sure the best way to do this at this point.

**Comment by hobu** [comment]
What about making a "writer.splitter" that is constructed with a writer and some sort of pattern(s) to output. Maybe something like:

```
<?xml version="1.0" encoding="utf-8"?>
<Pipeline version="1.0">
    <Writer type="writers.splitter">
        <Option name="pattern">
            some kind of "filename" or "output" pattern
        </Option>

        <Writer type="writers.las">
            <Option name="metadata">
                <Options/>
              </Option>
            <Option name="filename">
                given by splitter pattern
            </Option>
            <Option name="compression">
                true
            </Option>
            <Option name="format">
                2
            </Option>        
            <Filter type="filters.chipper">
                <Option name="capacity">3000</Option>
                <Reader type="readers.las">
                    <Option name="filename">
                        /Users/hobu/dev/git/pdal/test/data/las/1.2-with-color.las
                    </Option>
                </Reader>
            </Filter>
        </Writer>
    </Writer>
</Pipeline>

```

**Comment by abellgithub** [comment]
You want the output in separate files, rather than organized in a single file?  Is that the point of this?

**Comment by hobu** [comment]
Yeah, for any filter that outputs a PvSet, write that individual PvSet using the given "writer" to a single output. For this `filters.chipper` example, this would be the file cut in to however many 3000pt files are necessary to chip it up.

**Comment by abellgithub** [comment]
Might it be better to provide a single file with an index of some sort?  Seems way easier to handle.   100s of files seem like a PITA.

**Comment by hobu** [comment]
A very common scenario is "Cut this 1 billion point file into 10 100 million point files." or "Cut this file into files that are 1km x 1km." I'm fine with people shooting their appendages off if they choose too small of splits.

Maybe `filters.splitter` or `filters.chipper` outputs a "tileid" as Metadata for the PointView, and something further down the line can choose to do something with it (like write the filename with the id or something). 

Also, maybe this is called MultiWriter or something. I'm not sure.

**Comment by abellgithub** [comment]
Is this OK just as kernel -- as the issue title suggests?  That seems straightforward.  I still think that if we want to provide pipeline support, that will take some more thought.

**Comment by hobu** [comment]
I was thinking it would be a kernel first so we could figure out what people actually want to do and how they want to do it. Going forward, if there's every a MultiWriter, the kernel can then simply use it.

**Comment by abellgithub** [comment]
OK.  I'm good with this.  If we're going to support this directly, we're either going to have to change the internal model or modify a bunch of writers.  I'm not sure which I think is best right now, but perhaps the kernel is the answer and we can put the rest off until it becomes important.

**Comment by abellgithub** [comment]
Addressed by 0dd614538f0d0349e603e1feb8acb202ee25ce0b

**Comment by hobu** [comment]
Need a quick doc on this.

**Comment by abellgithub** [comment]
Already submitted.
