### ISSUE TITLE
64-bit installation puts some files under /usr/lib

### ISSUE THREAD

**Issue by devrimgunduz** [PDAL/PDAL#871]
PDAL install these files under /usr/lib on a 64-bit machine:

 /usr/lib/libpdal_plugin_reader_pgpointcloud.so
   /usr/lib/libpdal_plugin_writer_pgpointcloud.so
   /usr/lib/libpdal_util.so
   /usr/lib/libpdalcpp.so
   /usr/lib/pdal/cmake/PDALConfig.cmake
   /usr/lib/pdal/cmake/PDALConfigVersion.cmake
   /usr/lib/pdal/cmake/PDALTargets-noconfig.cmake
   /usr/lib/pdal/cmake/PDALTargets.cmake

Can you please check?

Thanks!

**Comment by gadomski** [comment]
Can you verify your `CMAKE_INSTALL_PREFIX` with the following command?

```bash
± grep CMAKE_INSTALL_PREFIX build/CMakeCache.txt
CMAKE_INSTALL_PREFIX:PATH=/Users/gadomski/local
```

Adjust the grep as necessary to point to your CMakeCache.txt. If `CMAKE_INSTALL_PREFIX == /usr/lib` then nothing strange is going on.

**Comment by devrimgunduz** [comment]
CMAKE_INSTALL_PREFIX:PATH=/usr

Per:

https://github.com/devrimgunduz/fmach-rpm/blob/master/rpm/redhat/pdal/EL-7/PDAL.spec#L33

Should I change it to something else?

**Comment by gadomski** [comment]
If you'd like to install PDAL with a different prefix, then yes.

If something in PDAL is broken, then please re-open this issue with a description of the problem. Closing as not-an-issue.

**Comment by devrimgunduz** [comment]
Hi,

I think it should be /usr/lib64 on 64-bit machines, right?

**Comment by abellgithub** [comment]
This varies by OS.

http://www.cmake.org/Bug/view.php?id=11964#c25988
http://www.cmake.org/cmake/help/v3.0/module/GNUInstallDirs.html

**Comment by devrimgunduz** [comment]
Hi,

I am not a cmake guy, but I'm seeing some direct references to /usr/lib directory in the code, like

CMAKE_INSTALL_PREFIX}/lib/

for example:
plugins/pgpointcloud/cmake_install.cmake:  if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libpdal_plugin_reader_pgpointcloud.so" AND

Instead, IMHO, it should CMAKE_INSTALL_LIBDIR that we should pass to cmake.

i.e.
-  "${CMAKE_INSTALL_PREFIX}/lib")
+  "${CMAKE_INSTALL_LIBDIR}")

What do you think?

Regards, Devrim

**Comment by abellgithub** [comment]
You can try.  Maybe Pete has some thoughts.  I don't want to change things without hearing from him, but in general I think you're right that things shouldn't be hardcoded in this way.  I'm just not sure on the best proper fix.

**Comment by hobu** [comment]
Proper and judicious use of   CMAKE_INSTALL_LIBDIR is probably the right way to go.

**Comment by devrimgunduz** [comment]
Hi,

I think I found something:

        -D PDAL_LIB_INSTALL_DIR:PATH=%{_lib} \

%{_lib} is an RPM macro that expands to lib64 on 64 bit systems and lib on 32 bit systems. By passing this to cmake, now all .so files are under /usr/lib64 on my Fedora 21 box.

**Comment by devrimgunduz** [comment]
It may be good to add this to build docs.

**Comment by hobu** [comment]
@devrimgunduz I made an attempt to fix this for you for lib64. The cmake config files will continue to install in their existing locations (do other cmake files exists in the location on your platform?)

**Comment by hobu** [comment]
@devrimgunduz did these changes fix your issue?

**Comment by tigerfoot** [comment]
On 1.1.0 release the closing patch is no more in the code ?
Is there any good reason to revert it.

**Comment by hobu** [comment]
Must have been a bad merge. Expect it in 1.2 to be released middle of next month.

**Comment by tigerfoot** [comment]
Thanks @hobu we will polish it during TOSprint !

**Comment by tigerfoot** [comment]
fixed up #1117

**Comment by abellgithub** [comment]
@hobu: Can this be closed?

**Comment by hobu** [comment]
I left it open because CMakeFiles junk sometimes gets installed into `./include` on OSX.
