### ISSUE TITLE
Some .cmake files are installed with make install -- is that ok?

### ISSUE THREAD

**Issue by devrimgunduz** [PDAL/PDAL#873]
Hi,

These 4 files are installed with make install:

PDALConfig.cmake 
PDALConfigVersion.cmake  
PDALTargets.cmake  
PDALTargets-noconfig.cmake

(and they are installed under /usr/lib/, which is another issue.

Are they needed? Otherwise, can we get rid of them?

**Comment by chambbj** [comment]
These are installed so that PDAL is discoverable by other CMake projects using it. Where they are installed is another issue (#871).
