### ISSUE TITLE
Need a readers.ply and writers.ply

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#878]
It'd be really handy to have PLY i/o for PDAL. It should be very simple to implement.

**Comment by chambbj** [comment]
IIRC, we can do this _very_ easily with PCL. Although a native implementation wouldn't be all that bad either.

**Comment by hobu** [comment]
OpenDroneMap wants an easy way to get from PLY -> LAZ

**Comment by abellgithub** [comment]
What's PLY?


On Tue, Apr 14, 2015 at 1:42 PM, Howard Butler <notifications@github.com>
wrote:

> OpenDroneMap wants an easy way to get from PLY -> LAZ
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PDAL/PDAL/issues/878#issuecomment-93013999>.
>



-- 
Andrew Bell
andrew.bell.ia@gmail.com

**Comment by hobu** [comment]
http://w3.impa.br/~diego/software/rply/ might be something to use for read/write. It's MIT and could be dropped into the codebase as-is.

**Comment by c42f** [comment]
rply is pretty solid and lightweight, I use it in displaz.  You get the points through a set of callback interfaces which are invoked when `ply_read` is called.  Unfortunately that means you don't get to control the read loop, so IIRC you can't read less than the whole file at once.

**Comment by gadomski** [comment]
I've started on ply support [on my fork](https://github.com/PDAL/PDAL/compare/master...gadomski:issues/878-ply). I'm using **rply** as suggested. FYI you can short-circuit the read->callback cycle once you've ingested enough points, which avoids reading the whole file into memory (if I'm reading things correctly).

I'm not opening a PR yet because I haven't tested things out enough (especially with big files, binary ply files, and the like) and I don't have a writer yet. Just throwing up a flag that I'm working on this so someone else doesn't duplicate work.

**Comment by abellgithub** [comment]
Wondered whether it's worth using any library for it.  PLY doesn't seem that complicated, even if it is awful.

**Comment by gadomski** [comment]
I generally default to letting other people do the work instead of doing it myself :-)

What's the downside to using a vendored **rply**?

**Comment by abellgithub** [comment]
Maybe none.  Is it everywhere?  I figured it was just one more thing you had to download, install and so on to get things to work, but I probably figured wrong.

**Comment by gadomski** [comment]
In my branch I've just [included rply in the `vendor/` directory](https://github.com/gadomski/PDAL/tree/issues/878-ply/vendor/rply-1.1.3), so you get it when you download PDAL. rply is pretty simple, the meat and potatoes are just a header file and an implementation file, so it doesn't add much weight to the repo as a whole. No new external dependencies.

**Comment by abellgithub** [comment]
Sounds good.  Whining for no reason.
