### ISSUE TITLE
laz-perf missing FindLazperf.cmake

### ISSUE THREAD

**Issue by oscarmartinezrubi** [PDAL/PDAL#880]
Will attempting to compile PDAL with laz-perf support it misses the cmake/modules/FindLazperf.cmake
I found it in previous commits of PDAL and added it myself but somehow it disappeared in the trunk and I guess it should be added again.

**Comment by connormanning** [comment]
How recent is your laz-perf install? Current laz-perf installs its own find module so PDAL's was intentionally removed.

**Comment by oscarmartinezrubi** [comment]
I just installed couple of hours ago...from https://github.com/verma/laz-perf
But I am doing installations without root.
Where does laz-perf install the find module?

**Comment by connormanning** [comment]
I misspoke - it's not actually a find module but a file that registers laz-perf's well-known location with cmake - hard-set at configure time rather than searching possible install paths.  Cmake's lib directory should contain a `lazperf` directory, but if those files couldn't be installed I can see why you'd have issues.

```
~ $ ls /usr/local/lib/cmake/lazperf
lazperf-config.cmake         lazperf-configVersion.cmake
```

**Comment by oscarmartinezrubi** [comment]
They appear in this folder in my case (no root install):

-bash-4.2$ ls /home/oscar/sw/laz-perf/build/lib/cmake/lazperf/
lazperf-config.cmake  lazperf-configVersion.cmake

After installing laz-perf i add this in my init script:

export LD_LIBRARY_PATH="/home/oscar/sw/laz-perf/build/lib:$LD_LIBRARY_PATH"
export CPATH="/home/oscar/sw/laz-perf/build/include:$CPATH"

maybe I am missing some env. variable?

**Comment by connormanning** [comment]
Relevant install rule is [here](https://github.com/verma/laz-perf/blob/master/CMakeLists.txt#L228-L229).  Maybe you can set `CMAKE_BINARY_DIR` explicitly when you run cmake configure?

**Comment by oscarmartinezrubi** [comment]
I do not quite see what you mean. Isn't it more safe to put back the FindLazperf.cmake?
(that is how the issue was fixed for me)

**Comment by hobu** [comment]
We may have to put the FindLazperf.cmake back into the tree, but we don't really want to. CMake says to use *Config.cmake files going forward, and both PDAL and lazperf are new enough that we don't have any legacy to worry about.
