### ISSUE TITLE
PDAL pgpointcloud reader single pcid per table

### ISSUE THREAD

**Issue by oscarmartinezrubi** [PDAL/PDAL#881]
The postgres reader requires the patches in the table to have the same pcid and the table to have been created with PCPATCH(PCID). However, in some cases it is useful to have in the same table different patches with different pcid. So, in that case the creation of the patches table is like:

`CREATE TABLE patches (id SERIAL PRIMARY KEY,pa PCPATCH);`

The pgpointcloud extension functions work ok in that case but the pdal pgpointcloud not, it reports:

PDAL: Unable to fetch pcid with column 'pa' and  table 'patches'

**Comment by hobu** [comment]
Please provide a patch to implement support for this if you are able. When @pramsey did the original implementation, I think this was a hard constraint that now may be gone.

**Comment by JWGmeligMeyling** [comment]
This really should be a documented issue/limitation imho. You simply cant import two pointclouds into a single database due to this problem.

**Comment by hobu** [comment]
ok. We either need a patch to the docs that describe the issue or code that implements what's needed.
