### ISSUE TITLE
ReturnNumber not getting transferred

### ISSUE THREAD

**Issue by strk** [PDAL/PDAL#884]
For some reason the "ReturnNumber" field is not being imported from .las to pgPointCloud.
Other fields are all present in the output.
Adding debugging info in DbWriter::prepared I see:
```
Pushing dimension NumberOfReturns (NumberOfReturns)
Pushing dimension Classification (Classification)
Pushing dimension ScanAngleRank (ScanAngleRank)
Pushing dimension PointSourceId (PointSourceId)
Pushing dimension ReturnNumber (ReturnNumber)
Pushing dimension GpsTime (GpsTime)
Pushing dimension X (X)
Pushing dimension Y (Y)
Pushing dimension Z (Z)
```

**Comment by abellgithub** [comment]
Can you please attach a small sample file and the command you are using?

**Comment by strk** [comment]
http://strk.keybit.net/tmp/test_pdalissue_884.las
http://strk.keybit.net/tmp/import_to_postgis

**Comment by strk** [comment]
Omitting the "output_dims" parameter imports all fields, including "ReturnNumber"

**Comment by strk** [comment]
Note: "ReturnNumber" is the first dimension, when no `output_dims` is given (might be related)

**Comment by abellgithub** [comment]
Can you explain how you are detecting that the dimension is missing?

**Comment by strk** [comment]
I'm using the PC_Summary function of pgPointCloud to inspect the dimensions present in the loaded PcPatch objects.

**Comment by strk** [comment]
OOps, figured. My SQL query was off by one, failing to show the first dimension.
Everything works as expected here. Sorry for the noise.
