### ISSUE TITLE
System Error

### ISSUE THREAD

**Issue by panzhigang** [PDAL/PDAL#885]
I downloaded the package from OSGeo4W, but when I was trying to run it, a system error showed up with "boost_program_options-vc100-mt-1_56.dll is missing from your computer". The dll files in the package are 1.55 version. Is there a way to solve it? Thanks. @chambbj

**Comment by chambbj** [comment]
The PDAL config probably needs to be updated, but you should also be able to run the OSGeo4W installer again and manually select the boost-devel (compile time) and/or boost-libs (runtime) packages, which are v1.56.
