### ISSUE TITLE
Intended semantics of BOX3D?

### ISSUE THREAD

**Issue by mpgerlek** [PDAL/PDAL#897]
```
    BOX3D boxA(0.0, 0.0, 100.0, 100.0);  // a "2D" box
    BOX3D boxB(50.0, 50.0, 3.1, 51.0, 51.0, 3.14);  // a "3D" box, wholly inside boxA
    
    bool aContainsB = boxA.contains(boxB); // returns false??
    bool bContainsA = boxB.contains(boxA); // returns false
    bool aContainsA = boxA.contains(boxA); // returns true
    bool bContainsB = boxB.contains(boxB); // returns true
```

Is this intended behavior?

I expected that `aContainsB` would have been true, but I believe that since a "2D" Box3D has is explicitly constructed to have an invalid Z, the result is actually false.

**Comment by hobu** [comment]
Yes, this is probably busted. I think I've only ever done 2D contains calls in the context of database drivers, so this isn't well tested code.

**Comment by abellgithub** [comment]
I'd vote this as user error.  I just don't think it's defined sufficiently (semantically speaking) to yield proper values.

Perhaps we should disable the 2D ctor?

**Comment by mpgerlek** [comment]
It's arguable either way.

Do you consider a 2D box to be a point or an infinite column?

.mpg

On May 7, 2015, at 4:11 PM, Howard Butler <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes, this is probably busted. I think I've only ever done 2D contains calls in the context of database drivers, so this isn't well tested code.

**Comment by abellgithub** [comment]
Since it's arguable either way, it seems wrong.  Can we just make a BOX2D type or something?

**Comment by mpgerlek** [comment]
'Point2d' would be better?

There's probably a library we can use for this, rather than rolling our own..?

Either way, such a change is liable to have to touch a lot code.

For now I'll just add the test case and put a bit of documentation in there.

.mpg

On May 7, 2015, at 4:14 PM, Andrew Bell <notifications@github.com<mailto:notifications@github.com>> wrote:


Since it's arguable either way, it seems wrong. Can we just make a BOX2D type or something?

**Comment by abellgithub** [comment]
Well, I don't care about the name.

As far as rolling our own, the code is trivial (it's essentially already there, too).
