### ISSUE TITLE
writer.p2g with inputs that restrict data to 0 points doesn't return

### ISSUE THREAD

**Issue by msmitherdc** [PDAL/PDAL#914]
Or takes a very long time. Inputs were a laz file with a numpy filter that eliminated all points (applied a classification filter on classes that didn't exist)

Output looks like 
```
numFiles 1964523185
[0,-2147483648]
[0,-2147483648]
[-1,-2147483648]
[0,-2147483648]
[-2,-2147483648]
[0,-2147483648]
[-3,-2147483648]
[0,-2147483648]
...
```

**Comment by hobu** [comment]
@msmitherdc Can you confirm this is no longer an issue, and the p2g stuff is working as expected?

**Comment by msmitherdc** [comment]
@hobu yes, confirmed.
