### ISSUE TITLE
`pdal translate --count 100 --offset 100`

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#921]
We used to be able to specify `--count 100` and an `--offset 100` options to have a translate operation only translate 100 points instead of the entire file. I no longer see a way to do this. Additionally, we want the same thing for `pdal pipeline` too.

This capability is useful in testing scenarios.

**Comment by abellgithub** [comment]
How about instead we just have a filter/kernel that allows you to cut a file.  Then you can run translate or whatever on the output of that?

**Comment by hobu** [comment]
Works for me as long as you can specify the offset of where to start `cut`'ing
