### ISSUE TITLE
Plugin loading debug environment variable

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#926]
When plugins aren't loading, it's really difficult to figure out what is going on. It would be helpful to have a `PDAL_PLUGIN_DEBUG` environment variable that barfs out plugin loading info so someone could diagnose what might be going on with a plugin name (bad filename, missing dependent .so, etc).

**Comment by abellgithub** [comment]
There is fairly decent logging now if the log level is set to debug.
