### ISSUE TITLE
`pdal tindex` updates

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#940]
- [ ] It needs to be able to multi-thread calls of the `kernels.info` invocations
- [x] It needs to allow you to set `--scale` and `--offset` for output content of `--merge`
- [x] The `--merge` call should take in a `--bbox` or similar in addition to a `--polygon`

**Comment by abellgithub** [comment]
Do you want scale/offset specifically supported, or should we just turn on the extra options stuff for tindex?

**Comment by hobu** [comment]
I think turn on standard extra options stuff.

**Comment by abellgithub** [comment]
Closing for now.
