### ISSUE TITLE
Review PgPointcloud driver performance

### ISSUE THREAD

**Issue by strk** [PDAL/PDAL#942]
A quick look suggested me that the PgPointcloud driver is always fetching the whole data in a pointcloud table rather than just the one selected by a bounding box (I'm assuming that info is passed by PDAL to drivers?). 

Also, the data is fetched after casting to text, which is known to be very slow.
See https://github.com/pgpointcloud/pointcloud/pull/85 for a future alternative.

**Comment by strk** [comment]
@hobu, @pramsey can you confirm the PgPointcloud never applies a bounding box filter ?

**Comment by hobu** [comment]
I think the user is supposed to limit the query by a where clause themselves, no?

**Comment by strk** [comment]
I dunno :) -- does PDAL have no abstraction of "extract a portion of the points in dataset X" ?

**Comment by abellgithub** [comment]
On Thu, Jun 18, 2015 at 11:16 AM, Sandro Santilli <notifications@github.com>
wrote:

> I dunno :) -- does PDAL have no abstraction of "extract a portion of the
> points in dataset X" ?
>
PDAL has a crop filter, but all points will be read and THEN the crop will
occur.  If you want to take advantage of the database's capabilities, you
need to specify a 'WHERE' clause.

-- 
Andrew Bell
andrew.bell.ia@gmail.com

**Comment by strk** [comment]
Is there any plan to abstract that "WHERE" so that it can be specified in the same way for all drivers ?

**Comment by hobu** [comment]
We've thought about it, but we haven't come up with something that equally applies without big performance hits across all the drivers. So far, we've lived with the fact that some drivers have spatial indexing and can do things like limit for bounds, while (most) others can't.

**Comment by strk** [comment]
What has to apply ? It could be an "hint" to the drive about the actual box of interest. The crop filter would pass such box over to the drivers. I'm not sure but I think gstreamer (another "piper") allows for arbitrary "pads"  to pass between elements of the pipe. If both sides implement a "pad", the communication benefit from it. In this case the "crop" filter could expose a "pad" (or generic parameter of some sort) to drivers, and not rely on them to implement it.

**Comment by abellgithub** [comment]
Closing for languishing.  I think this only applies to DB drivers and the only one getting much attention these days is pgpointcloud.  I don't think it makes sense to create a generic solution at this time.
