### ISSUE TITLE
Summary statistics by polygon

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#951]
I don't know whether it should be part of `filters.stats` or something separate, but it is a very common operation to want to be able to compute summary statistics for polygon areas. A number of algorithms start with these kinds of stats. 

I think it is unrealistic for PDAL to support everyone's special statistic, however. Instead, I think we should allow users to specify polygons much like the `filters.attribute` currently works -- given from OGR. 

For each of those polygons, the list of intersecting points is given to a list user-defined Python functions. It would then be the Python function's job to return a JSON tree of "stats" back to the Stage. The `done()` method would collect up these JSON entries and spit them back out on completion.

**Comment by abellgithub** [comment]
This is complete enough for now.  You can now pass multiple geometries to the crop filter which will create a unique PointView for each input geometry.  You can also now add metadata from the programmable filter.

TODO?  Allow JSON for adding metadata in programmable filter.
