### ISSUE TITLE
LasWriter writing to bad stream

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#953]
There's a situation that seems to only manifest on linux where valgrind reports the following when doing:
```valgrind --tool=memcheck /home/gridusr/local/src/PDAL/bin/pdal translate bad-translate.laz foo.laz &> vgrind.txt```

I'm convinced this is some kind of heap corruption issue, as @msmitherdc has seen it under `RelWithDebugInfo` and `Release` builds on a specific machine, but it is possible that the compiler is at fault (gcc 4.8.2) or something else is to blame too. I'm just not sure.

```
==9013== Syscall param write(buf) points to uninitialised byte(s)
==9013==    at 0x39BB60E6E0: __write_nocancel (in /lib64/libpthread-2.12.so)
==9013==    by 0x39BE2BA535: ??? (in /usr/lib64/libstdc++.so.6.0.13)
==9013==    by 0x39BE26BDAE: std::basic_filebuf<char, std::char_traits<char> >::_M_convert_to_external(char*, long) (in /usr/lib64/libstdc++.so.6.0.13)
==9013==    by 0x39BE26BECD: std::basic_filebuf<char, std::char_traits<char> >::overflow(int) (in /usr/lib64/libstdc++.so.6.0.13)
==9013==    by 0x39BE26C61D: std::basic_filebuf<char, std::char_traits<char> >::_M_terminate_output() (in /usr/lib64/libstdc++.so.6.0.13)
==9013==    by 0x39BE26EC61: std::basic_filebuf<char, std::char_traits<char> >::_M_seek(long, std::_Ios_Seekdir, __mbstate_t) (in /usr/lib64/libstdc++.so.6.0.13)
==9013==    by 0x39BE26EF49: std::basic_filebuf<char, std::char_traits<char> >::seekoff(long, std::_Ios_Seekdir, std::_Ios_Openmode) (in /usr/lib64/libstdc++.so.6.0.13)
==9013==    by 0x39BE291020: std::ostream::tellp() (in /usr/lib64/libstdc++.so.6.0.13)
==9013==    by 0x4D3860C: pdal::LasWriter::ready(pdal::BasePointTable&) (LasWriter.cpp:267)
==9013==    by 0x4CE54B9: pdal::Stage::execute(pdal::BasePointTable&) (Stage.cpp:112)
==9013==    by 0x4DB5FB9: pdal::TranslateKernel::execute() (TranslateKernel.cpp:358)
==9013==    by 0x4CA026E: pdal::Kernel::innerRun() (Kernel.cpp:323)
==9013==  Address 0x13a04acc is 252 bytes inside a block of size 8,192 alloc'd
==9013==    at 0x4A07192: operator new[](unsigned long) (vg_replace_malloc.c:363)
==9013==    by 0x39BE26B80B: std::basic_filebuf<char, std::char_traits<char> >::_M_allocate_internal_buffer() (in /usr/lib64/libstdc++.so.6.0.13)
==9013==    by 0x39BE26CCF6: std::basic_filebuf<char, std::char_traits<char> >::open(char const*, std::_Ios_Openmode) (in /usr/lib64/libstdc++.so.6.0.13)
==9013==    by 0x64E2A05: pdal::FileUtils::createFile(std::string const&, bool) (fstream:281)
==9013==    by 0x4D38775: pdal::LasWriter::ready(pdal::BasePointTable&) (LasWriter.cpp:232)
==9013==    by 0x4CE54B9: pdal::Stage::execute(pdal::BasePointTable&) (Stage.cpp:112)
==9013==    by 0x4DB5FB9: pdal::TranslateKernel::execute() (TranslateKernel.cpp:358)
==9013==    by 0x4CA026E: pdal::Kernel::innerRun() (Kernel.cpp:323)
==9013==    by 0x4CA0429: pdal::Kernel::do_execution() (Kernel.cpp:149)
==9013==    by 0x4CA0693: pdal::Kernel::run(int, char const**, std::string const&) (Kernel.cpp:208)
==9013==    by 0x40576B: main (pdal.cpp:246)
```

**Comment by abellgithub** [comment]
Is there a problem?  Or is valgrind just whining?

On Sun, Jul 5, 2015 at 4:04 PM, Howard Butler <notifications@github.com>
wrote:

> There's a situation that seems to only manifest on linux where valgrind
> reports the following when doing:
> valgrind --tool=memcheck /home/gridusr/local/src/PDAL/bin/pdal translate
> bad-translate.laz foo.laz &> vgrind.txt
>
> I'm convinced this is some kind of heap corruption issue, as @msmitherdc
> <https://github.com/msmitherdc> has seen it under RelWithDebugInfo and
> Release builds on a specific machine, but it is possible that the
> compiler is at fault (gcc 4.8.2) or something else is to blame too. I'm
> just not sure.
>
> ```==9013== Syscall param write(buf) points to uninitialised byte(s)
> ==9013== at 0x39BB60E6E0: __write_nocancel (in /lib64/libpthread-2.12.so)
> ==9013== by 0x39BE2BA535: ??? (in /usr/lib64/libstdc++.so.6.0.13)
> ==9013== by 0x39BE26BDAE: std::basic_filebuf >::_M_convert_to_external(char
>
>
>
>
>
>
>
>
>
>
>
>
> *, long) (in /usr/lib64/libstdc++.so.6.0.13) ==9013== by 0x39BE26BECD:
> std::basic_filebuf >::overflow(int) (in /usr/lib64/libstdc++.so.6.0.13)
> ==9013== by 0x39BE26C61D: std::basic_filebuf >::_M_terminate_output() (in
> /usr/lib64/libstdc++.so.6.0.13) ==9013== by 0x39BE26EC61:
> std::basic_filebuf >::_M_seek(long, std::_Ios_Seekdir, __mbstate_t) (in
> /usr/lib64/libstdc++.so.6.0.13) ==9013== by 0x39BE26EF49:
> std::basic_filebuf >::seekoff(long, std::_Ios_Seekdir, std::_Ios_Openmode)
> (in /usr/lib64/libstdc++.so.6.0.13) ==9013== by 0x39BE291020:
> std::ostream::tellp() (in /usr/lib64/libstdc++.so.6.0.13) ==9013== by
> 0x4D3860C: pdal::LasWriter::ready(pdal::BasePointTable&)
> (LasWriter.cpp:267) ==9013== by 0x4CE54B9:
> pdal::Stage::execute(pdal::BasePointTable&) (Stage.cpp:112) ==9013== by
> 0x4DB5FB9: pdal::TranslateKernel::execute() (TranslateKernel.cpp:358)
> ==9013== by 0x4CA026E: pdal::Kernel::innerRun() (Kernel.cpp:323) ==9013==
> Address 0x13a04acc is 252 bytes inside a block of size 8,192 alloc'd
> ==9013== at 0x4A07192: operator new <http://unsigned%20long>
> (vg_replace_malloc.c:363) ==9013== by 0x39BE26B80B: std::basic_filebuf
> >::_M_allocate_internal_buffer() (in /usr/lib64/libstdc++.so.6.0.13)
> ==9013== by 0x39BE26CCF6: std::basic_filebuf >::open(char const*,
> std::_Ios_Openmode) (in /usr/lib64/libstdc++.so.6.0.13)
> ==9013== by 0x64E2A05: pdal::FileUtils::createFile(std::string const&,
> bool) (fstream:281)
> ==9013== by 0x4D38775: pdal::LasWriter::ready(pdal::BasePointTable&)
> (LasWriter.cpp:232)
> ==9013== by 0x4CE54B9: pdal::Stage::execute(pdal::BasePointTable&)
> (Stage.cpp:112)
> ==9013== by 0x4DB5FB9: pdal::TranslateKernel::execute()
> (TranslateKernel.cpp:358)
> ==9013== by 0x4CA026E: pdal::Kernel::innerRun() (Kernel.cpp:323)
> ==9013== by 0x4CA0429: pdal::Kernel::do_execution() (Kernel.cpp:149)
> ==9013== by 0x4CA0693: pdal::Kernel::run(int, char const**, std::string
> const&) (Kernel.cpp:208)
> ==9013== by 0x40576B: main (pdal.cpp:246)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PDAL/PDAL/issues/953>.
>



-- 
Andrew Bell
andrew.bell.ia@gmail.com

**Comment by hobu** [comment]
So the issue here was GDAL's use of --with-libgeotiff=internal. Ultimately the heap was getting corrupted because of libgeotiff usage, and this is what was causing the trouble.
