### ISSUE TITLE
libgeotiff linking protection

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#954]
We need to provide a mechanism to determine if how we are linked against GDAL, and whether or not GDAL is using an internally- or externally-linked libgeotiff. #953 was caused by this issue.

We should 
- [ ] Determine GDAL's libgeotiff link status
- [ ] Report GDAL linkage status in `--version` information
- [ ] Complain if PDAL-necessary libgeotiff symbols in the gdal.so do not resolve

**Comment by abellgithub** [comment]
This is what library versioning is for, right?  Seems like it shouldn't be
our issue.  Seems like GDAL is busted or trying to do something very
strange.  Maybe I don't get it.

On Mon, Jul 6, 2015 at 8:42 AM, Howard Butler <notifications@github.com>
wrote:

> We need to provide a mechanism to determine if how we are linked against
> GDAL, and whether or not GDAL is using an internally- or externally-linked
> libgeotiff. #953 <https://github.com/PDAL/PDAL/issues/953> was caused by
> this issue.
>
> We should
>
>    -  Determine GDAL's libgeotiff link status
>    -  Report GDAL linkage status in --version information
>    -  Complain if PDAL-necessary libgeotiff symbols in the gdal.so do not
>    resolve
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PDAL/PDAL/issues/954>.
>



-- 
Andrew Bell
andrew.bell.ia@gmail.com

**Comment by hobu** [comment]
Yes GDAL is busted. Especially older versions of GDAL. It might be that all of the libgeotiff symbols are now renamed when GDAL does a `--with-libgeotiff=internal` link nowadays. We need to do the research to figure out what is going on to protect our users from suffering heap corruption and a bunch of other nasty stuff that can result when GDAL has internal libgeotiff and we externally link a different libgeotiff.

**Comment by abellgithub** [comment]
Here's what I understand at this point...

1) libtiff and libgeotiff are both handled equivalently in GDAL, but are handled separately (you can chose to rename/include the symbols from both libraries)
2) whether the lib[geo]tiff code is included into GDAL depends on the "internal" settings at configure time
3) Whether symbols get renamed or not is a separate issue from whether the internal option is set -- you can set "internal" and not rename symbols.  You need to set another config option to rename symbols.
4) Even if symbols are not renamed, there shouldn't be problems IF the ABI of the libraries aren't violated.

Given all this, I'm not sure what the recommendation should be.  The bottom line is that if your tiff/geotiff library that you've compiled separately is the same as the one you included with GDAL, there should be no problem.  We can detect whether the tiff/geotiff symbols are defined in the GDAL library unrenamed and ask people to confirm library versions of tiff/geotiff, I suppose.  Is this what we want?

**Comment by hobu** [comment]
We'll start on this again if it is an issue.
