### ISSUE TITLE
GpsTime ambiguous

### ISSUE THREAD

**Issue by abellgithub** [PDAL/PDAL#960]
The dimension GpsTime is ambiguous.  LAS, for example, has two different meanings for GPS time (GPS week time and GPS adjusted time).  Other formats may give different meaning to GPS time.  This makes merging data that uses the GpsTime dimension error-prone.

**Comment by abellgithub** [comment]
Lack of interest from anyone actually using the data.

**Comment by guyanf** [comment]
> The dimension GpsTime is ambiguous. LAS, for example, has two different meanings for GPS time (GPS week time and GPS adjusted time). Other formats may give different meaning to GPS time. This makes merging data that uses the GpsTime dimension error-prone.

How can I do? When I want to merge las files.
Change the GPS time first?
