### ISSUE TITLE
Add omni kernel (was "Add colorization kernel")

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#962]
It would be handy to be able to specify

`pdal color --input myfile.las --raster myfile.tif --output output.las`

to drive the `filters.colorization` filter.

**Comment by abellgithub** [comment]
Seems like we could just do something like:

`pdal filter -filter=filters.colorization --filters.colorization.raster myfile.tif ...`

Maybe this would suffice for other existing kernels?  Would have to think on it.

**Comment by hobu** [comment]
I like this. A kernel that dynamically defines one reader, one filter, and one writer (plus all options being able to be created via command line) would be quite powerful.

**Comment by chambbj** [comment]
#975 created in support of this, but I haven't tried colorization specifically just yet...maybe tomorrow morning.

**Comment by abellgithub** [comment]
@chambbj Can we close this?

**Comment by chambbj** [comment]
@abellgithub Yes, closing.
