### ISSUE TITLE
pdal/laz-perf with oracle very sensitive to offset

### ISSUE THREAD

**Issue by oscarmartinezrubi** [PDAL/PDAL#964]
I just realized how sensitive lazperf compression is in (at least) Oracle. I load 16 laz files (which total size is 366MB) with 16 pdal pipeline runs in two different ways:
 - using the mins of each file as offset values in each XML pdal config -> i get a total size of 700MB
- using the offsets of each file as offset values in each XML pdal config (and they were all set to 0 in all files) -> I get a total size of 2400MB

Is this huge difference normal? 

So, definitively the best choice is to use the mins of each file as offset for pdal/lazperf. 

Is there any reason why I should not do that always?

**Comment by oscarmartinezrubi** [comment]
I just did another run and now in both cases I get 700MB which makes more sense but then I wonder what happened the previous time...it is like the laz-perf compression was not applied for some unknown reason

**Comment by abellgithub** [comment]
Without seeing the pipelines involved, it's going to be difficult to provide feedback.

**Comment by oscarmartinezrubi** [comment]
I can not reproduce the issue, so I am gonna guess that somehow something messed up my environment temporarily and the laz-perf was not used. I am closing the issue until I can reproduce it again. Sorry for the inconveniences
