### ISSUE TITLE
pdal translate trims points on polygon boundary

### ISSUE THREAD

**Issue by abellgithub** [PDAL/PDAL#976]
When --polygon is a rectangle, pdal translate trims points on the boundary.

**Comment by hobu** [comment]
I don't think on the line satisfies the DE-9IM  matrix for GEOSPreparedContains_r, which is what we're currently using.

https://en.wikipedia.org/wiki/DE-9IM

**Comment by abellgithub** [comment]
Agree.  Should we modify or leave alone?

**Comment by hobu** [comment]
change to GEOSPreparedOverlaps_r?

**Comment by abellgithub** [comment]
Would make behavior consistent with --bounds, I think.

**Comment by hobu** [comment]
:+1: to that then.

**Comment by abellgithub** [comment]
Covers is the correct spatial relation.
