### ISSUE TITLE
PointView::layout()

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#979]
It would be really convenient, especially as an implementer of readers, to have direct access to the current layout in read() rather than it being hidden behind a bunch of methods. Is there a rationale for not having it accessible, even as const?

**Comment by abellgithub** [comment]
On Mon, Aug 24, 2015 at 4:59 PM, Howard Butler <notifications@github.com>
wrote:

> It would be really convenient, especially as an implementer of readers, to
> have direct access to the current layout in read() rather than it being
> hidden behind a bunch of methods. Is there a rationale for not having it
> accessible, even as const?
>

Functions allow changes in implementation.  dimTypes() should give you
everything.  I'd have to see what you're trying to do to provide advice.

-- 
Andrew Bell
andrew.bell.ia@gmail.com
