### ISSUE TITLE
pdal-config includes and libs is empty

### ISSUE THREAD

**Issue by wenzeslaus** [PDAL/PDAL#984]
I'm not getting anything from:

    pdal-config --includes
    pdal-config --libs

`pdal-config` contains:

    echo $LIBS
    echo ${INCLUDES}

which is what's in `pdal-config.in`. The libraries are never defined. It starts to work when I add them manually (obviously):

    INCLUDES="-I/pdal/intall/dir/include/"
    LIBS="-L/pdal/intall/dir/lib/ -lpdalcpp -lpdal_util -lstdc++"

I've no idea what to look for with CMake.

**Comment by hobu** [comment]
This script is busted and need to be fixed.

**Comment by hobu** [comment]
I think we should abandon the `pdal-config` script altogether and only use pdal.pc pkgconfig instead. Otherwise, we're maintaining two tools that do almost the same thing, in slightly different ways. All of the packaging folks are going to want the pkgconfig script anyway.

Thoughts @wenzeslaus?

**Comment by hobu** [comment]
I have pushed a fix to `pdal-config` and added a pkg-config script for PDAL to master

**Comment by wenzeslaus** [comment]
Thanks, it works now but I have to test it more. I remember I had to add also `-lpdal_util` and `-std=c++11` to `-lpdalcpp` to make it compile.

Sorry for not responding earlier. GRASS GIS `./configure` works well with `pdal-config`, so I'm glad to have it.

**Comment by hobu** [comment]
We had tried to do some symbol export magic so you wouldn't have to `-lpdal_util` in addition to `-lpdalcpp`. This must not be working. We want it to work so that you only link `pdalcpp`, so that's the intention anyway.

**Comment by abellgithub** [comment]
Wonder when this testing was.  Just fixed the linking stuff a short while ago.  At the least I would need to know the system to debug.

**Comment by hobu** [comment]
I think @wenzeslaus tested just this morning. I also was testing last night with the Python extension and I needed to manually link against `pdal_plang` instead of just `pdalcpp`

**Comment by abellgithub** [comment]
On Thu, Sep 10, 2015 at 10:32 AM, Howard Butler <notifications@github.com>
wrote:

> I think @wenzeslaus <https://github.com/wenzeslaus> tested just this
> morning. I also was testing last night with the Python extension and I
> needed to manually link against pdal_plang instead of just pdalcpp
>

I did nothing about pdal_plang.

-- 
Andrew Bell
andrew.bell.ia@gmail.com

**Comment by wenzeslaus** [comment]
I needed to use `-lpdal_util` and `-lstdc++` (said `-std=c++11` but meant `-lstdc++`) approximately a week ago (approx f27b967). Now it was fine just with `-lpdalcpp` (obtained from `pdal-confg`).

**Comment by hobu** [comment]
> Now it was fine just with -lpdalcpp (obtained from pdal-confg).

oh, great. As for `-stdc++`, I'm not sure what to advertise `pdal-config` with on that one.

**Comment by wenzeslaus** [comment]
> > Now it was fine just with -lpdalcpp (obtained from pdal-confg).
> oh, great. As for -stdc++, I'm not sure what to advertise pdal-config with on that one.

It works without it for me and I checked the actual link command as well:

    c++ -L...grass...lib -Wl,--export-dynamic -Wl,-rpath-link,...grass.../lib \
      -o ...grass...module.../main.o    -lgrass_gproj.7.1.svn -lmoregrasslibs...\
      -lgrass_gis.7.1.svn -lm  -L...pdal-bin/lib -lpdalcpp -lm

(no `-lstdc++` there)
