### ISSUE TITLE
Add support for ROSBAG BAG file generated from Velodyne LiDAR 

### ISSUE THREAD

**Issue by danames** [PDAL/PDAL#994]
We have a Velodyne LiDAR puck that generates a data set using the ROS software. The file format is a Bag format. There is a descripion of rosbag here: http://wiki.ros.org/rosbag and a description of the bag format here: http://wiki.ros.org/Bags. 

It would be very useful if pdal could read this format so we could use pdal to transform the data from BAG into LAS or something more useful. 

Here is a sample BAG file: https://drive.google.com/file/d/0B_kcuJIsJzw-blJqZXdhbFJFcDA/view?usp=sharing

when you open this file in a text editor, there is text in the header that is human readable that describes the file structure. Then it goes binary. 

Hoping someone might be interested in adding this interesting file format. 
- Dan

**Comment by hobu** [comment]
I am currently implementing `readers.gdal` which will read up a raster and all of its bands as a point cloud. This should allow import of pseudo point cloud formats such as BAG via GDAL mechanisms.

**Comment by danames** [comment]
Howard this is great news.  Please let me know if you are able to look at
the ROSBAG with any success.

I'm new enough to point clouds, what do you mean by 'pseudo point clouds'?

**Comment by hobu** [comment]
> I'm new enough to point clouds, what do you mean by 'pseudo point clouds'?

I mean stuff that is really rasters with a regular spacing instead of "randomly" located XY coordinates.  Another example would be Kinect depth field stuff. They are indeed all point clouds, but they could be modeled more efficiently as rasters, especially when they frequently are only XYZI (essentially a 2-band raster).

**Comment by danames** [comment]
OK that makes sense. The more we look at bag, it seems to be a continuous
stream of points collected by the lidar unit and is intended to be
'recorded' from the unit and can them be 'played back' to simulate the
sensor's data stream both of which modes are intended for robotics use. But
I'm hoping we can get it into an LAS file.

**Comment by hobu** [comment]
There should be a `readers.gdal` today or tomorrow in PDAL:master

**Comment by chambbj** [comment]
I don't have any experience with [rosbag](https://github.com/ros/ros_comm/tree/indigo-devel/tools/rosbag_storage) or [pcl_ros](https://github.com/ros-perception/perception_pcl/tree/jade-devel/pcl_ros), but it seems these could be used to arrive at a solution.

[This line](https://github.com/ros-perception/perception_pcl/blob/jade-devel/pcl_ros/tools/bag_to_pcd.cpp#L128) grabs the individual messages from the rosbag as a PCLPointCloud2 object. [PCDtoPDAL](https://github.com/PDAL/PDAL/blob/master/plugins/pcl/PCLConversions.hpp#L66) could be updated to accept PCLPointCloud2, or you could [convert it](http://docs.pointclouds.org/1.7.0/conversions_8h_source.html#l00167) first and just call PCDtoPDAL as-is. After this, PDAL would be able to write the point cloud using any of the supported writers.

I don't know how complex rosbag can be on a per point basis (i.e., the number of dimensions). Going the PCL route would limit you to XYZ, intensity, and RGB.

**Comment by hobu** [comment]
The `readers.gdal` implementation will create a point for each pixel (centered), along with `band-1, band-2, band-3, band-n` dimensions for each band as doubles. Applications will need to know what to do with the bands and which bands are what.

**Comment by hobu** [comment]
#996 provides `readers.gdal` implementation. You can use it like so to read a JPG into an LAS file. Presumably there is some kind of BAG band mapping that can be used too.

```
<?xml version="1.0"?>
<Pipeline version="1.0">
    <Writer type="writers.las">
        <Option name="filename">
            out.las
        </Option>
        <Filter type="filters.ferry">
           <Option name="dimension">
                band-1
                <Options>
                    <Option name="to">
                        Red
                    </Option>
                </Options>
            </Option>
           <Option name="dimension">
                band-2
                <Options>
                    <Option name="to">
                        Green
                    </Option>
                </Options>
            </Option>
           <Option name="dimension">
                band-3
                <Options>
                    <Option name="to">
                        Blue
                    </Option>
                </Options>
            </Option>
        <Reader type="readers.gdal">
            <Option name="filename">
                /Users/hobu/dev/git/pdal/test/data/autzen/autzen.jpg
            </Option>
        </Reader>
    </Filter>
    </Writer>
</Pipeline>
```

**Comment by hobu** [comment]
I incorrectly was assuming BAG == https://marinemetadata.org/references/bag instead of BAG == http://wiki.ros.org/Bags/Format

**Comment by redheli** [comment]
convert ros bag to pcl pcd(http://wiki.ros.org/pcl_ros), then use great PDAL

**Comment by abellgithub** [comment]
@hobu: Is this dead?
